Repository kyma-project/kyma, pull requests merged in 2018-08, with the labels that each got.

#36 [WIP] Modyfing API spec in Application Connector
  components/application-connector/Gopkg.lock
  components/application-connector/internal/metadata/servicedefservice.go
  components/application-connector/internal/metadata/servicedefservice_test.go
Labels: WIP

#105 Docker in docker scripts alignment
  ci.Dockerfile
  installation/scripts/installer-ci-local.sh
Labels: enhancement

#70 Orchestrate versions
  Jenkinsfile
  components/api-controller/Jenkinsfile
  components/application-connector/Jenkinsfile
  components/binding-usage-controller/Jenkinsfile
  components/configurations-generator/Jenkinsfile
  components/connector-service/Jenkinsfile
  components/environments/Jenkinsfile
  components/gateway/Jenkinsfile
  components/helm-broker/Jenkinsfile
  components/installer/Jenkinsfile
  components/istio-webhook/Jenkinsfile
  components/remote-environment-broker/Jenkinsfile
  components/ui-api-layer/Jenkinsfile
  docs/Jenkinsfile
  orchestrator.Jenkinsfile
  tests/acceptance/Jenkinsfile
  tests/api-controller-acceptance-tests/Jenkinsfile
  tests/application-connector-tests/Jenkinsfile
  tests/connector-service-tests/Jenkinsfile
  tests/gateway-tests/Jenkinsfile
  tests/kubeless-test-client/Jenkinsfile
  tests/test-environments/Jenkinsfile
  tests/test-logging-monitoring/Jenkinsfile
  tests/ui-api-layer-acceptance-tests/Jenkinsfile
  tools/alpine-net/Jenkinsfile
  tools/stability-checker/Jenkinsfile
  tools/watch-pods/Jenkinsfile
Labels: enhancement

#177 Change console's nginx user
  resources/core/charts/console/values.yaml
Labels: WIP

#270 Fix raw content links in local deployment of sample service
  docs/kyma/docs/033-gs-sample-service-deployment-to-local.md
Labels: area/documentation, bug

#272 Bump instances-ui and api-layer image versions
  resources/core/charts/service-catalog/charts/instances-ui/Chart.yaml
  resources/core/charts/ui-api/Chart.yaml
Labels: area/service-catalog, bug

#303 Remote Environment Broker: Middleware to propagate from http.Request to osb.Context brokerNamespace
  components/remote-environment-broker/Gopkg.lock
  components/remote-environment-broker/cmd/broker/main.go
  components/remote-environment-broker/internal/broker/automock/broker_mode_service.go
  components/remote-environment-broker/internal/broker/broker.go
  components/remote-environment-broker/internal/broker/catalog.go
  components/remote-environment-broker/internal/broker/middleware.go
  components/remote-environment-broker/internal/broker/middleware_test.go
  components/remote-environment-broker/internal/broker/server.go
  components/remote-environment-broker/internal/config/config.go
  components/remote-environment-broker/internal/mode/mode.go
  components/remote-environment-broker/internal/mode/mode_test.go
  resources/core/charts/remote-environment-broker/templates/deployment.yaml
  resources/core/charts/remote-environment-broker/templates/service-broker.yaml
  resources/core/charts/remote-environment-broker/values.yaml
Labels: area/service-catalog, enhancement

#327 Update console image version
  resources/core/charts/console/values.yaml
Labels: area/console

#326 Optimalisations in generic overrides mechanism in installer component
  components/installer/pkg/installation/controller.go
  components/installer/pkg/overrides/core.go
  components/installer/pkg/overrides/core_test.go
  components/installer/pkg/overrides/global_test.go
  components/installer/pkg/toolkit/installdata-creator.go
Labels: WIP

#305 Change overrides for istio-1.0
  components/installer/pkg/overrides/istio.go
  components/installer/pkg/overrides/istio_test.go
  installation/resources/installer-config.yaml.tpl
Labels: area/service-mesh, enhancement

#308 Added a getting started guide for custom monitoring metrics
  docs/monitoring/docs/030-gs-monitoring-custom-metrics.md
  docs/monitoring/docs/assets/pm-dashboard-1.png
  docs/monitoring/docs/assets/pm-dashboard-2.png
  docs/monitoring/docs/assets/sample-metrics-2.png
  tests/kubeless-test-client/README.md
Labels: area/documentation, area/monitoring

#323 Fix - /v1/events Service returns json as content type text/plain
  components/event-service/internal/events/bus/send.go
  components/event-service/internal/externalapi/errorhandler.go
  components/event-service/internal/externalapi/eventshandler.go
  components/event-service/internal/externalapi/eventshandler_test.go
  components/event-service/internal/httpconsts/httpconsts.go
Labels: area/eventing
