Repository kyma-project/kyma, pull requests merged in 2019-02, with the labels that each got.

#2543 Update Application Registry API spec
  components/application-registry/docs/api/api.yaml
  docs/application-connector/docs/assets/metadataapi.yaml
Labels: area/application-connector, area/documentation, enhancement

#2528 Add support for onlyOnceFlag to helm broker component
  components/helm-broker/internal/broker/automock/instance_storage.go
  components/helm-broker/internal/broker/broker.go
  components/helm-broker/internal/broker/catalog.go
  components/helm-broker/internal/broker/catalog_test.go
  components/helm-broker/internal/broker/fixture_test.go
  components/helm-broker/internal/broker/provision.go
  components/helm-broker/internal/broker/provision_export_test.go
  components/helm-broker/internal/broker/provision_test.go
  components/helm-broker/internal/broker/testdata/TestBundleConversion-with-schemas.golden.json
  components/helm-broker/internal/broker/testdata/TestBundleConversion-without-schemas.golden.json
  components/helm-broker/internal/bundle/form.go
  components/helm-broker/internal/model.go
  components/helm-broker/internal/model_test.go
  components/helm-broker/internal/storage/driver/etcd/driver.go
  components/helm-broker/internal/storage/driver/etcd/entity_instance.go
  components/helm-broker/internal/storage/driver/memory/entity_instance.go
  components/helm-broker/internal/storage/ext.go
Labels: area/service-catalog, enhancement

#2394 Move cluster overrides directly to Helm charts, split installation artifacts
  installation/resources/installer-config-cluster.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
  installation/scripts/installer.sh
  installation/scripts/release-generate-kyma-installer-artifacts.sh
  resources/application-connector/values.yaml
  resources/ark/values.yaml
  resources/cluster-essentials/values.yaml
  resources/core/values.yaml
  resources/dex/values.yaml
  resources/istio-kyma-patch/values.yaml
  resources/istio/values.yaml
  resources/jaeger/values.yaml
  resources/knative/values.yaml
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/prometheus-operator/values.yaml
  resources/service-catalog/values.yaml
  resources/xip-patch/values.yaml
Labels: area/installation, enhancement

#2553 Bump helm-broker component version
  resources/core/values.yaml
Labels: area/service-catalog, enhancement

#2486 Update cluster roles with SelfSubjectRulesReview
  resources/core/charts/cluster-users/templates/rbac-roles.yaml
Labels: area/console

#2559 Improve naming for event-bus tracing
  resources/core/charts/event-bus/charts/publish/values.yaml
  resources/core/charts/event-bus/charts/push/templates/deployment.yaml
  resources/core/charts/event-bus/charts/push/values.yaml
Labels: area/eventing, area/tracing

#2556 Move the Application Broker documentation to the Application Connector topic
  docs/application-connector/docs/02-01-application-connector.md
  docs/application-connector/docs/02-04-application-broker.md
  docs/application-connector/docs/06-03-event-activation.md
  docs/application-connector/docs/06-04-tokenrequest.md
  docs/application-connector/docs/assets/001-application-connector.svg
  docs/service-brokers/docs/01-03-ab.md
Labels: area/application-connector, area/documentation, enhancement

#2561 Update application-operator image version
  resources/application-connector/values.yaml
Labels: area/application-connector

#2451 Add GraphQL docs
  docs/console/docs/03-02-ui-api-layer.md
  docs/security/docs/03-01-kubecofig-generator.md
  docs/security/docs/03-02-graphql.md
  docs/security/docs/06-01-group.md
  docs/security/docs/06-02-idppreset.md
  docs/security/docs/08-01-update-tls-certificates.md
  docs/security/docs/08-02-manage-static-users.md
  docs/security/docs/08-03-add-connector.md
  resources/core/charts/ui-api/README.md
Labels: area/documentation, area/security

#2558 Bump images after environment renaming
  resources/core/charts/console/values.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
  resources/core/values.yaml
  resources/service-catalog-addons/charts/brokers-ui/Chart.yaml
  resources/service-catalog-addons/charts/catalog-ui/Chart.yaml
  resources/service-catalog-addons/charts/instances-ui/Chart.yaml
Labels: enhancement

#2575 Fix broken diagram links for Application Broker
  docs/application-connector/docs/02-04-application-broker.md
  docs/application-connector/docs/assets/004-AB-architecture.svg
  docs/application-connector/docs/assets/005-AB-API-service-class.svg
  docs/application-connector/docs/assets/006-AB-event-service-class.svg
  docs/service-brokers/docs/assets/020-AB-API-service-class.html
  docs/service-brokers/docs/assets/020-AB-API-service-class.png
  docs/service-brokers/docs/assets/020-AB-event-service-class.html
  docs/service-brokers/docs/assets/020-AB-event-service-class.png
Labels: area/application-connector, area/documentation, bug

#2534 Improve the event-flow-requirements documentation
  docs/event-bus/docs/03-02-event-flow-requirements.md
  docs/event-bus/docs/06-01-subscription.md
  docs/event-bus/docs/assets/event-activation.svg
Labels: area/documentation, area/eventing

#2576 Apply review input for GraphQL docs
  docs/console/docs/03-02-ui-api-layer.md
  docs/security/docs/03-02-graphql.md
Labels: area/documentation, bug

#2573 Add to helm broker removing instance during deprovisioning bundle
  components/helm-broker/internal/broker/automock/extended.go
  components/helm-broker/internal/broker/broker.go
  components/helm-broker/internal/broker/deprovision.go
  components/helm-broker/internal/broker/deprovision_export_test.go
  components/helm-broker/internal/broker/deprovision_test.go
Labels: area/service-catalog, enhancement

#2586 Fix Application Broker architecture diagram link
  docs/application-connector/docs/02-04-application-broker.md
Labels: area/application-connector, area/documentation, bug

#2589 Bump helm-broker component version
  resources/helm-broker/values.yaml
Labels: area/service-catalog, enhancement

#2580 Create a new helm-broker topic for the docs
  components/helm-broker/README.md
  docs/application-connector/docs/02-01-application-connector.md
  docs/docs-build.yaml
  docs/helm-broker/docs.config.json
  docs/helm-broker/docs/01-01-service-brokers.md
  docs/helm-broker/docs/01-02-helm-broker.md
  docs/helm-broker/docs/01-04-azure-broker.md
  docs/helm-broker/docs/01-05-gcp-broker.md
  docs/helm-broker/docs/02-01-helm-broker.md
  docs/helm-broker/docs/05-01-helm-broker.md
  docs/helm-broker/docs/05-02-helm-broker-bundles.md
  docs/helm-broker/docs/05-03-helm-broker-bundles-binding.md
  docs/helm-broker/docs/assets/002-azure-service-broker-class.png
  docs/helm-broker/docs/assets/003-gcp-class.png
  docs/helm-broker/docs/assets/003-gcp-classes.png
  docs/helm-broker/docs/assets/010-helm-registration.html
  docs/helm-broker/docs/assets/010-helm-registration.png
  docs/helm-broker/docs/assets/011-helm-architecture.html
  docs/helm-broker/docs/assets/011-helm-architecture.png
  docs/manifest.yaml
  docs/service-brokers/docs.config.json
  milv.config.yaml
  resources/application-connector/charts/application-broker/README.md
  resources/helm-broker/README.md
Labels: area/documentation, enhancement

#2539 Bump UI Acceptance tests
  resources/core/templates/tests/rbac-ui-acceptance.yaml
  resources/core/templates/tests/test-ui-acceptance.yaml
Labels: area/console, area/service-catalog, enhancement

#2593 Add docs-job.yaml and few fixes
  docs/application-connector/docs/02-01-application-connector.md
  docs/application-connector/docs/02-04-application-broker.md
  docs/helm-broker/docs.config.json
  resources/core/charts/docs/charts/documentation/templates/docs-job.yaml
  resources/core/values.yaml
Labels: area/documentation, bug, enhancement

#2579 Browser cache invalidation improvements (console)
  resources/core/charts/console/values.yaml
  resources/core/charts/docs/charts/content-ui/Chart.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
  resources/service-catalog-addons/charts/brokers-ui/Chart.yaml
  resources/service-catalog-addons/charts/catalog-ui/Chart.yaml
  resources/service-catalog-addons/charts/instances-ui/Chart.yaml
Labels: area/console, bug

#2583 Remove duplicated annotations section in dex chart
  installation/resources/installer-local.yaml
  installation/resources/installer.yaml
  resources/dex/templates/dex-deployment.yaml
Labels: bug

#2624 fix event-bus-publish target URL
  tests/kubeless-integration/test-kubeless.go
Labels: area/eventing, area/serverless

#2465 Add Application header to Connector Service call
  components/ui-api-layer/internal/domain/application/app_service.go
Labels: area/application-connector, enhancement

#2555 Add natss provisioner helm chart
  resources/event-bus/charts/natss-knative-provisioner/Chart.yaml
  resources/event-bus/charts/natss-knative-provisioner/templates/deployment.yaml
  resources/event-bus/charts/natss-knative-provisioner/values.yaml
  resources/event-bus/requirements.yaml
Labels: area/installation, enhancement, wg/knative

#2582 Bump images of console views for modularisation of service-catalog
  resources/core/charts/console/values.yaml
  resources/core/charts/docs/charts/content-ui/Chart.yaml
  resources/service-catalog-addons/charts/brokers-ui/Chart.yaml
  resources/service-catalog-addons/charts/catalog-ui/Chart.yaml
  resources/service-catalog-addons/charts/instances-ui/Chart.yaml
Labels: area/console, enhancement

#2620 Document securing APIs with generated client cert.
  docs/application-connector/docs/02-01-application-connector.md
  docs/application-connector/docs/03-01-ac-security.md
  docs/application-connector/docs/06-01-application.md
  docs/application-connector/docs/08-03-register-manage-services.md
  docs/application-connector/docs/08-04-register-secured-api.md
Labels: area/application-connector, area/documentation, enhancement

#2642 Add publish-knative helm charts
  resources/event-bus/charts/publish-knative/Chart.yaml
  resources/event-bus/charts/publish-knative/templates/_helpers.tpl
  resources/event-bus/charts/publish-knative/templates/deployment.yaml
  resources/event-bus/charts/publish-knative/templates/service-account.yaml
  resources/event-bus/charts/publish-knative/templates/service.yaml
  resources/event-bus/charts/publish-knative/values.yaml
  resources/event-bus/values.yaml
Labels: area/eventing, wg/knative

#2468 Adjust Connector Service chart to API changes
  resources/application-connector/charts/connector-service/templates/deployment.yaml
  resources/application-connector/charts/connector-service/templates/tests/test-acceptance.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/values.yaml
  resources/core/values.yaml
Labels: area/application-connector, enhancement

#2587 Bump ui-api-layer images
  resources/core/values.yaml
Labels: area/console, bug

#2430 Add the Asset Store component
  docs/asset-store/docs.config.json
  docs/asset-store/docs/01-01-asset-store.md
  docs/asset-store/docs/02-01-asset-store.md
  docs/asset-store/docs/03-01-asset-cr-lifecycle.md
  docs/asset-store/docs/03-02-bucket-cr-lifecycle.md
  docs/asset-store/docs/03-03-minio-gateway.md
  docs/asset-store/docs/06-01-asset.md
  docs/asset-store/docs/06-02-bucket.md
  docs/asset-store/docs/assets/asset-store-architecture.svg
  docs/asset-store/docs/assets/create-asset.svg
  docs/asset-store/docs/assets/create-bucket.svg
  docs/asset-store/docs/assets/delete-asset.svg
  docs/asset-store/docs/assets/delete-bucket.svg
  docs/asset-store/docs/assets/minio-gateway.svg
  docs/asset-store/docs/assets/minio.svg
  docs/asset-store/docs/assets/modify-asset.svg
  docs/docs-build.yaml
  docs/manifest.yaml
Labels: area/documentation

#2317 Add authorization layer to UI API layer
  components/ui-api-layer/Gopkg.lock
  components/ui-api-layer/Gopkg.toml
  components/ui-api-layer/internal/authn/middleware.go
  components/ui-api-layer/internal/authn/middleware_test.go
  components/ui-api-layer/internal/authn/oidc.go
  components/ui-api-layer/internal/authz/auth.go
  components/ui-api-layer/internal/authz/auth_test.go
  components/ui-api-layer/internal/authz/fixture_test.go
  components/ui-api-layer/internal/authz/rbac.go
  components/ui-api-layer/internal/authz/rbac_test.go
  components/ui-api-layer/internal/domain/root_resolver.go
  components/ui-api-layer/internal/domain/servicecatalog/disabled/resolver.go
  components/ui-api-layer/internal/domain/servicecatalog/servicebinding_resolver.go
  components/ui-api-layer/internal/domain/servicecatalog/servicebinding_resolver_test.go
  components/ui-api-layer/internal/domain/servicecatalog/servicecatalog.go
  components/ui-api-layer/internal/gqlschema/models_gen.go
  components/ui-api-layer/internal/gqlschema/schema.graphql
  components/ui-api-layer/internal/gqlschema/schema_gen.go
  components/ui-api-layer/main.go
  tests/ui-api-layer-acceptance-tests/Gopkg.lock
  tests/ui-api-layer-acceptance-tests/Gopkg.toml
  tests/ui-api-layer-acceptance-tests/README.md
  tests/ui-api-layer-acceptance-tests/internal/domain/authentication/idppreset_authz_test.go
  tests/ui-api-layer-acceptance-tests/internal/domain/authentication/idppreset_common.go
  tests/ui-api-layer-acceptance-tests/internal/domain/authentication/idppreset_test.go
  tests/ui-api-layer-acceptance-tests/internal/graphql/client.go
  tests/ui-api-layer-acceptance-tests/internal/graphql/config.go
Labels: area/console, area/security, enhancement

#2662 Remove type matadata from two docs
  docs/asset-store/docs/01-01-asset-store.md
  docs/asset-store/docs/02-01-asset-store.md
Labels: area/documentation

#2422 Fix installation documentation
  docs/kyma/docs/04-04-gke-installation.md
  docs/kyma/docs/04-05-aks-installation.md
  docs/kyma/docs/04-06-gke-xip.io-domain.md
  docs/kyma/docs/04-07-aks-xip.io-domain.md
  milv.config.yaml
Labels: WIP, area/documentation

#2665 Add further asset store configuration
  resources/core/charts/docs/charts/documentation/templates/docs-job.yaml
  resources/core/values.yaml
Labels: area/documentation

#2678 Fix the ci-gometalinter for event-bus
  components/event-bus/Makefile
Labels: area/ci, area/eventing

#2679 Bump Content UI image
  resources/core/charts/docs/charts/content-ui/Chart.yaml
Labels: area/console, area/documentation, enhancement

#2621 API controller: add API validation - allow one API per service
  components/api-controller/Gopkg.lock
  components/api-controller/Gopkg.toml
  components/api-controller/pkg/apis/gateway.kyma-project.io/meta/v1/types.go
  components/api-controller/pkg/apis/gateway.kyma-project.io/v1alpha2/types.go
  components/api-controller/pkg/controller/v1alpha2/apistatus.go
  components/api-controller/pkg/controller/v1alpha2/controller.go
  components/api-controller/pkg/controller/v1alpha2/controller_test.go
Labels: area/security, area/service-mesh, bug

#2648 Update api-controller accceptance tests
  tests/api-controller-acceptance-tests/Gopkg.lock
  tests/api-controller-acceptance-tests/apicontroller/component_test.go
Labels: area/security, area/service-mesh, bug

#2676 Bump instances-ui image
  resources/service-catalog-addons/charts/instances-ui/Chart.yaml
Labels: area/console, area/service-catalog, bug

#2645 Split Application Connector certificates secret
  resources/application-connector/charts/connector-service/templates/connector-service-app-ca-secret.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/templates/app-ca-crt-secret.yaml
Labels: area/application-connector, enhancement

#2666 Fix broken links in docs
  components/application-broker/cmd/poc-events/findings.md
  components/event-bus/README.md
  docs/application-connector/docs/01-01-application-connector.md
  docs/application-connector/docs/08-04-register-secured-api.md
  docs/asset-store/docs/02-01-asset-store.md
  docs/asset-store/docs/03-01-asset-cr-lifecycle.md
  docs/asset-store/docs/03-02-bucket-cr-lifecycle.md
  docs/asset-store/docs/03-03-minio-gateway.md
  docs/console/docs/03-02-ui-api-layer.md
  docs/event-bus/docs/03-02-event-flow-requirements.md
  docs/helm-broker/docs/05-01-helm-broker.md
  docs/kyma/docs/01-06-how-to-start.md
  docs/kyma/docs/04-02-local-installation-from-release.md
  docs/monitoring/docs/02-01-monitoring.md
  docs/security/docs/01-01-security.md
  docs/service-mesh/docs/03-02-istio-patch.md
  docs/tracing/docs/03-02-jaeger.md
  milv.config.yaml
  resources/ark/README.md
Labels: area/documentation, bug, priority/critical

#2626 Bump API controller and API controller acceptance tests images
  docs/api-gateway/docs/06-01-api.md
  resources/core/values.yaml
Labels: area/security, area/service-mesh, bug

#2637 Add Asset Store chart
  CODEOWNERS
  docs/kyma/docs/04-01-overview.md
  installation/resources/installer-config-local.yaml.tpl
  installation/resources/installer-cr-cluster-xip-io.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  resources/application-connector/charts/application-registry/values.yaml
  resources/assetstore/.helmignore
  resources/assetstore/Chart.yaml
  resources/assetstore/README.md
  resources/assetstore/charts/assetstore-controller-manager/.helmignore
  resources/assetstore/charts/assetstore-controller-manager/Chart.yaml
  resources/assetstore/charts/assetstore-controller-manager/README.md
  resources/assetstore/charts/assetstore-controller-manager/templates/_helpers.tpl
  resources/assetstore/charts/assetstore-controller-manager/templates/cluster-role-binding.yaml
  resources/assetstore/charts/assetstore-controller-manager/templates/cluster-role.yaml
  resources/assetstore/charts/assetstore-controller-manager/templates/service-account.yaml
  resources/assetstore/charts/assetstore-controller-manager/templates/service.yaml
  resources/assetstore/charts/assetstore-controller-manager/templates/statefulset.yaml
  resources/assetstore/charts/assetstore-controller-manager/values.yaml
  resources/assetstore/charts/minio/Chart.yaml
  resources/assetstore/charts/minio/README.md
  resources/assetstore/charts/minio/templates/_helper_create_bucket.txt
  resources/assetstore/charts/minio/templates/_helpers.tpl
  resources/assetstore/charts/minio/templates/configmap.yaml
  resources/assetstore/charts/minio/templates/content-upload-configmap.yaml
  resources/assetstore/charts/minio/templates/content-upload-podpreset.yaml
  resources/assetstore/charts/minio/templates/deployment.yaml
  resources/assetstore/charts/minio/templates/ingress.yaml
  resources/assetstore/charts/minio/templates/networkpolicy.yaml
  resources/assetstore/charts/minio/templates/post-install-create-bucket-job.yaml
  resources/assetstore/charts/minio/templates/pvc.yaml
  resources/assetstore/charts/minio/templates/secrets.yaml
  resources/assetstore/charts/minio/templates/service.yaml
  resources/assetstore/charts/minio/templates/statefulset.yaml
  resources/assetstore/charts/minio/templates/virtualservice.yaml
  resources/assetstore/charts/minio/values.yaml
  resources/assetstore/requirements.yaml
  resources/assetstore/templates/backendmodule.yaml
  resources/assetstore/values.yaml
  resources/cluster-essentials/templates/asset.crd.yaml
  resources/cluster-essentials/templates/bucket.crd.yaml
  resources/core/charts/minio/templates/backendmodule.yaml
  resources/core/charts/minio/templates/configmap.yaml
  resources/core/charts/ui-api/templates/deployment.yaml
Labels: area/documentation, enhancement

#2685 Bump documentation image
  resources/core/values.yaml
Labels: area/documentation, enhancement

#2643 Add instructions on how to secure graphql
  components/ui-api-layer/docs/security.md
Labels: area/documentation, area/security

#2673 Remove unused installation dir
  tools/kyma-installer/kyma.Dockerfile
Labels: area/installation

#2702 Add BC flow information to the AS architecture
  docs/asset-store/docs/02-01-asset-store.md
  docs/asset-store/docs/06-01-asset.md
  docs/asset-store/docs/assets/asset-store-architecture.svg
Labels: area/documentation

#2707 Update the doc image
  resources/core/values.yaml
Labels: area/documentation

#2708 Minor changes in docs
  docs/event-bus/docs/02-01-event-bus.md
Labels: area/documentation

#2709 Kyma docs - fixes and improvements
  docs/event-bus/docs/07-01-cli-reference.md
  docs/kyma/docs/04-04-gke-installation.md
  docs/kyma/docs/04-08-custom-component-installation.md
  docs/kyma/docs/04-10-update.md
  docs/kyma/docs/08-02-sample-service-deployment-to-cluster.md
  docs/kyma/docs/08-04-publish-service-image-and-deploy.md
  docs/security/docs/03-01-kubecofig-generator.md
  docs/service-mesh/docs/03-01-sidecar-proxy-injection.md
Labels: area/documentation, bug

#2711 Update scripts to test AC locally
  tests/application-operator-tests/scripts/run-local-tests.sh
  tests/application-registry-tests/scripts/run-local-tests.sh
  tests/connector-service-tests/scripts/run-local-tests.sh
Labels: area/application-connector, bug

#2714 Change CRD names
  docs/console/docs/06-01-microfrontend.md
  docs/console/docs/06-02-clustermicrofrontend.md
  docs/console/docs/06-03-backendmodule.md
Labels: area/documentation

#2598 Add fluentd to stability checker
  tools/stability-checker/README.md
  tools/stability-checker/deploy/chart/stability-checker/templates/deploy.yaml
  tools/stability-checker/deploy/chart/stability-checker/templates/fluentd.yaml
  tools/stability-checker/deploy/chart/stability-checker/templates/role-binding.yaml
  tools/stability-checker/deploy/chart/stability-checker/templates/role.yaml
  tools/stability-checker/deploy/chart/stability-checker/values.yaml
  tools/stability-checker/internal/notifier/templates.go
Labels: WIP, area/cluster

#2719 Bump stability checker image
  tools/stability-checker/deploy/chart/stability-checker/values.yaml
Labels: area/ci, area/cluster

#2670 Add instances field for ServiceClass and ClusterServiceClass types in UI API
  components/ui-api-layer/Dockerfile
  components/ui-api-layer/Gopkg.lock
  components/ui-api-layer/Gopkg.toml
  components/ui-api-layer/docs/configuration.md
  components/ui-api-layer/internal/domain/k8s/listener/automock/export.go
  components/ui-api-layer/internal/domain/root_resolver.go
  components/ui-api-layer/internal/domain/servicecatalog/clusterserviceclass_resolver.go
  components/ui-api-layer/internal/domain/servicecatalog/clusterserviceclass_resolver_test.go
  components/ui-api-layer/internal/domain/servicecatalog/disabled/resolver.go
  components/ui-api-layer/internal/domain/servicecatalog/servicecatalog.go
  components/ui-api-layer/internal/domain/servicecatalog/serviceclass_resolver.go
  components/ui-api-layer/internal/domain/servicecatalog/serviceclass_resolver_test.go
  components/ui-api-layer/internal/experimental/featuretoggles.go
  components/ui-api-layer/internal/gqlschema/config.yml
  components/ui-api-layer/internal/gqlschema/schema.graphql
  components/ui-api-layer/internal/gqlschema/schema_gen.go
  components/ui-api-layer/internal/module/module.go
  components/ui-api-layer/internal/module/module_test.go
  tests/ui-api-layer-acceptance-tests/Dockerfile
  tests/ui-api-layer-acceptance-tests/README.md
  tests/ui-api-layer-acceptance-tests/internal/domain/servicecatalog/clusterserviceclass_test.go
  tests/ui-api-layer-acceptance-tests/internal/domain/servicecatalog/serviceclass_test.go
  tests/ui-api-layer-acceptance-tests/internal/module/enabled.go
Labels: area/console, enhancement

#2723 Bump UI API Layer with acceptance tests
  resources/core/values.yaml
Labels: area/console, enhancement

#2722 Describe AC payload limits for API definitions
  docs/application-connector/docs/03-06-payload-limits-for-apis.md
Labels: area/application-connector, area/documentation

#2713 Support filter attribute in the package source of the asset store
  components/assetstore-controller-manager/config/crds/assetstore_v1alpha1_asset.yaml
  components/assetstore-controller-manager/pkg/apis/assetstore/v1alpha1/asset_types.go
  components/assetstore-controller-manager/pkg/assethook/automock/http_client.go
  components/assetstore-controller-manager/pkg/assethook/automock/webhook.go
  components/assetstore-controller-manager/pkg/buckethandler/automock/bucket_handler.go
  components/assetstore-controller-manager/pkg/buckethandler/automock/minio_client.go
  components/assetstore-controller-manager/pkg/cleaner/automock/cleaner.go
  components/assetstore-controller-manager/pkg/cleaner/automock/minio_client.go
  components/assetstore-controller-manager/pkg/controller/asset/asset_controller_test.go
  components/assetstore-controller-manager/pkg/controller/asset/asset_pending.go
  components/assetstore-controller-manager/pkg/controller/asset/bucket/automock/lister.go
  components/assetstore-controller-manager/pkg/controller/asset/webhook/automock/mutator.go
  components/assetstore-controller-manager/pkg/controller/asset/webhook/automock/validator.go
  components/assetstore-controller-manager/pkg/loader/automock/loader.go
  components/assetstore-controller-manager/pkg/loader/loader.go
  components/assetstore-controller-manager/pkg/loader/loader_test.go
  components/assetstore-controller-manager/pkg/loader/package_loader.go
  components/assetstore-controller-manager/pkg/loader/package_loader_test.go
  components/assetstore-controller-manager/pkg/loader/single_loader_test.go
  components/assetstore-controller-manager/pkg/loader/testdata/complex.zip
  components/assetstore-controller-manager/pkg/uploader/automock/minio_client.go
  components/assetstore-controller-manager/pkg/uploader/automock/uploader.go
  docs/asset-store/docs/02-01-asset-store.md
  docs/asset-store/docs/06-01-asset.md
Labels: area/documentation, enhancement

#2717 Bump assetstore and docs images
  resources/assetstore/values.yaml
  resources/core/values.yaml
Labels: area/documentation, enhancement

#2663 Remove instance during deprovisioning in application broker
  components/application-broker/internal/broker/automock/operation_storage.go
  components/application-broker/internal/broker/broker.go
  components/application-broker/internal/broker/state.go
  components/application-broker/internal/broker/state_test.go
  components/application-broker/internal/storage/driver/memory/entity_operation.go
  components/application-broker/internal/storage/ext.go
  components/application-broker/internal/storage/testing/operation_test.go
Labels: area/service-catalog

#2734 Check new formatting approach for tables
  docs/security/docs/03-02-graphql.md
Labels: area/documentation, enhancement

#2738 Fix css class conflict for inputs (techne vs. fiori)
  resources/core/charts/console/values.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
Labels: area/console, bug

#2740 Improve AC documentation - architecture / tutorials
  docs/application-connector/docs/02-01-application-connector.md
  docs/application-connector/docs/02-02-connector-service.md
  docs/application-connector/docs/assets/001-application-connector.svg
Labels: area/application-connector, area/documentation

#2664 Implement the GetInfo endpoint for connected applications and clusters
  components/connector-service/cmd/connectorservice/connectorservice.go
  components/connector-service/cmd/connectorservice/options.go
  components/connector-service/internal/clientcontext/extractor.go
  components/connector-service/internal/clientcontext/middlewares/applicationcontextfromsubject.go
  components/connector-service/internal/clientcontext/middlewares/applicationcontextfromsubject_test.go
  components/connector-service/internal/clientcontext/model.go
  components/connector-service/internal/externalapi/apiurlstrategy.go
  components/connector-service/internal/externalapi/apiurlstrrategy_test.go
  components/connector-service/internal/externalapi/csrinfohandler.go
  components/connector-service/internal/externalapi/csrinfohandler_test.go
  components/connector-service/internal/externalapi/externalapi.go
  components/connector-service/internal/externalapi/managementinfohandler.go
  components/connector-service/internal/externalapi/managementinfohandler_test.go
  components/connector-service/internal/externalapi/middlewares/runtimeurls.go
  components/connector-service/internal/externalapi/middlewares/runtimeurls_test.go
  components/connector-service/internal/externalapi/mocks/APIUrlsGenerator.go
  components/connector-service/internal/externalapi/model.go
  components/connector-service/internal/httphelpers/middlewares.go
  components/connector-service/internal/internalapi/internalapi.go
  tests/connector-service-tests/Gopkg.lock
  tests/connector-service-tests/scripts/run-local-tests.sh
  tests/connector-service-tests/test/apitests/certificatevalidation_test.go
  tests/connector-service-tests/test/apitests/connector_test.go
  tests/connector-service-tests/test/testkit/connectorclient.go
  tests/connector-service-tests/test/testkit/model.go
  tests/connector-service-tests/test/testkit/securedconnectorclient.go
Labels: area/application-connector, enhancement

#2619 E2e test restore backup
  tests/end-to-end/backup-restore-test/Dockerfile
  tests/end-to-end/backup-restore-test/Gopkg.lock
  tests/end-to-end/backup-restore-test/Gopkg.toml
  tests/end-to-end/backup-restore-test/Makefile
  tests/end-to-end/backup-restore-test/backup-restore.md
  tests/end-to-end/backup-restore-test/before-commit.sh
  tests/end-to-end/backup-restore-test/deploy/chart/backup-test/.helmignore
  tests/end-to-end/backup-restore-test/deploy/chart/backup-test/Chart.yaml
  tests/end-to-end/backup-restore-test/deploy/chart/backup-test/templates/test/_helpers.tpl
  tests/end-to-end/backup-restore-test/deploy/chart/backup-test/templates/test/test-backup.yaml
  tests/end-to-end/backup-restore-test/deploy/chart/backup-test/values.yaml
  tests/end-to-end/backup-restore-test/entrypoint.sh
  tests/end-to-end/backup-restore-test/restore/Gopkg.lock
  tests/end-to-end/backup-restore-test/restore/Gopkg.toml
  tests/end-to-end/backup-restore-test/restore/assertions.go
  tests/end-to-end/backup-restore-test/restore/function.yaml
  tests/end-to-end/backup-restore-test/restore/k8s.go
  tests/end-to-end/backup-restore-test/restore/os.go
  tests/end-to-end/backup-restore-test/restore/restore_cluster_backup_test.go
  tests/end-to-end/backup-restore-test/restore/test.goconvey
  tests/end-to-end/backup-restore-test/restore/utilities.go
Labels: area/installation

#2737 Adjust Jaeger documentation
  docs/tracing/docs/03-02-jaeger.md
Labels: area/documentation

#2748 Bump application broker image
  resources/application-connector/values.yaml
Labels: area/service-catalog

#2741 Fix failed governance jobs issues
  docs/service-brokers/helm-broker-service-classes/redis/docs/overview.md
  milv.config.yaml
Labels: area/documentation

#2724 Add security section to documentation overview in ui-api-layer
  components/ui-api-layer/README.md
  components/ui-api-layer/docs/README.md
  components/ui-api-layer/docs/configuration.md
Labels: area/documentation

#2754 Update dead links
  README.md
  docs/kyma/docs/01-06-how-to-start.md
Labels: area/documentation

#2683 Chart and image bump for getInfo
  resources/application-connector/charts/connector-service/templates/deployment.yaml
  resources/application-connector/charts/connector-service/templates/ingress.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#2743 JWT token authentication in configurations-generator
  components/configurations-generator/Gopkg.lock
  components/configurations-generator/Gopkg.toml
  components/configurations-generator/README.md
  components/configurations-generator/cmd/generator/main.go
  components/configurations-generator/internal/authn/middleware.go
  components/configurations-generator/internal/authn/middleware_test.go
  components/configurations-generator/internal/authn/oidc.go
Labels: area/service-mesh, enhancement

#2761 Use alerts from monitoring chart
  resources/core/charts/api-controller/templates/deployment.yaml
  resources/core/charts/namespace-controller/templates/4-deployment.yaml
  resources/core/charts/namespace-controller/templates/5-alert-rules.yaml
Labels: area/monitoring

#2690 Introduce configurable expiration time for certificates issued by Connector Service
  components/connector-service/cmd/connectorservice/connectorservice.go
  components/connector-service/cmd/connectorservice/options.go
  components/connector-service/cmd/connectorservice/options_test.go
  components/connector-service/internal/certificates/certificates.go
  components/connector-service/internal/certificates/certificates_test.go
Labels: area/application-connector, enhancement

#2751 Configurations generator remove istio policy
  resources/core/charts/configurations-generator/templates/authentication-policy.yaml
  resources/core/charts/configurations-generator/templates/deployment.yaml
  resources/core/values.yaml
Labels: area/service-mesh, enhancement

#2758 Docs image update
  resources/core/values.yaml
Labels: area/documentation

#2692 Bump Connector Service version
  resources/application-connector/charts/connector-service/templates/deployment.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#2769 Add the 'kyma-project.io/installation` label to Installer resources
  installation/resources/ark-secret.yaml.tpl
  installation/resources/azure-blobstore-secret.yaml.tpl
  installation/resources/azure-crb-for-healthz.yaml
  installation/resources/default-sa-rbac-role.yaml
  installation/resources/etcd-backup-abs-secret.yaml.tpl
  installation/resources/installer-config-cluster.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
  installation/resources/installer-cr-cluster-xip-io.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  installation/resources/installer-local.yaml
  installation/resources/installer.yaml
  installation/resources/release-adder.yaml
  installation/resources/tiller.yaml
  installation/resources/watch-pods.yaml
Labels: area/installation, enhancement

#2721 Kyma installer: add new makefile target "ci-pr" and "ci-master"
  tools/kyma-installer/Makefile
Labels: area/ci

#2764 Client certificate rotation in Connector Service
  components/connector-service/cmd/connectorservice/connectorservice.go
  components/connector-service/cmd/connectorservice/options.go
  components/connector-service/internal/clientcontext/extractor.go
  components/connector-service/internal/clientcontext/extractor_test.go
  components/connector-service/internal/clientcontext/middlewares/applicationcontextfromsubject.go
  components/connector-service/internal/clientcontext/middlewares/applicationcontextfromsubject_test.go
  components/connector-service/internal/clientcontext/middlewares/contextfromsubject.go
  components/connector-service/internal/clientcontext/middlewares/contextfromsubject_test.go
  components/connector-service/internal/clientcontext/model.go
  components/connector-service/internal/externalapi/csrinfohandler.go
  components/connector-service/internal/externalapi/csrinfohandler_test.go
  components/connector-service/internal/externalapi/externalapi.go
  components/connector-service/internal/externalapi/managementinfohandler.go
  components/connector-service/internal/externalapi/managementinfohandler_test.go
  components/connector-service/internal/externalapi/middlewares/tokenresolver.go
  components/connector-service/internal/externalapi/middlewares/tokenresolver_test.go
  components/connector-service/internal/externalapi/signaturehandler.go
  components/connector-service/internal/externalapi/signaturehandler_test.go
  components/connector-service/internal/httphelpers/middlewares.go
  components/connector-service/internal/httphelpers/writerwithstatus.go
  components/connector-service/internal/httphelpers/writerwithstatus_test.go
  components/connector-service/internal/internalapi/internalapi.go
  components/connector-service/internal/internalapi/tokenhandler.go
  components/connector-service/internal/internalapi/tokenhandler_test.go
  components/connector-service/internal/tokens/creator.go
  components/connector-service/internal/tokens/creator_provider.go
  components/connector-service/internal/tokens/creator_test.go
  components/connector-service/internal/tokens/manager.go
  components/connector-service/internal/tokens/manager_provider.go
  components/connector-service/internal/tokens/manager_test.go
  components/connector-service/internal/tokens/mocks/Creator.go
  components/connector-service/internal/tokens/mocks/Manager.go
  components/connector-service/internal/tokens/mocks/Resolver.go
  components/connector-service/internal/tokens/resolver.go
  components/connector-service/internal/tokens/resolver_test.go
  tests/connector-service-tests/test/apitests/connector_test.go
  tests/connector-service-tests/test/testkit/connectorclient.go
  tests/connector-service-tests/test/testkit/model.go
  tests/connector-service-tests/test/testkit/securedconnectorclient.go
Labels: area/application-connector, enhancement

#2781 Update the "Application" CRD document to follow the template
  docs/application-connector/docs/02-01-application-connector.md
  docs/application-connector/docs/06-01-application.md
  docs/application-connector/docs/06-02-apllicationmapping.md
Labels: area/application-connector, area/documentation

#2767 Client certificate rotation chart update
  resources/application-connector/charts/connector-service/templates/deployment.yaml
  resources/application-connector/charts/connector-service/templates/ingress.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#2804 Add FOSSA large badge
  README.md
Labels: area/documentation, enhancement

#2809 Certificate renewal documentation
  docs/application-connector/docs/02-01-application-connector.md
  docs/application-connector/docs/06-01-application.md
  docs/application-connector/docs/08-02-get-client-certificate.md
  docs/application-connector/docs/08-07-renew-client-cert.md
Labels: area/application-connector, area/documentation

#2806 Add namespace parameter for ClusterServiceClass fields in UI API Layer
  components/ui-api-layer/internal/domain/root_resolver.go
  components/ui-api-layer/internal/domain/servicecatalog/automock/instance_lister_by_cluster_service_class.go
  components/ui-api-layer/internal/domain/servicecatalog/clusterserviceclass_resolver.go
  components/ui-api-layer/internal/domain/servicecatalog/clusterserviceclass_resolver_test.go
  components/ui-api-layer/internal/domain/servicecatalog/disabled/resolver.go
  components/ui-api-layer/internal/domain/servicecatalog/servicecatalog.go
  components/ui-api-layer/internal/domain/servicecatalog/serviceinstance_service.go
  components/ui-api-layer/internal/domain/servicecatalog/serviceinstance_service_test.go
  components/ui-api-layer/internal/gqlschema/schema.graphql
  components/ui-api-layer/internal/gqlschema/schema_gen.go
Labels: area/console, enhancement

#2807 Bump UI API Layer
  resources/core/values.yaml
Labels: area/console, enhancement

#2822 fix release names in e2e testing script
  installation/scripts/e2e-testing.sh
Labels: area/ci

#2808 Add ability to skip Connector Service installation
  resources/application-connector/requirements.yaml
Labels: area/application-connector

#2810 Rework Alert Rules chart document
  resources/monitoring/charts/alert-rules/README.md
Labels: area/documentation

#2763 Add logging for Connector Service
  components/connector-service/cmd/connectorservice/connectorservice.go
  components/connector-service/internal/clientcontext/extractor.go
  components/connector-service/internal/clientcontext/extractor_test.go
  components/connector-service/internal/clientcontext/middlewares/applicationcontext.go
  components/connector-service/internal/clientcontext/middlewares/clustercontext.go
  components/connector-service/internal/clientcontext/middlewares/contextfromsubject.go
  components/connector-service/internal/clientcontext/model.go
  components/connector-service/internal/externalapi/csrinfohandler.go
  components/connector-service/internal/externalapi/csrinfohandler_test.go
  components/connector-service/internal/externalapi/managementinfohandler.go
  components/connector-service/internal/externalapi/managementinfohandler_test.go
  components/connector-service/internal/externalapi/middlewares/tokenresolver.go
  components/connector-service/internal/externalapi/signaturehandler.go
  components/connector-service/internal/externalapi/signaturehandler_test.go
  components/connector-service/internal/httphelpers/response.go
  components/connector-service/internal/internalapi/tokenhandler.go
  components/connector-service/internal/internalapi/tokenhandler_test.go
  components/connector-service/internal/logging/contextlogger.go
Labels: area/application-connector, enhancement

#2759 Introduce Asset Upload Service
  CODEOWNERS
  components/asset-upload-service/Dockerfile
  components/asset-upload-service/Gopkg.lock
  components/asset-upload-service/Gopkg.toml
  components/asset-upload-service/Makefile
  components/asset-upload-service/README.md
  components/asset-upload-service/before-commit.sh
  components/asset-upload-service/hack/regenerate-mocks.sh
  components/asset-upload-service/internal/bucket/automock/bucket_client.go
  components/asset-upload-service/internal/bucket/handler.go
  components/asset-upload-service/internal/bucket/handler_test.go
  components/asset-upload-service/internal/configurer/configurer.go
  components/asset-upload-service/internal/configurer/configurer_test.go
  components/asset-upload-service/internal/fileheader/automock/file.go
  components/asset-upload-service/internal/fileheader/automock/file_header.go
  components/asset-upload-service/internal/fileheader/fileheader.go
  components/asset-upload-service/internal/requesthandler/requesthandler.go
  components/asset-upload-service/internal/requesthandler/requesthandler_test.go
  components/asset-upload-service/internal/requesthandler/testdata/sample.txt
  components/asset-upload-service/internal/requesthandler/testdata/sample.yaml
  components/asset-upload-service/internal/uploader/automock/minio_client.go
  components/asset-upload-service/internal/uploader/export_test.go
  components/asset-upload-service/internal/uploader/uploader.go
  components/asset-upload-service/internal/uploader/uploader_test.go
  components/asset-upload-service/main.go
  components/asset-upload-service/pkg/signal/signal.go
  components/ui-api-layer/LICENSE
  docs/asset-store/docs/03-04-asset-upload-service.md
  docs/asset-store/docs/assets/asset-upload-service-swagger.yaml
Labels: area/documentation, enhancement

#2817 Include the event source-id and the event-type-version in the knative channel name
  components/event-bus/cmd/event-bus-publish-knative/handlers/publish.go
  components/event-bus/cmd/event-bus-publish-knative/handlers/publish_test.go
Labels: area/eventing, bug, priority/critical

#2770 Add Asset Upload Service chart
  components/asset-upload-service/README.md
  resources/assetstore/charts/asset-upload-service/.helmignore
  resources/assetstore/charts/asset-upload-service/Chart.yaml
  resources/assetstore/charts/asset-upload-service/templates/_helpers.tpl
  resources/assetstore/charts/asset-upload-service/templates/cluster-role-binding.yaml
  resources/assetstore/charts/asset-upload-service/templates/cluster-role.yaml
  resources/assetstore/charts/asset-upload-service/templates/deployment.yaml
  resources/assetstore/charts/asset-upload-service/templates/service-account.yaml
  resources/assetstore/charts/asset-upload-service/templates/service.yaml
  resources/assetstore/charts/asset-upload-service/templates/virtualservice.yaml
  resources/assetstore/charts/asset-upload-service/values.yaml
  resources/assetstore/requirements.yaml
  resources/assetstore/values.yaml
  resources/core/values.yaml
Labels: area/documentation, enhancement

#2778 Image bump for #2613
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#2845 Update event-bus component apps version
  components/event-bus/docs/knative-subscription-controller-test-resources/manager.yaml
  resources/event-bus/values.yaml
Labels: area/eventing

#2732 Implement GraphQL queries and mutations for ReplicaSets
  components/ui-api-layer/Gopkg.lock
  components/ui-api-layer/internal/domain/k8s/automock/export.go
  components/ui-api-layer/internal/domain/k8s/automock/gql_replica_set_converter.go
  components/ui-api-layer/internal/domain/k8s/automock/replica_set_svc.go
  components/ui-api-layer/internal/domain/k8s/export_test.go
  components/ui-api-layer/internal/domain/k8s/k8s.go
  components/ui-api-layer/internal/domain/k8s/pretty/kind.go
  components/ui-api-layer/internal/domain/k8s/replicaset_converter.go
  components/ui-api-layer/internal/domain/k8s/replicaset_converter_test.go
  components/ui-api-layer/internal/domain/k8s/replicaset_resolver.go
  components/ui-api-layer/internal/domain/k8s/replicaset_resolver_test.go
  components/ui-api-layer/internal/domain/k8s/replicaset_service.go
  components/ui-api-layer/internal/domain/k8s/replicaset_service_test.go
  components/ui-api-layer/internal/domain/k8s/resourcequota_service_test.go
  components/ui-api-layer/internal/domain/root_resolver.go
  components/ui-api-layer/internal/gqlschema/models_gen.go
  components/ui-api-layer/internal/gqlschema/schema.graphql
  components/ui-api-layer/internal/gqlschema/schema_gen.go
  tests/ui-api-layer-acceptance-tests/Gopkg.lock
  tests/ui-api-layer-acceptance-tests/internal/client/client.go
  tests/ui-api-layer-acceptance-tests/internal/domain/k8s/replicaset_test.go
Labels: area/console, enhancement

#2757 New CN value in connector-service
  components/application-operator/charts/application/templates/ingress.yaml
  components/application-operator/cmd/manager/manager.go
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/methods.go
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/methods_test.go
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/types.go
  components/application-operator/pkg/controller/reconciler.go
  components/application-operator/pkg/controller/reconciler_test.go
  components/application-operator/pkg/kymahelm/application/mocks/ReleaseManager.go
  components/application-operator/pkg/kymahelm/application/overrides.go
  components/application-operator/pkg/kymahelm/application/releasemanager.go
  components/application-operator/pkg/kymahelm/application/releasemanager_test.go
  components/connector-service/README.md
  components/connector-service/cmd/connectorservice/connectorservice.go
  components/connector-service/cmd/connectorservice/options.go
  components/connector-service/internal/clientcontext/middlewares/applicationcontext.go
  components/connector-service/internal/clientcontext/middlewares/applicationcontext_test.go
  components/connector-service/internal/clientcontext/middlewares/clustercontext.go
  components/connector-service/internal/clientcontext/middlewares/clustercontext_test.go
  components/connector-service/internal/clientcontext/model.go
  components/connector-service/internal/clientcontext/model_test.go
  components/connector-service/internal/externalapi/externalapi.go
  components/connector-service/internal/externalapi/middlewares/runtimeurls.go
  components/connector-service/internal/externalapi/middlewares/runtimeurls_test.go
  components/connector-service/internal/internalapi/internalapi.go
  tests/connector-service-tests/scripts/run-local-tests.sh
  tests/connector-service-tests/test/apitests/certificatevalidation_test.go
  tests/connector-service-tests/test/apitests/connector_test.go
  tests/connector-service-tests/test/testkit/config.go
  tests/connector-service-tests/test/testkit/connectorclient.go
Labels: area/application-connector, area/documentation, enhancement

#2816 Fix the broker registration tutorial
  docs/service-catalog/docs/08-01-broker-registration.md
Labels: area/documentation, bug

#2783 Add security recommendations for microfrontends
  docs/console/docs/01-01-console.md
  docs/console/docs/03-03-CR-security-guidelines.md
Labels: area/documentation

#2858 Add VNET rules to PostgreSQL documentation
  docs/service-brokers/azure-broker-service-classes/azure-postgresql/v10/postgresql-dbms/docs/plans-details.md
  docs/service-brokers/azure-broker-service-classes/azure-postgresql/v10/postgresql/docs/plans-details.md
  docs/service-brokers/azure-broker-service-classes/azure-postgresql/v9.6/postgresql-dbms/docs/plans-details.md
  docs/service-brokers/azure-broker-service-classes/azure-postgresql/v9.6/postgresql/docs/plans-details.md
Labels: area/documentation, area/service-catalog

#2844 Fix Alert rules for PVC
  resources/monitoring/charts/alert-rules/templates/kyma-rules.yaml
Labels: area/monitoring

#2863 Remove outdated section from Asset Store documentation
  docs/asset-store/docs/03-01-asset-cr-lifecycle.md
Labels: area/documentation, enhancement

#2779 Accept optional placeholders in Connector Service Info URL
  components/connector-service/internal/clientcontext/model.go
  components/connector-service/internal/clientcontext/model_test.go
  components/connector-service/internal/externalapi/csrinfohandler.go
  components/connector-service/internal/externalapi/csrinfohandler_test.go
Labels: area/application-connector, enhancement

#2773 Rename generate-docs script to prepare-content
  docs/Makefile
Labels: area/documentation, enhancement

#2862 Bump docs image
  resources/core/values.yaml
Labels: area/documentation, area/service-catalog

#2827 Use GraphQL querries and mutations for ReplicaSet in Console UI
  resources/core/charts/console/values.yaml
  resources/core/charts/ui-api/templates/cluster-role.yaml
  resources/core/templates/tests/rbac-ui-api-acceptance.yaml
  resources/core/values.yaml
Labels: area/console, enhancement

#2866 Enable Luigi alerts in lambda ui
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
Labels: area/console, enhancement

#2833 Conditional application management
  resources/application-connector/templates/applications-microfrontend.yaml
  resources/application-connector/values.yaml
  resources/core/charts/console/values.yaml
Labels: area/console, enhancement

#2846 Add description of Installation status
  docs/kyma/docs/06-01-installation.md
Labels: area/documentation

#2869 Fix dead links in "Asset Store" CRD docs
  docs/asset-store/docs/06-02-bucket.md
  docs/asset-store/docs/06-04-clusterbucket.md
Labels: area/documentation, bug

#2799 Connectivity Certs Controller implementation
  CODEOWNERS
  components/connectivity-certs-controller/.gitignore
  components/connectivity-certs-controller/Dockerfile
  components/connectivity-certs-controller/Gopkg.lock
  components/connectivity-certs-controller/Gopkg.toml
  components/connectivity-certs-controller/Makefile
  components/connectivity-certs-controller/README.md
  components/connectivity-certs-controller/before-commit.sh
  components/connectivity-certs-controller/cmd/connectivitycertscontroller/connectivitycertscontroller.go
  components/connectivity-certs-controller/cmd/connectivitycertscontroller/options.go
  components/connectivity-certs-controller/hack/boilerplate.go.txt
  components/connectivity-certs-controller/hack/generate-groups.sh
  components/connectivity-certs-controller/hack/update-codegen.sh
  components/connectivity-certs-controller/internal/certificates/csrprovider.go
  components/connectivity-certs-controller/internal/certificates/csrprovider_test.go
  components/connectivity-certs-controller/internal/certificates/mocks/CSRProvider.go
  components/connectivity-certs-controller/internal/certificates/mocks/Preserver.go
  components/connectivity-certs-controller/internal/certificates/model.go
  components/connectivity-certs-controller/internal/certificates/preserver.go
  components/connectivity-certs-controller/internal/certificates/preserver_test.go
  components/connectivity-certs-controller/internal/connectorservice/client.go
  components/connectivity-certs-controller/internal/connectorservice/client_test.go
  components/connectivity-certs-controller/internal/connectorservice/mocks/Client.go
  components/connectivity-certs-controller/internal/connectorservice/model.go
  components/connectivity-certs-controller/internal/controller/certificaterequest/controller.go
  components/connectivity-certs-controller/internal/controller/certificaterequest/controller_test.go
  components/connectivity-certs-controller/internal/controller/certificaterequest/mocks/Client.go
  components/connectivity-certs-controller/internal/secrets/mocks/Manager.go
  components/connectivity-certs-controller/internal/secrets/mocks/Repository.go
  components/connectivity-certs-controller/internal/secrets/repository.go
  components/connectivity-certs-controller/internal/secrets/repository_test.go
  components/connectivity-certs-controller/pkg/apis/apis.go
  components/connectivity-certs-controller/pkg/apis/applicationconnector/v1alpha1/doc.go
  components/connectivity-certs-controller/pkg/apis/applicationconnector/v1alpha1/register.go
  components/connectivity-certs-controller/pkg/apis/applicationconnector/v1alpha1/types.go
  components/connectivity-certs-controller/pkg/apis/applicationconnector/v1alpha1/zz_generated.deepcopy.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/clientset.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/doc.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/fake/clientset_generated.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/fake/doc.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/fake/register.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/scheme/doc.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/scheme/register.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/applicationconnector_client.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/certificaterequest.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/doc.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/fake/doc.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/fake/fake_applicationconnector_client.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/fake/fake_certificaterequest.go
  components/connectivity-certs-controller/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/generated_expansion.go
  components/connectivity-certs-controller/pkg/client/informers/externalversions/applicationconnector/interface.go
  components/connectivity-certs-controller/pkg/client/informers/externalversions/applicationconnector/v1alpha1/certificaterequest.go
  components/connectivity-certs-controller/pkg/client/informers/externalversions/applicationconnector/v1alpha1/interface.go
  components/connectivity-certs-controller/pkg/client/informers/externalversions/factory.go
  components/connectivity-certs-controller/pkg/client/informers/externalversions/generic.go
  components/connectivity-certs-controller/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  components/connectivity-certs-controller/pkg/client/listers/applicationconnector/v1alpha1/certificaterequest.go
  components/connectivity-certs-controller/pkg/client/listers/applicationconnector/v1alpha1/expansion_generated.go
Labels: area/application-connector, enhancement

#2868 Add links to backup documentation
  docs/backup/docs/03-01-backup-configuration.md
  docs/backup/docs/03-02-create-backup.md
  resources/ark/README.md
Labels: area/documentation

#2775 Implement skelton controller that reacts to event activation create and delete
  components/event-bus/Gopkg.lock
  components/event-bus/cmd/event-bus-subscription-controller-knative/cmd/manager/main.go
  components/event-bus/docs/knative-subscription-controller-test-resources/event-activation-controller-object-test.yaml
  components/event-bus/docs/knative-subscription-controller-test-resources/event-activation-example-crd.yaml
  components/event-bus/docs/knative-subscription-controller-test-resources/rbac_role.yaml
  components/event-bus/internal/knative/subscription/controller/add_eventactivation.go
  components/event-bus/internal/knative/subscription/controller/eventactivation/eventactivation_controller.go
  components/event-bus/internal/knative/subscription/controller/eventactivation/eventactivation_test.go
Labels: area/eventing

#2772 Load test migration
  tools/load-test/deploy/chart/load-test/templates/load-test.yaml
  tools/load-test/deploy/chart/load-test/values.yaml
Labels: area/serverless

#2854 Update application client in application connector components
  components/application-operator/charts/application/templates/ingress.yaml
  components/application-operator/pkg/kymahelm/application/releasemanager.go
  components/application-operator/pkg/kymahelm/application/releasemanager_test.go
  components/application-proxy/Gopkg.lock
  components/application-proxy/Gopkg.toml
  components/application-registry/Gopkg.lock
  components/application-registry/Gopkg.toml
  tests/application-operator-tests/Gopkg.lock
  tests/application-operator-tests/Gopkg.toml
  tests/application-registry-tests/Gopkg.lock
  tests/application-registry-tests/Gopkg.toml
  tests/application-registry-tests/test/testkit/k8sresources_check.go
  tests/application-registry-tests/test/testkit/k8sresources_client.go
  tests/connector-service-tests/Gopkg.lock
  tests/connector-service-tests/Gopkg.toml
  tests/connector-service-tests/test/apitests/certificatevalidation_test.go
  tests/connector-service-tests/test/testkit/k8sClient.go
Labels: area/application-connector, enhancement

#2749 New CN support in application-operator - charts
  resources/application-connector/charts/connector-service/README.md
  resources/application-connector/charts/connector-service/templates/deployment.yaml
  resources/application-connector/charts/connector-service/templates/tests/test-acceptance.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector, area/documentation, enhancement

#2880 Update API Spec of Connector Service
  components/connector-service/docs/api/connectorapi.yaml
  docs/application-connector/docs/assets/connectorapi.yaml
Labels: area/application-connector, area/documentation

#2782 Introduce kyma-developer role
  CODEOWNERS
  docs/security/docs/08-02-manage-static-users.md
  resources/core/charts/cluster-users/templates/rbac-roles.yaml
  resources/core/charts/cluster-users/templates/tests/test-cluster-users.yaml
  resources/core/charts/cluster-users/values.yaml
  resources/core/values.yaml
  resources/dex/templates/dex-users-secret.yaml
  tests/cluster-users-test/Dockerfile
  tests/cluster-users-test/Makefile
  tests/cluster-users-test/README.md
  tests/cluster-users-test/kyma-developer-binding.yaml
  tests/cluster-users-test/sar-test.sh
Labels: area/documentation, area/security, enhancement

#2793 Enable xip.io integration by default
  components/xip-patch/utils.sh
  components/xip-patch/xip-patch.sh
Labels: area/service-mesh, enhancement

#2889 Add missing project flag in gke doc
  docs/kyma/docs/04-04-gke-installation.md
Labels: area/documentation

#2864 Rename test monitoring
  CODEOWNERS
  tests/monitoring/Dockerfile
  tests/monitoring/Gopkg.lock
  tests/monitoring/Gopkg.toml
  tests/monitoring/Makefile
  tests/monitoring/README.md
  tests/monitoring/test-lambda-dashboard-requirements.go
  tests/monitoring/test-monitoring.go
  tests/test-logging-monitoring/.gitignore
Labels: area/monitoring

#2893 Use metrics-server instead of retired heapster
  installation/scripts/minikube.ps1
  installation/scripts/minikube.sh
Labels: area/installation, area/monitoring, bug

#2803 Connectivity Certs Controller chart
  installation/resources/installer-config-cluster.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
  resources/application-connector/charts/connectivity-certs-controller/.helmignore
  resources/application-connector/charts/connectivity-certs-controller/Chart.yaml
  resources/application-connector/charts/connectivity-certs-controller/README.md
  resources/application-connector/charts/connectivity-certs-controller/templates/certificate-request.crd.yaml
  resources/application-connector/charts/connectivity-certs-controller/templates/cluster-role-binding.yaml
  resources/application-connector/charts/connectivity-certs-controller/templates/deployment.yaml
  resources/application-connector/charts/connectivity-certs-controller/values.yaml
  resources/application-connector/requirements.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#2882 Update service catalog version
  docs/service-catalog/docs/07-01-cli-reference.md
  resources/service-catalog/charts/catalog/Chart.yaml
  resources/service-catalog/charts/catalog/values.yaml
Labels: area/service-catalog

#2888 Add Knative subscription-controller deployment
  resources/event-bus/charts/subscription-controller-knative/Chart.yaml
  resources/event-bus/charts/subscription-controller-knative/templates/_helpers.tpl
  resources/event-bus/charts/subscription-controller-knative/templates/deployment.yaml
  resources/event-bus/charts/subscription-controller-knative/templates/service-account.yaml
  resources/event-bus/charts/subscription-controller-knative/values.yaml
  resources/event-bus/requirements.yaml
  resources/event-bus/values.yaml
Labels: area/eventing, enhancement, wg/knative

#2912 Define monitoring configuration alerting defaults
  resources/monitoring/charts/alertmanager/values.yaml
Labels: area/installation, area/monitoring
