Repository kyma-project/kyma, pull requests merged in 2019-09, with the labels that each got.

#5508 Bump service-catalog-ui image
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
Labels: area/console, area/documentation, bug

#5513 Fix dead links
  docs/asset-store/06-02-bucket.md
  docs/asset-store/06-04-clusterbucket.md
Labels: area/documentation

#5505 Fix infinite redirect loop after authorisation error
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#5514 Add OAuth2 client creation details
  docs/security/03-06-oauth2-server.md
Labels: area/documentation

#5070 Update codeowners for UI components
  CODEOWNERS
Labels: area/console

#5485 Add Function CR documentation
  docs/serverless/01-01-serverless.md
  docs/serverless/02-01-serverless.md
  docs/serverless/03-01-custom-resources.md
  docs/serverless/03-02-lambda-functions.md
  docs/serverless/03-02-managing-lambdas.md
  docs/serverless/06-01-function.md
Labels: area/documentation

#5420 Bump client-go version to kubernetes1.15.2 in idppresets
  components/idppreset/Gopkg.lock
  components/idppreset/Gopkg.toml
  components/idppreset/pkg/client/clientset/versioned/clientset.go
  components/idppreset/pkg/client/clientset/versioned/fake/clientset_generated.go
  components/idppreset/pkg/client/clientset/versioned/fake/register.go
  components/idppreset/pkg/client/clientset/versioned/scheme/register.go
  components/idppreset/pkg/client/clientset/versioned/typed/authentication/v1alpha1/fake/fake_idppreset.go
  components/idppreset/pkg/client/informers/externalversions/authentication/v1alpha1/idppreset.go
  components/idppreset/pkg/client/informers/externalversions/factory.go
Labels: area/security, security/high

#5523 Fix memory leak in CMS controller
  components/cms-controller-manager/internal/controllers/suite_test.go
  components/cms-controller-manager/internal/webhookconfig/asset_webhook_config_service.go
  components/cms-controller-manager/internal/webhookconfig/asset_webhook_config_service_test.go
  components/cms-controller-manager/internal/webhookconfig/automock/asset_webhook_config_service.go
  components/cms-controller-manager/internal/webhookconfig/automock/indexer.go
  components/cms-controller-manager/internal/webhookconfig/automock/resource_getter.go
  components/cms-controller-manager/main.go
  resources/cms/values.yaml
Labels: area/core-and-supporting, bug, priority/critical

#5527 Fix a typo
  docs/kyma/05-03-overrides.md
Labels: area/documentation, area/installation

#5522 Create a README file for the Compass Runtime Agent
  components/compass-runtime-agent/README.md
Labels: area/application-connector, area/documentation, enhancement

#5482 Show API details
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#5552 Update Compass Runtime Agent Readme
  components/compass-runtime-agent/README.md
Labels: area/documentation

#5544 Improve dex template handling
  resources/dex/README.md
  resources/dex/templates/dex-config-map.yaml
  resources/dex/templates/dex-deployment.yaml
  resources/dex/values.yaml
Labels: area/security

#5553 Change file paths because of changed permissions
  components/xip-patch/certhelper.sh
Labels: area/application-connector, bug

#5558 Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: area/community, enhancement

#5464 Add the notification channels tutorial
  docs/monitoring/08-03-define-alerting-rules.md
  docs/monitoring/08-04-send-notifications.md
  docs/monitoring/assets/alert-notifications.png
  docs/monitoring/assets/integration-settings.png
  milv.config.yaml
  resources/monitoring/charts/alertmanager/README.md
Labels: area/documentation

#5502 Make application description optional
  resources/core/charts/console/values.yaml
Labels: area/console

#5550 Fix Helm Broker documentation where `authorization` is used in the wrong way
  docs/helm-broker/03-03-create-addons-repo.md
  docs/helm-broker/06-01-clusteraddonsconfiguration.md
  docs/helm-broker/06-02-addonsconfiguration.md
  docs/service-catalog/13-02-gcp-broker.md
Labels: area/documentation, area/service-catalog, bug

#5561 Create OWNERS file for service mesh and security
  components/README.md
  components/api-controller/OWNERS
  components/apiserver-proxy/OWNERS
  components/dex-static-user-configurer/OWNERS
  components/iam-kubeconfig-service/OWNERS
  components/istio-kyma-patch/OWNERS
  components/kyma-operator/OWNERS
  components/xip-patch/OWNERS
  installation/OWNERS
  resources/api-gateway/OWNERS
  resources/cluster-essentials/OWNERS
  resources/core/charts/api-controller/OWNERS
  resources/core/charts/apiserver-proxy/OWNERS
  resources/core/charts/cluster-users/OWNERS
  resources/core/charts/gateway/OWNERS
  resources/core/charts/iam-kubeconfig-service/OWNERS
  resources/core/charts/istio-rbac/OWNERS
  resources/dex/OWNERS
  resources/istio-init/OWNERS
  resources/istio-kyma-patch/OWNERS
  resources/istio/OWNERS
  resources/ory/OWNERS
  resources/xip-patch/OWNERS
  tests/integration/api-controller/OWNERS
  tests/integration/apiserver-proxy/OWNERS
  tests/integration/cluster-users/OWNERS
  tests/integration/dex/OWNERS
  tools/kyma-installer/OWNERS
Labels: area/security, area/service-mesh

#5572 Add documentation about S3 addon provider in Helm Broker
  docs/helm-broker/03-03-create-addons-repo.md
Labels: area/documentation, area/service-catalog

#5569 Add override to toggle agent-configuration job
  resources/compass/README.md
  resources/compass/templates/agent-configuration-job.yaml
  resources/compass/values.yaml
Labels: enhancement

#5452 Update client-go and kubernetes package to 12.5, add dynamic informer…
  resources/core/values.yaml
Labels: area/security, security/high

#5557 Fix backup component name from the docs
  docs/backup/04-01-install-velero.md
  installation/resources/velero-secret.yaml.tpl
Labels: bug

#5565 Improve Console Backend Service tests stability - (Cluster)DocsTopics
  resources/core/charts/console-backend-service/templates/tests/test.yaml
  resources/core/values.yaml
  tests/console-backend-service/internal/domain/cms/clusterdocstopic_test.go
  tests/console-backend-service/internal/domain/cms/cms.go
  tests/console-backend-service/internal/domain/servicecatalog/servicecatalog.go
  tests/console-backend-service/internal/domain/servicecatalog/serviceclass_test.go
  tests/console-backend-service/internal/mockice/mockice.go
Labels: area/core-and-supporting, bug, priority/critical, test-failing

#5593 Remove chart details and link to official documentation
  resources/monitoring/charts/alert-rules/README.md
  resources/monitoring/charts/alertmanager/README.md
Labels: area/documentation

#5598 Add a short reference to Velero CRDs
  docs/backup/08-01-create-backup.md
Labels: area/documentation

#5573 Extend addons configurations api with secretRef
  components/console-backend-service/Gopkg.lock
  components/console-backend-service/Gopkg.toml
  components/console-backend-service/internal/domain/root_resolver.go
  components/console-backend-service/internal/domain/servicecatalogaddons/addonsconfiguration_converter.go
  components/console-backend-service/internal/domain/servicecatalogaddons/addonsconfiguration_converter_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/addonsconfiguration_resolver.go
  components/console-backend-service/internal/domain/servicecatalogaddons/addonsconfiguration_resolver_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/addonsconfiguration_service.go
  components/console-backend-service/internal/domain/servicecatalogaddons/addonsconfiguration_service_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/automock/addons_cfg_mutations.go
  components/console-backend-service/internal/domain/servicecatalogaddons/automock/addons_cfg_updater.go
  components/console-backend-service/internal/domain/servicecatalogaddons/automock/cluster_addons_cfg_mutations.go
  components/console-backend-service/internal/domain/servicecatalogaddons/automock/cluster_addons_cfg_updater.go
  components/console-backend-service/internal/domain/servicecatalogaddons/bindableresources_resolver_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/clusteraddonsconfiguration_converter.go
  components/console-backend-service/internal/domain/servicecatalogaddons/clusteraddonsconfiguration_converter_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/clusteraddonsconfiguration_resolver.go
  components/console-backend-service/internal/domain/servicecatalogaddons/clusteraddonsconfiguration_resolver_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/clusteraddonsconfiguration_service.go
  components/console-backend-service/internal/domain/servicecatalogaddons/clusteraddonsconfiguration_service_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/disabled/resolver.go
  components/console-backend-service/internal/domain/servicecatalogaddons/export_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/extractor/addonsconfiguration.go
  components/console-backend-service/internal/domain/servicecatalogaddons/extractor/addonsconfiguration_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/extractor/clusteraddonsconfiguration.go
  components/console-backend-service/internal/domain/servicecatalogaddons/extractor/clusteraddonsconfiguration_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/extractor/servicebindingusage.go
  components/console-backend-service/internal/domain/servicecatalogaddons/extractor/servicebindingusage_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/extractor/usagekind.go
  components/console-backend-service/internal/domain/servicecatalogaddons/extractor/usagekind_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/listener/addonsconfiguration.go
  components/console-backend-service/internal/domain/servicecatalogaddons/listener/clusteraddonsconfiguration.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_converter.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_converter_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_resolver_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_service.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_service_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicecatalogaddons.go
  components/console-backend-service/internal/domain/servicecatalogaddons/usagekind_converter_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/usagekind_resolver_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/usagekind_service.go
  components/console-backend-service/internal/domain/servicecatalogaddons/usagekind_service_test.go
  components/console-backend-service/internal/gqlschema/models_gen.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
Labels: area/service-catalog, enhancement

#5600 Show FQDN of lambda trigger
  resources/core/charts/kubeless/charts/lambdas-ui/templates/deployment.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
Labels: area/console, bug

#5577 Faster and Reliable UI tests
  resources/core/charts/console/templates/test/rbac.yaml
  resources/core/values.yaml
Labels: area/console, enhancement, quality/testability

#5611 Improve Event Bus architecture
  docs/event-bus/02-01-event-bus.md
  docs/event-bus/03-02-event-flow-requirements.md
  docs/event-bus/assets/configure-consume-events.svg
Labels: area/documentation, area/eventing

#5629 Update Application Broker Diagram
  docs/application-connector/assets/004-AB-architecture.svg
Labels: area/documentation, bug

#5620 Fix e2e upgrade tests
  tests/end-to-end/upgrade/main.go
Labels: test-failing

#5551 Add query and subscriptions for namespaces
  components/console-backend-service/docs/configuration.md
  components/console-backend-service/internal/domain/k8s/automock/export.go
  components/console-backend-service/internal/domain/k8s/automock/gql_namespace_converter.go
  components/console-backend-service/internal/domain/k8s/automock/namespace_svc.go
  components/console-backend-service/internal/domain/k8s/export_test.go
  components/console-backend-service/internal/domain/k8s/k8s.go
  components/console-backend-service/internal/domain/k8s/listener/automock/export.go
  components/console-backend-service/internal/domain/k8s/listener/automock/namespace_converter.go
  components/console-backend-service/internal/domain/k8s/listener/namespace.go
  components/console-backend-service/internal/domain/k8s/listener/namespace_test.go
  components/console-backend-service/internal/domain/k8s/namespace_converter.go
  components/console-backend-service/internal/domain/k8s/namespace_converter_test.go
  components/console-backend-service/internal/domain/k8s/namespace_resolver.go
  components/console-backend-service/internal/domain/k8s/namespace_resolver_test.go
  components/console-backend-service/internal/domain/k8s/namespace_service.go
  components/console-backend-service/internal/domain/k8s/namespace_service_test.go
  components/console-backend-service/internal/domain/root_resolver.go
  components/console-backend-service/internal/gqlschema/config.yml
  components/console-backend-service/internal/gqlschema/models_gen.go
  components/console-backend-service/internal/gqlschema/namespace.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
  components/console-backend-service/main.go
  resources/core/charts/console-backend-service/templates/deployment.yaml
  resources/core/charts/console-backend-service/values.yaml
  resources/core/values.yaml
  tests/console-backend-service/internal/domain/k8s/namespace_test.go
Labels: area/console, enhancement

#5604 Compass Connector Oathkeeper integration
  resources/compass/charts/cockpit/templates/configmap.yaml
  resources/compass/charts/connector/templates/certs-setup-job.yaml
  resources/compass/charts/connector/templates/deployment.yaml
  resources/compass/charts/connector/templates/oathkeeper-rule.yaml
  resources/compass/charts/connector/templates/service.yaml
  resources/compass/charts/connector/templates/tests/test-connector.yaml
  resources/compass/charts/connector/values.yaml
  resources/compass/charts/gateway/templates/deployment.yaml
  resources/compass/charts/gateway/templates/gateway-certs-mtls.yaml
  resources/compass/charts/gateway/templates/gateway.yaml
  resources/compass/charts/gateway/templates/service.yaml
  resources/compass/charts/gateway/templates/virtualservice-mtls.yaml
  resources/compass/charts/gateway/templates/virtualservice.yaml
  resources/compass/charts/gateway/values.yaml
  resources/compass/templates/agent-configuration-job.yaml
  resources/compass/templates/test.yaml
  resources/compass/values.yaml
  resources/ory/values.yaml
Labels: area/application-connector, enhancement

#5633 Add a section about Subscription updates to an existing document
  docs/event-bus/03-05-subscription-updates.md
  docs/event-bus/06-01-subscription.md
Labels: area/documentation, area/eventing

#5630 Bump Kubernetes version to 1.14
  CODEOWNERS
  docs/kyma/04-02-local-installation.md
  docs/kyma/04-03-cluster-installation.md
  docs/kyma/04-04-use-your-own-domain.md
  installation/scripts/minikube.ps1
  installation/scripts/minikube.sh
Labels: area/cluster, area/installation, enhancement

#5517 Update NATS ClusterChannelProvisioner to NATS CRD
  components/event-bus/Gopkg.lock
  components/event-bus/Gopkg.toml
  components/event-bus/cmd/event-publish-service/application/application_test.go
  components/event-bus/cmd/event-publish-service/handlers/publish.go
  components/event-bus/cmd/event-publish-service/publisher/publisher.go
  components/event-bus/cmd/event-publish-service/test/fake/publisher.go
  components/event-bus/cmd/event-publish-service/validators/publish_validator.go
  components/event-bus/internal/knative/subscription/controller/subscription/reconcile.go
  components/event-bus/internal/knative/subscription/controller/subscription/reconcile_test.go
  components/event-bus/internal/knative/subscription/opts/opts.go
  components/event-bus/internal/knative/util/kn-eventing.go
  components/event-bus/internal/knative/util/kn-eventing_test.go
  components/event-bus/internal/knative/util/kn-subscription-builder.go
  components/event-bus/pkg/util/util.go
  components/event-bus/pkg/util/util_test.go
Labels: area/eventing

#5658 Unify tables in Kyma docs
  docs/api-gateway/06-01-api.md
  docs/application-connector/02-01-application-connector.md
  docs/application-connector/02-02-connector-service.md
  docs/application-connector/06-01-application.md
  docs/application-connector/06-02-apllicationmapping.md
  docs/application-connector/06-03-event-activation.md
  docs/application-connector/06-04-tokenrequest.md
  docs/backup/05-01-velero.md
  docs/console/06-01-microfrontend.md
  docs/console/06-02-clustermicrofrontend.md
  docs/console/06-03-backendmodule.md
  docs/event-bus/06-01-subscription.md
  docs/helm-broker/03-01-create-addons.md
  docs/helm-broker/06-01-clusteraddonsconfiguration.md
  docs/helm-broker/06-02-addonsconfiguration.md
  docs/kyma/06-01-installation.md
  docs/security/06-01-group.md
  docs/security/06-02-idppreset.md
  docs/serverless/06-01-function.md
  docs/service-catalog/06-01-service-binding-usage.md
  docs/service-catalog/06-02-usage-kind.md
Labels: area/documentation, quality/content

#5661 Update diagram sources in docs
  docs/asset-store/assets/create-bucket.svg
  docs/asset-store/assets/delete-bucket.svg
  docs/event-bus/assets/event-activation.html
  docs/event-bus/assets/event-bus-architecture.html
  docs/event-bus/assets/event-validation.html
  docs/migration-guides/1.3-1.4.md
  docs/serverless/02-01-serverless.md
  docs/serverless/assets/istio.html
  docs/serverless/assets/istio.png
  docs/serverless/assets/istio.svg
  docs/serverless/assets/kyma_connected.html
  docs/serverless/assets/kyma_connected.png
  docs/serverless/assets/lambda_example.html
  docs/serverless/assets/lambda_example.png
  docs/serverless/assets/lambda_example.svg
  docs/serverless/assets/monitoring.html
  docs/serverless/assets/nats.html
  docs/serverless/assets/nats.png
  docs/serverless/assets/nats.svg
  docs/serverless/assets/serverless_general.html
  docs/serverless/assets/serverless_general.png
  docs/serverless/assets/serverless_general.svg
  docs/service-catalog/03-02-provisioning-and-binding.md
  docs/service-catalog/assets/binding.html
  docs/service-catalog/assets/binding.png
  docs/service-catalog/assets/binding.svg
  docs/service-catalog/assets/deprovisioning.html
  docs/service-catalog/assets/deprovisioning.png
  docs/service-catalog/assets/deprovisioning.svg
  docs/service-catalog/assets/provisioning-and-binding.html
  docs/service-catalog/assets/provisioning-and-binding.png
  docs/service-catalog/assets/provisioning-and-binding.svg
  docs/service-catalog/assets/provisioning.html
  docs/service-catalog/assets/provisioning.png
  docs/service-catalog/assets/provisioning.svg
  docs/service-catalog/assets/unbinding.html
  docs/service-catalog/assets/unbinding.png
  docs/service-catalog/assets/unbinding.svg
  docs/service-catalog/assets/usagekind.html
  docs/service-catalog/assets/usagekind.png
  docs/service-catalog/assets/usagekind.svg
  docs/tracing/assets/request-traces.html
  docs/tracing/assets/store-traces.html
  docs/tracing/assets/tracing-architecture.html
Labels: area/documentation

#5651 Change Golang to Go
  components/api-controller/README.md
  components/apiserver-proxy/README.md
  components/application-broker/README.md
  components/asset-metadata-service/README.md
  components/asset-store-controller-manager/README.md
  components/asset-upload-service/README.md
  components/cms-controller-manager/README.md
  components/cms-services/README.md
  components/cms-services/cmd/asyncapi/README.md
  components/console-backend-service/README.md
  components/console-backend-service/docs/configuration.md
  components/iam-kubeconfig-service/README.md
  components/namespace-controller/README.md
  components/service-binding-usage-controller/README.md
  docs/headless-cms/06-01-docstopic.md
  docs/headless-cms/06-02-clusterdocstopic.md
  docs/kyma/08-01-sample-service-deployment-to-local.md
  docs/kyma/08-02-sample-service-deployment-to-cluster.md
  docs/kyma/08-03-local-develop-no-docker.md
  tests/asset-store/README.md
  tests/console-backend-service/README.md
  tests/end-to-end/backup-restore-test/README.md
  tests/end-to-end/upgrade/README.md
  tools/failery/README.md
  tools/load-test/README.md
Labels: area/documentation, quality/content

#5665 Update docs on adding identity providers to Dex
  docs/security/01-01-security.md
  docs/security/08-03-add-connector.md
  resources/dex/README.md
Labels: area/documentation, area/security

#5657 Hydra-maester: fix RBAC
  resources/ory/charts/hydra/charts/hydra-maester/templates/rbac.yaml
Labels: area/security

#5648 Fix default system namespaces list
  components/console-backend-service/main.go
  resources/core/values.yaml
Labels: area/console, bug

#5612 Adding OWNERS file for event-bus and serverless components
  OWNERS_ALIASES
  components/event-bus/OWNERS
  components/function-controller/OWNERS
  components/kubeless-images/OWNERS
  resources/event-bus/OWNERS
  resources/function-controller/OWNERS
  resources/knative-build-init/OWNERS
  resources/knative-build/OWNERS
  resources/knative-eventing/OWNERS
  resources/knative-provisioner-natss/OWNERS
  resources/knative-serving-init/OWNERS
  resources/knative-serving/OWNERS
  resources/nats-streaming/OWNERS
  tests/event-bus/OWNERS
  tests/knative-build/OWNERS
  tests/knative-serving/OWNERS
  tests/kubeless/OWNERS
Labels: area/eventing, area/serverless

#5663 Add documentation for Mercurial protocol in HelmBroker
  docs/helm-broker/03-03-create-addons-repo.md
  resources/helm-broker/values.yaml
Labels: area/documentation, area/service-catalog

#5613 use ko for function-controller development deployment
  components/function-controller/Makefile
  components/function-controller/README.md
  components/function-controller/config/default/manager_image_patch.yaml
  components/function-controller/config/manager/manager.yaml
Labels: area/serverless, quality/devx

#5682 Align monitoring documentation
  docs/monitoring/08-03-define-alerting-rules.md
  docs/monitoring/assets/fired-alert.png
  docs/monitoring/assets/rules-dashboard.png
Labels: area/documentation

#5306 Add Compass documentation to Kyma
  docs/README.md
  docs/compass/01-01-compass.md
  docs/compass/02-01-compass.md
  docs/compass/02-02-components.md
  docs/compass/04-01-compass.md
  docs/compass/assets/architecture.svg
  docs/compass/assets/components.svg
  docs/compass/assets/kyma-mode1.svg
  docs/compass/assets/kyma-mode2.svg
  docs/compass/assets/scenarios.svg
  resources/core/charts/docs/charts/content-ui/templates/docs-components-compass-cdt.yaml
Labels: area/documentation

#5678 Improve service programming model doc
  docs/event-bus/03-02-event-flow-requirements.md
  docs/event-bus/03-03-service-programming-model.md
Labels: area/documentation, area/eventing

#5699 Remove tmp file
  docs/application-connector/tmp.md
Labels: area/documentation, bug

#5703 Remove obsolete line
  docs/application-connector/08-02-get-client-certificate.md
Labels: area/application-connector, area/documentation

#5636 Improve the description of how to provide addons documentation
  docs/helm-broker/03-01-create-addons.md
  docs/helm-broker/03-03-create-addons-repo.md
  docs/helm-broker/03-07-addons-docs.md
Labels: area/documentation, area/service-catalog, enhancement

#5643 Secure compass with JWT and OAuth
  installation/resources/installer-cr-cluster-compass.yaml.tpl
  resources/compass/charts/gateway/templates/oathkeeper-rules.yaml
  resources/compass/charts/gateway/templates/virtualservice-secure.yaml
  resources/compass/charts/gateway/values.yaml
  resources/compass/values.yaml
  resources/dex/templates/dex-virtual-service.yaml
  resources/dex/values.yaml
  resources/ory/charts/oathkeeper/templates/configmap-config.yaml
  resources/ory/templates/virtualservice-hydra.yaml
  resources/ory/values.yaml
Labels: area/security, enhancement

#5686 Update Components list in Kyma docs
  docs/console/01-01-console.md
  docs/console/03-01-uiextensibility.md
  docs/console/06-01-microfrontend.md
  docs/helm-broker/06-01-clusteraddonsconfiguration.md
  docs/kyma/03-01-components.md
Labels: area/documentation, quality/content

#5704 Fix Knative Channel Name issue
  components/event-bus/cmd/event-publish-service/publisher/publisher.go
  components/event-bus/internal/knative/subscription/controller/subscription/reconcile.go
  components/event-bus/internal/knative/subscription/controller/subscription/reconcile_test.go
  components/event-bus/internal/knative/util/kn-eventing.go
  components/event-bus/internal/knative/util/kn-eventing_test.go
Labels: area/eventing

#5526 Upgrade knative eventing chart to 0.8.0
  resources/event-bus/charts/event-publish-service/templates/service-account.yaml
  resources/event-bus/charts/subscription-controller/templates/service-account.yaml
  resources/event-bus/values.yaml
  resources/knative-eventing/Chart.yaml
  resources/knative-eventing/README.md
  resources/knative-eventing/charts/knative-eventing/Chart.yaml
  resources/knative-eventing/charts/knative-eventing/templates/eventing.yaml
  resources/knative-eventing/charts/knative-eventing/templates/post-upgrade-job.yaml
  resources/knative-eventing/charts/knative-eventing/templates/pre-upgrade-job.yaml
  resources/knative-provisioner-natss/Chart.yaml
  resources/knative-provisioner-natss/README.md
  resources/knative-provisioner-natss/charts/knative-provisioner-natss/Chart.yaml
  resources/knative-provisioner-natss/charts/knative-provisioner-natss/templates/deployment.yaml
  resources/knative-provisioner-natss/charts/knative-provisioner-natss/templates/natss.yaml
  resources/knative-provisioner-natss/values.yaml
Labels: area/eventing

#5710 Fix a dead link
  components/application-broker/cmd/poc-events/findings.md
Labels: area/documentation

#5732 Improve function controller documentation
  components/function-controller/README.md
Labels: area/documentation, area/serverless

#5721 Update idppreset - upgrade k8s to 1.15
  components/idppreset/Gopkg.lock
  components/idppreset/Gopkg.toml
  components/idppreset/pkg/apis/authentication/v1alpha1/zz_generated.deepcopy.go
  components/idppreset/pkg/client/clientset/versioned/clientset.go
  components/idppreset/pkg/client/clientset/versioned/fake/clientset_generated.go
  components/idppreset/pkg/client/clientset/versioned/typed/authentication/v1alpha1/authentication_client.go
  components/idppreset/pkg/client/clientset/versioned/typed/authentication/v1alpha1/fake/fake_idppreset.go
  components/idppreset/pkg/client/clientset/versioned/typed/authentication/v1alpha1/idppreset.go
  components/idppreset/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
Labels: WIP

#5696 Create troubleshooting for expired SSL cert
  docs/kyma/10-07-expired-cert.md
Labels: area/documentation, area/security

#5691 Add an overview for monitoring tutorials
  docs/monitoring/01-01-monitoring.md
  docs/monitoring/08-01-overview.md
  docs/monitoring/08-02-observe-application-metrics.md
  docs/monitoring/08-03-create-and-configure-grafana-dashboard.md
  docs/monitoring/08-04-define-alerting-rules.md
  docs/monitoring/08-05-send-notifications.md
  docs/monitoring/assets/fired-alert.png
  docs/monitoring/assets/monitoring-tutorials.svg
  docs/monitoring/assets/rules-dashboard.png
  milv.config.yaml
Labels: area/documentation, area/monitoring, enhancement

#5693 Update dependencies for SBU
  components/service-binding-usage-controller/Gopkg.lock
  components/service-binding-usage-controller/Gopkg.toml
  components/service-binding-usage-controller/cmd/controller/main.go
  components/service-binding-usage-controller/cmd/migration/main.go
  components/service-binding-usage-controller/internal/controller/automock/binding_labels_fetcher.go
  components/service-binding-usage-controller/internal/controller/automock/extends.go
  components/service-binding-usage-controller/internal/controller/controller.go
  components/service-binding-usage-controller/internal/controller/controller_test.go
  components/service-binding-usage-controller/internal/controller/generic_supervisor.go
  components/service-binding-usage-controller/internal/controller/labels_fetcher.go
  components/service-binding-usage-controller/internal/controller/labels_fetcher_test.go
  components/service-binding-usage-controller/internal/controller/pretty/pretty.go
  components/service-binding-usage-controller/internal/controller/usagekind/helpers_test.go
  components/service-binding-usage-controller/pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
  components/service-binding-usage-controller/pkg/apis/settings/v1alpha1/zz_generated.deepcopy.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/clientset.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/fake/clientset_generated.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/fake/register.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/scheme/register.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/typed/servicecatalog/v1alpha1/fake/fake_servicebindingusage.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/typed/servicecatalog/v1alpha1/fake/fake_usagekind.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/typed/servicecatalog/v1alpha1/servicebindingusage.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/typed/servicecatalog/v1alpha1/servicecatalog_client.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/typed/servicecatalog/v1alpha1/usagekind.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/typed/settings/v1alpha1/fake/fake_podpreset.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/typed/settings/v1alpha1/podpreset.go
  components/service-binding-usage-controller/pkg/client/clientset/versioned/typed/settings/v1alpha1/settings_client.go
  components/service-binding-usage-controller/pkg/client/informers/externalversions/factory.go
  components/service-binding-usage-controller/pkg/client/informers/externalversions/generic.go
  components/service-binding-usage-controller/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  components/service-binding-usage-controller/pkg/client/informers/externalversions/servicecatalog/v1alpha1/servicebindingusage.go
  components/service-binding-usage-controller/pkg/client/informers/externalversions/servicecatalog/v1alpha1/usagekind.go
  components/service-binding-usage-controller/pkg/client/informers/externalversions/settings/v1alpha1/podpreset.go
Labels: WIP, area/service-catalog

#5594 Migrate to AsyncAPI 2.0.0
  components/cms-services/Gopkg.lock
  components/cms-services/Gopkg.toml
  components/cms-services/before-commit.sh
  components/cms-services/cmd/asyncapi/main.go
  components/cms-services/deploy/asyncapi/Dockerfile
  components/cms-services/go.mod
  components/cms-services/go.sum
  components/cms-services/pkg/endpoint/asyncapi/v1/testdata/valid.json
  components/cms-services/pkg/endpoint/asyncapi/v1/testdata/valid.yaml
  components/cms-services/pkg/endpoint/asyncapi/v1/validation_endpoint.go
  components/cms-services/pkg/endpoint/asyncapi/v1/validation_endpoint_test.go
  components/cms-services/pkg/runtime/service/service.go
  components/cms-services/pkg/runtime/service/service_test.go
  components/console-backend-service/internal/domain/application/eventactivation_converter.go
  components/console-backend-service/internal/domain/application/eventactivation_converter_test.go
  components/console-backend-service/internal/domain/application/eventactivation_resolver.go
  components/console-backend-service/internal/domain/application/eventactivation_resolver_test.go
  components/console-backend-service/internal/domain/assetstore/spec/asyncapispec.go
  components/console-backend-service/internal/domain/root_resolver.go
  resources/application-connector/values.yaml
  resources/cms/charts/cms-controller-manager/templates/webhook-config-map.yaml
  resources/cms/requirements.yaml
  resources/cms/values.yaml
  resources/core/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
  tests/application-registry-tests/test/apitests/metadata_test.go
  tests/application-registry-tests/test/testkit/model.go
Labels: area/console, area/core-and-supporting, enhancement

#5743 bump Hydra Maester version
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
Labels: area/security

#5634 hydra-maester-docu
  docs/security/03-06-oauth2-server.md
Labels: area/documentation, area/security

#5760 Fix Console Backend Service unit tests
  components/console-backend-service/internal/domain/application/eventactivation_converter_test.go
  components/console-backend-service/internal/domain/application/eventactivation_resolver_test.go
Labels: area/console, bug

#5713 Remove kubeless from console-backend-service
  components/console-backend-service/Gopkg.lock
  components/console-backend-service/Gopkg.toml
  components/console-backend-service/Makefile
  components/console-backend-service/internal/domain/kubeless/automock/export.go
  components/console-backend-service/internal/domain/kubeless/automock/function_lister.go
  components/console-backend-service/internal/domain/kubeless/disabled/resolver.go
  components/console-backend-service/internal/domain/kubeless/export_test.go
  components/console-backend-service/internal/domain/kubeless/function_converter.go
  components/console-backend-service/internal/domain/kubeless/function_converter_test.go
  components/console-backend-service/internal/domain/kubeless/function_resolver.go
  components/console-backend-service/internal/domain/kubeless/function_resolver_test.go
  components/console-backend-service/internal/domain/kubeless/function_service.go
  components/console-backend-service/internal/domain/kubeless/function_service_test.go
  components/console-backend-service/internal/domain/kubeless/kubeless.go
  components/console-backend-service/internal/domain/kubeless/kubeless_test.go
  components/console-backend-service/internal/domain/kubeless/pretty/kind.go
  components/console-backend-service/internal/domain/root_resolver.go
  components/console-backend-service/internal/gqlschema/models_gen.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
Labels: area/service-catalog

#5737 Bump SBU controller image to PR-5693
  resources/service-catalog-addons/values.yaml
Labels: WIP, area/service-catalog

#5736 Bump Application Broker image to PR-5687
  resources/application-connector/values.yaml
Labels: WIP, area/service-catalog

#5685 Save window location after relogin
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#5589 Fluent bit loki plugin
  docs/logging/05-01-logging.md
  docs/logging/08-01-configure-logcollector.md
  resources/logging/templates/fluent-bit-plugin/_helpers.tpl
  resources/logging/templates/fluent-bit-plugin/fluent-bit-configmap.yaml
  resources/logging/templates/fluent-bit-plugin/fluent-bit-daemonset.yaml
  resources/logging/templates/fluent-bit-plugin/fluent-bit-role-binding.yaml
  resources/logging/templates/fluent-bit-plugin/fluent-bit-role.yaml
  resources/logging/templates/fluent-bit-plugin/fluent-bit-service-account.yaml
  resources/logging/templates/promtail/clusterrole.yaml
  resources/logging/templates/promtail/clusterrolebinding.yaml
  resources/logging/templates/promtail/configmap.yaml
  resources/logging/templates/promtail/daemonset.yaml
  resources/logging/templates/promtail/podsecuritypolicy.yaml
  resources/logging/templates/promtail/role.yaml
  resources/logging/templates/promtail/rolebinding.yaml
  resources/logging/values.yaml
Labels: area/documentation, area/logging

#5766 Remove powershell installation scripts
  CODEOWNERS
  installation/cmd/run.ps1
  installation/scripts/build-kyma-installer.ps1
  installation/scripts/clean-up.ps1
  installation/scripts/configure-components.ps1
  installation/scripts/copy-resource.ps1
  installation/scripts/create-cr.ps1
  installation/scripts/extract-kyma-installer-image.ps1
  installation/scripts/generate-local-config.ps1
  installation/scripts/install-tiller.ps1
  installation/scripts/installer.ps1
  installation/scripts/is-installed.ps1
  installation/scripts/is-ready.ps1
  installation/scripts/minikube.ps1
  installation/scripts/replace-placeholder.ps1
Labels: area/cli, area/installation, enhancement

#5711 Add revocation charts to Compass Connector
  resources/compass/charts/connector/templates/configmap.yaml
  resources/compass/charts/connector/templates/deployment.yaml
  resources/compass/charts/connector/templates/role-binding.yaml
  resources/compass/charts/connector/templates/tests/role-binding.yaml
  resources/compass/charts/connector/templates/tests/service-account.yaml
  resources/compass/charts/connector/templates/tests/test-connector.yaml
  resources/compass/values.yaml
Labels: area/application-connector, enhancement

#5749 Remove 1.15 migration jobs from Application Connector
  components/application-operator/charts/application/templates/migration-job-1-5.yaml
  resources/application-connector/charts/application-registry/templates/migration-job-1-5.yaml
  resources/application-connector/charts/connection-token-handler/templates/migration-job-1-5.yaml
  resources/application-connector/charts/connectivity-certs-controller/templates/migration-job-1-5.yaml
  resources/application-connector/charts/connector-service/templates/migration-job-1-5.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector

#5668 Show Istio config in the acceptnace test
  resources/core/templates/tests/rbac.yaml
  resources/core/templates/tests/test.yaml
  resources/core/values.yaml
  tests/acceptance/Gopkg.lock
  tests/acceptance/README.md
  tests/acceptance/application/suite/app_testsuite.go
  tests/acceptance/application/suite/kubernetes.go
  tests/acceptance/application/suite/mapping_testsuite.go
  tests/acceptance/pkg/repeat/repeat.go
  tests/acceptance/servicecatalog/binding_usage_test.go
  tests/acceptance/servicecatalog/helpers_test.go
  tests/acceptance/servicecatalog/istio_test.go
  tests/acceptance/servicecatalog/servicecatalog_test.go
Labels: area/security

#5638 Improve Headless CMS and Asset Store docs
  docs/application-connector/01-01-application-connector.md
  docs/application-connector/03-04-metadata-service.md
  docs/asset-store/03-04-supported-webhooks.md
  docs/asset-store/03-05-asset-metadata-service.md
  docs/asset-store/03-06-asset-upload-service.md
  docs/asset-store/06-01-asset.md
  docs/asset-store/06-02-bucket.md
  docs/asset-store/06-03-clusterasset.md
  docs/asset-store/06-04-clusterbucket.md
  docs/asset-store/assets/metadata-service.yaml
  docs/asset-store/assets/mutation-service.yaml
  docs/asset-store/assets/validation-service.yaml
  docs/console/03-04-headless-cms-in-console.md
  docs/console/assets/spec-types.svg
  docs/headless-cms/03-01-docstopic-cr-lifecycle.md
  docs/headless-cms/03-01-headless-cms-in-console.md
  docs/headless-cms/03-02-cms-asyncapi-service.md
  docs/headless-cms/05-02-cms-asynapi-service.md
  docs/headless-cms/06-01-docstopic.md
  docs/headless-cms/06-02-clusterdocstopic.md
  docs/headless-cms/08-01-add-new-documentation-to-console.md
  docs/service-catalog/11-01-overview.md
  docs/service-catalog/11-02-catalog-view.md
  docs/service-catalog/11-03-instances-view.md
  docs/service-catalog/11-04-specifications-in-console-ui.md
  docs/service-catalog/assets/catalog-ui-docs.png
  docs/service-catalog/assets/docs-toggle.png
  docs/service-catalog/assets/nav-docs-ui.png
  docs/service-catalog/assets/spec-view.png
  docs/service-catalog/assets/tip-panel.png
Labels: area/core-and-supporting, area/documentation

#5771 Skip not ready Assets in Event Activation query
  components/console-backend-service/internal/domain/application/eventactivation_resolver.go
  components/console-backend-service/internal/domain/application/eventactivation_resolver_test.go
  resources/core/values.yaml
Labels: area/console, bug

#5780 Replace PR images: Goat components
  resources/core/values.yaml
  resources/dex/values.yaml
  resources/istio-kyma-patch/values.yaml
  resources/xip-patch/values.yaml
  tools/kyma-installer/kyma.Dockerfile
Labels: area/ci

#5786 Add the link to the Application Registry API specification in the Application Registry doc
  docs/application-connector/09-02-metadata-service.md
Labels: area/application-connector, area/documentation

#5794 Fix metrics for Application Registry and Connector Service
  resources/application-connector/charts/application-registry/templates/deployment.yaml
  resources/application-connector/charts/application-registry/templates/policy.yaml
  resources/application-connector/charts/application-registry/templates/service.yaml
  resources/application-connector/charts/application-registry/templates/servicemonitor.yaml
  resources/application-connector/charts/connector-service/templates/deployment.yaml
  resources/application-connector/charts/connector-service/templates/policy.yaml
  resources/application-connector/charts/connector-service/templates/service.yaml
  resources/application-connector/charts/connector-service/templates/servicemonitor.yaml
Labels: area/application-connector, bug

#5796 Fix metadata in tabs in docs
  docs/application-connector/10-02-application-gateway-troubleshooting.md
  docs/backup/04-01-install-velero.md
  docs/backup/08-01-create-backup.md
  docs/helm-broker/03-07-addons-docs.md
  docs/kyma/04-02-local-installation.md
  docs/kyma/04-04-cluster-installation.md
  docs/kyma/04-05-use-your-own-domain.md
  docs/kyma/04-06-use-your-own-image.md
  docs/kyma/04-10-upgrade.md
  docs/kyma/05-01-overview.md
  docs/kyma/05-02-custom-component-installation.md
  docs/kyma/10-03-network-error.md
Labels: area/documentation, enhancement

#5784 Disable Application Connector Tests on Minikube
  resources/application-connector/charts/application-operator/templates/tests/rbac.yaml
  resources/application-connector/templates/tests/rbac.yaml
  resources/application-connector/templates/tests/test.yaml
Labels: area/application-connector

#5803 Add ability to execute only one test in testing.sh
  installation/scripts/testing.sh
Labels: area/ci, enhancement

#5806 Skip unstable IDPPreset mutation test
  tests/console-backend-service/internal/domain/authentication/idppreset_test.go
Labels: test-failing

#5810 Fix test flag reading in testing.sh
  installation/scripts/testing.sh
Labels: area/cluster, bug

#5692 Add tutorials for additional Minio Gateway modes
  docs/asset-store/08-01-gateway-gcs-mode-set-up.md
  docs/asset-store/08-02-gateway-azure-mode-set-up.md
  docs/asset-store/08-03-gateway-s3-mode-set-up.md
  docs/asset-store/08-04-gateway-oss-mode-set.md
Labels: area/documentation, enhancement

#5765 Logging UI redesigned
  resources/core/charts/console/values.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
  resources/logging/charts/log-ui/templates/deployment.yaml
  resources/logging/charts/log-ui/values.yaml
  resources/logging/templates/loki/backendmodule.yaml
Labels: area/console, enhancement

#5797 Update addons UI version
  resources/helm-broker/values.yaml
Labels: area/console, bug

#5728 Bump Console Backend Service image to PR-5724
  resources/core/values.yaml
Labels: area/service-catalog

#5782 Runtime agent tests with oauth
  tests/compass-runtime-agent/test/runtimeagent/suite.go
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_suite_test.go
  tests/compass-runtime-agent/test/testkit/compass/client.go
  tests/compass-runtime-agent/test/testkit/config.go
  tests/compass-runtime-agent/test/testkit/oauth/client.go
Labels: area/application-connector, enhancement

#5768 Update Compass and Compass Runtime Agent charts
  installation/scripts/minikube.sh
  resources/compass-runtime-agent/dev/create_config_map.sh
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/templates/resources-role-binding.yaml
  resources/compass-runtime-agent/templates/role-binding.yaml
  resources/compass-runtime-agent/templates/tests/test-runtime-agent-integration.yaml
  resources/compass-runtime-agent/values.yaml
  resources/compass/charts/connector/templates/deployment.yaml
  resources/compass/charts/connector/templates/oathkeeper-rule.yaml
  resources/compass/charts/connector/templates/tests/test-connector.yaml
  resources/compass/charts/connector/values.yaml
  resources/compass/charts/director/scopes.yaml
  resources/compass/charts/director/templates/configmap.yaml
  resources/compass/charts/director/templates/deployment.yaml
  resources/compass/charts/director/values.yaml
  resources/compass/charts/gateway/templates/oathkeeper-rules.yaml
  resources/compass/charts/gateway/templates/virtualservice-secure.yaml
  resources/compass/charts/gateway/templates/virtualservice.yaml
  resources/compass/templates/agent-configuration-job.yaml
  resources/compass/templates/test.yaml
  resources/compass/values.yaml
Labels: enhancement

#5347 Add docs for the Asset Store and hCMS metrics
  docs/asset-store/09-01-asset-store-controller.md
  docs/asset-store/09-02-asset-metadata-service.md
  docs/asset-store/09-03-asset-upload-service.md
  docs/headless-cms/09-01-cms-controller-manager.md
  docs/headless-cms/09-02-asyncapi-service.md
Labels: area/documentation

#5815 Fix
  docs/asset-store/09-03-asset-upload-service.md
Labels: area/documentation

#5798 Add migration job for application-broker
  components/application-broker/.gitignore
  components/application-broker/Makefile
  components/application-broker/before-commit.sh
  components/application-broker/cmd/migration/main.go
  components/application-broker/deploy/migration/Dockerfile
Labels: area/service-catalog, enhancement

#5741 Update Service Catalog docs - remove api-server
  docs/service-catalog/01-01-service-catalog.md
  docs/service-catalog/03-03-experimental-features.md
  docs/service-catalog/05-01-service-catalog.md
  docs/service-catalog/05-02-catalog.md
  docs/service-catalog/05-03-catalog-crds.md
  docs/service-catalog/05-04-etcd-stateful.md
Labels: area/service-catalog

#5799 Add global mode to hydra
  resources/ory/charts/hydra/charts/hydra-maester/templates/rbac-global.yaml
  resources/ory/charts/hydra/charts/hydra-maester/templates/rbac-namespaces.yaml
  resources/ory/charts/hydra/charts/hydra-maester/templates/rbac.yaml
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
  resources/ory/values.yaml
Labels: area/security

#5769 Move provisioner charts to Kyma
  resources/compass/charts/provisioner/.helmignore
  resources/compass/charts/provisioner/Chart.yaml
  resources/compass/charts/provisioner/templates/deployment.yaml
  resources/compass/charts/provisioner/templates/service-account.yaml
  resources/compass/charts/provisioner/templates/service.yaml
  resources/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  resources/compass/charts/provisioner/values.yaml
  resources/compass/values.yaml
Labels: area/application-connector, enhancement

#5807 Update the default column in tables
  components/api-controller/README.md
  components/application-broker/README.md
  components/asset-metadata-service/README.md
  components/asset-store-controller-manager/README.md
  components/asset-upload-service/README.md
  components/cms-controller-manager/README.md
  components/console-backend-service/docs/configuration.md
  components/iam-kubeconfig-service/README.md
  components/service-binding-usage-controller/README.md
  resources/application-connector-ingress/charts/nginx-ingress/README.md
  resources/backup/README.md
  resources/service-catalog/charts/catalog/README.md
  tests/application-connector-tests/README.md
  tests/application-gateway-tests/README.md
  tests/asset-store/README.md
  tests/connector-service-tests/README.md
  tests/end-to-end/backup-restore-test/README.md
  tests/end-to-end/upgrade/README.md
Labels: area/documentation

#5823 Remove probes from SC
  resources/service-catalog/charts/catalog/templates/controller-manager-deployment.yaml
  resources/service-catalog/charts/catalog/templates/webhook-deployment.yaml
Labels: area/service-catalog

#5814 Bump Asset Store and hCMS images to the latest develop
  resources/assetstore/values.yaml
  resources/cms/values.yaml
Labels: area/core-and-supporting, enhancement

#5805 Label Runtime Agent manageable Applications
  components/application-operator/Gopkg.lock
  components/application-operator/Gopkg.toml
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/types.go
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/zz_generated.deepcopy.go
  components/application-operator/pkg/client/clientset/versioned/fake/clientset_generated.go
  components/application-operator/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/applicationconnector_client.go
  components/application-registry/Gopkg.lock
  components/application-registry/Gopkg.toml
  components/application-registry/pkg/apis/istio/v1alpha2/zz_generated.deepcopy.go
  components/application-registry/pkg/client/clientset/versioned/fake/clientset_generated.go
  components/application-registry/pkg/client/clientset/versioned/typed/istio/v1alpha2/istio_client.go
  components/compass-runtime-agent/cmd/init.go
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  components/compass-runtime-agent/internal/kyma/apiresources/assetstore/docstopicrepository.go
  components/compass-runtime-agent/internal/kyma/apiresources/assetstore/docstopicrepository_test.go
  components/compass-runtime-agent/internal/kyma/applications/converter.go
  components/compass-runtime-agent/internal/kyma/applications/converter_test.go
  components/compass-runtime-agent/internal/kyma/service.go
  components/compass-runtime-agent/internal/kyma/service_test.go
  components/compass-runtime-agent/scripts/patch-local-changes.sh
  resources/application-connector/templates/application.crd.yaml
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/templates/tests/cluster-role-binding.yaml
  resources/compass-runtime-agent/values.yaml
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/Gopkg.toml
  tests/compass-runtime-agent/test/runtimeagent/suite.go
  tests/compass-runtime-agent/test/runtimeagent/test/ignored_apps_test.go
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_test.go
  tests/compass-runtime-agent/test/testkit/compass/client.go
  tests/compass-runtime-agent/test/testkit/oauth/client.go
Labels: area/application-connector, enhancement
