Repository kyma-project/kyma, pull requests merged in 2019-08, with the labels that each got.

#5131 Fix ClusterAddonConfiguration informer interface
  components/helm-broker/Makefile
  components/helm-broker/pkg/client/informers/externalversions/addons/v1alpha1/interface.go
Labels: area/service-catalog, bug

#5116 Add missing modules to documentation
  docs/kyma/04-01-overview.md
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  resources/knative-build-init/README.md
  resources/knative-build/README.md
  resources/knative-build/values.yaml
  resources/knative-serving-init/README.md
  resources/knative-serving/README.md
Labels: area/documentation, area/serverless

#5110 Fix not hiding backdrop issue
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
Labels: area/console, bug

#5106 Fix docs topics removing
  components/helm-broker/internal/controller/addonsconfiguration_controller.go
  components/helm-broker/internal/controller/clusteraddonsconfiguration_controller.go
Labels: area/service-catalog, bug

#5109 Rename Application Services to not to start with Application Name
  components/application-operator/charts/application/templates/policy.yaml
  components/application-operator/charts/application/templates/service.yaml
  components/application-operator/charts/application/templates/tests/test-acceptance.yaml
  components/application-operator/charts/application/templates/validator.yaml
  components/application-operator/charts/application/templates/virtual-service.yaml
  resources/application-connector/values.yaml
  tests/application-gateway-tests/test/executor/proxy/suite.go
  tests/application-operator-tests/test/testkit/k8sresources_check.go
  tests/application-registry-tests/Gopkg.lock
  tests/application-registry-tests/Gopkg.toml
  tests/application-registry-tests/test/k8stests/k8sresource_test.go
  tests/application-registry-tests/test/testkit/util.go
Labels: area/application-connector

#5114 Add integration test for (Cluster)AddonConfiguration git feature
  components/helm-broker/Gopkg.lock
  components/helm-broker/cmd/controller/main.go
  components/helm-broker/internal/controller/setup.go
  components/helm-broker/test/integration/fake_repository_test.go
  components/helm-broker/test/integration/integration_test.go
  components/helm-broker/test/integration/source_test.go
  components/helm-broker/test/integration/suite_test.go
  components/helm-broker/test/integration/testdata/addons.tgz
Labels: area/service-catalog

#5105 Add documentation about the git support in Helm Broker
  docs/helm-broker/01-01-helm-broker.md
  docs/helm-broker/02-01-helm-broker.md
  docs/helm-broker/02-02-deep-dive.md
  docs/helm-broker/03-02-bind-addons.md
  docs/helm-broker/03-03-create-addons-repo.md
  docs/helm-broker/03-04-fetch-addons-from-https-servers.md
  docs/helm-broker/03-05-registration-rules.md
Labels: area/documentation

#5156 Add (Cluster)DocsTopic integration tests to helm broker
  components/helm-broker/Gopkg.lock
  components/helm-broker/test/integration/integration_test.go
  components/helm-broker/test/integration/source_test.go
  components/helm-broker/test/integration/suite_test.go
Labels: area/service-catalog

#5152 Add the Kiali ClusterDocsTopic
  resources/core/charts/docs/charts/content-ui/templates/docs-components-kiali-cdt.yaml
Labels: area/documentation, area/service-mesh

#5138 Use Config Map in Compass Runtime Agent
  components/compass-runtime-agent/Gopkg.lock
  components/compass-runtime-agent/cmd/init.go
  components/compass-runtime-agent/cmd/main.go
  components/compass-runtime-agent/cmd/options.go
  components/compass-runtime-agent/internal/compass/config_client.go
  components/compass-runtime-agent/internal/compass/config_client_test.go
  components/compass-runtime-agent/internal/compass/connector.go
  components/compass-runtime-agent/internal/compass/connector_test.go
  components/compass-runtime-agent/internal/compass/converter.go
  components/compass-runtime-agent/internal/compass/converter_test.go
  components/compass-runtime-agent/internal/compass/model.go
  components/compass-runtime-agent/internal/compass/query.go
  components/compass-runtime-agent/internal/graphql/client.go
Labels: area/application-connector

#5096 Update charts of Compass Runtime Agent
  resources/compass-runtime-agent/dev/create_config_map.sh
  resources/compass-runtime-agent/templates/cluster-role-binding.yaml
  resources/compass-runtime-agent/templates/compass-connection.crd.yaml
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/templates/role-binding.yaml
  resources/compass-runtime-agent/templates/tests/test-runtime-agent-integration.yaml
  resources/compass-runtime-agent/templates/token-config-map.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, enhancement

#4949 Integrate documentation-component in instances, catalog, and content uis in console
  resources/core/charts/docs/charts/content-ui/Chart.yaml
  resources/helm-broker/values.yaml
  resources/service-catalog-addons/charts/catalog-ui/Chart.yaml
  resources/service-catalog-addons/charts/instances-ui/Chart.yaml
Labels: area/core-and-supporting, area/documentation, enhancement

#5122 Unify Asset Store webhooks handling
  components/asset-store-controller-manager/README.md
  components/asset-store-controller-manager/config/crds/assetstore_v1alpha2_asset.yaml
  components/asset-store-controller-manager/config/crds/assetstore_v1alpha2_clusterasset.yaml
  components/asset-store-controller-manager/config/samples/assetstore_v1alpha2_asset.yaml
  components/asset-store-controller-manager/pkg/apis/assetstore/v1alpha2/asset_common_types.go
  components/asset-store-controller-manager/pkg/apis/assetstore/v1alpha2/zz_generated.deepcopy.go
  components/asset-store-controller-manager/pkg/assethook/api/v1alpha1/mutation_types.go
  components/asset-store-controller-manager/pkg/assethook/api/v1alpha1/validation_types.go
  components/asset-store-controller-manager/pkg/assethook/automock/accessor.go
  components/asset-store-controller-manager/pkg/assethook/automock/export.go
  components/asset-store-controller-manager/pkg/assethook/automock/http_processor.go
  components/asset-store-controller-manager/pkg/assethook/automock/metadata_extractor.go
  components/asset-store-controller-manager/pkg/assethook/automock/mutator.go
  components/asset-store-controller-manager/pkg/assethook/automock/validator.go
  components/asset-store-controller-manager/pkg/assethook/automock/webhook.go
  components/asset-store-controller-manager/pkg/assethook/config.go
  components/asset-store-controller-manager/pkg/assethook/engine/automock/metadata_extractor.go
  components/asset-store-controller-manager/pkg/assethook/engine/automock/mutator.go
  components/asset-store-controller-manager/pkg/assethook/engine/automock/validator.go
  components/asset-store-controller-manager/pkg/assethook/engine/engine.go
  components/asset-store-controller-manager/pkg/assethook/engine/export_test.go
  components/asset-store-controller-manager/pkg/assethook/engine/metadata_engine_test.go
  components/asset-store-controller-manager/pkg/assethook/engine/mutation_engine.go
  components/asset-store-controller-manager/pkg/assethook/engine/mutation_engine_test.go
  components/asset-store-controller-manager/pkg/assethook/engine/validation_engine.go
  components/asset-store-controller-manager/pkg/assethook/engine/validation_engine_test.go
  components/asset-store-controller-manager/pkg/assethook/export_test.go
  components/asset-store-controller-manager/pkg/assethook/metadata_engine.go
  components/asset-store-controller-manager/pkg/assethook/metadata_engine_test.go
  components/asset-store-controller-manager/pkg/assethook/mutation_engine.go
  components/asset-store-controller-manager/pkg/assethook/mutation_engine_test.go
  components/asset-store-controller-manager/pkg/assethook/processor.go
  components/asset-store-controller-manager/pkg/assethook/processor_test.go
  components/asset-store-controller-manager/pkg/assethook/validation_engine.go
  components/asset-store-controller-manager/pkg/assethook/validation_engine_test.go
  components/asset-store-controller-manager/pkg/assethook/webhook.go
  components/asset-store-controller-manager/pkg/assethook/webhook_test.go
  components/asset-store-controller-manager/pkg/controller/asset/asset_controller.go
  components/asset-store-controller-manager/pkg/controller/asset/asset_controller_test.go
  components/asset-store-controller-manager/pkg/controller/bucket/bucket_controller.go
  components/asset-store-controller-manager/pkg/controller/clusterasset/clusterasset_controller.go
  components/asset-store-controller-manager/pkg/controller/clusterasset/clusterasset_controller_test.go
  components/asset-store-controller-manager/pkg/controller/clusterbucket/clusterbucket_controller.go
  components/asset-store-controller-manager/pkg/handler/asset/asset.go
  components/asset-store-controller-manager/pkg/handler/asset/asset_test.go
  components/asset-store-controller-manager/pkg/handler/asset/pretty/reason.go
  components/asset-store-controller-manager/pkg/store/store.go
Labels: area/core-and-supporting, enhancement

#5123 Change the name of the metadata field to parameters in CMS
  components/cms-controller-manager/Gopkg.lock
  components/cms-controller-manager/Gopkg.toml
  components/cms-controller-manager/config/crds/cms_v1alpha1_clusterdocstopic.yaml
  components/cms-controller-manager/config/crds/cms_v1alpha1_docstopic.yaml
  components/cms-controller-manager/hack/crds/assetstore_v1alpha2_asset.yaml
  components/cms-controller-manager/hack/crds/assetstore_v1alpha2_clusterasset.yaml
  components/cms-controller-manager/pkg/apis/cms/v1alpha1/docstopic_common.go
  components/cms-controller-manager/pkg/apis/cms/v1alpha1/zz_generated.deepcopy.go
  components/cms-controller-manager/pkg/controller/clusterdocstopic/clusterdocstopic_controller_test.go
  components/cms-controller-manager/pkg/controller/docstopic/docstopic_controller_test.go
  components/cms-controller-manager/pkg/handler/docstopic/docstopic.go
  components/cms-controller-manager/pkg/handler/docstopic/docstopic_test.go
  components/cms-controller-manager/pkg/webhookconfig/asset_webhook_config_service.go
Labels: area/core-and-supporting, enhancement

#5093 Add CMS AsyncAPI service
  CODEOWNERS
  components/cms-services/.gitignore
  components/cms-services/Gopkg.lock
  components/cms-services/Gopkg.toml
  components/cms-services/Makefile
  components/cms-services/README.md
  components/cms-services/before-commit.sh
  components/cms-services/cmd/asyncapi/README.md
  components/cms-services/cmd/asyncapi/main.go
  components/cms-services/cmd/asyncapi/openapi.yaml
  components/cms-services/deploy/asyncapi/Dockerfile
  components/cms-services/pkg/endpoint/asyncapi/asyncapi.go
  components/cms-services/pkg/endpoint/asyncapi/asyncapi_test.go
  components/cms-services/pkg/endpoint/asyncapi/v1/conversion_endpoint.go
  components/cms-services/pkg/endpoint/asyncapi/v1/conversion_endpoint_test.go
  components/cms-services/pkg/endpoint/asyncapi/v1/testdata/anyof_1.1.0.json
  components/cms-services/pkg/endpoint/asyncapi/v1/testdata/anyof_1.1.0.yaml
  components/cms-services/pkg/endpoint/asyncapi/v1/testdata/anyof_invalid.json
  components/cms-services/pkg/endpoint/asyncapi/v1/testdata/anyof_invalid.yaml
  components/cms-services/pkg/endpoint/asyncapi/v1/testdata/invalid.json
  components/cms-services/pkg/endpoint/asyncapi/v1/testdata/invalid.yaml
  components/cms-services/pkg/endpoint/asyncapi/v1/testdata/valid.json
  components/cms-services/pkg/endpoint/asyncapi/v1/testdata/valid.yaml
  components/cms-services/pkg/endpoint/asyncapi/v1/validation_endpoint.go
  components/cms-services/pkg/endpoint/asyncapi/v1/validation_endpoint_test.go
  components/cms-services/pkg/runtime/endpoint/mutation_endpoint.go
  components/cms-services/pkg/runtime/endpoint/mutation_endpoint_test.go
  components/cms-services/pkg/runtime/endpoint/validation_endpoint.go
  components/cms-services/pkg/runtime/endpoint/validation_endpoint_test.go
  components/cms-services/pkg/runtime/log/log.go
  components/cms-services/pkg/runtime/service/export_test.go
  components/cms-services/pkg/runtime/service/fake/service.go
  components/cms-services/pkg/runtime/service/service.go
  components/cms-services/pkg/runtime/service/service_test.go
  components/cms-services/pkg/runtime/signal/signal.go
Labels: area/core-and-supporting, area/documentation, enhancement

#5117 Add compass-system to the list of system namespaces
  docs/console/05-01-console.md
  resources/core/charts/console/values.yaml
Labels: area/console, area/documentation

#5034 Fix not opening lambda UI
  resources/core/charts/kubeless/charts/lambdas-ui/templates/lambdas-microfrontend.yaml
Labels: area/console, bug

#5162 Fix wrong formatting in the HB docs
  docs/helm-broker/03-03-create-addons-repo.md
Labels: area/documentation, bug

#5141 Create basic ORY OAuth2 server doc
  docs/kyma/04-01-overview.md
  docs/security/03-06-oauth2-server.md
  resources/ory/README.md
Labels: area/documentation, area/security, area/service-mesh

#5148 Change the name of the metadata field to parameters in CBS
  components/console-backend-service/Gopkg.lock
  components/console-backend-service/Gopkg.toml
  components/console-backend-service/internal/domain/assetstore/asset_converter.go
  components/console-backend-service/internal/domain/assetstore/asset_converter_test.go
  components/console-backend-service/internal/domain/assetstore/clusterasset_converter.go
  components/console-backend-service/internal/domain/assetstore/clusterasset_converter_test.go
  components/console-backend-service/internal/domain/assetstore/extractor/common.go
  components/console-backend-service/internal/domain/assetstore/extractor/common_test.go
  components/console-backend-service/internal/gqlschema/asset.go
  components/console-backend-service/internal/gqlschema/clusterasset.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
  docs/asset-store/05-03-asset-store-controller-manager.md
  docs/asset-store/06-01-asset.md
  docs/asset-store/06-03-clusterasset.md
  docs/headless-cms/06-01-docstopic.md
  docs/headless-cms/06-02-clusterdocstopic.md
  resources/assetstore/charts/asset-store-controller-manager/templates/statefulset.yaml
  resources/assetstore/charts/asset-store-controller-manager/values.yaml
  resources/assetstore/values.yaml
  resources/cluster-essentials/templates/asset.crd.yaml
  resources/cluster-essentials/templates/bucket.crd.yaml
  resources/cluster-essentials/templates/clusterasset.crd.yaml
  resources/cluster-essentials/templates/clusterbucket.crd.yaml
  resources/cluster-essentials/templates/clusterdocstopic.crd.yaml
  resources/cluster-essentials/templates/docstopic.crd.yaml
  resources/cms/charts/cms-asyncapi-service/.helmignore
  resources/cms/charts/cms-asyncapi-service/Chart.yaml
  resources/cms/charts/cms-asyncapi-service/templates/_helpers.tpl
  resources/cms/charts/cms-asyncapi-service/templates/deployment.yaml
  resources/cms/charts/cms-asyncapi-service/templates/service.yaml
  resources/cms/charts/cms-asyncapi-service/values.yaml
  resources/cms/charts/cms-controller-manager/templates/statefulset.yaml
  resources/cms/charts/cms-controller-manager/templates/webhook-config-map.yaml
  resources/cms/requirements.yaml
  resources/cms/values.yaml
  resources/core/values.yaml
  tests/asset-store/Gopkg.lock
  tests/asset-store/Gopkg.toml
  tests/console-backend-service/Gopkg.lock
  tests/console-backend-service/Gopkg.toml
  tests/console-backend-service/internal/domain/cms/clusterdocstopic_test.go
  tests/console-backend-service/internal/domain/shared/clusterasset.go
Labels: area/core-and-supporting, area/documentation, enhancement

#5151 Set up a scheduled backup by default
  CODEOWNERS
  docs/backup/01-01-backup.md
  docs/backup/05-01-velero.md
  docs/backup/08-01-create-backup.md
  resources/backup/values.yaml
Labels: area/documentation

#5178 Add retries to test to improve resilience
  resources/core/values.yaml
  tests/integration/cluster-users/sar-test.sh
Labels: area/security

#5191 Add documentation about new AWS classes
  docs/service-catalog/13-04-aws-broker.md
Labels: area/documentation

#5193 Add GCP SB to the list of HB brokers
  docs/helm-broker/01-01-helm-broker.md
  docs/service-catalog/13-02-gcp-broker.md
Labels: area/documentation, bug

#4947 Parameters added to values.yaml
  components/application-operator/README.md
  docs/application-connector/05-01-application-operator.md
  docs/application-connector/05-02-application-registry.md
  docs/application-connector/05-04-connector-service.md
  resources/application-connector/charts/application-registry/templates/deployment.yaml
  resources/application-connector/charts/application-registry/values.yaml
  resources/application-connector/charts/connector-service/templates/deployment.yaml
  resources/application-connector/charts/connector-service/values.yaml
Labels: area/application-connector, area/documentation, enhancement

#5200 Remove type metadata from single Overview docs
  docs/console/01-01-console.md
  docs/tracing/01-01-tracing.md
Labels: area/console, area/documentation, area/logging

#5199 Stores RepositoryURL to etcd
  components/helm-broker/internal/storage/driver/etcd/entity_bundle.go
  components/helm-broker/internal/storage/testing/bundle_test.go
Labels: area/service-catalog

#5118 Compass Cockpit - sub-chart (preview)
  installation/scripts/minikube.sh
  resources/compass/charts/cockpit/.helmignore
  resources/compass/charts/cockpit/Chart.yaml
  resources/compass/charts/cockpit/templates/compass-microfrontend.yaml
  resources/compass/charts/cockpit/templates/configmap.yaml
  resources/compass/charts/cockpit/templates/deployment.yaml
  resources/compass/charts/cockpit/templates/mf-virtualservice.yaml
  resources/compass/charts/cockpit/templates/service.yaml
  resources/compass/charts/cockpit/templates/virtualservice.yaml
  resources/compass/charts/cockpit/values.yaml
  resources/compass/values.yaml
  resources/core/charts/console/values.yaml
Labels: area/console, enhancement

#5201 Bump Podpreset image
  resources/cluster-essentials/charts/pod-preset/README.md
  resources/cluster-essentials/charts/pod-preset/values.yaml
Labels: area/service-catalog

#5236 Disable URL path escape in the gateway proxy
  components/application-gateway/internal/proxy/proxy_test.go
  components/application-gateway/internal/proxy/proxyfactory.go
  resources/application-connector/values.yaml
Labels: area/application-connector, bug, priority/critical

#5233 Enable concurrency testing for core test
  resources/core/templates/tests/test.yaml
Labels: area/service-catalog

#5242 Rename troubleshooting files in "Service Mesh"
  docs/service-mesh/10-01-overview.md
  docs/service-mesh/10-02-no-access.md
  docs/service-mesh/10-03-connection-refused.md
  docs/service-mesh/10-04-jobs-fail-aks.md
Labels: area/documentation

#5231 Fix npm audit vulnerabilities in ui components
  resources/core/charts/console/values.yaml
  resources/core/charts/docs/charts/content-ui/Chart.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
  resources/core/values.yaml
  resources/helm-broker/values.yaml
  resources/logging/charts/log-ui/values.yaml
  resources/service-catalog-addons/charts/brokers-ui/Chart.yaml
  resources/service-catalog-addons/charts/catalog-ui/Chart.yaml
  resources/service-catalog-addons/charts/instances-ui/Chart.yaml
Labels: area/console

#5202 Add installer template for integration with compass
  installation/resources/installer-cr-cluster-with-compass.yaml.tpl
Labels: area/application-connector, area/ci, enhancement

#5240 Fix filter in service-catalog clusterdocstopic
  resources/core/charts/docs/charts/content-ui/templates/docs-components-service-catalog-cdt.yaml
Labels: area/documentation, bug

#5255 Fix dead links
  docs/event-bus/03-06-configure-default-channelprovisioner.md
  docs/kyma/04-02-local-installation.md
  resources/knative-provisioner-natss/README.md
Labels: area/documentation

#5222 Add an improved monitoring tutorial
  docs/monitoring/01-01-monitoring.md
  docs/monitoring/02-01-monitoring.md
  docs/monitoring/08-01-monitoring-custom-metrics.md
  docs/monitoring/08-01-observe-application-metrics.md
  docs/monitoring/assets/monitoring-architecture.svg
  docs/monitoring/assets/pm-dashboard-1.png
  docs/monitoring/assets/pm-dashboard-2.png
  docs/monitoring/assets/sample-metrics-2.png
Labels: area/documentation, area/monitoring, quality/content

#5251 Add a tutorial on creating a simple Grafana dashboard
  docs/monitoring/08-02-create-and-configure-grafana-dashboard.md
  docs/monitoring/assets/add-query.png
  docs/monitoring/assets/create-dashboard.png
  docs/monitoring/assets/edit-dashboard.png
  docs/monitoring/assets/gauge-dashboard-type.png
  docs/monitoring/assets/green-dashboard.png
  docs/monitoring/assets/instant.png
  docs/monitoring/assets/min-max-values.png
  docs/monitoring/assets/new-dashboard.png
  docs/monitoring/assets/panel-title.png
  docs/monitoring/assets/red-dashboard.png
  docs/monitoring/assets/save-dashboard.png
  docs/monitoring/assets/save-note.png
  docs/monitoring/assets/stats-and-metrics.png
  docs/monitoring/assets/temperature-celsius.png
  docs/monitoring/assets/threshold.png
  milv.config.yaml
Labels: area/documentation, area/monitoring, quality/content

#5259 Add a minor lg fix
  docs/monitoring/08-01-observe-application-metrics.md
Labels: area/documentation

#5271 Bump Helm-Broker, introduce documentation enabled flag to the controller
  resources/helm-broker/templates/deploy.yaml
  resources/helm-broker/values.yaml
Labels: area/service-catalog

#5279 Fix links
  components/console-backend-service/docs/security.md
Labels: area/documentation

#5298 Fix link
  docs/kyma/04-02-local-installation.md
Labels: area/documentation

#5302 Fix links to GraphQL docs
  docs/console/03-02-console-backend-service.md
  docs/security/03-03-graphql-request-flow.md
Labels: area/documentation

#5258 Add alert rules tutorial
  docs/monitoring/03-01-alertmanager.md
  docs/monitoring/08-03-define-alerting-rules.md
  docs/monitoring/assets/fired-alert.png
  docs/monitoring/assets/rules-dashboard.png
Labels: area/documentation

#5286 Update images for Compass components
  resources/compass/charts/gateway/templates/gateway-certs.yaml
  resources/compass/charts/gateway/templates/gateway.yaml
  resources/compass/templates/migrator-job.yaml
  resources/compass/values.yaml
Labels: WIP, enhancement

#5291 Improvements in configuration lists for AC components
  components/application-connectivity-validator/README.md
  components/application-gateway/README.md
  components/application-operator/README.md
  components/application-registry/README.md
  components/connectivity-certs-controller/README.md
  components/connector-service/README.md
  components/event-service/README.md
  resources/application-connector/charts/application-registry/README.md
  resources/application-connector/charts/connectivity-certs-controller/README.md
  resources/application-connector/charts/connector-service/README.md
Labels: area/application-connector, area/documentation, quality/content

#5300 Add PreloadURL to common types
  common/microfrontend-client/pkg/apis/ui/v1alpha1/types.go
Labels: area/console

#5314 Update the EventBus E2E tester and subscriber
  tests/event-bus/Gopkg.lock
  tests/event-bus/Gopkg.toml
Labels: area/eventing

#5316 Fix links in monitoring documentation
  docs/monitoring/03-01-alertmanager.md
  docs/monitoring/08-03-define-alerting-rules.md
Labels: area/documentation

#5249 Performance test for event-bus component
  tests/perf/components/event-bus/event-bus-perf-test.js
  tests/perf/prerequisites/event-bus/event-activation.yaml
  tests/perf/prerequisites/event-bus/event-subscriber.yaml
  tests/perf/prerequisites/event-bus/event-subscription.yaml
  tests/perf/prerequisites/event-bus/namespace.yaml
  tests/perf/prerequisites/event-bus/setup.sh
Labels: area/eventing

#5292 Add compass and compass runtime agent installer CRs
  installation/resources/README.md
  installation/resources/installer-cr-cluster-compass.yaml.tpl
  installation/resources/installer-cr-cluster-runtime.yaml.tpl
  installation/scripts/release-generate-kyma-installer-artifacts.sh
Labels: area/installation, enhancement

#5299 Move Kiali documentantion to Service Mesh docs
  docs/kiali/01-01-kiali.md
  docs/kiali/02-01-kiali.md
  docs/service-mesh/01-01-service-mesh.md
  docs/service-mesh/03-01-istio-setup-in-kyma.md
  docs/service-mesh/03-02-istio-patch.md
  docs/service-mesh/03-04-sidecar-proxy-injection.md
  docs/service-mesh/05-01-kiali.md
  resources/core/charts/docs/charts/content-ui/templates/docs-components-kiali-cdt.yaml
Labels: area/documentation

#5263 Fix dropdowns in console core
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#5323 Add tests.enabled values to the charts
  resources/application-connector/charts/application-registry/templates/tests/test.yaml
  resources/application-connector/charts/application-registry/values.yaml
  resources/application-connector/templates/tests/rbac.yaml
  resources/core/charts/console-backend-service/templates/tests/rbac.yaml
  resources/core/charts/console-backend-service/templates/tests/test.yaml
  resources/core/charts/console-backend-service/values.yaml
  resources/core/charts/console/templates/test/rbac.yaml
  resources/core/charts/console/templates/test/test.yaml
  resources/core/charts/console/values.yaml
  resources/core/templates/tests/rbac-external-solution.yaml
  resources/core/templates/tests/rbac.yaml
  resources/core/templates/tests/test-external-solution.yaml
  resources/core/templates/tests/test.yaml
  resources/core/values.yaml
Labels: area/application-connector, area/ci, enhancement

#5270 Add Compass Runtime Agent acceptance tests
  resources/compass-runtime-agent/templates/tests/cluster-role-binding.yaml
  resources/compass-runtime-agent/templates/tests/role-binding.yaml
  resources/compass-runtime-agent/templates/tests/service-account.yaml
  resources/compass-runtime-agent/templates/tests/service.yaml
  resources/compass-runtime-agent/templates/tests/test-runtime-agent-integration.yaml
  resources/compass-runtime-agent/values.yaml
  tests/compass-runtime-agent/.dockerignore
  tests/compass-runtime-agent/Dockerfile
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/Gopkg.toml
  tests/compass-runtime-agent/Makefile
  tests/compass-runtime-agent/before-commit.sh
  tests/compass-runtime-agent/scripts/entrypoint.sh
  tests/compass-runtime-agent/scripts/run_tests.sh
  tests/compass-runtime-agent/test/apitests/main_test.go
  tests/compass-runtime-agent/test/mock/applicationserver.go
  tests/compass-runtime-agent/test/mock/basicauthhandler.go
  tests/compass-runtime-agent/test/mock/csrfhandler.go
  tests/compass-runtime-agent/test/mock/errorhandler.go
  tests/compass-runtime-agent/test/mock/headershandler.go
  tests/compass-runtime-agent/test/mock/oauthhandler.go
  tests/compass-runtime-agent/test/mock/queryparamshandler.go
  tests/compass-runtime-agent/test/runtimeagent/suite.go
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_suite_test.go
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_test.go
  tests/compass-runtime-agent/test/testkit/applications/api.go
  tests/compass-runtime-agent/test/testkit/applications/app.go
  tests/compass-runtime-agent/test/testkit/applications/eventapi.go
  tests/compass-runtime-agent/test/testkit/applications/nameresolver.go
  tests/compass-runtime-agent/test/testkit/assertions/api_access_checker.go
  tests/compass-runtime-agent/test/testkit/assertions/k8s_resource_checker.go
  tests/compass-runtime-agent/test/testkit/compass/client.go
  tests/compass-runtime-agent/test/testkit/compass/query.go
  tests/compass-runtime-agent/test/testkit/config.go
  tests/compass-runtime-agent/test/testkit/graphql/graphqlizer.go
  tests/compass-runtime-agent/test/testkit/util/util.go
  tests/compass-runtime-agent/test/testkit/wait.go
Labels: area/application-connector, enhancement

#5340 Fix initialization of dynamic client
  components/application-registry/cmd/applicationregistry/handlers.go
  components/compass-runtime-agent/cmd/init.go
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector

#5322 Add label definition details page
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#5296 Add the upgrade tests for the EventBus publish V2 APIs
  tests/end-to-end/upgrade/pkg/tests/event-bus/event_bus.go
Labels: area/eventing

#5303 Bump e2e upgrade tests image
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
Labels: area/eventing

#5360 Fix dead links
  docs/helm-broker/06-01-clusteraddonsconfiguration.md
  docs/helm-broker/06-02-addonsconfiguration.md
Labels: area/documentation, bug

#5344 Fine tune eventing docs
  docs/event-bus/01-01-event-bus.md
  docs/event-bus/02-01-event-bus.md
  docs/event-bus/03-01-concepts.md
  docs/event-bus/10-02-troubleshooting-kyma-tracing.md
  docs/event-bus/assets/configure-consume-events.svg
  docs/event-bus/assets/event-validation.svg
  docs/event-bus/assets/publish-events.svg
  docs/tracing/02-01-tracing.md
Labels: area/documentation

#5361 Update codeowners file
  CODEOWNERS
Labels: area/documentation

#5238 Tweak event-bus resource consumption
  resources/event-bus/values.yaml
Labels: area/eventing

#5326 Add to Helm Broker prometheus/graphana metrics
  resources/helm-broker/templates/deploy.yaml
  resources/helm-broker/templates/metrics.yaml
  resources/helm-broker/values.yaml
  resources/monitoring/charts/grafana/dashboards/helm-broker-dashboard.json
Labels: area/service-catalog

#5274 Enable addons-ui in namespace scope
  installation/scripts/minikube.ps1
  installation/scripts/minikube.sh
  resources/core/charts/api-controller/templates/apis-microfrontend.yaml
  resources/helm-broker/charts/add-ons-ui/Chart.yaml
  resources/helm-broker/charts/add-ons-ui/templates/add-ons-microfrontend.yaml
  resources/helm-broker/charts/add-ons-ui/templates/destination-rule.yaml
  resources/helm-broker/charts/addons-ui/.helmignore
  resources/helm-broker/charts/addons-ui/Chart.yaml
  resources/helm-broker/charts/addons-ui/templates/_helpers.tpl
  resources/helm-broker/charts/addons-ui/templates/addons-clustermicrofrontend.yaml
  resources/helm-broker/charts/addons-ui/templates/addons-microfrontend.yaml
  resources/helm-broker/charts/addons-ui/templates/configmap.yaml
  resources/helm-broker/charts/addons-ui/templates/deployment.yaml
  resources/helm-broker/charts/addons-ui/templates/destination-rule.yaml
  resources/helm-broker/charts/addons-ui/templates/service.yaml
  resources/helm-broker/charts/addons-ui/templates/virtualservice.yaml
  resources/helm-broker/charts/addons-ui/values.yaml
  resources/helm-broker/requirements.yaml
  resources/helm-broker/values.yaml
Labels: enhancement

#5324 Fix fd-panel-title appearance
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#5367 Update golint lib in cms-services
  CODEOWNERS
  components/asset-metadata-service/before-commit.sh
  components/cms-services/Gopkg.lock
  components/cms-services/Gopkg.toml
  components/cms-services/before-commit.sh
Labels: area/ci, bug

#5366 Update the golint dependency reference
  components/event-bus/Gopkg.lock
  components/event-bus/Gopkg.toml
  components/event-bus/before-commit.sh
  components/event-service/Gopkg.lock
  components/event-service/Gopkg.toml
  components/event-service/before-commit.sh
  components/k8s-dashboard-proxy/Gopkg.lock
  components/k8s-dashboard-proxy/Gopkg.toml
  components/k8s-dashboard-proxy/before-commit.sh
  tests/end-to-end/kubeless-integration/Gopkg.lock
  tests/end-to-end/kubeless-integration/Gopkg.toml
  tests/end-to-end/kubeless-integration/Makefile
  tests/event-bus/Gopkg.lock
  tests/event-bus/Gopkg.toml
  tests/event-bus/before-commit.sh
  tests/integration/event-service/Gopkg.lock
  tests/integration/event-service/Gopkg.toml
  tests/integration/event-service/Makefile
  tests/kubeless/Gopkg.lock
  tests/kubeless/Gopkg.toml
  tests/kubeless/Makefile
Labels: area/eventing

#5342 Add grafana backendmodule
  resources/monitoring/charts/grafana/templates/backendmodule.yaml
Labels: area/console

#5359 Add "show istio proxy logs" toggle
  resources/logging/charts/log-ui/values.yaml
Labels: area/console, enhancement

#5338 Compass Runtime Agent Runtime and Apps labeling
  resources/compass-runtime-agent/templates/tests/test-runtime-agent-integration.yaml
  resources/compass-runtime-agent/values.yaml
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/Gopkg.toml
  tests/compass-runtime-agent/test/runtimeagent/suite.go
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_suite_test.go
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_test.go
  tests/compass-runtime-agent/test/testkit/applications/app.go
  tests/compass-runtime-agent/test/testkit/assertions/api_access_checker.go
  tests/compass-runtime-agent/test/testkit/assertions/k8s_resource_checker.go
  tests/compass-runtime-agent/test/testkit/compass/client.go
  tests/compass-runtime-agent/test/testkit/compass/model.go
  tests/compass-runtime-agent/test/testkit/compass/query.go
  tests/compass-runtime-agent/test/testkit/compass/scenarios.go
  tests/compass-runtime-agent/test/testkit/config.go
  tests/compass-runtime-agent/test/testkit/graphql/graphqlizer.go
Labels: area/application-connector

#5328 Bump compass director
  resources/compass/values.yaml
Labels: enhancement

#5334 Fix dropdowns behaviour on outsideclick event in console core
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#5385 Fix a broken link
  docs/event-bus/03-06-configure-default-channelprovisioner.md
Labels: area/documentation, bug

#5356 Upgrade event bus dependencies to kubernetes 1.12.6
  components/event-bus/Gopkg.lock
  components/event-bus/Gopkg.toml
  components/event-bus/api/push/eventing.kyma-project.io/v1alpha1/register.go
  components/event-bus/cmd/event-publish-service/handlers/publish.go
  components/event-bus/internal/knative/subscription/controller/subscription/reconcile.go
  components/event-bus/internal/knative/subscription/controller/subscription/reconcile_test.go
  components/event-bus/internal/knative/util/kn-eventing_test.go
  components/event-bus/internal/knative/util/kn-subscription-builder.go
  resources/event-bus/charts/event-publish-service/templates/deployment.yaml
  resources/event-bus/charts/subscription-controller/templates/deployment.yaml
Labels: area/eventing

#5330 Add E2E-Tests for the EventBus publish API V2
  tests/event-bus/e2e-tester/e2e-tester.go
Labels: area/eventing

#5331 Update the EventBus E2E test image
  resources/event-bus/templates/tests/test.yaml
  resources/event-bus/values.yaml
Labels: area/eventing

#5397 Update dependencies versions in AC components
  components/application-gateway/Gopkg.lock
  components/application-gateway/Gopkg.toml
  resources/application-connector/values.yaml
  tests/application-connector-tests/Gopkg.lock
  tests/application-connector-tests/Gopkg.toml
  tests/application-operator-tests/Gopkg.lock
  tests/application-operator-tests/Gopkg.toml
  tests/application-registry-tests/Gopkg.lock
  tests/application-registry-tests/Gopkg.toml
  tests/connection-token-handler-tests/Gopkg.lock
  tests/connection-token-handler-tests/Gopkg.toml
  tests/connector-service-tests/Gopkg.toml
Labels: area/application-connector

#5401 Add instructions for installing Kyma on Gardener shoot cluster
  docs/kyma/04-03-cluster-installation.md
Labels: area/documentation, area/installation

#5377 Disable metrics dashboard button if grafana is disabled
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
Labels: area/console, bug

#5358 Delete API from API Details View
  resources/core/charts/console/values.yaml
Labels: area/console, enhancement

#5301 Add preload for microfrontends and console-backend-service
  components/console-backend-service/Gopkg.lock
  components/console-backend-service/Gopkg.toml
  components/console-backend-service/internal/domain/ui/clustermicrofrontend_converter.go
  components/console-backend-service/internal/domain/ui/clustermicrofrontend_converter_test.go
  components/console-backend-service/internal/domain/ui/clustermicrofrontend_resolver_test.go
  components/console-backend-service/internal/domain/ui/clustermicrofrontend_service_test.go
  components/console-backend-service/internal/gqlschema/models_gen.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
  resources/helm-broker/charts/addons-ui/templates/addons-clustermicrofrontend.yaml
  resources/helm-broker/charts/addons-ui/templates/addons-microfrontend.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/templates/brokers-microfrontend.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/templates/catalog-microfrontend.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/templates/instances-microfrontend.yaml
Labels: area/console

#5416 Add waiter for the testing addons
  installation/scripts/testing-common.sh
  installation/scripts/testing.sh
Labels: area/ci, bug

#5402 Upgrade Istio to 1.2.4
  resources/istio-init/Chart.yaml
  resources/istio-init/files/crd-10.yaml
  resources/istio-init/files/crd-11.yaml
  resources/istio-init/templates/serviceaccount.yaml
  resources/istio-init/values.yaml
  resources/istio-kyma-patch/values.yaml
  resources/istio/Chart.yaml
  resources/istio/README.md
  resources/istio/charts/certmanager/Chart.yaml
  resources/istio/charts/galley/Chart.yaml
  resources/istio/charts/gateways/Chart.yaml
  resources/istio/charts/gateways/values.yaml
  resources/istio/charts/grafana/Chart.yaml
  resources/istio/charts/grafana/dashboards/istio-performance-dashboard.json
  resources/istio/charts/istiocoredns/Chart.yaml
  resources/istio/charts/kiali/Chart.yaml
  resources/istio/charts/mixer/Chart.yaml
  resources/istio/charts/mixer/values.yaml
  resources/istio/charts/nodeagent/Chart.yaml
  resources/istio/charts/pilot/Chart.yaml
  resources/istio/charts/pilot/values.yaml
  resources/istio/charts/prometheus/Chart.yaml
  resources/istio/charts/security/Chart.yaml
  resources/istio/charts/security/templates/deployment.yaml
  resources/istio/charts/sidecarInjectorWebhook/Chart.yaml
  resources/istio/charts/sidecarInjectorWebhook/templates/poddisruptionbudget.yaml
  resources/istio/charts/tracing/Chart.yaml
  resources/istio/requirements.yaml
  resources/istio/values.yaml
Labels: area/service-mesh, enhancement, security/high

#5423 Remove <br /> from one of doc
  docs/kyma/04-03-cluster-installation.md
Labels: area/documentation, bug

#5427 Fix a dead link in Istio Setup in Kyma
  docs/service-mesh/03-01-istio-setup-in-kyma.md
Labels: area/documentation, bug

#5425 Introduce api-gateway chart
  CODEOWNERS
  installation/resources/installer-cr-cluster-runtime.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  resources/api-gateway/.helmignore
  resources/api-gateway/Chart.yaml
  resources/api-gateway/README.md
  resources/api-gateway/files/crd-gates.yaml
  resources/api-gateway/templates/_helpers.tpl
  resources/api-gateway/templates/crd-configmap.yaml
  resources/api-gateway/templates/crd-job.yaml
  resources/api-gateway/templates/crd-rbac.yaml
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/templates/rbac.yaml
  resources/api-gateway/values.yaml
Labels: area/installation, area/security, area/service-mesh

#5312 Create a troubleshooting guide for Application Connector
  docs/application-connector/10-01-overview.md
  docs/application-connector/10-02-application-gateway-troubleshooting.md
  docs/application-connector/10-03-application-registry-troubleshooting.md
  docs/application-connector/10-04-connector-service-troubleshooting.md
  docs/application-connector/tmp.md
Labels: area/application-connector, area/documentation, quality/content

#5418 Uncomment Event Bus Subscription Controller tests
  components/event-bus/internal/knative/subscription/controller/subscription/reconcile_test.go
Labels: area/eventing

#5411 Improve logging and add retry to Application Connector Tests
  components/application-operator/cmd/manager/manager.go
  components/application-operator/pkg/controller/reconciler.go
  resources/application-connector/values.yaml
  tests/application-connector-tests/test/applicationaccess/suite.go
  tests/application-connector-tests/test/testkit/retry.go
  tests/application-connector-tests/test/testkit/services/client.go
  tests/application-connector-tests/test/testkit/util/util.go
Labels: area/application-connector, bug, test-failing

#5435 Compass Postgres secret generated only on install
  resources/compass/charts/postgresql/templates/secrets.yaml
Labels: bug

#5438 Move Compass Connector chart to Kyma
  resources/compass/charts/connector/templates/certs-setup-job.yaml
  resources/compass/charts/connector/templates/certs-setup-role-binding.yaml
  resources/compass/charts/connector/templates/deployment.yaml
  resources/compass/charts/connector/templates/role-binding.yaml
  resources/compass/charts/connector/templates/service-account.yaml
  resources/compass/charts/connector/values.yaml
  resources/compass/values.yaml
Labels: enhancement

#5426 Helm broker authorization docs
  docs/helm-broker/03-03-create-addons-repo.md
  docs/helm-broker/06-01-clusteraddonsconfiguration.md
  docs/helm-broker/06-02-addonsconfiguration.md
  milv.config.yaml
Labels: area/documentation, area/service-catalog

#5469 Update Kubernetes version to 1.13
  docs/kyma/04-02-local-installation.md
  docs/kyma/04-03-cluster-installation.md
  docs/kyma/04-04-use-your-own-domain.md
  installation/scripts/minikube.ps1
  installation/scripts/minikube.sh
Labels: area/cluster, area/documentation, area/installation, enhancement

#5488 Skip failing HelmBroker test
  tests/acceptance/servicecatalog/helpers_test.go
  tests/acceptance/servicecatalog/servicecatalog_test.go
Labels: area/service-catalog

#5468 Change order of arguments to match the function in Connector Service
  components/connector-service/cmd/connectorservice/handlers.go
  resources/application-connector/values.yaml
Labels: area/application-connector, bug

#5440 Update k8s resources and use components with updated k8s dependencies
  resources/core/charts/api-controller/templates/deployment.yaml
  resources/core/charts/api-controller/templates/pre-install-rbac.yaml
  resources/core/charts/api-controller/templates/tests/rbac.yaml
  resources/core/charts/apiserver-proxy/templates/deployment.yaml
  resources/core/charts/apiserver-proxy/templates/generate-certs-job.yaml
  resources/core/charts/apiserver-proxy/templates/remove-generate-certs-job.yaml
  resources/core/charts/apiserver-proxy/templates/service-ssl.yaml
  resources/core/charts/cluster-users/templates/clusterroles-coreos-com.yaml
  resources/core/charts/cluster-users/templates/clusterroles-istio-io.yaml
  resources/core/charts/cluster-users/templates/clusterroles-k8s-io.yaml
  resources/core/charts/cluster-users/templates/clusterroles-knative-eventing.yaml
  resources/core/charts/cluster-users/templates/clusterroles-knative-serving.yaml
  resources/core/charts/cluster-users/templates/clusterroles-kubeless-io.yaml
  resources/core/charts/cluster-users/templates/clusterroles-kyma-project-io.yaml
  resources/core/charts/cluster-users/templates/clusterroles-ory-sh.yaml
  resources/core/charts/cluster-users/templates/rbac-roles.yaml
  resources/core/charts/iam-kubeconfig-service/templates/deployment.yaml
  resources/core/values.yaml
  resources/dex/templates/dex-deployment.yaml
  resources/dex/templates/dex-rbac-role.yaml
  resources/dex/values.yaml
  resources/istio-kyma-patch/values.yaml
  resources/xip-patch/values.yaml
  tools/kyma-installer/kyma.Dockerfile
Labels: area/installation, area/service-mesh, enhancement

#5477 Move Compass Connector Tests charts to Kyma
  resources/compass/charts/connector/templates/tests/test-connector.yaml
  resources/compass/values.yaml
Labels: area/application-connector, enhancement

#4924 Knative function controller resources
  CODEOWNERS
  resources/function-controller/Chart.yaml
  resources/function-controller/README.md
  resources/function-controller/requirements.yaml
  resources/function-controller/templates/_helpers.tpl
  resources/function-controller/templates/cluster_role.yaml
  resources/function-controller/templates/cluster_role_binding.yaml
  resources/function-controller/templates/config.yaml
  resources/function-controller/templates/function-build-service-account.yaml
  resources/function-controller/templates/function_crd.yaml
  resources/function-controller/templates/manager.yaml
  resources/function-controller/templates/secret.yaml
  resources/function-controller/templates/service.yaml
  resources/function-controller/templates/serviceaccount.yaml
  resources/function-controller/values.yaml
Labels: area/serverless

#5290 Bump ORY components
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/templates/deployment.yaml
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/values.yaml
  resources/ory/charts/oathkeeper/templates/configmap-config-demo.yaml
  resources/ory/charts/oathkeeper/values.yaml
  resources/ory/values.yaml
Labels: area/security

#5471 Support old way of passing headers and query parameters
  components/application-registry/internal/externalapi/model.go
  components/application-registry/internal/externalapi/model_test.go
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#5478 Add tests for deprecated API in Application Registry
  resources/application-connector/values.yaml
  tests/application-registry-tests/before-commit.sh
  tests/application-registry-tests/test/k8stests/k8sresource_test.go
  tests/application-registry-tests/test/testkit/model.go
Labels: area/application-connector, enhancement

#5503 Update Compass components
  resources/compass/values.yaml
Labels: enhancement

#5506 Bump acceptance test image
  resources/core/values.yaml
Labels: area/service-catalog
