Repository kyma-project/kyma, pull requests merged in 2019-10, with the labels that each got.

#5833 Update dependencies for Runtime Agent
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/Gopkg.toml
Labels: enhancement

#5834 Use develop images of Application Connector
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  resources/compass/values.yaml
Labels: area/application-connector

#5854 Add Vary: Origin header to DEX
  resources/dex/templates/dex-virtual-service.yaml
Labels: area/console, area/security

#5821 Bump HB after fixing etcd timeout
  resources/helm-broker/templates/deploy.yaml
  resources/helm-broker/templates/rbac.yaml
  resources/helm-broker/values.yaml
Labels: area/service-catalog

#5859 Add Minikube DNS error troubleshooting
  docs/kyma/10-08-cant-download-img.md
Labels: area/documentation, enhancement

#5871 Fix 10-08-cant-download-img.md document
  docs/kyma/10-08-cant-download-img.md
Labels: area/documentation, bug

#5877 Bump api-gateway image
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/values.yaml
Labels: area/security, enhancement

#5883 Move description subsection to info section, remove initial tags section
  docs/application-connector/assets/connectorapi.yaml
  docs/application-connector/assets/eventsapi.yaml
  docs/application-connector/assets/metadataapi.yaml
Labels: area/application-connector, area/documentation

#5895 Update readme for kyma-operator
  components/kyma-operator/README.md
Labels: area/documentation

#5889 Update documentation of console
  docs/README.md
  docs/console/03-01-uiextensibility.md
  docs/console/03-02-console-backend-service.md
  docs/console/03-03-CR-security-guidelines.md
  docs/console/03-04-headless-cms-in-console.md
  docs/console/05-01-console.md
  docs/console/06-01-microfrontend.md
  docs/console/06-02-clustermicrofrontend.md
  docs/console/06-03-backendmodule.md
Labels: area/documentation

#5870 Wait for Application to be deployed in Compass Runtime Agent tests
  resources/compass-runtime-agent/templates/tests/test-runtime-agent-integration.yaml
  resources/compass-runtime-agent/values.yaml
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/test/runtimeagent/suite.go
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_test.go
  tests/compass-runtime-agent/test/testkit/config.go
Labels: area/application-connector

#5890 Improve stability of Application Operator Tests
  resources/application-connector/values.yaml
  tests/application-gateway-tests/Gopkg.lock
  tests/application-gateway-tests/test/executor/testkit/registry/client.go
  tests/integration/event-service/Gopkg.lock
  tests/integration/event-service/test/apitests/gateway_events_test.go
  tests/integration/event-service/test/apitests/gateway_health_test.go
  tests/integration/event-service/test/apitests/main_test.go
  tests/integration/event-service/test/testkit/wait.go
Labels: area/application-connector

#5855 Fix code and notes rendering
  docs/application-connector/08-02-get-client-certificate.md
  docs/application-connector/08-03-register-manage-services.md
  docs/application-connector/08-05-trigger-lambda-with-event.md
  docs/application-connector/08-06-call-registered-service-from-kyma.md
  docs/application-connector/08-08-renew-client-cert.md
  docs/application-connector/08-10-rotate-root-ca.md
  docs/event-bus/03-03-service-programming-model.md
  docs/event-bus/03-06-configure-default-channelprovisioner.md
  docs/event-bus/07-01-cli-reference.md
  docs/headless-cms/08-01-add-new-documentation-to-console.md
  docs/helm-broker/03-03-create-addons-repo.md
  docs/kyma/03-03-charts.md
  docs/kyma/03-04-deploy-private-registry.md
  docs/kyma/04-03-marketplace-installation.md
  docs/kyma/04-04-cluster-installation.md
  docs/kyma/04-06-use-your-own-image.md
  docs/kyma/04-11-update.md
  docs/kyma/08-03-local-develop-no-docker.md
  docs/kyma/08-04-publish-service-image-and-deploy.md
  docs/logging/03-01-access-logs.md
  docs/logging/08-01-configure-logcollector.md
  docs/monitoring/08-02-observe-application-metrics.md
  docs/monitoring/08-03-create-and-configure-grafana-dashboard.md
  docs/monitoring/08-04-define-alerting-rules.md
  docs/monitoring/08-05-send-notifications.md
  docs/security/03-01-iam-kubeconfig-service.md
  docs/security/03-06-oauth2-server.md
  docs/service-catalog/07-01-cli-reference.md
Labels: area/core-and-supporting, area/documentation

#5850 Correct metric type numbering
  docs/asset-store/11-01-asset-store-controller.md
  docs/asset-store/11-02-asset-metadata-service.md
  docs/asset-store/11-03-asset-upload-service.md
  docs/asset-store/11-04-minio.md
  docs/headless-cms/11-01-cms-controller-manager.md
  docs/headless-cms/11-02-asyncapi-service.md
  docs/kyma/04-04-cluster-installation.md
  docs/kyma/16-01-try-out-kyma.md
  docs/service-catalog/15-01-overview.md
  docs/service-catalog/15-02-catalog-view.md
  docs/service-catalog/15-03-instances-view.md
  docs/service-catalog/15-04-specifications-in-console-ui.md
  docs/service-catalog/17-01-service-brokers.md
  docs/service-catalog/17-02-gcp-broker.md
  docs/service-catalog/17-03-azure-broker.md
  docs/service-catalog/17-04-aws-broker.md
Labels: area/documentation, area/monitoring

#5947 Update variables
  docs/asset-store/08-02-gateway-azure-mode-set-up.md
  docs/asset-store/08-03-gateway-s3-mode-set-up.md
  docs/asset-store/08-04-gateway-oss-mode-set.md
Labels: area/core-and-supporting, area/documentation

#5698 Restructure Compass documents
  docs/compass/01-01-compass.md
  docs/compass/02-01-compass.md
  docs/compass/02-01-components.md
  docs/compass/02-02-components.md
  docs/compass/02-02-flow.md
  docs/compass/04-01-compass.md
  docs/compass/assets/architecture.svg
  docs/compass/assets/components.svg
  docs/compass/assets/kyma-mode1.svg
  docs/compass/assets/kyma-mode2.svg
Labels: area/documentation, enhancement

#5932 Improve apiserver-proxy integration test
  tests/integration/apiserver-proxy/test.sh
Labels: test-failing

#5951 Update to istio 1.2.7
  resources/istio-init/Chart.yaml
  resources/istio-init/values.yaml
  resources/istio-kyma-patch/values.yaml
  resources/istio/charts/certmanager/Chart.yaml
  resources/istio/charts/galley/Chart.yaml
  resources/istio/charts/gateways/Chart.yaml
  resources/istio/charts/grafana/Chart.yaml
  resources/istio/charts/istiocoredns/Chart.yaml
  resources/istio/charts/kiali/Chart.yaml
  resources/istio/charts/mixer/Chart.yaml
  resources/istio/charts/nodeagent/Chart.yaml
  resources/istio/charts/nodeagent/templates/daemonset.yaml
  resources/istio/charts/pilot/Chart.yaml
  resources/istio/charts/prometheus/Chart.yaml
  resources/istio/charts/security/Chart.yaml
  resources/istio/charts/sidecarInjectorWebhook/Chart.yaml
  resources/istio/charts/tracing/Chart.yaml
  resources/istio/requirements.yaml
  resources/istio/values.yaml
Labels: area/security, area/service-mesh

#5878 Bump up EventBus image to d90af2a
  resources/event-bus/values.yaml
Labels: area/eventing

#5955 Dex static connector override
  docs/security/08-03-add-connector.md
  resources/dex/templates/dex-config-map.yaml
  resources/dex/templates/dex-deployment.yaml
  resources/dex/templates/dex-rbac-role.yaml
  resources/dex/values.yaml
Labels: area/security, area/service-mesh

#5874 Bump Oathkeeper image to support alternative token location
  resources/ory/charts/oathkeeper/values.yaml
  resources/ory/values.yaml
Labels: WIP, enhancement

#5952 Disable core and lambdas tests
  resources/core/values.yaml
Labels: area/console, test-failing

#5936 apiserver-proxy-integration-test bump
  resources/core/values.yaml
Labels: test-failing

#5975 Improve Service Catalog Overview document for custom resources
  docs/service-catalog/03-01-resources.md
Labels: area/documentation, enhancement

#5991 Fix env variables
  docs/asset-store/08-02-gateway-azure-mode-set-up.md
Labels: area/core-and-supporting, area/documentation

#5986 Stabilize `expose API` UI test
  resources/core/values.yaml
Labels: test-missing

#5958 Improve tracing architecture documentation
  docs/tracing/02-01-tracing.md
  docs/tracing/03-05-search-traces.md
  docs/tracing/assets/tracing-architecture.svg
Labels: area/documentation, area/tracing

#5983 Adjust api-controller tests to use generic makefile
  tests/integration/api-controller/Dockerfile
  tests/integration/api-controller/Makefile
  tests/integration/api-controller/apicontroller/main_test.go
  tests/integration/api-controller/before-commit.sh
Labels: area/ci, enhancement

#5896 Improved installation stability and chart fixes
  components/kyma-operator/pkg/kymahelm/kyma-helm-client.go
  installation/scripts/testing.sh
  resources/jaeger/templates/deployment.yaml
  resources/logging/templates/loki/pvc.yaml
  resources/logging/values.yaml
  tests/integration/logging/test-logging.go
Labels: area/cluster, area/installation, area/logging, area/monitoring, enhancement

#6003 Bump Kyma Operator image
  tools/kyma-installer/kyma.Dockerfile
Labels: area/installation, enhancement

#5876 Allow listing and deleting functions
  components/console-backend-service/Gopkg.lock
  components/console-backend-service/README.md
  components/console-backend-service/internal/domain/root_resolver.go
  components/console-backend-service/internal/domain/serverless/convert/function.go
  components/console-backend-service/internal/domain/serverless/convert/function_test.go
  components/console-backend-service/internal/domain/serverless/disabled/resolver.go
  components/console-backend-service/internal/domain/serverless/function.go
  components/console-backend-service/internal/domain/serverless/function_service.go
  components/console-backend-service/internal/domain/serverless/function_service_test.go
  components/console-backend-service/internal/domain/serverless/pretty/kind.go
  components/console-backend-service/internal/domain/serverless/resolver.go
  components/console-backend-service/internal/gqlschema/models_gen.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
  components/console-backend-service/internal/resource/fake/service.go
  components/console-backend-service/internal/resource/service.go
  components/console-backend-service/internal/resource/unstructured.go
  components/console-backend-service/internal/resource/unstructured_test.go
  resources/core/charts/cluster-users/values.yaml
  resources/core/charts/console-backend-service/templates/cluster-role.yaml
  resources/function-controller/templates/backendmodule.yaml
Labels: area/console, area/serverless, enhancement

#5987 Add info how to list default metrics
  docs/asset-store/11-01-asset-store-controller.md
  docs/asset-store/11-02-asset-metadata-service.md
  docs/asset-store/11-03-asset-upload-service.md
  docs/asset-store/11-04-minio.md
  docs/headless-cms/11-01-cms-controller-manager.md
  docs/headless-cms/11-02-asyncapi-service.md
Labels: area/core-and-supporting, area/documentation, area/monitoring

#6009 Use api-controller test image from generic job
  resources/core/values.yaml
Labels: area/ci, enhancement

#5929 Reenable cluster-user tests
  resources/core/charts/cluster-users/templates/tests/test.yaml
  resources/core/charts/cluster-users/values.yaml
  resources/core/values.yaml
  resources/istio/charts/security/templates/enable-mesh-mtls.yaml
  tests/integration/cluster-users/sar-test.sh
Labels: area/security

#6016 Jaeger resource limit adjustments
  resources/jaeger/values.yaml
Labels: area/tracing, bug

#6015 Logging resource limit adjustments
  resources/logging/templates/loki/statefulset.yaml
  resources/logging/values.yaml
Labels: area/logging, bug

#5954 List functions
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
  resources/function-controller/templates/lambdas-microfrontend.yaml
Labels: area/console, area/serverless, enhancement

#6039 Disable leader election for Asset Store and CMS
  resources/assetstore/charts/asset-store-controller-manager/templates/deployment.yaml
  resources/cms/charts/cms-controller-manager/templates/deployment.yaml
Labels: area/core-and-supporting, enhancement

#5990 Create an example OpenAPI spec
  components/cms-services/cmd/asyncapi/openapi.yaml
  docs/asset-store/03-04-supported-webhooks.md
  docs/asset-store/assets/asset-metadata-service-openapi.yaml
  docs/asset-store/assets/asset-upload-service-openapi.yaml
  docs/asset-store/assets/example-openapi-service.yaml
  docs/asset-store/assets/metadata-service.yaml
  docs/asset-store/assets/mutation-service.yaml
  docs/asset-store/assets/validation-service.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-asset-store-cdt.yaml
Labels: area/core-and-supporting, area/documentation

#5697 Use Application name as a CR name in Compass Runtime Agent
  components/application-connectivity-validator/Gopkg.lock
  components/application-connectivity-validator/Gopkg.toml
  components/application-connectivity-validator/before-commit.sh
  components/application-connectivity-validator/cmd/applicationconnectivityvalidator/applicationconnectivityvalidator.go
  components/application-connectivity-validator/cmd/applicationconnectivityvalidator/options.go
  components/application-connectivity-validator/internal/validationproxy/handler.go
  components/application-connectivity-validator/internal/validationproxy/handler_test.go
  components/application-connectivity-validator/internal/validationproxy/mocks/ApplicationGetter.go
  components/application-connectivity-validator/internal/validationproxy/mocks/Cache.go
  components/application-operator/charts/application/templates/validator.yaml
  components/application-operator/charts/application/values.yaml
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/kyma/applications/converter.go
  components/compass-runtime-agent/internal/kyma/applications/converter_test.go
  components/compass-runtime-agent/internal/kyma/service.go
  components/compass-runtime-agent/internal/kyma/service_test.go
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/templates/tests/test-runtime-agent-integration.yaml
  resources/compass-runtime-agent/values.yaml
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_test.go
  tests/compass-runtime-agent/test/testkit/assertions/api_access_checker.go
  tests/compass-runtime-agent/test/testkit/assertions/k8s_resource_checker.go
Labels: WIP, area/application-connector

#6049 Bump service-catalog image
  resources/service-catalog/charts/catalog/templates/migration-job.yaml
  resources/service-catalog/charts/catalog/values.yaml
Labels: area/service-catalog

#6014 Add create function API
  components/console-backend-service/internal/domain/root_resolver.go
  components/console-backend-service/internal/domain/serverless/disabled/resolver.go
  components/console-backend-service/internal/domain/serverless/function.go
  components/console-backend-service/internal/domain/serverless/function_service.go
  components/console-backend-service/internal/domain/serverless/function_service_test.go
  components/console-backend-service/internal/domain/serverless/resolver.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
  components/console-backend-service/pkg/apis/ui/v1alpha1/zz_generated.deepcopy.go
  components/console-backend-service/pkg/client/clientset/versioned/fake/clientset_generated.go
  components/console-backend-service/pkg/client/clientset/versioned/typed/ui/v1alpha1/ui_client.go
Labels: area/serverless, enhancement

#5950 Incorporate enzyme tests for instance ui
  resources/core/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/values.yaml
Labels: area/console, priority/critical, test-failing, test-missing

#5984 fix knative-serving test
  tests/knative-serving/Makefile
  tests/knative-serving/knative_serving_test.go
Labels: area/quality, quality/testability

#6010 Improve documentation for event sample
  docs/application-connector/08-05-trigger-lambda-with-event.md
Labels: area/application-connector, area/documentation

#5943 Label runtime with events and console URLs
  components/compass-runtime-agent/cmd/main.go
  components/compass-runtime-agent/cmd/options.go
  components/compass-runtime-agent/internal/compass/clients_provider.go
  components/compass-runtime-agent/internal/compass/clients_provider_test.go
  components/compass-runtime-agent/internal/compass/connector/client_test.go
  components/compass-runtime-agent/internal/compass/director/client.go
  components/compass-runtime-agent/internal/compass/director/client_test.go
  components/compass-runtime-agent/internal/compass/director/mocks/ConfigClient.go
  components/compass-runtime-agent/internal/compass/director/mocks/DirectorClient.go
  components/compass-runtime-agent/internal/compass/director/model.go
  components/compass-runtime-agent/internal/compass/director/query.go
  components/compass-runtime-agent/internal/compass/mocks/ClientsProvider.go
  components/compass-runtime-agent/internal/compassconnection/init.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/compassconnection/supervisor.go
  components/compass-runtime-agent/internal/graphql/gql_client_testkit.go
  components/compass-runtime-agent/pkg/apis/compass/v1alpha1/types.go
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/templates/tests/test-runtime-agent-integration.yaml
  resources/compass-runtime-agent/values.yaml
  tests/compass-runtime-agent/Dockerfile
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/test/runtimeagent/suite.go
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_labels_test.go
  tests/compass-runtime-agent/test/testkit/compass/client.go
  tests/compass-runtime-agent/test/testkit/compass/model.go
  tests/compass-runtime-agent/test/testkit/compass/query.go
  tests/compass-runtime-agent/test/testkit/compass/scenarios.go
  tests/compass-runtime-agent/test/testkit/config.go
Labels: area/application-connector, enhancement

#6085 Compass runtime agent typo fix
  tests/compass-runtime-agent/README.md
Labels: area/documentation

#6029 Create Simple Function
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
  resources/function-controller/README.md
  resources/function-controller/templates/lambdas-microfrontend.yaml
Labels: area/console, area/serverless

#6083 fix broken helm links in docs
  docs/kyma/04-11-update.md
  docs/kyma/05-03-overrides.md
  docs/security/03-04-tiller-tls.md
Labels: area/documentation

#6079 Apiserver metrics&charts
  resources/monitoring/charts/grafana/dashboards/kubernetes-apiserver-dashboard.json
  resources/monitoring/charts/grafana/dashboards/kubernetes-apiserver-per-client-dashboard.json
Labels: area/monitoring, enhancement

#6081 Bump compass chart and update runtime agent tests
  resources/compass-runtime-agent/values.yaml
  resources/compass/charts/cockpit/values.yaml
  resources/compass/charts/director/config.yaml
  resources/compass/charts/director/scopes.yaml
  resources/compass/charts/director/templates/configmap.yaml
  resources/compass/charts/director/templates/deployment.yaml
  resources/compass/charts/gateway/templates/oathkeeper-rules.yaml
  resources/compass/charts/gateway/values.yaml
  resources/compass/configure-managed-gcp-postgresql.md
  resources/compass/templates/test.yaml
  resources/compass/values.yaml
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/Gopkg.toml
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_test.go
  tests/compass-runtime-agent/test/testkit/applications/app.go
  tests/compass-runtime-agent/test/testkit/compass/client.go
  tests/compass-runtime-agent/test/testkit/compass/query.go
  tests/compass-runtime-agent/test/testkit/graphql/graphqlizer.go
Labels: enhancement

#6058 Fix Asset Store flaky test
  resources/assetstore/templates/tests/rbac.yaml
  resources/assetstore/templates/tests/test.yaml
  resources/assetstore/values.yaml
  tests/asset-store/Gopkg.lock
  tests/asset-store/Gopkg.toml
  tests/asset-store/pkg/namespace/namespace.go
  tests/asset-store/pkg/resource/resource.go
  tests/asset-store/pkg/retry/retry.go
  tests/asset-store/pkg/retry/retry_test.go
  tests/asset-store/testsuite/asset.go
  tests/asset-store/testsuite/bucket.go
  tests/asset-store/testsuite/clusterasset.go
  tests/asset-store/testsuite/clusterbucket.go
  tests/asset-store/testsuite/common.go
  tests/asset-store/testsuite/testdata.go
  tests/asset-store/testsuite/testsuite.go
Labels: area/core-and-supporting, priority/critical, test-failing, test-missing

#6108 Update deps
  components/iam-kubeconfig-service/Gopkg.lock
  components/iam-kubeconfig-service/Gopkg.toml
Labels: area/security

#6098 Update logging parameter description
  docs/logging/05-01-logging.md
  resources/logging/values.schema.json
Labels: area/documentation, area/logging

#5858 Delete app- prefix from Application Operator generated services
  components/application-gateway/internal/k8sconsts/nameresolver.go
  components/application-gateway/internal/k8sconsts/nameresolver_test.go
  components/application-gateway/internal/proxy/proxy_test.go
  components/application-operator/charts/application/templates/policy.yaml
  components/application-operator/charts/application/templates/service.yaml
  components/application-operator/charts/application/templates/tests/test-acceptance.yaml
  components/application-operator/charts/application/templates/validator.yaml
  components/application-operator/charts/application/templates/virtual-service.yaml
  components/application-registry/internal/k8sconsts/nameresolver.go
  components/application-registry/internal/k8sconsts/nameresolver_test.go
  components/application-registry/internal/metadata/specification/service_test.go
  components/compass-runtime-agent/internal/k8sconsts/nameresolver.go
  components/compass-runtime-agent/internal/k8sconsts/nameresolver_test.go
  docs/application-connector/02-03-proxy-service.md
  docs/application-connector/03-03-consume-services.md
  docs/application-connector/08-06-call-registered-service-from-kyma.md
  docs/application-connector/10-02-application-gateway-troubleshooting.md
  resources/application-connector/charts/application-operator/values.yaml
  resources/application-connector/charts/application-registry/values.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/application-gateway-tests/test/executor/proxy/suite.go
  tests/application-gateway-tests/test/helmtest/proxy/tests/proxy_test.go
  tests/application-operator-tests/test/testkit/k8sresources_check.go
  tests/application-registry-tests/test/apitests/metadata_test.go
  tests/application-registry-tests/test/k8stests/k8sresource_test.go
  tests/compass-runtime-agent/test/testkit/applications/nameresolver.go
  tests/compass-runtime-agent/test/testkit/assertions/k8s_resource_checker.go
Labels: area/application-connector

#6107 Update Service Catalog Overview section
  docs/service-catalog/01-01-service-catalog.md
Labels: area/documentation, enhancement

#6038 Scenario Details View
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#6117 Bump Service Catalog image
  resources/service-catalog/charts/catalog/values.yaml
Labels: area/service-catalog

#6123 Bump provisioner image
  resources/compass/charts/provisioner/templates/deployment.yaml
  resources/compass/charts/provisioner/templates/role-binding.yaml
  resources/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  resources/compass/charts/provisioner/values.yaml
  resources/compass/values.yaml
Labels: enhancement

#6126 api-gateway tests codeowners update
  CODEOWNERS
  tests/integration/api-gateway/gateway-tests/main_test.go
Labels: area/security

#6055 Update main Kyma docs
  README.md
  docs/kyma/01-01-in-a-nutshell.md
  docs/kyma/01-05-how-to-start.md
  docs/kyma/01-05-kyma-and-knative.md
  docs/kyma/01-06-how-to-start.md
  docs/kyma/03-01-components.md
  docs/kyma/assets/kyma-knative.svg
Labels: WIP, area/documentation

#6128 Bump api-gateway integration tests image
  resources/api-gateway/values.yaml
Labels: area/security, enhancement

#6134 Add autoscaler section to Function Controller chart readme
  resources/function-controller/README.md
Labels: area/documentation, area/eventing

#6130 Change SBU image tag
  resources/service-catalog-addons/values.yaml
Labels: area/service-catalog

#6127 Bump images of Application Connector components
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  resources/compass/values.yaml
Labels: area/application-connector

#6145 Update alpine image
  tools/alpine-net/Dockerfile
Labels: area/security

#6137 Update GCP Broker screenshot and available classes
  docs/service-catalog/17-02-gcp-broker.md
  docs/service-catalog/assets/gcp-class.png
  resources/helm-broker/templates/default-addons-cfg.yaml
Labels: area/documentation

#5989 Prepare preview of kyma repo on kyma-project.io
  .kyma-project-io/build-preview.sh
  CODEOWNERS
Labels: area/community, area/core-and-supporting, area/documentation, enhancement

#6147 Bump alpine_net image tag
  installation/resources/tiller.yaml
  resources/kiali/values.yaml
Labels: area/security

#6158 Fix script for kyma-project.io preview
  .kyma-project-io/build-preview.sh
Labels: area/core-and-supporting, area/documentation, bug

#6112 Update Compass Provisioner chart
  resources/compass/charts/provisioner/templates/tests/role-binding.yaml
  resources/compass/charts/provisioner/templates/tests/service-account.yaml
  resources/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  resources/compass/charts/provisioner/values.yaml
  resources/compass/values.yaml
Labels: enhancement

#6077 Add-ons (namespaced) view doesn't refresh on namespace change
  resources/helm-broker/values.yaml
Labels: area/console, enhancement

#6169 Enable monitoring integration tests
  resources/monitoring/values.yaml
Labels: area/monitoring

#6170 Adjust Application Operator upgrade test
  tests/end-to-end/upgrade/chart/upgrade/templates/rbac.yaml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
  tests/end-to-end/upgrade/pkg/tests/application-operator/application_operator.go
Labels: area/application-connector

#6167 Add find query and update mutation, refactor folder structure, write first test using gomock
  components/console-backend-service/Gopkg.lock
  components/console-backend-service/Gopkg.toml
  components/console-backend-service/internal/domain/root_resolver.go
  components/console-backend-service/internal/domain/serverless/disabled/resolver.go
  components/console-backend-service/internal/domain/serverless/function.go
  components/console-backend-service/internal/domain/serverless/function/convert.go
  components/console-backend-service/internal/domain/serverless/function/convert_test.go
  components/console-backend-service/internal/domain/serverless/function/service.go
  components/console-backend-service/internal/domain/serverless/function/service_test.go
  components/console-backend-service/internal/domain/serverless/function_service.go
  components/console-backend-service/internal/domain/serverless/function_service_test.go
  components/console-backend-service/internal/domain/serverless/function_test.go
  components/console-backend-service/internal/domain/serverless/kind.go
  components/console-backend-service/internal/domain/serverless/mocks/function_service.go
  components/console-backend-service/internal/domain/serverless/pretty/kind.go
  components/console-backend-service/internal/domain/serverless/resolver.go
  components/console-backend-service/internal/domain/servicecatalogaddons/automock/addons_cfg_mutations.go
  components/console-backend-service/internal/domain/servicecatalogaddons/automock/addons_cfg_updater.go
  components/console-backend-service/internal/domain/servicecatalogaddons/automock/cluster_addons_cfg_mutations.go
  components/console-backend-service/internal/domain/servicecatalogaddons/automock/cluster_addons_cfg_updater.go
  components/console-backend-service/internal/gqlschema/models_gen.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
  components/console-backend-service/internal/resource/service.go
  components/console-backend-service/pkg/testing/prop/charset.go
  components/console-backend-service/pkg/testing/prop/properties.go
Labels: area/console, area/serverless, enhancement

#6086 Secure Compass Connector generate token mutations
  resources/compass/charts/connector/templates/deployment.yaml
  resources/compass/charts/connector/templates/service-role-binding.yaml
  resources/compass/charts/connector/templates/service.yaml
  resources/compass/charts/connector/templates/tests/test-connector.yaml
  resources/compass/charts/connector/values.yaml
  resources/compass/charts/director/templates/deployment.yaml
  resources/compass/charts/director/templates/service-account.yaml
  resources/compass/charts/gateway/templates/deployment.yaml
  resources/compass/values.yaml
  resources/core/charts/istio-rbac/values.yaml
Labels: area/security, enhancement

#6192 Fix a broken link
  resources/knative-build-init/README.md
Labels: area/documentation, bug

#6193 Fix a broken link
  resources/knative-build/README.md
Labels: area/documentation, bug
