Repository kyma-project/kyma, pull requests merged in 2019-01, with the labels that each got.

#2128 Fix go lint issues for load-test
  tools/load-test/load-test.go
Labels: area/serverless

#2130 Bump load test image
  tools/load-test/deploy/chart/load-test/values.yaml
Labels: area/serverless

#2063 Document installing Kyma with xip.io wildcard DNS
  docs/kyma/docs/032-inst-gke-installation.md
  docs/kyma/docs/036-inst-xip.io-domain.md
  docs/kyma/docs/042-gs-sample-service-deployment-to-cluster.md
  docs/kyma/docs/044-gs-local-develop-no-docker.md
  docs/kyma/docs/046-gs-publish-service-image-and-deploy.md
  docs/kyma/docs/048-gs-installation-overrides.md
Labels: area/documentation

#2143 Define BackendModule custom resources in Kyma components
  resources/application-connector/templates/backendmodule.yaml
  resources/core/charts/api-controller/templates/backendmodule.yaml
  resources/core/charts/console/templates/backendmodule.yaml
  resources/core/charts/kubeless/templates/backendmodule.yaml
  resources/core/charts/minio/templates/backendmodule.yaml
  resources/core/charts/service-catalog-addons/templates/backendmodule.yaml
  resources/service-catalog/templates/backendmodule.yaml
Labels: area/console, enhancement

#2155 Xip installation doc fix
  docs/kyma/docs/036-inst-xip.io-domain.md
Labels: area/documentation

#2138 Bump UI API Layer and acceptance tests
  resources/core/charts/ui-api/templates/cluster-role.yaml
  resources/core/templates/tests/rbac-ui-api-acceptance.yaml
  resources/core/templates/tests/test-ui-api-acceptance.yaml
  resources/core/values.yaml
Labels: area/console, enhancement

#2157 Fix skipping UI API Layer acceptance tests when Dex is disabled
  tests/ui-api-layer-acceptance-tests/internal/dex/dex.go
  tests/ui-api-layer-acceptance-tests/internal/domain/application/application_test.go
  tests/ui-api-layer-acceptance-tests/internal/domain/authentication/idppreset_test.go
  tests/ui-api-layer-acceptance-tests/internal/domain/k8s/limitrange_test.go
  tests/ui-api-layer-acceptance-tests/internal/domain/k8s/resourcequota_test.go
  tests/ui-api-layer-acceptance-tests/internal/domain/servicecatalog/servicecatalog_test.go
  tests/ui-api-layer-acceptance-tests/internal/domain/ui/backendmodule_test.go
  tests/ui-api-layer-acceptance-tests/internal/module/module.go
Labels: area/console, bug

#2158 Bump UI API Layer acceptance tests
  resources/core/values.yaml
Labels: area/console, bug

#2135 Extend documentation for lambda usage
  docs/serverless/docs/022-details-programming-model.md
Labels: area/documentation, area/serverless

#2141 Describe the Redis class provided by the Helm Broker
  docs/docs-build.yaml
  docs/service-brokers/helm-broker-service-classes/redis/docs.config.json
  docs/service-brokers/helm-broker-service-classes/redis/docs/overview.md
  docs/service-brokers/helm-broker-service-classes/redis/docs/plans-details.md
Labels: area/documentation, area/service-catalog

#2160 Add the documentation generation on kyma-project.io
  docs/Makefile
Labels: area/ci, area/community, area/documentation, enhancement

#2159 Update documentation image
  resources/core/charts/docs/charts/documentation/templates/docs-hb-service-classes.yaml
  resources/core/values.yaml
Labels: area/documentation

#2166 Application-connector fix for xip-io feature
  components/xip-patch/xip-patch.sh
  installation/resources/installer-config-cluster.yaml.tpl
  resources/application-connector/charts/application-operator/templates/controller.yaml
  resources/application-connector/charts/connector-service/templates/deployment.yaml
  resources/application-connector/charts/connector-service/templates/tests/test-acceptance.yaml
  resources/xip-patch/templates/job.yaml
  resources/xip-patch/templates/roles.yaml
Labels: area/service-mesh

#2171 Rename to Environments Controller
  docs/kyma/docs/034-inst-install-subcomponents.md
  resources/core/charts/namespace-controller/README.md
Labels: area/documentation

#2144 Support bind schemas and OSB fields in bundles
  components/helm-broker/Gopkg.lock
  components/helm-broker/Gopkg.toml
  components/helm-broker/internal/bind/resolver_example_test.go
  components/helm-broker/internal/bind/resolver_test.go
  components/helm-broker/internal/broker/broker_syncer.go
  components/helm-broker/internal/broker/broker_syncer_test.go
  components/helm-broker/internal/broker/catalog.go
  components/helm-broker/internal/broker/catalog_syncer_test.go
  components/helm-broker/internal/broker/server.go
  components/helm-broker/internal/bundle/form.go
  components/helm-broker/internal/bundle/form_test.go
  components/helm-broker/internal/bundle/helpers_test.go
  components/helm-broker/internal/bundle/loader.go
  components/helm-broker/internal/bundle/testdata/bundle-ignore-file-in-chart-dir.input.tgz
  components/helm-broker/internal/bundle/testdata/bundle-redis-0.0.1.golden/plans/enterprise/bind-instance-schema.json
  components/helm-broker/internal/bundle/testdata/bundle-redis-0.0.1.golden/plans/micro/bind-instance-schema.json
  components/helm-broker/internal/bundle/testdata/bundle-redis-0.0.1.input.tgz
  components/helm-broker/internal/config/config.go
  components/helm-broker/internal/model.go
  components/helm-broker/internal/storage/driver/etcd/entity_bundle.go
  components/helm-broker/internal/storage/storage.go
  docs/service-brokers/docs/005-overview-helm-broker.md
  docs/service-brokers/docs/012-configuration-helm-broker-bundles.md
Labels: area/service-catalog

#2176 Correct numbering of kyma docs
  components/helm-broker/README.md
  docs/api-gateway/docs/010-architecture-api-gateway.md
  docs/api-gateway/docs/020-details-security.md
  docs/api-gateway/docs/030-cr-api.md
  docs/application-connector/docs/010-architecture-application-connector.md
  docs/application-connector/docs/012-architecture-proxy-service.md
  docs/application-connector/docs/020-details-ac-security.md
  docs/application-connector/docs/021-details-access-ac-on-local.md
  docs/application-connector/docs/022-details-consume-services.md
  docs/application-connector/docs/023-details-metadata-service.md
  docs/application-connector/docs/024-details-pass-access-token-in-request-header.md
  docs/application-connector/docs/030-api-connector-service.md
  docs/application-connector/docs/031-api-metadata-service.md
  docs/application-connector/docs/032-api-event-service.md
  docs/application-connector/docs/040-gs-create-application.md
  docs/application-connector/docs/041-gs-get-client-certificate.md
  docs/application-connector/docs/042-gs-register-manage-services.md
  docs/application-connector/docs/043-gs-register-secured-api.md
  docs/application-connector/docs/044-gs-application-mapping.md
  docs/application-connector/docs/045-gs-trigger-lambda-with-event.md
  docs/application-connector/docs/046-gs-call-registered-service-from-kyma.md
  docs/application-connector/docs/050-cr-environment.md
  docs/application-connector/docs/051-cr-apllicationmapping.md
  docs/application-connector/docs/052-cr-tokenrequest.md
  docs/console/docs/020-cr-microfrontend.md
  docs/console/docs/021-cr-clustermicrofrontend.md
  docs/event-bus/docs/010-architecture-event-bus.md
  docs/event-bus/docs/020-details-concepts.md
  docs/event-bus/docs/021-details-event-flow-requirements.md
  docs/event-bus/docs/022-details-service-programming-model.md
  docs/event-bus/docs/023-details-troubleshooting.md
  docs/event-bus/docs/024-details-subscription-updates.md
  docs/event-bus/docs/040-cli-reference.md
  docs/kyma/docs/041-gs-sample-service-deployment-to-cluster.md
  docs/kyma/docs/042-gs-local-develop-no-docker.md
  docs/kyma/docs/043-gs-publish-service-image-and-deploy.md
  docs/kyma/docs/044-gs-installation-overrides.md
  docs/logging/docs/010-architecture-logging.md
  docs/logging/docs/020-details-access-oklog.md
  docs/monitoring/docs/010-architecture-monitoring.md
  docs/security/docs/010-architecture-auth.md
  docs/security/docs/020-details-kubecofig-generator.md
  docs/security/docs/021-details-add-connector.md
  docs/security/docs/022-details-manage-static-users.md
  docs/security/docs/023-details-update-tls-certificates.md
  docs/security/docs/030-cr-groups.md
  docs/security/docs/031-cr-idppresets.md
  docs/serverless/docs/010-architecture-serverless.md
  docs/serverless/docs/030-cli-reference.md
  docs/service-brokers/docs/001-overview-service-brokers.md
  docs/service-mesh/docs/020-details-sidecar-proxy-injection.md
  docs/service-mesh/docs/021-details-istio-patch.md
  docs/tracing/docs/010-architecture-tracing.md
  docs/tracing/docs/020-details-jaeger.md
  docs/tracing/docs/021-details-http-headers.md
  docs/tracing/docs/022-details-trace-comparison.md
  docs/tracing/docs/023-details-distributed-tracing.md
  milv.config.yaml
  resources/core/charts/configurations-generator/README.md
Labels: area/documentation

#2087 Make is-installed script not exit on error
  CODEOWNERS
  ci.Dockerfile
  docs/kyma/docs/033-inst-local-installation-scripts.md
  installation/scripts/is-installed.sh
  prow/kyma-integration-on-debian/deploy-and-test-kyma.sh
Labels: area/ci, area/installation, bug

#2178 Use bundles 0.2.0 - added testing bundles.
  docs/service-brokers/docs/003-overview-gcp-broker.md
  resources/core/charts/helm-broker/values.yaml
Labels: area/documentation, area/service-catalog, enhancement

#2185 Update doc image
  resources/core/values.yaml
Labels: area/documentation

#1991 Luigified Console
  docs/console/docs/assets/cmf-admin-section.png
  docs/console/docs/assets/mf-one-namespace.png
  resources/core/charts/console/values.yaml
  resources/core/charts/docs/charts/content-ui/Chart.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
  resources/core/charts/service-catalog-addons/charts/brokers-ui/Chart.yaml
  resources/core/charts/service-catalog-addons/charts/catalog-ui/Chart.yaml
  resources/core/charts/service-catalog-addons/charts/instances-ui/Chart.yaml
  resources/core/templates/tests/test-ui-acceptance.yaml
Labels: area/console

#2170 Bump UI API Layer with acceptance tests
  resources/core/values.yaml
Labels: area/console, enhancement

#2195 Fix connection-token-handler Gopkg.lock
  components/connection-token-handler/Gopkg.lock
Labels: area/application-connector, area/ci, wg/prow

#2177 Improve the overall SC documentation
  docs/service-catalog/docs/001-overview-service-catalog.md
  docs/service-catalog/docs/005-architecture-service-catalog.md
  docs/service-catalog/docs/010-details-resources.md
  docs/service-catalog/docs/011-details-add-service-to-the-catalog.md
  docs/service-catalog/docs/012-details-provisioning-and-binding.md
  docs/service-catalog/docs/014-details-backup-and-restore.md
  docs/service-catalog/docs/060-ui-overview.md
Labels: area/documentation, enhancement

#2201 Stabilize ui tests for variable network conditions
  resources/core/templates/tests/test-ui-acceptance.yaml
Labels: area/console, bug

#2220 Fix acceptance tests
  tests/acceptance/servicecatalog/binding_usage_test.go
Labels: area/service-catalog, bug, priority/critical

#2226 Remove function for calling Bash scripts from the Installer component
  components/installer/pkg/kymasources/kyma-packages_test.go
  components/installer/pkg/steps/mock.go
  components/installer/pkg/toolkit/command-script-exec.go
Labels: area/installation

#2154 Skip Application charts installation in acceptance tests if not needed
  tests/acceptance/application/suite/application.go
  tests/acceptance/servicecatalog/binding_usage_test.go
  tests/acceptance/servicecatalog/servicecatalog_test.go
  tests/application-operator-tests/test/testkit/k8sresources_client.go
  tests/application-registry-tests/Gopkg.lock
  tests/application-registry-tests/test/apitests/apispec_test.go
  tests/application-registry-tests/test/apitests/metadata_test.go
  tests/application-registry-tests/test/k8stests/k8sresource_test.go
  tests/application-registry-tests/test/testkit/k8sresources_check.go
  tests/application-registry-tests/test/testkit/k8sresources_client.go
  tests/connector-service-tests/Gopkg.lock
  tests/connector-service-tests/test/apitests/connector_test.go
  tests/connector-service-tests/test/testkit/k8sClient.go
Labels: area/application-connector, enhancement

#2218 Add docs how to install Knative from release
  docs/kyma/docs/038-inst-knative.md
Labels: area/documentation

#2193 Release 0.6.0-rc1 using Prow - dry run
  components/connection-token-handler/Gopkg.lock
  resources/application-connector/values.yaml
  resources/ark/values.yaml
  resources/core/values.yaml
  resources/dex/values.yaml
  resources/istio-kyma-patch/values.yaml
  resources/knative/values.yaml
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/service-catalog/values.yaml
  resources/xip-patch/values.yaml
  tests/acceptance/servicecatalog/binding_usage_test.go
  tests/logging/Makefile
Labels: area/ci, wg/prow

#2199 Add finalizers to Applications
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/methods.go
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/methods_test.go
  components/application-operator/pkg/controller/reconciler.go
  components/application-operator/pkg/controller/reconciler_test.go
  components/application-operator/pkg/kymahelm/application/mocks/ReleaseManager.go
  components/application-operator/pkg/kymahelm/application/releasemanager.go
  components/application-operator/pkg/kymahelm/application/releasemanager_test.go
  resources/application-connector/charts/application-operator/values.yaml
Labels: area/application-connector, enhancement

#2205 Update xip installation documentation
  docs/kyma/docs/036-inst-xip.io-domain.md
Labels: area/documentation

#2221 Update test acceptance image version
  resources/core/values.yaml
Labels: area/service-catalog, bug, priority/critical

#2228 Disable cache in ui tests
  resources/core/templates/tests/test-ui-acceptance.yaml
Labels: area/console, bug

#2229 Introduce UI API Layer documentation
  docs/console/docs/001-overview-console.md
  docs/console/docs/011-details-ui-api-layer.md
  docs/console/docs/022-cr-backendmodule.md
Labels: area/console, area/documentation

#2207 Adjust labels in console UI
  resources/core/charts/console/values.yaml
  resources/core/templates/tests/test-ui-acceptance.yaml
Labels: area/console, enhancement

#2234 Bump console images for scrollspy feature on content-ui
  resources/core/charts/docs/charts/content-ui/Chart.yaml
Labels: area/documentation, area/service-catalog, enhancement

#2232 Bump image of Application Operator
  installation/scripts/testing.sh
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#2239 Fix console-basic-test
  resources/core/templates/tests/test-ui-acceptance.yaml
Labels: area/console, bug

#2241 Fix image name of Application Operator tests
  tests/application-operator-tests/Makefile
Labels: area/application-connector, bug

#2240 Bump documentation
  resources/core/values.yaml
Labels: area/documentation, enhancement

#2242 Change Help label to Docs in core navigation on console ui
  resources/core/charts/console/values.yaml
Labels: area/documentation, enhancement

#2235 Add cluster name info to the stability checker summary
  tools/stability-checker/README.md
  tools/stability-checker/cmd/stability-checker/main.go
  tools/stability-checker/deploy/chart/stability-checker/templates/deploy.yaml
  tools/stability-checker/deploy/chart/stability-checker/values.yaml
  tools/stability-checker/internal/notifier/notifier.go
  tools/stability-checker/internal/notifier/renderer.go
  tools/stability-checker/internal/notifier/templates.go
  tools/stability-checker/local_helm_install.sh
Labels: area/documentation

#2245 Bump Instances image
  resources/core/charts/service-catalog-addons/charts/instances-ui/Chart.yaml
Labels: area/console, bug

#2263 Remove redundant ticks from console docs
  docs/console/docs/020-cr-microfrontend.md
  docs/console/docs/021-cr-clustermicrofrontend.md
Labels: area/documentation, bug

#2261 Fix BackendModule test in UI API Layer acceptance tests
  tests/ui-api-layer-acceptance-tests/internal/domain/ui/backendmodule_test.go
Labels: area/console, bug, priority/critical

#2262 Bump UI API Layer acceptance tests
  resources/core/values.yaml
Labels: area/console, bug, priority/critical

#2268 Improve console documentation
  docs/console/docs/020-cr-microfrontend.md
  docs/console/docs/021-cr-clustermicrofrontend.md
Labels: area/documentation

#2257 Validate minikube.sh, run.sh and installer.sh scripts input parameters
  installation/cmd/run.sh
  installation/scripts/installer.sh
  installation/scripts/minikube.sh
  installation/scripts/utils.sh
Labels: area/installation, bug

#2277 Correct the Azure link
  docs/service-brokers/docs/014-configuration-enable-azure-broker.md
  milv.config.yaml
Labels: area/documentation

#2296 Fix bug in 013-details-charts.md
  docs/kyma/docs/013-details-charts.md
Labels: area/documentation, bug

#2297 Fix typo in documentation
  docs/kyma/docs/044-gs-installation-overrides.md
Labels: area/documentation

#2278 Update image version for Catalog
  resources/core/charts/service-catalog-addons/charts/catalog-ui/Chart.yaml
Labels: WIP, area/console, enhancement

#2216 Document Kyma update process
  docs/kyma/docs/036-inst-update.md
  docs/kyma/docs/037-inst-xip.io-domain.md
  docs/kyma/docs/038-inst-custom-istio.md
  docs/kyma/docs/039-inst-knative.md
  docs/kyma/docs/040-inst-custom-service-catalog.md
  docs/kyma/docs/041-gs-sample-service-deployment-to-local.md
  docs/kyma/docs/042-gs-sample-service-deployment-to-cluster.md
  docs/kyma/docs/043-gs-local-develop-no-docker.md
  docs/kyma/docs/044-gs-publish-service-image-and-deploy.md
  docs/kyma/docs/045-gs-installation-overrides.md
Labels: area/documentation, area/installation, enhancement

#2318 Update doc title about Node.js runtime
  docs/serverless/docs/022-details-programming-model.md
Labels: area/documentation, area/serverless, bug

#2306 Fix adding connected app label
  components/application-registry/internal/metadata/servicedefservice.go
  components/application-registry/internal/metadata/servicedefservice_test.go
  tests/application-registry-tests/test/apitests/metadata_test.go
Labels: area/application-connector, bug, priority/critical

#2307 Bump image of Application Registry
  resources/application-connector/values.yaml
Labels: area/application-connector, bug, priority/critical

#2308 Rename "Environments" to "Namespaces"
  docs/application-connector/docs/001-overview-application-connector.md
  docs/application-connector/docs/010-architecture-application-connector.md
  docs/application-connector/docs/021-details-access-ac-on-local.md
  docs/application-connector/docs/022-details-consume-services.md
  docs/application-connector/docs/041-gs-get-client-certificate.md
  docs/application-connector/docs/044-gs-application-mapping.md
  docs/application-connector/docs/045-gs-trigger-lambda-with-event.md
  docs/application-connector/docs/046-gs-call-registered-service-from-kyma.md
  docs/application-connector/docs/051-cr-apllicationmapping.md
  docs/application-connector/docs/assets/001-application-connector.svg
  docs/assets/crd/mapping-prod.yaml
  docs/event-bus/docs/010-architecture-event-bus.md
  docs/event-bus/docs/020-details-concepts.md
  docs/event-bus/docs/021-details-event-flow-requirements.md
  docs/event-bus/docs/022-details-service-programming-model.md
  docs/event-bus/docs/030-cr-subscription.md
  docs/kyma/docs/006-overview-how-to-start.md
  docs/kyma/docs/011-details-environments.md
  docs/kyma/docs/011-details-namespaces.md
  docs/kyma/docs/030-inst-local-installation-from-release.md
  docs/kyma/docs/041-gs-sample-service-deployment-to-local.md
  docs/kyma/docs/042-gs-sample-service-deployment-to-cluster.md
  docs/kyma/docs/050-cr-installation.md
  docs/security/docs/001-overview-authorization-and-authentication.md
  docs/security/docs/021-details-add-connector.md
  docs/security/docs/assets/001-kyma-authorization.svg
  docs/serverless/docs/022-details-programming-model.md
  docs/service-brokers/docs/012-configuration-helm-broker-bundles.md
  docs/service-brokers/docs/020-architecture-ab.md
  docs/service-brokers/docs/021-architecture-helm-broker.md
  docs/service-brokers/docs/040-cr-event-activation.md
  docs/service-brokers/docs/assets/001-AB-architecture.svg
  docs/service-brokers/gcp-broker-service-classes/bigquery/docs/plans-details.md
  docs/service-brokers/gcp-broker-service-classes/cloud-bigtable/docs/plans-details.md
  docs/service-brokers/gcp-broker-service-classes/cloud-spanner/docs/plans-details.md
  docs/service-brokers/gcp-broker-service-classes/cloud-sql-mysql/docs/plans-details.md
  docs/service-brokers/gcp-broker-service-classes/google-cloud-storage/docs/plans-details.md
  docs/service-catalog/docs/001-overview-service-catalog.md
  docs/service-catalog/docs/005-architecture-service-catalog.md
  docs/service-catalog/docs/010-details-resources.md
  docs/service-catalog/docs/012-details-provisioning-and-binding.md
  docs/service-catalog/docs/040-cr-service-binding-usage.md
  docs/service-catalog/docs/061-ui-catalog.md
  docs/service-catalog/docs/assets/service-catalog-flow.svg
  resources/core/charts/kubeless/charts/lambdas-ui/README.md
  resources/core/charts/namespace-controller/README.md
Labels: area/documentation

#2287 Stabilise UI Tests in variable network conditions
  resources/core/charts/console/values.yaml
  resources/core/templates/tests/test-ui-acceptance.yaml
Labels: area/console, enhancement

#2264 Application Connector components hardening
  components/application-operator/Dockerfile
  components/application-proxy/Dockerfile
  components/application-registry/Dockerfile
  components/connection-token-handler/Dockerfile
  components/connector-service/Dockerfile
Labels: area/application-connector, enhancement

#2336 Update link and Namespace documentation
  docs/kyma/docs/011-details-namespaces.md
  resources/core/charts/namespace-controller/README.md
Labels: area/documentation

#2275 Application Connector components hardening - bump
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#2354 Update README.md
  components/xip-patch/README.md
Labels: area/documentation, bug

#2335 Add certificates authorization to Application Connector
  components/application-proxy/internal/authorization/basicauthstrategy.go
  components/application-proxy/internal/authorization/basicauthstrategy_test.go
  components/application-proxy/internal/authorization/certificategenstrategy.go
  components/application-proxy/internal/authorization/certificategenstrategy_test.go
  components/application-proxy/internal/authorization/externaltokenstrategy.go
  components/application-proxy/internal/authorization/externaltokenstrategy_test.go
  components/application-proxy/internal/authorization/factory.go
  components/application-proxy/internal/authorization/factory_test.go
  components/application-proxy/internal/authorization/mocks/Strategy.go
  components/application-proxy/internal/authorization/noauthstrategy.go
  components/application-proxy/internal/authorization/oauthstrategy.go
  components/application-proxy/internal/authorization/oauthstrategy_test.go
  components/application-proxy/internal/metadata/model/model.go
  components/application-proxy/internal/metadata/serviceapi/serviceapiservice.go
  components/application-proxy/internal/metadata/serviceapi/serviceapiservice_test.go
  components/application-proxy/internal/proxy/proxy.go
  components/application-proxy/internal/proxy/proxy_test.go
  components/application-proxy/internal/proxy/unauthorizedresponseretrier.go
  components/application-proxy/internal/proxy/unauthorizedresponseretrier_test.go
  components/application-registry/cmd/applicationregistry/applicationregistry.go
  components/application-registry/internal/externalapi/metadatahandler_test.go
  components/application-registry/internal/externalapi/model.go
  components/application-registry/internal/externalapi/servicedetailsvalidation.go
  components/application-registry/internal/externalapi/servicedetailsvalidation_test.go
  components/application-registry/internal/metadata/applications/repository.go
  components/application-registry/internal/metadata/certificates/generator.go
  components/application-registry/internal/metadata/certificates/generator_test.go
  components/application-registry/internal/metadata/certificates/model.go
  components/application-registry/internal/metadata/model/model.go
  components/application-registry/internal/metadata/secrets/mocks/Repository.go
  components/application-registry/internal/metadata/secrets/mocks/Service.go
  components/application-registry/internal/metadata/secrets/repository.go
  components/application-registry/internal/metadata/secrets/service.go
  components/application-registry/internal/metadata/secrets/service_test.go
  components/application-registry/internal/metadata/secrets/strategy/basicauth.go
  components/application-registry/internal/metadata/secrets/strategy/basicauth_test.go
  components/application-registry/internal/metadata/secrets/strategy/certificategen.go
  components/application-registry/internal/metadata/secrets/strategy/certificategen_test.go
  components/application-registry/internal/metadata/secrets/strategy/factory.go
  components/application-registry/internal/metadata/secrets/strategy/factory_test.go
  components/application-registry/internal/metadata/secrets/strategy/mocks/AccessStrategy.go
  components/application-registry/internal/metadata/secrets/strategy/mocks/Factory.go
  components/application-registry/internal/metadata/secrets/strategy/mocks/ModificationStrategy.go
  components/application-registry/internal/metadata/secrets/strategy/oauth.go
  components/application-registry/internal/metadata/secrets/strategy/oauth_test.go
  components/application-registry/internal/metadata/serviceapi/serviceapiservice.go
  components/application-registry/internal/metadata/serviceapi/serviceapiservice_test.go
  tests/application-registry-tests/test/apitests/metadata_test.go
  tests/application-registry-tests/test/k8stests/k8sresource_test.go
  tests/application-registry-tests/test/testkit/k8sresources_check.go
  tests/application-registry-tests/test/testkit/model.go
  tests/application-registry-tests/test/testkit/util.go
Labels: area/application-connector, enhancement

#2333 Bump ui-api-layer images
  resources/core/values.yaml
Labels: area/console, enhancement

#2332 Document uploading nats-streaming provisioner images
  components/event-bus/README.md
Labels: area/documentation, area/eventing

#2370 Move prow folder
  installation/scripts/prow/kyma-integration-on-debian/deploy-and-test-kyma.sh
  installation/scripts/prow/kyma-integration-on-debian/install-deps-debian.sh
Labels: area/ci

#2375 Remove unused prow folder
  CODEOWNERS
  prow/kyma-integration-on-debian/deploy-and-test-kyma.sh
  prow/kyma-integration-on-debian/install-deps-debian.sh
Labels: area/ci

#2377 Change numbering for documents
  docs/logging/docs/01-01-logging.md
  docs/logging/docs/02-01-logging.md
  docs/logging/docs/03-01-access-oklog.md
  docs/monitoring/docs/01-01-monitoring.md
  docs/monitoring/docs/02-01-monitoring.md
  docs/monitoring/docs/08-01-monitoring-custom-metrics.md
  docs/tracing/docs/01-01-tracing.md
  docs/tracing/docs/02-01-tracing.md
  docs/tracing/docs/03-01-distributed-tracing.md
  docs/tracing/docs/03-02-jaeger.md
  docs/tracing/docs/03-03-http-headers.md
  docs/tracing/docs/03-04-trace-comparison.md
  milv.config.yaml
Labels: area/documentation, area/logging, area/monitoring

#2382 Fix proxy certs in scratch image
  components/application-proxy/Dockerfile
Labels: area/application-connector

#2376 Kyma installer -Upgrade step should wait until success or timeout
  components/installer/pkg/kymahelm/kyma-helm-client.go
  resources/service-catalog/charts/catalog/templates/apiserver-deployment.yaml
  resources/service-catalog/charts/catalog/templates/controller-manager-deployment.yaml
Labels: area/installation, area/service-catalog

#2337 Set sidecar injection to false in service-catalog, cluster-essential, and core charts
  resources/cluster-essentials/charts/pod-preset/templates/controller-manager/stateful-set.yaml
  resources/cluster-essentials/charts/pod-preset/templates/webhook/deploy.yaml
  resources/core/charts/docs/charts/content-ui/templates/deployment.yaml
  resources/core/charts/docs/charts/documentation/templates/docs-gcp-service-classes.yaml
  resources/core/charts/docs/charts/documentation/templates/docs-hb-service-classes.yaml
  resources/core/charts/docs/charts/documentation/templates/docs-job.yaml
  resources/core/charts/etcd-operator/templates/backup-deployment.yaml
  resources/core/charts/helm-broker/charts/etcd-stateful/templates/03-statefulset.yaml
  resources/core/charts/helm-broker/templates/deploy.yaml
  resources/core/charts/service-catalog-addons/charts/brokers-ui/templates/deployment.yaml
  resources/core/templates/tests/test-core-acceptance.yaml
  resources/core/templates/tests/test-ui-acceptance.yaml
  resources/core/templates/tests/test-ui-api-acceptance.yaml
  resources/service-catalog/charts/catalog/templates/apiserver-deployment.yaml
  resources/service-catalog/charts/catalog/templates/controller-manager-deployment.yaml
  resources/service-catalog/charts/etcd-stateful/templates/00-etcd-tls-setup-job.yaml
  resources/service-catalog/charts/etcd-stateful/templates/03-statefulset.yaml
  resources/service-catalog/charts/etcd-stateful/templates/05-backup-job.yaml
Labels: area/service-mesh

#2327 Set sidecar injection annotations to false in Application Connector charts
  resources/application-connector/charts/application-broker/templates/deployment.yaml
  resources/application-connector/charts/application-operator/templates/controller.yaml
  resources/application-connector/charts/application-operator/templates/tests/test-acceptance.yaml
  resources/application-connector/charts/application-registry/templates/tests/test-acceptance.yaml
  resources/application-connector/charts/connection-token-handler/templates/deployment.yaml
  resources/application-connector/charts/connector-service/templates/tests/test-acceptance.yaml
  resources/application-connector/charts/nginx-ingress/values.yaml
Labels: area/application-connector, area/service-mesh

#2383 Fix proxy certs in scratch image - image bump
  resources/application-connector/values.yaml
Labels: area/application-connector

#2331 Set sidecar injection annotations to false in NS-controller, api-controller, azure-broker and dex
  resources/core/charts/api-controller/templates/deployment.yaml
  resources/core/charts/api-controller/templates/tests/test-api-controller.yaml
  resources/core/charts/azure-broker/charts/redis/templates/deployment.yaml
  resources/core/charts/azure-broker/templates/azure-service-classes-docu.yaml
  resources/core/charts/azure-broker/templates/deployment.yaml
  resources/core/charts/namespace-controller/templates/4-deployment.yaml
  resources/core/charts/namespace-controller/templates/tests/test-namespace-controller.yaml
  resources/dex/templates/dex-deployment.yaml
  resources/dex/templates/tests/test-dex-connection.yaml
Labels: area/service-mesh

#2384 Bump installer version
  installation/resources/installer.yaml
  tools/kyma-installer/kyma.Dockerfile
Labels: area/installation

#2340 Set sidecar injection to false in charts
  resources/core/charts/console/templates/deployment.yaml
  resources/core/charts/event-bus/charts/push/templates/deployment.yaml
  resources/core/charts/event-bus/templates/tests/test-e2e-tester.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/templates/deployment.yaml
  resources/core/charts/kubeless/templates/kubeless-controller-deployment.yaml
  resources/core/charts/kubeless/templates/tests/test-kubeless.yaml
  resources/core/charts/minio/templates/deployment.yaml
  resources/core/charts/minio/templates/post-install-create-bucket-job.yaml
  resources/core/charts/minio/templates/statefulset.yaml
  resources/core/charts/service-catalog-addons/charts/catalog-ui/templates/deployment.yaml
  resources/core/charts/service-catalog-addons/charts/instances-ui/templates/deployment.yaml
  resources/logging/templates/daemonset.yaml
  resources/logging/templates/statefulset.yaml
  resources/logging/templates/tests/logging.yaml
  resources/monitoring/charts/exporter-kube-state/templates/deployment.yaml
  resources/monitoring/charts/exporter-node/templates/daemonset.yaml
  resources/monitoring/templates/tests/test-kube-prometheus.yaml
  resources/prometheus-operator/templates/create-servicemonitor-job.yaml
  resources/prometheus-operator/templates/deployment.yaml
  resources/prometheus-operator/templates/get-crd-job.yaml
Labels: area/service-mesh

#2396 Rename outstanding items from "remote env." to "application" renaming
  docs/application-connector/docs/03-03-consume-services.md
  docs/application-connector/docs/06-03-tokenrequest.md
  docs/application-connector/docs/08-02-get-client-certificate.md
Labels: area/application-connector, area/documentation

#2392 Update image version
  resources/core/charts/service-catalog-addons/charts/catalog-ui/Chart.yaml
Labels: area/documentation, bug

#2328 Rename environments to namespaces in ui-api-layer under Application domain
  components/ui-api-layer/internal/domain/application/app_resolver.go
  components/ui-api-layer/internal/domain/application/application.go
  components/ui-api-layer/internal/domain/application/disabled/resolver.go
  components/ui-api-layer/internal/domain/application/eventactivation_resolver.go
  components/ui-api-layer/internal/domain/root_resolver.go
  components/ui-api-layer/internal/gqlschema/models_gen.go
  components/ui-api-layer/internal/gqlschema/schema.graphql
  components/ui-api-layer/internal/gqlschema/schema_gen.go
Labels: area/application-connector, enhancement

#2406 Update the SC screenshot
  docs/service-catalog/docs/assets/add-to-environment.png
  docs/service-catalog/docs/assets/add-to-namespace.png
Labels: area/documentation, bug

#2405 Bump application proxy version
  resources/application-connector/values.yaml
Labels: area/application-connector, bug

#2414 Remove release related jenkinsfiles
  release-github.Jenkinsfile
  release.Jenkinsfile
  tools/kyma-installer/Jenkinsfile
  tools/kyma-installer/artifacts.Jenkinsfile
Labels: area/ci, enhancement

#2416 Remove orchestrator Jenkinsfile
  CODEOWNERS
  orchestrator.Jenkinsfile
Labels: area/ci

#2355 Install Kyma on AKS
  docs/kyma/docs/04-05-aks-installation.md
  docs/kyma/docs/04-07-aks-xip.io-domain.md
  installation/resources/azure-crb-for-healthz.yaml
  installation/resources/installer-config-cluster.yaml.tpl
  milv.config.yaml
Labels: area/documentation

#2424 Increasing memory limit for size of the body in Application Registry
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#2351 Update GCP BRoker Provider doc and add Azure Broker Docs
  docs/docs-build.yaml
  docs/service-brokers/docs/001-overview-service-brokers.md
  docs/service-brokers/docs/002-overview-azure-broker.md
  docs/service-brokers/docs/003-overview-gcp-broker.md
  docs/service-brokers/docs/014-configuration-enable-azure-broker.md
  docs/service-brokers/docs/assets/002-azure-service-broker-class.png
  docs/service-brokers/docs/assets/003-gcp-broker-classes.png
  docs/service-brokers/docs/assets/003-gcp-class.png
  docs/service-brokers/docs/assets/003-gcp-classes.png
  docs/service-brokers/docs/assets/003-gcp-provider-class.png
  docs/service-brokers/helm-broker-service-classes/azure-broker/docs.config.json
  docs/service-brokers/helm-broker-service-classes/azure-broker/docs/overview.md
  docs/service-brokers/helm-broker-service-classes/azure-broker/docs/plans-details.md
  docs/service-brokers/helm-broker-service-classes/gcp-broker-provider/docs.config.json
  docs/service-brokers/helm-broker-service-classes/gcp-broker-provider/docs/overview.md
  docs/service-brokers/helm-broker-service-classes/gcp-broker/docs.config.json
  docs/service-brokers/helm-broker-service-classes/gcp-broker/docs/assets/gcp-broker-deprovisioning.svg
  docs/service-brokers/helm-broker-service-classes/gcp-broker/docs/assets/gcp-broker-key-management.svg
  docs/service-brokers/helm-broker-service-classes/gcp-broker/docs/assets/gcp-broker-provisioning.svg
  docs/service-brokers/helm-broker-service-classes/gcp-broker/docs/overview.md
  docs/service-brokers/helm-broker-service-classes/gcp-broker/docs/plans-details.md
Labels: area/documentation, area/service-catalog

#2432 Update dead links in docs of installation Kyma on AKS
  docs/kyma/docs/04-05-aks-installation.md
Labels: area/documentation, bug

#2407 Create skeleton subscription-controller
  components/event-bus/Gopkg.lock
  components/event-bus/Gopkg.toml
  components/event-bus/Makefile
  components/event-bus/before-commit.sh
  components/event-bus/cmd/event-bus-subscription-controller-knative/.gitignore
  components/event-bus/cmd/event-bus-subscription-controller-knative/Dockerfile
  components/event-bus/cmd/event-bus-subscription-controller-knative/Makefile
  components/event-bus/cmd/event-bus-subscription-controller-knative/cmd/manager/main.go
  components/event-bus/cmd/event-bus-subscription-controller-knative/dockerBuild.sh
  components/event-bus/docker-build-event-bus-sck.sh
  components/event-bus/docs/knative-subscription-controller-test-resources/README.md
  components/event-bus/docs/knative-subscription-controller-test-resources/manager.yaml
  components/event-bus/docs/knative-subscription-controller-test-resources/rbac_role.yaml
  components/event-bus/docs/knative-subscription-controller-test-resources/rbac_role_binding.yaml
  components/event-bus/internal/knative/subscription/controller/add_subscription.go
  components/event-bus/internal/knative/subscription/controller/controller.go
  components/event-bus/internal/knative/subscription/controller/subscription/subscription_controller.go
  components/event-bus/internal/knative/subscription/opts/opts.go
Labels: area/documentation, area/eventing

#2419 Fix broken links
  docs/service-brokers/docs/005-overview-helm-broker.md
  resources/service-catalog/README.md
Labels: area/documentation

#2420 Enable default sidecar injection
  components/istio-kyma-patch/README.md
  docs/service-mesh/docs/03-01-sidecar-proxy-injection.md
  docs/service-mesh/docs/03-02-istio-patch.md
  resources/core/templates/istio-injection-label.yaml
  resources/istio-kyma-patch/README.md
  resources/istio-kyma-patch/templates/clusterrole.yaml
  resources/istio-kyma-patch/templates/configmap.yaml
Labels: area/service-mesh, enhancement

#2443 Use bundles repo 0.3.0
  resources/core/charts/helm-broker/values.yaml
Labels: area/service-catalog, enhancement

#2402 Bump docs version after azure broker classes docs update
  resources/core/charts/docs/charts/documentation/templates/docs-azure-service-classes.yaml
  resources/core/values.yaml
Labels: area/documentation, area/service-catalog, enhancement

#2442 Improvements for AKS documentation
  docs/kyma/docs/04-05-aks-installation.md
  docs/kyma/docs/04-07-aks-xip.io-domain.md
  milv.config.yaml
Labels: WIP, area/documentation

#2347 Update Kyma installation documentation
  components/namespace-controller/README.md
  docs/kyma/docs/030-inst-overview.md
  docs/kyma/docs/031-inst-local-installation-from-release.md
  docs/kyma/docs/032-inst-local-installation-from-sources.md
  docs/kyma/docs/033-inst-gke-installation.md
  docs/kyma/docs/034-inst-install-subcomponents.md
  docs/kyma/docs/035-inst-xip.io-domain.md
  docs/kyma/docs/036-inst-custom-component-installation.md
  docs/kyma/docs/037-inst-knative.md
  docs/kyma/docs/038-inst-custom-istio.md
  docs/kyma/docs/038-inst-update.md
  docs/kyma/docs/039-inst-local-reinstallation.md
  docs/kyma/docs/040-inst-custom-service-catalog.md
  docs/kyma/docs/040-inst-local-installation-scripts.md
  docs/tracing/docs/03-02-jaeger.md
  installation/README.md
  resources/README.md
  resources/core/README.md
Labels: area/documentation

#2446 Generate clientset for Token Request CRD
  components/connection-token-handler/Gopkg.lock
  components/connection-token-handler/Gopkg.toml
  components/connection-token-handler/hack/generate-groups.sh
  components/connection-token-handler/hack/update-codegen.sh
  components/connection-token-handler/pkg/apis/applicationconnector/v1alpha1/zz_generated.deepcopy.go
  components/connection-token-handler/pkg/client/clientset/versioned/clientset.go
  components/connection-token-handler/pkg/client/clientset/versioned/doc.go
  components/connection-token-handler/pkg/client/clientset/versioned/fake/clientset_generated.go
  components/connection-token-handler/pkg/client/clientset/versioned/fake/doc.go
  components/connection-token-handler/pkg/client/clientset/versioned/fake/register.go
  components/connection-token-handler/pkg/client/clientset/versioned/scheme/doc.go
  components/connection-token-handler/pkg/client/clientset/versioned/scheme/register.go
  components/connection-token-handler/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/applicationconnector_client.go
  components/connection-token-handler/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/doc.go
  components/connection-token-handler/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/fake/doc.go
  components/connection-token-handler/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/fake/fake_applicationconnector_client.go
  components/connection-token-handler/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/fake/fake_tokenrequest.go
  components/connection-token-handler/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/generated_expansion.go
  components/connection-token-handler/pkg/client/clientset/versioned/typed/applicationconnector/v1alpha1/tokenrequest.go
  components/connection-token-handler/pkg/client/informers/externalversions/applicationconnector/interface.go
  components/connection-token-handler/pkg/client/informers/externalversions/applicationconnector/v1alpha1/interface.go
  components/connection-token-handler/pkg/client/informers/externalversions/applicationconnector/v1alpha1/tokenrequest.go
  components/connection-token-handler/pkg/client/informers/externalversions/factory.go
  components/connection-token-handler/pkg/client/informers/externalversions/generic.go
  components/connection-token-handler/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  components/connection-token-handler/pkg/client/listers/applicationconnector/v1alpha1/expansion_generated.go
  components/connection-token-handler/pkg/client/listers/applicationconnector/v1alpha1/tokenrequest.go
Labels: area/application-connector, enhancement

#2417 Delete integration Jenkins files
  Jenkinsfile
  ci.Dockerfile
  installation/cmd/ci.build.ps1
  installation/cmd/ci.build.sh
  installation/cmd/ci.run.ps1
  installation/cmd/ci.run.sh
Labels: area/ci

#2455 Adjust installation docs after changing release artefacts
  docs/kyma/docs/031-inst-local-installation-from-release.md
  docs/kyma/docs/033-inst-gke-installation.md
  docs/kyma/docs/037-inst-knative.md
  docs/kyma/docs/04-05-aks-installation.md
  docs/kyma/docs/04-07-aks-xip.io-domain.md
Labels: area/documentation, area/installation, enhancement

#2462 Fix the numeration bug
  docs/kyma/docs/03-05-deploy-private-registry.md
Labels: area/documentation, bug

#2429 Add ServiceMonitor CRD to cluster essentials
  docs/kyma/docs/04-01-overview.md
  docs/kyma/docs/04-08-custom-component-installation.md
  installation/resources/installer-cr.yaml.tpl
  resources/cluster-essentials/templates/service-monitor.crd.yaml
Labels: area/installation, area/monitoring, enhancement

#2294 Remove azure broker from kyma installation
  CODEOWNERS
  components/installer/README.md
  docs/kyma/docs/04-12-local-installation-scripts.md
  installation/resources/azure-broker-secret.yaml.tpl
  installation/scripts/configure-azure-broker.sh
  installation/scripts/generate-local-config.ps1
  installation/scripts/installer.sh
  resources/core/charts/azure-broker/.helmignore
  resources/core/charts/azure-broker/Chart.yaml
  resources/core/charts/azure-broker/README.md
  resources/core/charts/azure-broker/charts/redis/.helmignore
  resources/core/charts/azure-broker/charts/redis/Chart.yaml
  resources/core/charts/azure-broker/charts/redis/README.md
  resources/core/charts/azure-broker/charts/redis/templates/NOTES.txt
  resources/core/charts/azure-broker/charts/redis/templates/_helpers.tpl
  resources/core/charts/azure-broker/charts/redis/templates/deployment.yaml
  resources/core/charts/azure-broker/charts/redis/templates/networkpolicy.yaml
  resources/core/charts/azure-broker/charts/redis/templates/pvc.yaml
  resources/core/charts/azure-broker/charts/redis/templates/secrets.yaml
  resources/core/charts/azure-broker/charts/redis/templates/svc.yaml
  resources/core/charts/azure-broker/charts/redis/values.yaml
  resources/core/charts/azure-broker/templates/_helpers.tpl
  resources/core/charts/azure-broker/templates/azure-broker-basic-auth.yaml
  resources/core/charts/azure-broker/templates/azure-broker-credentials.yaml
  resources/core/charts/azure-broker/templates/azure-broker-redis.yaml
  resources/core/charts/azure-broker/templates/azure-service-classes-docu.yaml
  resources/core/charts/azure-broker/templates/broker.yaml
  resources/core/charts/azure-broker/templates/deployment.yaml
  resources/core/charts/azure-broker/templates/service.yaml
  resources/core/charts/azure-broker/values.yaml
  resources/core/requirements.yaml
  resources/core/values.yaml
  tools/watch-pods/README.md
Labels: area/documentation, area/service-catalog

#2475 istio-kyma-patch image bump
  resources/istio-kyma-patch/values.yaml
Labels: area/service-mesh

#2474 Bump image of Lambda UI
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
Labels: area/application-connector, enhancement, priority/critical

#2476 Fix event bus gometalinter issue
  components/event-bus/Makefile
Labels: area/eventing

#2437 Implement GraphQL mutations for pods
  components/ui-api-layer/internal/domain/k8s/automock/export.go
  components/ui-api-layer/internal/domain/k8s/automock/gql_pod_converter.go
  components/ui-api-layer/internal/domain/k8s/automock/pod_svc.go
  components/ui-api-layer/internal/domain/k8s/export_test.go
  components/ui-api-layer/internal/domain/k8s/k8s.go
  components/ui-api-layer/internal/domain/k8s/pod_converter.go
  components/ui-api-layer/internal/domain/k8s/pod_converter_test.go
  components/ui-api-layer/internal/domain/k8s/pod_resolver.go
  components/ui-api-layer/internal/domain/k8s/pod_resolver_test.go
  components/ui-api-layer/internal/domain/k8s/pod_service.go
  components/ui-api-layer/internal/domain/k8s/pod_service_test.go
  components/ui-api-layer/internal/domain/root_resolver.go
  components/ui-api-layer/internal/gqlschema/json.go
  components/ui-api-layer/internal/gqlschema/schema.graphql
  components/ui-api-layer/internal/gqlschema/schema_gen.go
  tests/ui-api-layer-acceptance-tests/internal/domain/k8s/pod_test.go
Labels: area/console, enhancement

#2470 Add bash trap to delete GC credentials file
  tools/gcp-broker-provider/bin/gcp-broker.sh
Labels: area/service-catalog, enhancement

#2471 Improve local development with custom password for admin account
  installation/cmd/run.sh
  installation/resources/installer-config-local.yaml.tpl
  installation/scripts/installer.sh
  resources/dex/templates/dex-users-secret.yaml
Labels: area/installation

#2450 Introduce Bucket controller for Asset Store
  CODEOWNERS
  components/assetstore-controller-manager/.gitignore
  components/assetstore-controller-manager/Dockerfile
  components/assetstore-controller-manager/Gopkg.lock
  components/assetstore-controller-manager/Gopkg.toml
  components/assetstore-controller-manager/Makefile
  components/assetstore-controller-manager/PROJECT
  components/assetstore-controller-manager/README.md
  components/assetstore-controller-manager/cmd/manager/main.go
  components/assetstore-controller-manager/config/crds/assetstore_v1alpha1_bucket.yaml
  components/assetstore-controller-manager/config/default/kustomization.yaml
  components/assetstore-controller-manager/config/default/manager_auth_proxy_patch.yaml
  components/assetstore-controller-manager/config/default/manager_image_patch.yaml
  components/assetstore-controller-manager/config/default/manager_image_patch.yaml-e
  components/assetstore-controller-manager/config/default/manager_prometheus_metrics_patch.yaml
  components/assetstore-controller-manager/config/manager/manager.yaml
  components/assetstore-controller-manager/config/rbac/auth_proxy_role.yaml
  components/assetstore-controller-manager/config/rbac/auth_proxy_role_binding.yaml
  components/assetstore-controller-manager/config/rbac/auth_proxy_service.yaml
  components/assetstore-controller-manager/config/rbac/rbac_role.yaml
  components/assetstore-controller-manager/config/rbac/rbac_role_binding.yaml
  components/assetstore-controller-manager/config/samples/assetstore_v1alpha1_bucket.yaml
  components/assetstore-controller-manager/hack/boilerplate.go.txt
  components/assetstore-controller-manager/pkg/apis/addtoscheme_assetstore_v1alpha1.go
  components/assetstore-controller-manager/pkg/apis/apis.go
  components/assetstore-controller-manager/pkg/apis/assetstore/group.go
  components/assetstore-controller-manager/pkg/apis/assetstore/v1alpha1/bucket_types.go
  components/assetstore-controller-manager/pkg/apis/assetstore/v1alpha1/bucket_types_test.go
  components/assetstore-controller-manager/pkg/apis/assetstore/v1alpha1/doc.go
  components/assetstore-controller-manager/pkg/apis/assetstore/v1alpha1/register.go
  components/assetstore-controller-manager/pkg/apis/assetstore/v1alpha1/v1alpha1_suite_test.go
  components/assetstore-controller-manager/pkg/apis/assetstore/v1alpha1/zz_generated.deepcopy.go
  components/assetstore-controller-manager/pkg/buckethandler/automock/bucket_handler.go
  components/assetstore-controller-manager/pkg/buckethandler/automock/minio_client.go
  components/assetstore-controller-manager/pkg/buckethandler/buckethandler.go
  components/assetstore-controller-manager/pkg/buckethandler/buckethandler_test.go
  components/assetstore-controller-manager/pkg/controller/add_bucket.go
  components/assetstore-controller-manager/pkg/controller/bucket/bucket_controller.go
  components/assetstore-controller-manager/pkg/controller/bucket/bucket_controller_suite_test.go
  components/assetstore-controller-manager/pkg/controller/bucket/bucket_controller_test.go
  components/assetstore-controller-manager/pkg/controller/bucket/bucket_finalizer.go
  components/assetstore-controller-manager/pkg/controller/bucket/bucket_finalizer_test.go
  components/assetstore-controller-manager/pkg/controller/bucket/bucket_status_reason.go
  components/assetstore-controller-manager/pkg/controller/bucket/config.go
  components/assetstore-controller-manager/pkg/controller/controller.go
  components/assetstore-controller-manager/pkg/webhook/webhook.go
Labels: area/documentation, enhancement

#2457 Fix test for multi dex providers
  tests/acceptance/Gopkg.lock
  tests/acceptance/dex/idtokenprovider.go
  tests/ui-api-layer-acceptance-tests/Gopkg.lock
  tests/ui-api-layer-acceptance-tests/internal/graphql/idtokenprovider.go
Labels: area/ci, area/security

#2346 Upgrade minikube and K8S version
  docs/kyma/docs/04-02-local-installation-from-release.md
  docs/kyma/docs/04-04-gke-installation.md
  installation/scripts/is-ready.ps1
  installation/scripts/minikube.ps1
  installation/scripts/minikube.sh
  installation/scripts/prow/kyma-integration-on-debian/install-deps-debian.sh
Labels: area/ci, area/eventing, wg/knative

#2494 Bump version of acceptance tests and ui-api-layer-acceptance-tests
  resources/core/values.yaml
Labels: area/ci

#2506 Fix Azure Broker class docs
  docs/service-brokers/azure-broker-service-classes/azure-eventhubs/docs.config.json
  docs/service-brokers/azure-broker-service-classes/azure-textanalytics/docs/plans-details.md
  docs/service-brokers/helm-broker-service-classes/azure-broker/docs/plans-details.md
Labels: area/documentation, area/service-catalog

#2509 Fix broken link in installation overview
  docs/kyma/docs/04-01-overview.md
Labels: area/documentation, area/installation

#2511 Resize screenshot so that it displays well on UI
  docs/service-catalog/docs/assets/instances.png
Labels: area/documentation, bug

#2512 Bump docs version
  resources/core/values.yaml
Labels: area/documentation

#2496 Implement GraphQL subscription for pods
  components/ui-api-layer/internal/domain/k8s/automock/pod_svc.go
  components/ui-api-layer/internal/domain/k8s/listener/automock/export.go
  components/ui-api-layer/internal/domain/k8s/listener/automock/gql_pod_converter.go
  components/ui-api-layer/internal/domain/k8s/listener/pod.go
  components/ui-api-layer/internal/domain/k8s/listener/pod_test.go
  components/ui-api-layer/internal/domain/k8s/pod_resolver.go
  components/ui-api-layer/internal/domain/k8s/pod_resolver_test.go
  components/ui-api-layer/internal/domain/k8s/pod_service.go
  components/ui-api-layer/internal/domain/k8s/pod_service_test.go
  components/ui-api-layer/internal/domain/root_resolver.go
  components/ui-api-layer/internal/gqlschema/models_gen.go
  components/ui-api-layer/internal/gqlschema/schema.graphql
  components/ui-api-layer/internal/gqlschema/schema_gen.go
  tests/ui-api-layer-acceptance-tests/internal/domain/k8s/pod_test.go
Labels: area/console, enhancement

#2499 Bump ui api layer images
  resources/core/values.yaml
Labels: area/console, enhancement

#2513 Document the ability to define admin password for local deployment
  docs/kyma/docs/04-02-local-installation-from-release.md
  docs/kyma/docs/04-03-local-installation-from-sources.md
  docs/kyma/docs/04-10-update.md
  docs/kyma/docs/04-12-local-installation-scripts.md
Labels: area/documentation, area/installation, enhancement

#2495 Disable sidecar injection in namespaces provided in configmap
  components/istio-kyma-patch/patch.sh
Labels: area/service-mesh, enhancement

#2521 Resize screenshot so that it displays well on UI #2
  docs/service-catalog/docs/assets/instances.png
Labels: area/documentation, bug

#2441 Bump service-catalog views images
  resources/core/charts/docs/charts/content-ui/Chart.yaml
  resources/core/charts/service-catalog-addons/charts/brokers-ui/Chart.yaml
  resources/core/charts/service-catalog-addons/charts/catalog-ui/Chart.yaml
  resources/core/charts/service-catalog-addons/charts/instances-ui/Chart.yaml
  resources/core/templates/tests/test-ui-acceptance.yaml
Labels: WIP, area/console, enhancement

#2518 Admin password windows
  installation/cmd/run.ps1
  installation/scripts/generate-local-config.ps1
Labels: area/installation

#2524 Add provisionOnlyOnce flag info
  docs/service-brokers/docs/05-02-helm-broker-bundles.md
Labels: area/documentation, area/service-catalog

#2531 Fix autoscaling version
  docs/kyma/docs/04-02-local-installation-from-release.md
Labels: area/documentation, bug

#2529 Add relative links for cross-references between Kyma docs
  docs/api-gateway/docs/02-01-api-gateway.md
  docs/application-connector/docs/01-01-application-connector.md
  docs/event-bus/docs/01-01-event-bus.md
  docs/event-bus/docs/03-05-subscription-updates.md
  docs/kyma/docs/04-04-gke-installation.md
  docs/kyma/docs/04-08-custom-component-installation.md
  docs/kyma/docs/08-03-local-develop-no-docker.md
  docs/kyma/docs/08-04-publish-service-image-and-deploy.md
  docs/security/docs/01-01-security.md
  docs/service-brokers/docs/01-02-helm-broker.md
  docs/service-brokers/docs/01-03-ab.md
  docs/service-brokers/docs/01-04-azure-broker.md
  docs/service-brokers/docs/01-05-gcp-broker.md
  docs/service-brokers/docs/05-01-helm-broker.md
  docs/service-mesh/docs/03-02-istio-patch.md
Labels: area/documentation, enhancement

#2510 Remove Resource Quotas from system namespaces
  installation/resources/installer-local.yaml
  installation/resources/installer.yaml
  resources/application-connector/templates/resource-quotas.yaml
  resources/cluster-essentials/templates/resource-quotas.yaml
Labels: area/installation, enhancement

#2533 Bump stability checker version
  tools/stability-checker/deploy/chart/stability-checker/values.yaml
Labels: area/ci

#2536 Add removed links
  docs/kyma/docs/04-01-overview.md
Labels: area/documentation, area/installation

#2526 Update knative eventing images
  resources/knative/charts/knative/templates/eventing.yaml
Labels: area/eventing, wg/knative

#2491 Fix nats-streaming issue
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  resources/nats-streaming/templates/_helpers.tpl
  resources/nats-streaming/templates/istio-label-injection.yaml
  resources/nats-streaming/templates/service.yaml
  resources/nats-streaming/templates/statefulset.yaml
Labels: area/cluster, area/eventing, bug, priority/critical
