Repository kyma-project/kyma, pull requests merged in 2019-12, with the labels that each got.

#6425 GraphQL playground available without auth in director
  resources/compass/charts/gateway/templates/oathkeeper-rules.yaml
  resources/compass/values.yaml
Labels: enhancement

#6412 Bump images of Schema Migrator, Director and Director tests in Compass chart
  resources/compass/charts/director/config.yaml
  resources/compass/charts/director/static-users.yaml
  resources/compass/templates/director-test.yaml
  resources/compass/templates/e2e-compass-test.yaml
  resources/compass/values.yaml
Labels: enhancement

#6287 Refactor catalog-ui
  resources/core/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
Labels: area/console

#6461 Fix fonts loading in Console
  resources/compass/charts/cockpit/values.yaml
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#5828 Remove dead code and add tests
  components/event-bus/internal/knative/util/util.go
  components/event-bus/internal/knative/util/util_test.go
Labels: WIP

#6488 Add description to Application Registry API spec parameters
  components/application-registry/docs/api/api.yaml
Labels: area/application-connector, area/documentation

#6503 Update documentation for cleaning up Runtime data
  docs/compass/03-01-provisioner-details.md
  docs/compass/08-06-provisioner-clean-up-runtime-data.md
Labels: area/documentation

#6371 Set application-name label on HTTP source Channel
  components/event-sources/Gopkg.lock
  components/event-sources/apis/sources/v1alpha1/http_lifecycle.go
  components/event-sources/reconciler/httpsource/controller.go
  components/event-sources/reconciler/httpsource/reconcile.go
  components/event-sources/reconciler/httpsource/reconcile_test.go
  components/event-sources/reconciler/objects/channel.go
  components/event-sources/reconciler/objects/channel_test.go
  components/event-sources/reconciler/objects/equality.go
  components/event-sources/reconciler/objects/equality_test.go
  components/event-sources/reconciler/testing/channel.go
  components/event-sources/reconciler/testing/httpsource.go
  components/event-sources/test/fixtures/channel.json
Labels: area/eventing

#6486 Improve logging diagram and description
  docs/logging/01-01-logging.md
  docs/logging/02-01-logging.md
  docs/logging/03-01-access-logs.md
  docs/logging/assets/logging-architecture.svg
  docs/logging/assets/loki-overview.png
Labels: area/documentation, area/logging

#6240 Add component prometheus-operator and monitoring to compass installer-cr
  installation/resources/installer-cr-cluster-compass.yaml.tpl
Labels: enhancement

#6507 Add Digital Lights logo to main README.md
  README.md
Labels: area/documentation

#6480 Enable Console e2e and CBS tests
  resources/core/charts/console-backend-service/values.yaml
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
Labels: area/console, bug

#6501 Add information about redirect URIs for OAuth2 clients
  docs/security/03-06-oauth2-server.md
Labels: area/documentation

#6527 Update Gardener installation guide
  docs/kyma/04-04-cluster-installation.md
Labels: area/documentation, area/installation

#6505 Enable support for cluster-local Gateway in Knative Serving
  resources/knative-serving/README.md
  resources/knative-serving/templates/istio-knative-extras.yaml
Labels: area/serverless

#6104 Use generic makefile for event-bus and function-controller components and tests
  components/event-bus/Makefile
  components/event-bus/before-commit.sh
  components/event-bus/cmd/event-publish-service/Dockerfile
  components/event-bus/cmd/subscription-controller/Dockerfile
  components/event-bus/cmd/subscription-controller/main.go
  components/event-bus/docker-build-event-publish-service.sh
  components/event-bus/docker-build-nats-init.sh
  components/event-bus/docker-build-subscription-controller.sh
  components/event-bus/images/nats-init/Dockerfile
  components/event-bus/images/nats-init/scripts/prepare-config.sh
  components/event-service/Dockerfile
  components/event-service/Gopkg.lock
  components/event-service/Makefile
  components/event-service/before-commit.sh
  components/event-service/internal/events/subscribed/mocks/NamespacesClient.go
  components/event-service/internal/events/subscribed/mocks/SubscriptionsGetter.go
  components/event-service/internal/externalapi/mocks/EventsClient.go
  components/event-sources/Makefile
  components/function-controller/Makefile
  components/kubeless-images/nodejs/Makefile
  tests/end-to-end/kubeless-integration/Dockerfile
  tests/end-to-end/kubeless-integration/Makefile
  tests/event-bus/Makefile
  tests/event-bus/e2e-subscriber/Dockerfile
  tests/event-bus/e2e-tester/Dockerfile
  tests/integration/event-service/Dockerfile
  tests/integration/event-service/Gopkg.lock
  tests/integration/event-service/Makefile
  tests/integration/event-service/can-i-commit.sh
  tests/integration/event-service/test/apitests/main_test.go
  tests/integration/event-service/test/testkit/subscriptions_client.go
  tests/kubeless/Makefile
Labels: area/eventing

#6515 Add migration guide for 1.8
  docs/migration-guides/1.7-1.8.md
Labels: area/documentation, area/monitoring

#6526 Update Connector Service dependencies
  components/connector-service/Gopkg.lock
  components/connector-service/Gopkg.toml
  resources/application-connector/values.yaml
Labels: WIP, area/application-connector

#6540 fix links
  docs/monitoring/08-05-send-notifications.md
Labels: area/documentation

#6517 Add to CODEOWNERS mention about new rafter chart in resources folder
  CODEOWNERS
Labels: area/core-and-supporting

#6530 Update Compass chart
  resources/compass/charts/gateway/templates/oathkeeper-rules.yaml
  resources/compass/charts/gateway/templates/virtualservice-mtls.yaml
  resources/compass/charts/gateway/templates/virtualservice-secure.yaml
  resources/compass/charts/gateway/templates/virtualservice.yaml
  resources/compass/templates/director-test.yaml
  resources/compass/templates/e2e-compass-test.yaml
  resources/compass/values.yaml
Labels: enhancement

#6452 Tenant chooser doesn't change the current tenant for the current view in Compass UI
  resources/compass/charts/cockpit/templates/configmap.yaml
  resources/compass/charts/cockpit/values.yaml
  resources/compass/charts/director/static-users.yaml
  resources/compass/values.yaml
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#6553 Update App Registry API spec description
  docs/application-connector/assets/metadataapi.yaml
Labels: area/application-connector, area/documentation

#6551 Remove FluentBit from docu
  docs/logging/01-01-logging.md
  docs/logging/02-01-logging.md
  docs/logging/05-01-logging.md
  docs/logging/08-01-configure-logcollector.md
  docs/logging/assets/logging-architecture.svg
Labels: area/documentation, area/logging

#6463 Compass Runtime Agent API Spec Format handling
  components/compass-runtime-agent/internal/compass/director/converter.go
  components/compass-runtime-agent/internal/compass/director/converter_test.go
  components/compass-runtime-agent/internal/kyma/apiresources/assetstore/docstopic/model.go
  components/compass-runtime-agent/internal/kyma/apiresources/assetstore/mocks/Service.go
  components/compass-runtime-agent/internal/kyma/apiresources/assetstore/service.go
  components/compass-runtime-agent/internal/kyma/apiresources/assetstore/service_test.go
  components/compass-runtime-agent/internal/kyma/apiresources/mocks/Service.go
  components/compass-runtime-agent/internal/kyma/apiresources/service.go
  components/compass-runtime-agent/internal/kyma/apiresources/service_test.go
  components/compass-runtime-agent/internal/kyma/model/types.go
  components/compass-runtime-agent/internal/kyma/service.go
  components/compass-runtime-agent/internal/kyma/service_test.go
  resources/compass-runtime-agent/values.yaml
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_test.go
  tests/compass-runtime-agent/test/testkit/applications/api.go
  tests/compass-runtime-agent/test/testkit/applications/eventapi.go
  tests/compass-runtime-agent/test/testkit/assertions/k8s_resource_checker.go
Labels: area/application-connector, bug

#6574 Remove the dead link
  docs/asset-store/08-03-gateway-s3-mode-set-up.md
Labels: area/documentation

#6570 Add destination rule to rafter-upload-service
  resources/rafter/charts/upload-service/templates/destination-rule.yaml
Labels: area/core-and-supporting

#6494 Update React Fundamental in Compass
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#6424 Upgrade event-bus tests to knative-0.10
  tests/event-bus/Gopkg.lock
  tests/event-bus/Gopkg.toml
  tests/event-bus/e2e-tester/e2e-tester.go
Labels: area/eventing

#6593 Add curl to Event Service tests Dockerfile
  tests/integration/event-service/Dockerfile
Labels: area/application-connector, bug

#6591 Update Connector Service image
  resources/application-connector/values.yaml
Labels: area/application-connector

#6265 Update Charts to knative-eventing 0.10.0
  resources/event-bus/charts/subscription-controller/templates/config-logging.yaml
  resources/event-bus/charts/subscription-controller/templates/config-observability.yaml
  resources/event-bus/charts/subscription-controller/templates/deployment.yaml
  resources/event-bus/charts/subscription-controller/templates/destination-rule.yaml
  resources/event-bus/charts/subscription-controller/templates/metrics-service.yaml
  resources/event-bus/charts/subscription-controller/templates/service-account.yaml
  resources/event-bus/charts/subscription-controller/templates/service-monitor.yaml
  resources/event-bus/charts/subscription-controller/values.yaml
  resources/event-bus/values.yaml
  resources/knative-eventing/Chart.yaml
  resources/knative-eventing/README.md
  resources/knative-eventing/charts/knative-eventing/Chart.yaml
  resources/knative-eventing/charts/knative-eventing/templates/eventing.yaml
  resources/knative-eventing/charts/knative-eventing/templates/pre-upgrade-job.yaml
  resources/knative-provisioner-natss/Chart.yaml
  resources/knative-provisioner-natss/README.md
  resources/knative-provisioner-natss/charts/knative-provisioner-natss/Chart.yaml
  resources/knative-provisioner-natss/charts/knative-provisioner-natss/templates/natss.yaml
  resources/knative-provisioner-natss/values.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/event-bus-subscription.yaml
Labels: area/eventing

#6450 Add request parameters to OAuth calls
  components/application-gateway/internal/metadata/serviceapi/serviceapiservice.go
  components/application-gateway/pkg/authorization/externaltokenstrategy_test.go
  components/application-gateway/pkg/authorization/factory.go
  components/application-gateway/pkg/authorization/factory_test.go
  components/application-gateway/pkg/authorization/mocks/OAuthClient.go
  components/application-gateway/pkg/authorization/model.go
  components/application-gateway/pkg/authorization/oauth/mocks/Client.go
  components/application-gateway/pkg/authorization/oauth/oauthclient.go
  components/application-gateway/pkg/authorization/oauth/oauthclient_test.go
  components/application-gateway/pkg/authorization/oauthstrategy.go
  components/application-gateway/pkg/authorization/oauthstrategy_test.go
  components/application-registry/docs/api/api.yaml
  components/application-registry/internal/externalapi/model.go
  components/application-registry/internal/metadata/applications/repository.go
  components/application-registry/internal/metadata/model/model.go
  components/application-registry/internal/metadata/model/model_test.go
  components/application-registry/internal/metadata/secrets/mocks/RequestParametersService.go
  components/application-registry/internal/metadata/secrets/requestParametersService.go
  components/application-registry/internal/metadata/secrets/requestParametersService_test.go
  components/application-registry/internal/metadata/secrets/service.go
  components/application-registry/internal/metadata/secrets/service_test.go
  components/application-registry/internal/metadata/secrets/strategy/basicauth.go
  components/application-registry/internal/metadata/secrets/strategy/basicauth_test.go
  components/application-registry/internal/metadata/secrets/strategy/certificategen.go
  components/application-registry/internal/metadata/secrets/strategy/certificategen_test.go
  components/application-registry/internal/metadata/secrets/strategy/factory.go
  components/application-registry/internal/metadata/secrets/strategy/mocks/AccessStrategy.go
  components/application-registry/internal/metadata/secrets/strategy/oauth.go
  components/application-registry/internal/metadata/secrets/strategy/oauth_test.go
  components/application-registry/internal/metadata/serviceapi/serviceapiservice.go
  components/application-registry/internal/metadata/serviceapi/serviceapiservice_test.go
  docs/application-connector/assets/metadataapi.yaml
  resources/application-connector/values.yaml
  tests/application-gateway-tests/test/executor/proxy/mock/applicationserver.go
  tests/application-gateway-tests/test/executor/proxy/mock/headershandler.go
  tests/application-gateway-tests/test/executor/proxy/mock/oauthhandler.go
  tests/application-gateway-tests/test/executor/proxy/tests/proxy_test.go
  tests/application-gateway-tests/test/executor/testkit/registry/client.go
  tests/application-gateway-tests/test/executor/testkit/registry/model.go
  tests/application-registry-tests/test/apitests/metadata_test.go
  tests/application-registry-tests/test/k8stests/k8sresource_test.go
  tests/application-registry-tests/test/testkit/model.go
Labels: area/application-connector, enhancement

#6565 Update documentation on additional headers and query parameters in Application Connector
  docs/application-connector/03-06-api-registration.md
  docs/application-connector/08-03-register-manage-services.md
  docs/application-connector/08-04-register-secured-api.md
Labels: area/application-connector, area/documentation

#6580 Update deprecated API versions
  docs/kyma/03-03-charts.md
  docs/kyma/03-04-deploy-private-registry.md
  tests/service-catalog/README.md
Labels: area/documentation

#6609 Fix the dead link
  docs/monitoring/08-05-send-notifications.md
Labels: area/documentation

#6572 Fix ModalWithForm behaviour
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, bug

#6567 Update documentation on installing Kyma via Compass Runtime Provisioner
  docs/compass/03-01-provisioner-details.md
  docs/compass/05-01-provisioner-entry-parameteres.md
  docs/compass/08-01-provisioner-provisioning-gcp.md
Labels: area/documentation

#6613 Fix title of HTTPSource adapter README
  components/event-sources/adapter/http/README.md
Labels: area/documentation

#6422 application-connector: Add support for Knative Event Mesh
  components/application-connectivity-validator/.gitignore
  components/application-connectivity-validator/cmd/applicationconnectivityvalidator/applicationconnectivityvalidator.go
  components/application-connectivity-validator/cmd/applicationconnectivityvalidator/options.go
  components/application-connectivity-validator/internal/validationproxy/handler.go
  components/application-connectivity-validator/internal/validationproxy/handler_test.go
  components/application-operator/charts/application/templates/httpsource.yaml
  components/application-operator/charts/application/templates/validator.yaml
  components/application-operator/charts/application/templates/virtual-service.yaml
  components/application-operator/charts/application/values.yaml
  resources/application-connector/values.yaml
  tests/application-operator-tests/test/testkit/k8sresources_check.go
Labels: area/eventing

#6538 Add Rafter backup/restore tests
  tests/end-to-end/backup-restore-test/Dockerfile
  tests/end-to-end/backup-restore-test/Gopkg.lock
  tests/end-to-end/backup-restore-test/Gopkg.toml
  tests/end-to-end/backup-restore-test/backupe2e/apicontroller.go
  tests/end-to-end/backup-restore-test/backupe2e/asset-store/asset-store.go
  tests/end-to-end/backup-restore-test/backupe2e/asset-store/testsuite/asset.go
  tests/end-to-end/backup-restore-test/backupe2e/asset-store/testsuite/assetData.go
  tests/end-to-end/backup-restore-test/backupe2e/asset-store/testsuite/bucket.go
  tests/end-to-end/backup-restore-test/backupe2e/asset-store/testsuite/clusterasset.go
  tests/end-to-end/backup-restore-test/backupe2e/asset-store/testsuite/clusterbucket.go
  tests/end-to-end/backup-restore-test/backupe2e/asset-store/testsuite/testsuite.go
  tests/end-to-end/backup-restore-test/backupe2e/cms/cms.go
  tests/end-to-end/backup-restore-test/backupe2e/cms/testsuite/clusterdocstopic.go
  tests/end-to-end/backup-restore-test/backupe2e/cms/testsuite/docstopic.go
  tests/end-to-end/backup-restore-test/backupe2e/cms/testsuite/testsuite.go
  tests/end-to-end/backup-restore-test/backupe2e/rafter.go
  tests/end-to-end/backup-restore-test/restore_cluster_backup_test.go
  tests/end-to-end/backup-restore-test/utils/resource/resource.go
Labels: area/cluster, area/core-and-supporting

#6635 Add RBAC settings to usage kind docs
  docs/service-catalog/06-02-usage-kind.md
Labels: area/documentation

#6544 Enable parallel tests for Application Connectivity components
  resources/application-connector/charts/application-operator/templates/tests/test.yaml
  resources/application-connector/charts/application-registry/templates/tests/test.yaml
  resources/application-connector/charts/connection-token-handler/templates/tests/test.yaml
  resources/application-connector/charts/connector-service/templates/tests/test.yaml
Labels: area/application-connector, area/quality, enhancement

#6645 Update monitoring documentation
  docs/monitoring/02-01-monitoring.md
  docs/monitoring/03-01-alertmanager.md
  docs/monitoring/05-01-alertmanager.md
  docs/monitoring/05-02-grafana.md
  docs/monitoring/05-03-prometheus.md
  docs/monitoring/08-01-overview.md
  docs/monitoring/08-02-observe-application-metrics.md
  docs/monitoring/08-03-create-and-configure-grafana-dashboard.md
  docs/monitoring/08-04-define-alerting-rules.md
  docs/monitoring/08-05-send-notifications.md
  docs/monitoring/assets/min-max-values.png
  docs/monitoring/assets/temperature-celsius.png
  resources/monitoring/README.md
  resources/monitoring/customresources.md
Labels: area/monitoring

#6620 Update the doc on overrides
  docs/kyma/05-03-overrides.md
Labels: area/documentation, area/installation

#6599 Add migration job of resources from AssetStore/CMS to Rafter
  resources/rafter/templates/_helper_migration_assetstore_resources.txt
  resources/rafter/templates/_helper_migration_create_rafter_upload_service_config_map.txt
  resources/rafter/templates/_helper_migration_system_buckets.txt
  resources/rafter/templates/_helper_migration_terminator.txt
  resources/rafter/templates/_helpers.tpl
  resources/rafter/templates/migration-job-post.yaml
  resources/rafter/templates/migration-job-pre.yaml
  resources/rafter/templates/migration-job-terminator.yaml
  resources/rafter/values.yaml
Labels: area/core-and-supporting, enhancement

#6666 new retention and memory defaults for monitoring setup
  resources/monitoring/values.yaml
Labels: area/monitoring

#6673 Fix backup deployment
  resources/backup/templates/deployment.yaml
Labels: bug

#6624 Enable event-sources component
  components/application-operator/charts/application/templates/httpsource.yaml
  components/application-operator/charts/application/values.yaml
  installation/resources/installer-cr-cluster-runtime.yaml.tpl
  installation/resources/installer-cr-cluster-with-compass.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  resources/event-bus/charts/subscription-controller/templates/config-logging.yaml
  resources/event-sources/templates/400-config-logging.yaml
  resources/event-sources/templates/400-config-observability.yaml
Labels: area/eventing

#6575 Add Rafter docs
  docs/rafter/01-01-rafter.md
  docs/rafter/01-02-rafter-in-kyma.md
  docs/rafter/02-01-basic-asset-flow.md
  docs/rafter/02-02-assetgroup.md
  docs/rafter/02-03-asset-and-bucket.md
  docs/rafter/03-01-asset-cr-lifecycle.md
  docs/rafter/03-02-bucket-cr-lifecycle.md
  docs/rafter/03-03-assetgroup-cr-lifecycle.md
  docs/rafter/03-04-minio-gateway.md
  docs/rafter/03-05-supported-webhooks.md
  docs/rafter/03-06-upload-service.md
  docs/rafter/03-07-asyncapi-service.md
  docs/rafter/03-08-front-matter-service.md
  docs/rafter/05-01-rafter.md
  docs/rafter/06-01-asset.md
  docs/rafter/06-02-assetgroup.md
  docs/rafter/06-03-bucket.md
  docs/rafter/06-04-clusterasset.md
  docs/rafter/06-05-clusterassetgroup.md
  docs/rafter/06-06-clusterbucket.md
  docs/rafter/08-01-add-new-documentation-to-console.md
  docs/rafter/08-02-set-minio-to-gateway-mode.md
  docs/rafter/11-01-rafter-controller-manager.md
  docs/rafter/11-02-asyncapi-service.md
  docs/rafter/11-03-upload-service.md
  docs/rafter/11-04-front-matter-service.md
  docs/rafter/11-05-minio.md
  docs/rafter/assets/asyncapi-service-openapi.yaml
  docs/rafter/assets/basic-architecture.svg
  docs/rafter/assets/create-asset.svg
  docs/rafter/assets/create-bucket.svg
  docs/rafter/assets/delete-asset.svg
  docs/rafter/assets/delete-bucket.svg
  docs/rafter/assets/example-openapi-service.yaml
  docs/rafter/assets/front-matter-service-openapi.yaml
  docs/rafter/assets/minio-gateway.svg
  docs/rafter/assets/minio.svg
  docs/rafter/assets/modify-asset.svg
  docs/rafter/assets/modify-bucket-ref-asset.svg
  docs/rafter/assets/prometheus.png
  docs/rafter/assets/rafter-architecture-1.svg
  docs/rafter/assets/rafter-architecture-2.svg
  docs/rafter/assets/tabs-catalog-ui.png
  docs/rafter/assets/upload-service-openapi.yaml
  docs/rafter/assets/upload-service.svg
  milv.config.yaml
Labels: area/core-and-supporting, area/documentation

#6474 Add integration tests for rafter domain in console-backend-service
  tests/console-backend-service/Gopkg.lock
  tests/console-backend-service/Gopkg.toml
  tests/console-backend-service/README.md
  tests/console-backend-service/internal/domain/cms/clusterdocstopic_test.go
  tests/console-backend-service/internal/domain/cms/cms.go
  tests/console-backend-service/internal/domain/rafter/clusterassetgroup_test.go
  tests/console-backend-service/internal/domain/rafter/rafter.go
  tests/console-backend-service/internal/domain/rafter/rafter_test.go
  tests/console-backend-service/internal/domain/servicecatalog/clusterserviceclass_test.go
  tests/console-backend-service/internal/domain/servicecatalog/serviceclass_test.go
  tests/console-backend-service/internal/domain/shared/asset.go
  tests/console-backend-service/internal/domain/shared/assetgroup.go
  tests/console-backend-service/internal/domain/shared/clusterasset.go
  tests/console-backend-service/internal/domain/shared/clusterassetgroup.go
  tests/console-backend-service/internal/domain/shared/clusterdocstopic.go
  tests/console-backend-service/internal/domain/shared/clusterserviceclass.go
  tests/console-backend-service/internal/domain/shared/docstopic.go
  tests/console-backend-service/internal/domain/shared/fixture/assetgroup.go
  tests/console-backend-service/internal/domain/shared/fixture/clusterasset.go
  tests/console-backend-service/internal/domain/shared/fixture/clusterassetgroup.go
  tests/console-backend-service/internal/domain/shared/fixture/clusterdocstopic.go
  tests/console-backend-service/internal/domain/shared/fixture/docstopic.go
  tests/console-backend-service/internal/domain/shared/serviceclass.go
  tests/console-backend-service/internal/domain/shared/wait/assetgroup.go
  tests/console-backend-service/internal/domain/shared/wait/clusterassetgroup.go
  tests/console-backend-service/internal/domain/shared/wait/clusterdocstopic.go
  tests/console-backend-service/internal/domain/shared/wait/docstopic.go
  tests/console-backend-service/internal/resource/assetgroup.go
  tests/console-backend-service/internal/resource/clusterassetgroup.go
  tests/console-backend-service/internal/resource/clusterdocstopic.go
  tests/console-backend-service/internal/resource/docstopic.go
Labels: area/core-and-supporting, enhancement

#6627 Migrate Compass Runtime to Rafter
  components/compass-runtime-agent/cmd/init.go
  components/compass-runtime-agent/cmd/options.go
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  components/compass-runtime-agent/internal/compass/connector/mocks/Client.go
  components/compass-runtime-agent/internal/kyma/apiresources/assetstore/docstopicrepository.go
  components/compass-runtime-agent/internal/kyma/apiresources/assetstore/mocks/DocsTopicRepository.go
  components/compass-runtime-agent/internal/kyma/apiresources/assetstore/service.go
  components/compass-runtime-agent/internal/kyma/apiresources/mocks/Service.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/clusterassetgroup/model.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/clusterassetgrouprepository.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/clusterassetgrouprepository_test.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/mocks/ClusterAssetGroupRepository.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/mocks/ResourceInterface.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/mocks/Service.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/service.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/service_test.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/upload/client.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/upload/client_test.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/upload/mocks/Client.go
  components/compass-runtime-agent/internal/kyma/apiresources/service.go
  components/compass-runtime-agent/internal/kyma/apiresources/service_test.go
  components/compass-runtime-agent/internal/kyma/model/types.go
  components/compass-runtime-agent/internal/kyma/service.go
  components/compass-runtime-agent/internal/kyma/service_test.go
  components/compass-runtime-agent/pkg/apis/compass/v1alpha1/zz_generated.deepcopy.go
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/Gopkg.toml
  tests/compass-runtime-agent/test/runtimeagent/suite.go
  tests/compass-runtime-agent/test/testkit/assertions/k8s_resource_checker.go
Labels: enhancement

#6660 Enable rafter e2e upgrade tests
  tests/end-to-end/upgrade/README.md
  tests/end-to-end/upgrade/main.go
Labels: area/core-and-supporting, enhancement

#6642 Add minor Application Connector documentation fixes
  docs/application-connector/08-02-get-client-certificate.md
  docs/application-connector/08-03-register-manage-services.md
  docs/application-connector/08-04-register-secured-api.md
  docs/compass/08-06-provisioner-clean-up-runtime-data.md
Labels: area/application-connector, area/documentation

#6569 Migrate Assetstore integration tests to Rafter
  resources/rafter/templates/tests/rbac.yaml
  resources/rafter/templates/tests/test.yaml
  resources/rafter/values.yaml
  tests/rafter/.gitignore
  tests/rafter/Dockerfile
  tests/rafter/Gopkg.lock
  tests/rafter/Gopkg.toml
  tests/rafter/Makefile
  tests/rafter/README.md
  tests/rafter/before-commit.sh
  tests/rafter/main_test.go
  tests/rafter/pkg/mockice/asyncapiFile.go
  tests/rafter/pkg/mockice/mockice.go
  tests/rafter/pkg/namespace/namespace.go
  tests/rafter/pkg/resource/resource.go
  tests/rafter/pkg/retry/retry.go
  tests/rafter/pkg/retry/retry_test.go
  tests/rafter/testsuite/assetdetails.go
  tests/rafter/testsuite/assetgroup.go
  tests/rafter/testsuite/bucket.go
  tests/rafter/testsuite/clusterassetgroup.go
  tests/rafter/testsuite/clusterbucket.go
  tests/rafter/testsuite/common.go
  tests/rafter/testsuite/testsuite.go
Labels: area/core-and-supporting, enhancement

#6623 Move hardcoded cert values into helm chart
  resources/application-connector/charts/connector-service/templates/connector-service-app-ca-secret.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#6690 Fix command in Kyma installation with your own domain
  docs/kyma/04-05-use-your-own-domain.md
Labels: area/documentation, bug

#6640 Fix generic list dropdown opening direction
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#6641 Add request flow to API Gateway V2 architecture doc
  docs/api-gateway-v2/02-01-api-gateway.md
  docs/api-gateway-v2/assets/002-api-gateway-request-flow.svg
Labels: area/documentation, area/security

#6693 Disable failing UI tests
  resources/core/charts/console/values.yaml
Labels: area/console, bug, test-failing

#6650 Document using CLI to provision clusters using Gardener
  docs/kyma/04-04-cluster-installation.md
Labels: area/cli, area/documentation, area/installation

#6694 Remove AS & HCMS docs
  docs/asset-store/01-01-asset-store.md
  docs/asset-store/02-01-asset-store.md
  docs/asset-store/03-01-asset-cr-lifecycle.md
  docs/asset-store/03-02-bucket-cr-lifecycle.md
  docs/asset-store/03-03-minio-gateway.md
  docs/asset-store/03-04-supported-webhooks.md
  docs/asset-store/03-05-asset-metadata-service.md
  docs/asset-store/03-06-asset-upload-service.md
  docs/asset-store/05-01-asset-store.md
  docs/asset-store/05-02-asset-store-metadata-service.md
  docs/asset-store/05-03-asset-store-controller-manager.md
  docs/asset-store/05-04-asset-upload-service.md
  docs/asset-store/05-05-minio.md
  docs/asset-store/06-01-asset.md
  docs/asset-store/06-02-bucket.md
  docs/asset-store/06-03-clusterasset.md
  docs/asset-store/06-04-clusterbucket.md
  docs/asset-store/08-01-gateway-gcs-mode-set-up.md
  docs/asset-store/08-02-gateway-azure-mode-set-up.md
  docs/asset-store/08-03-gateway-s3-mode-set-up.md
  docs/asset-store/08-04-gateway-oss-mode-set.md
  docs/asset-store/11-01-asset-store-controller.md
  docs/asset-store/11-02-asset-metadata-service.md
  docs/asset-store/11-03-asset-upload-service.md
  docs/asset-store/11-04-minio.md
  docs/asset-store/assets/asset-metadata-service-openapi.yaml
  docs/asset-store/assets/asset-store-architecture.svg
  docs/asset-store/assets/asset-upload-service-openapi.yaml
  docs/asset-store/assets/asset-upload-service.svg
  docs/asset-store/assets/create-asset.svg
  docs/asset-store/assets/create-bucket.svg
  docs/asset-store/assets/delete-asset.svg
  docs/asset-store/assets/delete-bucket.svg
  docs/asset-store/assets/example-openapi-service.yaml
  docs/asset-store/assets/minio-gateway.svg
  docs/asset-store/assets/minio.svg
  docs/asset-store/assets/modify-asset.svg
  docs/asset-store/assets/modify-bucket-ref-asset.svg
  docs/headless-cms/01-01-headless-cms.md
  docs/headless-cms/02-01-headless-cms.md
  docs/headless-cms/03-01-docstopic-cr-lifecycle.md
  docs/headless-cms/03-02-cms-asyncapi-service.md
  docs/headless-cms/05-01-cms-controller-manager.md
  docs/headless-cms/05-02-cms-asynapi-service.md
  docs/headless-cms/06-01-docstopic.md
  docs/headless-cms/06-02-clusterdocstopic.md
  docs/headless-cms/08-01-add-new-documentation-to-console.md
  docs/headless-cms/11-01-cms-controller-manager.md
  docs/headless-cms/11-02-asyncapi-service.md
  docs/headless-cms/assets/headless-cms-architecture.svg
  docs/headless-cms/assets/prometheus.png
  docs/headless-cms/assets/tabs-catalog-ui.png
  docs/rafter/assets/asyncapi-service-openapi.yaml
  docs/rafter/assets/example-openapi-service.yaml
  docs/rafter/assets/front-matter-service-openapi.yaml
  docs/rafter/assets/upload-service-openapi.yaml
Labels: area/documentation

#6696 Remove deprecated links
  docs/rafter/06-03-bucket.md
  docs/rafter/06-06-clusterbucket.md
Labels: area/documentation

#6594 Rafter dashboards
  resources/monitoring/templates/grafana/kyma-dashboards/assetstore-controller-manager.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/assetstore-metadata-service.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/assetstore-upload-service.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/cms-asyncapi-service.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/cms-controller-manager.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/minio.yaml
  resources/rafter/charts/asyncapi-service/templates/dashboard-configmap.yaml
  resources/rafter/charts/controller-manager/charts/minio/templates/dashboard-configmap.yaml
  resources/rafter/charts/controller-manager/templates/dashboard-configmap.yaml
  resources/rafter/charts/front-matter-service/templates/dashboard-configmap.yaml
  resources/rafter/charts/upload-service/templates/dashboard-configmap.yaml
Labels: area/core-and-supporting, area/monitoring

#6704 Replace pvc as emprtyDir in rafter-migration-post job
  resources/rafter/templates/migration-job-post.yaml
Labels: area/core-and-supporting, bug

#6678 IDP Preset overwritten on Lambda Save
  resources/core/charts/console/values.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
Labels: area/console, bug

#6692 Prevent reloading on each navigation change in compass
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#6638 Separate flows for adding API and Event API to Application
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#6689 Bump Compass charts
  resources/compass/charts/director/config.yaml
  resources/compass/charts/director/static-users.yaml
  resources/compass/charts/director/templates/deployment.yaml
  resources/compass/charts/gateway/values.yaml
  resources/compass/templates/director-test.yaml
  resources/compass/templates/e2e-compass-test.yaml
  resources/compass/values.yaml
Labels: enhancement

#6705 Don't remove old crds in rafter-migration-post-terminator
  resources/rafter/templates/_helper_migration_terminator.txt
Labels: area/core-and-supporting

#6707 Fix dead links
  README.md
  docs/helm-broker/03-03-create-addons-repo.md
  docs/monitoring/08-05-send-notifications.md
Labels: area/documentation

#6706 Provide tutorial on how to create certificate application pairing via Compass
  docs/compass/08-07-establish-secure-connection-with-compass.md
  docs/compass/08-08-maintain-secure-connection-with-compass.md
  docs/compass/08-09-revoke-client-certificate.md
Labels: area/documentation

#6709 Bump images of Application Connector
  resources/application-connector/values.yaml
Labels: area/application-connector

#6636 Knative Eventing Mesh enabled Application Broker
  components/application-broker/Gopkg.lock
  components/application-broker/Gopkg.toml
  components/application-broker/cmd/broker/main.go
  components/application-broker/cmd/broker/main_test.go
  components/application-broker/internal/broker/broker.go
  components/application-broker/internal/broker/deprovision.go
  components/application-broker/internal/broker/deprovision_test.go
  components/application-broker/internal/broker/fix_test.go
  components/application-broker/internal/broker/provision.go
  components/application-broker/internal/broker/provision_test.go
  components/application-broker/internal/broker/testing/api_object.go
  components/application-broker/internal/broker/testing/client_assertion.go
  components/application-broker/internal/knative/broker.go
  components/application-broker/internal/knative/client.go
  components/application-broker/internal/knative/subscription.go
  components/application-broker/internal/model.go
Labels: area/eventing, area/service-catalog

#6617 Add documentation for Knative Eventing Mesh
  docs/event-bus/01-01-event-bus.md
  docs/event-bus/03-04-knative-eventing-mesh.md
  docs/event-bus/assets/knative-event-mesh-send-events.svg
  docs/event-bus/assets/knative-event-mesh-subscription.svg
Labels: area/documentation, area/eventing

#6648 Add UAA activator
  CODEOWNERS
  components/uaa-activator/.gitignore
  components/uaa-activator/Dockerfile
  components/uaa-activator/Gopkg.lock
  components/uaa-activator/Gopkg.toml
  components/uaa-activator/Makefile
  components/uaa-activator/README.md
  components/uaa-activator/internal/ctxutil/cancelable.go
  components/uaa-activator/internal/ctxutil/check.go
  components/uaa-activator/internal/dex/configurator.go
  components/uaa-activator/internal/dex/overrider.go
  components/uaa-activator/internal/dex/uaa_renderer.go
  components/uaa-activator/internal/repeat/durations.go
  components/uaa-activator/internal/repeat/until_success.go
  components/uaa-activator/internal/scheduler/scheduler.go
  components/uaa-activator/internal/uaa/config.go
  components/uaa-activator/internal/uaa/creator.go
  components/uaa-activator/internal/uaa/waiter.go
  components/uaa-activator/main.go
  resources/core/charts/cluster-users/templates/rbac-roles.yaml
  resources/core/charts/cluster-users/values.yaml
  resources/service-manager-proxy/Chart.yaml
  resources/service-manager-proxy/values.yaml
  resources/uaa-activator/.helmignore
  resources/uaa-activator/Chart.yaml
  resources/uaa-activator/README.md
  resources/uaa-activator/templates/_helpers.tpl
  resources/uaa-activator/templates/job.yaml
  resources/uaa-activator/templates/rbac.yaml
  resources/uaa-activator/templates/secret.yaml
  resources/uaa-activator/values.yaml
Labels: area/documentation, area/security, area/service-catalog, enhancement

#6722 Downgrade Go version in App Registry and App Gateway
  components/application-gateway/Dockerfile
  components/application-registry/Dockerfile
Labels: bug, priority/critical

#6724 Bump images of App Registry and App Gateway
  resources/application-connector/values.yaml
Labels: area/application-connector, bug

#6731 Update CODEOWNERS for Rafter
  CODEOWNERS
Labels: area/core-and-supporting, enhancement

#6671 Introduce Helm good practices in Rafter chart
  resources/rafter/templates/_helper_tests.txt
  resources/rafter/templates/_helpers.tpl
  resources/rafter/templates/tests/rbac.yaml
  resources/rafter/templates/tests/test.yaml
  resources/rafter/values.yaml
  tests/rafter/Makefile
Labels: area/core-and-supporting, enhancement

#6736 Update Rafter tests image
  resources/rafter/values.yaml
Labels: area/core-and-supporting, enhancement

#6741 Fix dead links
  README.md
  docs/monitoring/08-05-send-notifications.md
Labels: area/documentation, bug

#6734 Fix link
  docs/event-bus/01-01-event-bus.md
Labels: area/documentation, area/eventing

#6744 Set Upload Service URL in Helm Broker and bump addons version
  resources/helm-broker/templates/default-addons-cfg.yaml
  resources/helm-broker/templates/deploy.yaml
Labels: area/core-and-supporting, area/service-catalog, bug

#6619 event-sources: Disable Knative scale to 0
  components/event-sources/Gopkg.lock
  components/event-sources/reconciler/httpsource/reconcile.go
  components/event-sources/reconciler/httpsource/reconcile_test.go
  components/event-sources/reconciler/object/equality.go
  components/event-sources/reconciler/object/equality_test.go
  components/event-sources/reconciler/object/service.go
  components/event-sources/test/fixtures/ksvc.json
Labels: area/eventing

#6749 Fix apollo cache policy
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
Labels: area/console, bug
