Repository kyma-project/kyma, pull requests merged in 2019-11, with the labels that each got.

#5781 Remove Santiago
  CODEOWNERS
Labels: area/serverless

#6201 Improve API Gateway v2 documentation
  docs/api-gateway-v2/06-01-apirule.md
  docs/api-gateway-v2/08-01-exposesecure.md
Labels: area/documentation, area/security

#6071 Enable cbs tests
  tests/console-backend-service/internal/domain/cms/clusterdocstopic_test.go
  tests/console-backend-service/internal/domain/k8s/configmap_test.go
  tests/console-backend-service/internal/domain/k8s/service_test.go
  tests/console-backend-service/internal/domain/servicecatalog/clusterserviceclass_test.go
  tests/console-backend-service/internal/domain/servicecatalogaddons/servicebinding_usage_test.go
Labels: WIP, test-failing, test-missing

#6209 Update compass director component
  resources/compass/values.yaml
Labels: enhancement

#6084 Enable core-console-backend-service test
  resources/core/charts/console-backend-service/values.yaml
  resources/core/values.yaml
Labels: WIP, test-failing, test-missing

#6194 Enable external solution tests
  resources/core/values.yaml
Labels: priority/critical, test-failing, test-missing

#6202 Navigate to namespace details after namespace creation
  resources/core/charts/console/values.yaml
Labels: area/console, enhancement

#6092 Update Application UI [Compass]
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#6208 Keep tab context in service catalog list
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
Labels: area/console, enhancement

#6050 Exclude Services related to NATSS Channels in restore
  components/backup-plugins/Gopkg.lock
  components/backup-plugins/internal/plugins/natsschannel_services.go
  components/backup-plugins/main.go
  docs/backup/assets/backup.yaml
  tests/end-to-end/backup-restore-test/restore_cluster_backup_test.go
Labels: area/eventing

#6219 Bump backup restore test image
  tests/end-to-end/backup-restore-test/deploy/chart/backup-test/values.yaml
Labels: area/eventing

#6222 Improve backup documentation
  docs/backup/04-01-install-velero.md
  docs/backup/05-01-velero.md
  docs/backup/10-01-restore-troubleshooting.md
  docs/kyma/04-01-overview.md
Labels: area/cluster, area/documentation, bug

#6228 disable apigateway tests
  resources/api-gateway/values.yaml
Labels: test-failing

#6189 Move certificate update information to Security
  docs/kyma/10-07-expired-cert.md
  docs/security/08-01-update-tls-certificates.md
Labels: area/documentation, area/security

#6247 Disable the pod-not-running rule
  resources/monitoring/charts/alert-rules/templates/kyma-rules.yaml
Labels: area/monitoring, bug, priority/critical

#6190 View and edit lambda code (knative)
  resources/core/charts/console-backend-service/templates/cluster-role.yaml
  resources/core/charts/console/values.yaml
Labels: area/console, enhancement

#6264 Oathkeeper maester image bump
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/values.yaml
Labels: area/security

#6236 Knative Source HTTP Adapter for Broker/Trigger
  components/event-sources/.gitignore
  components/event-sources/Gopkg.lock
  components/event-sources/Makefile
  components/event-sources/adapter/http/README.md
  components/event-sources/adapter/http/adapter.go
  components/event-sources/adapter/http/adapter_integration_test.go
  components/event-sources/adapter/http/adapter_test.go
  components/event-sources/cmd/http-adapter/main.go
  components/event-sources/hack/set-span-id.patch
Labels: area/eventing

#6257 Improved consistency of logging chart
  resources/core/charts/istio-rbac/values.yaml
  resources/logging/charts/log-ui/.helmignore
  resources/logging/charts/log-ui/Chart.yaml
  resources/logging/charts/log-ui/OWNERS
  resources/logging/charts/log-ui/README.md
  resources/logging/charts/log-ui/templates/_helpers.tpl
  resources/logging/charts/log-ui/templates/configmap.yaml
  resources/logging/charts/log-ui/templates/deployment.yaml
  resources/logging/charts/log-ui/templates/destination-rule.yaml
  resources/logging/charts/log-ui/templates/service.yaml
  resources/logging/charts/log-ui/values.yaml
  resources/logging/templates/fluent-bit-plugin/fluent-bit-role-binding.yaml
  resources/logging/templates/fluent-bit-plugin/fluent-bit-service-account.yaml
  resources/logging/templates/fluent-bit/_helpers.tpl
  resources/logging/templates/fluent-bit/configmap.yaml
  resources/logging/templates/fluent-bit/daemonset.yaml
  resources/logging/templates/fluent-bit/role.yaml
  resources/logging/templates/fluent-bit/rolebinding.yaml
  resources/logging/templates/log-ui/_helpers.tpl
  resources/logging/templates/log-ui/clustermicrofrontend.yaml
  resources/logging/templates/log-ui/configmap.yaml
  resources/logging/templates/log-ui/deployment.yaml
  resources/logging/templates/log-ui/destinationrule.yaml
  resources/logging/templates/log-ui/service.yaml
  resources/logging/templates/log-ui/virtualservice.yaml
  resources/logging/templates/loki/destinationrule.yaml
  resources/logging/templates/loki/istio-rbac.yaml
  resources/logging/templates/loki/policy.yaml
  resources/logging/templates/loki/role.yaml
  resources/logging/templates/loki/rolebinding.yaml
  resources/logging/templates/loki/serviceaccount.yaml
  resources/logging/templates/loki/servicemonitor.yaml
  resources/logging/templates/loki/servicerole.yaml
  resources/logging/templates/loki/servicerolebinding.yaml
  resources/logging/templates/loki/statefulset.yaml
  resources/logging/templates/loki/virtualservice.yaml
  resources/logging/templates/promtail/clusterrole.yaml
  resources/logging/templates/promtail/clusterrolebinding.yaml
  resources/logging/templates/promtail/role.yaml
  resources/logging/templates/promtail/rolebinding.yaml
  resources/logging/values.yaml
  resources/monitoring/charts/grafana/templates/datasource-configmap.yaml
Labels: area/logging

#6178 Authenticate Compass Runtime Agent tests via Dex
  resources/compass-runtime-agent/templates/tests/role-binding.yaml
  resources/compass-runtime-agent/templates/tests/test-runtime-agent-integration.yaml
  resources/compass-runtime-agent/values.yaml
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/scripts/run_tests.sh
  tests/compass-runtime-agent/test/runtimeagent/suite.go
  tests/compass-runtime-agent/test/testkit/authentication/config.go
  tests/compass-runtime-agent/test/testkit/authentication/get_token.go
  tests/compass-runtime-agent/test/testkit/authentication/id_token_provider.go
  tests/compass-runtime-agent/test/testkit/compass/client.go
  tests/compass-runtime-agent/test/testkit/config.go
  tests/compass-runtime-agent/test/testkit/secrets/model.go
  tests/compass-runtime-agent/test/testkit/secrets/repository.go
Labels: area/application-connector, enhancement

#6262 Bump compass tests
  resources/compass/templates/director-test.yaml
  resources/compass/templates/e2e-compass-test.yaml
  resources/compass/values.yaml
Labels: enhancement

#6272 Integrate HTTP adapter with Reconciler
  components/event-sources/Gopkg.lock
  components/event-sources/Makefile
  components/event-sources/README.md
  components/event-sources/adapter/http/README.md
  components/event-sources/apis/sources/v1alpha1/http_lifecycle.go
  components/event-sources/apis/sources/v1alpha1/http_types.go
  components/event-sources/config/200-rbac.yaml
  components/event-sources/config/500-sources-controller.yaml
  components/event-sources/config/samples/dummy-httpsource.yaml
  components/event-sources/reconciler/httpsource/adapter_config.go
  components/event-sources/reconciler/httpsource/controller.go
  components/event-sources/reconciler/httpsource/controller_test.go
  components/event-sources/reconciler/httpsource/reconcile.go
  components/event-sources/reconciler/httpsource/reconcile_test.go
  components/event-sources/reconciler/objects/channel_test.go
  components/event-sources/reconciler/objects/equality.go
  components/event-sources/reconciler/objects/equality_test.go
  components/event-sources/reconciler/objects/service.go
  components/event-sources/reconciler/objects/service_test.go
  components/event-sources/reconciler/testing/configmap.go
  components/event-sources/reconciler/testing/env.go
  components/event-sources/reconciler/testing/factory.go
  components/event-sources/reconciler/testing/httpsource.go
  components/event-sources/reconciler/testing/service.go
  components/event-sources/test/fixtures/ksvc.json
Labels: area/eventing

#6280 Fix broken links
  docs/serverless/06-01-function.md
  docs/service-mesh/01-01-service-mesh.md
  docs/service-mesh/03-03-istio-rbac.md
  docs/service-mesh/10-03-connection-refused.md
  docs/service-mesh/10-04-jobs-fail-aks.md
  resources/api-gateway/README.md
  resources/dex/README.md
Labels: area/documentation

#6277 Change caching policy for GraphQL requests
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#6252 Manage function dependencies
  resources/core/charts/console/values.yaml
Labels: area/console, enhancement

#6284 Metrics: ORY controllers
  resources/monitoring/charts/grafana/dashboards/ory-hydra-maester-dashboard.json
  resources/monitoring/charts/grafana/dashboards/ory-oathkeeper-maester-dashboard.json
  resources/ory/charts/hydra/charts/hydra-maester/templates/deployment.yaml
  resources/ory/charts/hydra/charts/hydra-maester/templates/servicemonitor.yaml
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/templates/deployment.yaml
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/templates/servicemonitor.yaml
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/values.yaml
Labels: area/security

#6230 Fix tracing
  docs/tracing/10-01-traces-troubleshooting.md
  resources/event-bus/charts/event-publish-service/templates/service.yaml
  resources/knative-eventing/README.md
  resources/knative-eventing/charts/knative-eventing/templates/eventing.yaml
  resources/knative-eventing/values.yaml
  resources/knative-provisioner-natss/charts/knative-provisioner-natss/templates/natss.yaml
Labels: area/tracing

#6267 Connect with Remote Application via Compass UI
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#6276 Add XSUAA to Dex connectors tutorial
  docs/security/08-03-add-connector.md
  milv.config.yaml
Labels: area/documentation, area/security

#6281 Add container port to Application Gateway test executor pod
  components/application-operator/charts/application/templates/tests/destination-rule.yaml
  resources/application-connector/values.yaml
  tests/application-gateway-tests/test/helmtest/proxy/suite.go
Labels: area/application-connector

#6309 Upgrade natss images to knative eventing 0.8.1
  resources/knative-provisioner-natss/charts/knative-provisioner-natss/templates/natss.yaml
  resources/knative-provisioner-natss/values.yaml
Labels: area/eventing

#6302 Align changes in compass chart
  resources/compass/charts/director/config.yaml
  resources/compass/charts/director/templates/deployment.yaml
  resources/compass/values.yaml
Labels: enhancement

#6335 Fix dead link
  docs/tracing/03-02-jaeger.md
Labels: area/documentation

#6333 Fetch Dex token after waiting for API Server in Runtime Agent tests
  resources/compass-runtime-agent/values.yaml
  tests/compass-runtime-agent/test/runtimeagent/suite.go
  tests/compass-runtime-agent/test/testkit/compass/client.go
Labels: area/application-connector

#6238 Remove migration job; bump ServiceCatalog image version
  components/application-broker/.gitignore
  components/application-broker/cmd/migration/main.go
  components/application-broker/deploy/migration/Dockerfile
  components/service-binding-usage-controller/.gitignore
  components/service-binding-usage-controller/cmd/migration/main.go
  components/service-binding-usage-controller/deploy/migration/Dockerfile
  resources/service-catalog/charts/catalog/Chart.yaml
  resources/service-catalog/charts/catalog/templates/_helpers.tpl
  resources/service-catalog/charts/catalog/templates/kyma-migration/post-upgrade-ab-job.yaml
  resources/service-catalog/charts/catalog/templates/kyma-migration/post-upgrade-sbu-job.yaml
  resources/service-catalog/charts/catalog/templates/kyma-migration/pre-upgrade-sbu-job.yaml
  resources/service-catalog/charts/catalog/templates/migration-job.yaml
  resources/service-catalog/charts/catalog/templates/pre-migration-job.yaml
  resources/service-catalog/charts/catalog/templates/pvc-checker.yaml
  resources/service-catalog/charts/catalog/templates/reproccess-job.yaml
  resources/service-catalog/charts/catalog/values.yaml
Labels: area/service-catalog

#6297 Scenario Details View (no longer) crashes with minified react error
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, bug

#6307 Enable Service Catalog Cascading Deletion
  resources/service-catalog/charts/catalog/templates/controller-manager-deployment.yaml
  resources/service-catalog/charts/catalog/values.yaml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
  tests/end-to-end/upgrade/pkg/tests/service-catalog/base_flow.go
  tests/service-catalog/test/servicecatalog_test.go
Labels: area/service-catalog, enhancement

#6338 Parametrize Compass Connector RBAC rule
  resources/compass/charts/connector/templates/service-role-binding.yaml
  resources/compass/charts/connector/values.yaml
Labels: bug

#6294 Bump Oathkeeper image to support alternative token location
  resources/ory/charts/oathkeeper/templates/deployment.yaml
  resources/ory/charts/oathkeeper/values.yaml
  resources/ory/values.yaml
Labels: area/security, area/service-mesh, enhancement

#6275 Expose new information from Cluster-/AddonConfigurations
  components/console-backend-service/internal/domain/servicecatalogaddons/addonsconfiguration_converter.go
  components/console-backend-service/internal/domain/servicecatalogaddons/addonsconfiguration_converter_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/clusteraddonsconfiguration_converter_test.go
  components/console-backend-service/internal/gqlschema/models_gen.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
Labels: area/console, enhancement

#6311 Refactored readiness check handler and fixed metrics
  components/event-bus/cmd/event-publish-service/application/application.go
  components/event-bus/cmd/event-publish-service/application/application_test.go
  components/event-bus/cmd/event-publish-service/handlers/publish.go
  components/event-bus/cmd/event-publish-service/handlers/readiness_check.go
  components/event-bus/cmd/event-publish-service/publisher/publisher.go
  components/event-bus/cmd/event-publish-service/test/fake/publisher.go
  components/event-bus/internal/knative/subscription/controller/subscription/reconcile_test.go
  components/event-bus/internal/knative/util/kn-eventing.go
  components/event-bus/internal/knative/util/kn-eventing_test.go
Labels: area/eventing

#6318 Bump event-bus image
  resources/event-bus/values.yaml
Labels: WIP, area/eventing

#6362 Describe available security schemes in API Gateway v2
  docs/api-gateway-v2/03-01-security_options.md
  docs/api-gateway-v2/03-02-whitelisted-domains.md
  docs/api-gateway-v2/03-03-blacklisted-services.md
Labels: area/documentation, area/security

#6369 Disable apigateway tests
  resources/api-gateway/values.yaml
Labels: bug, test-failing

#6377 Move back Application Connector Istio secret to Gateway chart
  resources/core/charts/gateway/templates/application-connector-certs.yaml
Labels: area/application-connector, priority/critical

#6368 Document Compass Provisioner component
  docs/compass/03-01-provisioner-details.md
  docs/compass/05-01-provisioner-entry-parameteres.md
  docs/compass/08-01-provisioner-provisioning-gcp.md
  docs/compass/08-02-provisioner-provisioning-gardener.md
  docs/compass/08-03-provisioner-runtime-operation-status.md
  docs/compass/08-04-provisioner-runtime-status.md
  docs/compass/08-05-provisioner-deprovisioning.md
  docs/compass/08-06-provisioner-clean-up-runtime-data.md
Labels: area/documentation

#6363 Revert "Bump Oathkeeper image to support alternative token location"
  resources/ory/charts/oathkeeper/templates/deployment.yaml
  resources/ory/charts/oathkeeper/values.yaml
  resources/ory/values.yaml
Labels: bug

#6336 Bump Provisioner images
  resources/compass/values.yaml
Labels: enhancement

#6340 Runtime Agent saves System Auth Ids to Application CR
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/types.go
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  components/compass-runtime-agent/internal/certificates/model.go
  components/compass-runtime-agent/internal/certificates/model_test.go
  components/compass-runtime-agent/internal/compass/connector/client.go
  components/compass-runtime-agent/internal/compass/connector/client_test.go
  components/compass-runtime-agent/internal/compass/connector/mocks/Client.go
  components/compass-runtime-agent/internal/compass/director/client_test.go
  components/compass-runtime-agent/internal/compass/director/converter.go
  components/compass-runtime-agent/internal/compass/director/converter_test.go
  components/compass-runtime-agent/internal/compass/director/model.go
  components/compass-runtime-agent/internal/compass/director/query.go
  components/compass-runtime-agent/internal/compassconnection/connector.go
  components/compass-runtime-agent/internal/compassconnection/package_main_test.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/kyma/applications/converter.go
  components/compass-runtime-agent/internal/kyma/applications/converter_test.go
  components/compass-runtime-agent/internal/kyma/applications/repository.go
  components/compass-runtime-agent/internal/kyma/model/types.go
  components/compass-runtime-agent/internal/kyma/service.go
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, priority/critical

#6305 Bump Application Connectivity images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  resources/core/values.yaml
Labels: area/application-connector

#6358 Disable Kubeless tests
  resources/core/charts/kubeless/values.yaml
Labels: area/serverless, test-failing

#6420 Remove the API document type
  docs/application-connector/02-02-connector-service.md
  docs/application-connector/08-11-get-api-specification.md
  docs/application-connector/08-12-get-subscribed-events.md
  docs/application-connector/09-01-connector-service.md
  docs/application-connector/09-02-metadata-service.md
  docs/application-connector/09-03-event-service.md
Labels: area/application-connector, area/documentation

#6442 Disable all Console tests (temp fix)
  resources/core/charts/console-backend-service/values.yaml
  resources/core/charts/console/values.yaml
Labels: area/console

#6356 Fix applications/runtimes choosers in create scenario modal
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, bug

#6449 Enable test coverage in generic makefile
  common/makefiles/docs/generic-make-go.md
  common/makefiles/generic-make-go.mk
Labels: area/quality

#6459 Fix a dead link
  docs/service-catalog/15-04-specifications-in-console-ui.md
Labels: area/documentation

#6455 Fix configuration for publish service metrics
  resources/event-bus/charts/event-publish-service/templates/destination-rule.yaml
  resources/event-bus/charts/event-publish-service/templates/metrics-service.yaml
  resources/event-bus/charts/event-publish-service/templates/policy.yaml
  resources/event-bus/charts/event-publish-service/templates/service-monitor.yaml
Labels: area/eventing

#6467 Release Kyma 1.8.0
  installation/resources/installer-local.yaml
  installation/resources/installer.yaml
Labels: area/community
