Repository kyma-project/kyma, pull requests merged in 2019-06, with the labels that each got.

#4346 Removed hard coded ClusterChannelProvisioner in channel spec
  components/event-bus/internal/knative/util/kn-eventing.go
  components/event-bus/internal/knative/util/kn-eventing_test.go
Labels: area/eventing

#4339 fix MinIO gateway GCS mode 403 response
  resources/assetstore/values.yaml
Labels: area/core-and-supporting, bug, test-failing

#4320 Add troubleshooting guide for Kyma installation
  docs/kyma/04-04-use-your-own-domain.md
  docs/kyma/04-05-use-your-own-image.md
  docs/kyma/14-01-overview.md
  docs/kyma/14-02-basic-troubleshooting.md
  docs/kyma/14-03-network-error.md
  docs/kyma/14-04-common-errors.md
  docs/kyma/14-05-transport-closing.md
  docs/kyma/14-06-unable-create-helm.md
Labels: area/documentation, area/installation

#4363 Fix error in processing docs in website
  docs/kyma/14-05-transport-closing.md
Labels: area/community, area/core-and-supporting, area/documentation

#4372 Fix links in troubleshooting
  docs/kyma/14-05-transport-closing.md
  docs/kyma/14-06-unable-create-helm.md
Labels: area/documentation, bug

#4355 Add troubleshooting guide for Service Mesh
  docs/service-mesh/14-01-overview.md
  docs/service-mesh/14-02-no-access.md
  docs/service-mesh/14-03-connection-refused.md
Labels: area/documentation, area/service-mesh

#4354 Add configuration documents for the Event Bus component
  docs/README.md
  docs/event-bus/02-01-event-bus.md
  docs/event-bus/05-01-event-bus.md
  docs/event-bus/05-02-nats-streaming.md
  docs/kyma/05-01-overview.md
Labels: area/documentation, area/eventing

#4379 Add the Headless CMS component
  docs/README.md
Labels: area/core-and-supporting, area/documentation

#4378 Simplify access to exposed APIs
  resources/core/charts/console/values.yaml
Labels: area/console, enhancement, quality/devx

#4280 Connectivity Certs Controller can handle secrets in different namespaces
  components/connectivity-certs-controller/cmd/connectivitycertscontroller/connectivitycertscontroller.go
  components/connectivity-certs-controller/cmd/connectivitycertscontroller/options.go
  components/connectivity-certs-controller/cmd/connectivitycertscontroller/options_test.go
  components/connectivity-certs-controller/internal/certificates/preserver.go
  components/connectivity-certs-controller/internal/certificates/preserver_test.go
  components/connectivity-certs-controller/internal/certificates/provider.go
  components/connectivity-certs-controller/internal/certificates/provider_test.go
  components/connectivity-certs-controller/internal/secrets/mocks/Repository.go
  components/connectivity-certs-controller/internal/secrets/repository.go
  components/connectivity-certs-controller/internal/secrets/repository_test.go
Labels: area/application-connector, enhancement

#4220 Add Application Connector Tests
  CODEOWNERS
  tests/application-connector-tests/Dockerfile
  tests/application-connector-tests/Gopkg.lock
  tests/application-connector-tests/Gopkg.toml
  tests/application-connector-tests/Makefile
  tests/application-connector-tests/README.md
  tests/application-connector-tests/before-commit.sh
  tests/application-connector-tests/scripts/entrypoint.sh
  tests/application-connector-tests/test/applicationaccess/suite.go
  tests/application-connector-tests/test/applicationaccess/tests/application_access_test.go
  tests/application-connector-tests/test/testkit/config.go
  tests/application-connector-tests/test/testkit/connector/client.go
  tests/application-connector-tests/test/testkit/connector/model.go
  tests/application-connector-tests/test/testkit/mtls.go
  tests/application-connector-tests/test/testkit/services/client.go
  tests/application-connector-tests/test/testkit/services/errors.go
  tests/application-connector-tests/test/testkit/services/model.go
  tests/application-connector-tests/test/testkit/util/util.go
  tests/application-connector-tests/test/testkit/wait.go
Labels: area/application-connector, enhancement

#4200 Connector service moved to Istio 1.1
  components/connector-service/Gopkg.lock
  components/connector-service/README.md
  components/connector-service/cmd/connectorservice/handlers.go
  components/connector-service/cmd/connectorservice/options.go
  components/connector-service/cmd/connectorservice/options_test.go
  components/connector-service/internal/certificates/certificates_test.go
  components/connector-service/internal/certificates/hash.go
  components/connector-service/internal/certificates/hash_test.go
  components/connector-service/internal/certificates/headerparser.go
  components/connector-service/internal/certificates/headerparser_test.go
  components/connector-service/internal/certificates/mocks/CertificateUtility.go
  components/connector-service/internal/certificates/mocks/HeaderParser.go
  components/connector-service/internal/certificates/mocks/Service.go
  components/connector-service/internal/certificates/service.go
  components/connector-service/internal/certificates/service_test.go
  components/connector-service/internal/certificates/subject.go
  components/connector-service/internal/clientcontext/extractor.go
  components/connector-service/internal/clientcontext/middlewares/contextfromsubject.go
  components/connector-service/internal/clientcontext/middlewares/contextfromsubject_test.go
  components/connector-service/internal/clientcontext/model.go
  components/connector-service/internal/externalapi/externalapi.go
  components/connector-service/internal/externalapi/revocationhandler.go
  components/connector-service/internal/externalapi/revocationhandler_test.go
  components/connector-service/internal/revocation/middlewares/revocationcheck.go
  components/connector-service/internal/revocation/middlewares/revocationcheck_test.go
  components/connector-service/internal/secrets/mocks/Manager.go
  components/connector-service/internal/secrets/mocks/Repository.go
  components/connector-service/internal/secrets/repository.go
  components/connector-service/internal/secrets/repository_test.go
Labels: area/application-connector, enhancement

#4203 Cleanup of Connector Service tests
  tests/connector-service-tests/Gopkg.lock
  tests/connector-service-tests/test/apitests/certificatevalidation_test.go
  tests/connector-service-tests/test/apitests/connector_test.go
  tests/connector-service-tests/test/testkit/connectorclient.go
  tests/connector-service-tests/test/testkit/k8sClient.go
  tests/connector-service-tests/test/testkit/securedconnectorclient.go
Labels: area/application-connector, enhancement

#4205 Replace nginx with istio
  installation/resources/installer-config-local.yaml.tpl
  resources/application-connector/charts/application-operator/templates/controller.yaml
  resources/application-connector/charts/application-operator/templates/tests/rbac.yaml
  resources/application-connector/charts/connectivity-certs-controller/README.md
  resources/application-connector/charts/connectivity-certs-controller/templates/deployment.yaml
  resources/application-connector/charts/connectivity-certs-controller/templates/role-binding.yaml
  resources/application-connector/charts/connectivity-certs-controller/values.yaml
  resources/application-connector/charts/connector-service/README.md
  resources/application-connector/charts/connector-service/templates/deployment.yaml
  resources/application-connector/charts/connector-service/templates/ingress.yaml
  resources/application-connector/charts/connector-service/templates/role-binding.yaml
  resources/application-connector/charts/connector-service/templates/tests/test-acceptance.yaml
  resources/application-connector/charts/connector-service/templates/virtualservice-mtls.yaml
  resources/application-connector/charts/connector-service/templates/virtualservice.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/templates/app-ca-crt-secret.yaml
  resources/application-connector/templates/ca-crt-istio-secret.yaml
  resources/application-connector/templates/tests/rbac.yaml
  resources/application-connector/templates/tests/test-acceptance.yaml
  resources/application-connector/values.yaml
  resources/core/charts/gateway/templates/gateway.yaml
  resources/istio/charts/gateways/values.yaml
Labels: area/application-connector, enhancement

#4246 Istio migration docs
  components/application-registry/README.md
  docs/application-connector/02-01-application-connector.md
  docs/application-connector/03-06-api-registration.md
  docs/application-connector/03-06-payload-limits-for-apis.md
  docs/application-connector/08-02-get-client-certificate.md
  docs/application-connector/08-03-register-manage-services.md
  docs/application-connector/08-05-trigger-lambda-with-event.md
  docs/application-connector/08-10-rotate-root-ca.md
  docs/application-connector/09-02-metadata-service.md
  docs/application-connector/09-03-event-service.md
  docs/application-connector/assets/001-application-connector.svg
  docs/kyma/04-04-use-your-own-domain.md
Labels: area/application-connector, area/documentation, enhancement

#4336 Cleanup of cluster-config.yaml.tpl
  docs/kyma/04-03-cluster-installation.md
  docs/kyma/04-04-use-your-own-domain.md
  docs/kyma/05-01-overview.md
  docs/kyma/05-02-custom-component-installation.md
  docs/service-catalog/03-04-experimental-features.md
  installation/resources/installer-config-cluster.yaml.tpl
  installation/scripts/release-generate-kyma-installer-artifacts.sh
  resources/monitoring/charts/alertmanager/README.md
Labels: area/documentation, area/installation

#4153 Add configurable SpecRequestTimeout parameter to Application Registry
  components/application-registry/README.md
  components/application-registry/cmd/applicationregistry/handlers.go
  components/application-registry/cmd/applicationregistry/options.go
  components/application-registry/internal/metadata/specification/assetstore/service.go
  components/application-registry/internal/metadata/specification/assetstore/service_test.go
  components/application-registry/internal/metadata/specification/service.go
  components/application-registry/internal/metadata/specification/service_test.go
Labels: area/application-connector, area/documentation, enhancement

#4397 Add information about Istio mTLS to Service Mesh docs.
  docs/service-mesh/01-01-service-mesh.md
  docs/service-mesh/03-02-istio-patch.md
Labels: area/documentation, area/service-mesh

#4007 Fix bugged event type example in docs
  docs/application-connector/08-05-trigger-lambda-with-event.md
  docs/application-connector/assets/eventsapi.yaml
Labels: area/application-connector, area/documentation, bug

#4384 Update event-service version
  resources/application-connector/values.yaml
Labels: area/eventing, enhancement

#4331 Fix version and deprovision logic in Helm Broker
  components/helm-broker/Gopkg.lock
  components/helm-broker/Gopkg.toml
  components/helm-broker/internal/broker/broker.go
  components/helm-broker/internal/broker/deprovision.go
  components/helm-broker/internal/broker/deprovision_test.go
  components/helm-broker/internal/broker/provision.go
  components/helm-broker/internal/storage/driver/etcd/entity_chart.go
  components/helm-broker/internal/storage/driver/memory/entity_chart.go
  docs/helm-broker/03-05-bundles-validation.md
Labels: area/service-catalog, bug

#4405 Add documentation to use google pubsub as default messaging middlewar…
  docs/event-bus/08-01-configure-default-channelprovisioner.md
  docs/event-bus/assets/gcppubsub.yaml
Labels: area/documentation

#4366 Update minIO image version
  docs/asset-store/08-01-gateway-mode-set-up.md
  resources/assetstore/values.yaml
Labels: area/core-and-supporting, area/documentation, enhancement

#4237 Improve Asset Store performance #3831
  components/asset-store-controller-manager/README.md
  components/asset-store-controller-manager/pkg/controller/asset/asset_controller.go
  components/asset-store-controller-manager/pkg/controller/asset/asset_controller_suite_test.go
  components/asset-store-controller-manager/pkg/controller/asset/config.go
  components/asset-store-controller-manager/pkg/controller/bucket/bucket_controller.go
  components/asset-store-controller-manager/pkg/controller/clusterasset/clusterasset_controller.go
  components/asset-store-controller-manager/pkg/controller/clusterasset/clusterasset_controller_suite_test.go
  components/asset-store-controller-manager/pkg/controller/clusterasset/config.go
  components/asset-store-controller-manager/pkg/controller/clusterbucket/clusterbucket_controller.go
  components/asset-store-controller-manager/pkg/path/file.go
  components/asset-store-controller-manager/pkg/store/store.go
  components/asset-store-controller-manager/pkg/store/store_test.go
  docs/asset-store/05-03-asset-store-controller-manager.md
  installation/resources/installer-config-local.yaml.tpl
  resources/assetstore/charts/asset-store-controller-manager/templates/statefulset.yaml
  resources/assetstore/charts/asset-store-controller-manager/values.yaml
  resources/assetstore/values.yaml
Labels: area/core-and-supporting, area/documentation, enhancement

#4403 Add a doc on installing Kyma through GCP Marketplace
  docs/kyma/04-03-cluster-installation.md
Labels: area/core-and-supporting, area/documentation, area/installation

#4413 Fix DocsTopic test after change in testing bundle
  tests/console-backend-service/before-commit.sh
  tests/console-backend-service/internal/domain/servicecatalog/clusterserviceclass_test.go
  tests/console-backend-service/internal/domain/servicecatalog/servicecatalog_test.go
Labels: WIP, area/service-catalog

#4422 Correct installation doc formatting
  docs/kyma/04-03-cluster-installation.md
Labels: area/documentation, area/installation

#4414 Bump console backend service tests version
  installation/scripts/testing-common.sh
  resources/core/values.yaml
  resources/helm-broker/templates/cfg-repos-url.yaml
Labels: area/service-catalog

#4416 Fix crashing lambdas view
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
Labels: area/console, bug

#4154 Bump Application Registry and add timeout flags
  resources/application-connector/charts/application-registry/README.md
  resources/application-connector/charts/application-registry/templates/deployment.yaml
  resources/application-connector/charts/application-registry/values.yaml
  resources/application-connector/values.yaml
Labels: WIP, area/application-connector, area/documentation, enhancement

#4383 Remove env=true label and treat all namespaces the same
  components/namespace-controller/README.md
  resources/cluster-essentials/templates/environments.yaml
  resources/core/charts/console/values.yaml
  resources/core/charts/namespace-controller/.helmignore
  resources/core/charts/namespace-controller/Chart.yaml
  resources/core/charts/namespace-controller/README.md
  resources/core/charts/namespace-controller/templates/0-service-account.yaml
  resources/core/charts/namespace-controller/templates/1-role.yaml
  resources/core/charts/namespace-controller/templates/2-role-binding.yaml
  resources/core/charts/namespace-controller/templates/4-deployment.yaml
  resources/core/charts/namespace-controller/templates/_helpers.tpl
  resources/core/charts/namespace-controller/templates/tests/test-namespace-controller.yaml
  resources/core/charts/namespace-controller/values.yaml
  resources/core/values.yaml
  tests/end-to-end/backup-restore-test/deploy/chart/backup-test/values.yaml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
Labels: area/console, enhancement

#4392 Update the path to point to 1.2.0 release
  docs/migration-guides/1.1-1.2.md
Labels: area/eventing

#4411 Validate API against blacklisted services
  components/api-controller/cmd/controller/main.go
  components/api-controller/cmd/controller/main_test.go
  components/api-controller/pkg/controller/v1alpha2/controller.go
  components/api-controller/pkg/controller/v1alpha2/controller_test.go
Labels: area/service-mesh, enhancement

#4362 Add business metrics to service binding usage component
  components/service-binding-usage-controller/Gopkg.lock
  components/service-binding-usage-controller/cmd/controller/main.go
  components/service-binding-usage-controller/internal/controller/automock/business_metric.go
  components/service-binding-usage-controller/internal/controller/automock/extends.go
  components/service-binding-usage-controller/internal/controller/controller.go
  components/service-binding-usage-controller/internal/controller/controller_test.go
  components/service-binding-usage-controller/internal/controller/metric/controller_business.go
  components/service-binding-usage-controller/internal/controller/usagekind/controller.go
  components/service-binding-usage-controller/internal/controller/usagekind/controller_test.go
Labels: area/service-catalog, enhancement

#4420 improve apiserver-proxy tests resilience
  tests/apiserver-proxy-tests/Gopkg.lock
  tests/apiserver-proxy-tests/Gopkg.toml
  tests/apiserver-proxy-tests/fetch-token/internal/auth.go
  tests/apiserver-proxy-tests/fetch-token/internal/config.go
  tests/apiserver-proxy-tests/fetch-token/internal/idtokenprovider.go
Labels: quality/testability

#4425 Add graphs to ServiceBindingUsage business metrics [do not merge]
  resources/monitoring/charts/grafana/dashboards/service-binding-usage-controller-dashboard.json
  resources/service-catalog-addons/values.yaml
Labels: area/service-catalog, enhancement

#4395 Delete unrelevant ns docu and rename files accordingly
  docs/application-connector/01-01-application-connector.md
  docs/kyma/03-02-namespaces.md
  docs/kyma/03-02-testing.md
  docs/kyma/03-03-charts.md
  docs/kyma/03-04-deploy-private-registry.md
Labels: area/documentation

#4417 Api-controller image bump
  resources/core/values.yaml
Labels: area/service-mesh, enhancement

#4427 improve apiserver-proxy-tests resilience image bump
  resources/core/values.yaml
Labels: quality/testability

#4216 Update Helm Broker docs
  docs/helm-broker/03-01-create-bundles.md
  docs/helm-broker/03-04-bundles-docs.md
Labels: area/documentation

#4453 Update config docs and the instruction on Kyma installation from the GCP Marketplace
  docs/kyma/04-03-cluster-installation.md
  docs/kyma/05-01-overview.md
Labels: area/documentation, area/installation

#4484 Api controller blacklisted svc 2
  components/api-controller/README.md
  components/api-controller/pkg/controller/v1alpha2/controller.go
  components/api-controller/pkg/controller/v1alpha2/controller_test.go
Labels: area/service-mesh, enhancement

#4495 Note fix and numbering change
  docs/event-bus/03-06-configure-default-channelprovisioner.md
Labels: area/documentation

#4499 Typo fix
  docs/event-bus/03-06-configure-default-channelprovisioner.md
Labels: area/documentation

#4117 Updating Kyma local installation documents with Kyma CLI
  docs/kyma/04-02-local-installation.md
  docs/kyma/04-07-local-installation-deprecated.md
  docs/kyma/04-11-local-reinstallation.md
  docs/kyma/04-12-local-installation-scripts.md
  docs/kyma/04-13-local-reinstallation-deprecated.md
  installation/cmd/run.ps1
  installation/cmd/run.sh
  installation/scripts/build-kyma-installer.ps1
  installation/scripts/build-kyma-installer.sh
  installation/scripts/clean-up.ps1
  installation/scripts/clean-up.sh
  installation/scripts/configure-components.ps1
  installation/scripts/configure-components.sh
  installation/scripts/install-tiller.ps1
  installation/scripts/install-tiller.sh
  installation/scripts/installer.ps1
  installation/scripts/installer.sh
  installation/scripts/minikube.ps1
  installation/scripts/minikube.sh
Labels: area/ci, area/documentation, area/installation, enhancement

#4436 Fix and improve metrics for ServiceCatalog
  docs/service-catalog/03-04-experimental-features.md
  installation/resources/installer-config-local.yaml.tpl
  resources/monitoring/charts/grafana/dashboards/service-catalog/service-catalog-apiserver.json
  resources/monitoring/charts/grafana/dashboards/service-catalog/service-catalog-crds.json
  resources/monitoring/charts/grafana/templates/dashboards-configmap.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/monitoring/values.yaml
  resources/service-catalog/charts/catalog-crds/templates/metrics.yaml
  resources/service-catalog/charts/catalog/templates/metrics.yaml
  resources/service-catalog/requirements.yaml
  resources/service-catalog/values.yaml
Labels: area/monitoring, area/service-catalog

#4348 Remove secret data from Entry API in Application Operator package
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/types.go
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/zz_generated.deepcopy.go
Labels: area/application-connector

#4341 Store additional headers and query parameters in the secret
  components/application-gateway/Gopkg.lock
  components/application-gateway/Gopkg.toml
  components/application-gateway/internal/metadata/applications/repository.go
  components/application-gateway/internal/metadata/model/model.go
  components/application-gateway/internal/metadata/serviceapi/serviceapiservice.go
  components/application-gateway/internal/metadata/serviceapi/serviceapiservice_test.go
  components/application-gateway/internal/proxy/proxy.go
  components/application-gateway/internal/proxy/proxy_test.go
  components/application-gateway/internal/proxy/proxyfactory.go
  components/application-gateway/internal/proxy/unauthorizedresponseretrier_test.go
  components/application-registry/Gopkg.lock
  components/application-registry/Gopkg.toml
  components/application-registry/cmd/applicationregistry/handlers.go
  components/application-registry/internal/externalapi/model.go
  components/application-registry/internal/metadata/applications/repository.go
  components/application-registry/internal/metadata/applications/util.go
  components/application-registry/internal/metadata/model/model.go
  components/application-registry/internal/metadata/secrets/mocks/Repository.go
  components/application-registry/internal/metadata/secrets/mocks/RequestParametersService.go
  components/application-registry/internal/metadata/secrets/repository.go
  components/application-registry/internal/metadata/secrets/repository_test.go
  components/application-registry/internal/metadata/secrets/requestParametersService.go
  components/application-registry/internal/metadata/secrets/requestParametersService_test.go
  components/application-registry/internal/metadata/secrets/service.go
  components/application-registry/internal/metadata/secrets/service_test.go
  components/application-registry/internal/metadata/serviceapi/serviceapiservice.go
  components/application-registry/internal/metadata/serviceapi/serviceapiservice_test.go
  docs/application-connector/08-03-register-manage-services.md
  docs/application-connector/08-04-register-secured-api.md
  tests/application-gateway-tests/test/executor/proxy/mock/headershandler.go
  tests/application-gateway-tests/test/executor/proxy/mock/queryparamshandler.go
  tests/application-gateway-tests/test/executor/testkit/registry/model.go
Labels: area/application-connector

#4512 Update api-controller-acceptance-test
  tests/api-controller-acceptance-tests/apicontroller/component_test.go
Labels: area/service-mesh, enhancement

#4517 Fix asset store bucket migration
  resources/assetstore/templates/_helper_migrate_buckets.txt
Labels: area/core-and-supporting, bug, priority/critical

#4505 Update ApplicationMapping documentation
  docs/application-connector/06-02-apllicationmapping.md
Labels: area/application-connector, area/documentation

#4401 List all namespaces
  components/console-backend-service/internal/domain/k8s/namespace_service.go
  components/console-backend-service/internal/domain/k8s/namespace_service_test.go
Labels: area/console, enhancement

#4511 Config docs application connector
  docs/application-connector/05-01-application-operator.md
  docs/application-connector/05-02-application-registry.md
  docs/application-connector/05-03-connectivity-certs-controller.md
  docs/application-connector/05-04-connector-service.md
Labels: area/application-connector, area/documentation

#4545 Change assetstore migrator job pvc access mode to ReadWriteOnce
  resources/assetstore/templates/migrator-job.yaml
Labels: area/core-and-supporting, bug

#4490 api-controller bump & api-controller-acceptance-tests bump
  resources/core/charts/api-controller/templates/deployment.yaml
  resources/core/charts/api-controller/values.yaml
  resources/core/values.yaml
Labels: area/service-mesh, enhancement

#4423 Bump images of Application Registry, Operator and Gateway
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#4547 Configure XS lambda size with 1 replica
  resources/core/charts/kubeless/charts/lambdas-ui/templates/configmap.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
Labels: area/console, enhancement

#4539 Add configuration documents for Monitoring
  docs/monitoring/05-01-alertmanager.md
  docs/monitoring/05-02-grafana.md
  docs/monitoring/05-03-prometheus.md
Labels: area/documentation, area/monitoring, quality/content

#4557 Api-controller blacklisted services docu
  components/api-controller/README.md
  docs/api-gateway/03-02-blacklisted-services.md
  docs/api-gateway/06-01-api.md
Labels: area/documentation, area/service-mesh

#4564 Fix default jwksuri when exposing secured lambda
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
Labels: area/console, bug

#4541 Add a configuration document for the Tracing component
  docs/tracing/05-01-jaeger.md
Labels: area/documentation, area/tracing, quality/content

#4454 Add find query and delete mutation for namespace
  components/console-backend-service/internal/domain/k8s/automock/gql_namespace_converter.go
  components/console-backend-service/internal/domain/k8s/automock/namespace_svc.go
  components/console-backend-service/internal/domain/k8s/namespace_converter.go
  components/console-backend-service/internal/domain/k8s/namespace_converter_test.go
  components/console-backend-service/internal/domain/k8s/namespace_resolver.go
  components/console-backend-service/internal/domain/k8s/namespace_resolver_test.go
  components/console-backend-service/internal/domain/k8s/namespace_service.go
  components/console-backend-service/internal/domain/k8s/namespace_service_test.go
  components/console-backend-service/internal/domain/root_resolver.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
Labels: area/console, enhancement

#4562 Bump api-controller-test image version
  resources/core/values.yaml
Labels: bug, test-missing

#4572 API Gateway blacklist - add more info
  docs/api-gateway/03-02-blacklisted-services.md
Labels: area/documentation

#4567 Add information about mTLS to Service Mesh documentation (v2)
  docs/service-mesh/01-01-service-mesh.md
Labels: area/documentation

#4575 Remove resource names form Connectivity Certs Controller RBAC
  resources/application-connector/charts/connectivity-certs-controller/templates/role-binding.yaml
Labels: area/application-connector, bug, priority/critical

#4561 Fix ServiceCatalog backup tests
  tests/end-to-end/backup-restore-test/backupe2e/service-catalog/brokers_flow.go
  tests/end-to-end/backup-restore-test/restore_cluster_backup_test.go
Labels: area/service-catalog, bug, quality/testability

#4590 new component iam-kubeconfig-service
  CODEOWNERS
  components/iam-kubeconfig-service/.gitignore
  components/iam-kubeconfig-service/Dockerfile
  components/iam-kubeconfig-service/Gopkg.lock
  components/iam-kubeconfig-service/Gopkg.toml
  components/iam-kubeconfig-service/Makefile
  components/iam-kubeconfig-service/README.md
  components/iam-kubeconfig-service/before-commit.sh
  components/iam-kubeconfig-service/cmd/generator/main.go
  components/iam-kubeconfig-service/doc.go
  components/iam-kubeconfig-service/internal/authn/middleware.go
  components/iam-kubeconfig-service/internal/authn/middleware_test.go
  components/iam-kubeconfig-service/internal/authn/oidc.go
  components/iam-kubeconfig-service/pkg/kube_config/endpoints.go
  components/iam-kubeconfig-service/pkg/kube_config/endpoints_test.go
  components/iam-kubeconfig-service/pkg/kube_config/kube_config.go
Labels: area/security, enhancement

#4588 Rename static-users-generator
  CODEOWNERS
  components/dex-static-user-configurer/Dockerfile
  components/dex-static-user-configurer/Makefile
  components/dex-static-user-configurer/README.md
  components/dex-static-user-configurer/scripts/config_replace.sh
Labels: area/documentation

#4595 Service Mesh docu update
  docs/service-mesh/01-01-service-mesh.md
Labels: area/documentation

#4578 Fix velero chart
  resources/velero/templates/deployment.yaml
  tests/end-to-end/backup-restore-test/deploy/chart/backup-test/values.yaml
Labels: bug

#4543 Page Header with Delete Button on Namespace Details View
  resources/core/charts/console-backend-service/templates/cluster-role.yaml
  resources/core/charts/console/templates/deployment.yaml
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
Labels: area/console, enhancement

#4584 Improve description of SBU custom resource
  docs/service-catalog/06-01-service-binding-usage.md
Labels: area/documentation, area/service-catalog

#4338 Update console dependencies
  resources/core/charts/docs/charts/content-ui/Chart.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
  resources/core/values.yaml
Labels: area/console

#4533 Api-Gateway authentication control for paths
  components/api-controller/examples/cr-v1alpha2-auth-exclude-paths.yaml
  components/api-controller/pkg/apis/authentication.istio.io/v1alpha1/types.go
  components/api-controller/pkg/apis/authentication.istio.io/v1alpha1/zz_generated.deepcopy.go
  components/api-controller/pkg/apis/gateway.kyma-project.io/v1alpha2/types.go
  components/api-controller/pkg/apis/gateway.kyma-project.io/v1alpha2/types_test.go
  components/api-controller/pkg/apis/gateway.kyma-project.io/v1alpha2/zz_generated.deepcopy.go
  components/api-controller/pkg/controller/authentication/v2/authenticationv2.go
  components/api-controller/pkg/controller/authentication/v2/authenticationv2_test.go
  components/api-controller/pkg/controller/authentication/v2/interface.go
  components/api-controller/pkg/controller/v1alpha2/controller.go
  components/api-controller/pkg/controller/v1alpha2/crd.go
  docs/api-gateway/03-01-security.md
  docs/api-gateway/06-01-api.md
Labels: area/service-mesh

#4583 API-controller and tests image bump
  resources/core/values.yaml
Labels: area/service-mesh

#4559 Add support for metadata in Assets
  components/asset-store-controller-manager/config/crds/assetstore_v1alpha2_asset.yaml
  components/asset-store-controller-manager/config/crds/assetstore_v1alpha2_clusterasset.yaml
  components/asset-store-controller-manager/pkg/apis/assetstore/v1alpha2/asset_common_types.go
  components/asset-store-controller-manager/pkg/apis/assetstore/v1alpha2/zz_generated.deepcopy.go
  components/asset-store-controller-manager/pkg/controller/clusterasset/clusterasset_controller.go
  components/asset-store-controller-manager/pkg/store/store_test.go
Labels: area/core-and-supporting, enhancement

#4602 Add link to Troubleshooting
  docs/kyma/04-07-local-installation-deprecated.md
Labels: area/documentation

#4603 Fix broken links
  docs/tracing/02-01-tracing.md
  docs/tracing/03-03-http-headers.md
Labels: area/documentation, bug

#4573 Add support for metadata in CMS
  components/cms-controller-manager/Gopkg.lock
  components/cms-controller-manager/Gopkg.toml
  components/cms-controller-manager/config/crds/cms_v1alpha1_clusterdocstopic.yaml
  components/cms-controller-manager/config/crds/cms_v1alpha1_docstopic.yaml
  components/cms-controller-manager/hack/crds/assetstore_v1alpha2_asset.yaml
  components/cms-controller-manager/hack/crds/assetstore_v1alpha2_bucket.yaml
  components/cms-controller-manager/hack/crds/assetstore_v1alpha2_clusterasset.yaml
  components/cms-controller-manager/hack/crds/assetstore_v1alpha2_clusterbucket.yaml
  components/cms-controller-manager/pkg/apis/cms/v1alpha1/docstopic_common.go
  components/cms-controller-manager/pkg/apis/cms/v1alpha1/zz_generated.deepcopy.go
  components/cms-controller-manager/pkg/controller/clusterdocstopic/clusterdocstopic_controller_test.go
  components/cms-controller-manager/pkg/controller/docstopic/docstopic_controller_test.go
  components/cms-controller-manager/pkg/handler/docstopic/automock/asset_service.go
  components/cms-controller-manager/pkg/handler/docstopic/automock/bucket_service.go
  components/cms-controller-manager/pkg/handler/docstopic/docstopic.go
  components/cms-controller-manager/pkg/handler/docstopic/docstopic_test.go
  components/cms-controller-manager/pkg/webhookconfig/automock/asset_webhook_config_service.go
  components/cms-controller-manager/pkg/webhookconfig/automock/indexer.go
Labels: area/core-and-supporting, enhancement

#4599 Add configuration documentation for the Logging component
  docs/logging/03-02-configure-storage.md
  docs/logging/05-01-logging.md
Labels: area/documentation, area/logging, quality/content

#4556 Add configuration documentation for the Backup component
  docs/backup/03-01-backup-configuration.md
  docs/backup/05-01-velero.md
  milv.config.yaml
  resources/velero/values.yaml
  tests/end-to-end/backup-restore-test/README.md
Labels: area/documentation, quality/content

#4610 Update the Velero links
  milv.config.yaml
  tests/end-to-end/backup-restore-test/README.md
Labels: area/documentation

#4611 Correct code snippets in the backup docs
  docs/backup/03-02-create-backup.md
  docs/backup/03-03-restore-backup.md
Labels: area/documentation

#4585 Align event delivery with cloud events specification
  components/event-bus/cmd/event-bus-publish-knative/dockerBuild.sh
  components/event-bus/cmd/event-bus-publish-knative/handlers/publish.go
  components/event-bus/cmd/event-bus-subscription-controller-knative/dockerBuild.sh
  components/event-bus/internal/trace/tags.go
  docs/event-bus/03-03-service-programming-model.md
  tests/event-bus/e2e-tester/e2e-tester.go
Labels: area/eventing

#4552 Change root CA secret key expected by Connector Service and Connectivity Certs Controller
  components/connectivity-certs-controller/internal/certificates/csrprovider.go
  components/connectivity-certs-controller/internal/certificates/preserver.go
  components/connector-service/internal/certificates/service.go
  components/connector-service/internal/certificates/service_test.go
  components/connector-service/internal/secrets/mocks/Repository.go
  components/connector-service/internal/secrets/repository.go
  components/connector-service/internal/secrets/repository_test.go
Labels: area/application-connector, enhancement

#4554 Enable tracing for GraphQL server in console backend service
  components/console-backend-service/Dockerfile
  components/console-backend-service/Gopkg.lock
  components/console-backend-service/Gopkg.toml
  components/console-backend-service/docs/configuration.md
  components/console-backend-service/main.go
  components/console-backend-service/pkg/tracing/config.go
  components/console-backend-service/pkg/tracing/handler.go
  components/console-backend-service/pkg/tracing/tracer.go
  milv.config.yaml
  resources/core/charts/console-backend-service/templates/deployment.yaml
  resources/core/charts/console-backend-service/values.yaml
  resources/core/values.yaml
Labels: area/console, area/documentation, area/tracing, enhancement

#4616 Apiserver proxy test should use FQDN of configurations generator service
  tests/apiserver-proxy-tests/test.sh
Labels: area/security, enhancement

#4632 Add log streams only for newest lambda pod
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
  resources/logging/charts/log-ui/values.yaml
Labels: area/console, enhancement, quality/devx

#4617 Apiserver proxy test image bump
  resources/core/charts/apiserver-proxy/templates/tests/test-apiserver-proxy.yaml
  resources/core/values.yaml
Labels: area/security, enhancement

#4624 Bump new event-bus images
  resources/event-bus/values.yaml
Labels: area/eventing

#4642 bump installer image
  installation/resources/installer.yaml
  tools/kyma-installer/kyma.Dockerfile
Labels: area/documentation, area/installation, enhancement

#4600 rename configurations-generator to iam-kubeconfig-service
  CODEOWNERS
  docs/security/03-01-iam-kubeconfig-service.md
  installation/resources/installer-config-local.yaml.tpl
  milv.config.yaml
  resources/core/charts/apiserver-proxy/templates/tests/test-apiserver-proxy.yaml
  resources/core/charts/configurations-generator/Chart.yaml
  resources/core/charts/configurations-generator/values.yaml
  resources/core/charts/iam-kubeconfig-service/Chart.yaml
  resources/core/charts/iam-kubeconfig-service/README.md
  resources/core/charts/iam-kubeconfig-service/templates/deployment.yaml
  resources/core/charts/iam-kubeconfig-service/templates/service.yaml
  resources/core/charts/iam-kubeconfig-service/templates/virtual-service.yaml
  resources/core/charts/iam-kubeconfig-service/values.yaml
  resources/core/values.yaml
Labels: area/documentation, area/security, enhancement

#4629 Bump Connector Service and Connectivity Certs Controller images
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#4386 Create Gql mutations and subscriptions for apis
  components/console-backend-service/internal/domain/apicontroller/api_converter.go
  components/console-backend-service/internal/domain/apicontroller/api_converter_test.go
  components/console-backend-service/internal/domain/apicontroller/api_resolver.go
  components/console-backend-service/internal/domain/apicontroller/api_resolver_test.go
  components/console-backend-service/internal/domain/apicontroller/api_service.go
  components/console-backend-service/internal/domain/apicontroller/api_service_test.go
  components/console-backend-service/internal/domain/apicontroller/apicontroller.go
  components/console-backend-service/internal/domain/apicontroller/automock/api_conv.go
  components/console-backend-service/internal/domain/apicontroller/automock/api_lister.go
  components/console-backend-service/internal/domain/apicontroller/automock/api_svc.go
  components/console-backend-service/internal/domain/apicontroller/automock/export.go
  components/console-backend-service/internal/domain/apicontroller/dep.go
  components/console-backend-service/internal/domain/apicontroller/disabled/resolver.go
  components/console-backend-service/internal/domain/apicontroller/listener/api.go
  components/console-backend-service/internal/domain/apicontroller/listener/automock/export.go
  components/console-backend-service/internal/domain/apicontroller/listener/automock/gql_api_converter.go
  components/console-backend-service/internal/domain/root_resolver.go
  components/console-backend-service/internal/gqlschema/models_gen.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
  tests/console-backend-service/Gopkg.lock
  tests/console-backend-service/internal/domain/apicontroller/apis_test.go
Labels: area/console, enhancement

#4536 Add mutations and subscriptions for apis to CBS
  resources/core/charts/console-backend-service/templates/cluster-role.yaml
  resources/core/charts/console/templates/deployment.yaml
  resources/core/templates/tests/rbac-test-console-backend-service.yaml
  resources/core/values.yaml
Labels: area/console, enhancement

#4653 remove configurations-generator
  CODEOWNERS
  components/configurations-generator/.gitignore
  components/configurations-generator/Dockerfile
  components/configurations-generator/Gopkg.lock
  components/configurations-generator/Gopkg.toml
  components/configurations-generator/Makefile
  components/configurations-generator/README.md
  components/configurations-generator/before-commit.sh
  components/configurations-generator/cmd/generator/main.go
  components/configurations-generator/doc.go
  components/configurations-generator/internal/authn/middleware.go
  components/configurations-generator/internal/authn/middleware_test.go
  components/configurations-generator/internal/authn/oidc.go
  components/configurations-generator/pkg/kube_config/endpoints.go
  components/configurations-generator/pkg/kube_config/endpoints_test.go
  components/configurations-generator/pkg/kube_config/kube_config.go
Labels: area/documentation, area/security, enhancement

#4671 Improve component's README.md
  components/iam-kubeconfig-service/README.md
Labels: area/documentation

#4664 Add optional destination rule for Connector Service
  resources/application-connector/charts/connector-service/templates/destination-rule.yaml
  resources/application-connector/charts/connector-service/values.yaml
Labels: area/application-connector, enhancement

#4666 Fix trusting cert
  docs/kyma/14-03-network-error.md
Labels: area/documentation, bug

#4676 IAM Kubeconfig Service docu
  docs/security/03-04-tiller-tls.md
  docs/security/03-05-roles-in-kyma.md
  docs/security/05-02-iam-kubeconfig-service.md
Labels: area/documentation, area/security, enhancement

#4668 Fix ServiceBindingUsage Variable Prefix in Lambda UI
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
  resources/service-catalog-addons/charts/instances-ui/Chart.yaml
Labels: area/console, bug

#4641 Bind Service Classes from Applications selectively via Console UI
  resources/core/charts/console/values.yaml
Labels: area/console, enhancement

#4637 Add polling to log UI
  resources/logging/charts/log-ui/templates/deployment.yaml
  resources/logging/charts/log-ui/values.yaml
Labels: area/console, enhancement, quality/devx
