Repository kyma-project/kyma, pull requests merged in 2020-04, with the labels that each got.

#7852 Enable function-controller for minikube
  resources/function-controller/templates/daemonset-configmap.yaml
  resources/function-controller/templates/daemonset.yaml
Labels: area/serverless

#7874 Fix dead links
  components/event-bus/README.md
Labels: area/documentation

#7873 Update migration guide for 1.11
  docs/migration-guides/1.10-1.11.md
Labels: area/documentation

#7870 Further improve knative-eventing-kafka documentation
  docs/knative-eventing-mesh/08-01-configure-kafka-channel.md
  docs/knative-eventing-mesh/08-02-set-up-channel.md
Labels: area/documentation, area/eventing

#7868 Add Event Triggers panel in new lambdas view
  resources/core/charts/console/values.yaml
Labels: area/console, area/serverless, enhancement

#7838 Update Runtime provisioning documentation with custom component sourceURL info
  docs/compass/03-10-provisioner-details.md
  docs/compass/08-02-provisioner-provisioning-gardener.md
  docs/compass/08-04-provisioner-runtime-status.md
Labels: area/documentation, area/management-plane

#7864 Rafter display name
  docs/rafter/06-01-asset.md
  docs/rafter/06-02-assetgroup.md
  docs/rafter/06-04-clusterasset.md
  docs/rafter/06-05-clusterassetgroup.md
  docs/rafter/08-01-add-new-documentation-to-console.md
  resources/cluster-essentials/templates/rafter.assetgroups.crd.yaml
  resources/cluster-essentials/templates/rafter.assets.crd.yaml
  resources/cluster-essentials/templates/rafter.clusterassetgroups.crd.yaml
  resources/cluster-essentials/templates/rafter.clusterassets.crd.yaml
  resources/rafter/charts/controller-manager/templates/assetgroups.crd.yaml
  resources/rafter/charts/controller-manager/templates/assets.crd.yaml
  resources/rafter/charts/controller-manager/templates/clusterassetgroups.crd.yaml
  resources/rafter/charts/controller-manager/templates/clusterassets.crd.yaml
  resources/rafter/values.yaml
Labels: area/documentation, enhancement

#7863 Add Automatic Scenario Assignment integration tests to Compass Director
  resources/compass/charts/director/config.yaml
  resources/compass/templates/director-api-test.yaml
  resources/compass/templates/director-gateway-integration-test.yaml
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#7880 Fluent-bit exclude path works only when there is not space around comma
  resources/logging/charts/fluentbit/templates/_helpers.tpl
Labels: area/logging, bug

#7886 Roll back to gce-proxy:1.14 for Job sidecars
  resources/compass/charts/director/templates/tenant-loader-job.yaml
  resources/compass/templates/migrator-job.yaml
  resources/compass/templates/tenant-fetcher-job.yaml
Labels: area/management-plane, bug

#7884 Bump Connectivity Adapter image
  resources/compass/values.yaml
Labels: area/management-plane, test-failing

#7865 7507 Install service entry inside knative eventing kafka chart
  resources/knative-eventing-kafka/templates/_helpers.tpl
  resources/knative-eventing-kafka/templates/broker-secret.yaml
  resources/knative-eventing-kafka/templates/serviceentry.yaml
  resources/knative-eventing-kafka/values.yaml
Labels: area/eventing

#7890 Reflect the serviceentry required changes in the Helm chart values in documentation
  docs/knative-eventing-mesh/08-01-configure-kafka-channel.md
Labels: area/documentation, area/eventing

#7889 Add entries to the migration guide for 1.11
  docs/migration-guides/1.10-1.11.md
Labels: area/documentation

#7875 Kyma version for provisioning on demand from query parameters
  resources/compass/charts/kyma-environment-broker/templates/deployment.yaml
  resources/compass/charts/kyma-environment-broker/values.yaml
Labels: area/management-plane

#7892 Add no default scenario flag to compass
  resources/compass/charts/director/templates/deployment.yaml
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#7893 Add display name for asset
  components/console-backend-service/Gopkg.lock
  components/console-backend-service/Gopkg.toml
  components/console-backend-service/internal/domain/rafter/asset_converter.go
  components/console-backend-service/internal/domain/rafter/asset_converter_test.go
  components/console-backend-service/internal/domain/rafter/clusterasset_converter.go
  components/console-backend-service/internal/domain/rafter/clusterasset_converter_test.go
  components/console-backend-service/internal/gqlschema/asset.go
  components/console-backend-service/internal/gqlschema/clusterasset.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
Labels: area/documentation, enhancement

#7857 Add tutorial about binding a service to a Namespace
  docs/application-connector/08-05-service-mapping.md
  docs/application-connector/08-06-trigger-lambda-with-event.md
  docs/application-connector/08-07-call-registered-service-from-kyma.md
  docs/application-connector/08-08-application-mapping.md
  docs/application-connector/08-09-renew-client-cert.md
  docs/application-connector/08-10-revoke-cert.md
  docs/application-connector/08-11-rotate-root-ca.md
  docs/application-connector/08-12-get-api-specification.md
  docs/application-connector/08-13-get-subscribed-events.md
Labels: area/application-connector, area/documentation

#7906 Fix KEB compass chart bool value
  resources/compass/charts/kyma-environment-broker/templates/deployment.yaml
Labels: area/management-plane, bug

#7817 Add tutorial about trigger lambda with events
  docs/serverless-v2/08-03-bind-service-instance.md
  docs/serverless-v2/08-04-trigger-lambda-with-event.md
Labels: area/documentation, area/serverless

#7848 Upgrade & Integration logging test
  resources/logging/templates/tests/rbac.yaml
  resources/logging/values.yaml
  tests/end-to-end/upgrade/chart/upgrade/templates/rbac.yaml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
  tests/end-to-end/upgrade/main.go
  tests/end-to-end/upgrade/pkg/tests/logging/logging.go
  tests/end-to-end/upgrade/pkg/tests/logging/pkg/jwt/jwt.go
  tests/end-to-end/upgrade/pkg/tests/logging/pkg/logstream/logstream.go
  tests/integration/logging/Dockerfile
  tests/integration/logging/Gopkg.lock
  tests/integration/logging/pkg/jwt/jwt.go
  tests/integration/logging/pkg/logstream/logstream.go
  tests/integration/logging/test-logging.go
  tests/integration/logging/testCounterPod.yaml
Labels: area/logging

#7754 Use testcafe in ui tests
  resources/core/charts/console/templates/test/test.yaml
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
Labels: area/console, enhancement

#7881 Show bound namespaces for namespace admin
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
Labels: area/console, bug

#7776 Add production profile for logging
  docs/logging/05-01-logging.md
  docs/logging/05-02-production-profile.md
Labels: area/documentation, area/logging

#7895 Limit Runtime Agent connections
  components/compass-runtime-agent/README.md
  components/compass-runtime-agent/cmd/main.go
  components/compass-runtime-agent/cmd/options.go
  components/compass-runtime-agent/internal/certificates/model.go
  components/compass-runtime-agent/internal/compass/cache/connection_data_cache.go
  components/compass-runtime-agent/internal/compass/cache/connection_data_cache_test.go
  components/compass-runtime-agent/internal/compass/clients_provider.go
  components/compass-runtime-agent/internal/compass/clients_provider_test.go
  components/compass-runtime-agent/internal/compass/director/mocks/ProxyConfigurator.go
  components/compass-runtime-agent/internal/compass/director/proxy.go
  components/compass-runtime-agent/internal/compass/director/proxy_test.go
  components/compass-runtime-agent/internal/compass/mocks/ClientsProvider.go
  components/compass-runtime-agent/internal/compassconnection/connector.go
  components/compass-runtime-agent/internal/compassconnection/init.go
  components/compass-runtime-agent/internal/compassconnection/mocks/Connector.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/compassconnection/supervisor.go
  components/compass-runtime-agent/internal/graphql/client.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/mocks/Service.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/upload/mocks/Client.go
  components/compass-runtime-agent/internal/metrics/mocks/MetricsClientsetInterface.go
  components/compass-runtime-agent/internal/metrics/mocks/MetricsV1beta1Interface.go
  components/compass-runtime-agent/internal/metrics/mocks/NodeMetricsInterface.go
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/templates/director-proxy-service.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/management-plane, bug

#7931 Bump image of Compass Runtime Agent
  resources/compass-runtime-agent/values.yaml
Labels: area/management-plane, bug

#7924 Show bound namespaces to namespace admin
  resources/core/values.yaml
Labels: area/console, bug

#7925 Add migration guide for 1.11.1 patch
  docs/migration-guides/1.10-1.11.1.md
  docs/migration-guides/1.10-1.11.md
  milv.config.yaml
Labels: area/documentation

#7935 Fix broken links
  docs/security/05-05-production-profile.md
Labels: area/documentation

#7938 Add missing header in serverless v2 tutorial
  docs/serverless-v2/08-04-trigger-lambda-with-event.md
Labels: area/documentation, area/serverless

#7876 Added disableLegacyConnectivity description
  docs/application-connector/05-01-application-operator.md
  docs/compass/04-01-compass.md
Labels: area/application-connector, area/documentation

#7939 Run ui test concurrently
  resources/core/charts/console/templates/test/test.yaml
Labels: area/console

#7950 Make tenant fetcher delete tenants instead of marking them
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#7915 Add event processing details to eventing mesh documentation
  docs/knative-eventing-mesh/02-01-knative-eventing-mesh.md
  docs/knative-eventing-mesh/03-01-event-processing.md
Labels: area/documentation, area/eventing

#7923 Luigi bump
  resources/compass/charts/cockpit/templates/configmap.yaml
  resources/compass/charts/cockpit/values.yaml
  resources/core/charts/console/values.yaml
Labels: area/console, area/management-plane

#7835 add sub-routes for slack/victorops notification
  resources/monitoring/templates/kyma-additions/alertmanager.config.yaml
  resources/monitoring/values.yaml
Labels: area/monitoring

#7940 Update the Kyma environment broker image
  resources/compass/values.yaml
Labels: area/eventing, area/management-plane

#7967 Change numbering for migration guide
  docs/migration-guides/1.10-1.11.md
  milv.config.yaml
Labels: area/documentation

#7913 API definition name passed to ClusterAssetGroup
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/clusterassetgrouprepository.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/clusterassetgrouprepository_test.go
  components/compass-runtime-agent/internal/kyma/apiresources/rafter/service.go
  components/compass-runtime-agent/internal/kyma/service_test.go
  components/compass-runtime-agent/internal/kyma/util.go
  resources/compass-runtime-agent/values.yaml
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/Gopkg.toml
  tests/compass-runtime-agent/test/testkit/assertions/k8s_resource_checker.go
Labels: area/application-connector

#7968 Fix luigi version bump
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, area/management-plane

#7969 Configure startingDeadlineSeconds in Tenant Fetcher
  resources/compass/templates/tenant-fetcher-job.yaml
Labels: area/management-plane, bug

#7954 Update kubernetes/client-go
  components/apiserver-proxy/Gopkg.lock
  components/apiserver-proxy/Gopkg.toml
  resources/apiserver-proxy/values.yaml
Labels: area/security

#7944 Add the Console UI tab for the tutorial on triggering events
  docs/serverless-v2/01-01-serverless-v2.md
  docs/serverless-v2/08-01-create-lambda.md
  docs/serverless-v2/08-02-expose-lambda.md
  docs/serverless-v2/08-03-bind-service-instance.md
  docs/serverless-v2/08-04-trigger-lambda-with-event.md
Labels: area/documentation, area/serverless

#7984 Remove camelcase
  docs/knative-eventing-mesh/03-01-event-processing.md
Labels: area/documentation

#7929 Bump Kyma version and KEB version
  resources/compass/charts/kyma-environment-broker/values.yaml
Labels: area/eventing

#7962 Enhance logging test
  resources/logging/values.yaml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
  tests/end-to-end/upgrade/pkg/tests/logging/logging.go
  tests/end-to-end/upgrade/pkg/tests/logging/pkg/jwt/jwt.go
  tests/end-to-end/upgrade/pkg/tests/logging/pkg/logstream/logstream.go
  tests/integration/logging/pkg/jwt/jwt.go
  tests/integration/logging/pkg/logstream/logstream.go
  tests/integration/logging/test-logging.go
Labels: area/logging, test-failing

#7974 Create scenarios LD on get
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#7973 Fix rendering of async api v1 spec
  resources/compass/charts/cockpit/values.yaml
  resources/core/charts/console/values.yaml
Labels: area/management-plane, bug

#7990 Bump KEB to support /info/runtimes endpoint
  resources/compass/charts/kyma-environment-broker/templates/api-rule.yaml
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#7977 Add Compass Connector charts and bump image
  resources/compass/charts/connector/templates/deployment.yaml
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#7926 Hide system namespaces toggle for non-runtime-admin
  resources/core/charts/console/values.yaml
Labels: area/console, enhancement

#7996 Update Oathkeeper rules to allow port in host header
  resources/compass/charts/gateway/templates/oathkeeper-rules.yaml
Labels: area/management-plane, bug, priority/critical

#7997 Fix indent in api rule
  resources/compass/charts/kyma-environment-broker/templates/api-rule.yaml
Labels: priority/critical

#7994 Bump director image with scenario assignments runtime flows
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#7963 Fix KNative Triggers indexer in cbs
  components/console-backend-service/internal/domain/eventing/trigger/converter.go
  components/console-backend-service/internal/domain/eventing/trigger/converter_test.go
  components/console-backend-service/internal/domain/eventing/trigger/service.go
  resources/core/values.yaml
Labels: area/console, bug

#7904 Disable istio-ingressgateway service monitor
  resources/monitoring/templates/kyma-additions/istio-telemetry-prometheus-svc-monitor-patch.yaml
  resources/monitoring/values.yaml
Labels: area/monitoring, area/service-mesh, bug

#7899 Bump cbs image with displayName for Assets
  resources/core/charts/console/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
Labels: area/console, area/documentation, enhancement

#8005 Stabilize UI tests
  resources/core/values.yaml
Labels: area/console, test-failing

#8003 Update Rafter images
  resources/rafter/values.yaml
Labels: area/core-and-supporting, enhancement

#8009 fixed minikube version for local installation to be 1.6.2
  docs/kyma/04-02-local-installation.md
Labels: area/documentation, area/installation

#7910 Troubleshooting guides cleanup
  docs/api-gateway-v2/10-02-connect-api-rule.md
  docs/kyma/10-04-common-errors.md
  docs/service-mesh/10-02-no-access.md
  docs/service-mesh/10-03-connection-refused.md
  docs/service-mesh/10-05-sidecar.md
Labels: area/documentation

#7941 Use httpbin instead of function in the API Gateway upgrade tests
  tests/end-to-end/upgrade/Gopkg.lock
  tests/end-to-end/upgrade/Gopkg.toml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
  tests/end-to-end/upgrade/pkg/tests/api-gateway/apigateway.go
Labels: area/security

#7972 Upgrade Fluent Bit
  resources/logging/charts/fluentbit/values.yaml
Labels: area/logging

#7986 API Server proxy image bump
  resources/apiserver-proxy/values.yaml
Labels: area/security

#8008 Bump api-gateway tests
  resources/api-gateway/templates/tests/test.yaml
  resources/api-gateway/values.yaml
Labels: area/security, test-failing

#8015 Configurable dex logger and changed default format to json
  resources/dex/templates/dex-config-map.yaml
  resources/dex/values.yaml
Labels: area/security

#8029 Route Director requests from Connectivity Adapter via Gateway
  resources/compass/charts/connectivity-adapter/templates/deployment.yaml
Labels: area/management-plane, enhancement

#7946 Extending monitoring integration test
  resources/monitoring/values.yaml
  tests/integration/monitoring/promAPI/rules.go
  tests/integration/monitoring/promAPI/targets.go
  tests/integration/monitoring/test-monitoring.go
Labels: area/monitoring, test-missing

#8044 Update istio
  components/istio-installer/Dockerfile
Labels: area/service-mesh

#8024 Fix overrides CM in KEB
  resources/compass/charts/kyma-environment-broker/templates/provisioning-runtime-overrides.yaml
Labels: bug, priority/critical

#8021 Randomize name for AddonsConfiguration
  tests/console-backend-service/internal/domain/servicecatalogaddons/addonsconfiguration_test.go
Labels: area/console

#7928 Update label map in fluent-bit
  resources/logging/charts/fluentbit/values.yaml
Labels: area/logging, area/serverless, enhancement

#8043 Adjust Serverless tests to the new Function CR
  installation/resources/installer-cr-azure-eventhubs.yaml.tpl
  installation/resources/installer-cr-cluster-runtime.yaml.tpl
  installation/resources/installer-cr-cluster-with-compass.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  resources/cluster-essentials/templates/functions.crd.yaml
  resources/function-controller/values.yaml
  tests/function-controller/go.mod
  tests/function-controller/go.sum
  tests/function-controller/main_test.go
  tests/function-controller/pkg/apirule/apirule.go
  tests/function-controller/pkg/namespace/namespace.go
  tests/function-controller/pkg/resource/resource.go
  tests/function-controller/pkg/retry/retry.go
  tests/function-controller/pkg/retry/retry_test.go
  tests/function-controller/pkg/shared/shared.go
  tests/function-controller/testsuite/function.go
  tests/function-controller/testsuite/testsuite.go
Labels: area/serverless, enhancement

#8051 Update maxReplicas in function CRD
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  resources/cluster-essentials/templates/functions.crd.yaml
Labels: area/serverless, enhancement

#8047 Show lambda build and execution logs in UI
  resources/core/charts/console/values.yaml
  resources/logging/values.yaml
Labels: area/console, area/serverless, enhancement

#8048 Bump randomized test name for Addons Configuration
  resources/core/values.yaml
Labels: area/console

#8039 api-migrator bump. Update README.md
  components/api-gateway-migrator/README.md
  milv.config.yaml
  resources/api-gateway/values.yaml
Labels: area/service-mesh

#8023 Update top level CODEOWNER
  CODEOWNERS
Labels: area/eventing

#8059 Tidy up documentation on connecting and reconnecting Runtime Agent with Compass
  docs/compass/03-20-runtime-agent-details.md
  docs/compass/08-10-runtime-agent-configuration.md
  docs/compass/08-11-runtime-agent-reconnecting.md
Labels: area/documentation, area/management-plane

#8045 Update istio
  resources/istio-kyma-patch/values.yaml
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: area/service-mesh

#8026 Update image for api-gateway tests
  tests/integration/api-gateway/Dockerfile
  tests/integration/api-gateway/gateway-tests/main_test.go
  tests/integration/api-gateway/gateway-tests/pkg/jwt/config.go
Labels: area/security

#8010 Move ingress-gateway DR to minikube env only
  resources/api-gateway/files/api-gateway-tests.sh
  resources/api-gateway/templates/tests/test.yaml
  resources/api-gateway/values.yaml
  resources/istio/files/destination-rules-minikube.yaml
  resources/istio/files/destination-rules.yaml
  resources/istio/templates/configmap-extra-manifests.yaml
  resources/istio/templates/job-migration-remove-dr.yaml
  resources/istio/templates/rbac-migration-remove-dr.yaml
Labels: area/security, area/service-mesh

#8073 Add minor article and formatting fixes
  docs/compass/03-20-runtime-agent-details.md
  docs/compass/08-10-runtime-agent-configuration.md
  docs/compass/08-11-runtime-agent-reconnecting.md
Labels: area/documentation, area/management-plane

#8035 Remove TaskRun and Tekton references from docs
  components/function-controller/README.md
  components/function-controller/internal/configwatcher/configwatcher.go
  docs/security/03-08-permission-controller.md
  docs/security/05-05-permission-controller.md
  docs/serverless-v2/01-01-serverless-v2.md
  docs/serverless-v2/02-01-serverless-v2.md
  docs/serverless-v2/03-01-api-rules.md
  docs/serverless-v2/06-01-function-cr.md
  docs/serverless-v2/assets/serverless-architecture.svg
  docs/serverless-v2/assets/serverless-v2-architecture.svg
  resources/function-controller/README.md
Labels: area/documentation, area/serverless

#8020 Update docs after Function Controller refactoring - NEW
  docs/rafter/06-01-asset.md
  docs/rafter/06-02-assetgroup.md
  docs/rafter/06-03-bucket.md
  docs/rafter/06-04-clusterasset.md
  docs/rafter/06-05-clusterassetgroup.md
  docs/rafter/06-06-clusterbucket.md
  docs/serverless-v2/02-01-serverless-v2.md
  docs/serverless-v2/03-03-lambda-processing.md
  docs/serverless-v2/06-01-function-cr.md
  docs/serverless-v2/08-01-create-lambda.md
  docs/serverless-v2/08-02-expose-lambda.md
  docs/serverless-v2/assets/built.svg
  docs/serverless-v2/assets/configured.svg
  docs/serverless-v2/assets/running.svg
Labels: area/documentation, area/serverless

#7844 Clean up old lambda UI view - kyma part
  resources/core/charts/kubeless/charts/lambdas-ui/templates/lambdas-microfrontend.yaml
  resources/function-controller/templates/cluster-microfrontend-functions.yaml
Labels: area/console, area/serverless

#8068 Rename the function-controller chart to the serverless
  CODEOWNERS
  components/function-controller/Makefile
  components/function-controller/README.md
  components/function-controller/internal/controllers/serverless/config.go
  docs/kyma/04-01-overview.md
  installation/resources/installer-cr-azure-eventhubs.yaml.tpl
  installation/resources/installer-cr-cluster-runtime.yaml.tpl
  installation/resources/installer-cr-cluster-with-compass.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  resources/serverless/.helmignore
  resources/serverless/Chart.yaml
  resources/serverless/README.md
  resources/serverless/charts/docker-registry/.helmignore
  resources/serverless/charts/docker-registry/Chart.yaml
  resources/serverless/charts/docker-registry/README.md
  resources/serverless/charts/docker-registry/templates/NOTES.txt
  resources/serverless/charts/docker-registry/templates/_helpers.tpl
  resources/serverless/charts/docker-registry/templates/configmap.yaml
  resources/serverless/charts/docker-registry/templates/deployment.yaml
  resources/serverless/charts/docker-registry/templates/ingress.yaml
  resources/serverless/charts/docker-registry/templates/poddisruptionbudget.yaml
  resources/serverless/charts/docker-registry/templates/pvc.yaml
  resources/serverless/charts/docker-registry/templates/secret.yaml
  resources/serverless/charts/docker-registry/templates/service.yaml
  resources/serverless/charts/docker-registry/values.yaml
  resources/serverless/requirements.yaml
  resources/serverless/templates/_helper_tests.txt
  resources/serverless/templates/_helpers.tpl
  resources/serverless/templates/apirule.yaml
  resources/serverless/templates/auth-proxy-role-binding.yaml
  resources/serverless/templates/auth-proxy-role.yaml
  resources/serverless/templates/auth-proxy-service.yaml
  resources/serverless/templates/backendmodule.yaml
  resources/serverless/templates/cluster-microfrontend-lambdas.yaml
  resources/serverless/templates/cluster-role-binding.yaml
  resources/serverless/templates/cluster-role.yaml
  resources/serverless/templates/daemonset-configmap.yaml
  resources/serverless/templates/daemonset.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/templates/destination-rule.yaml
  resources/serverless/templates/leader-election-role-binding.yaml
  resources/serverless/templates/leader-election-role.yaml
  resources/serverless/templates/runtimes.yaml
  resources/serverless/templates/secrets.yaml
  resources/serverless/templates/service-account.yaml
  resources/serverless/templates/service-monitor.yaml
  resources/serverless/templates/service.yaml
  resources/serverless/templates/tests/rbac.yaml
  resources/serverless/templates/tests/test.yaml
  resources/serverless/templates/usage-kind.yaml
  resources/serverless/values.yaml
  tests/function-controller/Makefile
  tests/function-controller/README.md
Labels: area/serverless

#8088 Rename lambdas to functions
  docs/serverless-v2/01-01-serverless-v2.md
  docs/serverless-v2/02-01-serverless-v2.md
  docs/serverless-v2/03-01-api-rules.md
  docs/serverless-v2/03-02-security.md
  docs/serverless-v2/03-03-function-processing.md
  docs/serverless-v2/03-03-lambda-processing.md
  docs/serverless-v2/06-01-function-cr.md
  docs/serverless-v2/08-01-create-function.md
  docs/serverless-v2/08-02-expose-function.md
  docs/serverless-v2/08-02-expose-lambda.md
  docs/serverless-v2/08-03-bind-service-instance.md
  docs/serverless-v2/08-04-trigger-function-with-event.md
  docs/serverless-v2/assets/built.svg
  docs/serverless-v2/assets/configured.svg
  docs/serverless-v2/assets/running.svg
  docs/serverless-v2/assets/serverless-architecture.svg
Labels: area/documentation

#8076 Remove Tekton leftovers
  CODEOWNERS
  resources/core/charts/console-backend-service/values.yaml
  resources/core/charts/console/values.yaml
  resources/permission-controller/values.yaml
  resources/serverless/Chart.yaml
  resources/serverless/templates/cluster-microfrontend-functions.yaml
  resources/serverless/templates/cluster-microfrontend-lambdas.yaml
  resources/serverless/templates/secrets.yaml
Labels: area/serverless

#8018 Refactor event-service informer
  components/event-service/internal/events/subscribed/events.go
Labels: area/eventing

#7966 update subscriber image
  tests/end-to-end/backup/chart/backup-test/values.yaml
  tests/end-to-end/backup/pkg/tests/eventmesh/subscriber.go
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
  tests/end-to-end/upgrade/pkg/tests/eventmesh/helpers/subscriber.go
Labels: area/eventing

#7961 Enable Istio authorization policy for the validator and the HTTP source adapter
  resources/application-connector/values.yaml
  tests/end-to-end/upgrade/chart/upgrade/templates/authorization-policy.yaml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
Labels: area/eventing, area/security

#8079 Adjust build resources
  installation/resources/installer-config-local.yaml.tpl
  installation/scripts/minikube.sh
  resources/knative-serving/values.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/templates/tests/rbac.yaml
  resources/serverless/templates/tests/test.yaml
  resources/serverless/values.yaml
Labels: area/serverless

#8054 Propagate flag global.enableCompassDefaultScenarioAssignment into UI …
  resources/compass/charts/cockpit/templates/configmap.yaml
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, area/management-plane, enhancement

#8104 Bump console image
  resources/core/charts/console/values.yaml
  resources/serverless/values.yaml
Labels: area/console, area/serverless, enhancement

#8119 Rename lambdas to functions and remove Kubeless references from docs
  components/application-gateway/README.md
  components/application-registry/README.md
  components/console-backend-service/docs/resource-quotas-status.md
  components/function-controller/README.md
  components/service-binding-usage-controller/examples/README.md
  docs/api-gateway-v2/08-01-exposesecure.md
  docs/application-connector/02-01-application-connector.md
  docs/application-connector/02-03-proxy-service.md
  docs/application-connector/02-04-application-broker.md
  docs/application-connector/03-08-application-gateway.md
  docs/application-connector/06-03-event-activation.md
  docs/application-connector/08-06-trigger-lambda-with-event.md
  docs/application-connector/08-07-call-registered-service-from-kyma.md
  docs/application-connector/assets/003-architecture-proxy-service.svg
  docs/application-connector/assets/005-AB-API-service-class.svg
  docs/application-connector/assets/006-AB-event-service-class.svg
  docs/compass/08-01-basic-flow-tutorial.md
  docs/console/03-02-console-backend-service.md
  docs/helm-broker/02-01-helm-broker.md
  docs/helm-broker/assets/hb-architecture.svg
  docs/knative-eventing-mesh/01-01-knative-eventing-mesh.md
  docs/knative-eventing-mesh/03-01-event-processing.md
  docs/knative-eventing-mesh/06-01-httpsource.md
  docs/knative-eventing-mesh/assets/eventing-mesh-flow.svg
  docs/kyma/01-01-in-a-nutshell.md
  docs/kyma/01-02-main-features.md
  docs/kyma/01-04-key-components.md
  docs/kyma/01-05-how-to-start.md
  docs/kyma/03-01-components.md
  docs/kyma/16-01-try-out-kyma.md
  docs/tracing/assets/request-traces.svg
  docs/tracing/assets/store-traces.svg
  resources/monitoring/charts/grafana/README.md
  tests/end-to-end/external-solution-integration/README.md
  tests/end-to-end/external-solution-integration/cmd/fakelambda/README.md
  tests/function-controller/README.md
Labels: area/documentation, area/serverless

#8063 Update CBS and CoreUI images
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
Labels: area/serverless, enhancement

#8121 Remove not used secret from knative serving
  resources/knative-serving/requirements.yaml
  resources/knative-serving/templates/serving.yaml
  resources/serverless/templates/secrets.yaml
Labels: area/serverless

#8128 Allow manual execution of Tenant Loader
  resources/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  resources/compass/charts/director/templates/tenant-loader-job-default.yaml
  resources/compass/templates/tenant-fetcher-job.yaml
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#8077 Add knative service controller to function-controller-manager
  components/function-controller/Makefile
  components/function-controller/cmd/manager/main.go
  components/function-controller/config/rbac/role.yaml
  components/function-controller/internal/controllers/knative/predicate.go
  components/function-controller/internal/controllers/knative/service_controller.go
  components/function-controller/internal/controllers/knative/service_controller_test.go
  components/function-controller/internal/controllers/knative/suite_test.go
  components/function-controller/internal/controllers/kubernetes/kubernetes_controller.go
  components/function-controller/internal/controllers/kubernetes/suite_test.go
  components/function-controller/internal/controllers/serverless/build_resources.go
  components/function-controller/internal/controllers/serverless/function_controller.go
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  components/function-controller/internal/controllers/serverless/suite_test.go
  components/function-controller/internal/resource/resource.go
  components/function-controller/internal/resource/resource_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  resources/serverless/templates/cluster-role.yaml
Labels: area/serverless, enhancement

#8118 Fix cbs error and add missing permission
  components/console-backend-service/internal/domain/application/app_service.go
  resources/core/charts/console-backend-service/templates/cluster-role.yaml
Labels: area/console, bug

#8115 Bump Provisioner and KEB
  resources/compass/values.yaml
Labels: area/management-plane

#8111 Extract cluster-users chart
  CODEOWNERS
  installation/resources/installer-cr-azure-eventhubs.yaml.tpl
  installation/resources/installer-cr-cluster-runtime.yaml.tpl
  installation/resources/installer-cr-cluster-with-compass.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  resources/cluster-users/Chart.yaml
  resources/cluster-users/OWNERS
  resources/cluster-users/README.md
  resources/cluster-users/templates/clusterroles-addons.yaml
  resources/cluster-users/templates/clusterroles-coreos-com.yaml
  resources/cluster-users/templates/clusterroles-istio-io.yaml
  resources/cluster-users/templates/clusterroles-k8s-io.yaml
  resources/cluster-users/templates/clusterroles-knative-eventing.yaml
  resources/cluster-users/templates/clusterroles-kyma-project-io.yaml
  resources/cluster-users/templates/clusterroles-ory-sh.yaml
  resources/cluster-users/templates/clusterroles-rafter.yaml
  resources/cluster-users/templates/clusterroles-velero-io.yaml
  resources/cluster-users/templates/rbac-roles.yaml
  resources/cluster-users/templates/tests/rbac.yaml
  resources/cluster-users/templates/tests/test.yaml
  resources/cluster-users/values.schema.json
  resources/cluster-users/values.yaml
  resources/core/charts/cluster-users/README.md
  resources/core/requirements.yaml
  resources/core/values.yaml
  resources/uaa-activator/values.yaml
Labels: area/security

#8136 Fix error messages in Console Backend Service
  resources/core/values.yaml
Labels: area/console, bug

#8138 Rename documentation back button
  resources/core/charts/docs/charts/content-ui/Chart.yaml
Labels: area/console

#8124 Update docs after cluster-users extraction
  docs/kyma/04-01-overview.md
  docs/security/03-05-roles-in-kyma.md
  docs/security/08-03-add-connector.md
Labels: area/documentation

#8137 Unify service brokers view in console
  resources/service-catalog-addons/charts/service-catalog-ui/values.yaml
Labels: area/console, enhancement

#8143 Remove a deprecated example
  docs/kyma/16-01-try-out-kyma.md
Labels: area/documentation, area/serverless

#8145 Improve UI tutorials for serverless
  docs/serverless/08-01-create-function.md
  docs/serverless/08-03-bind-service-instance.md
  docs/serverless/08-04-trigger-function-with-event.md
Labels: area/documentation, area/serverless

#8127 Update core-ui image
  resources/core/charts/console/values.yaml
Labels: area/console, area/serverless, enhancement

#8140 Fix flaky function-controller test
  components/function-controller/go.mod
  components/function-controller/go.sum
  components/function-controller/internal/controllers/knative/service_controller_test.go
  components/function-controller/internal/controllers/knative/suite_test.go
Labels: area/serverless, enhancement

#8148 Remove event bus mentions from docu
  docs/application-connector/01-01-application-connector.md
  docs/application-connector/02-01-application-connector.md
  docs/application-connector/02-04-application-broker.md
  docs/application-connector/06-03-event-activation.md
  docs/application-connector/assets/006-AB-event-service-class.svg
  docs/kyma/01-01-in-a-nutshell.md
  docs/kyma/01-05-how-to-start.md
  docs/kyma/03-01-components.md
Labels: area/documentation, area/eventing

#8158 Update serverless-controller-manager image
  resources/serverless/values.yaml
Labels: area/serverless, enhancement

#8165 Migration guide update
  docs/migration-guides/1.10-1.11.md
  docs/migration-guides/1.11-1.12.md
Labels: area/documentation

#8122 Add information about the default groups of Kyma roles
  docs/security/03-05-roles-in-kyma.md
Labels: area/documentation, area/security

#8161 Remove dependency to Rafter Config Map
  resources/core/charts/console-backend-service/templates/deployment.yaml
Labels: area/console, area/documentation, bug

#8134 fixed destinationrule for prometheus
  resources/monitoring/templates/kyma-additions/destination-rule.yaml
Labels: area/monitoring

#8164 Fix propagation of Serverless configuration
  components/function-controller/README.md
  resources/serverless/values.yaml
Labels: area/documentation, area/serverless, bug

#8141 Upgrade k8s dependencies in the external-solution-integration and crypto in the knative-serving tests
  resources/compass-runtime-agent/values.yaml
  resources/core/values.yaml
  resources/knative-serving/values.yaml
  tests/end-to-end/external-solution-integration/Gopkg.lock
  tests/end-to-end/external-solution-integration/Gopkg.toml
  tests/end-to-end/external-solution-integration/pkg/testsuite/create_legacy_service_instance.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/create_service_binding.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/create_service_instance.go
  tests/knative-serving/Gopkg.lock
  tests/knative-serving/Gopkg.toml
Labels: security/medium

#8052 External service configuration with HTTPS for fluent bit
  resources/logging/charts/fluentbit/templates/serviceentry.yaml
  resources/logging/charts/fluentbit/values.yaml
Labels: area/logging, area/service-mesh

#8167 Improve Kafka documentation
  docs/knative-eventing-mesh/08-01-configure-kafka-channel.md
  docs/knative-eventing-mesh/08-02-set-up-channel.md
Labels: area/documentation, area/eventing

#8153 Bump Director image
  resources/compass/values.yaml
Labels: area/management-plane, bug

#8170 Upgrade k8s.io packages in iam-kubeconfig-service
  components/iam-kubeconfig-service/Gopkg.lock
  components/iam-kubeconfig-service/Gopkg.toml
Labels: area/security, area/service-mesh, security/medium

#8169 Upgrade yaml.v2 version in APIServer proxy
  components/apiserver-proxy/Gopkg.toml
Labels: area/security, security/medium

#8171 Bump apiserver-proxy and iam-kubeconfig-service images
  resources/apiserver-proxy/values.yaml
  resources/iam-kubeconfig-service/values.yaml
Labels: area/security, area/service-mesh

#8177 Add info on requests and limits for functions
  docs/rafter/05-01-rafter.md
  docs/serverless/02-01-serverless.md
  docs/serverless/03-03-function-processing.md
  docs/serverless/05-01-serverless.md
Labels: area/documentation, area/serverless

#8166 Rename serverless deployment and serviceAccount
  resources/serverless/templates/auth-proxy-role-binding.yaml
  resources/serverless/templates/cluster-role-binding.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/templates/leader-election-role-binding.yaml
  resources/serverless/templates/service-account.yaml
  resources/serverless/templates/service.yaml
Labels: area/serverless

#8192 Bump Connectivity Adapter
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#8194 Fix a broken link
  docs/compass/05-01-provisioner-entry-parameteres.md
Labels: area/documentation, bug

#8201 update to grafana 6.7.3
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring

#8210 Upgrade Fluent Bit to 1.4.2
  resources/logging/charts/fluentbit/values.yaml
Labels: area/logging

#8152 Display runtime labels
  resources/compass/charts/cockpit/values.yaml
  resources/core/charts/console/values.yaml
Labels: area/console, area/management-plane, enhancement

#8215 Fix a broken link
  docs/compass/05-01-provisioner-entry-parameteres.md
Labels: area/documentation, bug

#8155 Set default domain name in API Gateway
  resources/api-gateway/templates/_helpers.tpl
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/values.yaml
Labels: area/service-mesh, enhancement

#8217 Fix API Definitions details view in Console
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#8219 Add Api > APIRule migration guide
  docs/api-gateway/03-04-migration.md
  docs/migration-guides/1.11-1.12.md
  milv.config.yaml
Labels: area/documentation

#8227 Configures monitoring with OIDC authentication
  resources/compass/charts/kyma-environment-broker/templates/deployment.yaml
  resources/compass/charts/kyma-environment-broker/templates/secrets.yaml
  resources/compass/charts/kyma-environment-broker/values.yaml
  resources/compass/values.yaml
Labels: area/management-plane

#8222 Upgrade the kube-rbac-proxy image
  resources/serverless/values.yaml
Labels: area/serverless

#8139 Update Provisioner chart with Runtime Upgrade
  resources/compass/charts/provisioner/templates/deployment.yaml
  resources/compass/charts/provisioner/values.yaml
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#8225 Add missed namespace arg to mutations in cbs
  components/console-backend-service/internal/domain/eventing/automock/resolver.go
  components/console-backend-service/internal/domain/eventing/disabled/resolver.go
  components/console-backend-service/internal/domain/eventing/eventing.go
  components/console-backend-service/internal/domain/eventing/eventing_test.go
  components/console-backend-service/internal/domain/eventing/trigger.go
  components/console-backend-service/internal/domain/eventing/trigger_test.go
  components/console-backend-service/internal/domain/root_resolver.go
  components/console-backend-service/internal/domain/serverless/disabled/resolver.go
  components/console-backend-service/internal/domain/serverless/function_resolver.go
  components/console-backend-service/internal/domain/serverless/function_resolver_test.go
  components/console-backend-service/internal/domain/serverless/serverless.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
Labels: area/console, area/serverless, bug, priority/critical

#8228 Disable istio authorization policy
  resources/application-connector/values.yaml
  tests/end-to-end/upgrade/chart/upgrade/templates/authorization-policy.yaml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
Labels: area/eventing

#8078 Add new backup strategy doc
  docs/backup/01-01-backup.md
  docs/backup/03-01-new-backup-strategy.md
  docs/backup/04-01-install-velero.md
  docs/backup/05-01-velero.md
  docs/backup/08-01-create-backup.md
  docs/backup/08-02-restore-backup.md
  docs/backup/10-01-restore-troubleshooting.md
Labels: area/documentation, area/quality

#8240 improved grafana configuration documentation
  docs/monitoring/05-02-grafana.md
Labels: area/monitoring

#8236 Fix OOM issue in Serverless
  components/function-controller/Makefile
  components/function-controller/README.md
  components/function-controller/cmd/manager/main.go
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/rbac/role.yaml
  components/function-controller/go.mod
  components/function-controller/internal/configwatcher/configwatcher.go
  components/function-controller/internal/configwatcher/configwatcher_test.go
  components/function-controller/internal/configwatcher/credentials_service.go
  components/function-controller/internal/configwatcher/credentials_service_test.go
  components/function-controller/internal/configwatcher/namespace_service.go
  components/function-controller/internal/configwatcher/namespaces_service_test.go
  components/function-controller/internal/configwatcher/runtimes_service.go
  components/function-controller/internal/configwatcher/runtimes_service_test.go
  components/function-controller/internal/configwatcher/service_account_service.go
  components/function-controller/internal/configwatcher/service_account_service_test.go
  components/function-controller/internal/controllers/knative/service_controller.go
  components/function-controller/internal/controllers/knative/service_controller_test.go
  components/function-controller/internal/controllers/knative/suite_test.go
  components/function-controller/internal/controllers/kubernetes/configmap_controller.go
  components/function-controller/internal/controllers/kubernetes/configmap_controller_test.go
  components/function-controller/internal/controllers/kubernetes/configmap_service.go
  components/function-controller/internal/controllers/kubernetes/handler.go
  components/function-controller/internal/controllers/kubernetes/kubernetes_controller.go
  components/function-controller/internal/controllers/kubernetes/kubernetes_controller_test.go
  components/function-controller/internal/controllers/kubernetes/namespace_controller.go
  components/function-controller/internal/controllers/kubernetes/namespace_controller_test.go
  components/function-controller/internal/controllers/kubernetes/secret_controller.go
  components/function-controller/internal/controllers/kubernetes/secret_controller_test.go
  components/function-controller/internal/controllers/kubernetes/secret_service.go
  components/function-controller/internal/controllers/kubernetes/serviceaccount_controller.go
  components/function-controller/internal/controllers/kubernetes/serviceaccount_controller_test.go
  components/function-controller/internal/controllers/kubernetes/serviceaccount_service.go
  components/function-controller/internal/controllers/kubernetes/shared.go
  components/function-controller/internal/controllers/kubernetes/suite_test.go
  components/function-controller/internal/controllers/kubernetes/utils_test.go
  components/function-controller/internal/controllers/serverless/function_controller.go
  components/function-controller/internal/controllers/serverless/function_controller_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  components/function-controller/internal/controllers/serverless/suite_test.go
  components/function-controller/internal/resource/automock/client.go
  components/function-controller/internal/resource/automock/k8s_client.go
  components/function-controller/internal/resource/resource.go
  components/function-controller/internal/resource/resource_test.go
Labels: area/documentation, area/serverless, bug, priority/critical

#8246 Disable pod monitor in knative-serving chart
  resources/knative-serving/templates/pod-monitor-ksvc.yaml
  resources/knative-serving/values.yaml
Labels: area/serverless, bug

#8184 Change dest of lambda/function dashboard
  resources/serverless/templates/backendmodule.yaml
  resources/serverless/templates/function-dashboard.yaml
  resources/serverless/values.yaml
Labels: area/monitoring, area/serverless

#8250 Add a prerequisites section to API Gateway migration
  docs/api-gateway/03-04-migration.md
Labels: area/documentation

#8251 Fix cbs integration tests
  tests/console-backend-service/internal/domain/eventing/trigger_test.go
Labels: area/console, bug, priority/critical

#8205 Fix Kubeless migration
  docs/migration-guides/1.11-1.12.md
  resources/cluster-users/templates/clusterroles-kubeless-io.yaml
  resources/cluster-users/templates/rbac-roles.yaml
  resources/cluster-users/values.yaml
  resources/core/charts/console-backend-service/templates/deployment.yaml
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/templates/runtimes.yaml
  resources/serverless/templates/secrets.yaml
  resources/serverless/templates/service-account.yaml
  resources/serverless/templates/usage-kind.yaml
  resources/serverless/values.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/cluster-role.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/function-usage-kind.yaml
Labels: area/documentation, area/serverless, bug, priority/critical

#8233 update kiali to 1.17.0
  resources/kiali/values.yaml
Labels: area/service-mesh
