Repository kyma-project/kyma, pull requests merged in 2020-05, with the labels that each got.

#8306 removing uninstall option from documentation
  docs/kyma/04-09-local-reinstallation.md
Labels: area/documentation, area/installation

#8258 Clean up the charts from unnecessary files
  resources/apiserver-proxy/files/generate-certs.sh
  resources/istio/templates/job-migration-remove-dr.yaml
  resources/istio/templates/rbac-migration-remove-dr.yaml
Labels: area/security, area/service-mesh

#8243 Prometheus CRDs doesn't work with k8s version 1.18
  resources/cluster-essentials/templates/alertmanager.crd.yaml
  resources/cluster-essentials/templates/podmonitor.crd.yaml
  resources/cluster-essentials/templates/prometheus.crd.yaml
  resources/cluster-essentials/templates/prometheusrules.crd.yaml
  resources/cluster-essentials/templates/servicemonitor.crd.yaml
  resources/cluster-essentials/templates/thanosrulers.crd.yaml
Labels: area/monitoring

#8332 Improve Volume snapshotting guide
  docs/backup/03-01-new-backup-strategy.md
Labels: area/documentation

#8348 Rename Eventing Mesh to Event Mesh
  docs/README.md
  docs/application-connector/01-01-application-connector.md
  docs/application-connector/02-01-application-connector.md
  docs/application-connector/02-04-application-broker.md
  docs/application-connector/06-03-event-activation.md
  docs/event-mesh/01-01-knative-eventing-mesh.md
  docs/event-mesh/02-01-knative-eventing-mesh.md
  docs/event-mesh/03-01-event-processing.md
  docs/event-mesh/05-01-nats-streaming.md
  docs/event-mesh/06-01-httpsource.md
  docs/event-mesh/08-01-configure-kafka-channel.md
  docs/event-mesh/08-02-set-up-channel.md
  docs/event-mesh/assets/event-mesh-flow.svg
  docs/event-mesh/assets/event-mesh-implementation.svg
  docs/knative-eventing-mesh/01-01-knative-eventing-mesh.md
  docs/kyma/01-01-in-a-nutshell.md
  docs/kyma/03-01-components.md
  docs/serverless/08-04-trigger-function-with-event.md
  resources/core/charts/docs/charts/content-ui/templates/docs-components-event-mesh-cag.yaml
  resources/knative-eventing/README.md
Labels: area/documentation, area/eventing

#8340 support for dynamic namespace discovery in kiali
  resources/kiali/values.yaml
Labels: area/service-mesh

#8341 use templating in kiali and jaeger CR to support complex overrides
  resources/kiali/templates/kiali.yaml
  resources/tracing/templates/jaeger.yaml
Labels: area/service-mesh, area/tracing

#8330 Update Troubleshooting guide for Api-gateway
  docs/api-gateway/10-02-connect-api-rule.md
Labels: area/documentation, area/security

#8353 Remove derberg from CODEOWNERS
  CODEOWNERS
Labels: area/community

#8314 Don't throw errors on the Kyma version query
  components/console-backend-service/internal/domain/k8s/versioninfo_converter.go
  components/console-backend-service/internal/domain/k8s/versioninfo_converter_test.go
  components/console-backend-service/internal/domain/k8s/versioninfo_resolver.go
  components/console-backend-service/internal/domain/k8s/versioninfo_resolver_test.go
  components/console-backend-service/internal/gqlschema/models_gen.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#8312 Add tests for knative trigger in serverless-controller-manager integration tests
  resources/serverless/templates/_helper_tests.txt
  resources/serverless/templates/tests/rbac.yaml
  resources/serverless/templates/tests/test.yaml
  resources/serverless/values.yaml
  tests/function-controller/Dockerfile
  tests/function-controller/README.md
  tests/function-controller/go.mod
  tests/function-controller/go.sum
  tests/function-controller/main_test.go
  tests/function-controller/pkg/apirule/apirule.go
  tests/function-controller/pkg/apirule/types/apirule.go
  tests/function-controller/pkg/broker/broker.go
  tests/function-controller/pkg/namespace/namespace.go
  tests/function-controller/pkg/resource/resource.go
  tests/function-controller/pkg/retry/retry.go
  tests/function-controller/pkg/shared/shared.go
  tests/function-controller/pkg/trigger/trigger.go
  tests/function-controller/testsuite/fixtures.go
  tests/function-controller/testsuite/function.go
  tests/function-controller/testsuite/functiondetails.go
  tests/function-controller/testsuite/testsuite.go
Labels: area/serverless, enhancement

#8362 Add troubleshooting guide for eventing
  docs/event-mesh/10-01-troubleshooting.md
Labels: area/documentation, area/eventing

#8363 Use custom jaeger operator image
  resources/tracing/values.yaml
Labels: area/tracing

#8207 Bump Compass Director, Provisioner and Schema Migrator images
  resources/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  resources/compass/charts/provisioner/values.yaml
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#8377 Update the migration guide 1.12
  docs/api-gateway/03-04-migration.md
  docs/migration-guides/1.11-1.12.md
Labels: area/documentation

#8375 Fix triggers for configMap and Job in function reconciler
  components/function-controller/internal/controllers/serverless/function_controller.go
Labels: area/serverless, bug, priority/critical

#8374 Add missing rbacs for kubeless in cbs
  resources/core/charts/console-backend-service/templates/cluster-role.yaml
  resources/serverless/values.yaml
Labels: area/console, bug, priority/critical

#8364 Add integration tests for servicebindingusages in serverless-controller-manager testsuite
  resources/serverless/templates/tests/rbac.yaml
  resources/serverless/values.yaml
  tests/function-controller/Dockerfile
  tests/function-controller/README.md
  tests/function-controller/go.mod
  tests/function-controller/go.sum
  tests/function-controller/pkg/addons/addons.go
  tests/function-controller/pkg/apirule/apirule.go
  tests/function-controller/pkg/broker/broker.go
  tests/function-controller/pkg/resource/resource.go
  tests/function-controller/pkg/servicebinding/servicebinding.go
  tests/function-controller/pkg/servicebindingusage/servicebindingusage.go
  tests/function-controller/pkg/servicebindingusage/types/v1alpha1/doc.go
  tests/function-controller/pkg/servicebindingusage/types/v1alpha1/register.go
  tests/function-controller/pkg/servicebindingusage/types/v1alpha1/types.go
  tests/function-controller/pkg/servicebindingusage/types/v1alpha1/zz_generated.deepcopy.go
  tests/function-controller/pkg/serviceinstance/serviceinstance.go
  tests/function-controller/pkg/shared/shared.go
  tests/function-controller/pkg/trigger/trigger.go
  tests/function-controller/testsuite/fixtures.go
  tests/function-controller/testsuite/function.go
  tests/function-controller/testsuite/testsuite.go
Labels: area/serverless, enhancement

#8379 Add tests for revision controller in serverless-controller-manager
  resources/serverless/templates/tests/rbac.yaml
  resources/serverless/values.yaml
  tests/function-controller/pkg/addons/addons.go
  tests/function-controller/pkg/apirule/apirule.go
  tests/function-controller/pkg/broker/broker.go
  tests/function-controller/pkg/resource/resource.go
  tests/function-controller/pkg/revision/revision.go
  tests/function-controller/pkg/servicebinding/servicebinding.go
  tests/function-controller/pkg/servicebindingusage/servicebindingusage.go
  tests/function-controller/pkg/serviceinstance/serviceinstance.go
  tests/function-controller/pkg/trigger/trigger.go
  tests/function-controller/testsuite/testsuite.go
Labels: area/serverless, enhancement

#8301 Write missing CBS integration tests for serverless domain
  resources/core/values.yaml
  tests/console-backend-service/internal/domain/eventing/trigger_test.go
  tests/console-backend-service/internal/domain/serverless/function_test.go
  tests/console-backend-service/internal/domain/serverless/function_types.go
  tests/console-backend-service/internal/domain/serverless/serverless.go
  tests/console-backend-service/internal/domain/serverless/serverless_test.go
Labels: area/serverless, enhancement, test-missing

#8287 Inject serviceBindings labels in Function CR
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/internal/controllers/serverless/build_resources.go
  components/function-controller/internal/controllers/serverless/function_controller.go
  components/function-controller/internal/controllers/serverless/function_controller_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha1/zz_generated.deepcopy.go
Labels: area/serverless, enhancement

#8386 Bump Provisioner and KEB images
  resources/compass/values.yaml
Labels: area/management-plane

#8299 Add external-services-mock chart
  resources/compass/charts/external-services-mock/.helmignore
  resources/compass/charts/external-services-mock/Chart.yaml
  resources/compass/charts/external-services-mock/templates/auditlog-configmap.yaml
  resources/compass/charts/external-services-mock/templates/auditlog-secret.yaml
  resources/compass/charts/external-services-mock/templates/deployment.yaml
  resources/compass/charts/external-services-mock/templates/service.yaml
  resources/compass/charts/external-services-mock/values.yaml
  resources/compass/charts/gateway/templates/deployment.yaml
  resources/compass/charts/gateway/values.yaml
  resources/compass/requirements.yaml
  resources/compass/templates/gateway-auditlog-integration-test.yaml
  resources/compass/values.yaml
Labels: area/management-plane

#8273 Switch Agent to use Secret instead of Config Map
  components/compass-runtime-agent/README.md
  components/compass-runtime-agent/cmd/main.go
  components/compass-runtime-agent/cmd/options.go
  components/compass-runtime-agent/go.sum
  components/compass-runtime-agent/internal/config/provider.go
  components/compass-runtime-agent/internal/config/provider_test.go
  docs/compass/03-20-runtime-agent-details.md
  docs/compass/08-10-runtime-agent-configuration.md
  docs/compass/08-11-runtime-agent-reconnecting.md
  resources/compass-runtime-agent/dev/create_config_map.sh
  resources/compass-runtime-agent/templates/1_13_migration-job.yaml
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/templates/resources-role-binding.yaml
  resources/compass-runtime-agent/templates/role-binding.yaml
  resources/compass-runtime-agent/templates/tests/compass-connectivity-adapter-external-solution-test.yaml
  resources/compass-runtime-agent/templates/tests/compass-external-solution-test.yaml
  resources/compass-runtime-agent/templates/tests/test-runtime-agent-integration.yaml
  resources/compass-runtime-agent/values.yaml
  resources/compass/templates/agent-configuration-job.yaml
  resources/compass/values.yaml
Labels: area/management-plane

#8381 Bump Compass images
  resources/compass/values.yaml
Labels: area/management-plane

#8391 Bump Provisioner image
  resources/compass/values.yaml
Labels: area/management-plane

#8388 Upgrade CBS test image version
  resources/core/values.yaml
Labels: area/serverless

#8396 Bump Compass Schema Migrator image
  resources/compass/values.yaml
Labels: area/management-plane, bug

#8387 Update UsageKind name in serverless tests
  tests/function-controller/README.md
  tests/function-controller/go.mod
  tests/function-controller/go.sum
  tests/function-controller/testsuite/testsuite.go
Labels: area/documentation, area/serverless

#8384 Inject serviceBindings labels in Function CR - console-backend-service
  components/console-backend-service/Gopkg.lock
  components/console-backend-service/Gopkg.toml
  components/console-backend-service/internal/domain/serverless/function_service.go
  components/console-backend-service/internal/domain/serverless/function_service_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/usagekind_service.go
Labels: area/console, area/serverless

#8402 improved log settings for gatekeeper
  resources/kiali/templates/kyma-additions/kcproxy-deployment.yaml
  resources/tracing/templates/kyma-additions/kcproxy-deployment.yaml
Labels: area/service-mesh, area/tracing

#8317 Charts for maintenance windows in Provisioner
  resources/compass/charts/provisioner/templates/deployment.yaml
  resources/compass/charts/provisioner/values.yaml
  resources/compass/values.yaml
Labels: area/management-plane

#8412 Update the Runtime Provisioner documentation after zone changed to a list of zones
  docs/compass/08-02-provisioner-provisioning-gardener.md
  docs/compass/08-04-provisioner-runtime-status.md
Labels: area/documentation, area/management-plane

#8397 Allow hiding Application from Runtimes
  resources/compass/charts/director/config.yaml
  resources/compass/charts/director/templates/configmap-configuration.yaml
  resources/compass/charts/director/templates/deployment.yaml
  resources/compass/charts/director/values.yaml
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#8418 Change update strategy for Docker Registry
  resources/serverless/charts/docker-registry/templates/deployment.yaml
  resources/serverless/charts/docker-registry/values.yaml
Labels: area/serverless, bug, priority/critical

#8343 Inject serviceBindings labels in Function CR - integration
  docs/serverless/06-01-function-cr.md
  docs/serverless/08-03-bind-service-instance.md
  resources/cluster-essentials/templates/functions.crd.yaml
  resources/core/charts/console-backend-service/templates/deployment.yaml
  resources/core/charts/console/templates/configmap.yaml
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
  resources/serverless/templates/_helper_bindings_migration.txt
  resources/serverless/templates/auth-proxy-service.yaml
  resources/serverless/templates/bindings-migration-job-post.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/templates/function-usage-kind.yaml
  resources/serverless/templates/service-monitor.yaml
  resources/serverless/templates/service.yaml
  resources/serverless/templates/tests/test.yaml
  resources/serverless/values.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/cluster-role.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/function-usage-kind.yaml
Labels: area/documentation, area/serverless

#8383 Bump KEB - LMS optional or mandatory (configurable)
  resources/compass/charts/kyma-environment-broker/templates/deployment.yaml
  resources/compass/charts/kyma-environment-broker/values.yaml
Labels: area/management-plane

#8411 Bump Provisioner and Provisioner tests
  resources/compass/values.yaml
Labels: area/management-plane

#8309 Stabilize UI tests and run them in two browsers
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
Labels: area/console, test-failing

#8426 Increase OathKeeper HTTP read timeout and thresholds for ORY probes
  resources/compass/values.yaml
  resources/ory/charts/hydra/templates/deployment.yaml
  resources/ory/charts/oathkeeper/templates/deployment-controller.yaml
  resources/ory/charts/oathkeeper/templates/deployment-with-sidecar.yaml
  resources/ory/values.yaml
Labels: area/management-plane, area/security, enhancement

#8432 Update ServiceManagerProxy chart
  resources/service-manager-proxy/Chart.yaml
  resources/service-manager-proxy/README.md
  resources/service-manager-proxy/templates/rbac.yaml
  resources/service-manager-proxy/values.yaml
Labels: area/management-plane, area/service-catalog

#8422 Remove basic authentication from KEB
  resources/compass/charts/kyma-environment-broker/templates/api-rule.yaml
  resources/compass/charts/kyma-environment-broker/templates/deployment.yaml
  resources/compass/charts/kyma-environment-broker/templates/secrets.yaml
  resources/compass/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
  resources/compass/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml
  resources/compass/charts/kyma-environment-broker/templates/tests/rbac.yaml
  resources/compass/charts/kyma-environment-broker/values.yaml
  resources/compass/values.yaml
Labels: area/management-plane

#8293 delete relase on install error - draft
  components/kyma-operator/Gopkg.lock
  components/kyma-operator/pkg/kymahelm/kyma-helm-client.go
  components/kyma-operator/pkg/kymainstallation/step.go
  components/kyma-operator/pkg/kymainstallation/step_test.go
  components/kyma-operator/pkg/steps/mock.go
Labels: area/installation, enhancement

#8431 Use custom image for Kiali
  resources/kiali/templates/operator/deployment.yaml
  resources/kiali/values.yaml
Labels: area/service-mesh

#8444 Set QPS for Kiali
  CODEOWNERS
  resources/kiali/values.yaml
Labels: area/service-mesh

#8453 Fix error handling in certhelpers
  installation/resources/installer-local.yaml
  installation/resources/installer.yaml
  installation/resources/tiller.yaml
Labels: area/installation

#8438 Installer retries last deployed rev
  components/kyma-operator/pkg/kymahelm/kyma-helm-client.go
  components/kyma-operator/pkg/kymainstallation/step.go
  components/kyma-operator/pkg/kymainstallation/stepsfactory.go
  components/kyma-operator/pkg/steps/installation.go
  components/kyma-operator/pkg/steps/mock.go
Labels: area/installation

#8430 Remove event-bus removal pre-upgrade job
  resources/event-sources/templates/100-pre-upgrade-job.yaml
Labels: area/eventing

#8436 Bump Director and Gateway image
  resources/compass/values.yaml
Labels: area/management-plane

#8449 New makefile and dockerfile for content-ui
  resources/core/charts/docs/charts/content-ui/Chart.yaml
Labels: area/console

#8415 Add more unit tests for serverless-controller-manager
  components/function-controller/.gitignore
  components/function-controller/internal/controllers/knative/service_controller_test.go
  components/function-controller/internal/controllers/kubernetes/configmap_controller.go
  components/function-controller/internal/controllers/kubernetes/configmap_controller_test.go
  components/function-controller/internal/controllers/kubernetes/configmap_service.go
  components/function-controller/internal/controllers/kubernetes/configmap_service_test.go
  components/function-controller/internal/controllers/kubernetes/namespace_controller.go
  components/function-controller/internal/controllers/kubernetes/namespace_controller_test.go
  components/function-controller/internal/controllers/kubernetes/secret_controller.go
  components/function-controller/internal/controllers/kubernetes/secret_controller_test.go
  components/function-controller/internal/controllers/kubernetes/secret_service.go
  components/function-controller/internal/controllers/kubernetes/secret_service_test.go
  components/function-controller/internal/controllers/kubernetes/serviceaccount_controller.go
  components/function-controller/internal/controllers/kubernetes/serviceaccount_controller_test.go
  components/function-controller/internal/controllers/kubernetes/serviceaccount_service_test.go
  components/function-controller/internal/controllers/kubernetes/shared.go
  components/function-controller/internal/controllers/kubernetes/shared_test.go
  components/function-controller/internal/controllers/serverless/build_resources.go
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  components/function-controller/internal/controllers/serverless/function_controller.go
  components/function-controller/internal/controllers/serverless/function_controller_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/resource/automock/client.go
  components/function-controller/internal/resource/resource.go
  components/function-controller/internal/resource/resource_test.go
  components/function-controller/pkg/apis/addtoscheme_runtime_v1alpha1.go
  components/function-controller/pkg/apis/apis.go
  components/function-controller/pkg/apis/serverless/v1alpha1/zz_generated.deepcopy.go
  tests/function-controller/.gitignore
  tests/function-controller/go.sum
  tests/function-controller/testsuite/function.go
  tests/function-controller/testsuite/testsuite.go
Labels: area/serverless, enhancement

#8425 Deprecate Application Connector's APIs
  docs/application-connector/02-01-application-connector.md
  docs/application-connector/assets/connectorapi.yaml
  docs/application-connector/assets/metadataapi.yaml
Labels: area/application-connector, area/documentation

#8291 Remove api-gateway-migrator
  components/api-gateway-migrator/Dockerfile
  components/api-gateway-migrator/Makefile
  components/api-gateway-migrator/README.md
  components/api-gateway-migrator/cmd/main.go
  components/api-gateway-migrator/examples/invalid.for.migration.input.yaml
  components/api-gateway-migrator/examples/invalid.for.migration.output.yaml
  components/api-gateway-migrator/examples/valid.for.migration.input.yaml
  components/api-gateway-migrator/examples/valid.for.migration.output.yaml
  components/api-gateway-migrator/go.mod
  components/api-gateway-migrator/go.sum
  components/api-gateway-migrator/pkg/finder/finder.go
  components/api-gateway-migrator/pkg/finder/finder_suite_test.go
  components/api-gateway-migrator/pkg/finder/finder_test.go
  components/api-gateway-migrator/pkg/finder/labels_test.go
  components/api-gateway-migrator/pkg/finder/status_test.go
  components/api-gateway-migrator/pkg/finder/structure_test.go
  components/api-gateway-migrator/pkg/migrator/k8s.go
  components/api-gateway-migrator/pkg/migrator/migrator.go
  components/api-gateway-migrator/pkg/migrator/migrator_suite_test.go
  components/api-gateway-migrator/pkg/migrator/migrator_test.go
  components/api-gateway-migrator/pkg/migrator/translate.go
  components/api-gateway-migrator/pkg/migrator/translate_test.go
  docs/api-gateway/01-01-api-gateway.md
  docs/api-gateway/03-04-migration.md
  docs/api-gateway/10-03-migration.md
  milv.config.yaml
  resources/api-gateway/templates/api-migrator-job.yaml
  resources/api-gateway/templates/api-migrator-rbac.yaml
  resources/api-gateway/values.yaml
Labels: area/security, area/service-mesh

#8466 Fixed typo on logging production profile docu
  docs/logging/05-02-production-profile.md
Labels: area/documentation, area/logging

#8460 Bump images
  resources/monitoring/values.yaml
Labels: area/management-plane, area/monitoring

#8480 Fix broken link
  docs/migration-guides/1.11-1.12.md
Labels: area/documentation

#8467 Update Api-gateway image
  resources/api-gateway/values.yaml
Labels: area/security

#8394 Update the Kyma environment broker image
  resources/compass/values.yaml
Labels: area/eventing

#8451 Remove nats-streaming migration job
  resources/nats-streaming/templates/migration-jobs.yaml
Labels: area/eventing

#8369 Enable caching in Serverless and disable colors in logs
  components/function-controller/README.md
  components/function-controller/deploy/function-runtime-image/nodejs12/kubeless-npm-install.sh
  components/function-controller/internal/controllers/serverless/build_resources.go
  components/function-controller/internal/controllers/serverless/config.go
  components/function-controller/internal/controllers/serverless/function_controller.go
  components/function-controller/internal/controllers/serverless/function_controller_test.go
  resources/serverless/templates/deployment.yaml
  resources/serverless/templates/runtimes.yaml
  resources/serverless/values.yaml
Labels: area/serverless, enhancement

#8491 enable tls verification for openid provider by default
  resources/kiali/templates/kyma-additions/kcproxy-deployment.yaml
  resources/tracing/templates/kyma-additions/kcproxy-deployment.yaml
Labels: area/service-mesh, area/tracing, bug

#8490 fixed cluster role setup for kiali-operator
  resources/kiali/templates/operator/clusterrole.yaml
Labels: area/service-mesh, bug

#8502 Fix dead Grafana link
  docs/monitoring/08-03-create-and-configure-grafana-dashboard.md
Labels: area/documentation

#8437 Grafana can't access logging end point
  resources/logging/templates/loki/servicerole.yaml
Labels: area/logging, area/monitoring, bug

#8407 rollback release on upgrade error
  components/kyma-operator/pkg/kymahelm/kyma-helm-client.go
  components/kyma-operator/pkg/kymainstallation/step.go
  components/kyma-operator/pkg/kymainstallation/step_test.go
Labels: area/installation, enhancement

#8461 Refactor Kiali documentation
  docs/kiali/01-01-kiali.md
  docs/kiali/02-01-kiali.md
  docs/kiali/03-01-kiali.md
  docs/kiali/05-01-kiali.md
  docs/kiali/assets/architecture.svg
  docs/kiali/assets/graph.png
  docs/kiali/assets/overview.png
  docs/service-mesh/01-01-service-mesh.md
  resources/core/charts/docs/charts/content-ui/templates/docs-components-kiali-cag.yaml
Labels: area/documentation, area/service-mesh

#8510 Update the Runtime Provisioner documentation
  docs/compass/08-02-provisioner-provisioning-gardener.md
  docs/compass/08-04-provisioner-runtime-status.md
Labels: area/documentation, area/management-plane

#8456 Prepare Grafana dashboard for Compass Director
  resources/compass/charts/director/templates/dashboard-configmap.yaml
  resources/compass/charts/director/templates/deployment.yaml
  resources/compass/charts/director/templates/policy.yaml
  resources/compass/charts/director/templates/service-monitor.yaml
  resources/compass/charts/director/templates/service.yaml
  resources/compass/charts/director/values.yaml
  resources/compass/templates/tenant-fetcher-job.yaml
  resources/compass/values.yaml
  resources/monitoring/values.yaml
Labels: area/management-plane, area/monitoring, enhancement

#8509 Update the Kyma environment broker image
  resources/compass/values.yaml
Labels: area/eventing, bug

#8515 Add identifier field support to Connectivity Adapter
  resources/compass/values.yaml
Labels: area/management-plane, bug

#8523 Fix a broken link
  docs/serverless/08-04-trigger-function-with-event.md
Labels: area/documentation, area/serverless

#8514 Add initial version of e2e upgrade test
  resources/compass/charts/kyma-environment-broker/templates/tests/e2e-upgrade-azure.yaml
  resources/compass/charts/kyma-environment-broker/values.yaml
  resources/compass/values.yaml
Labels: area/management-plane

#8530 Update the Kyma environment broker image to enforce lowercase Azure resource names
  resources/compass/values.yaml
Labels: area/eventing, bug

#8507 Bump new documentation component in console
  resources/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#8533 Installer advanced retries: docu
  docs/kyma/04-12-details.md
  docs/kyma/04-12-error-handling.md
Labels: area/documentation, area/installation

#8554 Add missing Serverless info to docs
  docs/serverless/03-01-api-rules.md
  docs/serverless/06-01-function-cr.md
Labels: area/documentation, area/serverless

#8553 Add Serverless Troubleshooting guide
  docs/serverless/10-01-serverless-troubleshooting.md
Labels: area/documentation, area/serverless

#8481 Installer step machine
  components/kyma-operator/Gopkg.lock
  components/kyma-operator/pkg/kymahelm/release.go
  components/kyma-operator/pkg/kymahelm/release_test.go
  components/kyma-operator/pkg/kymainstallation/step.go
  components/kyma-operator/pkg/kymainstallation/step_test.go
  components/kyma-operator/pkg/kymainstallation/stepsfactory.go
  components/kyma-operator/pkg/kymainstallation/stepsfactory_test.go
  components/kyma-operator/pkg/steps/installation.go
Labels: area/installation, enhancement

#8555 kyma-operator rollback fix
  components/kyma-operator/pkg/kymainstallation/step.go
Labels: area/installation

#8294 kyma-operator image bump
  tools/kyma-installer/kyma.Dockerfile
Labels: area/installation

#8516 Show Tenant fetcher custom metrics on Compass Director Grafana Dashboard
  resources/compass/charts/director/templates/dashboard-configmap.yaml
  resources/compass/templates/tenant-fetcher-job.yaml
  resources/compass/values.yaml
  resources/monitoring/charts/prometheus-pushgateway/.helmignore
  resources/monitoring/charts/prometheus-pushgateway/Chart.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/NOTES.txt
  resources/monitoring/charts/prometheus-pushgateway/templates/_helpers.tpl
  resources/monitoring/charts/prometheus-pushgateway/templates/deployment.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/ingress.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/kyma-additions/policy.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/networkpolicy.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/pdb.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/pushgateway-pvc.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/service.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/serviceaccount.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/servicemonitor.yaml
  resources/monitoring/charts/prometheus-pushgateway/values.yaml
  resources/monitoring/requirements.yaml
  resources/monitoring/values.yaml
Labels: area/management-plane, enhancement

#8561 Improve Grafana dashboard for Director
  resources/compass/charts/director/templates/dashboard-configmap.yaml
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#8551 Display Api type in console if there is no display name
  resources/service-catalog-addons/charts/service-catalog-ui/values.yaml
Labels: area/console, enhancement

#8558 Move the restore troubleshooting guide to Rafter
  docs/rafter/10-01-rafter-troubleshooting.md
Labels: area/documentation

#8406 Rework backup
  docs/backup/03-01-new-backup-strategy.md
  docs/kyma/01-01-in-a-nutshell.md
  docs/kyma/04-12-back-up-kyma.md
  docs/kyma/04-13-error-handling.md
  docs/kyma/08-05-restore-with-velero.md
  docs/kyma/08-06-create-volume-snapshots.md
  docs/kyma/08-07-create-volume-snapshots-providers.md
  docs/kyma/10-09-backup.md
  resources/core/charts/docs/charts/content-ui/templates/docs-components-backup-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-compass-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-console-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-kiali-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-rafter-cag.yaml
Labels: area/documentation

#8505 Ignore dynamic targets for monitoring test
  resources/monitoring/values.yaml
  tests/integration/monitoring/test-monitoring.go
Labels: area/monitoring

#8569 Fix links and add a tip
  docs/kyma/04-12-back-up-kyma.md
  docs/kyma/08-07-create-volume-snapshots-providers.md
Labels: area/documentation

#8568 Bump image for test core-external-solution
  resources/core/values.yaml
Labels: area/eventing

#8542 Log resources in serverless-controller-manager tests
  resources/serverless/templates/tests/rbac.yaml
  resources/serverless/values.yaml
  tests/function-controller/go.mod
  tests/function-controller/main_test.go
  tests/function-controller/pkg/addons/addons.go
  tests/function-controller/pkg/job/job.go
  tests/function-controller/pkg/kservice/kservice.go
  tests/function-controller/testsuite/testsuite.go
Labels: area/serverless, enhancement

#8574 Fix broken Istio link in the Tracing docs
  docs/tracing/10-01-traces-troubleshooting.md
Labels: area/documentation, bug

#8575 Adjust the function created in CBS tests to the serverless webhook
  tests/console-backend-service/internal/domain/serverless/function_test.go
Labels: area/serverless

#8570 Bump image for monitoring test
  resources/monitoring/values.yaml
Labels: area/monitoring

#8534 Metrics for Compass director
  resources/compass/charts/director/templates/business-dashboard-configmap.yaml
  resources/compass/charts/prometheus-postgres-exporter/.helmignore
  resources/compass/charts/prometheus-postgres-exporter/Chart.yaml
  resources/compass/charts/prometheus-postgres-exporter/README.md
  resources/compass/charts/prometheus-postgres-exporter/templates/NOTES.txt
  resources/compass/charts/prometheus-postgres-exporter/templates/_helpers.tpl
  resources/compass/charts/prometheus-postgres-exporter/templates/configmap.yaml
  resources/compass/charts/prometheus-postgres-exporter/templates/dashboard-configmap.yaml
  resources/compass/charts/prometheus-postgres-exporter/templates/deployment.yaml
  resources/compass/charts/prometheus-postgres-exporter/templates/podsecuritypolicy.yaml
  resources/compass/charts/prometheus-postgres-exporter/templates/policy.yaml
  resources/compass/charts/prometheus-postgres-exporter/templates/role.yaml
  resources/compass/charts/prometheus-postgres-exporter/templates/rolebinding.yaml
  resources/compass/charts/prometheus-postgres-exporter/templates/secrets.yaml
  resources/compass/charts/prometheus-postgres-exporter/templates/service.yaml
  resources/compass/charts/prometheus-postgres-exporter/templates/serviceaccount.yaml
  resources/compass/charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
  resources/compass/charts/prometheus-postgres-exporter/values.yaml
  resources/compass/requirements.yaml
Labels: area/management-plane

#8535 kyma-operator refactoring - extracting helm configuration
  components/kyma-operator/cmd/operator/main.go
  components/kyma-operator/pkg/kymahelm/kyma-helm-client.go
Labels: area/installation, enhancement

#8532 Wait for HTTP source in Application Connector test
  resources/application-connector/templates/tests/rbac.yaml
  resources/application-connector/values.yaml
  tests/application-connector-tests/Gopkg.lock
  tests/application-connector-tests/Gopkg.toml
  tests/application-connector-tests/test/applicationaccess/suite.go
  tests/application-connector-tests/test/testkit/retry.go
Labels: area/application-connector, bug

#8116 Add more Console smoke tests
  installation/resources/installer-config-local.yaml.tpl
  resources/core/charts/console/templates/deployment.yaml
  resources/core/charts/console/templates/test/test.yaml
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
  resources/logging/charts/logui/templates/deployment.yaml
  resources/logging/charts/logui/values.yaml
Labels: area/console

#8583 Modify seccomp annotations in postgres exporter chart
  resources/compass/charts/prometheus-postgres-exporter/templates/podsecuritypolicy.yaml
Labels: area/management-plane, bug

#8588 Update the console-backend-service image tag
  resources/core/values.yaml
Labels: area/serverless

#8587 Bump Application Connector tests image
  resources/application-connector/values.yaml
Labels: area/application-connector

#8600 Remove obsolete migration guide
  docs/migration-guides/1.11-1.12.md
Labels: area/documentation

#8592 Merge Director Grafana dashboards
  CODEOWNERS
  resources/compass/OWNERS
  resources/compass/charts/connectivity-adapter/templates/deployment.yaml
  resources/compass/charts/connectivity-adapter/values.yaml
  resources/compass/charts/director/templates/business-dashboard-configmap.yaml
  resources/compass/charts/director/templates/dashboard-configmap.yaml
  resources/compass/charts/pairing-adapter/templates/deployment.yaml
  resources/compass/charts/postgresql/templates/secrets.yaml
  resources/compass/charts/prometheus-postgres-exporter/templates/dashboard-configmap.yaml
  resources/compass/values.yaml
Labels: area/management-plane, area/monitoring, enhancement

#8586 Assign a non-root user for Kiali
  resources/kiali/values.yaml
Labels: area/security

#8590 Enable metrics endpoint for api-gateway
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/templates/monitoring.yaml
  resources/api-gateway/values.yaml
Labels: area/monitoring, area/security

#8513 Function CR validation
  components/function-controller/Makefile
  components/function-controller/README.md
  components/function-controller/cmd/webhook/main.go
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-controller/go.mod
  components/function-controller/go.sum
  components/function-controller/pkg/apis/serverless/v1alpha1/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_defaults_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/zz_generated.deepcopy.go
  resources/serverless/Chart.yaml
  resources/serverless/charts/webhook/Chart.yaml
  resources/serverless/charts/webhook/README.md
  resources/serverless/charts/webhook/templates/_helpers.tpl
  resources/serverless/charts/webhook/templates/cluster-role-binding.yaml
  resources/serverless/charts/webhook/templates/cluster-role.yaml
  resources/serverless/charts/webhook/templates/deployment.yaml
  resources/serverless/charts/webhook/templates/secret.yaml
  resources/serverless/charts/webhook/templates/service-account.yaml
  resources/serverless/charts/webhook/templates/service.yaml
  resources/serverless/charts/webhook/templates/webhooks.yaml
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/requirements.yaml
  resources/serverless/values.yaml
  tests/function-controller/testsuite/fixtures.go
  tests/function-controller/testsuite/testsuite.go
Labels: area/documentation, area/serverless

#8615 Add health endpoint for iam-kubeconfig-service
  components/iam-kubeconfig-service/cmd/generator/main.go
  components/iam-kubeconfig-service/pkg/kube_config/endpoints.go
  resources/iam-kubeconfig-service/templates/deployment.yaml
  resources/iam-kubeconfig-service/templates/service.yaml
  resources/iam-kubeconfig-service/values.yaml
Labels: area/security, area/service-mesh

#8567 Upgrade Grafana to v7.0.1
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring

#8622 Add Troubleshooting guide to Rafter
  docs/rafter/06-01-asset.md
  docs/rafter/06-04-clusterasset.md
  docs/rafter/10-02-upload-service-troubleshooting.md
Labels: area/core-and-supporting, area/documentation

#8628 IAM Kubeconfig Service image bump
  resources/iam-kubeconfig-service/values.yaml
Labels: area/security, area/service-mesh

#8623 Delete Kubeless CRD
  CODEOWNERS
  resources/cluster-users/templates/clusterroles-kubeless-io.yaml
  resources/cluster-users/templates/rbac-roles.yaml
  resources/cluster-users/values.schema.json
  resources/cluster-users/values.yaml
  resources/core/charts/console-backend-service/templates/cluster-role.yaml
  resources/core/charts/kubeless/Chart.yaml
  resources/core/charts/kubeless/templates/kubeless-crd.yaml
  resources/core/charts/kubeless/values.yaml
  resources/core/requirements.yaml
Labels: area/serverless

#8631 Fix preview build on Netlify
  .kyma-project-io/build-preview.sh
  docs/serverless/01-01-serverless.md
Labels: area/community, bug

#8632 Update istio docs
  docs/service-mesh/03-03-istio-rbac.md
  docs/service-mesh/10-03-connection-refused.md
  resources/api-gateway/README.md
  resources/istio/README.md
Labels: area/documentation

#8639 Fix broken links to Gardener documentation
  docs/kyma/04-04-cluster-installation.md
  docs/security/10-03-certificates-gardener.md
Labels: area/documentation, bug

#8614 Bump Director image
  resources/compass/values.yaml
Labels: area/management-plane

#8565 Upgrade service instance populator
  components/application-broker/Gopkg.lock
  components/application-broker/cmd/broker/main.go
  components/application-broker/internal/broker/broker.go
  components/application-broker/internal/broker/deprovision.go
  components/application-broker/internal/broker/id_selector.go
  components/application-broker/internal/broker/id_selector_test.go
  components/application-broker/internal/broker/provision.go
  components/application-broker/internal/broker/provision_test.go
  components/application-broker/internal/broker/server.go
  components/application-broker/internal/config/config.go
  components/application-broker/internal/nsbroker/facade.go
  components/application-broker/internal/nsbroker/facade_legacy_test.go
  components/application-broker/internal/storage/populator/automock/application_service_id_selector.go
  components/application-broker/internal/storage/populator/automock/broker_processes.go
  components/application-broker/internal/storage/populator/automock/operation_inserter.go
  components/application-broker/internal/storage/populator/common.go
  components/application-broker/internal/storage/populator/instances.go
  components/application-broker/internal/storage/populator/instances_test.go
  components/application-broker/internal/storage/storage.go
  components/application-broker/internal/syncer/broker_syncer.go
  components/application-broker/internal/syncer/controller.go
Labels: area/service-catalog

#8637 Parameterize compass-runtime-agent crd init script image
  resources/cluster-essentials/templates/crd-init-application-connector.yaml
  resources/cluster-essentials/templates/crd-init-compass-runtime-agent.yaml
  resources/cluster-essentials/values.yaml
Labels: area/core-and-supporting, area/installation, enhancement

#8643 Describe defaulting and validation webhooks in Serverless docs
  docs/serverless/02-01-serverless.md
  docs/serverless/03-01-supported-webhooks.md
  docs/serverless/03-02-api-rules.md
  docs/serverless/03-03-security.md
  docs/serverless/03-04-function-processing.md
  docs/serverless/assets/serverless-architecture.svg
Labels: area/documentation, area/serverless

#8648 Bump application broker image
  resources/application-connector/values.yaml
Labels: area/service-catalog
