Repository kyma-project/kyma, pull requests merged in 2020-03, with the labels that each got.

#7399 Bump kyma environment broker image
  resources/compass/values.yaml
Labels: area/management-plane

#7357 Secure storage endpoint
  resources/rafter/charts/controller-manager/charts/minio/templates/apirule.yaml
  resources/rafter/charts/controller-manager/charts/minio/templates/virtualservice.yaml
  resources/rafter/templates/pre-upgrade-delete-vs-job.yaml
  resources/rafter/values.yaml
Labels: area/core-and-supporting, enhancement

#7136 GolangCI-Lint script for function-controller
  components/function-controller/.golangci.yml
  components/function-controller/hack/run-linters.sh
  components/function-controller/pkg/controllers/function/function_controller.go
  components/function-controller/pkg/utils/controller_utils.go
  components/function-controller/pkg/utils/equality.go
  components/function-controller/pkg/utils/serving_utils_test.go
  components/function-controller/pkg/webhook/webhook.go
  components/function-controller/pkg/webhook/webhook_suite_test.go
  components/function-controller/pkg/webhook/webhook_test.go
Labels: area/serverless, enhancement

#7394 Add Kyma installation steps for IBM Cloud
  docs/kyma/04-04-cluster-installation.md
Labels: area/documentation

#7409 Update deps of function-controller
  components/function-controller/Makefile
  components/function-controller/go.mod
  components/function-controller/go.sum
  components/function-controller/main.go
  components/function-controller/pkg/apis/serverless/v1alpha1/v1alpha_suite_test.go
  components/function-controller/pkg/controllers/function/function_controller_suite_test.go
  components/function-controller/pkg/utils/controller_utils_test.go
  components/function-controller/pkg/webhook/server.go
  components/function-controller/pkg/webhook/webhook.go
  components/function-controller/pkg/webhook/webhook_suite_test.go
  components/function-controller/test/test.go
  resources/function-controller/templates/deployment.yaml
  resources/function-controller/values.yaml
Labels: area/serverless, enhancement

#7405 Log lines as JSON object fixed
  resources/logging/values.yaml
Labels: area/logging, bug

#7411 Remove dead link
  resources/function-controller/README.md
Labels: area/documentation

#7436 Fix applying labels on KService template in function-controller
  components/function-controller/pkg/controllers/function/function_controller.go
Labels: area/serverless, bug

#7390 Generate password for docker registry
  resources/function-controller/charts/docker-registry/templates/deployment.yaml
  resources/function-controller/charts/docker-registry/templates/secret.yaml
  resources/function-controller/charts/docker-registry/values.yaml
  resources/function-controller/templates/_helpers.tpl
  resources/function-controller/templates/image-pull-secret.yaml
  resources/function-controller/templates/secret.yaml
  resources/function-controller/templates/secrets.yaml
  resources/function-controller/values.yaml
Labels: area/serverless, enhancement

#7416 PoC: Distroless Istio
  resources/istio-kyma-patch/values.yaml
  resources/istio/files/kyma_cluster_istio_control_plane.yaml
  resources/istio/files/kyma_minikube_istio_control_plane.yaml
Labels: area/security, area/service-mesh

#7408 setting "editable" property to false in grafana dashboards
  resources/monitoring/templates/grafana/dashboards-1.14/cluster-total.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/etcd.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/k8s-coredns.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/pod-total.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/prometheus.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/workload-total.yaml
  resources/monitoring/templates/grafana/dashboards/etcd.yaml
  resources/monitoring/templates/grafana/dashboards/k8s-cluster-rsrc-use.yaml
  resources/monitoring/templates/grafana/dashboards/k8s-node-rsrc-use.yaml
  resources/monitoring/templates/grafana/dashboards/k8s-resources-cluster.yaml
  resources/monitoring/templates/grafana/dashboards/k8s-resources-namespace.yaml
  resources/monitoring/templates/grafana/dashboards/k8s-resources-pod.yaml
  resources/monitoring/templates/grafana/dashboards/k8s-resources-workload.yaml
  resources/monitoring/templates/grafana/dashboards/k8s-resources-workloads-namespace.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/apiserver.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-citadel.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/kubernetes-apiserver-per-client.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/lambda.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/rest-service.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/webapps.yaml
Labels: area/monitoring, bug

#7441 api-controller golang-buildpack version bump
  components/api-controller/Dockerfile
Labels: area/security

#7438 Bump function-controller version
  resources/function-controller/values.yaml
Labels: area/serverless, enhancement

#7418 Upgrade oathkeeper maester & hydra maester
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
  resources/ory/charts/oathkeeper/values.yaml
Labels: area/security, enhancement

#7375 Fix nginx vulnerabilities in console
  resources/compass/charts/cockpit/values.yaml
  resources/core/charts/console/values.yaml
  resources/core/charts/docs/charts/content-ui/Chart.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
  resources/helm-broker/charts/addons-ui/templates/configmap.yaml
  resources/helm-broker/charts/addons-ui/templates/deployment.yaml
  resources/helm-broker/values.yaml
  resources/logging/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/templates/configmap.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/templates/deployment.yaml
Labels: WIP, area/console

#7379 Fix compass E2E test
  tests/end-to-end/external-solution-integration/internal/scenario/compass_e2e/compass_e2e.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/register_application_in_compass.go
Labels: area/eventing, test-failing

#7429 Upgrade event-service Docker base image to `From scratch` [Component]
  components/event-service/Dockerfile
Labels: area/eventing

#7403 Refactor Runtime Agent metrics schema
  components/compass-runtime-agent/internal/metrics/logger.go
  components/compass-runtime-agent/internal/metrics/logger_test.go
  components/compass-runtime-agent/internal/metrics/model.go
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, area/logging, area/management-plane, bug

#7458 Upgrade Tiller to v2.16.3
  installation/resources/tiller.yaml
Labels: security/high

#7469 Remove outdated documentation from the official docs
  docs/application-connector/02-01-application-connector.md
  docs/application-connector/03-03-consume-services.md
Labels: area/documentation, bug

#7302 Prepare tutorial about binding Service Instances to lambda
  docs/serverless-v2/08-02-expose-lambda.md
  docs/serverless-v2/08-03-bind-service-instance.md
Labels: area/documentation, area/serverless

#7331 Add new deleteMany mutation for SBUsages in CBS and field in Function query with related SBUsages
  components/console-backend-service/internal/domain/k8s/deployment_resolver.go
  components/console-backend-service/internal/domain/k8s/deployment_resolver_test.go
  components/console-backend-service/internal/domain/root_resolver.go
  components/console-backend-service/internal/domain/serverless/disabled/resolver.go
  components/console-backend-service/internal/domain/serverless/function.go
  components/console-backend-service/internal/domain/serverless/function/listener.go
  components/console-backend-service/internal/domain/serverless/function_test.go
  components/console-backend-service/internal/domain/serverless/resolver.go
  components/console-backend-service/internal/domain/servicecatalogaddons/automock/export.go
  components/console-backend-service/internal/domain/servicecatalogaddons/automock/gql_service_binding_usage_converter.go
  components/console-backend-service/internal/domain/servicecatalogaddons/disabled/gql_service_binding_usage_converter.go
  components/console-backend-service/internal/domain/servicecatalogaddons/disabled/resolver.go
  components/console-backend-service/internal/domain/servicecatalogaddons/disabled/service_binding_usage_lister.go
  components/console-backend-service/internal/domain/servicecatalogaddons/export_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_converter.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_resolver.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_resolver_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_service.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_service_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicecatalogaddons.go
  components/console-backend-service/internal/domain/servicecatalogaddons/usagekind_converter_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/usagekind_resolver_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/usagekind_service.go
  components/console-backend-service/internal/domain/servicecatalogaddons/usagekind_service_test.go
  components/console-backend-service/internal/domain/shared/automock/gql_service_binding_usage_converter.go
  components/console-backend-service/internal/domain/shared/automock/service_binding_usage_lister.go
  components/console-backend-service/internal/domain/shared/automock/service_catalog_addons_retriever.go
  components/console-backend-service/internal/domain/shared/servicecatalogaddons.go
  components/console-backend-service/internal/gqlschema/config.yml
  components/console-backend-service/internal/gqlschema/models_gen.go
  components/console-backend-service/internal/gqlschema/schema.graphql
  components/console-backend-service/internal/gqlschema/schema_gen.go
Labels: area/serverless, area/service-catalog, enhancement

#7431 Update event service docker image [Resources]
  resources/application-connector/values.yaml
Labels: area/eventing

#7462 Improve retries in Application Connector Tests
  resources/application-connector/values.yaml
  tests/application-connector-tests/test/applicationaccess/suite.go
  tests/application-connector-tests/test/testkit/retry.go
Labels: area/application-connector, bug

#7454 Complete grafana oauth config and have kyma console disableable
  resources/monitoring/charts/grafana/templates/_pod.tpl
  resources/monitoring/charts/grafana/templates/kyma-additions/backendmodule.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/stats-metrics-microfrontend.yaml
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring

#7219 Add UsageKind for Knative Service
  resources/core/charts/console-backend-service/templates/cluster-role.yaml
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
  resources/function-controller/templates/usage-kind.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/cluster-role.yaml
Labels: area/serverless, area/service-catalog, enhancement

#7465 Add a security doc on Serverless
  docs/serverless-v2/02-01-serverless-v2.md
  docs/serverless-v2/03-01-api-rules.md
  docs/serverless-v2/03-02-security.md
Labels: area/documentation, area/security

#7354 Disable event-bus-upgrade-test
  tests/end-to-end/upgrade/Gopkg.lock
  tests/end-to-end/upgrade/main.go
  tests/end-to-end/upgrade/pkg/tests/event-bus/event_bus.go
Labels: area/eventing

#7457 Update ory postgresql
  resources/ory/charts/postgresql/Chart.yaml
  resources/ory/charts/postgresql/README.md
  resources/ory/charts/postgresql/templates/statefulset-slaves.yaml
  resources/ory/charts/postgresql/templates/statefulset.yaml
  resources/ory/charts/postgresql/values-production.yaml
  resources/ory/charts/postgresql/values.yaml
  resources/ory/requirements.yaml
Labels: area/security

#7476 Bump event-bus upgrade test image
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
Labels: area/eventing

#7420 golang-buildpack version bump
  components/iam-kubeconfig-service/Dockerfile
Labels: area/security

#7440 kyma-operator bump alpine version
  components/kyma-operator/Dockerfile
Labels: area/security

#7439 Feature toggle for Application Operator
  components/application-operator/charts/application/templates/deployment.yaml
  components/application-operator/charts/application/templates/role-binding.yaml
  components/application-operator/charts/application/templates/service.yaml
  components/application-operator/charts/application/templates/tests/application-gateway-tests.yaml
  components/application-operator/charts/application/templates/tests/rbac-application-gateway-test.yaml
  components/application-operator/charts/gateway/templates/deployment.yaml
  components/application-operator/charts/gateway/templates/role-binding.yaml
  components/application-operator/charts/gateway/templates/service.yaml
  components/application-operator/charts/gateway/templates/tests/gateway-tests.yaml
  components/application-operator/charts/gateway/templates/tests/rbac-gateway-test.yaml
  components/application-operator/cmd/manager/manager.go
  components/application-operator/cmd/manager/options.go
  components/application-operator/pkg/kymahelm/application/applicationreleasemanager_test.go
  components/application-operator/pkg/kymahelm/application/overrides.go
  components/application-operator/pkg/kymahelm/gateway/gatewaymanager_test.go
  components/application-operator/pkg/kymahelm/gateway/overrides.go
  resources/application-connector/charts/application-operator/templates/controller.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#7483 Change claim into parameter
  docs/serverless-v2/03-02-security.md
Labels: area/documentation

#7485 Fix broken links
  docs/service-mesh/01-01-service-mesh.md
  docs/service-mesh/03-01-istio-setup-in-kyma.md
  docs/service-mesh/05-05-production-profile.md
  docs/tracing/10-01-traces-troubleshooting.md
Labels: area/documentation

#7491 Use istioctl 1.4.6
  components/istio-installer/Dockerfile
Labels: area/service-mesh

#7489 Update service-mesh
  docs/service-mesh/01-01-service-mesh.md
Labels: area/documentation, area/service-mesh

#7461 Restrict access to Rafter, Tekton and Knative Serving resources
  resources/core/charts/cluster-users/templates/clusterroles-knative-serving.yaml
  resources/core/charts/cluster-users/templates/clusterroles-rafter.yaml
  resources/core/charts/cluster-users/templates/rbac-roles.yaml
  resources/core/charts/cluster-users/values.yaml
  resources/core/values.yaml
  tests/integration/cluster-users/sar-test.sh
Labels: area/core-and-supporting, area/security, area/serverless, security/medium

#7494 busybox unification
  resources/logging/templates/loki/statefulset.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/ory/charts/hydra/templates/tests/test-connection.yaml
  resources/ory/charts/hydra/values.yaml
  resources/ory/charts/oathkeeper/templates/deployment-with-sidecar.yaml
  resources/ory/charts/oathkeeper/templates/tests/test-connection.yaml
  resources/ory/charts/oathkeeper/values.yaml
Labels: area/security

#7395 Application Operator tests
  resources/application-connector/charts/application-operator/templates/tests/rbac.yaml
  resources/application-connector/charts/application-operator/templates/tests/test.yaml
  resources/application-connector/values.yaml
  tests/application-operator-tests/Dockerfile
  tests/application-operator-tests/Gopkg.lock
  tests/application-operator-tests/scripts/entrypoint.sh
  tests/application-operator-tests/test/applicationcontroller/suite.go
  tests/application-operator-tests/test/applicationcontroller/tests/applicationcontroller_test.go
  tests/application-operator-tests/test/serviceinstancecontroller/suite.go
  tests/application-operator-tests/test/serviceinstancecontroller/tests/serviceinstancecontroller_test.go
  tests/application-operator-tests/test/testkit/config.go
  tests/application-operator-tests/test/testkit/k8sresources_check.go
  tests/application-operator-tests/test/testkit/k8sresources_client.go
Labels: area/application-connector, enhancement

#7466 Update compass images
  resources/compass/values.yaml
Labels: WIP

#7309 Reduce prometheus memory footprint by reduced labelling and defensive querying
  installation/resources/installer-config-local.yaml.tpl
  installation/resources/installer-config-production.yaml.tpl
  resources/application-connector/charts/application-registry/templates/service-monitor.yaml
  resources/application-connector/charts/connector-service/templates/service-monitor.yaml
  resources/core/charts/apiserver-proxy/templates/servicemonitor.yaml
  resources/dex/templates/dashboard-configmap.yaml
  resources/dex/templates/service-monitor.yaml
  resources/event-bus/charts/event-publish-service/templates/service-monitor.yaml
  resources/event-bus/charts/subscription-controller/templates/service-monitor.yaml
  resources/helm-broker/charts/etcd-stateful/templates/04-servicemonitor.yaml
  resources/helm-broker/templates/extras/metrics.yaml
  resources/kiali/templates/servicemonitor.yaml
  resources/logging/charts/fluentbit/templates/service-monitor.yaml
  resources/monitoring/extractmetrics.sh
  resources/monitoring/templates/exporters/kube-api-server/servicemonitor.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-citadel.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/webapps.yaml
  resources/monitoring/templates/prometheus/servicemonitor.yaml
  resources/monitoring/values.yaml
  resources/ory/charts/hydra/charts/hydra-maester/templates/dashboard-configmap.yaml
  resources/ory/templates/monitoring-hydra.yaml
  resources/ory/templates/monitoring-oathkeeper.yaml
  resources/rafter/charts/asyncapi-service/templates/dashboard-configmap.yaml
  resources/rafter/charts/asyncapi-service/templates/service-monitor.yaml
  resources/rafter/charts/controller-manager/templates/dashboard-configmap.yaml
  resources/rafter/charts/controller-manager/templates/service-monitor.yaml
  resources/rafter/charts/front-matter-service/templates/dashboard-configmap.yaml
  resources/rafter/charts/front-matter-service/templates/service-monitor.yaml
  resources/rafter/charts/upload-service/templates/dashboard-configmap.yaml
  resources/rafter/charts/upload-service/templates/service-monitor.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/service-monitor.yaml
  resources/service-catalog/charts/catalog/templates/controller-manager-service-monitor.yaml
  resources/service-catalog/charts/catalog/values.yaml
Labels: area/monitoring

#7487 bump alpine to 3.11 in api-controller, apiserver-proxy, dex-static-us…
  components/api-controller/Dockerfile
  components/apiserver-proxy/Dockerfile
  components/dex-static-user-configurer/Dockerfile
  components/iam-kubeconfig-service/Dockerfile
  components/istio-kyma-patch/Dockerfile
  components/xip-patch/Dockerfile
Labels: area/security

#7515 Use custom images for Kiali and Node Exporter
  resources/kiali/templates/clusterrole.yaml
  resources/kiali/templates/deployment.yaml
  resources/kiali/values.yaml
  resources/logging/charts/fluentbit/values.yaml
  resources/monitoring/charts/prometheus-node-exporter/values.yaml
Labels: area/security

#7490 Update images of components that use kubectl
  resources/application-connector-helper/values.yaml
  resources/backup-init/values.yaml
  resources/cluster-essentials/values.yaml
  resources/core/values.yaml
  resources/dex/values.yaml
  resources/helm-broker/charts/etcd-stateful/values.yaml
  resources/istio-kyma-patch/values.yaml
  resources/istio/templates/job-install.yaml
  resources/xip-patch/values.yaml
Labels: area/security

#7517 Fix missing csp warning
  components/console-backend-service/internal/domain/application/app_service_test.go
  resources/core/values.yaml
Labels: area/console, security/low

#7527 Remove 'master' prefix from kyma version
  components/console-backend-service/internal/domain/k8s/versioninfo_converter.go
  components/console-backend-service/internal/domain/k8s/versioninfo_converter_test.go
Labels: area/console

#7521 Update KEB chart
  resources/compass/charts/kyma-environment-broker/templates/deployment.yaml
  resources/compass/charts/kyma-environment-broker/values.yaml
  resources/compass/values.yaml
Labels: area/management-plane

#7467 Bump compass chart
  resources/compass-runtime-agent/values.yaml
  resources/compass/values.yaml
  resources/core/values.yaml
  tests/end-to-end/external-solution-integration/Gopkg.lock
  tests/end-to-end/external-solution-integration/pkg/helpers/compass_fixtures.go
  tests/end-to-end/external-solution-integration/pkg/testkit/compass_director.go
Labels: area/management-plane, enhancement

#7539 Update docker registry image to be secure
  resources/function-controller/charts/docker-registry/values.yaml
Labels: area/serverless, enhancement

#7533 replace istio kubectl with alpine-kubectl
  resources/event-bus/charts/event-publish-service/templates/migration-jobs.yaml
  resources/event-bus/charts/subscription-controller/templates/migration-jobs.yaml
  resources/istio-init/templates/job-crd-10.yaml
  resources/istio-init/templates/job-crd-11.yaml
  resources/istio-init/templates/job-crd-12.yaml
  resources/istio-init/templates/job-crd-certmanager-10.yaml
  resources/istio-init/templates/job-crd-certmanager-11.yaml
  resources/istio-init/templates/kyma-job-cleaner.yaml
  resources/knative-serving-init/templates/delete-crd-job.yaml
  resources/nats-streaming/templates/migration-jobs.yaml
Labels: area/security

#7138 Provisioner Azure on Gardener Tests
  resources/compass/charts/provisioner/templates/deployment.yaml
  resources/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  resources/compass/charts/provisioner/values.yaml
  resources/compass/values.yaml
Labels: area/management-plane, area/quality, enhancement

#7534 Monitoring test failing with calling prometheus targets endpoint
  tests/integration/monitoring/test-monitoring.go
Labels: area/monitoring, bug, test-failing

#7545 bump alpine-kubectl version
  installation/resources/installer-local.yaml
  installation/resources/installer.yaml
  installation/resources/tiller.yaml
  resources/api-gateway/values.yaml
  resources/backup-init/templates/pre-upgrade-job.yaml
  resources/cluster-essentials/templates/prometheus.upgrade.job.yaml
  resources/core/charts/apiserver-proxy/templates/job.yaml
  resources/dex/templates/upgrade-job.yaml
  resources/istio-init/values.yaml
  resources/jaeger/templates/vs-job.yaml
  resources/monitoring/templates/kyma-additions/aks-kubelet-monitoring-patch.yaml
  resources/monitoring/templates/kyma-additions/azure-coredns-monitoring-patch.yaml
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
  resources/ory/templates/database-connectionstring-job.yaml
  resources/ory/values.yaml
  resources/rafter/charts/upload-service/values.yaml
  resources/rafter/values.yaml
  resources/service-catalog/charts/catalog/values.yaml
Labels: area/security

#7301 Namespaces resources migration from event bus to event-mesh pre-upgrade job
  resources/event-bus/charts/mesh-namespaces-migration/Chart.yaml
  resources/event-bus/charts/mesh-namespaces-migration/templates/_helpers.tpl
  resources/event-bus/charts/mesh-namespaces-migration/templates/migration-jobs.yaml
  resources/event-bus/values.yaml
  resources/knative-eventing/charts/knative-eventing/templates/pre-upgrade-job.yaml
Labels: area/eventing

#7536 Monitoring test image bump
  resources/monitoring/values.yaml
Labels: area/monitoring, bug, test-failing

#7557 Add a note about roles limitations in HB
  docs/helm-broker/06-01-clusteraddonsconfiguration.md
  docs/helm-broker/06-02-addonsconfiguration.md
Labels: area/documentation, area/service-catalog

#7525 Display old/new applications based on global.enableAPIPackages flag
  resources/application-connector/templates/applications-microfrontend.yaml
  resources/compass-runtime-agent/templates/compass-apps-microfrontend.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/console, enhancement

#7552 Fix vulnerabilities in console - bump asyncapi-react
  resources/compass/charts/cockpit/values.yaml
  resources/core/charts/docs/charts/content-ui/Chart.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
Labels: security/medium

#7551 Refactor istio charts
  CODEOWNERS
  docs/kyma/04-01-overview.md
  installation/resources/installer-cr-azure-eventhubs.yaml.tpl
  installation/resources/installer-cr-cluster-compass.yaml.tpl
  installation/resources/installer-cr-cluster-runtime.yaml.tpl
  installation/resources/installer-cr-cluster-with-compass.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  installation/scripts/testing-common.sh
  resources/istio-init/Chart.yaml
  resources/istio-init/OWNERS
  resources/istio-init/README.md
  resources/istio-init/files/crd-10.yaml
  resources/istio-init/files/crd-11.yaml
  resources/istio-init/files/crd-12.yaml
  resources/istio-init/files/crd-certmanager-10.yaml
  resources/istio-init/files/crd-certmanager-11.yaml
  resources/istio-init/templates/clusterrole.yaml
  resources/istio-init/templates/clusterrolebinding.yaml
  resources/istio-init/templates/configmap-crd-10.yaml
  resources/istio-init/templates/configmap-crd-11.yaml
  resources/istio-init/templates/configmap-crd-12.yaml
  resources/istio-init/templates/configmap-crd-certmanager-10.yaml
  resources/istio-init/templates/configmap-crd-certmanager-11.yaml
  resources/istio-init/templates/job-crd-10.yaml
  resources/istio-init/templates/job-crd-11.yaml
  resources/istio-init/templates/job-crd-12.yaml
  resources/istio-init/templates/job-crd-certmanager-10.yaml
  resources/istio-init/templates/job-crd-certmanager-11.yaml
  resources/istio-init/templates/kyma-job-cleaner.yaml
  resources/istio-init/templates/kyma-namespce-label-job.yaml
  resources/istio-init/templates/serviceaccount.yaml
  resources/istio-init/values.yaml
  resources/istio/README.md
  resources/istio/UPGRADE.md
  resources/istio/files/destination-rules.yaml
  resources/istio/files/job-script.sh
  resources/istio/templates/NOTES.txt
  resources/istio/templates/_affinity.tpl
  resources/istio/templates/_podDisruptionBudget.tpl
  resources/istio/templates/configmap-extra-manifests.yaml
  resources/istio/templates/job-install.yaml
  resources/istio/templates/job-namespace-label.yaml
  resources/istio/templates/rbac-install.yaml
  resources/istio/templates/rbac-namespace-label.yaml
  resources/istio/values.yaml
Labels: area/installation, area/service-mesh

#7543 Remove double 'master' prefix in Kyma version
  resources/core/values.yaml
Labels: area/console, bug

#7548 Bump images with whitesource changes
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
  resources/core/values.yaml
  resources/helm-broker/values.yaml
  resources/logging/values.yaml
Labels: area/security

#7559 adjusted minikube setup for monitoring
  installation/resources/installer-config-local.yaml.tpl
Labels: area/monitoring

#7423 Remove nginx-controller
  components/xip-patch/certhelper.sh
  docs/application-connector/08-10-rotate-root-ca.md
  installation/resources/installer-config-kind.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
  installation/resources/installer-cr-azure-eventhubs.yaml.tpl
  installation/resources/installer-cr-cluster-runtime.yaml.tpl
  installation/resources/installer-cr-cluster-with-compass.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  resources/application-connector-helper/Chart.yaml
  resources/application-connector-helper/OWNERS
  resources/application-connector-helper/templates/NOTES.txt
  resources/application-connector-helper/templates/_helpers.tpl
  resources/application-connector-helper/templates/helper-job.yaml
  resources/application-connector-helper/templates/rbac.yaml
  resources/application-connector-helper/templates/serviceaccount.yaml
  resources/application-connector-helper/values.yaml
  resources/application-connector-ingress/Chart.yaml
  resources/application-connector-ingress/OWNERS
  resources/application-connector-ingress/charts/nginx-ingress/.helmignore
  resources/application-connector-ingress/charts/nginx-ingress/Chart.yaml
  resources/application-connector-ingress/charts/nginx-ingress/README.md
  resources/application-connector-ingress/charts/nginx-ingress/templates/NOTES.txt
  resources/application-connector-ingress/charts/nginx-ingress/templates/_helpers.tpl
  resources/application-connector-ingress/charts/nginx-ingress/templates/clusterrole.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/clusterrolebinding.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/controller-configmap.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/controller-daemonset.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/controller-deployment.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/controller-hpa.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/controller-metrics-service.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/controller-poddisruptionbudget.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/controller-service.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/controller-stats-service.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/default-backend-deployment.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/default-backend-service.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/headers-configmap.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/podsecuritypolicy.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/role.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/rolebinding.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/serviceaccount.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/tcp-configmap.yaml
  resources/application-connector-ingress/charts/nginx-ingress/templates/udp-configmap.yaml
  resources/application-connector-ingress/charts/nginx-ingress/values.yaml
  resources/application-connector-ingress/templates/NOTES.txt
  resources/application-connector-ingress/templates/_helpers.tpl
  resources/application-connector-ingress/values.yaml
  resources/application-connector/templates/nginx-ingress-cert.yaml
Labels: area/application-connector, area/documentation

#7530 Add profiles for Monitoring
  docs/monitoring/01-01-monitoring.md
  docs/monitoring/05-04-production-profile.md
  docs/security/05-05-production-profile.md
  docs/service-mesh/05-05-production-profile.md
Labels: area/documentation, area/monitoring

#7504 Add Director proxy in Runtime Agent
  components/compass-runtime-agent/Makefile
  components/compass-runtime-agent/cmd/init.go
  components/compass-runtime-agent/cmd/main.go
  components/compass-runtime-agent/cmd/options.go
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  components/compass-runtime-agent/internal/compass/director/mocks/ProxyConfigurator.go
  components/compass-runtime-agent/internal/compass/director/proxy.go
  components/compass-runtime-agent/internal/compass/director/proxy_test.go
  components/compass-runtime-agent/internal/compassconnection/init.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/compassconnection/supervisor.go
  components/compass-runtime-agent/internal/metrics/logger.go
  components/compass-runtime-agent/internal/metrics/logger_test.go
  components/compass-runtime-agent/internal/metrics/metrics_fetcher_test.go
  components/compass-runtime-agent/internal/metrics/resources_fetcher_test.go
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector

#7572 Add id field to Service Entry in Application CR
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/types.go
Labels: area/application-connector

#7544 Align compass chart with runtime mapping feature
  resources/compass/charts/gateway/templates/oathkeeper-rules.yaml
  resources/compass/values.yaml
Labels: WIP, area/management-plane, enhancement

#7473 Grafana loki image update to v1.3.0
  resources/logging/charts/fluentbit/templates/_helpers.tpl
  resources/logging/charts/fluentbit/templates/configmap.yaml
  resources/logging/charts/fluentbit/templates/daemonset.yaml
  resources/logging/charts/fluentbit/values.yaml
  resources/logging/values.yaml
Labels: area/logging, area/security, priority/critical, security/critical

#7488 Istio grafana dashboards fixes
  resources/monitoring/templates/grafana/kyma-dashboards/istio-citadel.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-galley.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-mesh.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-mixer.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-performance.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-pilot.yaml
Labels: area/monitoring, area/service-mesh, bug

#7574 reduce log level for grafana to warning
  docs/monitoring/05-02-grafana.md
  docs/monitoring/05-04-production-profile.md
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring

#7560 Document gatewayOncePerNamespace Application Operator work mode
  components/application-operator/README.md
  docs/application-connector/02-01-application-connector.md
  docs/application-connector/05-01-application-operator.md
Labels: area/application-connector, area/documentation

#7576 Add security headers for log ui server
  resources/logging/values.yaml
Labels: area/console, area/logging, security/medium

#7565 Reduce istio cpu requests for prod profile
  docs/service-mesh/05-05-production-profile.md
  installation/resources/installer-config-production.yaml.tpl
Labels: area/documentation, area/installation, area/service-mesh

#7590 Add migration guide with an entry about Kyma CLI
  docs/migration-guide/1.10-1.11.md
Labels: area/cli, area/documentation

#7541 Specify namespace for Istio gateway for Grafana virtual service
  resources/monitoring/charts/grafana/templates/kyma-additions/virtualservice.yaml
Labels: area/monitoring

#7584 Improved labelling of grafana dashboards
  resources/apiserver-proxy/templates/dashboard-configmap.yaml
  resources/backup/templates/dashboard-configmap.yaml
  resources/dex/templates/dashboard-configmap.yaml
  resources/event-bus/charts/event-publish-service/templates/dashboard-configmap.yaml
  resources/event-bus/charts/subscription-controller/templates/dashboard-configmap.yaml
  resources/helm-broker/templates/extras/dashboard-configmap.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/etcd.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/nodes.yaml
  resources/monitoring/templates/grafana/dashboards-1.14/prometheus.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/apiserver.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-citadel.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-galley.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-mesh.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-mixer.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-performance.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-pilot.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-service.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/istio-workload.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/kubernetes-apiserver-per-client.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/lambda.yaml
  resources/ory/charts/hydra/charts/hydra-maester/templates/dashboard-configmap.yaml
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/templates/dashboard-configmap.yaml
  resources/rafter/charts/asyncapi-service/templates/dashboard-configmap.yaml
  resources/rafter/charts/controller-manager/charts/minio/templates/dashboard-configmap.yaml
  resources/rafter/charts/controller-manager/templates/dashboard-configmap.yaml
  resources/rafter/charts/front-matter-service/templates/dashboard-configmap.yaml
  resources/rafter/charts/upload-service/templates/dashboard-configmap.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/dashboard-configmap.yaml
  resources/service-catalog/charts/catalog/templates/dashboard-configmap.yaml
Labels: area/monitoring

#7502 Fix empty slack notifications by switching to .Annotations.message attribute
  resources/monitoring/templates/kyma-additions/alertmanager.config.yaml
  resources/monitoring/templates/prometheus/kyma-rules/alert-rules-backup.yaml
  resources/monitoring/templates/prometheus/kyma-rules/alert-rules-logging.yaml
  resources/monitoring/templates/prometheus/kyma-rules/alert-rules-rest-services.yaml
  resources/monitoring/templates/prometheus/kyma-rules/alert-rules-webapps.yaml
  resources/monitoring/templates/prometheus/kyma-rules/general.rules.yaml
  resources/monitoring/templates/prometheus/kyma-rules/kubernetes-storage.yaml
  resources/monitoring/templates/prometheus/kyma-rules/kyma-rules.yaml
  resources/monitoring/templates/prometheus/kyma-rules/kyma-rules2.yaml
Labels: area/monitoring

#7595 Fix for loki match label with fluent-bit
  resources/logging/charts/fluentbit/templates/configmap.yaml
  resources/logging/charts/fluentbit/values.yaml
Labels: area/logging, bug

#7598 Correct one Serverless tutorial
  docs/serverless-v2/08-03-bind-service-instance.md
Labels: area/documentation

#7600 Fix whitespace trimming in AKS installation docs
  docs/kyma/04-05-use-your-own-domain.md
Labels: area/documentation

#7604 Add endpoints to whitelist
  milv.config.yaml
Labels: area/documentation

#7563 Disable app name update in director API
  resources/compass-runtime-agent/values.yaml
  resources/compass/values.yaml
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/Gopkg.toml
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_test.go
  tests/compass-runtime-agent/test/testkit/applications/app.go
  tests/compass-runtime-agent/test/testkit/compass/client.go
  tests/compass-runtime-agent/test/testkit/graphql/graphqlizer.go
Labels: WIP, area/management-plane, enhancement

#7599 Fix vulnerable images for MinIO, MinIO Client, and update Docker Registry image
  resources/function-controller/charts/docker-registry/values.yaml
  resources/rafter/charts/upload-service/values.yaml
  resources/rafter/values.yaml
Labels: area/core-and-supporting, area/serverless, enhancement

#7591 bump helm in kyma-operator
  components/kyma-operator/Gopkg.lock
  components/kyma-operator/Gopkg.toml
Labels: area/security

#7570 Knative Eventing Mesh Migration Guide
  docs/migration-guides/1.10-1.11.md
Labels: area/documentation, area/eventing

#7607 Fix folders for migration guides
  docs/migration-guide/1.10-1.11.md
  docs/migration-guides/1.10-1.11.md
Labels: area/documentation

#7593 kyma-operator image bump
  resources/api-gateway/Chart.yaml
  resources/ory/charts/hydra/charts/hydra-maester/Chart.yaml
  tools/kyma-installer/kyma.Dockerfile
Labels: area/security

#7451 Enable docker registry on clusters with self signed certs
  components/function-controller/pkg/utils/serving_utils.go
  docs/kyma/04-01-overview.md
  installation/resources/installer-cr-azure-eventhubs.yaml.tpl
  installation/resources/installer-cr-cluster-runtime.yaml.tpl
  installation/resources/installer-cr-cluster-with-compass.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  resources/function-controller-init/templates/crd-challenges.yaml
  resources/function-controller-init/templates/crd-orders.yaml
  resources/function-controller/charts/docker-registry/templates/deployment.yaml
  resources/function-controller/charts/docker-registry/values.yaml
  resources/function-controller/templates/daemonset-configmap.yaml
  resources/function-controller/templates/daemonset.yaml
  resources/function-controller/templates/deployment.yaml
  resources/function-controller/templates/serverless-service-account.yaml
  resources/function-controller/templates/tests/rbac.yaml
  resources/function-controller/templates/tests/test.yaml
  resources/function-controller/values.yaml
  resources/knative-serving/templates/serving.yaml
  resources/knative-serving/values.yaml
Labels: area/serverless, enhancement

#7597 Grafana test framework image removed
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring, area/security, security/critical

#7614 Fix broken links
  docs/compass/08-02-provisioner-provisioning-gardener.md
Labels: area/documentation, bug

#7620 Update official Compass docs on the website
  docs/compass/02-02-basic-architecture.md
  docs/compass/02-03-detailed-workflow.md
  docs/compass/02-10-runtime-agent-workflow.md
  docs/compass/03-01-labels.md
  docs/compass/03-10-provisioner-details.md
  docs/compass/03-20-runtime-agent-details.md
  docs/compass/assets/api-registration.svg
  docs/compass/assets/app-configuration-update.svg
  docs/compass/assets/app-pairing.svg
  docs/compass/assets/runtime-configuration-update.svg
  docs/compass/assets/runtime-creation.svg
  docs/compass/assets/runtime-notification.svg
Labels: area/documentation, area/management-plane

#7616 Fix the events URL
  docs/migration-guides/1.10-1.11.md
  milv.config.yaml
Labels: area/documentation, area/eventing

#7622 Update labels link
  docs/compass/08-02-provisioner-provisioning-gardener.md
Labels: area/documentation

#7630 Configurable exclude path for loki input
  resources/logging/charts/fluentbit/templates/_helpers.tpl
  resources/logging/charts/fluentbit/templates/configmap.yaml
  resources/logging/charts/fluentbit/values.yaml
Labels: area/logging

#7627 Fix wrong header formatting
  docs/compass/03-01-labels.md
Labels: area/documentation, bug

#7631 Change image of minio client in rafter upload service
  resources/rafter/charts/upload-service/values.yaml
  resources/rafter/values.yaml
Labels: enhancement

#7609 Add Eventbus to Eventmesh upgrade tests
  tests/end-to-end/upgrade/main.go
  tests/end-to-end/upgrade/pkg/tests/eventmesh-migration/helpers/application.go
  tests/end-to-end/upgrade/pkg/tests/eventmesh-migration/helpers/event.go
  tests/end-to-end/upgrade/pkg/tests/eventmesh-migration/migrate-eventbus/eventbus.go
  tests/end-to-end/upgrade/pkg/tests/eventmesh-migration/migrate-eventbus/migrate-eventbus-setup.go
Labels: area/eventing

#7497 Api packages list & details
  resources/compass-runtime-agent/templates/compass-apps-microfrontend.yaml
  resources/core/charts/console/values.yaml
Labels: area/console, area/management-plane

#7561 Add API Package credential support in Application Broker
  components/application-broker/Gopkg.lock
  components/application-broker/Gopkg.toml
  components/application-broker/cmd/broker/main.go
  components/application-broker/internal/broker/automock/api_package_credentials_creator.go
  components/application-broker/internal/broker/automock/api_package_credentials_getter.go
  components/application-broker/internal/broker/automock/api_package_credentials_remover.go
  components/application-broker/internal/broker/automock/export.go
  components/application-broker/internal/broker/automock/service_binding_fetcher.go
  components/application-broker/internal/broker/bind.go
  components/application-broker/internal/broker/bind_creds_renderer.go
  components/application-broker/internal/broker/bind_creds_renderer_test.go
  components/application-broker/internal/broker/bind_export_test.go
  components/application-broker/internal/broker/bind_test.go
  components/application-broker/internal/broker/broker.go
  components/application-broker/internal/broker/catalog.go
  components/application-broker/internal/broker/catalog_test.go
  components/application-broker/internal/broker/deprovision.go
  components/application-broker/internal/broker/deprovision_test.go
  components/application-broker/internal/broker/dto.go
  components/application-broker/internal/broker/fix_test.go
  components/application-broker/internal/broker/provision.go
  components/application-broker/internal/broker/provision_test.go
  components/application-broker/internal/broker/server.go
  components/application-broker/internal/config/config.go
  components/application-broker/internal/director/cli.go
  components/application-broker/internal/director/config.go
  components/application-broker/internal/director/error.go
  components/application-broker/internal/director/nothing_doer_service.go
  components/application-broker/internal/director/service.go
  components/application-broker/internal/model.go
  components/application-broker/internal/servicecatalog/service_binding.go
  components/application-broker/internal/servicecatalog/service_binding_test.go
  components/application-broker/internal/syncer/mapper.go
  components/application-broker/internal/syncer/mapper_test.go
  components/application-broker/internal/syncer/validator.go
  resources/application-connector/charts/application-broker/templates/cluster-role.yaml
  resources/application-connector/charts/application-broker/templates/deployment.yaml
  resources/application-connector/charts/application-broker/values.yaml
  resources/application-connector/values.yaml
Labels: area/service-catalog, enhancement

#7633 fluent-bit can't discover pod labels
  resources/logging/charts/fluentbit/templates/configmap.yaml
Labels: area/logging, bug

#7636 Fluentbit is missing concrete resources limitations
  installation/resources/installer-config-production.yaml.tpl
  resources/logging/charts/fluentbit/values.yaml
  resources/logging/values.yaml
Labels: area/logging

#7635 Fix Gateway docs
  docs/rafter/08-02-set-minio-to-gateway-mode.md
Labels: area/documentation

#7646 Update usages of Compass GQL API
  resources/core/charts/console/values.yaml
Labels: area/console, area/management-plane

#7650 fix name for logging override in production profile
  installation/resources/installer-config-production.yaml.tpl
Labels: area/logging, bug

#7652 Fix compass tenant fetcher
  resources/compass/values.yaml
Labels: area/management-plane, bug

#7648 Fix 'docs per plan of null' error in console
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
Labels: area/console, bug

#7610 Bump charts for eventbus to eventmesh upgrade tests
  tests/end-to-end/upgrade/chart/upgrade/templates/rbac.yaml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
Labels: area/eventing

#7645 Don't fetch both API & Event on details view
  resources/compass/charts/cockpit/values.yaml
Labels: area/console

#7661 Update Certificates rotation tutorial
  docs/application-connector/08-10-rotate-root-ca.md
Labels: area/documentation

#7641 Fix propagating annotations in function-controller
  components/function-controller/pkg/controllers/function/function_controller.go
Labels: enhancement

#7349 Added auth policy for app-validator, app-event-service and source adapter
  components/application-connectivity-validator/internal/validationproxy/handler.go
  components/application-operator/README.md
  components/application-operator/charts/application/templates/authorization-policy.yaml
  components/application-operator/charts/application/templates/policy.yaml
  components/application-operator/charts/application/templates/role-binding.yaml
  components/application-operator/charts/application/templates/service-account.yaml
  components/application-operator/charts/application/templates/validator.yaml
  components/application-operator/charts/application/values.yaml
  components/application-operator/cmd/manager/manager.go
  components/application-operator/cmd/manager/options.go
  components/application-operator/pkg/kymahelm/application/applicationreleasemanager_test.go
  components/application-operator/pkg/kymahelm/application/overrides.go
  components/event-sources/reconciler/httpsource/reconcile_test.go
  components/event-sources/reconciler/object/policy.go
  components/event-sources/reconciler/object/policy_test.go
  components/event-sources/test/fixtures/policy.json
Labels: area/eventing, area/security

#7404 Enable Function Controller in all namespaces - controllers
  components/function-controller/README.md
  components/function-controller/go.mod
  components/function-controller/go.sum
  components/function-controller/main.go
  components/function-controller/pkg/configwatcher/configwatcher.go
  components/function-controller/pkg/configwatcher/configwatcher_test.go
  components/function-controller/pkg/configwatcher/credentials_service.go
  components/function-controller/pkg/configwatcher/credentials_service_test.go
  components/function-controller/pkg/configwatcher/namespace_service.go
  components/function-controller/pkg/configwatcher/namespaces_service_test.go
  components/function-controller/pkg/configwatcher/runtimes_service.go
  components/function-controller/pkg/configwatcher/runtimes_service_test.go
  components/function-controller/pkg/configwatcher/service_account_service.go
  components/function-controller/pkg/configwatcher/service_account_service_test.go
  components/function-controller/pkg/container/container.go
  components/function-controller/pkg/controllers/config/controller.go
  components/function-controller/pkg/controllers/config/controller_suite_test.go
  components/function-controller/pkg/controllers/config/controller_test.go
  components/function-controller/pkg/controllers/config/handler.go
  components/function-controller/pkg/controllers/config/utils_test.go
  components/function-controller/pkg/controllers/function/function_controller_suite_test.go
  components/function-controller/pkg/controllers/function/function_controller_test.go
Labels: area/serverless, enhancement

#7668 Label def scopes for integration systems
  resources/compass/charts/director/config.yaml
Labels: area/management-plane, enhancement

#7581 Test function-controller in custom namespace
  tests/function-controller/go.mod
  tests/function-controller/main_test.go
  tests/function-controller/pkg/apirule/apirule.go
  tests/function-controller/pkg/apirule/types/apirule.go
  tests/function-controller/pkg/apirule/types/groupversion_info.go
  tests/function-controller/pkg/apirule/types/rule_types.go
  tests/function-controller/pkg/namespace/namespace.go
  tests/function-controller/testsuite/function.go
  tests/function-controller/testsuite/functiondetails.go
  tests/function-controller/testsuite/testsuite.go
Labels: area/serverless

#7558 Enable Function controller in all namespaces
  docs/serverless-v2/01-01-serverless-v2.md
  docs/serverless-v2/08-01-create-lambda.md
  docs/serverless-v2/08-02-expose-lambda.md
  docs/serverless-v2/08-03-bind-service-instance.md
  installation/resources/installer-cr-azure-eventhubs.yaml.tpl
  installation/resources/installer-cr-cluster-runtime.yaml.tpl
  installation/resources/installer-cr-cluster-with-compass.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  resources/function-controller/templates/cluster-role.yaml
  resources/function-controller/templates/runtimes.yaml
  resources/function-controller/templates/secrets.yaml
  resources/function-controller/templates/serverless-namespace.yaml
  resources/function-controller/templates/serverless-service-account.yaml
  resources/function-controller/templates/service-account.yaml
  resources/function-controller/templates/tests/rbac.yaml
  resources/function-controller/values.yaml
Labels: area/serverless, enhancement

#7664 Fix broken namespaces filter
  resources/core/charts/console/values.yaml
Labels: area/console, bug

#7628 Hide Event Bus documentation, add missing docu to Eventing Mesh
  docs/knative-eventing-mesh/05-01-nats-streaming.md
  docs/knative-eventing-mesh/08-01-configure-kafka-channel.md
  docs/knative-eventing-mesh/08-02-set-up-channel.md
  resources/core/charts/docs/charts/content-ui/templates/docs-components-api-gateway-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-api-gateway-v2-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-backup-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-compass-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-console-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-event-bus-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-knative-eventing-mesh-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-logging-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-monitoring-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-rafter-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-serverless-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-serverless-v2-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-service-mesh-cag.yaml
  resources/core/charts/docs/charts/content-ui/templates/docs-components-tracing-cag.yaml
Labels: area/documentation, area/eventing

#7680 Fix formatting
  docs/compass/02-03-detailed-workflow.md
Labels: area/documentation, bug

#7674 fluent bit config fix
  resources/logging/charts/fluentbit/templates/configmap.yaml
  resources/logging/charts/fluentbit/values.yaml
Labels: area/logging, bug

#7684 Remove note from Eventing docs
  docs/knative-eventing-mesh/01-01-knative-eventing-mesh.md
Labels: area/documentation

#7683 Upgrade kiwigrid image
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring, area/security, security/high

#7603 Bump Provisioner image
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#7496 Separate user DB per component
  resources/compass/charts/director/templates/deployment.yaml
  resources/compass/charts/director/templates/tenant-loader-job.yaml
  resources/compass/charts/kyma-environment-broker/templates/deployment.yaml
  resources/compass/charts/kyma-environment-broker/templates/pre-upgrade-job.yaml
  resources/compass/charts/postgresql/templates/init-db-config-map.yaml
  resources/compass/charts/postgresql/templates/secrets.yaml
  resources/compass/charts/postgresql/templates/statefulset-slaves.yaml
  resources/compass/charts/postgresql/templates/statefulset.yaml
  resources/compass/charts/provisioner/templates/deployment.yaml
  resources/compass/configure-managed-gcp-postgresql.md
  resources/compass/templates/director-api-test.yaml
  resources/compass/templates/managed-postgresql-secret.yaml
  resources/compass/templates/migrator-job.yaml
  resources/compass/templates/tenant-fetcher-job.yaml
  resources/compass/values.yaml
Labels: area/management-plane, area/security

#7701 Upgraded dependencies for knative serving tests
  tests/knative-serving/Gopkg.lock
  tests/knative-serving/Gopkg.toml
  tests/knative-serving/knative_serving_test.go
Labels: WIP, area/serverless

#7637 Add UI tutorials for Serverless
  docs/serverless-v2/08-01-create-lambda.md
  docs/serverless-v2/08-02-expose-lambda.md
  docs/serverless-v2/08-03-bind-service-instance.md
Labels: area/documentation, area/serverless

#7718 Bump K8s client in Service Catalog tests
  tests/service-catalog/Gopkg.lock
  tests/service-catalog/Gopkg.toml
Labels: area/service-catalog, security/high

#7677 Log Persistent Volumes capacity
  components/compass-runtime-agent/cmd/main.go
  components/compass-runtime-agent/internal/metrics/logger.go
  components/compass-runtime-agent/internal/metrics/logger_test.go
  components/compass-runtime-agent/internal/metrics/metrics_fetcher.go
  components/compass-runtime-agent/internal/metrics/metrics_fetcher_test.go
  components/compass-runtime-agent/internal/metrics/model.go
  components/compass-runtime-agent/internal/metrics/resources_fetcher.go
  components/compass-runtime-agent/internal/metrics/volumes_fetcher.go
  components/compass-runtime-agent/internal/metrics/volumes_fetcher_test.go
  resources/compass-runtime-agent/templates/cluster-role-binding.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/logging, area/management-plane, enhancement

#7647 Remove special characters from compass labels
  components/compass-runtime-agent/internal/compass/director/client.go
  components/compass-runtime-agent/internal/compass/director/client_test.go
  resources/compass-runtime-agent/values.yaml
  resources/compass/values.yaml
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_labels_test.go
Labels: area/management-plane

#7702 Update Compass tutorial with the feature flag setup info
  docs/compass/04-01-compass.md
  docs/compass/08-01-basic-flow-tutorial.md
  docs/compass/assets/lambda.yaml
  milv.config.yaml
Labels: area/documentation, area/management-plane

#7723 revamp of lambda dashboard
  resources/monitoring/templates/grafana/kyma-dashboards/lambda.yaml
Labels: area/monitoring, area/serverless

#7729 Configure db pool for Director, Tenant Loader and Tenant Fetcher
  resources/compass/charts/director/templates/deployment.yaml
  resources/compass/charts/director/templates/tenant-loader-job.yaml
  resources/compass/charts/director/values.yaml
  resources/compass/templates/tenant-fetcher-job.yaml
  resources/compass/values.yaml
Labels: area/management-plane

#7739 Fix auth init in app broker
  components/application-broker/internal/director/service.go
  components/application-broker/internal/director/service_test.go
Labels: bug

#7751 Add more precise info to Events API spec
  docs/application-connector/assets/eventsapi.yaml
Labels: area/documentation

#7749 Unify Runtime Agent naming across docs
  docs/compass/02-01-components.md
  docs/compass/02-10-runtime-agent-workflow.md
  docs/compass/04-01-compass.md
  docs/compass/06-01-runtime-agent-compass-connection.md
Labels: area/documentation, area/management-plane

#7745 Add to compass provisioning overrides for runtimes
  resources/compass/charts/kyma-environment-broker/templates/deployment.yaml
  resources/compass/charts/kyma-environment-broker/templates/provisioning-runtime-overrides.yaml
  resources/compass/charts/kyma-environment-broker/templates/rbac.yaml
  resources/compass/values.yaml
Labels: area/management-plane

#7753 Fix Compass Director migrations
  resources/compass/values.yaml
Labels: area/management-plane, bug

#7758 Fix serviceinstance panic
  components/event-bus/cmd/mesh-namespaces-migration/serviceinstance.go
Labels: area/eventing

#7772 remove unnecessary check for gardener env
  components/xip-patch/xip-patch.sh
Labels: area/installation, bug

#7774 bump provisioner
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#7773 xip-patch image bump
  resources/apiserver-proxy/values.yaml
  resources/core/values.yaml
  resources/xip-patch/values.yaml
Labels: area/installation, bug

#7783 bump provisioner
  resources/compass/values.yaml
Labels: area/management-plane

#7782 Fix app and runtime status update with initial value
  resources/compass/values.yaml
Labels: area/management-plane, bug

#7770 Troubleshooting guides cleanup
  docs/kyma/10-04-common-errors.md
  docs/kyma/10-05-transport-closing.md
  docs/kyma/10-06-unable-create-helm.md
  docs/service-mesh/10-02-no-access.md
  docs/service-mesh/10-03-connection-refused.md
  docs/service-mesh/10-04-jobs-fail-aks.md
Labels: area/documentation

#7748 Additional security headers
  resources/compass/charts/cockpit/values.yaml
  resources/core/charts/console/values.yaml
  resources/core/charts/docs/charts/content-ui/Chart.yaml
  resources/core/charts/docs/charts/content-ui/templates/deployment.yaml
  resources/core/charts/docs/charts/content-ui/values.yaml
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
  resources/helm-broker/values.yaml
  resources/logging/values.yaml
Labels: area/console, area/security

#7786 Fix CM overrides in KEB
  resources/compass/charts/kyma-environment-broker/templates/provisioning-runtime-overrides.yaml
Labels: bug

#7784 Describe proxy refactoring in the Application Gateway
  components/application-gateway/cmd/applicationgateway/applicationproxy.go
  docs/application-connector/02-01-application-connector.md
  docs/application-connector/02-03-proxy-service.md
  docs/application-connector/03-08-application-gateway.md
Labels: area/application-connector, area/documentation

#7781 Fix the EventMesh delivery and latency dashboards
  resources/knative-eventing/charts/event-mesh-dashboard/templates/event-mesh-delivery.yaml
  resources/knative-eventing/charts/event-mesh-dashboard/templates/event-mesh-latency-dashboard.yaml
  resources/knative-eventing/charts/event-mesh-dashboard/templates/knative-eventing-broker-trigger.yaml
Labels: area/eventing

#7791 Update dex image
  resources/dex/Chart.yaml
Labels: area/security

#7785 Enable downloading pre releases in Provisioner
  resources/compass/charts/provisioner/templates/deployment.yaml
  resources/compass/charts/provisioner/values.yaml
  resources/compass/values.yaml
Labels: area/management-plane
