Repository kyma-project/kyma, pull requests merged in 2020-01, with the labels that each got.

#6750 Change helm broker metrics port
  resources/helm-broker/templates/deploy.yaml
  resources/helm-broker/templates/metrics.yaml
  resources/helm-broker/values.yaml
Labels: area/service-catalog

#6762 Update ports of metrics services in Rafter docs
  docs/rafter/11-03-upload-service.md
  docs/rafter/11-05-minio.md
Labels: area/application-connector, area/core-and-supporting, bug

#6758 Expose metrics of MinIO in Rafter release
  resources/rafter/values.yaml
Labels: area/core-and-supporting, bug

#6765 Add Codeowners of Rafter backup and upgrade tests
  CODEOWNERS
Labels: area/core-and-supporting

#6770 Fix a dead link to chart template debugging
  docs/helm-broker/03-01-create-addons.md
Labels: area/documentation

#6675 Upgrade Velero to 1.2.0
  docs/backup/01-01-backup.md
  docs/backup/04-01-install-velero.md
  docs/backup/05-01-velero.md
  docs/backup/08-01-create-backup.md
  docs/backup/08-02-restore-backup.md
  resources/backup-init/Chart.yaml
  resources/backup-init/templates/_helpers.tpl
  resources/backup-init/templates/crd-backups.yaml
  resources/backup-init/templates/crd-backupstoragelocations.yaml
  resources/backup-init/templates/crd-deletebackuprequests.yaml
  resources/backup-init/templates/crd-downloadrequests.yaml
  resources/backup-init/templates/crd-podvolumebackups.yaml
  resources/backup-init/templates/crd-podvolumerestores.yaml
  resources/backup-init/templates/crd-resticrepositories.yaml
  resources/backup-init/templates/crd-restores.yaml
  resources/backup-init/templates/crd-schedules.yaml
  resources/backup-init/templates/crd-serverstatusrequests.yaml
  resources/backup-init/templates/crd-volumesnapshotlocations.yaml
  resources/backup/Chart.yaml
  resources/backup/README.md
  resources/backup/templates/NOTES.txt
  resources/backup/templates/_helpers.tpl
  resources/backup/templates/configmaps.yaml
  resources/backup/templates/dashboard-configmap.yaml
  resources/backup/templates/deployment.yaml
  resources/backup/templates/restic-daemonset.yaml
  resources/backup/templates/service.yaml
  resources/backup/templates/serviceaccount-server.yaml
  resources/backup/templates/servicemonitor.yaml
  resources/backup/templates/volumesnapshotlocation.yaml
  resources/backup/values.yaml
Labels: area/quality

#6766 Expose 'experimental' category in the console UI
  CODEOWNERS
  resources/api-gateway/templates/api-rules-microfrontend.yaml
  resources/core/charts/console/values.yaml
  resources/function-controller/templates/lambdas-microfrontend.yaml
Labels: area/console, enhancement

#6774 Bump images of Rafter to newest
  resources/rafter/values.yaml
Labels: area/core-and-supporting, bug

#6771 Hb sustain servicebroker
  docs/helm-broker/02-01-helm-broker.md
  resources/helm-broker/templates/rbac.yaml
  resources/helm-broker/values.yaml
Labels: area/service-catalog

#6811 Increase CBS pod limits
  resources/core/charts/console-backend-service/templates/deployment.yaml
Labels: area/console, bug

#6778 Add knative-build namespace to the list of system namespaces
  resources/core/charts/console-backend-service/values.yaml
Labels: area/console

#6810 Upgrade Jaeger to v1.16.0
  resources/jaeger/templates/deployment.yaml
  resources/jaeger/values.yaml
Labels: area/tracing

#6798 Increase timeouts for fetching spec in Application Registry
  components/application-registry/README.md
  components/application-registry/cmd/applicationregistry/options.go
  components/application-registry/internal/metadata/specification/rafter/service_test.go
  components/application-registry/internal/metadata/specification/service_test.go
  docs/application-connector/05-02-application-registry.md
  resources/application-connector/charts/application-registry/README.md
  resources/application-connector/charts/application-registry/values.schema.json
  resources/application-connector/charts/application-registry/values.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#6669 Implement Compass E2E test using external solution
  tests/end-to-end/external-solution-integration/Gopkg.lock
  tests/end-to-end/external-solution-integration/Gopkg.toml
  tests/end-to-end/external-solution-integration/README.md
  tests/end-to-end/external-solution-integration/cmd/runner/main.go
  tests/end-to-end/external-solution-integration/internal/scenario/compass_e2e.go
  tests/end-to-end/external-solution-integration/internal/scenario/e2e.go
  tests/end-to-end/external-solution-integration/internal/scenario/state.go
  tests/end-to-end/external-solution-integration/pkg/helpers/compass_fixtures.go
  tests/end-to-end/external-solution-integration/pkg/helpers/lambda.go
  tests/end-to-end/external-solution-integration/pkg/helpers/secret.go
  tests/end-to-end/external-solution-integration/pkg/step/parallel.go
  tests/end-to-end/external-solution-integration/pkg/testkit/certificates.go
  tests/end-to-end/external-solution-integration/pkg/testkit/clients.go
  tests/end-to-end/external-solution-integration/pkg/testkit/compass_connector.go
  tests/end-to-end/external-solution-integration/pkg/testkit/compass_director.go
  tests/end-to-end/external-solution-integration/pkg/testkit/registry.go
  tests/end-to-end/external-solution-integration/pkg/testkit/testservice.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/assign_scenario_in_compass.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/connect_application_using_compass.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/create_mapping.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/create_namespace.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/create_separate_service_instance.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/create_service_binding.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/create_service_binding_usage.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/create_service_instance.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/register_application_in_compass.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/register_test_service.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/send_event.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/start_test_server.go
Labels: enhancement

#6804 Remove auto polling from catalog-ui and new lambda-ui
  resources/core/charts/console/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
Labels: area/console, bug, priority/critical

#6681 Add Test Definition with compass external solution test
  resources/compass-runtime-agent/templates/tests/compass-external-solution-test.yaml
  resources/compass-runtime-agent/templates/tests/rbac-external-solution.yaml
  resources/compass-runtime-agent/values.yaml
  resources/compass/charts/director/config.yaml
  resources/compass/values.yaml
  resources/core/values.yaml
Labels: enhancement

#6839 Bump ServiceBindingUsage controller image
  resources/service-catalog-addons/values.yaml
Labels: area/service-catalog

#6826 Create triggers from lambda UI
  resources/core/charts/kubeless/charts/lambdas-ui/values.yaml
Labels: area/console, area/serverless, enhancement

#6808 Integrate Fluent Bit into Kyma
  docs/logging/01-01-logging.md
  docs/logging/02-01-logging.md
  docs/logging/03-02-configure-storage.md
  docs/logging/05-01-logging.md
  docs/logging/assets/logging-architecture.svg
  resources/logging/Chart.yaml
  resources/logging/README.md
  resources/logging/charts/fluentbit/Chart.yaml
  resources/logging/charts/fluentbit/templates/NOTES.txt
  resources/logging/charts/fluentbit/templates/_helpers.tpl
  resources/logging/charts/fluentbit/templates/cluster-role.yaml
  resources/logging/charts/fluentbit/templates/cluster-rolebinding.yaml
  resources/logging/charts/fluentbit/templates/configmap.yaml
  resources/logging/charts/fluentbit/templates/daemonset.yaml
  resources/logging/charts/fluentbit/templates/pod-security-policy.yaml
  resources/logging/charts/fluentbit/templates/policy.yaml
  resources/logging/charts/fluentbit/templates/secrets.yaml
  resources/logging/charts/fluentbit/templates/service-account.yaml
  resources/logging/charts/fluentbit/templates/service-monitor.yaml
  resources/logging/charts/fluentbit/templates/service.yaml
  resources/logging/charts/fluentbit/values.yaml
  resources/logging/templates/fluent-bit/_helpers.tpl
  resources/logging/templates/fluent-bit/configmap.yaml
  resources/logging/templates/fluent-bit/daemonset.yaml
  resources/logging/templates/fluent-bit/role.yaml
  resources/logging/templates/fluent-bit/rolebinding.yaml
  resources/logging/templates/log-ui/clustermicrofrontend.yaml
  resources/logging/templates/log-ui/configmap.yaml
  resources/logging/templates/log-ui/deployment.yaml
  resources/logging/templates/log-ui/destinationrule.yaml
  resources/logging/templates/log-ui/service.yaml
  resources/logging/templates/log-ui/virtualservice.yaml
  resources/logging/templates/loki/backendmodule.yaml
  resources/logging/templates/loki/destinationrule.yaml
  resources/logging/templates/loki/networkpolicy.yaml
  resources/logging/templates/loki/podsecuritypolicy.yaml
  resources/logging/templates/loki/policy.yaml
  resources/logging/templates/loki/role.yaml
  resources/logging/templates/loki/rolebinding.yaml
  resources/logging/templates/loki/secret.yaml
  resources/logging/templates/loki/service.yaml
  resources/logging/templates/loki/serviceaccount.yaml
  resources/logging/templates/loki/servicerole.yaml
  resources/logging/templates/loki/servicerolebinding.yaml
  resources/logging/templates/loki/statefulset.yaml
  resources/logging/templates/loki/virtualservice.yaml
  resources/logging/templates/promtail/_helpers.tpl
  resources/logging/templates/promtail/clusterrole.yaml
  resources/logging/templates/promtail/clusterrolebinding.yaml
  resources/logging/templates/promtail/configmap.yaml
  resources/logging/templates/promtail/daemonset.yaml
  resources/logging/templates/promtail/dashboard-configmap.yaml
  resources/logging/templates/promtail/podsecuritypolicy.yaml
  resources/logging/templates/promtail/role.yaml
  resources/logging/templates/promtail/rolebinding.yaml
  resources/logging/templates/tests/rbac.yaml
  resources/logging/templates/tests/test.yaml
  resources/logging/values.yaml
  tests/integration/logging/test-logging.go
Labels: area/logging

#6856 Adding istio-installer component
  CODEOWNERS
  components/istio-installer/Dockerfile
  components/istio-installer/Makefile
  components/istio-installer/OWNERS
  components/istio-installer/README.md
Labels: area/installation, area/service-mesh

#6747 Update service-catalog-ui image
  resources/compass/charts/cockpit/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/Chart.yaml
Labels: area/console, enhancement

#6825 Adjust MTLS Virtual Service values
  components/application-operator/charts/application/templates/virtual-service.yaml
  resources/application-connector/charts/connector-service/templates/virtualservice-mtls.yaml
  resources/application-connector/templates/application-connector-gateway.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector, enhancement

#6819 Remove old code form UI tests and enable them
  resources/core/charts/console/values.yaml
  resources/core/values.yaml
Labels: area/console, test-failing

#6781 Add validation of function CR in webhooks in function-controller
  components/function-controller/Gopkg.lock
  components/function-controller/Gopkg.toml
  components/function-controller/pkg/webhook/default_server/function/mutating/function_create_handler.go
  components/function-controller/pkg/webhook/default_server/function/mutating/function_create_handler_test.go
  components/function-controller/pkg/webhook/default_server/webhook_test.go
Labels: area/serverless, bug

#6801 Update codeowners for function-controller and kubeless
  CODEOWNERS
Labels: area/core-and-supporting, area/serverless, enhancement

#6863 Align Helm Broker chart with external repo version
  resources/cluster-essentials/templates/addons-configuration.crd.yaml
  resources/cluster-essentials/templates/cluster-addons-configuration.crd.yaml
  resources/helm-broker/templates/_helpers.tpl
  resources/helm-broker/templates/default-addons-cfg.yaml
  resources/helm-broker/templates/deploy.yaml
  resources/helm-broker/templates/extras/dashboard-configmap.yaml
  resources/helm-broker/templates/extras/istio-rbac.yaml
  resources/helm-broker/templates/extras/metrics.yaml
  resources/helm-broker/templates/helm-broker-cfg.yaml
  resources/helm-broker/templates/helm-secret.yaml
  resources/helm-broker/templates/svc.yaml
  resources/helm-broker/values.yaml
Labels: area/service-catalog, enhancement

#6874 Update Compass Provisioner charts
  resources/compass/charts/provisioner/templates/deployment.yaml
  resources/compass/charts/provisioner/templates/registration-job.yaml
  resources/compass/charts/provisioner/values.yaml
  resources/compass/values.yaml
Labels: enhancement

#6870 Close connection in cbs if auth failed
  components/console-backend-service/internal/authn/middleware.go
  components/console-backend-service/main.go
Labels: area/console, bug

#6877 Add documentation for installing components from user-defined URLs
  docs/kyma/05-04-component-source-url.md
  docs/kyma/06-01-installation.md
  milv.config.yaml
Labels: area/documentation, area/installation

#6843 Fix the Knative Serving acceptance test
  tests/knative-serving/Gopkg.lock
  tests/knative-serving/knative_serving_test.go
Labels: area/eventing, area/serverless

#6850 Add documentation for Hydra production profile
  docs/security/03-07-production-profile.md
Labels: area/documentation, area/security

#6837 Use istioctl to install istio 1.4.3
  resources/istio-kyma-patch/values.yaml
  resources/istio/files/job-script.sh
  resources/istio/files/kyma_cluster_istio_control_plane.yaml
  resources/istio/templates/configmap-cluster.yaml
  resources/istio/templates/configmap-minikube.yaml
  resources/istio/templates/job.yaml
Labels: area/service-mesh

#6911 Add Fair & Arithnea logos to the main README.md
  README.md
Labels: area/documentation

#6910 Emphasize in docs that Rafter is only for storing public data
  docs/rafter/01-01-rafter.md
  docs/rafter/03-04-minio-gateway.md
  docs/rafter/03-06-upload-service.md
  docs/rafter/08-02-set-minio-to-gateway-mode.md
Labels: area/core-and-supporting, area/documentation

#6918 Add michal-hudy and janmedrek to cluster-essentials codeowners
  CODEOWNERS
Labels: area/community

#6887 Change burst and set random resync period in CBS
  components/console-backend-service/docs/configuration.md
  components/console-backend-service/internal/domain/root_resolver.go
  components/console-backend-service/main.go
Labels: area/console, bug

#6896 Update the Knative serving acceptance tests image
  resources/knative-serving/values.yaml
Labels: area/eventing, area/serverless

#6882 explicit "default" namespace for installation resource
  components/kyma-operator/README.md
  docs/backup/10-01-restore-troubleshooting.md
  docs/kyma/04-11-update.md
  docs/kyma/05-02-custom-component-installation.md
  docs/kyma/05-03-overrides.md
  docs/kyma/06-01-installation.md
  docs/monitoring/08-05-send-notifications.md
  docs/rafter/08-02-set-minio-to-gateway-mode.md
  docs/security/08-01-update-tls-certificates.md
  installation/resources/installer-cr-cluster-compass.yaml.tpl
  installation/resources/installer-cr-cluster-runtime.yaml.tpl
  installation/resources/installer-cr-cluster-with-compass.yaml.tpl
  installation/resources/installer-cr-cluster.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
  installation/scripts/is-installed.sh
Labels: area/installation

#6904 Improve synchronisation mechanism between Console Backend Service and API server
  resources/core/charts/console-backend-service/templates/deployment.yaml
  resources/core/values.yaml
Labels: area/console, bug

#6928 Monitoring upgrade fix
  resources/cluster-essentials/templates/prometheus.upgrade.job.yaml
Labels: area/monitoring, bug

#6930 Upgrade istio installer image
  components/istio-installer/Dockerfile
Labels: area/cluster, enhancement

#6799 Remove/update deprecated apiGroups in console-backend-service
  components/console-backend-service/Gopkg.lock
  components/console-backend-service/Gopkg.toml
  components/console-backend-service/contrib/examples/service-catalog-test-data.yaml
  components/console-backend-service/internal/authz/fixture_test.go
  components/console-backend-service/internal/domain/k8s/automock/deployment_getter.go
  components/console-backend-service/internal/domain/k8s/automock/deployment_lister.go
  components/console-backend-service/internal/domain/k8s/dep.go
  components/console-backend-service/internal/domain/k8s/deployment_converter.go
  components/console-backend-service/internal/domain/k8s/deployment_converter_test.go
  components/console-backend-service/internal/domain/k8s/deployment_resolver.go
  components/console-backend-service/internal/domain/k8s/deployment_resolver_test.go
  components/console-backend-service/internal/domain/k8s/deployment_service.go
  components/console-backend-service/internal/domain/k8s/deployment_service_test.go
  components/console-backend-service/internal/domain/k8s/k8s.go
  components/console-backend-service/internal/extractor/resourcemeta_test.go
  components/console-backend-service/pkg/client/clientset/versioned/typed/ui/v1alpha1/ui_client.go
Labels: area/core-and-supporting, enhancement

#6772 Remove last leftovers from AssetStore/HCMS
  resources/cluster-essentials/templates/asset.crd.yaml
  resources/cluster-essentials/templates/bucket.crd.yaml
  resources/cluster-essentials/templates/clusterasset.crd.yaml
  resources/cluster-essentials/templates/clusterbucket.crd.yaml
  resources/cluster-essentials/templates/clusterdocstopic.crd.yaml
  resources/cluster-essentials/templates/docstopic.crd.yaml
  resources/rafter/templates/_helper_migration_assetstore_resources.txt
  resources/rafter/templates/_helper_migration_create_rafter_upload_service_config_map.txt
  resources/rafter/templates/_helper_migration_system_buckets.txt
  resources/rafter/templates/migration-job-post.yaml
  resources/rafter/templates/migration-job-pre.yaml
  resources/rafter/templates/migration-job-terminator.yaml
  resources/rafter/values.yaml
Labels: area/core-and-supporting

#6934 Disable destination rules for hydra
  resources/ory/templates/hydra-destinationrules.yaml
Labels: area/service-mesh, bug

#6912 Temporary disable mockice in cbs tests
  tests/console-backend-service/internal/domain/rafter/clusterassetgroup_test.go
  tests/console-backend-service/internal/domain/servicecatalog/serviceclass_test.go
  tests/console-backend-service/internal/mockice/mockice.go
Labels: area/core-and-supporting, bug, test-failing

#6941 Temporary disable mockice in cbs tests - bump image of cbs-tests
  resources/core/values.yaml
Labels: area/core-and-supporting, bug, test-failing

#6809 Change name of service port in minio
  resources/rafter/charts/controller-manager/charts/minio/templates/deployment.yaml
  resources/rafter/charts/controller-manager/charts/minio/templates/service.yaml
  resources/rafter/charts/controller-manager/charts/minio/templates/servicemonitor.yaml
  resources/rafter/charts/controller-manager/charts/minio/templates/statefulset.yaml
  resources/rafter/charts/controller-manager/charts/minio/templates/virtualservice.yaml
Labels: area/core-and-supporting, area/security

#6285 Add the Compass tutorial
  docs/compass/02-01-components.md
  docs/compass/02-02-flow.md
  docs/compass/04-01-compass.md
  docs/compass/08-01-tutorial.md
  docs/compass/assets/architecture.svg
  docs/compass/assets/components.svg
  docs/compass/assets/kyma-mode1.svg
  docs/compass/assets/kyma-mode2.svg
  docs/compass/assets/lambda.yaml
  docs/compass/assets/order-service-api-spec.yaml
  docs/compass/assets/order-service.yaml
Labels: area/documentation

#6953 Fix the misprints in the Compass tutorial
  docs/compass/08-01-tutorial.md
Labels: area/documentation, bug

#6828 Fix bug with Specification URL in Application Registry
  components/application-registry/internal/apperrors/apperrors.go
  components/application-registry/internal/apperrors/apperrors_test.go
  resources/application-connector/values.yaml
Labels: area/application-connector, bug

#6960 Fix bugs in APIRule CR example
  docs/api-gateway-v2/06-01-apirule.md
Labels: area/documentation

#6932 Remove add runtime to default scenario step in E2E tests
  resources/compass-runtime-agent/values.yaml
  resources/compass/charts/director/templates/deployment.yaml
  resources/compass/values.yaml
  resources/core/values.yaml
  tests/end-to-end/external-solution-integration/internal/scenario/compass_e2e.go
  tests/end-to-end/external-solution-integration/pkg/testkit/compass_director.go
  tests/end-to-end/external-solution-integration/pkg/testsuite/assign_scenario_in_compass.go
Labels: area/management-plane, enhancement

#6880 Eventing mesh dashboard pods
  components/application-operator/charts/application/templates/validator.yaml
  components/event-sources/config/500-sources-controller.yaml
  components/event-sources/reconciler/httpsource/adapter_config.go
  components/event-sources/reconciler/httpsource/reconcile.go
  components/event-sources/reconciler/httpsource/reconcile_test.go
  components/event-sources/reconciler/object/equality.go
  components/event-sources/reconciler/object/equality_test.go
  components/event-sources/reconciler/object/object.go
  components/event-sources/reconciler/object/service.go
  components/event-sources/test/fixtures/ksvc.json
Labels: area/eventing, area/monitoring

#6966 Compass tutorial improvement
  docs/compass/08-01-basic-flow-tutorial.md
Labels: area/documentation, bug

#6963 Update E2E tests image tag
  resources/compass-runtime-agent/values.yaml
  resources/core/values.yaml
Labels: enhancement

#6959 Add value for mtls gateway for Application Operator values
  components/application-operator/charts/application/values.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector

#6977 Unify backend and frontend naming in docs
  docs/console/06-02-clustermicrofrontend.md
  docs/event-bus/03-01-concepts.md
  docs/tracing/03-01-distributed-tracing.md
  docs/tracing/03-02-jaeger.md
  resources/jaeger/README.md
Labels: area/documentation

#6978 Enable stale bot for epics
  .github/stale.yml
Labels: area/community

#6976 Enable JWT strategy for API rules in Console UI
  resources/core/charts/console/templates/configmap.yaml
  resources/core/charts/console/values.yaml
Labels: area/console, enhancement

#6980 Remove incorrect installation references
  CONTRIBUTING.md
  docs/security/03-07-production-profile.md
  resources/application-connector/README.md
  resources/jaeger/README.md
Labels: area/documentation

#6947 Test simple http request to exposed minio in rafter integration tests
  tests/rafter/main_test.go
  tests/rafter/pkg/fileclient/fileclient.go
  tests/rafter/testsuite/asset.go
  tests/rafter/testsuite/assetdetails.go
  tests/rafter/testsuite/testsuite.go
Labels: area/core-and-supporting, test-missing

#6974 Issue wildcard certificates on Gardener clusters
  components/xip-patch/xip-patch.sh
  resources/xip-patch/templates/rolebindings.yaml
  resources/xip-patch/templates/roles.yaml
  resources/xip-patch/values.yaml
Labels: area/security, area/service-mesh

#6954 Test simple http request to exposed minio in rafter integration tests - image and rbacs
  resources/rafter/templates/_helper_migration_terminator.txt
  resources/rafter/templates/tests/rbac.yaml
  resources/rafter/templates/tests/test.yaml
  resources/rafter/values.yaml
Labels: area/core-and-supporting, test-missing

#6971 Migrate knative natss to knative 0.12
  resources/knative-provisioner-natss/charts/knative-provisioner-natss/templates/natss.yaml
  resources/knative-provisioner-natss/values.yaml
Labels: area/eventing

#6992 Add code ownership to knative-serving related folders for michal-hudy m00g3n aerfio magicmatatjahu
  CODEOWNERS
Labels: area/serverless, enhancement

#6997 Add migration guide caution note to upgrade documentation
  docs/kyma/04-10-upgrade.md
  docs/security/05-05-production-profile.md
Labels: area/documentation, enhancement

#6881 Added a new dashboard for participating pods in event mesh
  resources/application-connector/values.yaml
  resources/event-sources/templates/_helpers.tpl
  resources/event-sources/values.yaml
  resources/knative-eventing/README.md
  resources/knative-eventing/charts/event-mesh-dashboard/Chart.yaml
  resources/knative-eventing/charts/event-mesh-dashboard/templates/_helpers.tpl
  resources/knative-eventing/charts/event-mesh-dashboard/templates/event-mesh-pods-dashboard.yaml
  resources/knative-eventing/charts/knative-eventing/templates/eventing.yaml
  resources/knative-provisioner-natss/README.md
  resources/knative-provisioner-natss/charts/knative-provisioner-natss/templates/natss.yaml
  resources/knative-serving/README.md
  resources/knative-serving/templates/serving.yaml
Labels: area/eventing, area/monitoring

#6968 Mention the configmap mode in Rafter
  docs/rafter/01-01-rafter.md
  docs/rafter/06-01-asset.md
  docs/rafter/06-02-assetgroup.md
Labels: area/core-and-supporting, area/documentation

#7004 Add a note about README.md files from external charts
  CONTRIBUTING.md
Labels: area/documentation

#6529 Extend Compass Runtime Agent Tests with Application access test
  resources/compass-runtime-agent/templates/tests/test-runtime-agent-integration.yaml
  resources/compass-runtime-agent/values.yaml
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/README.md
  tests/compass-runtime-agent/scripts/remove_test_scenario.sh
  tests/compass-runtime-agent/scripts/run_tests.sh
  tests/compass-runtime-agent/test/runtimeagent/suite.go
  tests/compass-runtime-agent/test/runtimeagent/test/runtime_agent_test.go
  tests/compass-runtime-agent/test/testkit/assertions/events_api_access_checker.go
  tests/compass-runtime-agent/test/testkit/assertions/proxy_api_access_checker.go
  tests/compass-runtime-agent/test/testkit/compass/client.go
  tests/compass-runtime-agent/test/testkit/compass/model.go
  tests/compass-runtime-agent/test/testkit/compass/query.go
  tests/compass-runtime-agent/test/testkit/util/util.go
Labels: area/application-connector

#7019 Fix dead links
  docs/api-gateway-v2/06-01-apirule.md
Labels: area/documentation

#6985 Knative Kafka Channel Integration
  docs/event-bus/03-04-knative-eventing-mesh.md
  installation/resources/installer-cr-cluster.yaml.tpl
  resources/knative-eventing/charts/knative-eventing/templates/eventing.yaml
  resources/knative-eventing/values.yaml
  tools/kyma-installer/kyma.Dockerfile
Labels: area/eventing

#6999 Add Knative Eventing Kafka channel acceptance tests
  tests/contract/knative-channel-kafka/Dockerfile
  tests/contract/knative-channel-kafka/Gopkg.lock
  tests/contract/knative-channel-kafka/Gopkg.toml
  tests/contract/knative-channel-kafka/Makefile
  tests/contract/knative-channel-kafka/OWNERS
  tests/contract/knative-channel-kafka/README.md
  tests/contract/knative-channel-kafka/kafka_channel_test.go
Labels: area/eventing, area/serverless

#7000 Add Knative Eventing Kafka channel acceptance tests charts
  installation/resources/installer-cr-cluster.yaml.tpl
  resources/knative-eventing-channel-kafka-tests/Chart.yaml
  resources/knative-eventing-channel-kafka-tests/OWNERS
  resources/knative-eventing-channel-kafka-tests/README.md
  resources/knative-eventing-channel-kafka-tests/requirements.yaml
  resources/knative-eventing-channel-kafka-tests/templates/rbac.yaml
  resources/knative-eventing-channel-kafka-tests/templates/test.yaml
  resources/knative-eventing-channel-kafka-tests/values.yaml
Labels: area/eventing, area/serverless

#7025 Bump compass director and UI images
  resources/compass/charts/cockpit/values.yaml
  resources/compass/values.yaml
Labels: area/management-plane, enhancement

#7023 Bump compass chart
  resources/compass/charts/kyma-environment-broker/templates/app-config.yaml
  resources/compass/charts/kyma-environment-broker/templates/deployment.yaml
  resources/compass/charts/kyma-environment-broker/values.yaml
  resources/compass/templates/migrator-job.yaml
  resources/compass/values.yaml
Labels: area/management-plane

#6981 Change domain for lambdas and replace default gateways in knative-serving chart
  resources/knative-serving-init/templates/serving.yaml
  resources/knative-serving/Chart.yaml
  resources/knative-serving/templates/serving.yaml
  resources/knative-serving/values.yaml
Labels: area/core-and-supporting, area/serverless, enhancement

#7002 Add applications details view
  resources/compass/charts/cockpit/templates/compass-apps-microfrontend.yaml
  resources/core/charts/console/values.yaml
Labels: area/console, enhancement

#6951 Permission-controller documentation
  components/permission-controller/Makefile
  components/permission-controller/README.md
  docs/security/01-01-security.md
  docs/security/03-05-roles-in-kyma.md
  docs/security/03-08-permission-controller.md
  docs/security/05-05-permission-controller.md
  resources/core/charts/cluster-users/templates/rbac-roles.yaml
  resources/core/charts/cluster-users/values.yaml
  resources/permission-controller/README.md
  resources/permission-controller/templates/deployment.yaml
  resources/permission-controller/values.yaml
  resources/uaa-activator/templates/secret.yaml
  resources/uaa-activator/values.yaml
Labels: area/documentation, area/security, enhancement

#7039 Update backup docs with correct priority of resources
  docs/backup/08-02-restore-backup.md
Labels: area/documentation, enhancement

#7059 Update function-controller to use newest stable tekton version
  components/function-controller/go.mod
  components/function-controller/go.sum
  components/function-controller/pkg/controllers/function/function_controller_test.go
  components/function-controller/pkg/utils/build_utils.go
Labels: area/serverless, enhancement

#7072 Present legacy connector URL in compass
  resources/compass/charts/cockpit/values.yaml
Labels: area/management-plane, enhancement

#7032 Compass tenant loader job
  resources/compass/charts/director/templates/configmap-default-tenant-config.yaml
  resources/compass/charts/director/templates/tenant-loader-job.yaml
  resources/compass/templates/tenant-fetcher-job.yaml
  resources/compass/templates/tenant-fetcher-secret.yaml
  resources/compass/values.yaml
Labels: area/management-plane

#7077 Handle cloudsql-proxy on tenant loader and tenant fetcher
  resources/compass/charts/director/templates/tenant-loader-job.yaml
  resources/compass/templates/tenant-fetcher-job.yaml
Labels: area/management-plane
