Repository kyma-project/kyma, pull requests merged in 2021-09, with the labels that each got.

#11644 Grafana oauth test
  tests/fast-integration/monitoring-test/.env.template
  tests/fast-integration/monitoring-test/grafana-test.js
  tests/fast-integration/monitoring/client.js
  tests/fast-integration/monitoring/helpers.js
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#12007 Add azure service broker image swap webhook
  resources/helm-broker/templates/webhook-deployment.yaml
  resources/helm-broker/templates/webhook-register.yaml
  resources/helm-broker/templates/webhook-service.yaml
  resources/helm-broker/values.yaml
Labels: size/L, lgtm

#11990 xip.io to nip.io change #11924
  components/function-controller/internal/docker/registry_test.go
  components/xip-patch/README.md
  components/xip-patch/xip-patch.sh
  docs/kyma/04-03-cluster-installation.md
  docs/kyma/10-03-network-error.md
  docs/monitoring/08-03-create-and-configure-grafana-dashboard.md
  docs/runtime-agent/06-01-runtime-agent-compass-connection.md
  docs/security/03-04-ingress-egress-traffic.md
  docs/security/08-02-update-tls-certificates.md
  milv.config.yaml
  resources/apiserver-proxy/charts/apiserver-proxy-init/files/generate-certs.sh
  resources/apiserver-proxy/values.yaml
  resources/core/values.yaml
  resources/xip-patch/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/values.yaml
Labels: size/M, lgtm

#11991 Troubleshooting guides update
  docs/04-operation-guides/troubleshooting/apix-02-dns-mgt-connection-refused.md
  docs/04-operation-guides/troubleshooting/apix-03-dns-mgt-could-not-resolve-host.md
  docs/04-operation-guides/troubleshooting/apix-04-dns-mgt-resource-ignored.md
  docs/04-operation-guides/troubleshooting/apix-05-cert-mgt-issuer-not-created.md
Labels: area/documentation, area/api-gateway, size/M, lgtm

#12008 Backport gitv2 bump
  resources/serverless/values.yaml
Labels: size/S, lgtm

#12012 Make allowlist for API-Gateway disabled as default
  docs/api-gateway/03-02-whitelisted-domains.md
  resources/api-gateway/values.yaml
Labels: size/XS, lgtm

#11983 upgrade to fluent-bit 1.8
  resources/logging/charts/fluent-bit/templates/configmap.yaml
  resources/logging/charts/fluent-bit/values.yaml
  resources/telemetry/charts/fluent-bit/values.yaml
Labels: area/logging, size/S, lgtm

#11984 made kubelet alert rule resilient to muliple kubelet scrapeconfigs
  resources/monitoring/templates/prometheus/rules-1.14/kubelet.rules.yaml
Labels: size/XS, lgtm

#11993 Rely on OAuth2Client CR in the Helm chart
  components/eventing-controller/Makefile
  components/eventing-controller/config/crd/external/README.md
  components/eventing-controller/config/crd/external/hydra.ory.sh_oauth2clients.yaml
  components/eventing-controller/config/rbac/role.yaml
  components/eventing-controller/go.mod
  components/eventing-controller/pkg/commander/beb/beb.go
  components/eventing-controller/pkg/deployment/oauth2client_cr.go
  components/eventing-controller/pkg/object/equality.go
  components/eventing-controller/reconciler/backend/reconciler.go
  components/eventing-controller/reconciler/backend/reconciler_test.go
  resources/eventing/charts/controller/templates/clusterrole.yaml
  resources/eventing/charts/controller/templates/oauth2-client.yaml
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, size/L, lgtm

#12018 Bump alpine base for minio tests
  tests/rafter/Dockerfile
Labels: size/XS, lgtm

#12013 Adapt Istio Docu regarding Prometheus mTLS
  docs/01-overview/main-areas/observability/obsv-03-istio-monitoring.md
  docs/03-tutorials/00-observability/obsv-01-observe-application-metrics.md
Labels: size/M, lgtm

#12019 Bump kaniko executer
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#12020 bump nodejs runtimes for serverless
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
Labels: size/S, lgtm

#12022 Fix a broken link
  docs/tracing/10-01-traces-troubleshooting.md
Labels: bug, area/documentation, size/XS, lgtm

#12036 Update Kyma version to 1.24.6
  VERSION
  installation/resources/installer.yaml
Labels: size/XS, lgtm

#11976 Apply new defaults for kyma 2
  installation/resources/values.yaml
  resources/helm-broker/values.yaml
  resources/kiali/values.yaml
  resources/logging/values.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/tracing/values.yaml
Labels: size/M, lgtm

#12042 Fix webhookauth
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/pkg/handlers/utils.go
  components/eventing-controller/pkg/handlers/utils_test.go
  components/eventing-controller/testing/test_helpers.go
Labels: size/L, lgtm

#12028 security update of several images
  resources/kiali/values.yaml
  resources/logging/charts/fluent-bit/values.yaml
  resources/logging/charts/loki/values.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/monitoring/charts/prometheus-node-exporter/values.yaml
  resources/tracing/values.yaml
Labels: area/monitoring, area/logging, size/S, lgtm

#12044 Have a default value if env var is not defined
  tests/fast-integration/monitoring-test/grafana-test.js
  tests/fast-integration/utils/index.js
Labels: size/S, lgtm

#12024 bump tags for serverless chart
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#12006 Fix event multiplexer pattern for NATS
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, size/L, lgtm

#12025 bump rafter image tags
  resources/rafter/values.yaml
Labels: size/XS, lgtm

#12046 Bump image
  resources/eventing/charts/controller/values.yaml
Labels: size/XS, lgtm

#12045 Cleanup the code referring to the OAuth usage in BEB subscriptions
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/pkg/handlers/utils.go
  components/eventing-controller/pkg/handlers/utils_test.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, size/S, lgtm

#12034 Update secret-migration script (#11700)
  resources/ory/files/secret-migration.sh
Labels: size/XS, lgtm

#12043 Update Prometheus Alertmanager to Version 0.23.0
  resources/monitoring/values.yaml
Labels: area/monitoring, size/XS, lgtm

#12047 [cluster-users tests] fix bug during token fetch caused by assumed ordering of url fragments
  tests/integration/cluster-users/oidc_token_fetcher/main.go
Labels: size/S, lgtm

#12049 Add cosign step to remaining Kyma components
  components/console-backend-service/Makefile
  components/dex-static-user-configurer/Makefile
  components/function-runtimes/Makefile
  components/istio-installer/Makefile
  components/xip-patch/Makefile
Labels: size/M, lgtm

#12053 Add cosign step to components
  components/function-controller/Makefile
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/nats-operator/Makefile
Labels: size/M, lgtm

#12055 kiali not working with istio 1.11 - update kiali to 1.38.1
  resources/kiali/templates/role-viewer.yaml
  resources/kiali/templates/role.yaml
  resources/kiali/values.yaml
Labels: bug, priority/critical, area/service-mesh, size/M, lgtm

#12065 fixed jaeger integration for kiali
  resources/kiali/values.yaml
Labels: size/XS, lgtm

#12064 backport Kiali 1.38.1 to kyma 1.24
  resources/kiali/templates/_helpers.tpl
  resources/kiali/templates/configmap.yaml
  resources/kiali/templates/deployment.yaml
  resources/kiali/templates/hpa.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-configmap.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-secret.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-service.yaml
  resources/kiali/templates/kyma-additions/clustermicrofrontend.yaml
  resources/kiali/templates/kyma-additions/peerauthentication.yaml
  resources/kiali/templates/kyma-additions/servicemonitor.yaml
  resources/kiali/templates/kyma-additions/virtualservice.yaml
  resources/kiali/templates/role-viewer.yaml
  resources/kiali/templates/role.yaml
  resources/kiali/templates/service.yaml
  resources/kiali/values.yaml
Labels: size/XL, lgtm

#12016 SKR migration test prints job logs
  tests/fast-integration/package-lock.json
  tests/fast-integration/package.json
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
  tests/fast-integration/utils/index.js
Labels: size/XXL, lgtm

#12023 SKR migration test improve log messages
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
Labels: size/M, lgtm

#12057 Clean up the Operation Guides
  components/application-broker/README.md
  components/function-runtimes/README.md
  docs/01-overview/main-areas/api-exposure/apix-01-api-gateway.md
  docs/01-overview/main-areas/application-connectivity/ac-04-security.md
  docs/01-overview/main-areas/service-mesh/smsh-01-details.md
  docs/03-tutorials/00-api-exposure/apix-03-config-authorizations-apigateway.md
  docs/03-tutorials/00-api-exposure/assets/function.yaml
  docs/03-tutorials/00-serverless/svls-03-expose-function.md
  docs/03-tutorials/00-service-management/smgt-14-hb-create-addons-repo.md
  docs/03-tutorials/01-develop-service-local-no-docker-kyma.md
  docs/03-tutorials/02-publish-service-image-and-deploy-kyma.md
  docs/03-tutorials/03-set-up-idp.md
  docs/04-operation-guides/README.md
  docs/04-operation-guides/operations/README.md
  docs/04-operation-guides/troubleshooting/apix-01-apigateway-connect-api-rule.md
  docs/04-operation-guides/troubleshooting/smsh-01-503-no-access.md
  docs/04-operation-guides/troubleshooting/troubleshoot-volume-backup.md
  docs/05-technical-reference/00-architecture/ac-01-application-connector-components.md
  docs/05-technical-reference/00-architecture/ac-04-application-broker.md
  docs/05-technical-reference/00-architecture/apix-01-architecture-apigateway.md
  docs/05-technical-reference/00-architecture/assets/apix-api-gateway-flow.svg
  docs/05-technical-reference/00-architecture/assets/apix-api-gateway-request-flow.svg
  docs/05-technical-reference/00-architecture/obsv-01-architecture-monitoring.md
  docs/05-technical-reference/00-architecture/obsv-03-architecture-tracing.md
  docs/05-technical-reference/00-architecture/smgt-10-hb.md
  docs/05-technical-reference/00-configuration-parameters/ac-02-application-operator-sub-chart.md
  docs/05-technical-reference/00-configuration-parameters/obsv-01-configpara-alertmanager.md
  docs/05-technical-reference/00-configuration-parameters/obsv-02-configpara-grafana.md
  docs/05-technical-reference/00-configuration-parameters/obsv-03-configpara-prometheus.md
  docs/05-technical-reference/00-configuration-parameters/obsv-11-configpara-logging.md
  docs/05-technical-reference/00-configuration-parameters/obsv-21-configpara-tracing.md
  docs/05-technical-reference/00-configuration-parameters/obsv-31-configpara-kiali.md
  docs/05-technical-reference/00-configuration-parameters/ra-01-connection-with-compass.md
  docs/05-technical-reference/00-configuration-parameters/smgt-01-sc-catalog-subchart.md
  docs/05-technical-reference/00-configuration-parameters/smgt-02-sc-podpreset-subchart.md
  docs/05-technical-reference/00-configuration-parameters/smgt-03-hb-chart.md
  docs/05-technical-reference/00-configuration-parameters/smgt-04-hb-etcd-subchart.md
  docs/05-technical-reference/00-configuration-parameters/svls-01-serverless-chart.md
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
  docs/05-technical-reference/00-custom-resources/metadata.yaml
  docs/05-technical-reference/00-custom-resources/smgt-01-sc-sbu.md
  docs/05-technical-reference/00-custom-resources/smgt-02-sc-usage-kind.md
  docs/05-technical-reference/00-custom-resources/smgt-03-hb-clusteraddonsconfiguration.md
  docs/05-technical-reference/00-custom-resources/smgt-04-hb-addonsconfiguration.md
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  docs/05-technical-reference/00-custom-resources/svls-02-gitrepository.md
  docs/05-technical-reference/ac-02-application-gateway-details.md
  docs/05-technical-reference/svls-01-sample-functions.md
  docs/05-technical-reference/svls-02-function-processing-stages.md
  docs/05-technical-reference/svls-04-git-source-type.md
  docs/05-technical-reference/svls-05-exposing-functions.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
  docs/05-technical-reference/svls-07-supported-webhooks.md
  docs/05-technical-reference/svls-09-available-presets.md
  docs/glossary.md
  resources/core/README.md
  resources/iam-kubeconfig-service/README.md
  resources/service-catalog-addons/README.md
Labels: area/documentation, size/L, lgtm

#12050 Reconcile Kyma subscription if APIRule is updated/deleted
  components/eventing-controller/config/rbac/role.yaml
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/reconciler/subscription/reconciler.go
  components/eventing-controller/reconciler/subscription/reconciler_test.go
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, size/L, lgtm

#12072 Clean up the Operation Guides pt.2
  docs/04-operation-guides/troubleshooting/01-installation-troubleshooting.md
  docs/04-operation-guides/troubleshooting/troubleshoot-03-installation-troubleshooting.md
  docs/04-operation-guides/troubleshooting/troubleshoot-05-common-errors.md
Labels: area/documentation, size/L, lgtm

#12069 Bump nodejs build base images
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
Labels: size/XS, lgtm

#12054 Bump busybox
  resources/monitoring/charts/grafana/values.yaml
  resources/ory/charts/hydra/values.yaml
  resources/ory/charts/oathkeeper/values.yaml
  resources/telemetry/charts/fluent-bit/values.yaml
Labels: size/XS, lgtm

#12061 Assert proper oidc config in kubeconfig from KEB
  tests/fast-integration/kyma-environment-broker/client.js
  tests/fast-integration/kyma-environment-broker/helpers.js
  tests/fast-integration/skr-test/skr-test.js
Labels: size/M, lgtm

#12076 Update serverless nodejs image tags
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#12063 Add "check-code" for local publisher-proxy development
  components/event-publisher-proxy/Makefile
  components/event-publisher-proxy/README.md
Labels: area/eventing, size/S, lgtm

#12027 Used axiosRetry to have a stable Commerce Mock Loki test
  tests/fast-integration/logging/client.js
  tests/fast-integration/monitoring/client.js
  tests/fast-integration/utils/index.js
Labels: size/M, lgtm

#12070 Update codeowners for Huskies
  CODEOWNERS
Labels: size/S, lgtm

#12059 SKR migration test check env variables in function pods
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#12079 Fix the `serverless-long` test
  resources/serverless/templates/tests/long-test.yaml
  resources/serverless/values.yaml
Labels: area/serverless, test-failing, size/S, lgtm

#12081 Fix nats operator release-1.24.6
  components/nats-operator/cmd/nats-operator/Dockerfile
Labels: area/eventing, size/XS, lgtm

#12075 Fix nats-operator
  components/nats-operator/cmd/nats-operator/Dockerfile
  resources/eventing/charts/nats/values.yaml
Labels: area/eventing, size/XS, lgtm

#12086 Switched to official commerce-mock-lite mock for testing
  tests/fast-integration/logging/helpers.js
  tests/fast-integration/test/fixtures/commerce-mock/commerce-mock.yaml
Labels: size/S, lgtm

#12085 Extend existing in-cluster eventing test in fast-integration
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
Labels: area/eventing, size/M, lgtm

#12088 Bump TPI images with signed ones
  resources/rafter/charts/upload-service/values.yaml
  resources/rafter/values.yaml
  resources/serverless/charts/docker-registry/values.yaml
  resources/tracing/values.yaml
Labels: size/S, lgtm

#12087 Bump nats-operator-1.24 image to 775123fa
  resources/eventing/charts/nats/values.yaml
Labels: area/eventing, size/XS, lgtm

#12083 have lokis removeKeys attribute overridable
  resources/logging/charts/fluent-bit/templates/_helpers.tpl
  resources/logging/charts/fluent-bit/templates/configmap.yaml
  resources/logging/charts/fluent-bit/values.yaml
Labels: area/logging, size/S, lgtm

#12091 Fixxed smal Docu mistakes
  docs/03-tutorials/00-observability/obsv-01-observe-application-metrics.md
Labels: size/S, lgtm

#12089 Bump etcd image with a signed one
  resources/helm-broker/charts/etcd-stateful/values.yaml
Labels: size/XS, lgtm

#12090 Bump octopus image with a signed one
  resources/testing/values.yaml
Labels: size/XS, lgtm

#12066 Rename ports to comply with Istio naming convention
  resources/eventing/charts/controller/templates/service.yaml
  resources/eventing/charts/publisher-proxy/templates/service.yaml
  resources/eventing/charts/publisher-proxy/values.yaml
  resources/eventing/values.yaml
Labels: size/S, lgtm

#12082 Bump images with signed ones
  resources/api-gateway/values.yaml
  resources/cluster-essentials/charts/pod-preset/values.yaml
  resources/cluster-essentials/values.yaml
Labels: size/S, lgtm

#12092 authproxy must not forward host header for istio routing
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/kiali/values.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/values.yaml
Labels: bug, area/service-mesh, area/tracing, size/XS, lgtm

#12094 Update Install Kyma doc
  docs/04-operation-guides/operations/01-install-kyma.md
Labels: size/S, lgtm

#12078 Upgrade nats-server to 2.2.4
  resources/eventing/charts/nats/templates/40-cr.yaml
Labels: area/eventing, size/XS, lgtm

#12096 Bump base images and versions for rafter and serverless
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
  resources/rafter/values.yaml
  resources/serverless/values.yaml
  tests/rafter/Dockerfile
Labels: size/S, lgtm

#12103 Adapted to new service name
  docs/03-tutorials/00-observability/obsv-01-observe-application-metrics.md
Labels: size/S, lgtm

#11858 Change Prometheus to match all rules and test that all applied PrometheusRules are registered
  resources/logging/charts/fluent-bit/templates/kyma-additions/fluent-bit.rules.yaml
  resources/monitoring/values.yaml
  tests/fast-integration/monitoring-test/monitoring-test.js
  tests/fast-integration/monitoring/helpers.js
  tests/fast-integration/package.json
  tests/fast-integration/telemetry-test/telemetry-test.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#12106 1656 remove sb
  tests/fast-integration/skr-svcat-migration-test/deploy-sample-resources.js
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_inst-sb_auditlog.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_inst-sb_auditlogmanagement.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_inst-sb_html5appsrepo.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_inst-sb_redis.yaml
Labels: size/M, lgtm

#12107 Fix typos and increase job timeout in SKR migration test
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
  tests/fast-integration/utils/index.js
Labels: size/XS, lgtm

#12098 update Observability tech references
  docs/01-overview/main-areas/observability/README.md
  docs/01-overview/main-areas/observability/assets/distributed-tracing.svg
  docs/01-overview/main-areas/observability/obsv-03-istio-monitoring.md
  docs/01-overview/main-areas/observability/obsv-10-useful-links.md
  docs/05-technical-reference/00-configuration-parameters/README.md
  docs/05-technical-reference/00-configuration-parameters/obsv-01-configpara-alertmanager.md
  docs/05-technical-reference/00-configuration-parameters/obsv-01-configpara-observability.md
  docs/05-technical-reference/00-configuration-parameters/obsv-02-configpara-grafana.md
  docs/05-technical-reference/00-configuration-parameters/obsv-03-configpara-prometheus.md
  docs/05-technical-reference/00-configuration-parameters/obsv-11-configpara-logging.md
  docs/05-technical-reference/00-configuration-parameters/obsv-21-configpara-tracing.md
  docs/05-technical-reference/00-configuration-parameters/obsv-31-configpara-kiali.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/other-tracing-benefits-of-distributed-tracing.md
  docs/05-technical-reference/other-tracing-envoy-http-headers.md
Labels: area/documentation, area/monitoring, area/tracing, area/logging, size/L, lgtm

#12102 Fix Cloud Event (Binary Content Mode) processing for NATS backend ( release 1.24.6 )
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
Labels: area/eventing, size/XS, lgtm

#12114 Bump images for eventing 1.24.6
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, size/XS, lgtm

#12115 Move in-cluster eventing sub-test to the fixture
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: area/eventing, size/S, lgtm

#12109 Delete BTP operator migrated resources in SKR test
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
  tests/fast-integration/utils/index.js
Labels: size/M, lgtm

#12117 Enhanced Monitoring Doc with some small details
  docs/01-overview/main-areas/observability/obsv-03-istio-monitoring.md
Labels: size/XS, lgtm

#12084 Remove Helm hook annotations from cluster essentials resources
  resources/cluster-essentials/templates/priorityclass.yaml
  resources/cluster-essentials/templates/psp-privileged.yaml
  resources/cluster-essentials/templates/psp-unprivileged.yaml
  resources/cluster-essentials/templates/rbac-clusterrole.yaml
  resources/cluster-essentials/templates/rbac-clusterrolebinding.yaml
Labels: size/M, lgtm

#12104 Update the Get Started guides for Kyma 2.0
  docs/01-overview/main-areas/eventing/evnt-02-useful-links.md
  docs/01-overview/main-areas/service-mesh/smsh-01-details.md
  docs/02-get-started/00-task-debug-function-w-CLI.md
  docs/02-get-started/00-task-provision-cluster.md
  docs/02-get-started/01-overview.md
  docs/02-get-started/01-quick-install.md
  docs/02-get-started/02-create-namespace.md
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/02-get-started/03-deploy-microservice.md
  docs/02-get-started/04-expose-microservice.md
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/02-get-started/05-add-redis-service.md
  docs/02-get-started/05-observability.md
  docs/02-get-started/06-create-redis-service-instance.md
  docs/02-get-started/07-bind-redis-service-to-microservice.md
  docs/02-get-started/08-connect-external-application.md
  docs/02-get-started/09-trigger-microservice-with-event.md
  docs/02-get-started/10-create-function.md
  docs/02-get-started/11-expose-function.md
  docs/02-get-started/12-bind-redis-service-to-function.md
  docs/02-get-started/13-trigger-function-with-event.md
  docs/02-get-started/16-01-try-out-kyma.md
  docs/02-get-started/README.md
  docs/02-get-started/assets/order-flow.svg
  docs/02-get-started/assets/orders-service-openapi.yaml
  docs/02-get-started/metadata.yaml
  docs/03-tutorials/00-api-exposure/apix-04-own-domain.md
  docs/03-tutorials/01-develop-service-local-no-docker-kyma.md
  docs/04-operation-guides/operations/01-install-kyma-CLI.md
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/operations/05-upgrade-kyma.md
  docs/04-operation-guides/troubleshooting/apix-01-apigateway-connect-api-rule.md
  docs/04-operation-guides/troubleshooting/cli-01-debugger-stops-at-dependency.md
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
  milv.config.yaml
  resources/core/README.md
  resources/monitoring/README.md
Labels: area/documentation, size/XXL, lgtm

#12113 Cherry-pick #12085 #12115 (add binary mode to in-cluster eventing test)
  tests/fast-integration/test/2-commerce-mock.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
Labels: area/eventing, size/M, lgtm

#12112 bump istio-installer 1.11.1 -> 1.11.2
  components/istio-installer/Dockerfile
Labels: size/XS, lgtm

#12111 fix/dex deployment with k8s 1.21
  resources/dex/templates/dex-deployment.yaml
Labels: size/XS, lgtm

#12121 Update API Exposure area docu
  docs/01-overview/main-areas/api-exposure/apix-02-useful-links.md
  docs/03-tutorials/00-api-exposure/apix-01-expose-service-apigateway.md
  docs/03-tutorials/00-api-exposure/apix-02-expose-and-secure-service.md
  docs/03-tutorials/00-api-exposure/apix-03-own-domain.md
  docs/04-operation-guides/troubleshooting/apix-02-dns-mgt-connection-refused.md
  docs/04-operation-guides/troubleshooting/apix-03-dns-mgt-could-not-resolve-host.md
  docs/05-technical-reference/00-architecture/assets/apix-api-gateway-request-flow.svg
  docs/05-technical-reference/apix-01-config-authorizations-apigateway.md
  docs/05-technical-reference/apix-02-whitelisted-domains.md
  docs/05-technical-reference/apix-03-blacklisted-services.md
Labels: area/documentation, area/api-gateway, size/M, lgtm

#12110 Introduce Liveness Probe
  components/function-controller/internal/controllers/serverless/build_resources.go
  components/function-controller/internal/controllers/serverless/deployment.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  resources/serverless/values.yaml
Labels: size/M, lgtm

#12123 Fix/add dns annotation
  resources/istio-configuration/templates/istio-operator.yaml
Labels: size/XS, lgtm

#12124 Document unhealthy status
  docs/serverless/03-08-function-processing.md
  docs/serverless/06-01-function-cr.md
  docs/serverless/assets/running.svg
Labels: size/XS, lgtm

#12125 Document unhealthy status
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  docs/05-technical-reference/assets/svls-running.svg
  docs/05-technical-reference/svls-02-function-processing-stages.md
Labels: size/XS, lgtm

#11994 Enable Prometheus scraping using mTLS
  components/event-publisher-proxy/config/event-publisher-nats/120-peerauthentication.yaml
  resources/eventing/charts/controller/templates/peerauthentication.yaml
  resources/eventing/charts/controller/templates/servicemonitor.yaml
  resources/eventing/charts/publisher-proxy/templates/peerauthentication.yaml
  resources/eventing/charts/publisher-proxy/templates/servicemonitor.yaml
  resources/kiali/templates/kyma-additions/peerauthentication.yaml
  resources/logging/charts/fluent-bit/templates/kyma-additions/peerauthentication.yaml
  resources/logging/charts/fluent-bit/templates/servicemonitor.yaml
  resources/logging/charts/loki/templates/kyma-additions/peerauthentication.yaml
  resources/logging/charts/loki/templates/servicemonitor.yaml
  resources/monitoring/charts/grafana/templates/policy.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/monitoring/charts/prometheus-istio/templates/servicemonitor.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/kyma-additions/policy.yaml
  resources/monitoring/extractmetrics.sh
  resources/monitoring/templates/exporters/kube-state-metrics/serviceMonitor.yaml
  resources/monitoring/templates/grafana/servicemonitor.yaml
  resources/monitoring/templates/prometheus-operator/servicemonitor.yaml
  resources/monitoring/values.yaml
  resources/ory/templates/monitoring-hydra.yaml
  resources/ory/templates/monitoring-oathkeeper.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/policy.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/service-monitor.yaml
  resources/service-catalog/charts/catalog/templates/controller-manager-service-monitor.yaml
  resources/tracing/templates/kyma-additions/metrics-policies.yaml
  resources/tracing/templates/kyma-additions/metrics-servicemonitor.yaml
Labels: size/L, lgtm

#12127 bump istio 1.11.1 -> 1.11.2 in istio component
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: size/XS, lgtm

#12128 Update the Get Started guides for Kyma 2.0, pt.2
  docs/02-get-started/01-quick-install.md
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/02-get-started/05-observability.md
Labels: area/documentation, size/M, lgtm

#12120 bump istio 1.11.1 -> 1.11.2
  resources/istio-configuration/Chart.yaml
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: size/S, lgtm

#12116 Fix fast integration tests with central app gateway failing
  tests/fast-integration/Makefile
  tests/fast-integration/compass-test/compass-test.js
  tests/fast-integration/package.json
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/test/2-getting-started-guides.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: bug, area/application-connector, size/M, lgtm

#12139 bump istio-installer to 1.11.2
  components/istio-installer/Dockerfile
Labels: size/XS, lgtm

#12143 Switch serverless to TPI kaniko-executer image
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#12145 [release-1.24] Switch serverless to TPI kaniko-executer image
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#12133 updated fluent-bit to 1.8.7
  resources/logging/charts/fluent-bit/values.yaml
Labels: area/logging, size/XS, lgtm

#12148 Migrate Application Connector requirements.yaml to Chart.yaml
  resources/application-connector/Chart.yaml
  resources/application-connector/requirements.yaml
Labels: area/application-connector, area/quality, size/S, lgtm

#12153 Reduce mem limit for build profile
  docs/05-technical-reference/svls-09-available-presets.md
Labels: size/XS, lgtm

#12149 Update MILV config file for Kyma 2.0
  milv.config.yaml
Labels: size/S, lgtm

#12122 Simplify the tutorials
  docs/01-overview/main-areas/api-exposure/apix-02-useful-links.md
  docs/03-tutorials/00-api-exposure/apix-01-expose-service-apigateway.md
  docs/03-tutorials/00-api-exposure/apix-01-own-domain.md
  docs/03-tutorials/00-api-exposure/apix-02-expose-service-apigateway.md
  docs/03-tutorials/00-api-exposure/apix-03-expose-and-secure-service.md
  docs/03-tutorials/00-api-exposure/apix-03-own-domain.md
Labels: area/documentation, area/api-gateway, size/XL, lgtm

#12152 Reduce mem limit for build profile
  docs/serverless/03-06-available-presets.md
  resources/serverless/charts/webhook/values.yaml
Labels: size/XS, lgtm

#12131 Fixes for Eventing K.2.0 docs
  docs/03-tutorials/00-eventing/evnt-01-setup-in-cluster-eventing.md
  docs/05-technical-reference/00-architecture/evnt-01-architecture.md
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
Labels: size/S, lgtm

#12150 add eventing-specific integration tests
  tests/fast-integration/Makefile
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/package.json
Labels: size/M, lgtm

#12167 Bump alpine
  components/apiserver-proxy/Dockerfile
  components/iam-kubeconfig-service/Dockerfile
Labels: size/XS, lgtm

#12169 simplify observability diagrams
  docs/01-overview/main-areas/assets/kyma-areas.svg
  docs/01-overview/main-areas/observability/obsv-10-useful-links.md
  docs/01-overview/main-areas/service-mesh/smsh-02-default-istio-setup-in-kyma.md
  docs/02-get-started/05-observability.md
  docs/03-tutorials/00-observability/obsv-02-create-and-configure-grafana-dashboard.md
  docs/04-operation-guides/security/assets/obsv-access-services.svg
  docs/04-operation-guides/security/sec-06-access-expose-kiali-grafana.md
  docs/05-technical-reference/00-architecture/assets/obsv-kiali-architecture.svg
  docs/05-technical-reference/00-architecture/assets/obsv-tracing-architecture.svg
  docs/05-technical-reference/00-architecture/obsv-01-architecture-monitoring.md
  docs/05-technical-reference/00-architecture/obsv-02-architecture-logging.md
  docs/05-technical-reference/00-architecture/obsv-03-architecture-tracing.md
  docs/05-technical-reference/00-architecture/obsv-04-architecture-kiali.md
Labels: area/documentation, area/tracing, size/M, lgtm

#12173 Nats-operator image 1.24.6: upgrade to alpine:3.14.2
  components/nats-operator/cmd/nats-operator/Dockerfile
Labels: bug, priority/critical, area/eventing, size/XS, lgtm

#12170 Nats-operator image: upgrade to alpine:3.14.2
  components/nats-operator/cmd/nats-operator/Dockerfile
  resources/eventing/charts/nats/values.yaml
Labels: bug, priority/critical, area/eventing, size/XS, lgtm

#12175 Bump build image of Application Operator
  components/application-operator/Dockerfile
Labels: size/XS, lgtm

#12180 Bump nats-operator image to c33012c2
  resources/eventing/charts/nats/values.yaml
Labels: bug, priority/critical, area/eventing, size/XS, lgtm

#12176 Bump libgit2 to 1.1.1-r2 in function controller
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
Labels: size/S, lgtm

#12155 Add Service Management 2.0 documentation
  components/application-broker/README.md
  components/application-operator/README.md
  docs/01-overview/main-areas/service-management/assets/aws-class.png
  docs/01-overview/main-areas/service-management/assets/azure-service-broker-class.png
  docs/01-overview/main-areas/service-management/assets/gcp-class.png
  docs/01-overview/main-areas/service-management/smgt-01-overview.md
  docs/01-overview/main-areas/service-management/smgt-01-sc-overview.md
  docs/01-overview/main-areas/service-management/smgt-02-brokers-overview.md
  docs/01-overview/main-areas/service-management/smgt-03-sc-resources.md
  docs/01-overview/main-areas/service-management/smgt-10-hb-overview.md
  docs/01-overview/main-areas/service-management/smgt-99-useful-links.md
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/03-tutorials/00-api-exposure/apix-02-expose-service-apigateway.md
  docs/03-tutorials/00-application-connectivity/ac-06-service-mapping.md
  docs/03-tutorials/00-serverless/svls-03-expose-function.md
  docs/03-tutorials/00-service-management/README.md
  docs/03-tutorials/00-service-management/assets/binding.svg
  docs/03-tutorials/00-service-management/assets/deprovisioning.svg
  docs/03-tutorials/00-service-management/assets/hb-provisioning.svg
  docs/03-tutorials/00-service-management/assets/provisioning-and-binding.svg
  docs/03-tutorials/00-service-management/assets/provisioning.svg
  docs/03-tutorials/00-service-management/assets/unbinding-deprovisioning.svg
  docs/03-tutorials/00-service-management/assets/unbinding.svg
  docs/03-tutorials/00-service-management/assets/usagekind.svg
  docs/03-tutorials/00-service-management/metadata.yaml
  docs/03-tutorials/00-service-management/smgt-01-sc-provisioning.md
  docs/03-tutorials/00-service-management/smgt-02-sc-deprovisioning.md
  docs/03-tutorials/00-service-management/smgt-03-sc-broker-registration.md
  docs/03-tutorials/00-service-management/smgt-11-hb-create-addons.md
  docs/03-tutorials/00-service-management/smgt-12-hb-bind-addons.md
  docs/03-tutorials/00-service-management/smgt-13-hb-test-addons.md
  docs/03-tutorials/00-service-management/smgt-14-hb-create-addons-repo.md
  docs/03-tutorials/00-service-management/smgt-15-hb-check-addons.md
  docs/03-tutorials/00-service-management/smgt-16-hb-register-addons-sc.md
  docs/03-tutorials/00-service-management/smgt-17-hb-provision-addons-sc.md
  docs/03-tutorials/03-set-up-idp.md
  docs/04-operation-guides/security/sec-02-authorization-in-kyma.md
  docs/04-operation-guides/troubleshooting/apix-01-apigateway-connect-api-rule.md
  docs/04-operation-guides/troubleshooting/apix-02-dns-mgt-connection-refused.md
  docs/04-operation-guides/troubleshooting/apix-03-dns-mgt-could-not-resolve-host.md
  docs/04-operation-guides/troubleshooting/smgt-01-instance-failed-status.md
  docs/04-operation-guides/troubleshooting/smgt-02-id-conflict.md
  docs/05-technical-reference/00-architecture/obsv-03-architecture-tracing.md
  docs/05-technical-reference/00-architecture/smgt-01-sc.md
  docs/05-technical-reference/00-architecture/smgt-10-hb.md
  docs/05-technical-reference/00-architecture/smgt-11-hb-deep-dive.md
  docs/05-technical-reference/00-configuration-parameters/smgt-01-sc-catalog-subchart.md
  docs/05-technical-reference/00-configuration-parameters/smgt-02-sc-podpreset-subchart.md
  docs/05-technical-reference/00-configuration-parameters/smgt-03-hb-chart.md
  docs/05-technical-reference/00-configuration-parameters/smgt-04-hb-etcd-subchart.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/smgt-01-sc-sbu.md
  docs/05-technical-reference/00-custom-resources/smgt-02-sc-usage-kind.md
  docs/05-technical-reference/00-custom-resources/smgt-03-hb-clusteraddonsconfiguration.md
  docs/05-technical-reference/00-custom-resources/smgt-04-hb-addonsconfiguration.md
  docs/05-technical-reference/assets/service-catalog-flow.svg
  docs/05-technical-reference/ra-01-configuring-runtime.md
  resources/service-catalog-addons/README.md
Labels: area/documentation, area/service-catalog, size/XXL, lgtm

#12182 Make charts installable with helm template
  resources/api-gateway/templates/monitoring.yaml
  resources/ory/templates/hydra-virtualservice.yaml
Labels: size/XS, lgtm

#12177 Update Kyma version to 1.24.7
  VERSION
  installation/resources/installer.yaml
Labels: size/XS, lgtm

#12187 Add a note to the SM2.0 docs
  docs/01-overview/main-areas/service-management/smgt-01-overview.md
Labels: area/documentation, size/XS, lgtm

#12074 Fix: Do not override host header
  components/application-gateway/internal/proxy/proxyfactory.go
Labels: size/XS, lgtm

#12163 Added backend switching logic in fast-integration and added eventing tests with Event Mesh
  tests/fast-integration/Makefile
  tests/fast-integration/README.md
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#12179 Bump k8s-tools on release 1.24
  components/dex-static-user-configurer/Dockerfile
  components/istio-installer/Dockerfile
  components/istio-installer/README.md
  components/xip-patch/Dockerfile
  docs/kyma/03-03-charts.md
  docs/kyma/08-04-create-volume-snapshots.md
  docs/kyma/10-08-cant-download-img.md
  resources/api-gateway/values.yaml
  resources/apiserver-proxy/templates/job.yaml
  resources/application-connector/charts/application-broker/templates/subscription-migration.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/values.yaml
  resources/busola-migrator/values.yaml
  resources/certificates/values.yaml
  resources/cluster-essentials/templates/migrate-ac-certs-job.yaml
  resources/cluster-essentials/values.yaml
  resources/cluster-users/values.yaml
  resources/dex/templates/upgrade-job.yaml
  resources/eventing/values.yaml
  resources/helm-broker/templates/clear-cr-job.yaml
  resources/istio/templates/istio-proxy-reset.yaml
  resources/istio/values.yaml
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
  resources/ory/values.yaml
  resources/rafter/charts/upload-service/values.yaml
  resources/rafter/templates/pre-upgrade-delete-vs-job.yaml
  resources/rafter/values.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/clear-cr-job.yaml
  resources/service-catalog/charts/catalog/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/templates/job.yaml
  tests/integration/api-gateway/Dockerfile
  tests/integration/apiserver-proxy/Dockerfile
  tests/integration/dex/Dockerfile
Labels: size/M, lgtm

#12203 bump postgres 11.12-alpine to 11.13-alpine for release 1.24
  resources/ory/charts/postgresql/values.yaml
Labels: size/XS, lgtm

#12184 remove dex from oathkeeper jwks urls
  resources/ory/values.yaml
Labels: size/XS, lgtm

#12157 Rewrote Prometheus Istio Setup Docs
  docs/01-overview/main-areas/observability/assets/prometheus-setup.svg
  docs/01-overview/main-areas/observability/obsv-03-istio-monitoring.md
  docs/05-technical-reference/00-architecture/assets/obsv-monitoring-architecture.svg
Labels: size/M, lgtm

#11547 Add x-request-id header in the establish connection requests
  components/compass-runtime-agent/internal/compassconnection/connector.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/kyma/util.go
  components/compass-runtime-agent/pkg/apis/compass/v1alpha1/zz_generated.deepcopy.go
  resources/compass-runtime-agent/values.yaml
Labels: size/M, lgtm

#12119 Add tests for CE dispatching on NATS
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/pkg/handlers/test_helpers.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, size/L, lgtm

#12164 Apply new defaults for kyma 2
  installation/resources/values.yaml
  resources/cluster-essentials/values.yaml
  resources/cluster-users/values.yaml
  resources/kiali/values.yaml
  resources/logging/charts/loki/values.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/rafter/charts/controller-manager/charts/minio/values.yaml
  resources/service-catalog-addons/values.yaml
  resources/tracing/values.yaml
Labels: size/M, lgtm

#12178 Bump images after k8s-tools bump
  resources/api-gateway/values.yaml
  resources/apiserver-proxy/values.yaml
  resources/core/values.yaml
  resources/dex/values.yaml
  resources/istio/values.yaml
  resources/xip-patch/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/values.yaml
Labels: size/S, lgtm

#12193 Bumping apiserver-proxy ange iam-kubeconfig-service images
  resources/apiserver-proxy/values.yaml
  resources/iam-kubeconfig-service/values.yaml
Labels: size/XS, lgtm

#12204 Bump images after k8s-tools bump in release 1.24
  resources/api-gateway/values.yaml
  resources/apiserver-proxy/values.yaml
  resources/core/values.yaml
  resources/dex/values.yaml
  resources/istio/values.yaml
  resources/xip-patch/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/values.yaml
Labels: size/S, lgtm

#12197 Increase loki timeout
  tests/fast-integration/utils/index.js
Labels: size/XS, lgtm

#12156 Added backend switching logic in eventing fast-integration tests
  tests/fast-integration/Makefile
  tests/fast-integration/README.md
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/package.json
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#12199 Upgrade alpine to 3.14.2 version
  resources/console/charts/web/values.yaml
  resources/helm-broker/charts/addons-ui/values.yaml
  resources/logging/charts/logui/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/values.yaml
Labels: size/S, lgtm

#12209 Bump alpine for kyma-operator for release-1.24
  components/kyma-operator/Dockerfile
Labels: size/XS, lgtm

#12202 bump postgres 11.12-alpine to 11.13-alpine
  resources/ory/charts/postgresql/values.yaml
Labels: size/XS, lgtm

#12213 bump kyma-operator in kyma-installer in release-1.24
  tools/kyma-installer/kyma.Dockerfile
Labels: size/XS, lgtm

#12210 Upgrade alpine to 3.14.2 version in console
  resources/console/charts/web/values.yaml
  resources/helm-broker/charts/addons-ui/values.yaml
  resources/logging/charts/logui/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/values.yaml
Labels: size/S, lgtm

#12154 Fix event-publisher-proxy ha issue
  components/eventing-controller/pkg/deployment/publisher_deployment.go
  components/eventing-controller/pkg/object/equality.go
  components/eventing-controller/pkg/object/equality_test.go
  resources/eventing/charts/controller/values.yaml
Labels: bug, area/eventing, size/M, lgtm

#12194 kiali cannot reach jaeger - enable sidecar for kiali
  resources/kiali/templates/kyma-additions/servicemonitor.yaml
  resources/kiali/values.yaml
Labels: bug, area/tracing, size/XS, lgtm

#12195 Bump helm to 3.7 in kyma-operator
  components/kyma-operator/Dockerfile
  components/kyma-operator/Makefile
  components/kyma-operator/go.mod
  components/kyma-operator/go.sum
Labels: size/XL, lgtm

#12216 update dex version
  resources/dex/Chart.yaml
Labels: size/XS, lgtm

#12174 update docs according Busola UI
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/02-get-started/05-observability.md
  docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
  docs/03-tutorials/00-serverless/svls-02-create-git-function.md
  docs/03-tutorials/00-serverless/svls-03-expose-function.md
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/operations/obsv-01-access-logs.md
  docs/04-operation-guides/security/sec-02-authorization-in-kyma.md
  docs/04-operation-guides/security/sec-03-access-kyma.md
Labels: area/documentation, area/serverless, area/logging, size/M, lgtm

#12218 Bump kyma-operator in kyma-installer
  tools/kyma-installer/kyma.Dockerfile
Labels: size/XS, lgtm

#12220 bump gce-proxy in ORY chart
  resources/ory/charts/gcloud-sqlproxy/values.yaml
Labels: area/installation, area/api-gateway, size/XS, lgtm

#12222 bump gce proxy
  resources/ory/charts/gcloud-sqlproxy/values.yaml
Labels: area/installation, area/api-gateway, size/XS, lgtm

#12207 bumping apiserver-proxy and iam-kubeconfig-service images
  resources/apiserver-proxy/values.yaml
  resources/iam-kubeconfig-service/values.yaml
Labels: size/XS, lgtm

#12223 added dariusztutaj to codeowners file
  CODEOWNERS
Labels: size/M, lgtm

#12232 removed trailing spaces in fluent-bit config
  resources/logging/charts/fluent-bit/templates/configmap.yaml
  resources/logging/charts/fluent-bit/templates/kyma-additions/_parsers.tpl
Labels: area/logging, size/XS, lgtm

#12160 Bump helm-broker, etcd, sb-proxy-k8s images
  resources/helm-broker/charts/etcd-stateful/values.yaml
  resources/helm-broker/values.yaml
  resources/service-manager-proxy/values.yaml
Labels: size/S, lgtm

#12159 Bump helm-broker, etcd, sb-proxy-k8s images
  resources/helm-broker/charts/etcd-stateful/values.yaml
  resources/helm-broker/values.yaml
  resources/service-manager-proxy/values.yaml
Labels: size/S, lgtm

#12236 Remove space from markdown
  docs/04-operation-guides/security/sec-06-useful-links.md
Labels: size/XS, lgtm

#12226 remove eventing crds from cluster essentials
  components/eventing-controller/Makefile
  resources/cluster-essentials/files/eventingbackends.eventing.kyma-project.io.crd.yaml
  resources/cluster-essentials/files/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/eventing/README.md
Labels: lgtm
