Repository kyma-project/kyma, pull requests merged in 2021-12, with the labels that each got.

#12756 Revert "bump istio-installer to 1.12.0"
  components/istio-installer/Dockerfile
Labels: size/XS, lgtm

#12672 Fix for storing timestamp of lastAttempt of synchronisation in Connection CR and processing it in reconciliation loop
  components/compass-runtime-agent/internal/compassconnection/controller.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/compassconnection/supervisor.go
  resources/compass-runtime-agent/values.yaml
Labels: size/L, lgtm

#12755 add info where to look for profile settings
  docs/02-get-started/01-quick-install.md
Labels: size/XS, lgtm

#12749 disable alertmanager grafana dashboard if alertmanager is deactivated
  resources/monitoring/templates/grafana/kyma-dashboards/alertmanager.yaml
Labels: area/monitoring, size/XS, lgtm

#12742 Bump helm-broker related images (release 1.25)
  resources/helm-broker/values.yaml
Labels: size/XS, lgtm

#12758 Compass Runtime Agent image bump for main branch after PR-12672
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#12759 Replace PR tags for the serverless and the rafter components
  resources/rafter/values.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm

#12761 add eventing contributors as eventing-crd owners
  CODEOWNERS
Labels: size/XS, lgtm

#12729 Compass Runtime Agent sync rate fix for 1.25 branch
  components/compass-runtime-agent/internal/compassconnection/controller.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/compassconnection/supervisor.go
  components/compass-runtime-agent/pkg/apis/compass/v1alpha1/zz_generated.deepcopy.go
Labels: size/L, lgtm

#12763 Compass Runtime Agent image bump for release 1.25 branch after PR-12729
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#12208 Eventing controller should update the Subscription status correctly if sink is misconfigured
  components/eventing-controller/controllers/events/events.go
  components/eventing-controller/controllers/subscription/beb/event.go
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/utils.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/values.yaml
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: size/XL, lgtm

#12764 add info on metrics endpoint
  docs/05-technical-reference/svls-08-function-specification.md
Labels: size/XS, lgtm

#12766 disabled ingressgateway autoscaling for evaluation profile
  resources/istio-configuration/profile-evaluation.yaml
  resources/istio-configuration/templates/istio-operator.yaml
  resources/istio-configuration/values.yaml
Labels: size/S, lgtm

#12750 Removed testing component
  CODEOWNERS
  installation/resources/crds/testing/clustertestsuite.crd.yaml
  installation/resources/crds/testing/testdefinition.crd.yaml
  resources/cluster-essentials/files/clustertestsuite.crd.yaml
  resources/cluster-essentials/files/testdefinition.crd.yaml
  resources/cluster-users/values.yaml
  resources/rafter/templates/tests/rbac.yaml
  resources/rafter/templates/tests/test.yaml
  resources/rafter/values.yaml
  resources/testing/.helmignore
  resources/testing/Chart.yaml
  resources/testing/README.md
  resources/testing/charts/octopus/.helmignore
  resources/testing/charts/octopus/Chart.yaml
  resources/testing/charts/octopus/templates/_helpers.tpl
  resources/testing/charts/octopus/templates/manager.yaml
  resources/testing/charts/octopus/templates/rbac_role.yaml
  resources/testing/charts/octopus/templates/rbac_role_binding.yaml
  resources/testing/charts/octopus/templates/service-account.yaml
  resources/testing/charts/octopus/values.yaml
  resources/testing/values.yaml
  tests/end-to-end/upgrade/chart/upgrade/templates/test/test-upgrade.yaml
  tests/rafter/README.md
Labels: size/XL, lgtm

#12760 Restore Istio PeerAuthentications (with strict mode)
  resources/eventing/charts/controller/templates/peerauthentication.yaml
  resources/eventing/charts/publisher-proxy/templates/peerauthentication.yaml
  resources/kiali/templates/kyma-additions/peerauthentication.yaml
  resources/logging/charts/fluent-bit/templates/kyma-additions/peerauthentication.yaml
  resources/logging/charts/loki/templates/kyma-additions/peerauthentication.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/peerauthentication.yaml
  resources/ory/templates/monitoring-hydra.yaml
  resources/ory/templates/monitoring-oathkeeper.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/peerauthentication.yaml
  resources/tracing/templates/kyma-additions/peerauthentication.yaml
Labels: area/monitoring, size/L, lgtm

#12762 Ory fix the production profile and make JWKS secret optional in Helm
  resources/ory/charts/oathkeeper/templates/secret.yaml
  resources/ory/profile-production.yaml
Labels: size/XS, lgtm

#12704 Document Loki and Prometheus limits
  docs/01-overview/main-areas/observability/README.md
  docs/01-overview/main-areas/observability/obsv-01-telemetry-observability-overview.md
  docs/01-overview/main-areas/observability/obsv-10-useful-links.md
  docs/04-operation-guides/operations/obsv-02-adjust-loki.md
  docs/04-operation-guides/troubleshooting/obsv-03-troubleshoot-loki-logging.md
Labels: area/documentation, area/logging, size/M, lgtm

#12775 Fix auth-proxy restart command
  docs/04-operation-guides/security/sec-06-access-expose-kiali-grafana.md
Labels: size/XS, lgtm

#12753 fix issues found by various linters
  components/event-publisher-proxy/Makefile
  components/event-publisher-proxy/cmd/event-publisher-proxy/beb/beb.go
  components/event-publisher-proxy/cmd/event-publisher-proxy/nats/nats.go
  components/event-publisher-proxy/pkg/application/clean.go
  components/event-publisher-proxy/pkg/application/fake/lister.go
  components/event-publisher-proxy/pkg/handler/beb/handler.go
  components/event-publisher-proxy/pkg/handler/beb/handler_test.go
  components/event-publisher-proxy/pkg/handler/common.go
  components/event-publisher-proxy/pkg/handler/handlertest/handlertest.go
  components/event-publisher-proxy/pkg/handler/nats/handler.go
  components/event-publisher-proxy/pkg/handler/nats/handler_test.go
  components/event-publisher-proxy/pkg/legacy-events/legacy.go
  components/event-publisher-proxy/pkg/metrics/server.go
  components/event-publisher-proxy/pkg/oauth/client_test.go
  components/event-publisher-proxy/pkg/receiver/receiver.go
  components/event-publisher-proxy/pkg/receiver/receiver_test.go
  components/event-publisher-proxy/pkg/sender/beb_test.go
  components/event-publisher-proxy/pkg/subscribed/helpers.go
  components/event-publisher-proxy/pkg/subscribed/response.go
  components/event-publisher-proxy/testing/fixtures.go
  components/event-publisher-proxy/testing/utils.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#12721 Tests for CRUD operations on application services
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/test/fixtures/commerce-mock/commerce-mock.yaml
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: area/application-connector, size/M, lgtm

#12778 Upgrade go version in Compass Runtime Agent
  components/compass-runtime-agent/go.mod
  resources/compass-runtime-agent/values.yaml
Labels: size/M, lgtm

#12786 Simplify App Conn tutorials some more
  docs/01-overview/main-areas/application-connectivity/ac-04-security.md
  docs/01-overview/main-areas/application-connectivity/ac-05-useful-links.md
  docs/03-tutorials/00-application-connectivity/ac-02-get-client-certificate.md
  docs/03-tutorials/00-application-connectivity/ac-03-register-manage-services.md
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
  docs/03-tutorials/00-application-connectivity/ac-06-renew-client-cert.md
  docs/03-tutorials/00-application-connectivity/ac-07-revoke-client-cert.md
  docs/03-tutorials/00-application-connectivity/ac-08-rotate-root-ca.md
  docs/03-tutorials/00-application-connectivity/ac-11-disable-tls-certificate-verification.md
Labels: area/documentation, area/application-connector, size/M, lgtm

#12785 Adjust Ory replicaCount with the HPA in the Helm templates
  resources/ory/charts/hydra/templates/deployment.yaml
  resources/ory/charts/oathkeeper/templates/deployment-controller.yaml
  resources/ory/charts/oathkeeper/templates/deployment-with-sidecar.yaml
  resources/ory/charts/oathkeeper/templates/hpa.yaml
  resources/ory/charts/oathkeeper/values.yaml
  resources/ory/profile-evaluation.yaml
  resources/ory/profile-production.yaml
  resources/ory/templates/hpa.yaml
  resources/ory/values.yaml
Labels: area/security, size/L, lgtm

#12779 Bump BTP Operator in fast integration migration test to v0.1.18
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
Labels: size/XS, lgtm

#12791 use natural lg for CRD in docs
  components/README.md
  components/application-broker/README.md
  components/eventing-controller/README.md
  components/eventing-controller/config/crd/external/README.md
  components/kyma-operator/README.md
  docs/01-overview/main-areas/api-exposure/apix-01-api-gateway.md
  docs/01-overview/main-areas/service-management/smgt-01-overview.md
  docs/03-tutorials/00-serverless/svls-06-sync-function-with-gitops.md
  docs/05-technical-reference/00-architecture/apix-01-architecture-apigateway.md
  docs/05-technical-reference/00-architecture/evnt-01-architecture.md
  docs/05-technical-reference/00-custom-resources/ac-01-application.md
  docs/05-technical-reference/00-custom-resources/ac-02-tokenrequest.md
  docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
  docs/05-technical-reference/00-custom-resources/ra-01-compassconnection.md
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  docs/05-technical-reference/00-custom-resources/svls-02-gitrepository.md
  docs/glossary.md
  resources/api-gateway/README.md
  resources/monitoring/README.md
Labels: size/M, lgtm

#12792 Improved docu for mTLS scrape setup
  docs/01-overview/main-areas/observability/obsv-03-istio-monitoring.md
Labels: area/documentation, area/monitoring, size/XS, lgtm

#12654 Add Kyma 2.0 migration guide
  docs/assets/1.24-2.0-remove-deprecated-resources.sh
  docs/migration-guide-1.24-2.0.md
  milv.config.yaml
Labels: area/documentation, size/L, lgtm

#12794 remove 404 link
  README.md
Labels: area/documentation, lgtm

#12795 Fix the link to the migration script
  docs/migration-guide-1.24-2.0.md
Labels: area/documentation, size/XS, lgtm

#12799 Fix the titles of the "Revoke a client cert" tutorials
  docs/01-overview/main-areas/application-connectivity/ac-05-useful-links.md
  docs/01-overview/main-areas/application-connectivity/ra-02-useful-links.md
  docs/03-tutorials/00-application-connectivity/ac-07-revoke-client-cert.md
  docs/03-tutorials/00-application-connectivity/ra-03-revoke-client-certificate.md
Labels: bug, area/documentation, size/M, lgtm

#12798 Update Telemetry chart
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#12797 Bump publisher proxy image
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#12800 Bump Application Connector images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/XS, lgtm

#12801 Bump eventing-controller image
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#12805 Update codeowners (rel 1.24)
  CODEOWNERS
Labels: size/M, lgtm

#12802 Fix images
  resources/application-connector/values.yaml
  resources/service-catalog-addons/values.yaml
Labels: size/XS, lgtm

#12626 Compass Runtime Agent should reconcile the mTLS secret in istio-system
  components/compass-runtime-agent/internal/certificates/manager.go
  components/compass-runtime-agent/internal/certificates/manager_test.go
  components/compass-runtime-agent/internal/certificates/mocks/Manager.go
  components/compass-runtime-agent/internal/compassconnection/connector.go
  components/compass-runtime-agent/internal/compassconnection/mocks/Connector.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/compassconnection/supervisor.go
  components/compass-runtime-agent/internal/secrets/mocks/Repository.go
  components/compass-runtime-agent/internal/secrets/repository.go
  components/compass-runtime-agent/internal/secrets/repository_test.go
  resources/compass-runtime-agent/values.yaml
Labels: size/L, lgtm

#12804 Use proper tag for busola migrator
  resources/busola-migrator/values.yaml
Labels: size/XS, lgtm

#12803 use subAccountID from environment
  tests/fast-integration/kcp/client.js
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
Labels: size/S, lgtm

#12789 Bump helm-broker related images (release 1.24)
  resources/helm-broker/values.yaml
Labels: size/XS, lgtm

#12806 Update image for e2e upgrade test
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
Labels: size/XS, lgtm

#12807 Replace PR image for compass runtime agent
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#12588 add support for SKR in eventing fast-integration tests
  tests/fast-integration/compass/client.js
  tests/fast-integration/compass/gql.js
  tests/fast-integration/compass/helpers.js
  tests/fast-integration/eventing-test/.env.template
  tests/fast-integration/eventing-test/README.md
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/utils/index.js
Labels: area/eventing, size/L, lgtm

#12811 eventing controller reconciler should validate only the host part in …
  components/eventing-controller/controllers/subscription/nats/reconciler.go
Labels: area/eventing, size/XS, lgtm

#12814 Bump golang version in telemetry operator
  components/telemetry-operator/Dockerfile
  components/telemetry-operator/go.mod
Labels: size/M, lgtm

#12816 Bump golang version in telemetry operator chart
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#12781 implement mutex in bebmock subscriptions
  components/eventing-controller/controllers/backend/reconciler_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/testing/bebmock.go
  components/eventing-controller/testing/saferequests.go
  components/eventing-controller/testing/safesubscriptions.go
  components/eventing-controller/testing/test_helpers.go
  installation/resources/crds/eventing/eventingbackends.eventing.kyma-project.io.crd.yaml
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#12769 Preserve Eventing Publisher proxy deployment annotations after reconciliation
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#12713 Add ability to add runtime resource presets
  components/function-controller/cmd/webhook/main.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_defaults_test.go
  resources/serverless/charts/webhook/templates/configmap.yaml
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/profile-evaluation.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#12787 Fetch runtime status from KEB when operation fails in fast-integration tests
  tests/fast-integration/kcp/client.js
  tests/fast-integration/kyma-environment-broker/helpers.js
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
  tests/fast-integration/skr-nightly/provision/provision-skr-nightly.js
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-test/skr-test.js
  tests/fast-integration/skr-test/test.js
Labels: size/L, lgtm

#12828 fix components yaml sample
  docs/04-operation-guides/operations/02-install-kyma.md
Labels: bug, area/documentation, size/XS, lgtm

#12832 Update gophers codeowners for fast-integration tests
  CODEOWNERS
Labels: size/S, lgtm

#12826 Increased timeout and separated out nats invalid sink tests
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/testing/test_helpers.go
Labels: size/L, lgtm

#12833 Fix endless reconciliation of the Publisher proxy deployment
  components/eventing-controller/pkg/object/equality.go
  components/eventing-controller/pkg/object/equality_test.go
  resources/eventing/values.yaml
Labels: bug, area/eventing, size/M, lgtm

#12808 Fix "retry sending an event to sink" for NATS dispatcher
  components/eventing-controller/README.md
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/pkg/env/backend_config.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/testing/subscriber.go
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/values.yaml
Labels: size/L, lgtm

#12834 Add new members to eventing codeownership
  CODEOWNERS
Labels: size/S, lgtm

#12836 add kymaVersion
  tests/fast-integration/kyma-environment-broker/client.js
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
Labels: size/XS, lgtm

#12855 Fix link to function.yaml
  docs/03-tutorials/00-api-exposure/apix-03-expose-and-secure-service.md
Labels: area/documentation, size/XS, lgtm

#12856 Fix link to function.yaml 2.0 docu
  docs/03-tutorials/00-api-exposure/apix-03-expose-and-secure-service.md
Labels: size/XS, lgtm

#12858 Ory troubleshooting guide 2.0 docu
  docs/04-operation-guides/troubleshooting/sec-02-oauth2-protected-apirules.md
Labels: area/documentation, area/security, size/S, lgtm

#12842 Ory troubleshooting guide
  docs/04-operation-guides/troubleshooting/sec-02-oauth2-protected-apirules.md
Labels: area/documentation, area/security, size/S, lgtm

#12768 Make observability tests part of standard test suite
  tests/fast-integration/Makefile
  tests/fast-integration/monitoring-test/grafana-test.js
  tests/fast-integration/monitoring-test/monitoring-test.js
  tests/fast-integration/monitoring-test/readme.md
  tests/fast-integration/monitoring/.env.template
  tests/fast-integration/monitoring/client.js
  tests/fast-integration/monitoring/grafana.js
  tests/fast-integration/monitoring/helpers.js
  tests/fast-integration/monitoring/prometheus.js
  tests/fast-integration/package.json
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/test/2-getting-started-guide.js
  tests/fast-integration/test/3-monitoring.js
  tests/fast-integration/test/fixtures/getting-started-guide/index.js
  tests/fast-integration/test/fixtures/getting-started-guide/microservice.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/ns.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/redis-addon-sb-si.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/redis-sbu.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/xf-mocks.yaml
  tests/fast-integration/test/index.js
  tests/fast-integration/test/test.js
Labels: area/monitoring, size/XXL, lgtm

#12765 Update Eventing documentation
  docs/01-overview/main-areas/eventing/evnt-02-useful-links.md
  docs/03-tutorials/00-eventing/evnt-01-send-event-outside-cluster.md
  docs/03-tutorials/00-eventing/evnt-02-setup-in-cluster-eventing.md
  docs/05-technical-reference/00-architecture/evnt-01-architecture.md
  docs/05-technical-reference/evnt-01-event-names.md
  docs/05-technical-reference/evnt-01-event-processing.md
Labels: area/documentation, size/L, lgtm

#12736 Add exponential reconcile for serverless controller
  components/function-controller/Makefile
  components/function-controller/cmd/manager/main.go
  components/function-controller/go.mod
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  components/function-controller/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/gitops.go
  components/function-controller/internal/controllers/serverless/gitops_test.go
  components/function-controller/internal/controllers/serverless/suite_test.go
  components/function-controller/internal/git/errors.go
  components/function-controller/internal/git/errors_test.go
  components/function-controller/internal/git/go2git.go
  components/function-controller/internal/git/go2git_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#12767 Add liveness probe implementation for serverless controller
  components/function-controller/cmd/manager/main.go
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/health.go
  components/function-controller/internal/controllers/serverless/health_test.go
  resources/serverless/templates/deployment.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#12864 Fix non-namespaced resources in the Ory Helm chart
  resources/ory/charts/hydra/charts/hydra-maester/templates/rbac.yaml
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/templates/rbac.yaml
Labels: size/XS, lgtm

#12865 Fix non-namespaced resources in the Ory Helm chart
  resources/ory/charts/hydra/charts/hydra-maester/templates/rbac.yaml
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/templates/rbac.yaml
Labels: size/XS, lgtm

#12754 Expose istio /healthz/ready endpoint to public
  resources/certificates/templates/virtualservice.yaml
Labels: size/S, lgtm

#12862 Fix Serverless grafana dashboard time units
  resources/serverless/templates/function-dashboard.yaml
Labels: size/XS, lgtm

#12751 Introduce priority class for DaemonSets
  resources/cluster-essentials/templates/priorityclass-high.yaml
  resources/cluster-essentials/values.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/istio-configuration/values.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/logging/charts/fluent-bit/templates/_pod.tpl
  resources/logging/values.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/prometheus-node-exporter/templates/daemonset.yaml
  resources/monitoring/values.yaml
  resources/serverless/charts/docker-registry/templates/deployment.yaml
  resources/serverless/charts/webhook/templates/deployment.yaml
  resources/serverless/templates/daemonset-certs.yaml
  resources/serverless/values.yaml
  resources/service-catalog/values.yaml
  resources/telemetry/charts/fluent-bit/templates/_pod.tpl
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/values.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
Labels: size/M, lgtm

#12873 Update security-related tutorial
  docs/04-operation-guides/security/sec-07-useful-links.md
  docs/04-operation-guides/troubleshooting/sec-01-certificates-gardener.md
Labels: area/documentation, area/security, size/S, lgtm

#12191 Remove requirements.yaml
  resources/helm-broker/Chart.yaml
  resources/helm-broker/requirements.yaml
  resources/rafter/Chart.yaml
  resources/rafter/charts/controller-manager/Chart.yaml
  resources/rafter/charts/controller-manager/requirements.yaml
  resources/rafter/charts/upload-service/Chart.yaml
  resources/rafter/charts/upload-service/requirements.lock
  resources/rafter/charts/upload-service/requirements.yaml
  resources/rafter/requirements.yaml
  resources/serverless/Chart.yaml
  resources/serverless/requirements.yaml
  resources/service-catalog-addons/Chart.yaml
  resources/service-catalog-addons/requirements.yaml
  tests/fast-integration/telemetry-test/helm/mockserver/requirements.yaml
Labels: size/M, lgtm

#12875 fix dead link in finalizers-findings.md
  components/application-broker/cmd/poc-finalizers/finalizers-findings.md
Labels: size/XS, lgtm

#12870 Fix the horizontal communication between NATS nodes in a NATS cluster (production profile)
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
Labels: size/XS, lgtm

#12877 Add SKR configmap to CRA chart
  resources/compass-runtime-agent/templates/skr-configmap.yaml
  resources/compass-runtime-agent/values.yaml
Labels: enhancement, area/application-connector, size/XS, lgtm

#12878 Remove namespace from cluster wide k8s objects
  components/application-operator/charts/application/templates/role-binding.yaml
  components/binding/charts/binding/templates/mutating-webhook.yaml
  resources/api-gateway/templates/rbac.yaml
  resources/application-connector/charts/central-application-connectivity-validator/templates/rbac.yaml
  resources/application-connector/charts/central-application-gateway/templates/rbac.yaml
  resources/application-connector/charts/connection-token-handler/templates/role-binding.yaml
  resources/cluster-essentials/charts/pod-preset/templates/webhook/webhook.yaml
  resources/compass-runtime-agent/templates/cluster-role-binding.yaml
  resources/helm-broker/templates/webhook-register.yaml
  resources/monitoring/charts/grafana/templates/podsecuritypolicy.yaml
  resources/monitoring/charts/prometheus-node-exporter/templates/psp.yaml
  resources/telemetry/charts/operator/templates/role-binding.yaml
Labels: size/S, lgtm

#12883 Fix Eventing architecture diagram
  docs/05-technical-reference/00-architecture/assets/evnt-architecture.svg
  docs/05-technical-reference/assets/eventing-flow.svg
  docs/05-technical-reference/assets/evnt-processing-flow.svg
Labels: area/documentation, area/eventing, size/XS, lgtm

#12880 update grafana to 7.5.12
  resources/monitoring/values.yaml
Labels: area/monitoring, size/XS, lgtm

#12861 updated fluent bit to 1.8.11
  resources/logging/values.yaml
  resources/telemetry/values.yaml
Labels: area/logging, size/XS, lgtm

#12879 Remove namespace from cluster wide k8s objects
  components/application-operator/charts/application/templates/role-binding.yaml
  components/binding/charts/binding/templates/mutating-webhook.yaml
  resources/api-gateway/templates/rbac.yaml
  resources/application-connector/charts/central-application-connectivity-validator/templates/rbac.yaml
  resources/application-connector/charts/central-application-gateway/templates/rbac.yaml
  resources/application-connector/charts/connection-token-handler/templates/role-binding.yaml
  resources/cluster-essentials/charts/pod-preset/templates/webhook/webhook.yaml
  resources/compass-runtime-agent/templates/cluster-role-binding.yaml
  resources/helm-broker/templates/webhook-register.yaml
  resources/monitoring/charts/grafana/templates/podsecuritypolicy.yaml
  resources/monitoring/charts/prometheus-node-exporter/templates/psp.yaml
  resources/telemetry/charts/operator/templates/role-binding.yaml
Labels: size/S, lgtm

#12884 Add SKR configmap to CRA chart (#12877)
  resources/compass-runtime-agent/templates/skr-configmap.yaml
  resources/compass-runtime-agent/values.yaml
Labels: enhancement, size/XS, lgtm

#12885 Bump version to 2.1.0-rc1
  VERSION
Labels: size/XS, lgtm

#12886 Bump version to 2.0.1-rc1
  VERSION
Labels: size/XS, lgtm

#12888 update to grafana 7.5.12
  resources/monitoring/values.yaml
Labels: area/monitoring, size/XS, lgtm

#12887 Update the codeowners file
  CODEOWNERS
Labels: size/XS, lgtm

#12869 Remove JS installer
  tests/fast-integration/hack/cache-images.sh
  tests/fast-integration/hack/create-cluster-k3d.sh
  tests/fast-integration/hack/create-cluster-k3s.sh
  tests/fast-integration/hack/delete-cluster.sh
  tests/fast-integration/hack/registries.yaml
  tests/fast-integration/installer/chart-downloader.js
  tests/fast-integration/installer/charts/ingress-dns-cert/Chart.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/OWNERS
  tests/fast-integration/installer/charts/ingress-dns-cert/README.md
  tests/fast-integration/installer/charts/ingress-dns-cert/templates/certificate.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/templates/job.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/templates/rolebindings.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/templates/roles.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/templates/serviceaccount.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/values.yaml
  tests/fast-integration/installer/compass-namespace.yaml
  tests/fast-integration/installer/config-istio.yaml
  tests/fast-integration/installer/helm.js
  tests/fast-integration/installer/index.js
  tests/fast-integration/installer/istioctl.js
  tests/fast-integration/installer/kyma-crds.js
  tests/fast-integration/installer/system-namespaces.yaml
  tests/fast-integration/kyma.js
  tests/fast-integration/package-lock.json
  tests/fast-integration/package.json
  tests/fast-integration/provisioner/k3d.js
  tests/fast-integration/provisioner/registries.yaml
Labels: size/XXL, lgtm

#12872 Introduce priority class for DaemonSets (#12751)
  resources/cluster-essentials/templates/priorityclass-high.yaml
  resources/cluster-essentials/values.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/istio-configuration/values.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/logging/charts/fluent-bit/templates/_pod.tpl
  resources/logging/values.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/prometheus-node-exporter/templates/daemonset.yaml
  resources/monitoring/values.yaml
  resources/serverless/charts/docker-registry/templates/deployment.yaml
  resources/serverless/charts/webhook/templates/deployment.yaml
  resources/serverless/templates/daemonset-certs.yaml
  resources/serverless/values.yaml
  resources/service-catalog/values.yaml
  resources/telemetry/charts/fluent-bit/templates/_pod.tpl
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/values.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
Labels: size/M, lgtm

#12896 fix in the trigger-workload-with-event.md
  docs/02-get-started/04-trigger-workload-with-event.md
Labels: size/XS, lgtm

#12898 Fix test-helpers for migration and upgrade tests
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
Labels: size/M, lgtm

#12863 Remove unused code for watch-pods
  installation/resources/watch-pods.yaml
  installation/scripts/prow/kyma-integration-on-debian/deploy-and-test-kyma.sh
  installation/scripts/watch-pods.sh
Labels: size/M, lgtm

#12901 Fix Capital GUI/CLI in algolia search results
  docs/01-overview/main-areas/ui/ui-01-gui.md
  docs/01-overview/main-areas/ui/ui-02-cli.md
  docs/04-operation-guides/security/sec-03-access-kyma.md
Labels: size/M, lgtm

#12908 Delete ui-01-GUI.md
  docs/01-overview/main-areas/ui/ui-01-GUI.md
Labels: size/S, lgtm

#12909 Delete ui-02-CLI.md
  docs/01-overview/main-areas/ui/ui-02-CLI.md
Labels: size/M, lgtm

#12903 Bump CRA
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/XS, lgtm

#12912 Fix Capital GUI/CLI in algolia search results
  docs/01-overview/main-areas/ui/ui-01-gui.md
  docs/01-overview/main-areas/ui/ui-02-cli.md
  docs/04-operation-guides/security/sec-03-access-kyma.md
Labels: size/XS, lgtm

#12916 Cherry pick adding app labels by CRA
  components/compass-runtime-agent/internal/kyma/applications/converter.go
  components/compass-runtime-agent/internal/kyma/applications/converter_test.go
  components/compass-runtime-agent/internal/kyma/applications/repository.go
  resources/compass-runtime-agent/values.yaml
Labels: enhancement, area/application-connector, size/S, lgtm

#12919 Increase memory limits for a few monitoring components
  resources/monitoring/charts/kube-state-metrics/values.yaml
  resources/monitoring/profile-production.yaml
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#12921 update grafana to 7.5.12 (#12880)
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring, size/XS, lgtm

#12824 Add git-function authentication integration tests
  resources/serverless/charts/k3s-tests/templates/k3s-test.yaml
  resources/serverless/charts/k3s-tests/values.yaml
  resources/serverless/values.yaml
  tests/function-controller/cmd/main.go
  tests/function-controller/go.mod
  tests/function-controller/go.sum
  tests/function-controller/testsuite/gitops/function.go
  tests/function-controller/testsuite/gitops/gitrepository.go
  tests/function-controller/testsuite/scenarios/gitauth.go
  tests/function-controller/testsuite/scenarios/gitops.go
Labels: size/XXL, lgtm

#12920 Increase memory limit of eventing controller
  resources/eventing/profile-evaluation.yaml
Labels: area/eventing, size/XS, lgtm

#12925 Remove excessive logs from fast-integration tests - `execa` calls
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
Labels: size/S, lgtm

#12890 Change metric for monitoring requests to EPP
  resources/eventing/charts/dashboards/templates/delivery.yaml
  tests/fast-integration/eventing-test/metric-test.js
Labels: size/S, lgtm

#12918 Fix NATS servers discovery
  resources/eventing/charts/nats/templates/service.yaml
Labels: area/eventing, test-failing, size/XS, lgtm

#12928 Add latest Eventing documentation
  docs/01-overview/main-areas/eventing/evnt-02-useful-links.md
  docs/03-tutorials/00-eventing/evnt-01-send-event-outside-cluster.md
  docs/03-tutorials/00-eventing/evnt-02-setup-in-cluster-eventing.md
  docs/05-technical-reference/00-architecture/assets/evnt-architecture.svg
  docs/05-technical-reference/00-architecture/evnt-01-architecture.md
  docs/05-technical-reference/assets/eventing-flow.svg
  docs/05-technical-reference/assets/evnt-processing-flow.svg
  docs/05-technical-reference/evnt-01-event-names.md
  docs/05-technical-reference/evnt-01-event-processing.md
Labels: area/documentation, size/L, lgtm

#12933 Remove waiting for service-catalog-ui pod in skr-svcat-migration-test
  tests/fast-integration/skr-svcat-migration-test/deploy-sample-resources.js
Labels: size/XS, lgtm

#12488 clean event types
  components/eventing-controller/Makefile
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/controllers/backend/reconciler_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/testing/bebmock.go
  components/eventing-controller/testing/matchers.go
  components/eventing-controller/testing/test_helpers.go
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#12940 Remove excessive debug logging from KEB client
  tests/fast-integration/kyma-environment-broker/client.js
Labels: size/XS, lgtm

#12929 Fast integration remove excessive logs hotfix
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
Labels: size/XS, lgtm

#12935 Bump crypto lib
  components/function-controller/go.mod
  components/function-controller/go.sum
  resources/serverless/values.yaml
Labels: size/S, lgtm

#12932 Remove ginkgo from function ctrl tests
  components/function-controller/internal/controllers/serverless/fixtures_test.go
  components/function-controller/internal/controllers/serverless/function_controller_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_asserts_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/suite_test.go
  resources/serverless/values.yaml
Labels: size/XXL, lgtm

#12942 Istio-configuration: make comaptible with image-url-helper tool
  resources/istio-configuration/templates/_helpers.tpl
  resources/istio-configuration/templates/istio-operator.yaml
  resources/istio-configuration/values.yaml
Labels: size/M, lgtm

#12943 Add wait for ClusterServiceBroker func in fast-integration test
  tests/fast-integration/skr-svcat-migration-test/deploy-sample-resources.js
  tests/fast-integration/utils/index.js
Labels: size/S, lgtm

#12938 Add tests for valid sink
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
Labels: size/M, lgtm

#12944 Upgrade crypo lib - patch release
  components/function-controller/go.mod
  components/function-controller/go.sum
Labels: size/S, lgtm

#12936 Bump crypto patch release
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#12934 Troubleshooting guide for gateway not reachable
  docs/01-overview/main-areas/api-exposure/apix-02-useful-links.md
  docs/04-operation-guides/troubleshooting/apix-06-gateway-not-reachable.md
Labels: area/documentation, area/api-gateway, size/S, lgtm

#12947 revert change to the selector label as selector labels are immutable
  resources/kiali/templates/_helpers.tpl
Labels: size/XS, lgtm

#12937 Remove ginkgo k8s controllers tests
  components/function-controller/go.mod
  components/function-controller/go.sum
  components/function-controller/internal/controllers/kubernetes/configmap_controller_test.go
  components/function-controller/internal/controllers/kubernetes/fixtures_test.go
  components/function-controller/internal/controllers/kubernetes/namespace_controller_test.go
  components/function-controller/internal/controllers/kubernetes/role_controller_test.go
  components/function-controller/internal/controllers/kubernetes/rolebinding_controller_test.go
  components/function-controller/internal/controllers/kubernetes/secret_controller_test.go
  components/function-controller/internal/controllers/kubernetes/serviceaccount_controller_test.go
  components/function-controller/internal/controllers/kubernetes/serviceaccount_service_test.go
  components/function-controller/internal/controllers/kubernetes/shared_test.go
  components/function-controller/internal/controllers/kubernetes/suite_test.go
  components/function-controller/internal/controllers/serverless/suite_test.go
  resources/serverless/values.yaml
Labels: size/XXL, lgtm

#12959 Add init container to service-manager-proxy component
  resources/service-manager-proxy/templates/deployment.yaml
  resources/service-manager-proxy/values.yaml
Labels: size/XS, lgtm

#12941 Dump runtime status on test failure
  tests/fast-integration/kcp/client.js
  tests/fast-integration/kyma-environment-broker/helpers.js
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
  tests/fast-integration/skr-nightly/provision/provision-skr-nightly.js
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-test/skr-test.js
  tests/fast-integration/skr-test/test.js
Labels: size/L, lgtm

#12952 Add a troubleshooting guide about a misconfigured resource
  docs/04-operation-guides/troubleshooting/01-resources-misconfigured.md
Labels: area/documentation, size/S, lgtm
