Repository kyma-project/kyma, pull requests merged in 2021-10, with the labels that each got.

#12224 updating dex image
  resources/dex/Chart.yaml
Labels: size/XS, lgtm

#12244 fixed default settings for loki dashboard
  resources/logging/charts/loki/templates/kyma-additions/grafana-dashboard.yaml
Labels: size/S, lgtm

#12250 Fixed dead links
  .github/pull-request-template.md
  CONTRIBUTING.md
Labels: area/documentation, size/XS, lgtm

#12256 removed unneeded label check from monitoring test
  tests/fast-integration/monitoring-test/monitoring-test.js
Labels: size/XS, lgtm

#12242 updated docu links for authproxy
  docs/04-operation-guides/security/sec-06-access-expose-kiali-grafana.md
  resources/kiali/values.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/tracing/values.yaml
Labels: size/XS, lgtm

#12246 fixed label used in description text of observability tutorial
  docs/03-tutorials/00-observability/obsv-01-observe-application-metrics.md
Labels: size/XS, lgtm

#12252 Adopt overriding default docker registry docu
  docs/03-tutorials/00-serverless/svls-07-set-external-registry.md
Labels: size/M, lgtm

#12198 Update values.yaml in application-connector
  resources/application-connector/charts/application-broker/templates/deployment.yaml
  resources/application-connector/charts/application-operator/templates/controller.yaml
  resources/application-connector/charts/application-operator/templates/tests/gateway-test.yaml
  resources/application-connector/charts/application-operator/templates/tests/operator-test.yaml
  resources/application-connector/charts/application-registry/templates/deployment.yaml
  resources/application-connector/charts/application-registry/templates/tests/test.yaml
  resources/application-connector/charts/central-application-connectivity-validator/templates/deployment.yaml
  resources/application-connector/charts/central-application-gateway/templates/deployment.yaml
  resources/application-connector/charts/connection-token-handler/templates/deployment.yaml
  resources/application-connector/charts/connection-token-handler/templates/tests/test.yaml
  resources/application-connector/charts/connector-service/templates/deployment.yaml
  resources/application-connector/charts/connector-service/templates/tests/test.yaml
  resources/application-connector/templates/_helpers.tpl
  resources/application-connector/templates/certs-setup-job.yaml
  resources/application-connector/templates/tests/test.yaml
  resources/application-connector/values.yaml
Labels: size/L, lgtm

#12241 Remove technical debt (bash tests)
  resources/cluster-users/files/kyma-test-bindings.yaml
  resources/cluster-users/files/sar-test.sh
  resources/cluster-users/files/test_resources/k8s/Client.yaml
  resources/cluster-users/files/test_resources/k8s/Deployment.yaml
  resources/cluster-users/files/test_resources/k8s/README.md
  resources/cluster-users/files/test_resources/k8s/Service.yaml
  resources/cluster-users/files/test_resources/k8s/VirtualService.yaml
  resources/cluster-users/files/test_resources/k8s/ory-hydra-change-envs-and-restart.sh
  tests/integration/cluster-users/README.md
  tests/integration/cluster-users/components.yaml
  tests/integration/cluster-users/docker-compose.yaml
  tests/integration/cluster-users/hydra.yml
  tests/integration/cluster-users/k3d-cluster-users.sh
  tests/integration/cluster-users/kyma-cert.key
  tests/integration/cluster-users/kyma-cert.pem
  tests/integration/cluster-users/nginx.conf
  tests/integration/cluster-users/oidc_token_fetcher/go.mod
  tests/integration/cluster-users/oidc_token_fetcher/go.sum
  tests/integration/cluster-users/oidc_token_fetcher/main.go
  tests/integration/cluster-users/oidc_token_fetcher/main_test.go
Labels: size/XXL, lgtm

#12273 kyma delete is now undeploy
  docs/04-operation-guides/operations/07-uninstall-kyma.md
Labels: area/documentation, area/cli, size/XS, lgtm

#12262 Use main branch from website
  .kyma-project-io/build-preview.sh
Labels: size/XS, lgtm

#12245 Update python function runtime base image
  components/function-runtimes/python38/Dockerfile
  components/function-runtimes/python39/Dockerfile
Labels: hacktoberfest-accepted, size/S, lgtm

#12278 Remove axios-retry
  tests/fast-integration/logging/client.js
  tests/fast-integration/monitoring/client.js
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/utils/index.js
Labels: bug, area/monitoring, area/logging, size/M, lgtm

#12276 review CLI docs
  docs/01-overview/main-areas/ui/metadata.yaml
  docs/01-overview/main-areas/ui/ui-02-CLI.md
  docs/05-technical-reference/00-cli-commands/README.md
Labels: area/documentation, area/cli, size/S, lgtm

#12181 Add Central Gateway URL to the Application CustomResource using Application Registry
  components/application-registry/cmd/applicationregistry/applicationregistry.go
  components/application-registry/cmd/applicationregistry/options.go
  components/application-registry/go.mod
  components/application-registry/go.sum
  components/application-registry/hack/code-generator.go
  components/application-registry/hack/tools.go
  components/application-registry/internal/k8sconsts/mocks/NameResolver.go
  components/application-registry/internal/k8sconsts/nameresolver.go
  components/application-registry/internal/k8sconsts/nameresolver_test.go
  components/application-registry/internal/metadata/applications/repository.go
  components/application-registry/internal/metadata/applications/util.go
  components/application-registry/internal/metadata/serviceapi/mocks/Service.go
  components/application-registry/internal/metadata/serviceapi/serviceapiservice.go
  components/application-registry/internal/metadata/serviceapi/serviceapiservice_test.go
  components/application-registry/internal/metadata/servicedefservice.go
  components/application-registry/internal/metadata/servicedefservice_test.go
  components/application-registry/internal/metadata/specification/service.go
  components/application-registry/internal/metadata/specification/service_test.go
  resources/application-connector/charts/application-registry/templates/deployment.yaml
  resources/application-connector/charts/application-registry/values.yaml
  resources/application-connector/values.yaml
  resources/cluster-essentials/files/applications.applicationconnector.crd.yaml
Labels: enhancement, area/application-connector, size/XL, lgtm

#12277 fix broken links from kyma-governance-nightly
  README.md
  components/function-controller/cmd/jobinit/README.md
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/security/sec-03-access-kyma.md
Labels: area/documentation, size/S, lgtm

#12251 Bump serverless images
  resources/serverless/charts/docker-registry/values.yaml
  resources/serverless/values.yaml
Labels: hacktoberfest-accepted, size/S, lgtm

#12279 Skip istio sidecar for k3s-tests job
  resources/serverless/charts/k3s-tests/templates/k3s-test.yaml
Labels: size/XS, lgtm

#12212 Updates to kiali and logging chart values.yaml
  resources/kiali/templates/_helpers.tpl
  resources/kiali/templates/deployment.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/kiali/templates/tests/test.yaml
  resources/kiali/values.yaml
  resources/logging/charts/fluent-bit/templates/_pod.tpl
  resources/logging/charts/fluent-bit/values.yaml
  resources/logging/charts/logui/templates/deployment.yaml
  resources/logging/charts/logui/values.yaml
  resources/logging/charts/loki/templates/statefulset.yaml
  resources/logging/charts/loki/values.yaml
  resources/logging/templates/_helpers.tpl
  resources/logging/values.yaml
Labels: size/M, lgtm

#12285 regenerate build-init container image
  components/function-controller/deploy/jobinit/Dockerfile
Labels: hacktoberfest-accepted, size/XS, lgtm

#12225 Update values.yaml in compass-runtime-agent
  resources/compass-runtime-agent/templates/_helpers.tpl
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/templates/tests/test-runtime-agent-integration.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/S, lgtm

#12290 Reintroduce SBU tutorial for functions
  components/service-binding-usage-controller/examples/README.md
  docs/01-overview/main-areas/service-management/smgt-01-overview.md
  docs/03-tutorials/00-serverless/svls-10-bind-a-serviceinstance-to-a-function.md
Labels: size/L, lgtm

#12291 fix spelling
  docs/05-technical-reference/00-configuration-parameters/smsh-01-istio-chart.md
Labels: size/XS, lgtm

#12284 Update values.yaml in telemetry, testing
  resources/telemetry/charts/fluent-bit/templates/_pod.tpl
  resources/telemetry/charts/fluent-bit/templates/tests/test-connection.yaml
  resources/telemetry/charts/fluent-bit/values.yaml
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/values.yaml
  resources/testing/charts/octopus/templates/_helpers.tpl
  resources/testing/charts/octopus/templates/manager.yaml
  resources/testing/values.yaml
Labels: size/M, lgtm

#12280 Enabled non-mtls support for pushing traces
  resources/tracing/templates/kyma-additions/peerauthentication.yaml
  resources/tracing/values.yaml
Labels: bug, area/tracing, size/M, lgtm

#12281 Rename component istio to istio-configuration for Kyma installation
  installation/resources/components.yaml
Labels: size/XS, lgtm

#12289 Pull main on build
  .kyma-project-io/build-preview.sh
Labels: size/S, lgtm

#12295 Fix gcloud and custom DB Ory install
  resources/ory/files/secret-migration.sh
Labels: size/XS, lgtm
