Repository kyma-project/kyma, pull requests merged in 2021-07, with the labels that each got.

#11295 Central gateway application registry
  components/application-registry/go.mod
  components/application-registry/go.sum
  components/application-registry/internal/metadata/applications/repository.go
  components/application-registry/internal/metadata/applications/repository_test.go
  components/application-registry/internal/metadata/applications/util.go
  components/application-registry/internal/metadata/applications/util_test.go
  resources/application-connector/values.yaml
  tests/application-registry-tests/test/apitests/metadata_test.go
  tests/application-registry-tests/test/k8stests/k8sresource_test.go
Labels: lgtm, size/XL

#11598 Improve oidc configuration
  resources/busola-migrator/templates/deployment.yaml
  resources/busola-migrator/values.yaml
Labels: lgtm, size/XS

#11537 Add two docs and diagrams on authentication in Kyma 2.0
  docs/04-operation-guides/security/all-01-access-kyma.md
  docs/04-operation-guides/security/all-02-authentication-in-kyma.md
  docs/04-operation-guides/security/assets/all-authentication-diagram.svg
  docs/04-operation-guides/security/assets/all-kyma-dashboard.svg
  docs/04-operation-guides/security/assets/dex.svg
  docs/04-operation-guides/security/assets/kyma-access-console.svg
  docs/04-operation-guides/security/assets/kyma-access-kubectl.svg
Labels: area/documentation, area/security, lgtm, size/M

#11591 Clean Application Operator dependencies up
  components/application-operator/go.mod
  components/application-operator/go.sum
  resources/application-connector/values.yaml
Labels: area/application-connector, lgtm, size/L

#11606 Add resource quotas to cert removal backup job
  resources/application-connector/charts/connector-service/templates/helm-certs-removal-backup.yaml
Labels: lgtm, size/S

#11558 Module Upgrades
  components/application-connectivity-validator/go.mod
  components/application-connectivity-validator/go.sum
  components/application-gateway/go.mod
  components/application-gateway/go.sum
  components/application-registry/go.mod
  components/application-registry/go.sum
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  components/connection-token-handler/cmd/manager/manager.go
  components/connection-token-handler/go.mod
  components/connection-token-handler/go.sum
  components/connection-token-handler/pkg/apis/applicationconnector/v1alpha1/register.go
  components/connection-token-handler/pkg/controller/tokenrequest/tokenrequest_controller.go
  tests/application-operator-tests/go.mod
  tests/application-operator-tests/go.sum
  tests/application-registry-tests/go.mod
  tests/application-registry-tests/go.sum
  tests/application-registry-tests/test/testkit/k8sresources_client.go
Labels: lgtm, size/XXL

#11575 Upgrade The Rafter images
  resources/rafter/values.yaml
Labels: area/core-and-supporting, bug, lgtm, size/XS

#11613 Missing PR Values Update
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: lgtm, size/S

#11610 Deduplicate subscription filters
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/api/v1alpha1/subscription_types_test.go
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  components/eventing-controller/pkg/handlers/beb_test.go
  components/eventing-controller/pkg/handlers/eventtype/clean.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/pkg/handlers/test_helpers.go
  components/eventing-controller/pkg/handlers/utils.go
  components/eventing-controller/pkg/handlers/utils_test.go
  components/eventing-controller/reconciler/subscription-nats/reconciler_test.go
  components/eventing-controller/reconciler/subscription/reconciler_test.go
  components/eventing-controller/testing/subscriber.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, lgtm, size/L

#11603 Wait for service plan in test scenario
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/utils/index.js
Labels: lgtm, size/S

#11535 Change insensitive terms into their inclusive alternatives
  resources/api-gateway/templates/_helpers.tpl
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/values.yaml
Labels: lgtm, size/S

#11617 Increase resource limits in helm certs backup job
  resources/application-connector/charts/connector-service/templates/helm-certs-removal-backup.yaml
Labels: lgtm, size/XS

#11440 Fast-integration tests oauth tokens handling refactoring
  tests/fast-integration/compass/client.js
  tests/fast-integration/kyma-environment-broker/client.js
  tests/fast-integration/lib/oauth.js
Labels: lgtm, size/L

#11618 Bump version to release 1.24.0
  VERSION
  installation/resources/installer.yaml
Labels: lgtm, size/XS

#11594 Upgrade Grafana to latest Apache licensed version
  resources/monitoring/charts/grafana/Chart.yaml
  resources/monitoring/charts/grafana/templates/_helpers.tpl
  resources/monitoring/charts/grafana/templates/_pod.tpl
  resources/monitoring/charts/grafana/templates/configmap-dashboard-provider.yaml
  resources/monitoring/charts/grafana/templates/configmap.yaml
  resources/monitoring/charts/grafana/templates/deployment.yaml
  resources/monitoring/charts/grafana/templates/image-renderer-deployment.yaml
  resources/monitoring/charts/grafana/templates/image-renderer-service.yaml
  resources/monitoring/charts/grafana/templates/ingress.yaml
  resources/monitoring/charts/grafana/templates/podsecuritypolicy.yaml
  resources/monitoring/charts/grafana/templates/pvc.yaml
  resources/monitoring/charts/grafana/templates/secret.yaml
  resources/monitoring/charts/grafana/templates/service.yaml
  resources/monitoring/charts/grafana/templates/statefulset.yaml
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring, lgtm, size/L

#11580 Update installer version
  installation/resources/installer.yaml
Labels: lgtm, size/XS

#11577 upgrade to loki 2.2.1
  resources/logging/charts/fluent-bit/values.yaml
  resources/logging/charts/loki/Chart.yaml
  resources/logging/charts/loki/templates/serviceaccount.yaml
  resources/logging/charts/loki/values.yaml
Labels: area/logging, lgtm, size/S

#11626 bump alpine
  components/kyma-operator/Dockerfile
Labels: lgtm, size/XS

#11627 Bump kyma operator
  tools/kyma-installer/kyma.Dockerfile
Labels: lgtm, size/XS

#11568 Use latest minio image
  resources/rafter/values.yaml
Labels: area/documentation, lgtm, size/XS

#11498 Add Python39 runtime
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/samples/serverless_v1alpha1_function_python39.yaml
  components/function-controller/internal/controllers/serverless/build_resources.go
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  components/function-controller/internal/controllers/serverless/runtime/runtime.go
  components/function-controller/internal/controllers/serverless/runtime/runtime_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha1/runtime_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha1/zz_generated.deepcopy.go
  components/function-runtimes/Makefile
  components/function-runtimes/python39/Dockerfile
  components/function-runtimes/python39/kubeless/.gitignore
  components/function-runtimes/python39/kubeless/kubeless.py
  components/function-runtimes/python39/kubeless/requirements.txt
  docs/serverless/03-01-function-specification.md
  docs/serverless/03-02-available-runtimes.md
  docs/serverless/03-04-git-source-type.md
  docs/serverless/06-01-function-cr.md
  installation/resources/crds/serverless/functions.serverless.crd.yaml
  resources/cluster-essentials/files/functions.serverless.crd.yaml
  resources/serverless/templates/runtimes.yaml
  resources/serverless/values.yaml
Labels: lgtm, size/XL

#11632 Fix links returning 404 error
  docs/service-mesh/10-02-no-access.md
Labels: area/documentation, lgtm, size/XS

#11612 Migrate serverless admission webhooks to v1
  resources/serverless/charts/webhook/templates/webhooks.yaml
  resources/serverless/templates/admission_webhook.yaml
Labels: area/serverless, enhancement, lgtm, size/S

#11538 Add Recipe for using custom OIDC Idp
  docs/03-tutorials/03-set-up-idp.md
Labels: lgtm, size/L

#11569 Update jaegertracing crd in cluster essentials
  resources/cluster-essentials/files/jaegers.jaegertracing.crd.yaml
Labels: lgtm, size/M

#11602 Delete Istio 1.8 workarounds
  resources/service-catalog/charts/catalog/templates/controller-manager-policy.yaml
Labels: lgtm, size/XS

#11642 Remove redundant DestinationRule
  docs/service-mesh/03-01-istio-setup-in-kyma.md
  resources/istio/files/destination-rules.yaml
  resources/istio/templates/configmap-extra-manifests.yaml
Labels: lgtm, size/S

#11623 Replace satori/go.uuid with google/uuid in Application Registry
  components/application-registry/go.mod
  components/application-registry/go.sum
  resources/application-connector/values.yaml
Labels: area/application-connector, area/security, lgtm, size/M

#11648 Update crabtree assignment in CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/M

#11624 Central application gateway simplify API
  components/central-application-gateway/README.md
  components/central-application-gateway/cmd/applicationgateway/applicationproxy.go
  components/central-application-gateway/cmd/applicationgateway/options.go
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/central-application-gateway/internal/metadata/applications/repository.go
  components/central-application-gateway/internal/metadata/applications/repository_test.go
  components/central-application-gateway/internal/metadata/servicedefservice.go
  resources/application-connector/charts/central-application-gateway/templates/deployment.yaml
  resources/application-connector/charts/central-application-gateway/templates/service.yaml
  resources/application-connector/values.yaml
Labels: lgtm, size/L

#11582 update Observability diagrams
  docs/01-overview/02-main-areas/README.md
  docs/01-overview/02-main-areas/observability/obsv-01-telemetry-observability-overview.md
  docs/03-tutorials/observability/assets/monitoring-tutorials.svg
  docs/03-tutorials/observability/obsv-01-monitoring-overview.md
  docs/05-technical-reference/03-architecture/assets/obsv-logging-architecture.svg
  docs/05-technical-reference/03-architecture/assets/obsv-monitoring-architecture.svg
  docs/05-technical-reference/03-architecture/assets/obsv-monitoring-flow.svg
  docs/05-technical-reference/03-architecture/assets/obsv-tracing-architecture.svg
  docs/05-technical-reference/03-architecture/obsv-01-architecture-monitoring.md
  docs/05-technical-reference/03-architecture/obsv-02-architecture-logging.md
  docs/05-technical-reference/03-architecture/obsv-03-architecture-tracing.md
  docs/05-technical-reference/assets/obsv-logging-arch-test.svg
  docs/05-technical-reference/assets/obsv-monitoring-architecture-variant.svg
  docs/05-technical-reference/assets/obsv-monitoring-architecture.svg
Labels: area/documentation, lgtm, size/M

#11655 Use the same version of the OAuth2Client CRD as installation
  components/eventing-controller/Makefile
  components/eventing-controller/config/crd/external/README.md
  components/eventing-controller/config/crd/external/apirules-gateway-kyma-project-io.yaml
  components/eventing-controller/config/crd/external/hydra.ory.sh_oauth2clients.yaml
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, lgtm, size/XL

#11619 Add kubeconfigID override to busola-migrator
  components/busola-migrator/README.md
  components/busola-migrator/internal/busola/encoder.go
  components/busola-migrator/internal/busola/encoder_test.go
  components/busola-migrator/internal/busola/init.go
  components/busola-migrator/internal/busola/init_test.go
  components/busola-migrator/internal/config/config.go
  components/busola-migrator/main.go
  resources/busola-migrator/templates/deployment.yaml
  resources/busola-migrator/values.yaml
Labels: lgtm, size/L

#11634 Optimze HTTP header access in test
  components/event-publisher-proxy/pkg/handler/beb/handler_test.go
  components/event-publisher-proxy/testing/utils.go
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, lgtm, size/M

#11656 Update function-controller tests for python39
  components/function-controller/config/samples/serverless_v1alpha1_funtion_python39.yaml
  resources/serverless/values.yaml
  tests/function-controller/go.mod
  tests/function-controller/go.sum
  tests/function-controller/testsuite/runtimes/python.go
  tests/function-controller/testsuite/scenarios/light_runtimes.go
Labels: lgtm, size/L

#11657 Restrict fluent-bit pod permissions
  resources/logging/charts/fluent-bit/values.yaml
Labels: lgtm, size/S

#11671 Fix links to Gardener documentation
  docs/kyma/04-03-cluster-installation.md
  docs/security/10-03-certificates-gardener.md
Labels: area/documentation, bug, lgtm, size/XS

#11677 fixed jaeger CRD schema
  installation/resources/crds/tracing/jaegers.jaegertracing.crd.yaml
  resources/cluster-essentials/files/jaegers.jaegertracing.crd.yaml
Labels: area/tracing, bug, lgtm, size/M

#11651 Enhance Eventing controller logs
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/pkg/application/clean_test.go
  components/eventing-controller/pkg/application/fake/lister.go
  components/eventing-controller/pkg/application/lister.go
  components/eventing-controller/pkg/commander/beb/beb.go
  components/eventing-controller/pkg/commander/beb/beb_test.go
  components/eventing-controller/pkg/commander/nats/nats.go
  components/eventing-controller/pkg/commander/nats/nats_test.go
  components/eventing-controller/pkg/ems/api/events/client/client.go
  components/eventing-controller/pkg/ems/auth/auth_test.go
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/pkg/handlers/beb_test.go
  components/eventing-controller/pkg/handlers/eventtype/clean.go
  components/eventing-controller/pkg/handlers/eventtype/clean_test.go
  components/eventing-controller/pkg/handlers/eventtype/parse.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/pkg/handlers/utils.go
  components/eventing-controller/pkg/informers/sync.go
  components/eventing-controller/pkg/object/equality_test.go
  components/eventing-controller/reconciler/backend/reconciler.go
  components/eventing-controller/reconciler/backend/reconciler_test.go
  components/eventing-controller/reconciler/errors/skip.go
  components/eventing-controller/reconciler/errors/skip_test.go
  components/eventing-controller/reconciler/subscription-nats/reconciler.go
  components/eventing-controller/reconciler/subscription-nats/reconciler_test.go
  components/eventing-controller/reconciler/subscription/reconciler.go
  components/eventing-controller/reconciler/subscription/reconciler_test.go
  components/eventing-controller/testing/cloudevent.go
  components/eventing-controller/testing/subscriber.go
  components/eventing-controller/utils/utils.go
  components/eventing-controller/utils/utils_test.go
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, lgtm, size/XXL

#11649 Fix tracing for publisher and controller
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/event-publisher-proxy/pkg/handler/handlertest/handlertest.go
  components/event-publisher-proxy/pkg/handler/nats/handler.go
  components/event-publisher-proxy/pkg/legacy-events/legacy.go
  components/event-publisher-proxy/pkg/tracing/helpers.go
  components/event-publisher-proxy/pkg/tracing/helpers_test.go
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/pkg/tracing/tracing.go
  components/eventing-controller/pkg/tracing/tracing_test.go
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/L

#11419 Update fast-integration test to support switching Eventing backends
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
Labels: area/eventing, lgtm, size/XS

#11682 Security rafter curl
  resources/rafter/values.yaml
  tests/rafter/Dockerfile
Labels: lgtm, size/XS

#11690 removing xip.io from docu
  docs/03-tutorials/observability/obsv-03-create-and-configure-grafana-dashboard.md
  docs/04-operation-guides/security/09-tls-certificates-security.md
  docs/04-operation-guides/troubleshooting/troubleshoot-certificates-gardener.md
  docs/04-operation-guides/troubleshooting/troubleshoot-console-network-error.md
  docs/05-technical-reference/06-custom-resources/custrsrc-runtimeagent-compass-connection.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
Labels: lgtm, size/M

#11680 added a psp specific for fluent-bit
  resources/logging/charts/fluent-bit/templates/psp.yaml
  resources/logging/charts/fluent-bit/values.yaml
Labels: area/logging, lgtm, size/S

#11669 Add prerequisites and provisioning
  docs/04-operation-guides/operations/01-install-kyma.md
  docs/04-operation-guides/operations/07-uninstall-kyma.md
Labels: lgtm, size/M

#11640 improve Observability Overview
  docs/01-overview/02-main-areas/README.md
  docs/01-overview/02-main-areas/observability/obsv-01-telemetry-observability-overview.md
Labels: area/documentation, lgtm, size/M

#11675 Cleanup Overrides - Adapt Production Profil and Base Chart
  resources/logging/charts/fluent-bit/values.yaml
  resources/monitoring/profile-production.yaml
Labels: lgtm, size/M

#11693 Disable AlertManager Alert
  resources/monitoring/templates/prometheus/rules-1.14/prometheus.yaml
Labels: lgtm, size/XS

#11661 Update node exporter chart
  resources/monitoring/charts/prometheus-node-exporter/Chart.yaml
  resources/monitoring/charts/prometheus-node-exporter/templates/daemonset.yaml
  resources/monitoring/charts/prometheus-node-exporter/templates/monitor.yaml
  resources/monitoring/charts/prometheus-node-exporter/templates/psp.yaml
  resources/monitoring/charts/prometheus-node-exporter/templates/serviceaccount.yaml
  resources/monitoring/charts/prometheus-node-exporter/values.yaml
Labels: lgtm, size/L

#11666 Update wookiees codeowners
  .kyma-project-io/build-preview.sh
  CODEOWNERS
  OWNERS_ALIASES
  components/compass-runtime-agent/OWNERS
  resources/compass-runtime-agent/OWNERS
  resources/rafter/OWNERS
  resources/rafter/charts/asyncapi-service/Chart.yaml
  resources/rafter/charts/controller-manager/Chart.yaml
  resources/rafter/charts/front-matter-service/Chart.yaml
  resources/rafter/charts/upload-service/Chart.yaml
  resources/serverless/charts/webhook/Chart.yaml
  tests/compass-runtime-agent/OWNERS
Labels: area/serverless, enhancement, lgtm, size/M

#11708 Fix Serverless admission webhook
  resources/serverless/charts/webhook/templates/webhooks.yaml
  resources/serverless/templates/admission_webhook.yaml
Labels: area/serverless, bug, lgtm, size/XS

#11707 fix of securityContext in node-exporter
  resources/monitoring/charts/prometheus-node-exporter/templates/daemonset.yaml
  resources/monitoring/charts/prometheus-node-exporter/templates/psp.yaml
  resources/monitoring/charts/prometheus-node-exporter/values.yaml
Labels: lgtm, size/S

#11687 Insert correct helm broker and node exporter link in doc
  docs/helm-broker/01-01-helm-broker.md
  docs/monitoring/02-01-monitoring.md
Labels: lgtm, size/XS

#11712 Add readiness probes to OAuth2 proxies
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
Labels: area/monitoring, area/tracing, lgtm, size/S

#11705 Update istio version, kiali and tracing overrides
  tests/fast-integration/installer/config-istio.yaml
  tests/fast-integration/installer/index.js
  tests/fast-integration/utils/index.js
Labels: lgtm, size/M

#11718 Re-structure Service Mesh, Security and API Gateway docs
  docs/01-overview/02-main-areas/README.md
  docs/01-overview/02-main-areas/api-exposure/apix-01-api-gateway.md
  docs/01-overview/02-main-areas/api-exposure/apix-02-whitelisted-domains.md
  docs/01-overview/02-main-areas/api-exposure/apix-03-blacklisted-services.md
  docs/01-overview/02-main-areas/api-exposure/metadata.yaml
  docs/01-overview/02-main-areas/assets/kyma-areas.svg
  docs/01-overview/02-main-areas/service-mesh/smsh-01-overview.md
  docs/01-overview/02-main-areas/service-mesh/smsh-02-default-istio-setup-in-kyma.md
  docs/03-tutorials/api-exposure/apix-01-expose-service-apigateway.md
  docs/03-tutorials/api-exposure/apix-02-expose-and-secure-service.md
  docs/03-tutorials/api-exposure/apix-03-config-authorizations-apigateway.md
  docs/04-operation-guides/operations/smsh-01-istio-disable-sidecar-injection.md
  docs/04-operation-guides/operations/smsh-02-istio-provide-custom-config.md
  docs/04-operation-guides/security/README.md
  docs/04-operation-guides/security/sec-01-concept-roles.md
  docs/04-operation-guides/security/sec-02-authentication-in-kyma.md
  docs/04-operation-guides/security/sec-03-authorization-in-kyma.md
  docs/04-operation-guides/security/sec-04-access-kyma.md
  docs/04-operation-guides/security/sec-05-customization-operation.md
  docs/04-operation-guides/security/sec-06-production-profile.md
  docs/04-operation-guides/security/sec-07-tls-certificates-security.md
  docs/04-operation-guides/troubleshooting/apix-01-apigateway-connect-api-rule.md
  docs/04-operation-guides/troubleshooting/sec-01-console-403-forbidden.md
  docs/04-operation-guides/troubleshooting/sec-02-certificates-gardener.md
  docs/04-operation-guides/troubleshooting/sec-03-console-not-enough-permissions.md
  docs/04-operation-guides/troubleshooting/smsh-01-console-503-no-access.md
  docs/04-operation-guides/troubleshooting/smsh-02-connection-refused.md
  docs/04-operation-guides/troubleshooting/smsh-03-istio-no-sidecar.md
  docs/04-operation-guides/troubleshooting/smsh-04-istio-sidecar-version.md
  docs/05-technical-reference/03-architecture/apix-01-architecture-apigateway.md
  docs/05-technical-reference/05-configuration-parameters/sec-01-cluster-users.md
  docs/05-technical-reference/06-custom-resources/apix-01-apirule.md
Labels: lgtm, size/M

#11486 Add service management documentation
  docs/01-overview/02-main-areas/service-management/assets/aws-class.png
  docs/01-overview/02-main-areas/service-management/assets/azure-service-broker-class.png
  docs/01-overview/02-main-areas/service-management/assets/gcp-class.png
  docs/01-overview/02-main-areas/service-management/smgt-01-sc-overview.md
  docs/01-overview/02-main-areas/service-management/smgt-02-brokers-overview.md
  docs/01-overview/02-main-areas/service-management/smgt-03-sc-resources.md
  docs/01-overview/02-main-areas/service-management/smgt-10-hb-overview.md
  docs/01-overview/02-main-areas/service-management/smgt-99-useful-links.md
  docs/03-tutorials/eventing/placeholder.md
  docs/03-tutorials/service-management/assets/binding.svg
  docs/03-tutorials/service-management/assets/deprovisioning.svg
  docs/03-tutorials/service-management/assets/hb-provisioning.svg
  docs/03-tutorials/service-management/assets/provisioning-and-binding.svg
  docs/03-tutorials/service-management/assets/provisioning.svg
  docs/03-tutorials/service-management/assets/unbinding-deprovisioning.svg
  docs/03-tutorials/service-management/assets/unbinding.svg
  docs/03-tutorials/service-management/assets/usagekind.svg
  docs/03-tutorials/service-management/placeholder.md
  docs/03-tutorials/service-management/smgt-01-sc-provisioning.md
  docs/03-tutorials/service-management/smgt-02-sc-deprovisioning.md
  docs/03-tutorials/service-management/smgt-03-sc-broker-registration.md
  docs/03-tutorials/service-management/smgt-11-hb-create-addons.md
  docs/03-tutorials/service-management/smgt-12-hb-bind-addons.md
  docs/03-tutorials/service-management/smgt-13-hb-test-addons.md
  docs/03-tutorials/service-management/smgt-14-hb-create-addons-repo.md
  docs/03-tutorials/service-management/smgt-15-hb-check-addons.md
  docs/03-tutorials/service-management/smgt-16-hb-register-addons-sc.md
  docs/03-tutorials/service-management/smgt-17-hb-provision-addons-sc.md
  docs/03-tutorials/tut-security-overview.md
  docs/04-operation-guides/troubleshooting/README.md
  docs/04-operation-guides/troubleshooting/smgt-01-instance-failed-status.md
  docs/04-operation-guides/troubleshooting/smgt-02-id-conflict.md
  docs/05-technical-reference/03-architecture/assets/smgt-hb-cluster.svg
  docs/05-technical-reference/03-architecture/assets/smgt-hb-deep-dive.svg
  docs/05-technical-reference/03-architecture/assets/smgt-hb-namespaced.svg
  docs/05-technical-reference/03-architecture/assets/smgt-sc-architecture.svg
  docs/05-technical-reference/03-architecture/smgt-01-sc.md
  docs/05-technical-reference/03-architecture/smgt-10-hb.md
  docs/05-technical-reference/03-architecture/smgt-11-hb-deep-dive.md
  docs/05-technical-reference/05-configuration-parameters/README.md
  docs/05-technical-reference/05-configuration-parameters/smgt-01-sc-catalog-subchart.md
  docs/05-technical-reference/05-configuration-parameters/smgt-02-sc-podpreset-subchart.md
  docs/05-technical-reference/05-configuration-parameters/smgt-03-hb-chart.md
  docs/05-technical-reference/05-configuration-parameters/smgt-04-hb-etcd-subchart.md
  docs/05-technical-reference/06-custom-resources/smgt-01-sc-sbu.md
  docs/05-technical-reference/06-custom-resources/smgt-02-sc-usage-kind.md
  docs/05-technical-reference/06-custom-resources/smgt-03-hb-clusteraddonsconfiguration.md
  docs/05-technical-reference/06-custom-resources/smgt-04-hb-addonsconfiguration.md
Labels: area/documentation, lgtm, size/XXL

#11725 Replace Console with Kyma Dashboard
  docs/04-operation-guides/operations/01-install-kyma.md
Labels: area/documentation, area/installation, lgtm, size/XS

#11621 Use Nats queue subscriptions
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/api/v1alpha1/subscription_types_test.go
  components/eventing-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_eventingbackends.yaml
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/pkg/commander/beb/beb.go
  components/eventing-controller/pkg/commander/commander.go
  components/eventing-controller/pkg/commander/fake/commander.go
  components/eventing-controller/pkg/commander/nats/nats.go
  components/eventing-controller/pkg/commander/nats/nats_test.go
  components/eventing-controller/pkg/env/backend_config.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/pkg/handlers/utils.go
  components/eventing-controller/reconciler/backend/reconciler.go
  components/eventing-controller/reconciler/backend/reconciler_test.go
  components/eventing-controller/reconciler/subscription-nats/reconciler.go
  components/eventing-controller/reconciler/subscription-nats/reconciler_test.go
  components/eventing-controller/testing/matchers.go
  installation/resources/crds/eventing/eventingbackends.eventing.kyma-project.io.crd.yaml
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/cluster-essentials/files/eventingbackends.eventing.kyma-project.io.crd.yaml
  resources/cluster-essentials/files/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, lgtm, size/XL

#11703 Use the correct memory metrics to get memory usage in the container
  resources/monitoring/templates/grafana/dashboards-1.14/statefulset.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/kyma-backends.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/kyma-controllers.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/kyma-frontends.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/pods.yaml
  resources/monitoring/templates/prometheus/rules-1.14/k8s.rules.yaml
Labels: lgtm, size/M

#11700 Update secret-migration script
  resources/ory/files/secret-migration.sh
Labels: lgtm, size/XS

#11691 bump deps in kyma-operator
  components/kyma-operator/go.mod
  components/kyma-operator/go.sum
  components/kyma-operator/pkg/kymahelm/kyma-helm-client.go
Labels: lgtm, size/L

#11737 Bump helm
  components/kyma-operator/go.mod
  components/kyma-operator/go.sum
  components/kyma-operator/pkg/kymahelm/kyma-helm-client.go
Labels: lgtm, size/L

#11692 bump kyma-operator
  tools/kyma-installer/kyma.Dockerfile
Labels: lgtm, size/XS

#11736 Update version to 1.24.1
  VERSION
  installation/resources/installer.yaml
Labels: lgtm, size/XS

#11742 Bump kyma operator
  tools/kyma-installer/kyma.Dockerfile
Labels: lgtm, size/XS

#11728 Add liveness and readiness probes to application-operator
  resources/application-connector/charts/application-operator/templates/controller.yaml
  resources/application-connector/charts/application-operator/values.yaml
Labels: area/application-connector, enhancement, lgtm, size/S

#11743 Use the correct memory metrics to get memory usage in the container (…
  resources/monitoring/templates/grafana/dashboards-1.14/statefulset.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/kyma-backends.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/kyma-controllers.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/kyma-frontends.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/pods.yaml
  resources/monitoring/templates/prometheus/rules-1.14/k8s.rules.yaml
Labels: lgtm, size/M, tide/merge-blocker

#11670 Add administrators list
  resources/cluster-users/templates/rbac-roles.yaml
  resources/cluster-users/values.yaml
Labels: lgtm, size/S

#11733 Use timeout on channel read
  components/eventing-controller/reconciler/subscription-nats/reconciler_test.go
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, lgtm, size/M

#11735 Add liveness and readiness probes to prometheus operator
  resources/monitoring/templates/prometheus-operator/deployment.yaml
  resources/monitoring/values.yaml
Labels: area/monitoring, enhancement, lgtm, size/L

#11740 Fix invalid crd
  installation/resources/crds/tracing/jaegers.jaegertracing.crd.yaml
Labels: lgtm, size/XS

#11721 adjusted the fluent-bit PSP to the actual pod requirements
  resources/logging/charts/fluent-bit/templates/_pod.tpl
  resources/logging/charts/fluent-bit/templates/clusterrole.yaml
  resources/logging/charts/fluent-bit/templates/psp.yaml
  resources/logging/charts/fluent-bit/values.yaml
Labels: lgtm, size/M

#11759 Increase memory limit for eval profile
  resources/eventing/profile-evaluation.yaml
Labels: lgtm, size/XS

#11730 Add liveness and readiness probes to api gateway
  resources/api-gateway/templates/deployment.yaml
Labels: area/api-gateway, enhancement, lgtm, size/XS

#11741 Add liveness/readiness probes to ory-hydra-maester
  resources/ory/charts/hydra/charts/hydra-maester/templates/deployment.yaml
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
Labels: area/api-gateway, enhancement, lgtm, size/S

#11744 Add missing liveness/readiness probes to serverless pods
  resources/serverless/charts/webhook/templates/deployment.yaml
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/values.yaml
Labels: area/serverless, enhancement, lgtm, size/M

#11778 Fix a typo in the central_application_connectivity_validator parameter name
  docs/application-connector/05-00-application-connector.md
Labels: area/application-connector, bug, lgtm, size/XS

#11779 Fix a typo in the central_application_connectivity_validator parameter name
  docs/application-connector/05-00-application-connector.md
Labels: area/application-connector, bug, lgtm, size/XS

#11772 Replace uuid library in Application Registry
  components/application-registry/go.mod
  components/application-registry/go.sum
Labels: area/application-connector, area/security, lgtm, size/S

#11771 made kubelet alert rule resilient to muliple kubelet scrapeconfigs
  resources/monitoring/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
Labels: area/monitoring, bug, lgtm, size/XS

#11781 New Code Owners
  CODEOWNERS
Labels: lgtm, size/M

#11782 Bump Application Registry image to introduce fix
  resources/application-connector/values.yaml
Labels: area/application-connector, area/security, lgtm, size/XS

#11776 Remove HB and SBU clear job hooks from charts
  resources/helm-broker/templates/clear-cr-job.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/clear-cr-job.yaml
Labels: lgtm, size/L

#11752 Document easy back-channel communication from function to eventing backend
  docs/serverless/08-04-trigger-function-with-event.md
Labels: area/serverless, lgtm, size/M

#11787 Fix Eventing 2.0 docs links and structure
  docs/01-overview/02-main-areas/eventing/evnt-02-useful-links.md
  docs/05-technical-reference/03-architecture/ac-04-application-broker.md
  docs/05-technical-reference/03-architecture/evnt-01-architecture.md
  docs/05-technical-reference/assets/evnt-processing-flow.svg
  docs/05-technical-reference/evnt-01-event-processing.md
Labels: area/documentation, lgtm, size/S

#11729 review backup docs
  docs/04-operation-guides/operations/10-backup-kyma.md
  docs/04-operation-guides/operations/13-restore-kyma-with-velero.md
  docs/04-operation-guides/operations/15-backup-volume-snapshots.md
Labels: area/documentation, lgtm, size/XL

#11713 update istio monitoring doc
  docs/01-overview/02-main-areas/assets/monitoring-istio.svg
  docs/01-overview/02-main-areas/observability/assets/monitoring-istio.svg
  docs/01-overview/02-main-areas/observability/obsv-01-telemetry-observability-overview.md
  docs/01-overview/02-main-areas/observability/obsv-03-istio-monitoring.md
  docs/01-overview/02-main-areas/service-mesh/con-monitoring-istio.md
  docs/04-operation-guides/operations/05-upgrade-kyma.md
  docs/04-operation-guides/troubleshooting/obsv-01-troubleshoot-prometheus-istio-server-crash-oom.md
Labels: area/documentation, lgtm, size/L

#11792 Restart authProxy pods when configuration changes
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
Labels: lgtm, size/XS

#11717 Add cosign step to kyma components
  common/makefiles/generic-make-go.mk
Labels: lgtm, size/XS

#11785 Remove old code
  resources/serverless/values.yaml
  tests/function-controller/pkg/namespace/namespace.go
Labels: lgtm, size/XS

#11456 Update crds application connector
  components/compass-runtime-agent/Makefile
  components/compass-runtime-agent/hack/Dockerfile
  components/compass-runtime-agent/internal/compassconnection/testdata/compass-connection.crd.yaml
  components/compass-runtime-agent/pkg/apis/compass/v1alpha1/types.go
  components/compass-runtime-agent/pkg/client/clientset/versioned/fake/register.go
  components/compass-runtime-agent/pkg/client/listers/compass/v1alpha1/compassconnection.go
  installation/resources/crds/application-connector/applicationmappings.applicationconnector.crd.yaml
  installation/resources/crds/application-connector/applications.applicationconnector.crd.yaml
  installation/resources/crds/application-connector/centralconnections.applicationconnector.crd.yaml
  installation/resources/crds/application-connector/certificaterequests.applicationconnector.crd.yaml
  installation/resources/crds/application-connector/eventactivations.applicationconnector.crd.yaml
  installation/resources/crds/application-connector/tokenrequests.applicationconnector.crd.yaml
  installation/resources/crds/compass-runtime-agent/compass-connection.crd.yaml
  resources/cluster-essentials/files/applications.applicationconnector.crd.yaml
  resources/cluster-essentials/files/centralconnections.applicationconnector.crd.yaml
  resources/cluster-essentials/files/certificaterequests.applicationconnector.crd.yaml
  resources/cluster-essentials/files/compass-connection.crd.yaml
  resources/compass-runtime-agent/values.yaml
  tests/fast-integration/installer/kyma-crds.js
Labels: lgtm, size/XXL

#11790 Removing new eventing as it is the default
  tests/fast-integration/compass-test/compass-test.js
  tests/fast-integration/installer/index.js
  tests/fast-integration/kyma.js
  tests/fast-integration/test/1-install.js
Labels: lgtm, size/S

#11791 Security python expat
  components/function-runtimes/python38/Dockerfile
  resources/serverless/values.yaml
Labels: lgtm, size/S

#11684 SKR SVCAT migration test
  tests/fast-integration/Makefile
  tests/fast-integration/installer/helm.js
  tests/fast-integration/package.json
  tests/fast-integration/skr-svcat-migration-test/.env.template
  tests/fast-integration/skr-svcat-migration-test/readme.md
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
  tests/fast-integration/skr-test/skr-test.js
Labels: lgtm, size/L

#11789 Remove subscription-migration job fro app-broker
  resources/application-connector/charts/application-broker/templates/subscription-migration.yaml
Labels: lgtm, size/L

#11797 Security issues nodejs12 and nodejs14
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
  resources/serverless/values.yaml
Labels: lgtm, size/S

#11801 add voigt and wozniakjan to codeowners for fastlane
  CODEOWNERS
Labels: lgtm, size/XS

#11803 Add check for existing kyma installation pre pipeline installation changes
  tests/fast-integration/installer/index.js
Labels: lgtm, size/XS

#11800 Add skhalash to fast-integration tests codeowners
  CODEOWNERS
Labels: lgtm, size/XS

#11720 Add telemetry operator
  CODEOWNERS
  components/telemetry-operator/.dockerignore
  components/telemetry-operator/.gitignore
  components/telemetry-operator/Dockerfile
  components/telemetry-operator/Makefile
  components/telemetry-operator/PROJECT
  components/telemetry-operator/README.md
  components/telemetry-operator/api/v1alpha1/groupversion_info.go
  components/telemetry-operator/api/v1alpha1/loggingconfiguration_types.go
  components/telemetry-operator/api/v1alpha1/zz_generated.deepcopy.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_loggingconfigurations.yaml
  components/telemetry-operator/config/crd/kustomization.yaml
  components/telemetry-operator/config/crd/kustomizeconfig.yaml
  components/telemetry-operator/config/crd/patches/cainjection_in_loggingconfigurations.yaml
  components/telemetry-operator/config/crd/patches/webhook_in_loggingconfigurations.yaml
  components/telemetry-operator/config/default/kustomization.yaml
  components/telemetry-operator/config/default/manager_auth_proxy_patch.yaml
  components/telemetry-operator/config/default/manager_config_patch.yaml
  components/telemetry-operator/config/manager/controller_manager_config.yaml
  components/telemetry-operator/config/manager/kustomization.yaml
  components/telemetry-operator/config/manager/manager.yaml
  components/telemetry-operator/config/prometheus/kustomization.yaml
  components/telemetry-operator/config/prometheus/monitor.yaml
  components/telemetry-operator/config/rbac/auth_proxy_client_clusterrole.yaml
  components/telemetry-operator/config/rbac/auth_proxy_role.yaml
  components/telemetry-operator/config/rbac/auth_proxy_role_binding.yaml
  components/telemetry-operator/config/rbac/auth_proxy_service.yaml
  components/telemetry-operator/config/rbac/kustomization.yaml
  components/telemetry-operator/config/rbac/leader_election_role.yaml
  components/telemetry-operator/config/rbac/leader_election_role_binding.yaml
  components/telemetry-operator/config/rbac/loggingconfiguration_editor_role.yaml
  components/telemetry-operator/config/rbac/loggingconfiguration_viewer_role.yaml
  components/telemetry-operator/config/rbac/role.yaml
  components/telemetry-operator/config/rbac/role_binding.yaml
  components/telemetry-operator/config/rbac/service_account.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_loggingconfiguration.yaml
  components/telemetry-operator/controllers/loggingconfiguration_controller.go
  components/telemetry-operator/controllers/loggingconfiguration_controller_test.go
  components/telemetry-operator/controllers/suite_test.go
  components/telemetry-operator/go.mod
  components/telemetry-operator/go.sum
  components/telemetry-operator/hack/boilerplate.go.txt
  components/telemetry-operator/main.go
Labels: lgtm, size/XXL

#11798 Document how to setup event subscriptions via kyma CLI
  docs/02-get-started/13-trigger-function-with-event.md
Labels: area/cli, area/documentation, area/eventing, area/serverless, lgtm, size/M

#11697 Allow for easy back-channel communication from function to eventing backend
  components/function-controller/internal/controllers/serverless/build_resources.go
  components/function-controller/internal/controllers/serverless/config.go
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/kubeless.js
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/lib/ce.js
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/package.json
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/kubeless.js
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/lib/ce.js
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/package.json
  components/function-runtimes/python38/kubeless/kubeless.py
  components/function-runtimes/python38/kubeless/requirements.txt
  components/function-runtimes/python39/kubeless/kubeless.py
  components/function-runtimes/python39/kubeless/requirements.txt
  resources/serverless/templates/deployment.yaml
  resources/serverless/values.yaml
Labels: area/serverless, lgtm, size/L

#11809 Helm wait fix
  components/kyma-operator/pkg/kymahelm/kyma-helm-client.go
Labels: lgtm, size/S

#11812 fixing helm waiting issue
  components/kyma-operator/pkg/kymahelm/kyma-helm-client.go
Labels: lgtm, size/S

#11816 Move skipping of kyma installation to affected tests themselves
  tests/fast-integration/compass-test/compass-test.js
  tests/fast-integration/installer/index.js
  tests/fast-integration/test/1-install.js
Labels: lgtm, size/S

#11815 bump kyma-operator
  tools/kyma-installer/kyma.Dockerfile
Labels: lgtm, size/XS

#11813 Remove missing Make dependency from telemetry-operator
  components/telemetry-operator/Makefile
Labels: lgtm, size/XS

#11817 Parse smctl response for fast-integration tests
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
Labels: lgtm, size/S

#11814 Update to version 1.24.2
  VERSION
  installation/resources/installer.yaml
Labels: lgtm, size/XS

#11810 Fix Kyma operator
  tools/kyma-installer/kyma.Dockerfile
Labels: lgtm, size/XS
