Repository kyma-project/kyma, pull requests merged in 2021-08, with the labels that each got.

#11783 Remove old references of event mesh and event service
  components/central-application-connectivity-validator/README.md
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/centralapplicationconnectivityvalidator.go
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/options.go
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/options_test.go
  components/central-application-connectivity-validator/internal/validationproxy/handler.go
  components/central-application-connectivity-validator/internal/validationproxy/handler_test.go
  resources/application-connector/charts/central-application-connectivity-validator/templates/deployment.yaml
  resources/application-connector/values.yaml
  tests/application-connector-tests/test/applicationaccess/suite.go
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
  tests/end-to-end/upgrade/pkg/tests/application-operator/application_operator.go
Labels: lgtm, size/L

#11784 Remove old code app broker
  components/application-broker/cmd/broker/main.go
  components/application-broker/internal/broker/broker.go
  components/application-broker/internal/broker/provision.go
  components/application-broker/internal/broker/provision_test.go
  components/application-broker/internal/config/config.go
  resources/application-connector/charts/application-broker/templates/deployment.yaml
  resources/application-connector/values.yaml
Labels: lgtm, size/M

#11829 Add README files for the Application Connectivity area
  docs/01-overview/02-main-areas/application-connectivity/README.md
  docs/03-tutorials/application-connectivity/README.md
Labels: area/application-connector, area/documentation, lgtm, size/S

#11747 Rework Security documents for Kyma 2.0
  docs/01-overview/02-main-areas/api-exposure/apix-03-blacklisted-services.md
  docs/01-overview/02-main-areas/assets/kyma-areas.svg
  docs/03-tutorials/sec-01-tls-certificates-security.md
  docs/04-operation-guides/security/01-sec-overview.md
  docs/04-operation-guides/security/02-sec-authentication-in-kyma.md
  docs/04-operation-guides/security/03-sec-authorization-in-kyma.md
  docs/04-operation-guides/security/04-sec-access-kyma.md
  docs/04-operation-guides/security/05-sec-ingress-egress-traffic.md
  docs/04-operation-guides/security/06-sec-customization-operation.md
  docs/04-operation-guides/security/07-sec-useful links.md
  docs/04-operation-guides/security/ac-01-disable-ssl-certificate-verification.md
  docs/04-operation-guides/security/sec-01-concept-roles.md
  docs/04-operation-guides/security/sec-03-authorization-in-kyma.md
  docs/04-operation-guides/security/sec-06-production-profile.md
  docs/04-operation-guides/security/sec-07-tls-certificates-security.md
  docs/04-operation-guides/troubleshooting/sec-01-certificates-gardener.md
  docs/04-operation-guides/troubleshooting/sec-01-console-403-forbidden.md
  docs/04-operation-guides/troubleshooting/sec-03-console-not-enough-permissions.md
  docs/05-technical-reference/05-configuration-parameters/apix-02-ory-chart.md
  docs/05-technical-reference/05-configuration-parameters/sec-01-cluster-users.md
  docs/05-technical-reference/06-custom-resources/custrsrc-kyma-installation.md
Labels: area/documentation, area/security, lgtm, size/XL

#11676 Add Central Connectivity Validator fast integration tests
  tests/fast-integration/compass-test/compass-test.js
  tests/fast-integration/installer/index.js
  tests/fast-integration/kyma.js
  tests/fast-integration/package.json
  tests/fast-integration/test/1-install.js
  tests/fast-integration/test/2-commerce-mock.js
  tests/fast-integration/test/3-getting-started-guides.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: area/application-connector, area/quality, lgtm, size/L

#11820 Update helm-broker default addons repository
  resources/helm-broker/values.yaml
Labels: lgtm, size/XS

#11833 Update helm-broker default addons configuration (#11820)
  resources/helm-broker/values.yaml
Labels: lgtm, size/XS

#11796 Add Loki grafana dashboard and update alert rules
  resources/logging/charts/loki/templates/kyma-additions/grafana-dashboard.yaml
  resources/logging/charts/loki/templates/kyma-additions/loki.rules.yaml
Labels: lgtm, size/XXL

#11843 fix broken link
  docs/kyma/04-05-use-your-own-image.md
Labels: area/documentation, bug, lgtm

#11838 Fix: '[spec.preserveUnknownFields: Invalid value: true: must be false
  installation/resources/crds/application-connector/applications.applicationconnector.crd.yaml
  resources/cluster-essentials/files/applications.applicationconnector.crd.yaml
Labels: lgtm, size/XS

#11689 Clean-up default and not-used values of Istio Operator
  resources/istio/files/istio-operator-cluster-evaluation.yaml
  resources/istio/files/istio-operator-cluster-production.yaml
  resources/istio/files/istio-operator-cluster.yaml
  resources/istio/files/istio-operator-minikube-evaluation.yaml
  resources/istio/files/istio-operator-minikube.yaml
  resources/istio/files/profile-default-example.yaml
Labels: lgtm, size/XL

#11844 Update file names, fix grammar mistakes
  docs/04-operation-guides/security/sec-01-overview.md
  docs/04-operation-guides/security/sec-02-authentication-in-kyma.md
  docs/04-operation-guides/security/sec-03-authorization-in-kyma.md
  docs/04-operation-guides/security/sec-04-access-kyma.md
  docs/04-operation-guides/security/sec-05-ingress-egress-traffic.md
  docs/04-operation-guides/security/sec-06-customization-operation.md
  docs/04-operation-guides/security/sec-07-useful links.md
Labels: area/documentation, lgtm, size/XS

#11830 Enable central gateway & validator by default
  resources/application-connector/charts/central-application-connectivity-validator/templates/deployment.yaml
  resources/application-connector/charts/central-application-gateway/templates/deployment.yaml
  resources/application-connector/requirements.yaml
  resources/application-connector/values.yaml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
  tests/end-to-end/upgrade/pkg/tests/application-operator/application_operator.go
  tests/fast-integration/installer/index.js
Labels: lgtm, size/M

#11845 Update the Application Connector chart documentation
  docs/application-connector/05-00-application-connector.md
Labels: area/application-connector, area/documentation, lgtm, size/XS

#11848 Remove the Migration Guide for Kyma 1.23
  docs/migration-guides/1.22-1.23.md
Labels: area/documentation, lgtm, size/S

#11851 Document easy back-channel communication from function to eventing backend & remove an old migration guide
  docs/migration-guides/1.22-1.23.md
  docs/serverless/08-04-trigger-function-with-event.md
Labels: area/documentation, area/serverless, bug, lgtm, size/M

#11774 Optimize Compass runtime agent's labelling mechanism
  components/compass-runtime-agent/internal/compass/connector/client_test.go
  components/compass-runtime-agent/internal/compass/director/client.go
  components/compass-runtime-agent/internal/compass/director/client_test.go
  components/compass-runtime-agent/internal/compass/director/converter_test.go
  components/compass-runtime-agent/internal/compass/director/mocks/DirectorClient.go
  components/compass-runtime-agent/internal/compass/director/model.go
  components/compass-runtime-agent/internal/compass/director/query.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/compassconnection/supervisor.go
  components/compass-runtime-agent/internal/graphql/gql_client_testkit.go
Labels: size/XL, lgtm

#11854 Corrected Images Versions
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#11696 Skr svcat install example resources
  temp.json
  tests/fast-integration/skr-svcat-migration-test/deploy-sample-resources.js
  tests/fast-integration/skr-svcat-migration-test/fixtures/01_clusteraddonconfiguration.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/02_serviceinstance_auditlog.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/02_serviceinstance_auditlogmanagement.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/02_serviceinstance_html5appsrepo.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/02_serviceinstance_redis.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/03_function_auditlog.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/03_function_auditlogmanagement.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/03_function_html5appsrepo.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/03_function_redis.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_func-sb_auditlog.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_func-sb_auditlogmanagement.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_func-sb_html5appsrepo.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_func-sb_redis.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_inst-sb_auditlog.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_inst-sb_auditlogmanagement.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_inst-sb_html5appsrepo.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/04_inst-sb_redis.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/05_sbu_auditlog.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/05_sbu_auditlogmanagement.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/05_sbu_html5appsrepo.yaml
  tests/fast-integration/skr-svcat-migration-test/fixtures/05_sbu_redis.yaml
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
  tests/fast-integration/utils/index.js
Labels: size/XL, lgtm

#11859 Prevent cert error for RequestClientCert
  components/central-application-gateway/pkg/authorization/clientcert/clientcertificate.go
  components/central-application-gateway/pkg/httptools/roundtripper_test.go
  resources/application-connector/values.yaml
Labels: size/S, lgtm

#11860 migrate from alpha->stable
  docs/02-get-started/00-task-provision-cluster.md
  docs/04-operation-guides/operations/01-install-kyma.md
  docs/04-operation-guides/troubleshooting/troubleshoot-debug-kyma-deployment.md
Labels: size/S, lgtm

#11793 Update Prometheus Istio troubleshooting
  docs/04-operation-guides/operations/10-backup-kyma.md
  docs/04-operation-guides/troubleshooting/obsv-01-troubleshoot-prometheus-istio-server-crash-oom.md
Labels: area/documentation, size/L, lgtm

#11863 Istio Prometheus TW review
  docs/04-operation-guides/troubleshooting/obsv-01-troubleshoot-prometheus-istio-server-crash-oom.md
Labels: size/L, lgtm

#11864 Fix deploy cert flag in Kyma repo
  docs/03-tutorials/sec-01-tls-certificates-security.md
  docs/04-operation-guides/operations/01-install-kyma.md
Labels: area/documentation, size/XS, lgtm

#11847 Enable alertmanager on kyma2
  installation/resources/values.yaml
Labels: size/XS, lgtm

#11871 Remove waiting for validator in fast-integration to unblock test-infra changes
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: size/XS, lgtm

#11876 Add domain info
  docs/04-operation-guides/operations/01-install-kyma.md
Labels: size/XS, lgtm

#11856 Increase CPU limit for fluent-bit in production profile
  resources/logging/profile-production.yaml
Labels: size/XS, lgtm

#11875 Remove installer steps from fast integration tests
  tests/fast-integration/Makefile
  tests/fast-integration/compass-test/compass-test.js
  tests/fast-integration/package.json
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/test/1-install.js
  tests/fast-integration/test/2-getting-started-guides.js
Labels: size/M, lgtm

#11884 Remove obsolete make target ci-no-install
  tests/fast-integration/Makefile
Labels: size/XS, lgtm

#11868 Add configuration parameters of the ORY chart
  docs/05-technical-reference/05-configuration-parameters/apix-02-ory-chart.md
Labels: size/S, lgtm

#11879 Add OAuth2 secured API Rule to fast-integration tests
  tests/fast-integration/compass-test/compass-test.js
  tests/fast-integration/skr-test/skr-test.js
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/upgrade-test/upgrade-test-tests.js
  tests/fast-integration/utils/index.js
Labels: enhancement, area/serverless, area/api-gateway, size/L, lgtm

#11846 Refactor central-application-connectivity-validator cache sync controller.
  components/central-application-connectivity-validator/README.md
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/centralapplicationconnectivityvalidator.go
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/options.go
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/options_test.go
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-connectivity-validator/internal/controller/cachesync.go
  components/central-application-connectivity-validator/internal/controller/cachesync_test.go
  components/central-application-connectivity-validator/internal/controller/cachesynccontroller.go
  components/central-application-connectivity-validator/internal/controller/manager.go
  components/central-application-connectivity-validator/internal/controller/signals/signal.go
  resources/application-connector/profile-evaluation.yaml
  resources/application-connector/values.yaml
Labels: area/application-connector, size/XL, lgtm

#11881 Upgrade dependencies in Application Operator
  components/application-operator/go.mod
  components/application-operator/go.sum
  components/application-operator/pkg/overrides/overrides_test.go
  components/application-operator/pkg/utils/maps_test.go
  components/application-operator/pkg/utils/string_map_test.go
  resources/application-connector/values.yaml
Labels: area/security, area/application-connector, size/L, lgtm

#11880 update tracing troubleshooting
  docs/04-operation-guides/troubleshooting/obsv-02-troubleshoot-jaeger-shows-few-traces.md
Labels: size/M, lgtm

#11852 Update version to 1.24.3
  VERSION
  installation/resources/installer.yaml
Labels: size/XS, lgtm

#11891 Upgrade dependencies in Application Operator
  components/application-operator/go.mod
  components/application-operator/go.sum
  components/application-operator/pkg/overrides/overrides_test.go
  components/application-operator/pkg/utils/maps_test.go
  components/application-operator/pkg/utils/string_map_test.go
  resources/application-connector/values.yaml
Labels: size/L, lgtm

#11883 Add health probe endpoint to api-gateway
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/values.yaml
Labels: size/S, lgtm

#11893 Upgrade Application Operator image
  resources/application-connector/values.yaml
Labels: area/security, area/application-connector, size/XS, lgtm

#11896 Clean up the Overview section
  docs/01-overview/02-main-areas/README.md
  docs/01-overview/02-main-areas/api-exposure/README.md
  docs/01-overview/02-main-areas/api-exposure/assets/api-gateway.svg
  docs/01-overview/02-main-areas/application-connectivity/README.md
  docs/01-overview/02-main-areas/assets/cmf-admin-section.png
  docs/01-overview/02-main-areas/assets/cmf-cluster.yaml
  docs/01-overview/02-main-areas/assets/cmf-environment.yaml
  docs/01-overview/02-main-areas/assets/graph.png
  docs/01-overview/02-main-areas/assets/kyma-areas.svg
  docs/01-overview/02-main-areas/assets/mf-namespaced.yaml
  docs/01-overview/02-main-areas/assets/mf-one-namespace.png
  docs/01-overview/02-main-areas/assets/overview.png
  docs/01-overview/02-main-areas/assets/spec-types.svg
  docs/01-overview/02-main-areas/eventing/README.md
  docs/01-overview/02-main-areas/observability/README.md
  docs/01-overview/02-main-areas/serverless/README.md
  docs/01-overview/02-main-areas/service-management/README.md
  docs/01-overview/02-main-areas/ui/README.md
  docs/01-overview/README.md
  docs/01-overview/assets/crd/mapping-prod.yaml
  docs/01-overview/assets/kyma-advantages.svg
  docs/01-overview/assets/kyma-overview.svg
Labels: area/documentation, size/L, lgtm

#11890 Bump text and websocket packages
  components/console-backend-service/go.mod
  components/console-backend-service/go.sum
  resources/console/values.yaml
Labels: area/console, area/security, size/S, lgtm

#11837 Documentation for the back-channel communication
  docs/03-tutorials/eventing/evnt-01-setup-in-cluster-eventing.md
  docs/05-technical-reference/svls-08-function-specification.md
Labels: area/documentation, area/serverless, size/M, lgtm

#11841 Service Mesh for Kyma 2.0
  docs/01-overview/02-main-areas/service-mesh/README.md
  docs/01-overview/02-main-areas/service-mesh/smsh-01-details.md
  docs/01-overview/02-main-areas/service-mesh/smsh-02-default-istio-setup-in-kyma.md
  docs/01-overview/02-main-areas/service-mesh/smsh-03-useful-links.md
  docs/04-operation-guides/operations/smsh-01-istio-disable-sidecar-injection.md
  docs/04-operation-guides/operations/smsh-02-istio-provide-custom-config.md
  docs/04-operation-guides/troubleshooting/smsh-01-503-no-access.md
  docs/04-operation-guides/troubleshooting/smsh-02-connection-refused.md
  docs/04-operation-guides/troubleshooting/smsh-03-istio-no-sidecar.md
  docs/04-operation-guides/troubleshooting/smsh-04-istio-sidecar-version.md
  docs/05-technical-reference/05-configuration-parameters/smsh-01-istio-chart.md
Labels: area/documentation, area/service-mesh, size/L, lgtm

#11898 Remove PR image for CBS
  resources/console/values.yaml
Labels: area/console, size/XS, lgtm

#11895 K8S-tools: bump image
  components/dex-static-user-configurer/Dockerfile
  components/istio-installer/Dockerfile
  components/istio-installer/README.md
  components/xip-patch/Dockerfile
  docs/kyma/03-03-charts.md
  docs/kyma/08-04-create-volume-snapshots.md
  docs/kyma/10-08-cant-download-img.md
  resources/api-gateway/values.yaml
  resources/apiserver-proxy/templates/job.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/values.yaml
  resources/busola-migrator/values.yaml
  resources/certificates/values.yaml
  resources/cluster-essentials/templates/migrate-ac-certs-job.yaml
  resources/cluster-essentials/values.yaml
  resources/cluster-users/values.yaml
  resources/dex/templates/upgrade-job.yaml
  resources/eventing/values.yaml
  resources/istio/templates/istio-proxy-reset.yaml
  resources/istio/values.yaml
  resources/kiali/values.yaml
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
  resources/ory/values.yaml
  resources/rafter/charts/upload-service/values.yaml
  resources/rafter/templates/pre-upgrade-delete-vs-job.yaml
  resources/rafter/values.yaml
  resources/serverless/values.yaml
  resources/service-catalog/charts/catalog/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/templates/job.yaml
  tests/integration/api-gateway/Dockerfile
  tests/integration/apiserver-proxy/Dockerfile
  tests/integration/dex/Dockerfile
Labels: size/M, lgtm

#11900 Bump images after k8s-tools bump
  resources/api-gateway/values.yaml
  resources/apiserver-proxy/values.yaml
  resources/core/values.yaml
  resources/dex/values.yaml
  resources/istio/values.yaml
  resources/xip-patch/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/values.yaml
Labels: size/S, lgtm

#11902 remove obsolete console docs
  docs/03-tutorials/tut-console-CR-security-guidelines.md
  docs/03-tutorials/tut-extend-ui-luigi.md
  docs/05-technical-reference/05-configuration-parameters/configpara-31-console.md
  docs/05-technical-reference/06-custom-resources/README.md
  docs/05-technical-reference/06-custom-resources/custrsrc-console-backendmodule.md
  docs/05-technical-reference/06-custom-resources/custrsrc-console-clustermicrofrontend.md
  docs/05-technical-reference/06-custom-resources/custrsrc-console-microfrontend.md
  docs/05-technical-reference/console-backend-service-modules.md
Labels: area/documentation, size/L, lgtm

#11877 Add azure service broker image swap webhook
  resources/helm-broker/templates/webhook-deployment.yaml
  resources/helm-broker/templates/webhook-register.yaml
  resources/helm-broker/templates/webhook-service.yaml
  resources/helm-broker/values.yaml
Labels: size/L, lgtm

#11878 Svcat migration test
  tests/fast-integration/kyma-environment-broker/client.js
  tests/fast-integration/kyma-environment-broker/helpers.js
  tests/fast-integration/skr-svcat-migration-test/deploy-sample-resources.js
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
  tests/fast-integration/utils/index.js
Labels: size/XL, lgtm

#11897 Unique BEB names upgrade job
  resources/eventing/charts/controller/templates/_helpers.tpl
  resources/eventing/charts/controller/templates/pre-upgrade-job.yaml
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, size/L, lgtm

#11909 Fix knative.dev/pkg security vulns in application-broker
  components/application-broker/go.mod
  components/application-broker/go.sum
  components/application-broker/internal/broker/testing/actions.go
  components/application-broker/internal/broker/testing/client_assertion.go
  components/application-broker/internal/broker/testing/listers.go
  components/application-broker/internal/broker/testing/sorter.go
  resources/application-connector/values.yaml
Labels: size/L, lgtm

#11914 Update Console/Busola docs
  docs/01-overview/main-areas/ui/81-console-ui.md
  docs/01-overview/main-areas/ui/ui-01-GUI.md
  docs/01-overview/main-areas/ui/ui-02-CLI.md
Labels: area/documentation, size/S, lgtm

#11918 update_snapshot_troubleshooting
  docs/04-operation-guides/troubleshooting/troubleshoot-volume-backup.md
Labels: area/documentation, size/XS, lgtm

#11907 Add option to disable domainAllowList in API Gateway
  docs/api-gateway/03-02-whitelisted-domains.md
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/values.yaml
Labels: size/S, lgtm

#11910 Bump xtext and websocket packages
  components/console-backend-service/go.mod
  components/console-backend-service/go.sum
Labels: size/S, lgtm

#11678 Fixes in jobs managing Kyma certificates
  components/application-connectivity-certs-setup-job/README.md
  components/application-connectivity-certs-setup-job/go.sum
  components/application-connectivity-certs-setup-job/main.go
  components/application-connectivity-certs-setup-job/migrator.go
  components/application-connectivity-certs-setup-job/migrator_test.go
  components/application-connectivity-certs-setup-job/mocks/Manager.go
  components/application-connectivity-certs-setup-job/mocks/SecretRepository.go
  components/application-connectivity-certs-setup-job/options.go
  components/application-connectivity-certs-setup-job/secrets.go
  components/compass-runtime-agent/README.md
  components/compass-runtime-agent/cmd/main.go
  components/compass-runtime-agent/cmd/options.go
  components/compass-runtime-agent/internal/certificates/migrator.go
  components/compass-runtime-agent/internal/certificates/migrator_test.go
  components/compass-runtime-agent/internal/secrets/mocks/Manager.go
  components/compass-runtime-agent/internal/secrets/mocks/Repository.go
  components/compass-runtime-agent/internal/secrets/repository.go
  docs/application-connector-compass-mode/08-11-rotate-root-ca.md
  docs/application-connector/08-11-rotate-root-ca.md
  docs/security/03-04-ingress-egress-traffic.md
  docs/service-mesh/10-02-no-access.md
  resources/application-connector/charts/connector-service/files/certs-backup.sh
  resources/application-connector/charts/connector-service/files/certs-restore.sh
  resources/application-connector/charts/connector-service/templates/helm-certs-removal-backup-roles.yaml
  resources/application-connector/charts/connector-service/templates/helm-certs-removal-backup.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/files/watcher.sh
  resources/application-connector/templates/application-connector-gateway.yaml
  resources/application-connector/templates/certs-setup-job.yaml
  resources/application-connector/templates/certs-setup-role-binding.yaml
  resources/application-connector/templates/certs-sync-deploy.yaml
  resources/application-connector/templates/certs-sync-rbac.yaml
  resources/application-connector/values.yaml
  resources/cluster-essentials/templates/migrate-ac-certs-job.yaml
  resources/cluster-essentials/values.yaml
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/XXL, lgtm

#11911 Bump CBS image with xtext and websocket fixes
  resources/console/values.yaml
Labels: size/XS, lgtm

#11925 Fix knative.dev/pkg security vulns in application-broker
  components/application-broker/go.mod
  components/application-broker/go.sum
  components/application-broker/internal/broker/testing/actions.go
  components/application-broker/internal/broker/testing/client_assertion.go
  components/application-broker/internal/broker/testing/listers.go
  components/application-broker/internal/broker/testing/sorter.go
  resources/application-connector/values.yaml
Labels: size/L, lgtm

#11919 SC migration test - fix deletion platform
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
Labels: size/XS, lgtm

#11929 Add note about Kyma version support
  README.md
Labels: area/documentation, size/XS, lgtm

#11930 Bump helm broker img
  resources/helm-broker/values.yaml
Labels: size/XS, lgtm

#11805 Use unique names for BEB resources
  components/eventing-controller/api/v1alpha1/subscription_lifecycle.go
  components/eventing-controller/pkg/commander/beb/beb.go
  components/eventing-controller/pkg/commander/beb/beb_test.go
  components/eventing-controller/pkg/ems/api/events/client/client.go
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/pkg/handlers/beb_test.go
  components/eventing-controller/pkg/handlers/utils.go
  components/eventing-controller/pkg/handlers/utils_test.go
  components/eventing-controller/reconciler/subscription/reconciler.go
  components/eventing-controller/reconciler/subscription/reconciler_test.go
  components/eventing-controller/testing/bebmock.go
  resources/eventing/charts/controller/values.yaml
Labels: size/L, lgtm

#11901 telemetry helm chart
  components/telemetry-operator/helm-chart/.helmignore
  components/telemetry-operator/helm-chart/Chart.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/.helmignore
  components/telemetry-operator/helm-chart/charts/fluent-bit/Chart.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/NOTES.txt
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/_helpers.tpl
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/_pod.tpl
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/clusterrole.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/clusterrolebinding.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/configmap-luascripts.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/configmap.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/daemonset.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/deployment.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/networkpolicy.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/prometheusrule.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/psp.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/service.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/serviceaccount.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/servicemonitor.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/templates/tests/test-connection.yaml
  components/telemetry-operator/helm-chart/charts/fluent-bit/values.yaml
  components/telemetry-operator/helm-chart/charts/operator/.helmignore
  components/telemetry-operator/helm-chart/charts/operator/Chart.yaml
  components/telemetry-operator/helm-chart/charts/operator/templates/_helpers.tpl
  components/telemetry-operator/helm-chart/charts/operator/templates/deployment.yaml
  components/telemetry-operator/helm-chart/charts/operator/templates/leader-election-role-binding.yaml
  components/telemetry-operator/helm-chart/charts/operator/templates/leader-election-role.yaml
  components/telemetry-operator/helm-chart/charts/operator/templates/loggingconfiguration-editor-role.yaml
  components/telemetry-operator/helm-chart/charts/operator/templates/loggingconfiguration-viewer-role.yaml
  components/telemetry-operator/helm-chart/charts/operator/templates/role-binding.yaml
  components/telemetry-operator/helm-chart/charts/operator/templates/role.yaml
  components/telemetry-operator/helm-chart/charts/operator/templates/serviceaccount.yaml
  components/telemetry-operator/helm-chart/charts/operator/templates/servicemonitor.yaml
  components/telemetry-operator/helm-chart/charts/operator/values.yaml
  components/telemetry-operator/helm-chart/crds/loggingconfiguration.crd.yaml
  tests/fast-integration/package.json
  tests/fast-integration/telemetry-test/helm.js
  tests/fast-integration/telemetry-test/helm/mockserver-config/Chart.yaml
  tests/fast-integration/telemetry-test/helm/mockserver-config/README.md
  tests/fast-integration/telemetry-test/helm/mockserver-config/static/initializerJson.json
  tests/fast-integration/telemetry-test/helm/mockserver-config/static/mockserver.properties
  tests/fast-integration/telemetry-test/helm/mockserver-config/templates/configmap.yaml
  tests/fast-integration/telemetry-test/helm/mockserver/.helmignore
  tests/fast-integration/telemetry-test/helm/mockserver/Chart.yaml
  tests/fast-integration/telemetry-test/helm/mockserver/README.md
  tests/fast-integration/telemetry-test/helm/mockserver/requirements.yaml
  tests/fast-integration/telemetry-test/helm/mockserver/templates/NOTES.txt
  tests/fast-integration/telemetry-test/helm/mockserver/templates/_helpers.tpl
  tests/fast-integration/telemetry-test/helm/mockserver/templates/deployment.yaml
  tests/fast-integration/telemetry-test/helm/mockserver/templates/ingress.yaml
  tests/fast-integration/telemetry-test/helm/mockserver/templates/service-test.yaml
  tests/fast-integration/telemetry-test/helm/mockserver/templates/service.yaml
  tests/fast-integration/telemetry-test/helm/mockserver/values.yaml
  tests/fast-integration/telemetry-test/logging-config.yaml
  tests/fast-integration/telemetry-test/telemetry-test.js
  tests/fast-integration/utils/index.js
Labels: area/logging, size/XXL, lgtm

#11931 Bump helm broker image
  resources/helm-broker/values.yaml
Labels: size/XS, lgtm

#11916 Update Busola troubleshooting
  docs/04-operation-guides/troubleshooting/troubleshoot-console-network-error.md
Labels: area/documentation, size/S, lgtm

#11938 Document field `source.credentialsType` in the config.yaml regarding docs 2.0
  docs/05-technical-reference/svls-06-function-configuration-file.md
Labels: area/documentation, area/serverless, size/XS, lgtm

#11927 Bump application broker image
  resources/application-connector/values.yaml
Labels: size/XS, lgtm

#11702 IstioOperator Helm chart for Kyma 2.0
  resources/istio-configuration/Chart.yaml
  resources/istio-configuration/OWNERS
  resources/istio-configuration/profile-evaluation.yaml
  resources/istio-configuration/profile-production.yaml
  resources/istio-configuration/templates/_helpers.tpl
  resources/istio-configuration/templates/istio-operator.yaml
  resources/istio-configuration/templates/monitoring/grafana/dashboards/istio-mesh.yaml
  resources/istio-configuration/templates/monitoring/grafana/dashboards/istio-performance.yaml
  resources/istio-configuration/templates/monitoring/grafana/dashboards/istio-service.yaml
  resources/istio-configuration/templates/monitoring/grafana/dashboards/istio-workload.yaml
  resources/istio-configuration/templates/monitoring/service-monitor.yaml
  resources/istio-configuration/templates/mtls-global-v2.yaml
  resources/istio-configuration/values.yaml
Labels: area/service-mesh, size/XXL, lgtm

#11937 SC migration test: Do not process response from smtcl
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
Labels: size/XS, lgtm

#11922 Add a README to the Security section
  docs/03-tutorials/00-application-connectivity/ac-14-disable-ssl-certificate-verification.md
  docs/04-operation-guides/security/README.md
  docs/04-operation-guides/security/sec-01-authentication-in-kyma.md
  docs/04-operation-guides/security/sec-02-authorization-in-kyma.md
  docs/04-operation-guides/security/sec-03-access-kyma.md
  docs/04-operation-guides/security/sec-04-ingress-egress-traffic.md
  docs/04-operation-guides/security/sec-05-customization-operation.md
  docs/04-operation-guides/security/sec-06-useful links.md
Labels: area/documentation, size/S, lgtm

#11942 Add mockserver dependency
  tests/fast-integration/package-lock.json
  tests/fast-integration/package.json
Labels: size/XXL, lgtm

#11807 Recreate BEB subscription if it was deleted from BTP side
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/reconciler/subscription/reconciler_test.go
  components/eventing-controller/testing/bebmock.go
  components/eventing-controller/testing/matchers.go
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, size/L, lgtm

#11923 Add telemetry chart CODEOWNERs
  CODEOWNERS
Labels: size/XS, lgtm

#11947 Move telemetry operator to the rest of the charts
  resources/telemetry/.helmignore
  resources/telemetry/Chart.yaml
  resources/telemetry/charts/fluent-bit/.helmignore
  resources/telemetry/charts/fluent-bit/Chart.yaml
  resources/telemetry/charts/fluent-bit/templates/NOTES.txt
  resources/telemetry/charts/fluent-bit/templates/_helpers.tpl
  resources/telemetry/charts/fluent-bit/templates/_pod.tpl
  resources/telemetry/charts/fluent-bit/templates/clusterrole.yaml
  resources/telemetry/charts/fluent-bit/templates/clusterrolebinding.yaml
  resources/telemetry/charts/fluent-bit/templates/configmap-luascripts.yaml
  resources/telemetry/charts/fluent-bit/templates/configmap.yaml
  resources/telemetry/charts/fluent-bit/templates/daemonset.yaml
  resources/telemetry/charts/fluent-bit/templates/deployment.yaml
  resources/telemetry/charts/fluent-bit/templates/networkpolicy.yaml
  resources/telemetry/charts/fluent-bit/templates/prometheusrule.yaml
  resources/telemetry/charts/fluent-bit/templates/psp.yaml
  resources/telemetry/charts/fluent-bit/templates/service.yaml
  resources/telemetry/charts/fluent-bit/templates/serviceaccount.yaml
  resources/telemetry/charts/fluent-bit/templates/servicemonitor.yaml
  resources/telemetry/charts/fluent-bit/templates/tests/test-connection.yaml
  resources/telemetry/charts/fluent-bit/values.yaml
  resources/telemetry/charts/operator/.helmignore
  resources/telemetry/charts/operator/Chart.yaml
  resources/telemetry/charts/operator/templates/_helpers.tpl
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/templates/leader-election-role-binding.yaml
  resources/telemetry/charts/operator/templates/leader-election-role.yaml
  resources/telemetry/charts/operator/templates/loggingconfiguration-editor-role.yaml
  resources/telemetry/charts/operator/templates/loggingconfiguration-viewer-role.yaml
  resources/telemetry/charts/operator/templates/role-binding.yaml
  resources/telemetry/charts/operator/templates/role.yaml
  resources/telemetry/charts/operator/templates/serviceaccount.yaml
  resources/telemetry/charts/operator/templates/servicemonitor.yaml
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/crds/loggingconfiguration.crd.yaml
Labels: area/logging, size/XS, lgtm

#11943 Clean up Glossary
  docs/glossary.md
Labels: area/documentation, size/M, lgtm

#11906 Remove screenshots from Grafana tutorial
  docs/03-tutorials/00-observability/assets/add-query.png
  docs/03-tutorials/00-observability/assets/create-dashboard.png
  docs/03-tutorials/00-observability/assets/edit-dashboard.png
  docs/03-tutorials/00-observability/assets/enable-labels.png
  docs/03-tutorials/00-observability/assets/gauge-dashboard-type.png
  docs/03-tutorials/00-observability/assets/green-dashboard.png
  docs/03-tutorials/00-observability/assets/instant.png
  docs/03-tutorials/00-observability/assets/metrics.png
  docs/03-tutorials/00-observability/assets/min-max-values.png
  docs/03-tutorials/00-observability/assets/new-dashboard.png
  docs/03-tutorials/00-observability/assets/panel-title.png
  docs/03-tutorials/00-observability/assets/red-dashboard.png
  docs/03-tutorials/00-observability/assets/save-dashboard.png
  docs/03-tutorials/00-observability/assets/save-note.png
  docs/03-tutorials/00-observability/assets/temperature-celsius.png
  docs/03-tutorials/00-observability/assets/threshold.png
  docs/03-tutorials/00-observability/obsv-02-create-and-configure-grafana-dashboard.md
Labels: area/documentation, size/M, lgtm

#11861 Replacing Dex with Ory Hydra login and consent app in api-gateway tests
  resources/ory/values.yaml
  tests/integration/api-gateway/gateway-tests/main_test.go
  tests/integration/api-gateway/gateway-tests/manifests/hydra-client.yaml
  tests/integration/api-gateway/gateway-tests/manifests/jwt-oauth-one-path-strategy.yaml
  tests/integration/api-gateway/gateway-tests/manifests/jwt-oauth-strategy.yaml
  tests/integration/api-gateway/gateway-tests/manifests/k8s/deployment.yaml
  tests/integration/api-gateway/gateway-tests/manifests/k8s/service.yaml
  tests/integration/api-gateway/gateway-tests/manifests/k8s/virtualservice.yaml
  tests/integration/api-gateway/gateway-tests/pkg/jwt/auth.go
  tests/integration/api-gateway/gateway-tests/pkg/jwt/config.go
  tests/integration/api-gateway/gateway-tests/pkg/jwt/idtokenprovider.go
Labels: area/security, size/L, lgtm

#11951 Remove busola from docs
  docs/01-overview/main-areas/serverless/svls-04-development-toolkit.md
  docs/01-overview/main-areas/ui/ui-01-GUI.md
  docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
  docs/03-tutorials/00-serverless/svls-02-create-git-function.md
  docs/03-tutorials/00-serverless/svls-03-expose-function.md
  docs/04-operation-guides/operations/obsv-01-access-logs.md
  docs/05-technical-reference/02-components.md
Labels: area/documentation, size/S, lgtm

#11954 Update CODEOWNERS for Central Application Connectivity on 'release-1.24' branch
  CODEOWNERS
Labels: area/application-connector, size/M, lgtm

#11933 Upgrade dependencies in Application Connectivity and Compass Runtime Agent
  components/application-connectivity-validator/go.mod
  components/application-connectivity-validator/go.sum
  components/application-gateway/go.mod
  components/application-gateway/go.sum
  components/application-registry/go.mod
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  components/connection-token-handler/cmd/manager/manager.go
  components/connection-token-handler/go.mod
  components/connection-token-handler/go.sum
  components/connection-token-handler/pkg/apis/applicationconnector/v1alpha1/register.go
  components/connection-token-handler/pkg/controller/tokenrequest/tokenrequest_controller.go
  tests/application-operator-tests/go.mod
  tests/application-operator-tests/go.sum
  tests/application-registry-tests/go.mod
  tests/application-registry-tests/go.sum
  tests/application-registry-tests/test/testkit/k8sresources_client.go
Labels: size/XXL, lgtm

#11956 Bump images for Application Connector and Compass Runtime Agent
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/security, area/application-connector, size/S, lgtm

#11955 Prepare Kyma 1.24.4
  VERSION
  installation/resources/installer.yaml
Labels: size/XS, lgtm

#11960 Fix note on Kyma versions
  README.md
Labels: area/documentation, size/XS, lgtm

#11873 Add the custom domain tutorial
  docs/03-tutorials/00-api-exposure/apix-01-expose-service-apigateway.md
  docs/03-tutorials/00-api-exposure/apix-04-own-domain.md
Labels: area/documentation, area/api-gateway, size/L, lgtm

#11952 Update CODEOWNERS with Central Application Connectivity charts
  CODEOWNERS
Labels: area/application-connector, size/S, lgtm

#11985 xip.io to nip.io change (xip-patch update) #11924
  components/xip-patch/README.md
  components/xip-patch/xip-patch.sh
Labels: size/XS, lgtm

#11966 Test upgrade broker
  tests/fast-integration/upgrade-test/fixtures/helm-broker/index.js
  tests/fast-integration/upgrade-test/fixtures/helm-broker/sample-addons.yaml
  tests/fast-integration/upgrade-test/fixtures/helm-broker/service-instance.yaml
  tests/fast-integration/upgrade-test/upgrade-test-prep.js
  tests/fast-integration/upgrade-test/upgrade-test-tests.js
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#11986 Change helm value for telemetry operator
  resources/telemetry/charts/fluent-bit/values.yaml
Labels: size/XS, lgtm

#11963 recycle Grafana README
  docs/03-tutorials/00-observability/obsv-02-create-and-configure-grafana-dashboard.md
  resources/monitoring/charts/grafana/README.md
Labels: area/documentation, size/L, lgtm

#11935 Run all fast-integration tests with app-connectivity as default
  tests/fast-integration/Makefile
  tests/fast-integration/compass-test/compass-test.js
  tests/fast-integration/package.json
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/test/2-getting-started-guides.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: size/M, lgtm

#11939 Application Connector Test improvements
  resources/application-connector/values.yaml
  tests/application-connector-tests/test/testkit/connector/client.go
  tests/application-registry-tests/test/k8stests/k8sresource_test.go
  tests/connector-service-tests/go.mod
  tests/connector-service-tests/go.sum
  tests/connector-service-tests/test/apitests/connector_test.go
  tests/connector-service-tests/test/testkit/connectorclient.go
  tests/connector-service-tests/test/testkit/securedconnectorclient.go
Labels: size/L, lgtm

#11932 Added troubleshooting docs
  docs/04-operation-guides/troubleshooting/apix-02-dns-mgt-connection-refused.md
  docs/04-operation-guides/troubleshooting/apix-03-dns-mgt-could-not-resolve-host.md
  docs/04-operation-guides/troubleshooting/apix-04-dns-mgt-resource-ignored.md
  docs/04-operation-guides/troubleshooting/apix-05-cert-mgt-issuer-not-created.md
  docs/04-operation-guides/troubleshooting/smsh-01-503-no-access.md
  docs/04-operation-guides/troubleshooting/smsh-02-connection-refused.md
  docs/04-operation-guides/troubleshooting/smsh-03-istio-no-sidecar.md
Labels: area/documentation, area/api-gateway, size/L, lgtm

#11920 Fix nats-operator
  components/nats-operator/Makefile
  components/nats-operator/cmd/nats-operator-doctor/Dockerfile
  components/nats-operator/cmd/nats-operator-doctor/main.go
  components/nats-operator/cmd/nats-operator/Dockerfile
  components/nats-operator/go.mod
  components/nats-operator/go.sum
  components/nats-operator/logger/logger.go
  components/nats-operator/logger/logger_test.go
  components/nats-operator/options/options.go
  components/nats-operator/options/options_test.go
  components/nats-operator/pkg/client/natscluster/client.go
  components/nats-operator/pkg/client/natscluster/fake/client.go
  components/nats-operator/pkg/doctor/doctor.go
  components/nats-operator/pkg/doctor/doctor_test.go
  components/nats-operator/pkg/doctor/state.go
  components/nats-operator/pkg/doctor/state_test.go
  components/nats-operator/pkg/errors/errors.go
  components/nats-operator/pkg/errors/errors_test.go
  components/nats-operator/pkg/testing/k8s.go
  components/nats-operator/pkg/testing/natscluster.go
  resources/eventing/charts/controller/templates/clusterrole.yaml
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/nats/values.yaml
Labels: area/eventing, size/XXL, lgtm

#11998 Increase mem lim for eval profile (#11759)
  resources/eventing/profile-evaluation.yaml
Labels: area/eventing, size/XS, lgtm

#12001 Fix nats-operator
  components/nats-operator/Makefile
  components/nats-operator/cmd/nats-operator-doctor/Dockerfile
  components/nats-operator/cmd/nats-operator-doctor/main.go
  components/nats-operator/cmd/nats-operator/Dockerfile
  components/nats-operator/go.mod
  components/nats-operator/go.sum
  components/nats-operator/logger/logger.go
  components/nats-operator/logger/logger_test.go
  components/nats-operator/options/options.go
  components/nats-operator/options/options_test.go
  components/nats-operator/pkg/client/natscluster/client.go
  components/nats-operator/pkg/client/natscluster/fake/client.go
  components/nats-operator/pkg/doctor/doctor.go
  components/nats-operator/pkg/doctor/doctor_test.go
  components/nats-operator/pkg/doctor/state.go
  components/nats-operator/pkg/doctor/state_test.go
  components/nats-operator/pkg/errors/errors.go
  components/nats-operator/pkg/errors/errors_test.go
  components/nats-operator/pkg/testing/k8s.go
  components/nats-operator/pkg/testing/natscluster.go
Labels: area/eventing, size/XXL, lgtm

#12002 Chart changes for nats-operator fix
  resources/eventing/charts/controller/templates/clusterrole.yaml
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/nats/values.yaml
Labels: area/eventing, size/M, lgtm
