Repository kyma-project/kyma, pull requests merged in 2021-06, with the labels that each got.

#11394 Update Eventing controller charts
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/values.yaml
Labels: area/eventing, lgtm, size/S

#11372 configuring istio proxy hold app until start
  resources/istio/files/istio-operator-cluster-evaluation.yaml
  resources/istio/files/istio-operator-cluster-production.yaml
  resources/istio/files/istio-operator-cluster.yaml
  resources/istio/files/istio-operator-minikube-evaluation.yaml
  resources/istio/files/istio-operator-minikube.yaml
Labels: area/service-mesh, lgtm

#11403 Add documentation for exposing Kiali and Grafana with oauth2_proxy
  docs/operation-guides/config-07-kiali-grafana.md
Labels: lgtm, size/L

#11406 Bump oathkeeper-maester and hydra-maester versions
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
  resources/ory/charts/oathkeeper/values.yaml
Labels: lgtm, size/XS

#11349 Update CRDs from v1beta1 to v1 - rafter
  installation/resources/crds/rafter/assetgroups.rafter.crd.yaml
  installation/resources/crds/rafter/assets.rafter.crd.yaml
  installation/resources/crds/rafter/buckets.rafter.crd.yaml
  installation/resources/crds/rafter/clusterassetgroups.rafter.crd.yaml
  installation/resources/crds/rafter/clusterassets.rafter.crd.yaml
  installation/resources/crds/rafter/clusterbuckets.rafter.crd.yaml
  resources/cluster-essentials/files/assetgroups.rafter.crd.yaml
  resources/cluster-essentials/files/assets.rafter.crd.yaml
  resources/cluster-essentials/files/buckets.rafter.crd.yaml
  resources/cluster-essentials/files/clusterassetgroups.rafter.crd.yaml
  resources/cluster-essentials/files/clusterassets.rafter.crd.yaml
  resources/cluster-essentials/files/clusterbuckets.rafter.crd.yaml
Labels: lgtm, size/XXL

#11407 Add the Eventing backend type in the reconciler logs
  components/eventing-controller/reconciler/backend/reconciler.go
Labels: area/eventing, lgtm, size/M

#11409 Bump version to 1.23.0
  VERSION
  installation/resources/installer.yaml
Labels: lgtm, size/XS

#11393 Fix monitoring test
  components/eventing-controller/pkg/deployment/publisher_deployment.go
  components/eventing-controller/pkg/env/backend_config.go
  resources/eventing/charts/controller/templates/_helpers.tpl
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/templates/peerauthentication.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/dashboards/templates/delivery.yaml
  resources/eventing/charts/dashboards/templates/latency.yaml
  resources/eventing/charts/dashboards/templates/nats.yaml
  resources/eventing/charts/publisher-proxy/templates/_helpers.tpl
  resources/eventing/charts/publisher-proxy/templates/peerauthentication.yaml
  resources/eventing/charts/publisher-proxy/templates/service.yaml
  resources/eventing/charts/publisher-proxy/templates/servicemonitor.yaml
  resources/eventing/charts/publisher-proxy/values.yaml
Labels: lgtm, size/M

#11380 Additional message in case of undefined restartCount parent
  tests/fast-integration/utils/index.js
Labels: lgtm, size/S

#11400 Add VS patch pre install job to Busola Migrator
  resources/busola-migrator/files/vs_patch.sh
  resources/busola-migrator/templates/vs-patch-pre-install-job.yaml
  resources/busola-migrator/values.yaml
Labels: area/console, area/security, enhancement, lgtm, size/L

#11408 Add missing tests for eventing-backend reconciler
  components/eventing-controller/go.mod
  components/eventing-controller/reconciler/backend/reconciler_test.go
Labels: area/eventing, lgtm, size/M

#11415 Update Eventing controller image
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/XS

#11411 Update Eventing Subscription CRD
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
Labels: area/eventing, lgtm, size/XS

#11421 Name normalization utility functions
  components/application-operator/pkg/normalization/normalization.go
  components/application-operator/pkg/normalization/normalization_test.go
Labels: lgtm, size/L

#11424 remove pre-upgrade job for loki
  resources/logging/charts/loki/templates/kyma-additions/pre-upgrade-job.yaml
Labels: lgtm, size/M

#11426 Add the AC chart documentation and describe the central_connectivity_validator.enabled parameter
  docs/application-connector/05-00-application-connector.md
Labels: area/application-connector, area/documentation, lgtm, size/S

#11414 Adjust Busola Migrator init string generation
  components/busola-migrator/internal/busola/init.go
  resources/busola-migrator/values.yaml
Labels: area/console, enhancement, lgtm, size/M

#11355 Update CRDs from v1beta1 to v1 - serverless
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/crd/bases/serverless.kyma-project.io_gitrepositories.yaml
  installation/resources/crds/serverless/functions.serverless.crd.yaml
  installation/resources/crds/serverless/gitrepositories.serverless.crd.yaml
Labels: lgtm, size/XXL

#11431 Bump Busola Migrator image tag
  resources/busola-migrator/values.yaml
Labels: area/console, lgtm, size/XS

#11428 Add tests for eventing cleanup phase
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  components/eventing-controller/pkg/application/fake/lister.go
  components/eventing-controller/pkg/commander/beb/beb.go
  components/eventing-controller/pkg/commander/beb/beb_test.go
  components/eventing-controller/pkg/commander/fake/commander.go
  components/eventing-controller/pkg/commander/nats/nats.go
  components/eventing-controller/pkg/commander/nats/nats_test.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/pkg/handlers/test_helpers.go
  components/eventing-controller/testing/bebmock.go
  components/eventing-controller/testing/subscriber.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/XL

#11383 Update CRDs from v1beta1 to v1 - function controller
  components/function-controller/Makefile
  components/function-controller/config/crd/patches/cainjection_in_functions.yaml
  components/function-controller/config/crd/patches/cainjection_in_gitrepositories.yaml
  components/function-controller/config/crd/patches/webhook_in_functions.yaml
  components/function-controller/config/crd/patches/webhook_in_gitrepositories.yaml
  components/function-controller/config/webhook/manifests.yaml
  components/function-controller/pkg/apis/serverless/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/M

#11410 rafter, serverless: create Istio's `vs` instead of `apirule` during install
  resources/rafter/charts/controller-manager/charts/minio/templates/apirule.yaml
  resources/rafter/charts/controller-manager/charts/minio/templates/virtualservice.yaml
  resources/serverless/templates/apirule.yaml
  resources/serverless/templates/virtualservice.yaml
Labels: lgtm, size/L

#11369 Have tests for Audit log
  tests/fast-integration/audit-log/client.js
  tests/fast-integration/audit-log/helpers.js
  tests/fast-integration/audit-log/index.js
  tests/fast-integration/package-lock.json
  tests/fast-integration/package.json
  tests/fast-integration/skr-test/.env.template
  tests/fast-integration/skr-test/readme.md
  tests/fast-integration/skr-test/skr-test.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: lgtm, size/XXL

#11429 Fast-integration tests oauth credentials handling refactoring
  tests/fast-integration/compass/client.js
  tests/fast-integration/kyma-environment-broker/client.js
  tests/fast-integration/lib/oauth.js
Labels: lgtm, size/M

#11444 instantiate for aws only
  tests/fast-integration/skr-test/skr-test.js
Labels: lgtm, size/XS

#11445 Bump helm controller image
  resources/helm-broker/values.yaml
Labels: lgtm, size/XS

#11443 Clean up
  components/eventing-controller/pkg/commander/beb/beb.go
  components/eventing-controller/pkg/commander/nats/nats.go
  components/eventing-controller/pkg/deployment/publisher_deployment.go
  components/eventing-controller/pkg/handlers/utils.go
  components/eventing-controller/pkg/object/equality.go
  components/eventing-controller/reconciler/backend/reconciler.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/L

#11402 Allow disabling rafter minio exposure
  installation/resources/values.yaml
  resources/rafter/charts/controller-manager/charts/minio/templates/virtualservice.yaml
  resources/rafter/charts/controller-manager/charts/minio/values.yaml
Labels: area/console, area/core-and-supporting, area/documentation, lgtm, size/S

#11433 Upgrade Istio installer to 1.10.0
  components/istio-installer/Dockerfile
Labels: area/service-mesh, lgtm, size/XS

#11449 Fix Grafana link
  docs/monitoring/08-03-create-and-configure-grafana-dashboard.md
Labels: area/documentation, lgtm, size/XS

#11448 Bump bluemonday version
  components/apiserver-proxy/go.mod
  components/apiserver-proxy/go.sum
Labels: lgtm, size/S

#11425 Removed old Monitoring Tests
  tests/integration/monitoring/.gitignore
  tests/integration/monitoring/Dockerfile
  tests/integration/monitoring/Makefile
  tests/integration/monitoring/OWNERS
  tests/integration/monitoring/README.md
  tests/integration/monitoring/go.mod
  tests/integration/monitoring/go.sum
  tests/integration/monitoring/prom/alerts.go
  tests/integration/monitoring/prom/rules.go
  tests/integration/monitoring/prom/targets.go
  tests/integration/monitoring/test-lambda-dashboard-requirements.go
  tests/integration/monitoring/test-monitoring.go
Labels: lgtm, size/XXL

#11458 Bump Application Connectivity images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, lgtm, size/XS

#11450 K8S-tools: bump image
  components/dex-static-user-configurer/Dockerfile
  components/istio-installer/Dockerfile
  components/istio-installer/README.md
  components/xip-patch/Dockerfile
  docs/kyma/03-03-charts.md
  docs/kyma/08-04-create-volume-snapshots.md
  docs/kyma/10-08-cant-download-img.md
  resources/api-gateway/values.yaml
  resources/apiserver-proxy/templates/job.yaml
  resources/application-connector/charts/application-broker/templates/subscription-migration.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/values.yaml
  resources/busola-migrator/values.yaml
  resources/certificates/values.yaml
  resources/cluster-essentials/templates/migrate-ac-certs-job.yaml
  resources/cluster-essentials/values.yaml
  resources/cluster-users/values.yaml
  resources/dex/templates/upgrade-job.yaml
  resources/eventing/values.yaml
  resources/helm-broker/templates/clear-cr-job.yaml
  resources/istio/templates/istio-proxy-reset.yaml
  resources/istio/values.yaml
  resources/kiali/values.yaml
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
  resources/ory/values.yaml
  resources/rafter/charts/upload-service/values.yaml
  resources/rafter/templates/pre-upgrade-delete-vs-job.yaml
  resources/rafter/values.yaml
  resources/serverless/values.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/clear-cr-job.yaml
  resources/service-catalog/charts/catalog/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/templates/job.yaml
  tests/integration/api-gateway/Dockerfile
  tests/integration/apiserver-proxy/Dockerfile
  tests/integration/dex/Dockerfile
Labels: lgtm, size/M

#11459 Bump images after k8s-tools bump
  resources/api-gateway/values.yaml
  resources/apiserver-proxy/values.yaml
  resources/core/values.yaml
  resources/dex/values.yaml
  resources/istio/values.yaml
  resources/xip-patch/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/values.yaml
Labels: lgtm, size/S

#11460 Update Eventing images
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/XS

#11452 Add pod antiaffinity to NATS cluster
  resources/eventing/charts/nats/templates/40-cr.yaml
Labels: area/eventing, lgtm, size/S

#10674 Add health and ready check
  components/eventing-controller/README.md
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/go.sum
  components/eventing-controller/options/options.go
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/L

#11464 Update eventing controller image
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/XS

#11465 Bump apiserver-proxy and dex versions
  resources/apiserver-proxy/values.yaml
  resources/dex/Chart.yaml
Labels: lgtm, size/XS

#11366 Update CRDs from v1beta1 to v1 - eventing
  installation/resources/crds/eventing/natsserviceroles.nats.crd.yaml
  resources/cluster-essentials/files/natsserviceroles.nats.crd.yaml
Labels: lgtm, size/S

#11467 Reconnect to Nats in publisher-proxy
  components/event-publisher-proxy/cmd/event-publisher-proxy/nats/nats.go
  components/event-publisher-proxy/pkg/handler/nats/handler_test.go
  components/event-publisher-proxy/pkg/nats/connect.go
  components/event-publisher-proxy/pkg/nats/connect_test.go
  components/event-publisher-proxy/pkg/sender/nats.go
  components/event-publisher-proxy/pkg/sender/nats_test.go
Labels: lgtm, size/L

#11454 add certificate creation validation during install
  resources/certificates/files/gardener.sh
  resources/certificates/templates/job-gardener.yaml
Labels: lgtm, size/M

#11477 Clean up docs
  docs/operation-guides/01-install-kyma.md
  docs/operation-guides/03-change-kyma-config-values.md
  docs/operation-guides/05-upgrade-kyma.md
  docs/operation-guides/07-uninstall-kyma.md
  docs/operation-guides/08-securityconcept-roles.md
  docs/operation-guides/09-tls-certificates-security.md
  docs/operation-guides/10-backup-kyma.md
  docs/operation-guides/13-restore-kyma-with-velero.md
  docs/operation-guides/15-backup-volume-snapshots.md
  docs/operation-guides/50-kiali-grafana.md
  docs/operation-guides/60-default-istio-setup-in-kyma.md
  docs/operation-guides/60-istio-disable-sidecar-injection.md
  docs/operation-guides/60-istio-provide-custom-config.md
  docs/operation-guides/troubleshoot-03-installation-troubleshooting.md
  docs/operation-guides/troubleshoot-volume-backup.md
  docs/operation-guides/zz-access-logs.md
  docs/operation-guides/zz-install-runtimeagent-modes.md
  docs/operation-guides/zz-loki-configure-storage.md
  docs/operation-guides/zz-runtimeagent-configure-runtime.md
  docs/tutorials/tut-config-authorizations-apigateway.md
  docs/tutorials/tut-console-CR-security-guidelines.md
  docs/tutorials/tut-setup-in-cluster-eventing.md
Labels: lgtm, size/XXL

#11447 Fine tune eventing CRDs and Makefile
  components/eventing-controller/Makefile
  components/eventing-controller/README.md
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_eventingbackends.yaml
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/pkg/commander/nats/nats_test.go
  components/eventing-controller/reconciler/subscription-nats/reconciler_test.go
  components/eventing-controller/testing/nats.go
  installation/resources/crds/eventing/eventingbackends.eventing.kyma-project.io.crd.yaml
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/cluster-essentials/files/eventingbackends.eventing.kyma-project.io.crd.yaml
  resources/cluster-essentials/files/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/XL

#11473 Bump oathkeeper image version
  resources/ory/charts/oathkeeper/values.yaml
Labels: lgtm, size/XS

#11441 Static users bound to roles based on override
  installation/resources/values.yaml
  resources/cluster-users/templates/rbac-roles.yaml
  resources/cluster-users/values.yaml
Labels: lgtm, size/S

#11468 Compass runtime agent name normalization
  components/compass-runtime-agent/cmd/main.go
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  components/compass-runtime-agent/internal/compass/director/proxy.go
  components/compass-runtime-agent/internal/compassconnection/controller.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/kyma/applications/converter.go
  components/compass-runtime-agent/internal/kyma/applications/util.go
  components/compass-runtime-agent/internal/kyma/applications/util_test.go
  components/compass-runtime-agent/internal/metrics/logger.go
  components/compass-runtime-agent/internal/metrics/logger_test.go
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, lgtm, size/XL

#11480 bump controller-runtime version
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  components/eventing-controller/reconciler/backend/reconciler.go
  components/eventing-controller/reconciler/backend/reconciler_test.go
  components/eventing-controller/reconciler/subscription-nats/reconciler.go
  components/eventing-controller/reconciler/subscription/reconciler.go
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/L

#11434 Upgrade Istio resource to 1.10.0 version
  resources/istio/Chart.yaml
  resources/istio/files/istio-operator-cluster-evaluation.yaml
  resources/istio/files/istio-operator-cluster-production.yaml
  resources/istio/files/istio-operator-cluster.yaml
  resources/istio/files/istio-operator-minikube-evaluation.yaml
  resources/istio/files/istio-operator-minikube.yaml
  resources/istio/values.yaml
  resources/ory/charts/hydra/charts/hydra-maester/templates/deployment.yaml
Labels: area/service-mesh, lgtm, size/S

#11455 Fix Function Controller manifests generation
  components/function-controller/Makefile
  components/function-controller/README.md
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/crd/bases/serverless.kyma-project.io_gitrepositories.yaml
  components/function-controller/internal/controllers/serverless/function_controller.go
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  components/function-controller/internal/controllers/serverless/gitops_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  installation/resources/crds/serverless/functions.serverless.crd.yaml
  resources/serverless/values.yaml
Labels: area/serverless, bug, lgtm, size/XL

#11483 Remove old sub-charts from the new installation
  installation/resources/values.yaml
  resources/helm-broker/values.yaml
  resources/service-catalog-addons/requirements.yaml
  resources/service-catalog-addons/values.yaml
Labels: lgtm, size/S

#11461 Disable Central Application Gateway
  resources/application-connector/values.yaml
Labels: lgtm, size/XS

#11484 Enable milv check on internal links in docs
  milv.config.yaml
Labels: lgtm, size/XS

#11413 Remove old content from website while building preview
  .kyma-project-io/build-preview.sh
  .kyma-project-io/docs-get-started-cag.yaml
  .kyma-project-io/docs-glossary-cag.yaml
  .kyma-project-io/docs-operation-guides-cag.yaml
  .kyma-project-io/docs-overview-cag.yaml
  .kyma-project-io/docs-technical-reference-cag.yaml
  .kyma-project-io/docs-tutorials-cag.yaml
  .kyma-project-io/values.yaml
Labels: lgtm, size/L

#11485 Update yaml sample
  docs/04-operation-guides/operations/01-install-kyma.md
Labels: area/documentation, lgtm, size/M

#11494 Avoid restarting eventing-controller if NATS cluster was restarted
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/reconciler/subscription-nats/reconciler.go
  resources/eventing/charts/controller/templates/clusterrole.yaml
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/L

#11503 Bump images for publisher and controller
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/XS

#11152 Add fast integration pipeline for Single Application Gateway
  resources/application-connector/charts/central-application-gateway/templates/deployment.yaml
  resources/application-connector/charts/central-application-gateway/templates/rbac.yaml
  resources/application-connector/profile-evaluation.yaml
  resources/application-connector/profile-production.yaml
  resources/application-connector/requirements.yaml
  tests/fast-integration/Makefile
  tests/fast-integration/README.md
  tests/fast-integration/compass-test/compass-test.js
  tests/fast-integration/compass/client.js
  tests/fast-integration/installer/index.js
  tests/fast-integration/kyma.js
  tests/fast-integration/package-lock.json
  tests/fast-integration/package.json
  tests/fast-integration/test/1-install.js
  tests/fast-integration/test/2-commerce-mock.js
  tests/fast-integration/test/3-getting-started-guides.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/utils/index.js
Labels: area/application-connector, enhancement, lgtm, size/XL

#11504 Upgrade alpine to 3.14.0 for console
  resources/console/charts/web/values.yaml
  resources/helm-broker/charts/addons-ui/values.yaml
  resources/logging/charts/logui/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/values.yaml
Labels: lgtm, size/S

#11501 fixing fast-integration upgrade-test
  tests/fast-integration/test/2-commerce-mock.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/upgrade-test/upgrade-test-tests.js
Labels: lgtm, size/M

#11510 Bump oathkepper-maester version
  installation/resources/crds/ory/rules.crd.yaml
  resources/cluster-essentials/files/rules.crd.yaml
  resources/ory/charts/oathkeeper/values.yaml
Labels: lgtm, size/XXL

#11492 Migrate logging integration test to fast-integration
  tests/fast-integration/logging/client.js
  tests/fast-integration/logging/helpers.js
  tests/fast-integration/logging/index.js
  tests/fast-integration/test/2-commerce-mock.js
Labels: area/logging, lgtm, size/M

#11511 Bump version to 1.23.1
  VERSION
  installation/resources/installer.yaml
Labels: area/installation, lgtm, size/XS

#11512 bump istio installer image version
  resources/istio/values.yaml
Labels: area/service-mesh, lgtm, size/XS

#11513 Update the Busola installation link
  docs/03-tutorials/serverless/svls-01-create-inline-function.md
  docs/03-tutorials/serverless/svls-02-create-git-function.md
  docs/03-tutorials/serverless/svls-03-expose-function.md
Labels: area/documentation, area/serverless, lgtm, size/XS

#11506 Remove leftovers related to overrides
  docs/03-tutorials/serverless/svls-07-set-external-registry.md
  docs/05-technical-reference/05-configuration-parameters/svls-01-serverless-chart.md
Labels: area/documentation, area/serverless, lgtm, size/XS

#11515 Remove duplicated keys in monitoring YAMLs
  resources/monitoring/charts/prometheus-istio/templates/servicemonitor.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/pods.yaml
Labels: lgtm, size/XS

#11517 Update default busola URL and enable pkce by default
  resources/busola-migrator/values.yaml
Labels: lgtm, size/S

#11500 Add Python 3.9 to the list of supported Serverless runtimes
  docs/01-overview/02-main-areas/serverless/svls-02-from-code-to-function.md
  docs/01-overview/02-main-areas/serverless/svls-04-development-toolkit.md
  docs/05-technical-reference/06-custom-resources/svls-01-function.md
  docs/05-technical-reference/svls-01-sample-functions.md
  docs/05-technical-reference/svls-04-git-source-type.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
  docs/05-technical-reference/svls-08-function-specification.md
Labels: area/documentation, area/serverless, lgtm, size/M

#11523 Clean up UAA related parts - iteration 1
  docs/01-overview/02-main-areas/api-exposure/01-01-api-gateway.md
  docs/01-overview/02-main-areas/service-mesh/con-service-mesh-istio.md
  docs/03-tutorials/application-connectivity/tut-establish-secure-connection-with-compass-runtimeagent.md
  docs/03-tutorials/tut-add-connector-security.md
  docs/03-tutorials/tut-config-authorizations-apigateway.md
  docs/03-tutorials/tut-generate-kubeconfig-security.md
  docs/03-tutorials/tut-invalidate-dex-signing-keys-security.md
  docs/03-tutorials/tut-manage-static-users-security.md
  docs/04-operation-guides/security/05-07-permission-controller.md
  docs/04-operation-guides/troubleshooting/troubleshoot-console-403-forbidden.md
  docs/04-operation-guides/troubleshooting/troubleshoot-console-network-error.md
  docs/04-operation-guides/troubleshooting/troubleshoot-console-not-enough-permissions.md
  docs/05-technical-reference/03-architecture/arch-apigateway-01.md
  docs/05-technical-reference/03-architecture/arch-kiali-01.md
  docs/05-technical-reference/03-architecture/arch-tracing-01.md
  docs/05-technical-reference/05-configuration-parameters/configpara-13-grafana.md
  docs/05-technical-reference/05-configuration-parameters/security-api-server-proxy.md
  docs/05-technical-reference/05-configuration-parameters/security-iam-kubeconfig-service.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
Labels: lgtm, size/L

#11516 Bump helm-broker resource
  resources/helm-broker/values.yaml
Labels: lgtm, size/XS

#11309 Update Eventing 2.0 docs
  docs/01-overview/02-main-areas/eventing/01-01-eventing-overview.md
  docs/01-overview/02-main-areas/eventing/evnt-01-overview.md
  docs/01-overview/02-main-areas/eventing/evnt-02-useful-links.md
  docs/03-tutorials/eventing/evnt-01-setup-in-cluster-eventing.md
  docs/05-technical-reference/03-architecture/assets/evnt-architecture.svg
  docs/05-technical-reference/03-architecture/assets/evnt-processing-flow.svg
  docs/05-technical-reference/03-architecture/evnt-01-architecture.md
  docs/05-technical-reference/03-architecture/evnt-02-event-processing.md
Labels: lgtm, size/M

#11533 Perform cleanup for Impersonate-Group header in request
  components/apiserver-proxy/internal/proxy/proxy.go
  components/apiserver-proxy/internal/proxy/proxy_test.go
Labels: lgtm, size/S

#11502 Istio 1.10 improvements
  resources/istio/files/istio-install.sh
  resources/istio/files/istio-operator-cluster-evaluation.yaml
  resources/istio/files/istio-operator-cluster-production.yaml
  resources/istio/files/istio-operator-cluster.yaml
  resources/istio/files/istio-operator-minikube-evaluation.yaml
  resources/istio/files/istio-operator-minikube.yaml
  resources/istio/files/istio-upgrade.sh
Labels: area/service-mesh, lgtm, size/S

#11528 Fix problem with duplicated keys (name label)
  resources/eventing/charts/publisher-proxy/templates/_helpers.tpl
  resources/eventing/charts/publisher-proxy/templates/service.yaml
Labels: lgtm, size/S

#11442 Remove cert-manager from Kyma
  CODEOWNERS
  installation/resources/crds/cert-manager/cert-manager.certificaterequests.crd.yaml
  installation/resources/crds/cert-manager/cert-manager.certificates.crd.yaml
  installation/resources/crds/cert-manager/cert-manager.challenges.acme.crd.yaml
  installation/resources/crds/cert-manager/cert-manager.clusterissuers.crd.yaml
  installation/resources/crds/cert-manager/cert-manager.issuers.crd.yaml
  installation/resources/crds/cert-manager/cert-manager.orders.acme.crd.yaml
  installation/resources/namespaces/.gitkeep
  installation/resources/namespaces/cert-manager/cert-manager-namespace.yaml
  resources/cert-manager/Chart.yaml
  resources/cert-manager/OWNERS
  resources/cert-manager/README.md
  resources/cert-manager/templates/NOTES.txt
  resources/cert-manager/templates/_helpers.tpl
  resources/cert-manager/templates/cainjector-deployment.yaml
  resources/cert-manager/templates/cainjector-psp-clusterrole.yaml
  resources/cert-manager/templates/cainjector-psp-clusterrolebinding.yaml
  resources/cert-manager/templates/cainjector-psp.yaml
  resources/cert-manager/templates/cainjector-rbac.yaml
  resources/cert-manager/templates/cainjector-serviceaccount.yaml
  resources/cert-manager/templates/crds.legacy.yaml
  resources/cert-manager/templates/deployment.yaml
  resources/cert-manager/templates/psp-clusterrole.yaml
  resources/cert-manager/templates/psp-clusterrolebinding.yaml
  resources/cert-manager/templates/psp.yaml
  resources/cert-manager/templates/rbac.yaml
  resources/cert-manager/templates/service.yaml
  resources/cert-manager/templates/serviceaccount.yaml
  resources/cert-manager/templates/servicemonitor.yaml
  resources/cert-manager/templates/webhook-deployment.yaml
  resources/cert-manager/templates/webhook-mutating-webhook.yaml
  resources/cert-manager/templates/webhook-psp-clusterrole.yaml
  resources/cert-manager/templates/webhook-psp-clusterrolebinding.yaml
  resources/cert-manager/templates/webhook-psp.yaml
  resources/cert-manager/templates/webhook-rbac.yaml
  resources/cert-manager/templates/webhook-service.yaml
  resources/cert-manager/templates/webhook-serviceaccount.yaml
  resources/cert-manager/templates/webhook-validating-webhook.yaml
  resources/cert-manager/values.yaml
  resources/certificates/README.md
  resources/certificates/files/check.sh
  resources/certificates/files/user-provided.sh
  resources/certificates/templates/job-user-provided.yaml
  resources/certificates/templates/rbac-check.yaml
  resources/certificates/templates/rbac-user-provided.yaml
Labels: lgtm, size/XXL

#11532 Add jaegertracing crd
  installation/resources/crds/tracing/jaegers.jaegertracing.crd.yaml
Labels: lgtm, size/M

#11540 Add check to avoid cache conflicts in build preview script
  .kyma-project-io/build-preview.sh
Labels: lgtm, size/S

#11536 Fix nodejs build containers
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
Labels: lgtm, size/S

#11522 Dependency Upgrade
  components/application-operator/go.mod
  components/application-operator/go.sum
Labels: lgtm, size/L

#11542 updated base image kiali - fluent-bit, grafana patch update 7.4.5
  resources/kiali/values.yaml
  resources/logging/charts/fluent-bit/values.yaml
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring, lgtm, size/XS

#11514 prepare kyma-gateway for move to certificates chart
  resources/core/charts/gateway/templates/gateway.yaml
Labels: lgtm, size/XS

#11534 Update postgres
  resources/ory/charts/postgresql/values.yaml
Labels: lgtm, size/XS

#11529 remove `namespace` dir because it's no longer needed
  installation/resources/namespaces/.gitkeep
Labels: lgtm, size/XS

#11553 bump `apiserver-proxy` version
  resources/apiserver-proxy/values.yaml
Labels: lgtm, size/XS

#11549 istio tracing config is set to 100
  resources/istio/files/istio-operator-cluster-evaluation.yaml
  resources/istio/files/istio-operator-cluster-production.yaml
  resources/istio/files/istio-operator-cluster.yaml
  resources/istio/files/istio-operator-minikube-evaluation.yaml
  resources/istio/files/istio-operator-minikube.yaml
Labels: area/service-mesh, area/tracing, bug, lgtm, size/M

#11518 Replace keycloak-proxy by oauth2-proxy
  installation/resources/values.yaml
  resources/dex/values.yaml
  resources/kiali/templates/_helpers.tpl
  resources/kiali/templates/kyma-additions/auth-proxy-configmap.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-secret.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-service.yaml
  resources/kiali/templates/kyma-additions/kcproxy-deployment.yaml
  resources/kiali/templates/kyma-additions/kcproxy-secret.yaml
  resources/kiali/templates/kyma-additions/peerauthentication.yaml
  resources/kiali/templates/kyma-additions/virtualservice.yaml
  resources/kiali/values.yaml
  resources/monitoring/charts/grafana/templates/_helpers.tpl
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-configmap.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-secret.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/tracing/templates/_helpers.tpl
  resources/tracing/templates/kyma-additions/auth-proxy-configmap.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-secret.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-service.yaml
  resources/tracing/templates/kyma-additions/kcproxy-deployment.yaml
  resources/tracing/templates/kyma-additions/kcproxy-secret.yaml
  resources/tracing/templates/kyma-additions/virtualservice.yaml
  resources/tracing/values.yaml
  tests/fast-integration/installer/index.js
Labels: lgtm, size/XL

#11554 Bump serverless images
  resources/serverless/values.yaml
Labels: area/serverless, lgtm, size/XS

#11555 Corrected Runtime Agent Container Version
  resources/compass-runtime-agent/values.yaml
Labels: lgtm, size/XS

#11556 Update Istio-installer to 1.10.2
  components/istio-installer/Dockerfile
Labels: lgtm, size/XS

#11525 Remove ConfigMap creation from Certificates components
  resources/certificates/files/gardener.sh
  resources/certificates/files/legacy.sh
Labels: lgtm, size/S

#11551 Update Eventing resource limits for the evaluation profile
  resources/eventing/profile-evaluation.yaml
Labels: area/eventing, lgtm, size/S

#11562 Update Istio to 1.10.2
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: lgtm, size/XS

#11566 Change cookie names for OAuth2 Proxy deployments
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
Labels: lgtm, size/XS

#11563 Update to version 1.24.0-rc1
  .kyma-project-io/values.yaml
  VERSION
  installation/resources/installer.yaml
Labels: lgtm, size/XS

#11570 Added jeremyharisch and chrkl as CodeOwners
  CODEOWNERS
Labels: lgtm, size/S

#11571 Bump image for service-manager-proxy
  resources/service-manager-proxy/values.yaml
Labels: lgtm, size/XS

#11560 upgrade Kiali to 1.36
  resources/kiali/templates/_helpers.tpl
  resources/kiali/templates/configmap.yaml
  resources/kiali/templates/deployment.yaml
  resources/kiali/templates/hpa.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-configmap.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-secret.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-service.yaml
  resources/kiali/templates/kyma-additions/clustermicrofrontend.yaml
  resources/kiali/templates/kyma-additions/peerauthentication.yaml
  resources/kiali/templates/kyma-additions/servicemonitor.yaml
  resources/kiali/templates/kyma-additions/virtualservice.yaml
  resources/kiali/templates/role-viewer.yaml
  resources/kiali/templates/role.yaml
  resources/kiali/templates/service.yaml
  resources/kiali/values.yaml
Labels: area/service-mesh, lgtm, size/XL

#11457 Change service exposure guide for Kiali and Grafana to OIDC
  docs/04-operation-guides/operations/50-kiali-grafana.md
Labels: lgtm, size/L

#11573 Improve overview headlines
  docs/01-overview/02-main-areas/README.md
  docs/01-overview/README.md
Labels: area/documentation, lgtm, size/M

#11507 Dynamic oauth2client creation
  components/eventing-controller/Makefile
  components/eventing-controller/README.md
  components/eventing-controller/config/crd/external/README.md
  components/eventing-controller/config/crd/external/hydra.ory.sh_oauth2clients.yaml
  components/eventing-controller/config/rbac/role.yaml
  components/eventing-controller/go.mod
  components/eventing-controller/pkg/commander/beb/beb.go
  components/eventing-controller/pkg/commander/beb/beb_test.go
  components/eventing-controller/pkg/commander/commander.go
  components/eventing-controller/pkg/commander/fake/commander.go
  components/eventing-controller/pkg/commander/mocks/commander.go
  components/eventing-controller/pkg/commander/nats/nats.go
  components/eventing-controller/pkg/deployment/oauth2client_cr.go
  components/eventing-controller/pkg/env/config.go
  components/eventing-controller/pkg/env/config_test.go
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/pkg/handlers/beb_test.go
  components/eventing-controller/pkg/object/equality.go
  components/eventing-controller/reconciler/backend/reconciler.go
  components/eventing-controller/reconciler/backend/reconciler_test.go
  components/eventing-controller/reconciler/subscription/reconciler.go
  components/eventing-controller/reconciler/subscription/reconciler_test.go
  resources/eventing/charts/controller/templates/clusterrole.yaml
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/templates/oauth2-client.yaml
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, lgtm, size/XL

#11574 Update external crd for eventing controller
  components/eventing-controller/Makefile
  components/eventing-controller/config/crd/external/apirules-gateway-kyma-project-io.yaml
  components/eventing-controller/config/crd/external/hydra.ory.sh_oauth2clients.yaml
Labels: area/eventing, lgtm, size/XL

#11579 Codeowners updated for new Application Connectivity Components
  CODEOWNERS
Labels: lgtm, size/XS

#11576 Change cookie names for OAuth2 Proxy deployments (#11566)
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
Labels: lgtm, size/XS

#11581 Fix rendering Kyma groups for OAuth2 Proxy deployments
  resources/kiali/templates/_helpers.tpl
  resources/kiali/templates/kyma-additions/auth-proxy-secret.yaml
  resources/monitoring/charts/grafana/templates/_helpers.tpl
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-secret.yaml
  resources/tracing/templates/_helpers.tpl
  resources/tracing/templates/kyma-additions/auth-proxy-secret.yaml
Labels: lgtm, size/S

#11588 Fix rendering Kyma groups for OAuth2 Proxy deployments
  resources/kiali/templates/_helpers.tpl
  resources/kiali/templates/kyma-additions/auth-proxy-secret.yaml
  resources/monitoring/charts/grafana/templates/_helpers.tpl
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-secret.yaml
  resources/tracing/templates/_helpers.tpl
  resources/tracing/templates/kyma-additions/auth-proxy-secret.yaml
Labels: lgtm, size/S

#11527 Remove isBEBEnabled flag
  components/application-connectivity-validator/README.md
  components/application-connectivity-validator/cmd/applicationconnectivityvalidator/applicationconnectivityvalidator.go
  components/application-connectivity-validator/cmd/applicationconnectivityvalidator/options.go
  components/application-connectivity-validator/internal/validationproxy/handler.go
  components/application-connectivity-validator/internal/validationproxy/handler_test.go
  components/application-operator/README.md
  components/application-operator/charts/application/profile-evaluation.yaml
  components/application-operator/charts/application/profile-production.yaml
  components/application-operator/charts/application/templates/deployment.yaml
  components/application-operator/charts/application/templates/service.yaml
  components/application-operator/charts/application/templates/validator.yaml
  components/application-operator/charts/application/values.yaml
  components/application-operator/cmd/manager/manager.go
  components/application-operator/cmd/manager/options.go
  components/application-operator/pkg/overrides/overrides.go
  resources/application-connector/charts/application-operator/templates/controller.yaml
  resources/application-connector/values.yaml
  tests/fast-integration/installer/index.js
Labels: area/eventing, lgtm, size/XL

#11586 Fix http request reference link to Express
  docs/serverless/03-01-function-specification.md
Labels: lgtm, size/XS

#11589 Bump image for service-manager-proxy
  resources/service-manager-proxy/values.yaml
Labels: lgtm, size/XS

#11544 Fix replicas vs. PDB settings in evaluation profile
  resources/cluster-essentials/charts/pod-preset/templates/webhook/deploy.yaml
  resources/cluster-essentials/charts/pod-preset/values.yaml
  resources/cluster-essentials/profile-evaluation.yaml
  resources/cluster-essentials/profile-production.yaml
  resources/istio/files/istio-operator-cluster-evaluation.yaml
  resources/istio/files/istio-operator-cluster-production.yaml
  resources/istio/files/istio-operator-minikube-evaluation.yaml
Labels: lgtm, size/S

#11587 Bump Console filters fix
  resources/console/charts/web/values.yaml
Labels: lgtm, size/XS

#11491 Fix https://github.com/kyma-project/kyma/issues/11398
  components/central-application-gateway/cmd/applicationgateway/applicationproxy.go
  components/central-application-gateway/internal/csrf/client/csrfclient.go
  components/central-application-gateway/internal/csrf/client/csrfclient_test.go
  components/central-application-gateway/internal/proxy/cache.go
  components/central-application-gateway/internal/proxy/cache_test.go
  components/central-application-gateway/internal/proxy/factory_test.go
  components/central-application-gateway/internal/proxy/proxy.go
  components/central-application-gateway/internal/proxy/proxy_test.go
  components/central-application-gateway/internal/proxy/retryableroundtripper.go
  components/central-application-gateway/internal/proxy/retryableroundtripper_test.go
  components/central-application-gateway/internal/proxy/reverseproxy.go
  components/central-application-gateway/internal/proxy/unauthorizedresponseretrier.go
  components/central-application-gateway/internal/proxy/unauthorizedresponseretrier_test.go
  components/central-application-gateway/pkg/authorization/basicauthstrategy.go
  components/central-application-gateway/pkg/authorization/certificategenstrategy.go
  components/central-application-gateway/pkg/authorization/certificategenstrategy_test.go
  components/central-application-gateway/pkg/authorization/clientcert/clientcertificate.go
  components/central-application-gateway/pkg/authorization/externaltokenstrategy.go
  components/central-application-gateway/pkg/authorization/factory.go
  components/central-application-gateway/pkg/authorization/factory_test.go
  components/central-application-gateway/pkg/authorization/mocks/OAuthClient.go
  components/central-application-gateway/pkg/authorization/mocks/Strategy.go
  components/central-application-gateway/pkg/authorization/mocks/StrategyFactory.go
  components/central-application-gateway/pkg/authorization/noauthstrategy.go
  components/central-application-gateway/pkg/authorization/oauthstrategy.go
  components/central-application-gateway/pkg/httptools/roundtripper.go
  components/central-application-gateway/pkg/httptools/roundtripper_test.go
  resources/application-connector/values.yaml
Labels: lgtm, size/XXL

#11595 update goats CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/M

#11593 Fix replicas vs PDB settings in evaluation profile
  resources/cluster-essentials/charts/pod-preset/templates/webhook/deploy.yaml
  resources/cluster-essentials/charts/pod-preset/values.yaml
  resources/cluster-essentials/profile-evaluation.yaml
  resources/cluster-essentials/profile-production.yaml
  resources/istio/files/istio-operator-cluster-evaluation.yaml
  resources/istio/files/istio-operator-cluster-production.yaml
  resources/istio/files/istio-operator-minikube-evaluation.yaml
Labels: lgtm, size/S

#11597 Fix enumeration in obervability service exposure guide
  docs/04-operation-guides/operations/obsv-02-access-expose-kiali-grafana.md
Labels: lgtm, size/S

#11596 Update version to 1.24.0-rc2
  VERSION
  installation/resources/installer.yaml
Labels: lgtm, size/XS

#11584 Bump core-ui image
  resources/console/charts/web/values.yaml
Labels: lgtm, size/XS
