Repository kyma-project/kyma, pull requests merged in 2021-05, with the labels that each got.

#11196 Migrate requirements.yaml to chart.yaml to be helm3 compliant
  resources/logging/Chart.yaml
  resources/logging/requirements.yaml
  resources/monitoring/Chart.yaml
  resources/monitoring/requirements.yaml
Labels: estimate: 3, lgtm, size/S

#11213 Rename master to main (leftovers)
  resources/serverless/charts/k3s-tests/README.md
  tests/fast-integration/README.md
Labels: area/documentation, lgtm, size/XS

#11215 k8s-tools: bump image
  components/dex-static-user-configurer/Dockerfile
  components/istio-installer/Dockerfile
  components/istio-installer/README.md
  components/xip-patch/Dockerfile
  docs/kyma/03-03-charts.md
  docs/kyma/08-04-create-volume-snapshots.md
  docs/kyma/10-08-cant-download-img.md
  resources/api-gateway/values.yaml
  resources/apiserver-proxy/templates/job.yaml
  resources/application-connector/charts/application-broker/templates/subscription-migration.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/values.yaml
  resources/certificates/values.yaml
  resources/cluster-essentials/templates/migrate-ac-certs-job.yaml
  resources/cluster-essentials/values.yaml
  resources/cluster-users/values.yaml
  resources/dex/templates/upgrade-job.yaml
  resources/eventing/values.yaml
  resources/helm-broker/templates/clear-cr-job.yaml
  resources/istio/templates/istio-proxy-reset.yaml
  resources/istio/values.yaml
  resources/kiali/values.yaml
  resources/logging/charts/loki/templates/kyma-additions/pre-upgrade-job.yaml
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
  resources/ory/values.yaml
  resources/rafter/charts/upload-service/values.yaml
  resources/rafter/templates/pre-upgrade-delete-vs-job.yaml
  resources/rafter/values.yaml
  resources/serverless/values.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/clear-cr-job.yaml
  resources/service-catalog/charts/catalog/values.yaml
  tests/integration/api-gateway/Dockerfile
  tests/integration/apiserver-proxy/Dockerfile
  tests/integration/dex/Dockerfile
Labels: lgtm, size/M

#11221 Remove the Eventing pre-upgrade-job
  resources/eventing/templates/pre-upgrade-job.yaml
Labels: area/eventing, lgtm, size/M

#11223 Bump images after k8s-tools bump
  resources/api-gateway/values.yaml
  resources/apiserver-proxy/values.yaml
  resources/core/values.yaml
  resources/dex/values.yaml
  resources/istio/values.yaml
  resources/xip-patch/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/values.yaml
Labels: lgtm, size/S

#11193 Enable performing commerce tests in pre and post kyma upgrade states
  tests/fast-integration/Makefile
  tests/fast-integration/package.json
  tests/fast-integration/test/2-commerce-mock-cleanup.js
  tests/fast-integration/test/2-commerce-mock-prep.js
  tests/fast-integration/test/2-commerce-mock-tests.js
Labels: lgtm, size/M

#11212 add first draft for observability overview
  docs/overview/02-main-areas/observability/01-overview.md
  docs/overview/02-main-areas/observability/con-kiali.md
  docs/overview/02-main-areas/observability/con-logging.md
  docs/overview/02-main-areas/observability/con-monitoring.md
  docs/overview/02-main-areas/observability/con-tracing-jaeger.md
  docs/overview/02-main-areas/observability/con-tracing.md
  docs/overview/02-main-areas/observability/tracing-search-traces.md
  docs/overview/10-navigationdummy-AppConnectivity.md
  docs/overview/20-navigationdummy-ServiceConsumption.md
  docs/overview/30-navigationdummy-Serverless.md
  docs/overview/40-navigationdummy-Eventing.md
  docs/overview/51-telemetry-observability-overview.md
  docs/overview/60-navigationdummy-ServiceMesh.md
  docs/overview/70-navigationdummy-APIexposure.md
  docs/overview/81-console-ui.md
  docs/overview/83-CLI-overview.md
  docs/tutorials/tut-extend-ui-luigi.md
  docs/tutorials/tut-monitor-00-overview.md
  docs/tutorials/tut-monitor-01-observe-application-metrics.md
  docs/tutorials/tut-monitor-02-create-and-configure-grafana-dashboard.md
  docs/tutorials/tut-monitor-03-define-alerting-rules-monitor.md
  docs/tutorials/tut-monitor-04-send-notifications.md
Labels: area/documentation, lgtm, size/L

#11219 Remove testing component from new installation
  installation/resources/components.yaml
Labels: area/installation, lgtm, size/XS

#11218 Update go compiler ver
  components/application-broker/cmd/broker/Dockerfile
  components/application-broker/go.mod
  components/binding/Dockerfile
  components/binding/go.mod
  components/service-binding-usage-controller/Dockerfile
  components/service-binding-usage-controller/go.mod
  components/uaa-activator/Dockerfile
  components/uaa-activator/go.mod
  resources/application-connector/values.yaml
  resources/service-catalog-addons/values.yaml
  resources/uaa-activator/values.yaml
Labels: lgtm, size/S

#11232 Update images related to Eventing components
  resources/application-connector/values.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/nats-controller/values.yaml
Labels: area/eventing, lgtm, size/XS

#11210 Adapt BEB controller to work with defaults
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/pkg/env/config.go
  components/eventing-controller/pkg/env/config_test.go
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/pkg/handlers/beb_test.go
  components/eventing-controller/pkg/handlers/utils.go
  components/eventing-controller/pkg/handlers/utils_test.go
  components/eventing-controller/reconciler/subscription/reconciler_test.go
  components/eventing-controller/testing/test_helpers.go
  resources/cluster-essentials/files/subscriptions.eventing.kyma-project.io.crd.yaml
Labels: area/eventing, lgtm, size/L

#11205 add first glossary entries
  docs/glossary/glossary.md
Labels: area/documentation, lgtm, size/S

#11241 Bump iam-kubeconfig-service alpine image version
  components/iam-kubeconfig-service/Dockerfile
Labels: lgtm, size/XS

#11239 Bump apiserver-proxy alpine image version
  components/apiserver-proxy/Dockerfile
Labels: lgtm, size/XS

#11243 Remove function liveness probe
  components/function-controller/internal/controllers/serverless/build_resources.go
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  resources/serverless/values.yaml
Labels: area/serverless, bug, lgtm, priority/critical, size/S

#11249 Revert liveness probe addition to Serverless Functions
  resources/serverless/values.yaml
Labels: area/serverless, bug, lgtm, priority/critical, size/XS

#11211 Refactor publisher, preparing it for switching the eventing backend
  components/event-publisher-proxy/cmd/event-publisher-proxy/beb/beb.go
  components/event-publisher-proxy/cmd/event-publisher-proxy/main.go
  components/event-publisher-proxy/cmd/event-publisher-proxy/nats/nats.go
  components/event-publisher-proxy/pkg/handler/beb/handler.go
  components/event-publisher-proxy/pkg/handler/beb/handler_test.go
  components/event-publisher-proxy/pkg/sender/beb.go
  components/event-publisher-proxy/pkg/sender/beb_test.go
  components/event-publisher-proxy/pkg/sender/nats.go
  components/event-publisher-proxy/pkg/sender/sender.go
  components/event-publisher-proxy/pkg/signals/signals.go
Labels: area/eventing, lgtm, size/L

#11250 Bump of image for "Remove node10 add node14"
  resources/console/values.yaml
Labels: lgtm, size/XS

#11247 Bump dex image
  resources/dex/Chart.yaml
Labels: lgtm, size/XS

#11224 Remove event-service leftovers
  components/application-operator/charts/application/templates/authorization-policy.yaml
  components/application-operator/charts/application/templates/deployment.yaml
  components/application-operator/charts/application/templates/role-binding.yaml
  components/application-operator/charts/application/templates/service.yaml
  components/application-operator/charts/application/templates/validator.yaml
  resources/application-connector/charts/application-operator/templates/cluster-rolebinding.yaml
  resources/application-connector/charts/application-operator/templates/pod-security-policy.yaml
  resources/application-connector/values.yaml
  tests/end-to-end/upgrade/chart/upgrade/templates/authorization-policy.yaml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
Labels: lgtm, size/L

#11263 Update to version 1.9.5
  components/istio-installer/Dockerfile
Labels: lgtm, size/XS

#11264 Correct the default runtime in Serverless docs
  docs/serverless/03-02-available-runtimes.md
  docs/serverless/03-05-supported-webhooks.md
Labels: area/documentation, area/serverless, lgtm, size/XS

#11262 Upgrade Istio to 1.9.5
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: lgtm, priority/critical, size/XS

#11246 Bump apiserver-proxy image
  resources/apiserver-proxy/values.yaml
Labels: lgtm, size/XS

#11258 Bump sb-proxy image to 0.8.18
  resources/service-manager-proxy/values.yaml
Labels: lgtm, size/XS

#11040 Improve performance of kubeless runtime
  components/function-runtimes/python38/Dockerfile
  components/function-runtimes/python38/kubeless/.gitignore
  components/function-runtimes/python38/kubeless/kubeless.py
  components/function-runtimes/python38/kubeless/requirements.txt
  resources/serverless/values.yaml
Labels: enhancement, lgtm, size/M

#11270 Update kyma-installer Dockerfile
  tools/kyma-installer/kyma.Dockerfile
Labels: lgtm, size/XS

#11265 Bump images: Upgrade merge and alpine for console
  resources/console/charts/web/values.yaml
  resources/console/values.yaml
  resources/helm-broker/charts/addons-ui/values.yaml
  resources/logging/charts/logui/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/values.yaml
Labels: lgtm, size/S

#11248 Polishing of upgrade test
  tests/fast-integration/Makefile
  tests/fast-integration/package.json
  tests/fast-integration/upgrade-test/upgrade-test-cleanup.js
  tests/fast-integration/upgrade-test/upgrade-test-prep.js
  tests/fast-integration/upgrade-test/upgrade-test-tests.js
  tests/fast-integration/upgrade-test/upgrade-test.js
Labels: lgtm, size/M

#11267 bump images after pr-11224
  resources/application-connector/values.yaml
  tests/end-to-end/upgrade/chart/upgrade/values.yaml
Labels: lgtm, size/XS

#11261 Switch to 3.13.5 alpine version in whole serverless domain
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/python38/Dockerfile
  resources/rafter/values.yaml
  resources/serverless/values.yaml
  tests/rafter/Dockerfile
Labels: area/serverless, lgtm, security/high, size/M

#11260 Bump client-go and knative/pkg in the function-controller
  components/function-controller/go.mod
  components/function-controller/go.sum
  resources/serverless/values.yaml
Labels: area/serverless, lgtm, security/medium, size/XXL

#11242 Add region to fast integration KEB client
  tests/fast-integration/kyma-environment-broker/client.js
Labels: lgtm, size/S

#11274 Upgrade missing PR-* image tags
  resources/rafter/values.yaml
  resources/serverless/charts/docker-registry/values.yaml
  resources/serverless/values.yaml
Labels: area/serverless, lgtm, size/S

#11266 Update client-go to v0.18.18
  components/console-backend-service/Dockerfile
  components/console-backend-service/go.mod
  components/console-backend-service/go.sum
  components/console-backend-service/internal/domain/apigateway.resolvers.go
  components/console-backend-service/internal/domain/application/app_service.go
  components/console-backend-service/internal/domain/application/app_service_test.go
  components/console-backend-service/internal/domain/application/gateway/provider.go
  components/console-backend-service/internal/domain/bebEventing/resolver.go
  components/console-backend-service/internal/domain/k8s/configmap_service.go
  components/console-backend-service/internal/domain/k8s/configmap_service_test.go
  components/console-backend-service/internal/domain/k8s/namespace_service.go
  components/console-backend-service/internal/domain/k8s/pod_service.go
  components/console-backend-service/internal/domain/k8s/pod_service_test.go
  components/console-backend-service/internal/domain/k8s/replicaset_service.go
  components/console-backend-service/internal/domain/k8s/replicaset_service_test.go
  components/console-backend-service/internal/domain/k8s/resource_service.go
  components/console-backend-service/internal/domain/k8s/secret_service.go
  components/console-backend-service/internal/domain/k8s/selfsubjectrules_service.go
  components/console-backend-service/internal/domain/k8s/service_service.go
  components/console-backend-service/internal/domain/k8s/service_service_test.go
  components/console-backend-service/internal/domain/serverless/function_service.go
  components/console-backend-service/internal/domain/servicecatalog/servicebinding_service.go
  components/console-backend-service/internal/domain/servicecatalog/servicebinding_service_test.go
  components/console-backend-service/internal/domain/servicecatalog/serviceinstance_service.go
  components/console-backend-service/internal/domain/servicecatalogaddons/addonsconfiguration_service.go
  components/console-backend-service/internal/domain/servicecatalogaddons/clusteraddonsconfiguration_service.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_service.go
  components/console-backend-service/internal/domain/servicecatalogaddons/servicebindingusage_service_test.go
  components/console-backend-service/internal/domain/servicecatalogaddons/usagekind_service.go
  components/console-backend-service/internal/resource/service_base.go
  components/console-backend-service/main.go
  components/console-backend-service/pkg/client/clientset/versioned/typed/ui/v1alpha1/backendmodule.go
  components/console-backend-service/pkg/dynamic/dynamicinformer/informer.go
  components/console-backend-service/pkg/tracing/config.go
  components/console-backend-service/pkg/tracing/handler.go
  components/console-backend-service/pkg/tracing/setup.go
  components/console-backend-service/pkg/tracing/tracer.go
  resources/console/values.yaml
Labels: lgtm, size/XXL

#11275 Update console_backend_service image
  resources/console/values.yaml
Labels: lgtm, size/XS

#11253 Remove coredns patching
  resources/certificates/files/legacy.sh
Labels: lgtm, size/M

#11277 Update codeowners
  CODEOWNERS
Labels: area/community, lgtm, size/M

#11278 Update Observability component details
  docs/overview/02-main-areas/observability/con-kiali.md
  docs/overview/02-main-areas/observability/con-logging.md
  docs/overview/02-main-areas/observability/con-monitoring-alertmanager.md
  docs/overview/02-main-areas/observability/con-monitoring.md
  docs/overview/02-main-areas/observability/con-tracing.md
  docs/overview/51-telemetry-observability-overview.md
Labels: lgtm, size/L

#11279 Upgrade python runtime to the 3.8.10 version
  components/function-runtimes/python38/Dockerfile
  resources/serverless/values.yaml
Labels: area/serverless, lgtm, security/critical, size/XS

#11280 Resolve PR tags for serverless runtimes
  resources/serverless/values.yaml
Labels: lgtm, size/XS

#11286 improve Grafana-related docu for K2.0
  docs/overview/02-main-areas.md
  docs/overview/51-telemetry-observability-overview.md
Labels: lgtm, size/XS

#11282 bump base image for nats operator
  components/nats-operator/Dockerfile
Labels: lgtm, size/XS

#11285 improve Grafana-related documentation
  docs/kyma/03-01-components.md
  docs/logging/01-01-logging.md
  docs/monitoring/01-01-monitoring.md
Labels: lgtm, size/S

#11288 bump nats-operator image
  resources/eventing/charts/nats/values.yaml
Labels: lgtm, size/XS

#11230 Installation with helm template
  resources/service-catalog/charts/catalog/templates/webhook-deployment.yaml
  tests/fast-integration/README.md
  tests/fast-integration/installer/helm.js
  tests/fast-integration/installer/index.js
  tests/fast-integration/installer/installer-local.yaml
  tests/fast-integration/installer/system-namespaces.yaml
  tests/fast-integration/kyma.js
  tests/fast-integration/test/2-commerce-mock.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/utils/index.js
Labels: lgtm, size/L

#11304 Set temp override for Kubernetes min version in Serverless webhook
  resources/serverless/charts/webhook/templates/deployment.yaml
Labels: area/serverless, bug, lgtm, size/XS

#11310 Fix race condition in event test
  tests/fast-integration/test/2-commerce-mock.js
Labels: lgtm, size/S

#11307 Bump helm-controller in Kyma
  resources/helm-broker/values.yaml
Labels: lgtm, size/XS

#11293 Change ETCD image in Helm Broker to alpine 3.3.15 based
  resources/helm-broker/charts/etcd-stateful/values.yaml
Labels: lgtm, size/XS

#11305 Upgrade GO compiler to the latest for the function-controller
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  resources/serverless/values.yaml
Labels: area/serverless, lgtm, security/high, size/S

#11291 Observability overview tweaks
  docs/overview/51-telemetry-observability-overview.md
Labels: lgtm, size/S

#11314 use copied nats and prometheus-nats-exporter images
  resources/eventing/charts/nats/templates/40-cr.yaml
Labels: lgtm, size/XS

#11318 Resolve PR tags for the serverless domain
  resources/serverless/values.yaml
Labels: area/serverless, lgtm, size/XS

#11317 change line breaks, move istio document
  docs/overview/02-main-areas/service-mesh/con-monitoring-istio.md
  docs/overview/51-telemetry-observability-overview.md
Labels: area/documentation, lgtm, size/XS

#11302 Add go.mod
  tests/compass-runtime-agent/Gopkg.lock
  tests/compass-runtime-agent/Gopkg.toml
  tests/compass-runtime-agent/Makefile
  tests/compass-runtime-agent/go.mod
  tests/compass-runtime-agent/go.sum
Labels: lgtm, size/XXL

#11301 add first definition for microservice
  docs/glossary/glossary.md
Labels: area/documentation, lgtm, size/XS

#11313 Upgrade Wookiee beings in the CODEOWNERS file
  CODEOWNERS
Labels: area/serverless, enhancement, lgtm, size/M

#11320 Set version to 1.23.0-rc1
  .kyma-project-io/values.yaml
  installation/resources/installer.yaml
Labels: lgtm, size/XS

#11326 Fix test on remote cluster
  tests/fast-integration/test/2-commerce-mock.js
Labels: lgtm, size/XS

#11333 update nats dependencies
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  resources/eventing/charts/event-publisher-nats/values.yaml
  resources/eventing/charts/event-publisher-proxy/values.yaml
Labels: lgtm, size/XL

#11316 disable exposure of observability tools for new installer
  installation/resources/values.yaml
  resources/kiali/templates/kyma-additions/virtualservice.yaml
  resources/kiali/values.yaml
  resources/logging/Chart.yaml
  resources/logging/charts/loki/templates/kyma-additions/authorizationpolicy.yaml
  resources/logging/charts/loki/templates/kyma-additions/requestautentication.yaml
  resources/logging/charts/loki/templates/kyma-additions/virtualservice.yaml
  resources/logging/charts/loki/values.yaml
  resources/tracing/templates/kyma-additions/virtualservice.yaml
  resources/tracing/values.yaml
Labels: lgtm, size/M

#11338 Update CODEOWNERS and OWNERS
  CODEOWNERS
  resources/monitoring/OWNERS
  resources/tracing/OWNERS
  tests/integration/logging/OWNERS
  tests/integration/monitoring/OWNERS
  tests/perf/OWNERS
Labels: lgtm, size/S

#11334 Add Jaeger security context
  resources/tracing/values.yaml
Labels: lgtm, size/S

#11339 Bug/no persistence in test mocks
  tests/fast-integration/test/fixtures/commerce-mock/commerce-mock.yaml
Labels: lgtm, size/S

#11345 Release 1.21.2
  VERSION
  docs/kyma/03-02-testing.md
  installation/resources/installer.yaml
  resources/dex/templates/tests/test-connection.yaml
  resources/monitoring/extractmetrics.sh
Labels: lgtm, size/S

#11347 Release 1.22.1
  VERSION
  docs/kyma/03-02-testing.md
  installation/resources/installer.yaml
  resources/dex/templates/tests/test-connection.yaml
  resources/monitoring/extractmetrics.sh
Labels: lgtm, size/S

#11346 Bump version to 1.23.0-rc2
  VERSION
  docs/kyma/03-02-testing.md
  installation/resources/installer.yaml
  resources/dex/templates/tests/test-connection.yaml
  resources/monitoring/extractmetrics.sh
Labels: lgtm, size/S

#11335 minor language editing
  docs/overview/02-main-areas.md
Labels: area/documentation, lgtm, size/XS

#11344 Change curl image
  docs/kyma/03-02-testing.md
  resources/dex/templates/tests/test-connection.yaml
  resources/monitoring/extractmetrics.sh
Labels: lgtm, size/XS

#11336 [istio ingressgateway] add memory based HPA
  resources/istio/files/istio-kyma-validate-test.sh
  resources/istio/files/istio-operator-cluster-evaluation.yaml
  resources/istio/files/istio-operator-cluster-production.yaml
  resources/istio/files/istio-operator-cluster.yaml
  resources/istio/files/istio-operator-minikube-evaluation.yaml
  resources/istio/files/istio-operator-minikube.yaml
  resources/istio/templates/tests/istio-kyma-validate-rbac.yaml
Labels: lgtm, size/M

#11352 Update Api-Gateway and ORY CRDs
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
  installation/resources/crds/ory/oauth2clients.crd.yaml
  installation/resources/crds/ory/rules.crd.yaml
  resources/cluster-essentials/files/apirules.gateway.crd.yaml
  resources/cluster-essentials/files/oauth2clients.crd.yaml
  resources/cluster-essentials/files/rules.crd.yaml
Labels: lgtm, size/XXL

#11354 Bump HB to bf64ee7a
  resources/helm-broker/values.yaml
Labels: lgtm, size/XS

#11358 updated base image for fluent-bit and kiwigrid-sidecar
  resources/logging/charts/fluent-bit/values.yaml
  resources/monitoring/charts/grafana/values.yaml
Labels: area/logging, lgtm, size/XS

#11360 Bump x/net dependency in sbu
  components/service-binding-usage-controller/Dockerfile
  components/service-binding-usage-controller/go.mod
  components/service-binding-usage-controller/go.sum
Labels: lgtm, size/S

#11353 Update CRDs from v1beta1 to v1 - testing
  installation/resources/crds/testing/clustertestsuite.crd.yaml
  installation/resources/crds/testing/testdefinition.crd.yaml
Labels: lgtm, size/L

#11363 Bump Service binding usage controller
  resources/service-catalog-addons/values.yaml
Labels: lgtm, size/XS

#11361 Change image `eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20200309-9a88ce97` to `eu.gcr.io/kyma-project/tpi/k8s-tools:20210504-12243229`.
  tests/fast-integration/installer/charts/ingress-dns-cert/templates/job.yaml
Labels: lgtm, size/XS

#11315 update observability tutorials
  docs/operation-guides/config-07-kiali-grafana.md
  docs/operation-guides/ops-tls-certificates-security.md
  docs/tutorials/01-develop-service-local-no-docker-kyma.md
  docs/tutorials/02-publish-service-image-and-deploy-kyma.md
  docs/tutorials/50-access-kiali-monitor-servicemesh.md
  docs/tutorials/51-monitoring-overview.md
  docs/tutorials/52-observe-application-metrics.md
  docs/tutorials/53-create-and-configure-grafana-dashboard.md
  docs/tutorials/54-define-alerting-rules-monitor.md
  docs/tutorials/55-send-notifications.md
  docs/tutorials/57-configure-in-cluster-observability.md
  docs/tutorials/tut-compare-traces-tracing.md
  docs/tutorials/tut-extend-kubectl-with-kyma-plugin.md
  docs/tutorials/tut-monitor-04-send-notifications.md
  docs/tutorials/tut-search-traces-tracing.md
Labels: area/documentation, lgtm, size/L

#11356 Ensure QoS for helpers Pods in ORY chart
  resources/ory/charts/oathkeeper/templates/job.yaml
  resources/ory/templates/job-secret-migration.yaml
Labels: lgtm, size/S

#11359 Grafana/Kiali port forward instructions
  docs/operation-guides/config-07-kiali-grafana.md
  docs/operation-guides/troubleshoot-kubectl-port-forward.md
Labels: lgtm, size/M

#11374 remove obsolete observability tutorials
  docs/overview/51-telemetry-observability-overview.md
  docs/tutorials/50-access-kiali-monitor-servicemesh.md
  docs/tutorials/57-configure-in-cluster-observability.md
Labels: lgtm, size/S

#11377 remove obsolete components from logging diagram
  docs/technical-reference/assets/logging-architecture.svg
Labels: area/documentation, lgtm, size/XL

#11378 Offboard
  CODEOWNERS
Labels: lgtm, size/S

#11340 add global.installCRD to kyma2 values
  installation/resources/values.yaml
Labels: lgtm, size/XS

#11281 Migrate monitoring tests to JS
  tests/fast-integration/Makefile
  tests/fast-integration/monitoring-test/monitoring-test.js
  tests/fast-integration/monitoring-test/readme.md
  tests/fast-integration/monitoring/client.js
  tests/fast-integration/monitoring/helpers.js
  tests/fast-integration/package-lock.json
  tests/fast-integration/package.json
  tests/fast-integration/utils/index.js
Labels: lgtm, size/L

#11325 KEB Resolve user (email) of the runtime creator
  tests/fast-integration/kyma-environment-broker/client.js
  tests/fast-integration/skr-test/.env.template
Labels: lgtm, size/XS

#11385 integrate kyma docu 2.0 with new website layout
  .kyma-project-io/build-preview.sh
  docs/get-started/metadata.yaml
  docs/glossary/metadata.yaml
  docs/old-component-docs/application-connector/metadata.yaml
  docs/old-component-docs/kyma/metadata.yaml
  docs/old-component-docs/metadata.yaml
  docs/old-component-docs/security/metadata.yaml
  docs/operation-guides/metadata.yaml
  docs/overview/02-main-areas/api-exposure/metadata.yaml
  docs/overview/02-main-areas/application-connectivity/metadata.yaml
  docs/overview/02-main-areas/eventing/metadata.yaml
  docs/overview/02-main-areas/metadata.yaml
  docs/overview/02-main-areas/serverless/metadata.yaml
  docs/overview/02-main-areas/service-management/metadata.yaml
  docs/overview/02-main-areas/service-mesh/metadata.yaml
  docs/overview/metadata.yaml
  docs/technical-reference/metadata.yaml
  docs/tutorials/metadata.yaml
Labels: lgtm, size/S

#11388 Stabilise monitoring tests
  tests/fast-integration/monitoring-test/monitoring-test.js
  tests/fast-integration/monitoring/helpers.js
Labels: bug, lgtm, size/XS, test-failing

#11395 Update Eventing controller image
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, lgtm, size/XS

#11364 Add UAA Enabled feature flag
  components/busola-migrator/README.md
  components/busola-migrator/internal/app/app.go
  components/busola-migrator/internal/app/automock/html_renderer.go
  components/busola-migrator/internal/app/migrate.go
  components/busola-migrator/internal/app/migrate_test.go
  components/busola-migrator/internal/app/redirect.go
  components/busola-migrator/internal/app/redirect_test.go
  components/busola-migrator/internal/app/static.go
  components/busola-migrator/internal/app/static_test.go
  components/busola-migrator/internal/config/config.go
  components/busola-migrator/internal/renderer/renderer.go
  components/busola-migrator/internal/renderer/renderer_test.go
  components/busola-migrator/internal/renderer/template.go
  components/busola-migrator/internal/renderer/testdata/a.gohtml
  components/busola-migrator/internal/renderer/testdata/b.gohtml
  components/busola-migrator/internal/router/router.go
  components/busola-migrator/internal/router/router_test.go
  components/busola-migrator/static/index.html
  components/busola-migrator/static/success.html
  components/busola-migrator/static/templates/index.gohtml
  components/busola-migrator/static/templates/success.gohtml
  resources/busola-migrator/templates/deployment.yaml
  resources/busola-migrator/values.yaml
Labels: area/console, area/security, enhancement, lgtm, size/XL

#11391 Align Eventing backend controller logger with the unified Kyma logger
  components/eventing-controller/README.md
  components/eventing-controller/cmd/eventing-controller/Dockerfile
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  components/eventing-controller/log/log.go
  components/eventing-controller/options/options.go
  components/eventing-controller/pkg/commander/beb/beb.go
  components/eventing-controller/pkg/commander/nats/nats.go
  components/eventing-controller/reconciler/backend/reconciler.go
  components/eventing-controller/reconciler/backend/reconciler_test.go
Labels: area/eventing, lgtm, size/L

#11399 Enhance backend controller logger
  components/eventing-controller/cmd/eventing-controller/Dockerfile
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/logger/logger.go
  components/eventing-controller/options/options.go
  components/eventing-controller/reconciler/backend/reconciler.go
  components/eventing-controller/reconciler/backend/reconciler_test.go
Labels: area/eventing, lgtm, size/M

#11252 Add omit empty for protocol and protocol settings for eventing-controller
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/reconciler/subscription-nats/reconciler_test.go
  components/eventing-controller/reconciler/subscription/reconciler_test.go
  resources/eventing/charts/controller/values.yaml
Labels: lgtm, size/L

#11390 Set owner references for publisher deployment
  components/eventing-controller/go.mod
  components/eventing-controller/pkg/deployment/controller_deployment.go
  components/eventing-controller/reconciler/backend/reconciler.go
  components/eventing-controller/reconciler/backend/reconciler_test.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, lgtm, size/L
