Repository kyma-project/kyma, pull requests merged in 2021-11, with the labels that each got.

#12458 Updated docs about certificates
  docs/03-tutorials/sec-01-tls-certificates-security.md
  docs/04-operation-guides/security/sec-02-authorization-in-kyma.md
  docs/04-operation-guides/security/sec-04-ingress-egress-traffic.md
  docs/04-operation-guides/security/sec-07-useful-links.md
Labels: area/documentation, size/L, lgtm

#12520 Fix broken links
  docs/03-tutorials/00-api-exposure/apix-01-own-domain.md
  docs/04-operation-guides/troubleshooting/sec-01-certificates-gardener.md
Labels: area/documentation, size/XS, lgtm

#12507 Bump istio on release-1.24 to 1.11.4
  components/istio-installer/Dockerfile
Labels: size/XS, lgtm

#12498 Bump istio on main to 1.11.4
  resources/istio-configuration/Chart.yaml
  resources/istio-configuration/values.yaml
Labels: size/XS, lgtm

#12519 Adapt kcp config in fast upgrade test
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
Labels: size/XS, lgtm

#12522 bump istio-installer to 1.11.4 in release-1.24
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: size/XS, lgtm

#12523 avoid leaking secrets
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/upgrade-helpers.js
Labels: size/S, lgtm

#12510 update fluent-bit to 1.8.9
  resources/logging/values.yaml
Labels: area/logging, size/XS, lgtm

#12532 bump bluemonday in apiserver-proxy to 1.0.16
  components/apiserver-proxy/go.mod
  components/apiserver-proxy/go.sum
Labels: size/XS, lgtm

#12534 Bump fluent-bit used in telemetry
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#12530 goats codeowners update + cleaning
  CODEOWNERS
Labels: size/S, lgtm

#12537 Bump apiserver-proxy and dex versions
  resources/apiserver-proxy/values.yaml
  resources/dex/Chart.yaml
Labels: size/XS, lgtm

#12496 Cherry-pick: Fix basic auth (#12367)
  components/function-controller/cmd/jobinit/main.go
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  components/function-controller/internal/git/auth.go
  components/function-controller/internal/git/auth_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
Labels: size/L, lgtm

#12497 Bump cherry-picked version
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#12486 Grafanawatcher
  resources/monitoring/charts/grafana/templates/_pod.tpl
  resources/monitoring/charts/grafana/values.yaml
Labels: size/M, lgtm

#12528 Bump Console (fix repository URL validation regex)
  resources/console/charts/web/values.yaml
Labels: size/XS, lgtm

#12542 Change role reference in FITests assertion
  tests/fast-integration/utils/index.js
Labels: size/XS, lgtm

#12535 React to OAuth2 secret changes in the Eventing controller
  components/eventing-controller/config/manager/manager.yaml
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_test.go
  components/eventing-controller/pkg/commander/beb/beb.go
  components/eventing-controller/pkg/commander/commander.go
  components/eventing-controller/pkg/commander/fake/commander.go
  components/eventing-controller/pkg/commander/nats/nats.go
  components/eventing-controller/pkg/handlers/utils.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#12544 Rename Grafana ConfigMap watcher sidecar containers
  resources/monitoring/charts/grafana/templates/_pod.tpl
Labels: size/XS, lgtm

#12545 Update bluemonday to 1.0.16
  components/apiserver-proxy/go.mod
  components/apiserver-proxy/go.sum
Labels: size/XS, lgtm

#12539 [istio-conf] adjust helm settings to match Kyma 1 convention for tracing
  resources/istio-configuration/templates/istio-operator.yaml
  resources/istio-configuration/values.yaml
Labels: size/XS, lgtm

#12540 Allow to override cluster-essential pod-preset certs
  resources/cluster-essentials/charts/pod-preset/templates/webhook/webhook.yaml
  resources/cluster-essentials/charts/pod-preset/values.yaml
  resources/cluster-essentials/values.yaml
Labels: size/M, lgtm

#12533 Improve skr kyma to kyma2 upgrade aws dev
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/upgrade-helpers.js
Labels: size/L, lgtm

#12547 Update base image for gateway-legacy-test executor to alpine 3.14.2
  resources/application-connector/values.yaml
  tests/application-gateway-legacy-tests/test/helmtest/Dockerfile
Labels: size/XS, lgtm

#12559 Fix security issues in the context of the rafter image
  resources/rafter/values.yaml
Labels: area/security, size/XS, lgtm

#12453 Clean up unneeded rafter jobs
  resources/rafter/charts/controller-manager/charts/minio/templates/_helper_create_bucket.txt
  resources/rafter/charts/controller-manager/charts/minio/templates/configmap.yaml
  resources/rafter/charts/controller-manager/charts/minio/templates/deployment.yaml
  resources/rafter/charts/controller-manager/charts/minio/templates/post-install-create-bucket-job.yaml
  resources/rafter/charts/upload-service/templates/_helper_migrate_buckets.txt
  resources/rafter/charts/upload-service/templates/migrator-job.yaml
  resources/rafter/templates/pre-upgrade-delete-vs-job.yaml
Labels: hacktoberfest-accepted, size/XL, lgtm

#12506 added kyma disclaimer to istio svc & po
  resources/istio-configuration/templates/istio-operator.yaml
Labels: area/security, area/service-mesh, size/S, lgtm

#12565 Fix typo
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#12564 Bump alpine version in ory
  resources/ory/values.yaml
Labels: size/XS, lgtm

#12571 Remove unused `minio_client` image from the `values` file
  resources/rafter/values.yaml
Labels: area/security, size/XS, lgtm

#12568 Extend kcp js wrapper
  tests/fast-integration/kcp/client.js
Labels: size/L, lgtm

#12569 Migrate skr upgrade test to kcp wrapper
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/upgrade-helpers.js
Labels: size/L, lgtm

#12549 Small improvements to the eventing-controller dev setup
  components/eventing-controller/README.md
  components/eventing-controller/config/default/controller_ko_image.yaml
  components/eventing-controller/config/default/manager_auth_proxy_patch.yaml
  components/eventing-controller/config/default/manager_config_patch.yaml
  components/eventing-controller/config/default/manager_env.yaml
  components/eventing-controller/config/manager/manager.yaml
Labels: area/eventing, size/M, lgtm

#12553 Rename commander to subscription manager in eventing-controller
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_test.go
  components/eventing-controller/pkg/commander/commander.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb_test.go
  components/eventing-controller/pkg/subscriptionmanager/manager.go
  components/eventing-controller/pkg/subscriptionmanager/mock/manager.go
  components/eventing-controller/pkg/subscriptionmanager/nats/nats.go
  components/eventing-controller/pkg/subscriptionmanager/nats/nats_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#12574 Fix a typo
  docs/01-overview/main-areas/service-management/smgt-01-overview.md
Labels: bug, area/documentation, size/XS, lgtm

#12566 Limit Loki ingestion rate
  resources/logging/charts/loki/templates/kyma-additions/loki.rules.yaml
  resources/logging/charts/loki/values.yaml
Labels: size/XS, lgtm

#12229 Changes to the monitoring chart
  resources/monitoring/charts/grafana/templates/_helpers.tpl
  resources/monitoring/charts/grafana/templates/_pod.tpl
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/monitoring/charts/kube-state-metrics/templates/deployment.yaml
  resources/monitoring/charts/kube-state-metrics/values.yaml
  resources/monitoring/charts/prometheus-istio/templates/deploy.yaml
  resources/monitoring/charts/prometheus-istio/values.yaml
  resources/monitoring/charts/prometheus-node-exporter/templates/daemonset.yaml
  resources/monitoring/charts/prometheus-node-exporter/values.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/deployment.yaml
  resources/monitoring/charts/prometheus-pushgateway/values.yaml
  resources/monitoring/templates/_helpers.tpl
  resources/monitoring/templates/alertmanager/alertmanager.yaml
  resources/monitoring/templates/prometheus-operator/deployment.yaml
  resources/monitoring/templates/prometheus/prometheus.yaml
  resources/monitoring/values.yaml
Labels: size/L, lgtm

#12578 upgrade kaniko version
  resources/serverless/values.yaml
Labels: area/security, size/XS, lgtm

#12552 Move git server to test images
  resources/serverless/charts/k3s-tests/templates/k3s-test.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#12555 Upgrade containerd lib and golang builder for application-operator
  components/application-operator/Dockerfile
  components/application-operator/go.mod
  components/application-operator/go.sum
  resources/application-connector/values.yaml
Labels: size/S, lgtm

#12587 bump nats exporter version to 0.9.0
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#12580 Upgrade serverless components
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/python38/Dockerfile
  components/function-runtimes/python38/kubeless/requirements.txt
  components/function-runtimes/python39/Dockerfile
  components/function-runtimes/python39/kubeless/requirements.txt
  resources/serverless/values.yaml
Labels: area/security, size/M, lgtm

#12589 Replace PR tags: Upgrade serverless components
  resources/serverless/values.yaml
Labels: size/S, lgtm

#12312 fix the eventingReady status change right after the backend switch
  components/eventing-controller/Dockerfile
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_test.go
  components/eventing-controller/testing/test_helpers.go
Labels: area/eventing, size/L, lgtm

#12592 Update serverless components
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/python38/Dockerfile
  components/function-runtimes/python38/kubeless/requirements.txt
  components/function-runtimes/python39/Dockerfile
  components/function-runtimes/python39/kubeless/requirements.txt
Labels: area/security, size/M, lgtm

#12595 Upgrade minio image
  resources/rafter/values.yaml
Labels: area/security, size/XS, lgtm

#12596 Bump eventing-controller's image
  components/eventing-controller/go.mod
  resources/eventing/values.yaml
Labels: size/M, lgtm

#12554 enable containerd support in fluent-bit, enable new multiline feature
  resources/logging/charts/fluent-bit/templates/configmap.yaml
  resources/logging/charts/fluent-bit/values.yaml
Labels: area/logging, size/XS, lgtm

#12584 Bump version of gjson dependency in Connector Service
  components/connector-service/Dockerfile
  components/connector-service/go.mod
  components/connector-service/go.sum
  resources/application-connector/values.yaml
Labels: size/M, lgtm

#12601 bump the image
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#12590 Bump: Update serverless components
  resources/serverless/values.yaml
Labels: size/S, lgtm

#12603 Bump cloudsql-proxy image in ory chart
  resources/ory/values.yaml
Labels: size/XS, lgtm

#12591 Bump podpreset-controller and podpreset-webhook image versions
  resources/cluster-essentials/values.yaml
Labels: size/XS, lgtm

#12577 Bump Ory components to the latest versions
  resources/ory/values.yaml
Labels: size/XS, lgtm

#12585 Upgrade containerd lib to v1.4.11 to mitigate CVE-2021-41103 and other security fixes
  components/application-connectivity-validator/Dockerfile
  components/application-connectivity-validator/go.mod
  components/application-connectivity-validator/go.sum
  components/application-gateway/Dockerfile
  components/application-gateway/go.mod
  components/application-gateway/go.sum
  components/application-registry/Dockerfile
  components/application-registry/go.mod
  components/application-registry/go.sum
  components/central-application-gateway/Dockerfile
  components/central-application-gateway/Makefile
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/Dockerfile
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
Labels: size/XXL, lgtm

#12546 Add a caution note
  docs/02-get-started/README.md
  docs/04-operation-guides/operations/02-install-kyma.md
Labels: area/documentation, size/S, lgtm

#12607 Use latest image for prometheus-operator-reloader
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#12610 Update application connectivity images to latest versions from registry
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/S, lgtm

#12614 Add note for auth proxy configuration on Windows
  docs/04-operation-guides/security/sec-06-access-expose-kiali-grafana.md
Labels: size/XS, lgtm

#12618 Update Ory oath2clients CRD
  installation/resources/crds/ory/oauth2clients.crd.yaml
Labels: size/L, lgtm

#12616 bump go version
  components/event-publisher-proxy/cmd/event-publisher-proxy/Dockerfile
  components/event-publisher-proxy/go.mod
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#12622 Add nullables to the App Mapping CRD
  installation/resources/crds/application-connector/applicationmappings.applicationconnector.crd.yaml
Labels: bug, size/XS, lgtm

#12621 Add Spec to SanityCheck in App Broker
  components/application-broker/cmd/broker/Dockerfile
  components/application-broker/go.mod
  components/application-broker/go.sum
  components/application-broker/internal/broker/sanity_check.go
  resources/application-connector/values.yaml
Labels: bug, size/M, lgtm

#12623 update to newest configmap reloader for prometheus
  resources/monitoring/charts/prometheus-istio/values.yaml
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#12625 Fix of application-gateway host regression
  components/application-gateway/internal/proxy/proxyfactory.go
  resources/application-connector/values.yaml
Labels: size/XS, lgtm

#12628 Update image version for application-gateway to the latest one
  resources/application-connector/values.yaml
Labels: size/XS, lgtm

#12629 Update docker builder image to golang:1.17.3-alpine for projects app-…
  components/application-connectivity-certs-setup-job/Dockerfile
  components/application-connectivity-certs-setup-job/go.mod
  components/application-connectivity-certs-setup-job/go.sum
  components/central-application-connectivity-validator/Dockerfile
Labels: size/L, lgtm

#12620 Fix problems with concurrent updates in Compass
  tests/fast-integration/compass/client.js
Labels: size/M, lgtm

#12632 Replace some vunerable libs in central-connectivity-validator
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  resources/application-connector/values.yaml
Labels: size/M, lgtm

#12514 Fast-integration hourly periodic for SKR nightly
  tests/fast-integration/Makefile
  tests/fast-integration/kcp/client.js
  tests/fast-integration/package.json
  tests/fast-integration/skr-nightly/provision/provision-skr-nightly.js
  tests/fast-integration/skr-nightly/skr-nightly.js
  tests/fast-integration/skr-nightly/test/test-nightly.js
  tests/fast-integration/skr-test/helpers.js
  tests/fast-integration/skr-test/index.js
  tests/fast-integration/skr-test/skr-test.js
  tests/fast-integration/skr-test/test.js
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/test/2-getting-started-guides.js
  tests/fast-integration/test/index.js
  tests/fast-integration/test/test.js
Labels: size/XL, lgtm

#12633 improve error logging for skr-upgrade pipeline
  tests/fast-integration/kcp/client.js
Labels: size/XS, lgtm

#12634 Change installation timeout to 20 min
  components/kyma-operator/pkg/kymahelm/kyma-helm-client.go
Labels: size/XS, lgtm

#12635 fix kyma upgrade command
  tests/fast-integration/kcp/client.js
Labels: size/XS, lgtm

#12637 Update Eventing images
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#12638 Update Google pause image registry in serverless
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#12639 Update serverless chart codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#12642 Bump busybox to 1.34.1 to fix CVEs
  resources/application-connector/values.yaml
  resources/monitoring/values.yaml
  resources/ory/values.yaml
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#12640 Remove unnecessary helm values from profiles in istio-configuration component
  resources/istio-configuration/profile-evaluation.yaml
  resources/istio-configuration/profile-production.yaml
Labels: area/service-mesh, size/XS, lgtm

#12636 add debug info for runtime status
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
Labels: size/XS, lgtm

#12646 Bump busybox to 1.34.1 to fix CVEs - 1.24
  resources/monitoring/charts/grafana/values.yaml
  resources/ory/charts/hydra/values.yaml
  resources/ory/charts/oathkeeper/values.yaml
Labels: size/XS, lgtm

#12611 Replace the `registry` component
  resources/serverless/charts/docker-registry/templates/deployment.yaml
  resources/serverless/values.yaml
Labels: enhancement, area/security, size/XS, lgtm

#12645 Update Kyma version to 1.24.9
  VERSION
  installation/resources/installer.yaml
Labels: size/XS, lgtm

#12465 Adjust Application Connectivity docs to Kyma 2.0, pt.2
  docs/01-overview/main-areas/application-connectivity/README.md
  docs/01-overview/main-areas/application-connectivity/ac-03-application-registry.md
  docs/01-overview/main-areas/application-connectivity/ac-05-useful-links.md
  docs/01-overview/main-areas/application-connectivity/ra-01-runtime-agent-overview.md
  docs/03-tutorials/00-application-connectivity/ac-01-create-application.md
  docs/03-tutorials/00-application-connectivity/ac-02-get-client-certificate.md
  docs/03-tutorials/00-application-connectivity/ac-03-register-manage-services.md
  docs/03-tutorials/00-application-connectivity/ac-04-register-secured-api.md
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
  docs/03-tutorials/00-application-connectivity/ac-06-renew-client-cert.md
  docs/03-tutorials/00-application-connectivity/ac-07-revoke-client-cert.md
  docs/03-tutorials/00-application-connectivity/ac-08-rotate-root-ca.md
  docs/03-tutorials/00-application-connectivity/ac-09-get-api-specification.md
  docs/03-tutorials/00-application-connectivity/ac-10-get-subscribed-events.md
  docs/03-tutorials/00-application-connectivity/ra-01-establish-secure-connection-with-compass.md
  docs/03-tutorials/00-application-connectivity/ra-02-maintain-secure-connection-with-compass.md
  docs/03-tutorials/00-application-connectivity/ra-03-revoke-client-certificate.md
  docs/04-operation-guides/operations/ac-03-application-connector-certificates.md
  docs/04-operation-guides/operations/ac-04-access-ac-on-local.md
  docs/04-operation-guides/operations/ra-01-enable-kyma-with-runtime-agent.md
  docs/04-operation-guides/troubleshooting/ac-01-application-gateway-troubleshooting.md
  docs/05-technical-reference/00-architecture/ac-01-application-connector-components.md
  docs/05-technical-reference/00-architecture/ac-02-connector-service.md
  docs/05-technical-reference/00-architecture/ra-01-runtime-agent-workflow.md
  docs/05-technical-reference/00-configuration-parameters/ac-04-application-connectivity-certs-setup-job.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/ac-01-application.md
  docs/05-technical-reference/00-custom-resources/ac-02-eventactivation.md
  docs/05-technical-reference/00-custom-resources/ac-02-tokenrequest.md
  docs/05-technical-reference/ac-01-application-gateway-details.md
  docs/05-technical-reference/ra-01-configuring-runtime.md
Labels: area/documentation, area/application-connector, size/L, lgtm

#12656 bump postgres in ORY from 11.13-alpine to 11.14-alpine
  resources/ory/values.yaml
Labels: size/XS, lgtm

#12658 Assure sufficient privileges to migrate 1.x users to cluster-admins
  resources/busola-migrator/templates/rbac.yaml
Labels: size/XS, lgtm

#12630 Increase maxUnavailable count for DaemonSets
  resources/logging/charts/fluent-bit/values.yaml
  resources/monitoring/charts/prometheus-node-exporter/values.yaml
Labels: size/S, lgtm

#12427 introduce help target for makefile
  common/makefiles/generic-make-go.mk
Labels: area/quality, size/M, lgtm

#12650 Fix configpath error
  tests/fast-integration/kcp/client.js
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
Labels: size/M, lgtm

#12662 change in glossary.md and quick-install.md
  docs/02-get-started/01-quick-install.md
  docs/glossary.md
Labels: area/documentation, size/S, lgtm

#12664 Bump Ory components to the latest versions and update CRD - 1.25
  installation/resources/crds/ory/oauth2clients.crd.yaml
  resources/cluster-essentials/files/oauth2clients.crd.yaml
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
  resources/ory/charts/hydra/values.yaml
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/values.yaml
  resources/ory/charts/oathkeeper/values.yaml
Labels: area/security, size/XL, lgtm

#12660 update fluent-bit to 1.8.10
  resources/logging/values.yaml
  resources/telemetry/values.yaml
Labels: area/logging, size/XS, lgtm

#12659 removed resourceSelector workaround from monitoring chart
  CODEOWNERS
  resources/istio-configuration/templates/monitoring/service-monitor.yaml
  resources/monitoring/templates/prometheus-operator/deployment.yaml
  resources/monitoring/templates/prometheus/prometheus.yaml
  resources/monitoring/values.yaml
Labels: area/monitoring, size/M, lgtm

#12663 Update version to 1.25.0-rc1
  .kyma-project-io/values.yaml
  VERSION
  installation/resources/installer.yaml
Labels: size/XS, lgtm

#12598 optionally enable build failures caused by linting
  common/makefiles/generic-make-go.mk
Labels: size/S, lgtm

#12665 Upgrade alpine to 3.14.3 version in Console
  resources/console/charts/web/values.yaml
  resources/helm-broker/charts/addons-ui/values.yaml
  resources/logging/charts/logui/values.yaml
  resources/service-catalog-addons/charts/service-catalog-ui/values.yaml
Labels: area/console, size/S, lgtm

#12682 Update postgres 11.14-alpine tag
  resources/ory/values.yaml
Labels: size/XS, lgtm

#12415 Replaced nats-operator with nats helm chart
  installation/resources/crds/eventing/natsclusters.nats.crd.yaml
  installation/resources/crds/eventing/natsserviceroles.nats.crd.yaml
  resources/cluster-essentials/files/natsclusters.nats.crd.yaml
  resources/cluster-essentials/files/natsserviceroles.nats.crd.yaml
  resources/eventing/README.md
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/nats/.helmignore
  resources/eventing/charts/nats/Chart.yaml
  resources/eventing/charts/nats/README.md
  resources/eventing/charts/nats/templates/00-prereqs.yaml
  resources/eventing/charts/nats/templates/10-deployment.yaml
  resources/eventing/charts/nats/templates/20-service.yaml
  resources/eventing/charts/nats/templates/40-cr.yaml
  resources/eventing/charts/nats/templates/50-servicemonitor.yaml
  resources/eventing/charts/nats/templates/_helpers.tpl
  resources/eventing/charts/nats/templates/configmap.yaml
  resources/eventing/charts/nats/templates/destination-rule.yaml
  resources/eventing/charts/nats/templates/service.yaml
  resources/eventing/charts/nats/templates/serviceMonitor.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
  resources/eventing/profile-evaluation.yaml
  resources/eventing/profile-production.yaml
  resources/eventing/values.yaml
Labels: size/XXL, lgtm

#12679 bump istio-installer to 1.12.0
  components/istio-installer/Dockerfile
Labels: area/service-mesh, size/XS, lgtm

#12667 bump postgres 11.13-alpine to 11.14-alpine
  resources/ory/charts/postgresql/values.yaml
Labels: size/XS, lgtm

#12599 refactoring according to golangci-lint checks
  components/eventing-controller/Makefile
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#12691 Disable istio for SC webhook
  resources/service-catalog/charts/catalog/templates/webhook-deployment.yaml
Labels: size/XS, lgtm

#12684 Bump image to include the timeout increase on kyma installer
  tools/kyma-installer/kyma.Dockerfile
Labels: size/XS, lgtm

#12681 Increase maxUnavailable count for DaemonSets
  resources/logging/charts/fluent-bit/values.yaml
  resources/monitoring/charts/prometheus-node-exporter/values.yaml
Labels: size/S, lgtm

#12653 Extend KO dev environment
  components/eventing-controller/Makefile
  components/eventing-controller/config/default/controller_ko_image.yaml
  components/eventing-controller/config/default/manager_env.yaml
  components/eventing-controller/config/manager/manager.yaml
Labels: size/XS, lgtm

#12644 Add AuthorizationPolicies for obervabilty services
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-serviceaccount.yaml
  resources/kiali/templates/kyma-additions/authorization-policy.yaml
  resources/logging/charts/loki/templates/kyma-additions/authorizationpolicy.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-serviceaccount.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/authorization-policy.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-serviceaccount.yaml
  resources/tracing/templates/kyma-additions/authorization-policy.yaml
  resources/tracing/templates/kyma-additions/peerauthentication.yaml
Labels: size/L, lgtm

#12699 Removed unused reloader and exporter from NATS helm chart
  resources/eventing/charts/nats/README.md
  resources/eventing/charts/nats/templates/service.yaml
  resources/eventing/charts/nats/templates/serviceMonitor.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#12690 add Knative info to 1.21 migration guide
  docs/migration-guides/1.20-1.21.md
Labels: area/documentation, size/M, lgtm

#12696 Extend waiting time for updating Condition in installation CRD.
  components/kyma-operator/pkg/conditionmanager/condition-manager.go
Labels: area/installation, size/S, lgtm

#12705 Explicit delete pods for fast integration tests
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
  tests/fast-integration/utils/index.js
Labels: size/S, lgtm

#12710 Format and build the kyma-operator image
  components/kyma-operator/go.sum
  components/kyma-operator/pkg/conditionmanager/condition-manager.go
Labels: size/XS, lgtm

#12712 Bump kyma operator with fix to the condition manager
  tools/kyma-installer/kyma.Dockerfile
Labels: size/XS, lgtm

#12700 Move dependencies section to the Chart definition in Oathkeeper
  resources/ory/charts/oathkeeper/Chart.yaml
  resources/ory/charts/oathkeeper/requirements.yaml
Labels: area/security, size/S, lgtm

#12717 Add Benjamin Lindner to code owners
  CODEOWNERS
Labels: size/S, lgtm

#12550 Remove old Ory jobs for Kyma 2.0
  resources/ory/charts/oathkeeper/templates/job.yaml
  resources/ory/templates/job-secret-migration.yaml
Labels: size/L, lgtm

#12677 update eventing-controller dependency in event-publisher-proxy
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/event-publisher-proxy/pkg/subscribed/helpers.go
  components/event-publisher-proxy/pkg/subscribed/helpers_test.go
  components/event-publisher-proxy/testing/utils.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#12567 Add a new Condition for BEB Webhook callback status
  components/eventing-controller/api/v1alpha1/subscription_lifecycle.go
  components/eventing-controller/api/v1alpha1/subscription_lifecycle_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#12701 remove nats-operator
  CODEOWNERS
  components/nats-operator/Makefile
  components/nats-operator/README.md
  components/nats-operator/cmd/nats-operator-doctor/Dockerfile
  components/nats-operator/cmd/nats-operator-doctor/main.go
  components/nats-operator/cmd/nats-operator/Dockerfile
  components/nats-operator/go.mod
  components/nats-operator/go.sum
  components/nats-operator/logger/logger.go
  components/nats-operator/logger/logger_test.go
  components/nats-operator/options/options.go
  components/nats-operator/options/options_test.go
  components/nats-operator/pkg/client/natscluster/client.go
  components/nats-operator/pkg/client/natscluster/fake/client.go
  components/nats-operator/pkg/doctor/doctor.go
  components/nats-operator/pkg/doctor/doctor_test.go
  components/nats-operator/pkg/doctor/state.go
  components/nats-operator/pkg/doctor/state_test.go
  components/nats-operator/pkg/errors/errors.go
  components/nats-operator/pkg/errors/errors_test.go
  components/nats-operator/pkg/testing/k8s.go
  components/nats-operator/pkg/testing/natscluster.go
Labels: area/eventing, size/XXL, lgtm

#12693 Update Grafana
  resources/monitoring/charts/grafana/Chart.yaml
  resources/monitoring/charts/grafana/templates/_helpers.tpl
  resources/monitoring/charts/grafana/templates/_pod.tpl
  resources/monitoring/charts/grafana/templates/configmap-dashboard-provider.yaml
  resources/monitoring/charts/grafana/templates/configmap.yaml
  resources/monitoring/charts/grafana/templates/deployment.yaml
  resources/monitoring/charts/grafana/templates/image-renderer-deployment.yaml
  resources/monitoring/charts/grafana/templates/image-renderer-service.yaml
  resources/monitoring/charts/grafana/templates/ingress.yaml
  resources/monitoring/charts/grafana/templates/podsecuritypolicy.yaml
  resources/monitoring/charts/grafana/templates/pvc.yaml
  resources/monitoring/charts/grafana/templates/secret.yaml
  resources/monitoring/charts/grafana/templates/service.yaml
  resources/monitoring/charts/grafana/templates/statefulset.yaml
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring, size/L, lgtm

#12709 Adapt observability AuthorizationPolicies for disabled auth-proxies
  resources/kiali/templates/kyma-additions/auth-proxy-serviceaccount.yaml
  resources/kiali/templates/kyma-additions/authorization-policy.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-serviceaccount.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/authorization-policy.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-serviceaccount.yaml
  resources/tracing/templates/kyma-additions/authorization-policy.yaml
Labels: size/M, lgtm

#12723 update nats server to 2.6.5
  resources/eventing/values.yaml
Labels: area/eventing, lgtm

#12724 update oauth2-proxy to 7.2
  resources/kiali/values.yaml
  resources/monitoring/values.yaml
  resources/tracing/values.yaml
Labels: area/monitoring, area/tracing, size/XS, lgtm

#12688 Increase timeout for commerce-mock test
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: size/XS, lgtm

#12725 Bump Fluent-Bit image
  resources/logging/charts/fluent-bit/values.yaml
Labels: area/logging, size/XS, lgtm

#12716 correct steps for Busola Dashboard in Get Started
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/02-get-started/04-trigger-workload-with-event.md
Labels: area/documentation, size/S, lgtm

#12731 fix a bug in step 3
  docs/02-get-started/03-deploy-expose-microservice.md
Labels: size/XS, lgtm

#12726 Bump auth-proxy image
  resources/kiali/values.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/tracing/values.yaml
Labels: area/monitoring, area/tracing, size/XS, lgtm

#12648 Allow using different mock namespaces
  tests/fast-integration/README.md
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/test/fixtures/commerce-mock/commerce-mock.yaml
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: area/eventing, area/ci, size/M, lgtm

#12737 Fix a broken link
  docs/03-tutorials/03-set-up-idp.md
Labels: bug, area/documentation, size/XS, lgtm

#12739 Add permissive mTLS policy for Fluent Bit
  resources/logging/charts/fluent-bit/templates/kyma-additions/peerauthentication.yaml
  resources/logging/charts/fluent-bit/values.yaml
Labels: area/monitoring, area/logging, size/S, lgtm

#12741 Bump helm-broker related images
  resources/helm-broker/values.yaml
Labels: size/XS, lgtm

#12747 Update the k3d version in Prerequisites for Kyma installation and Get Started
  docs/02-get-started/README.md
  docs/04-operation-guides/operations/02-install-kyma.md
Labels: area/documentation, size/XS, lgtm

#12745 Scrape Fluent Bit via HTTP if permissive mTLS is set
  resources/logging/charts/fluent-bit/templates/servicemonitor.yaml
Labels: size/XS, lgtm

#12748 Update docs to use k3d v5
  docs/04-operation-guides/operations/02-install-kyma.md
Labels: area/cli, size/XS, lgtm
