Repository kyma-project/kyma, pull requests merged in 2021-04, with the labels that each got.

#11007 Update the event-type cleanup logic
  components/event-publisher-proxy/pkg/handler/http/handler.go
  components/event-publisher-proxy/pkg/handler/nats/handler.go
  components/event-publisher-proxy/pkg/legacy-events/legacy.go
  components/event-publisher-proxy/pkg/legacy-events/legacy_test.go
  components/eventing-controller/pkg/application/clean.go
  components/eventing-controller/pkg/application/clean_test.go
  components/eventing-controller/pkg/handlers/eventtype/clean.go
  components/eventing-controller/pkg/handlers/eventtype/clean_test.go
  components/eventing-controller/pkg/handlers/eventtype/parse.go
  components/eventing-controller/pkg/handlers/eventtype/parse_test.go
  components/eventing-controller/testing/test_helpers.go
Labels: area/eventing

#11036 Update the Eventing docs
  docs/eventing/02-01-eventing-architecture.md
Labels: area/eventing

#11008 Update the Eventing publishers and controllers images
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/event-publisher-nats/values.yaml
  resources/eventing/charts/event-publisher-proxy/values.yaml
  resources/eventing/charts/nats-controller/values.yaml
Labels: area/eventing

#11034 Update the event-type cleanup logic (#11007)
  components/event-publisher-proxy/pkg/handler/http/handler.go
  components/event-publisher-proxy/pkg/handler/nats/handler.go
  components/event-publisher-proxy/pkg/legacy-events/legacy.go
  components/event-publisher-proxy/pkg/legacy-events/legacy_test.go
  components/eventing-controller/pkg/application/clean.go
  components/eventing-controller/pkg/application/clean_test.go
  components/eventing-controller/pkg/handlers/eventtype/clean.go
  components/eventing-controller/pkg/handlers/eventtype/clean_test.go
  components/eventing-controller/pkg/handlers/eventtype/parse.go
  components/eventing-controller/pkg/handlers/eventtype/parse_test.go
  components/eventing-controller/testing/test_helpers.go
  docs/eventing/02-01-eventing-architecture.md
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/event-publisher-nats/values.yaml
  resources/eventing/charts/event-publisher-proxy/values.yaml
  resources/eventing/charts/nats-controller/values.yaml
Labels: area/eventing

#11037 Upgrade 'busybox' in application-gateway-legacy-tests
  resources/application-connector/values.yaml
  tests/application-gateway-legacy-tests/test/executor/Dockerfile
Labels: area/application-connector, area/security

#11011 Add @rafalpotempa and @koala7659 to missing OWNERS
  components/application-connectivity-certs-setup-job/OWNERS
  components/application-connectivity-validator/OWNERS
  components/application-gateway/OWNERS
  components/application-operator/OWNERS
  components/application-registry/OWNERS
  components/compass-runtime-agent/OWNERS
  components/connection-token-handler/OWNERS
  components/connector-service/OWNERS
  resources/application-connector/OWNERS
  resources/application-connector/charts/application-operator/OWNERS
  resources/application-connector/charts/application-registry/OWNERS
  resources/application-connector/charts/connection-token-handler/OWNERS
  resources/application-connector/charts/connector-service/OWNERS
  resources/compass-runtime-agent/OWNERS
  tests/application-connector-tests/OWNERS
  tests/application-gateway-legacy-tests/OWNERS
  tests/application-gateway-tests/OWNERS
  tests/application-operator-tests/OWNERS
  tests/application-registry-tests/OWNERS
  tests/compass-runtime-agent/OWNERS
  tests/connection-token-handler-tests/OWNERS
  tests/connector-service-tests/OWNERS
Labels: area/application-connector

#11042 update fluent-bit base image
  resources/logging/charts/fluent-bit/values.yaml
Labels: area/logging

#10968 Sync ORY/Oathkeeper charts to the latest version
  resources/cluster-essentials/files/rules.crd.yaml
  resources/ory/charts/oathkeeper/Chart.yaml
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/templates/_helpers.tpl
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/templates/rbac.yaml
  resources/ory/charts/oathkeeper/charts/oathkeeper-master/values.yaml
  resources/ory/charts/oathkeeper/templates/NOTES.txt
  resources/ory/charts/oathkeeper/templates/_helpers.tpl
  resources/ory/charts/oathkeeper/templates/configmap-config-demo.yaml
  resources/ory/charts/oathkeeper/templates/configmap-rules.yaml
  resources/ory/charts/oathkeeper/templates/deployment-controller.yaml
  resources/ory/charts/oathkeeper/templates/ingress-api.yaml
  resources/ory/charts/oathkeeper/templates/ingress-proxy.yaml
  resources/ory/charts/oathkeeper/templates/service-api.yaml
  resources/ory/charts/oathkeeper/templates/service-proxy.yaml
  resources/ory/charts/oathkeeper/values.yaml
Labels: WIP

#11050 Fix eventing health probes coming outside of Istio mesh
  resources/eventing/charts/event-publisher-nats/templates/service.yaml
  resources/eventing/charts/nats-controller/templates/deployment.yaml
  resources/eventing/charts/nats-controller/templates/service.yaml
  resources/eventing/values.yaml
Labels: priority/critical

#11015 Upgrade istio-installer to use Istio version 1.9.1
  components/istio-installer/Dockerfile
Labels: area/service-mesh

#11074 Fix a link after renaming the master branch to main
  docs/kyma/06-01-installation.md
Labels: area/documentation, bug

#11058 Add latency metrics for the Event publishers
  components/event-publisher-proxy/cmd/event-publisher-nats/main.go
  components/event-publisher-proxy/cmd/event-publisher-proxy/main.go
  components/event-publisher-proxy/pkg/handler/http/handler.go
  components/event-publisher-proxy/pkg/handler/http/handler_test.go
  components/event-publisher-proxy/pkg/handler/nats/handler.go
  components/event-publisher-proxy/pkg/handler/nats/handler_test.go
  components/event-publisher-proxy/pkg/metrics/collector.go
  components/event-publisher-proxy/pkg/metrics/metricstest/metricstest.go
  components/event-publisher-proxy/pkg/metrics/server.go
  components/event-publisher-proxy/testing/utils.go
Labels: area/eventing

#11088 Update connectivity-validator Eventing dashboard label
  components/application-operator/charts/application/templates/validator.yaml
Labels: area/eventing

#11092 Upgrade 'application-connector' and 'compass-runtime-agent' images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, area/quality

#11096 Fix the link
  docs/kyma/04-07-upgrade.md
Labels: area/documentation, bug

#11083 re-setting retention time for loki
  resources/logging/charts/loki/values.yaml
Labels: area/logging

#11101 Add Nina Hingerl to documentation codeowners
  CODEOWNERS
Labels: area/documentation

#10987 Add busola-migrator component and redirecting logic
  CODEOWNERS
  components/busola-migrator/.gitignore
  components/busola-migrator/Dockerfile
  components/busola-migrator/Makefile
  components/busola-migrator/README.md
  components/busola-migrator/go.mod
  components/busola-migrator/go.sum
  components/busola-migrator/internal/app/app.go
  components/busola-migrator/internal/app/fixtures_test.go
  components/busola-migrator/internal/app/health.go
  components/busola-migrator/internal/app/health_test.go
  components/busola-migrator/internal/app/migrate.go
  components/busola-migrator/internal/app/migrate_test.go
  components/busola-migrator/internal/app/redirect.go
  components/busola-migrator/internal/app/redirect_test.go
  components/busola-migrator/internal/app/static.go
  components/busola-migrator/internal/app/static_test.go
  components/busola-migrator/internal/busola/encoder.go
  components/busola-migrator/internal/busola/encoder_test.go
  components/busola-migrator/internal/busola/init.go
  components/busola-migrator/internal/busola/init_test.go
  components/busola-migrator/internal/config/config.go
  components/busola-migrator/internal/kubernetes/config.go
  components/busola-migrator/internal/router/router.go
  components/busola-migrator/internal/router/router_test.go
  components/busola-migrator/main.go
  components/busola-migrator/pkg/ptr/ptr.go
  components/busola-migrator/pkg/ptr/ptr_test.go
  components/busola-migrator/static/assets/72-Bold-full.woff
  components/busola-migrator/static/assets/72-Light-full.woff
  components/busola-migrator/static/assets/72-Regular-full.woff
  components/busola-migrator/static/assets/SAP-icons.woff
  components/busola-migrator/static/assets/fundamental-styles.css
  components/busola-migrator/static/assets/style.css
  components/busola-migrator/static/index.html
  resources/busola-migrator/.helmignore
  resources/busola-migrator/Chart.yaml
  resources/busola-migrator/README.md
  resources/busola-migrator/templates/_helpers.tpl
  resources/busola-migrator/templates/deployment.yaml
  resources/busola-migrator/templates/service.yaml
  resources/busola-migrator/templates/serviceaccount.yaml
  resources/busola-migrator/templates/virtualservice.yaml
  resources/busola-migrator/values.yaml
Labels: area/console, area/security, enhancement

#11026 Expose a common interface for different messaging backends
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/pkg/handlers/beb_test.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/pkg/handlers/utils.go
  components/eventing-controller/reconciler/subscription-nats/reconciler.go
  components/eventing-controller/reconciler/subscription/reconciler.go
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/nats-controller/values.yaml
Labels: area/eventing

#11131 Update Eventing dashboard selectors
  resources/eventing/charts/dashboards/templates/delivery.yaml
  resources/eventing/charts/dashboards/templates/pods.yaml
Labels: area/eventing

#11137 Remove the 1.20-1.21 migration guide
  docs/migration-guides/1.20-1.21.md
Labels: area/documentation

#11138 Remove the 1.20-1.21 migration guide
  docs/migration-guides/1.20-1.21.md
Labels: area/documentation

#11150 Update application-broker image
  resources/application-connector/values.yaml
Labels: area/application-connector, area/eventing

#11149 Bump Golang version in Application Connectivity
  components/application-connectivity-certs-setup-job/Dockerfile
  components/application-connectivity-certs-setup-job/go.mod
  components/application-connectivity-validator/Dockerfile
  components/application-connectivity-validator/go.mod
  components/application-gateway/Dockerfile
  components/application-gateway/go.mod
  components/application-operator/Dockerfile
  components/application-registry/Dockerfile
  components/application-registry/go.mod
  components/compass-runtime-agent/Dockerfile
  components/compass-runtime-agent/go.mod
  components/connection-token-handler/Dockerfile
  components/connection-token-handler/go.mod
  components/connector-service/Dockerfile
  components/connector-service/go.mod
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector

#11143 updates base images of grafana, fluent-bit, kiali
  resources/kiali/values.yaml
  resources/logging/charts/fluent-bit/values.yaml
  resources/monitoring/charts/grafana/values.yaml
Labels: area/logging, area/monitoring

#11157 Bump Application Connectivity
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector

#11160 Add the link to Busola console to allowlist
  milv.config.yaml
Labels: area/documentation

#11164 Update image tag for the serverless test
  resources/serverless/values.yaml
Labels: area/serverless

#11167 Add Azure link to allowlist
  docs/serverless/08-06-set-external-registry.md
  milv.config.yaml
Labels: area/documentation

#11168 K8s-tools: bump image
  resources/eventing/values.yaml
Labels: area/ci

#11176 Fix random port generator for Event publisher tests
  components/event-publisher-proxy/testing/utils.go
Labels: area/eventing

#11171 Update Event publishers images
  resources/eventing/charts/event-publisher-nats/values.yaml
  resources/eventing/charts/event-publisher-proxy/values.yaml
Labels: area/eventing

#11156 Single binary event controller
  components/eventing-controller/README.md
  components/eventing-controller/cmd/eventing-controller-nats/Dockerfile
  components/eventing-controller/cmd/eventing-controller-nats/main.go
  components/eventing-controller/cmd/eventing-controller/beb/beb.go
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/cmd/eventing-controller/nats/nats.go
  components/eventing-controller/pkg/env/config.go
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/nats-controller/templates/deployment.yaml
  resources/eventing/charts/nats-controller/values.yaml
Labels: area/eventing, lgtm, size/XL

#11178 Migrate observability resources to new api versions
  resources/monitoring/charts/grafana/templates/_helpers.tpl
  resources/monitoring/charts/prometheus-istio/templates/_helpers.tpl
Labels: lgtm, size/XS

#11194 Prepare release 1.22.0
  VERSION
  installation/resources/installer.yaml
Labels: lgtm, size/XS

#11198 Adjust the list of available nodejs runtimes
  installation/resources/crds/serverless/functions.serverless.crd.yaml
Labels: lgtm, size/XS

#11117 Remove redundant annotations from catalog resources
  resources/service-catalog/charts/catalog/values.yaml
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/getting-started-guides/redis-addon-sb-si.yaml
Labels: lgtm, size/S

#11119 Add kiali and tracing component to Kyma Alpha deploy flow
  installation/resources/components.yaml
Labels: area/cli, lgtm, size/XS

#11188 remove unnecessary crds
  resources/cluster-essentials/files/init-300-httpsource.crd.yaml
  resources/cluster-essentials/files/init-kafkachannel.crd.yaml
  resources/cluster-essentials/files/natschannel.crd.yaml
Labels: lgtm, size/L

#11195 fix document order in git and netlify
  docs/operation-guides/config-01-install-kyma-custom.md
  docs/operation-guides/config-08-securityconcept-roles.md
  docs/overview/03-CLI-overview.md
Labels: area/documentation, lgtm, size/XS

#11189 Fix KO for eventing-publisher-nats
  components/event-publisher-proxy/config/event-publisher-nats/100-service.yaml
  components/event-publisher-proxy/config/event-publisher-nats/110-clusterrole.yaml
  components/event-publisher-proxy/config/event-publisher-nats/115-clusterrolebinding.yaml
  components/event-publisher-proxy/config/event-publisher-nats/120-peerauthentication.yaml
  components/event-publisher-proxy/config/event-publisher-nats/125-serviceaccount.yaml
  components/event-publisher-proxy/config/event-publisher-nats/200-deployment.yaml
Labels: area/eventing, lgtm, size/L

#11206 Revert "Migrate observability resources to new api versions"
  resources/monitoring/charts/grafana/templates/_helpers.tpl
  resources/monitoring/charts/prometheus-istio/templates/_helpers.tpl
Labels: lgtm, size/XS

#11207 Fix eventing-controller makefile
  components/eventing-controller/Makefile
  components/eventing-controller/README.md
Labels: area/eventing, lgtm, size/M
