Repository kyma-project/kyma, pull requests merged in 2022-11, with the labels that each got.

#15952 Update go dependencies for application connector and compass-runtime-agent: net, crypto and text
  components/application-operator/go.mod
  components/application-operator/go.sum
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/XL, lgtm

#15961 Bump eventing images
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#15854 remove deprecated nodejs12
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/dockerfiles.yaml
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  components/function-controller/internal/controllers/serverless/fixtures_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/gitops_test.go
  components/function-controller/internal/controllers/serverless/gitrepo/git_repo_controller_test.go
  components/function-controller/internal/controllers/serverless/runtime/nodejs_test.go
  components/function-controller/internal/controllers/serverless/runtime/runtime.go
  components/function-controller/internal/controllers/serverless/runtime/runtime_test.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/runtime_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/runtime_validation.go
  components/function-runtimes/Makefile
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/templates/runtimes.yaml
  resources/serverless/values.yaml
  tests/function-controller/testsuite/scenarios/gitops.go
  tests/function-controller/testsuite/scenarios/light_runtimes.go
Labels: size/L, lgtm

#15899 Add new troubleshooting guide for consumer with pending messages
  docs/04-operation-guides/assets/grafana_pending_consumer.png
  docs/04-operation-guides/troubleshooting/eventing/evnt-05-fix-pending-messages.md
Labels: area/documentation, area/eventing, size/L, lgtm

#15940 bump gomega version to 1.23 in Eventing
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/controllers/subscription/testing/test_utils.go
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#15971 Remove documentation about PSP in context of serverless functions
  docs/01-overview/main-areas/serverless/svls-06-security-considerations.md
Labels: area/documentation, area/serverless, size/XS, lgtm

#15924 Caching the OAuth tokens in Application Gateway
  components/central-application-gateway/internal/metadata/serviceapi/serviceapiservice.go
  components/central-application-gateway/pkg/authorization/externaltokenstrategy_test.go
  components/central-application-gateway/pkg/authorization/factory.go
  components/central-application-gateway/pkg/authorization/factory_test.go
  components/central-application-gateway/pkg/authorization/mocks/OAuthClient.go
  components/central-application-gateway/pkg/authorization/model.go
  components/central-application-gateway/pkg/authorization/oauth/mocks/Client.go
  components/central-application-gateway/pkg/authorization/oauth/oauthclient.go
  components/central-application-gateway/pkg/authorization/oauth/oauthclient_test.go
  components/central-application-gateway/pkg/authorization/oauthcertstrategy.go
  components/central-application-gateway/pkg/authorization/oauthcertstrategy_test.go
  components/central-application-gateway/pkg/authorization/oauthstrategy.go
  components/central-application-gateway/pkg/authorization/oauthstrategy_test.go
  resources/application-connector/values.yaml
  tests/components/application-connector/Makefile.test-application-gateway
  tests/components/application-connector/docs/application-gateway-tests.md
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-oauth-nagative-other-ca.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-oauth-negative-expired-client-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-oauth-negative-expired-server-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, hacktoberfest-accepted, size/L, lgtm

#15948 Serverless picks bump
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15946 Remove serverless psp
  components/function-controller/cmd/manager/main.go
  components/function-controller/config/rbac/role.yaml
  components/function-controller/internal/controllers/kubernetes/fixtures_test.go
  components/function-controller/internal/controllers/kubernetes/namespace_controller.go
  components/function-controller/internal/controllers/kubernetes/namespace_controller_test.go
  components/function-controller/internal/controllers/kubernetes/role_controller.go
  components/function-controller/internal/controllers/kubernetes/role_controller_test.go
  components/function-controller/internal/controllers/kubernetes/role_service.go
  components/function-controller/internal/controllers/kubernetes/role_service_test.go
  components/function-controller/internal/controllers/kubernetes/rolebinding_controller.go
  components/function-controller/internal/controllers/kubernetes/rolebinding_controller_test.go
  components/function-controller/internal/controllers/kubernetes/rolebinding_service.go
  components/function-controller/internal/controllers/kubernetes/rolebinding_service_test.go
  components/function-controller/internal/controllers/kubernetes/shared.go
  components/function-controller/internal/controllers/kubernetes/suite_test.go
  components/function-controller/internal/controllers/serverless/config.go
  components/function-controller/internal/controllers/serverless/system_state.go
  resources/serverless/templates/deployment.yaml
  resources/serverless/templates/psp-build.yaml
  resources/serverless/templates/psp-function.yaml
  resources/serverless/templates/role-build.yaml
  resources/serverless/templates/role-function.yaml
  resources/serverless/templates/rolebinding-build.yaml
  resources/serverless/templates/rolebinding-function.yaml
  resources/serverless/templates/service-accounts.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/XXL, lgtm, kind/cleanup

#15967 Cherry-pick Istio 1.15.3 (#15959)
  resources/istio-resources/files/dashboards/control-plane.json
  resources/istio-resources/files/dashboards/mesh.json
  resources/istio-resources/files/dashboards/performance.json
  resources/istio-resources/files/dashboards/service.json
  resources/istio-resources/files/dashboards/workload.json
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: area/service-mesh, size/S, lgtm

#15941 Enfore trace collector restart if configuration changes
  components/telemetry-operator/controller/tracepipeline/config_hash.go
  components/telemetry-operator/controller/tracepipeline/config_hash_test.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/controller_test.go
  components/telemetry-operator/controller/tracepipeline/resources.go
  components/telemetry-operator/controller/tracepipeline/resources_test.go
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15977 Update application-operator module dependency
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/S, lgtm

#15979 Update postgres exporter image
  resources/ory/values.yaml
Labels: area/api-gateway, size/XS, lgtm

#15981 remove the `golangci.yml` file
  components/function-controller/.golangci.yml
Labels: area/serverless, size/L, lgtm, kind/cleanup

#15963 Remove test inrepo config.
  .prow/inrepo-test.yaml
Labels: area/ci, size/M, lgtm, area/prow

#15987 Update openssl
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
Labels: size/XS, lgtm

#15990 Update openssl
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  resources/serverless/values.yaml
Labels: size/S, lgtm

#15993 Application Connector and compass runtime agent cherry pick with update go dependencies for application connector and compass-runtime-agent
  components/application-operator/go.mod
  components/application-operator/go.sum
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
Labels: size/XL, lgtm

#15966 removing common/ingressgateway
  common/go.mod
  common/go.sum
  common/ingressgateway/doc.go
  common/ingressgateway/ingressgateway.go
  common/ingressgateway/ingressgateway_test.go
  common/logging/logger/logger.go
Labels: size/L, lgtm

#15997 Removing Magda Strek from owners of common directory
  CODEOWNERS
Labels: size/XS, lgtm

#16000 Update gce proxy image
  resources/ory/values.yaml
Labels: size/XS, lgtm

#15950 upgrade to oauth2-proxy 7.4.0
  resources/kiali/values.yaml
  resources/monitoring/values.yaml
  resources/tracing/values.yaml
Labels: area/monitoring, size/XS, lgtm

#16002 Cherrypick GCEProxy image update
  resources/ory/values.yaml
Labels: size/XS, lgtm

#15976 fast-integration: use dummy credentials for BTP operator in SKR tests
  tests/fast-integration/skr-test/provision/provision-skr.js
  tests/fast-integration/smctl/helpers.js
Labels: size/S, lgtm

#16005 Update application-operator module dependency with latest version from branch release-2.8
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
Labels: size/S, lgtm

#15999 Improve common logging to allow the use of AtomicLevel
  common/logging/logger/logger.go
  common/logging/logger/logger_test.go
Labels: area/serverless, area/logging, size/M, lgtm

#15975 Manually delete a manually created NATS consumer
  components/eventing-controller/pkg/backend/jetstreamv2/errors.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_internal_unit_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/stubs_test.go
  components/eventing-controller/utils/errors.go
  resources/eventing/values.yaml
Labels: kind/bug, area/eventing, size/L, lgtm

#14975 Add API versioning and deprecation policy
  docs/05-technical-reference/00-api-overview/README.md
Labels: size/M, lgtm

#16011 Remove ok-to-test workflow
  .github/workflows/ok-to-test.yaml
  .github/workflows/trusted-dev.yaml
Labels: size/M, lgtm

#16010 Bump AC and CRA images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#16012 Fix makefiles
  tests/components/application-connector/Makefile.test-application-conn-validator
  tests/components/application-connector/Makefile.test-application-gateway
  tests/components/application-connector/Makefile.test-compass-runtime-agent
Labels: size/XS, lgtm

#16008 Fix flaky reconciler test
  components/eventing-controller/controllers/subscriptionv2/eventmesh/reconciler_integration_test.go
Labels: size/XS, lgtm

#16016 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#16017 Bump k8s-tools image in Kyma 2.8
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15965 Remove PSP from api-gatway
  resources/api-gateway/templates/psp.yaml
  resources/api-gateway/templates/rbac.yaml
  resources/api-gateway/templates/webhook-certificates.yaml
  resources/api-gateway/values.yaml
Labels: size/M, lgtm

#15566 Compass Runtime Agent tests - readme
  milv.config.yaml
  tests/components/application-connector/README.md
  tests/components/application-connector/docs/assets/compass-runtime-agent-tests-architecture.svg
  tests/components/application-connector/docs/compass-runtime-agent-tests.md
Labels: area/application-connector, size/L, lgtm, area/tests

#16022 Move security context in ory charts
  resources/ory/charts/hydra/charts/hydra-maester/templates/deployment.yaml
  resources/ory/charts/postgresql/templates/statefulset.yaml
Labels: size/S, lgtm

#16023 Bump changelog generator
  .github/workflows/github-release.yaml
Labels: size/XS, lgtm

#15982 Bump prometheus and operator
  installation/resources/crds/monitoring/alertmanagerconfigs.monitoring.coreos.crd.yaml
  installation/resources/crds/monitoring/alertmanagers.monitoring.coreos.crd.yaml
  installation/resources/crds/monitoring/podmonitors.monitoring.coreos.crd.yaml
  installation/resources/crds/monitoring/probes.monitoring.coreos.crd.yaml
  installation/resources/crds/monitoring/prometheuses.monitoring.crd.yaml
  installation/resources/crds/monitoring/prometheusrules.monitoring.crd.yaml
  installation/resources/crds/monitoring/servicemonitors.monitoring.coreos.crd.yaml
  installation/resources/crds/monitoring/thanosrulers.monitoring.coreos.crd.yaml
  resources/monitoring/values.yaml
Labels: size/XL, lgtm

#16020 Bump Eventing NATS image to 2.9.6
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#16018 Bump dependencies for eventing controller and epp
  components/event-publisher-proxy/Dockerfile
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/Dockerfile
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/M, lgtm

#15877 Component test to expose workload with custom domain
  tests/components/api-gateway/Makefile
  tests/components/api-gateway/README.md
  tests/components/api-gateway/custom_domain_test.go
  tests/components/api-gateway/features/api-gateway/oauth2_jwt_1path.feature
  tests/components/api-gateway/features/api-gateway/oauth2_jwt_2path.feature
  tests/components/api-gateway/features/api-gateway/oauth2_secured_endpoint.feature
  tests/components/api-gateway/features/api-gateway/secure_to_unsecure.feature
  tests/components/api-gateway/features/api-gateway/service_per_path.feature
  tests/components/api-gateway/features/api-gateway/unsecure_to_secure_OAuth2.feature
  tests/components/api-gateway/features/api-gateway/unsecure_to_secure_OAuth2_JWT.feature
  tests/components/api-gateway/features/api-gateway/unsecured_endpoint.feature
  tests/components/api-gateway/features/e2e/custom_domain.feature
  tests/components/api-gateway/go.mod
  tests/components/api-gateway/go.sum
  tests/components/api-gateway/main_test.go
  tests/components/api-gateway/manifests/custom-domain/resources.yaml
  tests/components/api-gateway/manifests/jwt-oauth-one-path-strategy.yaml
  tests/components/api-gateway/manifests/jwt-oauth-strategy.yaml
  tests/components/api-gateway/manifests/no_access_strategy.yaml
  tests/components/api-gateway/manifests/oauth-strategy.yaml
  tests/components/api-gateway/pkg/client/client.go
  tests/components/api-gateway/pkg/resource/batch.go
  tests/components/api-gateway/test_helpers.go
Labels: area/api-gateway, size/XL, lgtm, area/tests

#16043 Autobump Github Action images
  .github/dependabot.yml
Labels: size/XS, lgtm

#16044 Fix autobump Github Action images
  .github/dependabot.yml
Labels: size/XS, lgtm

#15862 Propose changes in the Function CRD
  components/function-controller/design/extend_function_spec_proposal.md
  components/function-controller/design/subresources_templates_proposal.md
Labels: size/XL, lgtm, architecture

#16037 Add details view to LogPipeline dashboard extension
  resources/telemetry/charts/operator/templates/logpipeline_busola_extension_cm.yaml
Labels: size/L, lgtm

#16015 Loki docs deprecation
  docs/01-overview/main-areas/assets/kyma-areas.svg
  docs/01-overview/main-areas/observability/README.md
  docs/01-overview/main-areas/observability/obsv-02-logging-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-10-useful-links.md
  docs/02-get-started/05-observability.md
  docs/04-operation-guides/operations/obsv-01-access-logs.md
  docs/04-operation-guides/operations/obsv-02-adjust-loki.md
  docs/04-operation-guides/troubleshooting/observability/obsv-03-troubleshoot-loki-logging.md
  docs/05-technical-reference/00-architecture/assets/obsv-logging-architecture.drawio.svg
  docs/05-technical-reference/00-architecture/obsv-02-architecture-logging.md
  docs/05-technical-reference/00-configuration-parameters/obsv-01-configpara-observability.md
Labels: size/M, lgtm

#15980 Remove PSP from CRA
  resources/compass-runtime-agent/templates/cluster-role-binding.yaml
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/templates/pod-security-policy.yaml
Labels: area/application-connector, size/M, lgtm, area/charts

#16063 [release-2.8] Fix python runtime security issues
  components/function-runtimes/python39/Dockerfile
  components/function-runtimes/python39/kubeless/kubeless.py
Labels: size/XS, lgtm

#16065 Bump Serverless runtimes
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#16052 Skip OTLP collector endpoint availability check in functions
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/lib/tracer.js
  components/function-runtimes/nodejs16/lib/tracer.js
  components/function-runtimes/python39/kubeless/tracing.py
  resources/serverless/values.yaml
Labels: size/M, lgtm

#16038 Delete Consumer with Unsubscription
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_integration_test.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#16060 Set latest images for telemetry components
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#16064 Bump Serverless images
  resources/serverless/values.yaml
Labels: size/S, lgtm

#16068 Bump PR images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: size/S, lgtm

#15996 bump nats-prometheus-exporter to v0.10.1
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#16049 Add Validation and Defaulting webhook for v1alpha2 subscriptions
  components/eventing-controller/PROJECT
  components/eventing-controller/api/v1alpha2/errors.go
  components/eventing-controller/api/v1alpha2/groupversion_info.go
  components/eventing-controller/api/v1alpha2/subscription_types.go
  components/eventing-controller/api/v1alpha2/subscription_webhook.go
  components/eventing-controller/api/v1alpha2/subscription_webhook_unit_test.go
  components/eventing-controller/config/.gitignore
  components/eventing-controller/config/crd/kustomization.yaml
  components/eventing-controller/config/helm/kustomization.yaml
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_internal_unit_test.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/reconciler.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/test/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler_internal_unit_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/utils.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/utils_unit_test.go
  components/eventing-controller/pkg/backend/cleaner/eventmesh.go
  components/eventing-controller/pkg/backend/cleaner/eventmesh_unit_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/test_helpers.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils_unit_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_v1v2_integration_test.go
  components/eventing-controller/pkg/env/backend_config.go
  resources/eventing/charts/controller/templates/clusterrole.yaml
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/templates/webhook.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/XXL, lgtm

#16066 Add sink validation to validating webhook
  components/eventing-controller/api/v1alpha2/errors.go
  components/eventing-controller/api/v1alpha2/subscription_webhook.go
  components/eventing-controller/api/v1alpha2/subscription_webhook_unit_test.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/test/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/test/utils.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler_internal_unit_test.go
  components/eventing-controller/pkg/backend/sink/v2/validator.go
  components/eventing-controller/pkg/backend/sink/v2/validator_test.go
  components/eventing-controller/pkg/backend/sink/validator.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go
  components/eventing-controller/testing/v2/test_helpers.go
  components/eventing-controller/utils/utils.go
  components/eventing-controller/utils/utils_unit_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#16072 Improved loki deprecation notes
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
  docs/04-operation-guides/operations/obsv-01-access-logs.md
  docs/05-technical-reference/00-architecture/obsv-02-architecture-logging.md
Labels: area/documentation, area/logging, size/S, lgtm

#16084 document new k8s 1.24 support
  docs/04-operation-guides/operations/02-install-kyma.md
Labels: size/XS, lgtm

#16004 Migrate from RegisteredLoggers to the AtomicLevel
  components/function-controller/cmd/manager/main.go
  components/function-controller/cmd/webhook/main.go
  components/function-controller/go.mod
  components/function-controller/go.sum
  components/function-controller/internal/logging/dynamic.go
  components/function-controller/internal/logging/registry.go
  components/function-controller/internal/logging/setup.go
  components/function-controller/internal/webhook/resources/resources.go
  resources/serverless/values.yaml
Labels: area/serverless, area/logging, size/L, lgtm, kind/cleanup

#16088 Update Eventing images
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#16090 Replace serverless PR tags
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm

#16085 Update Eventing deps
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  components/eventing-controller/pkg/backend/jetstreamv2/mocks/JetStreamContext.go
  components/eventing-controller/pkg/backend/jetstreamv2/stubs_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_v1v2_integration_test.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#16091 refactor of constructing build job
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/controllers/serverless/utils.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#16087 Add seccompprofile to istio
  resources/istio/values.yaml
Labels: size/XS, lgtm

#16109 Add specific CODEOWNER rules for observability
  CODEOWNERS
Labels: size/XS, lgtm

#16106 Fix config checksum
  components/telemetry-operator/controller/tracepipeline/config_hash.go
  components/telemetry-operator/controller/tracepipeline/config_hash_test.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/internal/configchecksum/checksum.go
  components/telemetry-operator/internal/configchecksum/checksum_test.go
Labels: size/L, lgtm

#16110 Improve busola extension
  resources/telemetry/charts/operator/templates/logpipeline_busola_extension_cm.yaml
Labels: size/L, lgtm

#15820 [Telemetry Operator] Extract finalizer logic
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/finalizer.go
  components/telemetry-operator/controller/logpipeline/finalizer_test.go
  components/telemetry-operator/controller/logpipeline/sync.go
  components/telemetry-operator/controller/logpipeline/sync_test.go
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#16094 Trace logging in upgrade tests
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: size/M, lgtm

#16114 Migration script 2.9 for PSP removal and other orphaned resources
  docs/assets/2.8-2.9-cleanup-psp.sh
  docs/migration-guide-2.8-2.9.md
Labels: size/M, lgtm

#16117 Cherry-pick migration script from main (60ada7e)
  docs/assets/2.8-2.9-cleanup-psp.sh
  docs/migration-guide-2.8-2.9.md
Labels: size/M, lgtm

#16115 Change http response code based on backend error
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/handler/handler_test.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream_test.go
  components/event-publisher-proxy/pkg/sender/sender.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#16095 remove explicit stream check from sending
  components/event-publisher-proxy/pkg/sender/jetstream.go
Labels: area/eventing, size/S, lgtm

#16097 Bump images for updated EPP and NATS
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#16122 update eventing from main
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/handler/handler_test.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream_test.go
  components/event-publisher-proxy/pkg/sender/sender.go
  components/eventing-controller/.golangci.yaml
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils_unit_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_integration_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_util.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_v1v2_integration_test.go
  components/eventing-controller/pkg/env/nats_config.go
  components/eventing-controller/pkg/env/nats_config_test.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream_test.go
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/profile-evaluation.yaml
  resources/eventing/profile-production.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#16124 Update VERSION to 2.9.0-rc2
  VERSION
Labels: size/XS, lgtm

#16101 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm

#16127 Bump dependencies eventing controller
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/M, lgtm

#16103 Introduces XFF configuration support for Istio via CRD
  CODEOWNERS
  docs/05-technical-reference/00-custom-resources/oper-01-istio.md
  installation/resources/crds/istio/istios.operator.crd.yaml
Labels: area/service-mesh, size/L, lgtm

#15934 Telemetry Operator - Add component for creating webhook certificates
  CODEOWNERS
  components/telemetry-operator/config/rbac/role.yaml
  components/telemetry-operator/controller/logparser/controller.go
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/main.go
  components/webhook-cert-init/.dockerignore
  components/webhook-cert-init/.gitignore
  components/webhook-cert-init/Dockerfile
  components/webhook-cert-init/Makefile
  components/webhook-cert-init/README.md
  components/webhook-cert-init/go.mod
  components/webhook-cert-init/go.sum
  components/webhook-cert-init/main.go
  resources/telemetry/charts/operator/templates/role.yaml
Labels: size/XL, lgtm

#16145 Change VERSION to 2.9.0
  VERSION
Labels: size/XS, lgtm

#16146 improve custom help text
  resources/telemetry/charts/operator/templates/logpipeline_busola_extension_cm.yaml
Labels: size/XS, lgtm

#16130 Bump dependencies `event-publisher-proxy`
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  resources/eventing/values.yaml
Labels: size/L, lgtm

#16150 Fix Dockerfile for webhook cert init image
  components/webhook-cert-init/Dockerfile
Labels: size/XS, lgtm

#16048 Assertion for secret creation while creating SKR
  tests/fast-integration/skr-test/test.js
Labels: size/S, lgtm

#16153 Telemetry Operator - Fix webhook cert init
  components/webhook-cert-init/main.go
Labels: size/XS, lgtm

#16144 Removed fetching specs from Compass
  components/compass-runtime-agent/internal/compass/director/client_test.go
  components/compass-runtime-agent/internal/compass/director/converter.go
  components/compass-runtime-agent/internal/compass/director/converter_test.go
  components/compass-runtime-agent/internal/compass/director/query.go
  components/compass-runtime-agent/internal/kyma/applications/converter.go
  components/compass-runtime-agent/internal/kyma/applications/converter_test.go
  components/compass-runtime-agent/internal/kyma/applications/util.go
  components/compass-runtime-agent/internal/kyma/model/types.go
  components/compass-runtime-agent/internal/kyma/model/util.go
  components/compass-runtime-agent/internal/kyma/service_test.go
  components/compass-runtime-agent/internal/kyma/util.go
  resources/compass-runtime-agent/values.yaml
Labels: size/XL, lgtm

#16155 Remove PR image for compass-runtime-agent
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#16116 Support structured json format of incoming CEs in nodejs runtimes
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/lib/ce.js
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/package.json
  components/function-runtimes/nodejs16/lib/ce.js
  components/function-runtimes/nodejs16/package.json
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
  docs/05-technical-reference/svls-08-function-specification.md
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/L, lgtm

#16086 Guard job for manifest
  components/telemetry-operator/Makefile
  components/telemetry-operator/hack/lint-manifests.sh
Labels: size/M, lgtm

#16152 Telemetry Operator - Use webhook cert init container
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/templates/validation_webhook.yaml
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/values.yaml
Labels: size/M, lgtm

#16156 Compass runtime agent graphQL fix cherrypick 2.8
  components/compass-runtime-agent/internal/compass/director/client_test.go
  components/compass-runtime-agent/internal/compass/director/converter.go
  components/compass-runtime-agent/internal/compass/director/converter_test.go
  components/compass-runtime-agent/internal/compass/director/query.go
  components/compass-runtime-agent/internal/kyma/applications/converter.go
  components/compass-runtime-agent/internal/kyma/applications/converter_test.go
  components/compass-runtime-agent/internal/kyma/applications/util.go
  components/compass-runtime-agent/internal/kyma/model/types.go
  components/compass-runtime-agent/internal/kyma/model/util.go
  components/compass-runtime-agent/internal/kyma/service_test.go
  components/compass-runtime-agent/internal/kyma/util.go
Labels: size/XL, lgtm

#16054 Remove internal names from CRD description fields
  components/telemetry-operator/apis/telemetry/v1alpha1/logparser_types.go
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/apis/telemetry/v1alpha1/tracepipeline_types.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  installation/resources/crds/telemetry/logparsers.crd.yaml
  installation/resources/crds/telemetry/logpipelines.crd.yaml
  resources/telemetry/charts/operator/values.yaml
Labels: size/L, lgtm

#16165 Change VERSION to 2.8.4
  VERSION
Labels: size/XS, lgtm

#16164 Compass runtime agent graphQL fix cherrypick 2.8
  components/compass-runtime-agent/internal/compass/director/client_test.go
  components/compass-runtime-agent/internal/compass/director/converter.go
  components/compass-runtime-agent/internal/compass/director/converter_test.go
  components/compass-runtime-agent/internal/compass/director/query.go
  components/compass-runtime-agent/internal/kyma/applications/converter.go
  components/compass-runtime-agent/internal/kyma/applications/converter_test.go
  components/compass-runtime-agent/internal/kyma/applications/util.go
  components/compass-runtime-agent/internal/kyma/model/types.go
  components/compass-runtime-agent/internal/kyma/model/util.go
  components/compass-runtime-agent/internal/kyma/service_test.go
  components/compass-runtime-agent/internal/kyma/util.go
Labels: size/XL, lgtm

#16138 Add Internal Registry Garbage Collection proposal
  components/function-controller/design/internal_registry_garbage_collection.md
Labels: kind/feature, area/serverless, size/M, lgtm

#16167 Image update for compass runtime agent graphQL fix cherrypick 2.9
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#16170 Change VERSION to 2.9.1
  VERSION
Labels: size/XS, lgtm

#16171 Telemetry Operator - Remove custom secrets cache
  components/telemetry-operator/controller/logparser/controller.go
  components/telemetry-operator/controller/logparser/sync.go
  components/telemetry-operator/controller/logparser/sync_test.go
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/secrets_cache.go
  components/telemetry-operator/controller/logpipeline/secrets_cache_test.go
  components/telemetry-operator/controller/logpipeline/sync.go
  components/telemetry-operator/controller/logpipeline/sync_test.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/internal/kubernetes/get_or_create.go
  components/telemetry-operator/internal/kubernetes/utils.go
  components/telemetry-operator/internal/kubernetes/utils_test.go
Labels: size/L, lgtm

#16104 Apply restricted secrity profile on Serverless components
  docs/01-overview/main-areas/serverless/svls-06-security-considerations.md
  resources/serverless/charts/docker-registry/templates/deployment.yaml
  resources/serverless/charts/docker-registry/values.yaml
  resources/serverless/charts/webhook/templates/deployment.yaml
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#16173 Login customizations
  tests/fast-integration/kcp/client.js
Labels: size/M, lgtm

#16108 add SecretMounts to function API
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  components/function-controller/internal/controllers/serverless/deployment_test.go
  components/function-controller/internal/controllers/serverless/fixtures_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/zz_generated.deepcopy.go
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/XL, lgtm

#16166 Expose gateway name and gateway cert secret in serverless chart
  resources/serverless/templates/daemonset-certs-configmap.yaml
  resources/serverless/templates/daemonset-certs.yaml
  resources/serverless/templates/virtualservice.yaml
  resources/serverless/values.yaml
Labels: size/S, lgtm

#16185 Update Froggy codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#16187 fast-integration: fix KCP test oauth timeout
  tests/fast-integration/kcp/client.js
Labels: size/S, lgtm

#16188 Telemetry Operator - Set resources for init container
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/values.yaml
Labels: size/S, lgtm

#16184 Include striped down otel collector image in telemetry operator
  components/telemetry-operator/Makefile
  components/telemetry-operator/controller/tracepipeline/resources.go
  components/telemetry-operator/main.go
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#16192 Drop tobiscr from fast-integration codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#16190 Copy .npmrc into nodejs16 runtime
  resources/serverless/templates/runtimes.yaml
Labels: size/XS, lgtm

#16172 Fix retry on conflict in Serverless integration tests
  resources/serverless/values.yaml
  tests/function-controller/pkg/function/function.go
  tests/function-controller/pkg/function/v1alpha1/function.go
  tests/function-controller/pkg/resource/resource.go
  tests/function-controller/pkg/retry/retry.go
Labels: kind/bug, area/serverless, size/M, lgtm, kind/flake, area/tests

#16189 Opentelemetry collector base configuration
  components/telemetry-operator/config/crd/kustomization.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_tracepipeline_jaeger.yaml
  components/telemetry-operator/controller/tracepipeline/resources.go
  resources/telemetry/values.yaml
Labels: size/M, lgtm

#16182 add tip about creating App from Busola
  docs/03-tutorials/00-application-connectivity/ac-01-create-application.md
Labels: area/documentation, area/busola, area/application-connector, size/XS, lgtm

#16204 Fix reflecting Fluent Bit state on LogParser CRD
  components/telemetry-operator/controller/logparser/controller.go
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#16206 Bump otel-collector image
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#16131 Add stream re-creation check in eventing FI tests
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
  tests/fast-integration/utils/index.js
Labels: area/eventing, size/L, lgtm

#16213 Fix EventMesh namespace in Exact type matching for Sub v1alpha2 CRD
  components/eventing-controller/pkg/backend/utils/eventmesh_utils.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils_test.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#16168 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm

#16147 Add missing CRD_NAME env for api-gateway cert webhook
  resources/api-gateway/templates/webhook-certificates.yaml
  resources/api-gateway/values.yaml
Labels: size/M, lgtm

#16202 New Watch Method with Custom K8S Context
  tests/fast-integration/kcp/client.js
  tests/fast-integration/utils/index.js
Labels: size/XS, lgtm

#16211 Fix tracepipeline controller crash
  components/telemetry-operator/controller/logparser/controller.go
  components/telemetry-operator/controller/logparser/setup.go
  components/telemetry-operator/controller/logparser/setup_test.go
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/setup.go
  components/telemetry-operator/controller/logpipeline/setup_test.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/setup.go
  components/telemetry-operator/controller/tracepipeline/setup_test.go
  resources/telemetry/values.yaml
Labels: size/XL, lgtm

#16220 Delete 2.5-2.6 and 2.8-2.9 cleanups
  docs/assets/2.5-2.6-cleanup-logging-fluent-bit.sh
  docs/assets/2.8-2.9-cleanup-psp.sh
Labels: area/documentation, size/M, lgtm

#16222 Fixing manifests check error
  components/telemetry-operator/Makefile
Labels: size/XS, lgtm

#16223 Duplicate definition of GF_PATHS_PROVISIONING env variable in grafana
  resources/monitoring/charts/grafana/values.yaml
Labels: kind/bug, area/monitoring, size/XS, lgtm

#16224 updated kiwigrid sidecar to newest python version
  resources/monitoring/values.yaml
Labels: area/monitoring, size/XS, lgtm

#16133 Clean consumers for ec restart
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/errors.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_internal_unit_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/mocks/Backend.go
  components/eventing-controller/pkg/backend/jetstreamv2/mocks/JetStreamBackend.go
  components/eventing-controller/pkg/backend/jetstreamv2/stubs_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/types.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_integration_test.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream_test.go
  components/eventing-controller/testing/v2/test_helpers.go
  components/eventing-controller/utils/errors.go
  resources/eventing/values.yaml
Labels: size/XL, lgtm
