Repository kyma-project/kyma, pull requests merged in 2022-01, with the labels that each got.

#12962 Fix arguments for provisionSKR() in skr-svcat-migration-test
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
Labels: size/XS, lgtm

#12915 Update tracing charts to latest images.
  installation/resources/crds/tracing/jaegers.jaegertracing.crd.yaml
  resources/cluster-essentials/files/jaegers.jaegertracing.crd.yaml
  resources/tracing/Chart.yaml
  resources/tracing/templates/_helpers.tpl
  resources/tracing/templates/crds.yaml
  resources/tracing/templates/deployment.yaml
  resources/tracing/templates/jaeger.yaml
  resources/tracing/templates/kyma-additions/metrics-service.yaml
  resources/tracing/templates/kyma-additions/metrics-servicemonitor.yaml
  resources/tracing/templates/kyma-additions/peerauthentication.yaml
  resources/tracing/templates/kyma-additions/zipkin-service.yaml
  resources/tracing/templates/role.yaml
  resources/tracing/templates/service.yaml
  resources/tracing/values.yaml
Labels: size/XXL, lgtm

#12965 Update fluent-bit image from main on to release branch
  resources/logging/charts/fluent-bit/values.yaml
Labels: size/XS, lgtm

#12971 add skr provisioning parameter info to client lib
  tests/fast-integration/kyma-environment-broker/client.js
Labels: size/XS, lgtm

#12881 Loki Dashboard Revamp
  resources/logging/charts/loki/templates/kyma-additions/grafana-dashboard.yaml
Labels: size/XXL, lgtm

#12974 Fix kyma-preview-integration-dev timeouts
  tests/fast-integration/skr-test/test.js
Labels: size/XS, lgtm

#12980 Bump event subscriber go version
  tools/event-subscriber/Dockerfile
Labels: size/XS, lgtm

#12985 Revert port customisations
  resources/tracing/templates/deployment.yaml
  resources/tracing/templates/service.yaml
Labels: size/S, lgtm

#12939 Change version to main
  .github/workflows/github-release.yaml
  CODEOWNERS
  VERSION
Labels: size/XS, lgtm

#12987 Update uaa activator gomod - CVE-2021-3121
  components/uaa-activator/go.mod
  components/uaa-activator/go.sum
  components/uaa-activator/internal/dex/overrider.go
  components/uaa-activator/internal/uaa/waiter.go
Labels: size/XL, lgtm

#12914 Add functions startup metrics
  components/function-controller/cmd/manager/main.go
  components/function-controller/go.mod
  components/function-controller/internal/controllers/serverless/function_controller.go
  components/function-controller/internal/controllers/serverless/function_metrics.go
  resources/serverless/templates/function-metrics-dashboard.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#12973 move customParams info away from client into upgrade test
  tests/fast-integration/kyma-environment-broker/client.js
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
Labels: size/XS, lgtm

#12984 Adding namespace kyma-integration in compass-runtime-agent chart
  resources/compass-runtime-agent/templates/integration-namespace.yaml
Labels: size/XS, lgtm

#12970 OWNERS and CODEOWNERS cleanup
  CODEOWNERS
  common/OWNERS
  components/application-connectivity-certs-setup-job/OWNERS
  components/application-connectivity-validator/OWNERS
  components/application-gateway/OWNERS
  components/application-operator/OWNERS
  components/application-registry/OWNERS
  components/central-application-connectivity-validator/OWNERS
  components/central-application-gateway/OWNERS
  components/compass-runtime-agent/OWNERS
  components/connection-token-handler/OWNERS
  components/connector-service/OWNERS
  resources/application-connector/OWNERS
  resources/application-connector/charts/application-operator/OWNERS
  resources/application-connector/charts/application-registry/OWNERS
  resources/application-connector/charts/central-application-connectivity-validator/OWNERS
  resources/application-connector/charts/connection-token-handler/OWNERS
  resources/application-connector/charts/connector-service/OWNERS
  resources/compass-runtime-agent/OWNERS
  tests/application-connector-tests/OWNERS
  tests/application-gateway-legacy-tests/OWNERS
  tests/application-gateway-tests/OWNERS
  tests/application-operator-tests/OWNERS
  tests/application-registry-tests/OWNERS
  tests/compass-runtime-agent/OWNERS
  tests/connection-token-handler-tests/OWNERS
  tests/connector-service-tests/OWNERS
Labels: size/L, lgtm

#12994 Cherry pick from main of decoupling compass-runtime-agent and application-connector to Kyma release 2.0 branch
  resources/compass-runtime-agent/templates/integration-namespace.yaml
Labels: size/XS, lgtm

#12989 Bump Serverless test image
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#12900 skr-svcat-migration test with KEB
  tests/fast-integration/kyma-environment-broker/client.js
  tests/fast-integration/kyma-environment-broker/helpers.js
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-test/skr-test.js
Labels: size/M, lgtm

#12975 Provide fix for #12972
  installation/resources/crds/tracing/jaegers.jaegertracing.crd.yaml
Labels: size/XS, lgtm

#12910 update Telemetry Operator to use new LogPipeline CRD
  components/telemetry-operator/Dockerfile
  components/telemetry-operator/Makefile
  components/telemetry-operator/PROJECT
  components/telemetry-operator/README.md
  components/telemetry-operator/api/v1alpha1/loggingconfiguration_types.go
  components/telemetry-operator/api/v1alpha1/logpipeline_types.go
  components/telemetry-operator/api/v1alpha1/zz_generated.deepcopy.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_loggingconfigurations.yaml
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  components/telemetry-operator/config/crd/kustomization.yaml
  components/telemetry-operator/config/crd/patches/cainjection_in_logpipelines.yaml
  components/telemetry-operator/config/crd/patches/webhook_in_logpipelines.yaml
  components/telemetry-operator/config/rbac/logpipeline_editor_role.yaml
  components/telemetry-operator/config/rbac/logpipeline_viewer_role.yaml
  components/telemetry-operator/config/rbac/role.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_loggingconfiguration.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline.yaml
  components/telemetry-operator/controllers/loggingconfiguration_controller.go
  components/telemetry-operator/controllers/logpipeline_controller.go
  components/telemetry-operator/controllers/logpipeline_controller_test.go
  components/telemetry-operator/controllers/suite_test.go
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/fluentbit/config_builder_test.go
  components/telemetry-operator/main.go
Labels: size/XXL, lgtm

#13009 Bump version to 2.0.1
  VERSION
Labels: size/XS, lgtm

#13010 Rename oauth2 proxy secrets
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-secret.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-secret.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-secret.yaml
Labels: size/S, lgtm

#13011 Rename oauth2 proxy secrets
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-secret.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-secret.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-secret.yaml
Labels: size/S, lgtm

#12988 Remove sayanh and suleymanakbas91 from codeowners
  CODEOWNERS
  OWNERS_ALIASES
  common/OWNERS
  resources/monitoring/OWNERS
  resources/tracing/OWNERS
  tests/perf/OWNERS
Labels: size/M, lgtm

#13017 Disable istio for service catalog webhook
  resources/service-catalog/charts/catalog/templates/webhook-deployment.yaml
  resources/service-catalog/charts/catalog/values.yaml
Labels: size/XS, lgtm

#13013 Add deprecated auth-proxy Secrets to cleanup script
  docs/assets/1.24-2.0-remove-deprecated-resources.sh
Labels: size/S, lgtm

#13020 Add deprecated auth-proxy Secrets to cleanup script
  docs/assets/1.24-2.0-remove-deprecated-resources.sh
Labels: size/S, lgtm

#13022 Set istio inject to false for service catalog webhook
  resources/service-catalog/charts/catalog/values.yaml
Labels: size/XS, lgtm

#13024 Point the tag in the migration guide to 2.0
  docs/migration-guide-1.24-2.0.md
Labels: area/documentation, size/XS, lgtm

#13027 Remove the migration script from main
  docs/assets/1.24-2.0-remove-deprecated-resources.sh
Labels: area/documentation, size/L, lgtm

#13028 Set istio inject to false for service catalog webhook (release-2.0)
  resources/service-catalog/charts/catalog/templates/webhook-deployment.yaml
  resources/service-catalog/charts/catalog/values.yaml
Labels: size/XS, lgtm

#13023 Enable healthz endpoints in service-catalog-webhook and sm-proxy init container probes it
  resources/service-catalog/charts/catalog/templates/webhook-service.yaml
  resources/service-catalog/charts/catalog/values.yaml
  resources/service-manager-proxy/templates/deployment.yaml
  resources/service-manager-proxy/values.yaml
Labels: size/S, lgtm

#13030 Enable healthz endpoints in service-catalog-webhook and sm-proxy init container probes it (release-2.0)
  resources/service-catalog/charts/catalog/templates/webhook-service.yaml
  resources/service-catalog/charts/catalog/values.yaml
  resources/service-manager-proxy/templates/deployment.yaml
  resources/service-manager-proxy/values.yaml
Labels: size/S, lgtm

#13019 istio running on solo fips distroless images
  resources/istio-configuration/Chart.yaml
  resources/istio-configuration/values.yaml
Labels: area/security, area/service-mesh, area/installation, size/S, lgtm

#13018 Fix updateSKR() in fast-integration
  tests/fast-integration/kyma-environment-broker/helpers.js
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-test/skr-test.js
  tests/fast-integration/skr-test/test.js
Labels: size/S, lgtm

#12951 Add tests for valid sink with path (#12810)
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
Labels: size/XS, lgtm

#12995 Fix upgrade-test-cleanup test
  tests/fast-integration/upgrade-test/upgrade-test-cleanup.js
Labels: size/XS, lgtm

#13006 Serverless tests improvments
  resources/serverless/charts/k3s-tests/templates/k3s-test.yaml
Labels: size/M, lgtm

#13032 istio-configuration clean up
  resources/istio-configuration/Chart.yaml
  resources/istio-configuration/templates/istio-operator.yaml
  resources/istio-configuration/values.yaml
Labels: area/service-mesh, size/S, lgtm

#13033 Cherry pick bug fixes from main to release-2.0
  components/eventing-controller/README.md
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/pkg/env/backend_config.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/pkg/object/equality.go
  components/eventing-controller/pkg/object/equality_test.go
  components/eventing-controller/testing/bebmock.go
  components/eventing-controller/testing/saferequests.go
  components/eventing-controller/testing/safesubscriptions.go
  components/eventing-controller/testing/subscriber.go
  components/eventing-controller/testing/test_helpers.go
  installation/resources/crds/eventing/eventingbackends.eventing.kyma-project.io.crd.yaml
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, size/XXL, lgtm

#13035 Cherry pick bug fixes from main to release-2.0
  resources/eventing/charts/nats/templates/service.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
  resources/eventing/profile-evaluation.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/S, lgtm

#13036 Bump version to 2.0.2
  VERSION
Labels: size/XS, lgtm

#13039 cleanup old istio leftovers
  docs/04-operation-guides/troubleshooting/smsh-04-istio-sidecar-version.md
  milv.config.yaml
Labels: size/XS, lgtm

#12967 cleanup permission-controller
  CODEOWNERS
  components/permission-controller/.gitignore
  components/permission-controller/Dockerfile
  components/permission-controller/Makefile
  components/permission-controller/OWNERS
  components/permission-controller/PROJECT
  components/permission-controller/README.md
  components/permission-controller/controllers/namespace_controller.go
  components/permission-controller/controllers/namespace_controller_test.go
  components/permission-controller/controllers/suite_test.go
  components/permission-controller/go.mod
  components/permission-controller/go.sum
  components/permission-controller/main.go
Labels: size/XL, lgtm

#12990 Update CRs formatting according to new guidelines
  docs/01-overview/main-areas/api-exposure/apix-02-useful-links.md
  docs/01-overview/main-areas/serverless/svls-01-overview.md
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/02-get-started/README.md
  docs/03-tutorials/00-api-exposure/apix-01-own-domain.md
  docs/03-tutorials/00-api-exposure/apix-02-expose-service-apigateway.md
  docs/03-tutorials/00-api-exposure/apix-03-expose-and-secure-service.md
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
  docs/03-tutorials/00-serverless/svls-03-expose-function.md
  docs/03-tutorials/03-set-up-idp.md
  docs/04-operation-guides/troubleshooting/apix-01-apigateway-connect-api-rule.md
  docs/04-operation-guides/troubleshooting/apix-02-dns-mgt-connection-refused.md
  docs/04-operation-guides/troubleshooting/apix-03-dns-mgt-could-not-resolve-host.md
  docs/04-operation-guides/troubleshooting/apix-04-dns-mgt-resource-ignored.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
  docs/05-technical-reference/apix-01-config-authorizations-apigateway.md
  docs/05-technical-reference/apix-02-whitelisted-domains.md
  docs/05-technical-reference/apix-03-blacklisted-services.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
  tests/fast-integration/README.md
  tests/function-controller/README.md
Labels: size/L, lgtm

#13041 Bump API-Gateway controller version to include subdomain blocklist
  resources/api-gateway/values.yaml
Labels: area/api-gateway, size/XS, lgtm

#13044 istio-configuration clean up
  resources/istio-configuration/templates/istio-operator.yaml
  resources/istio-configuration/values.yaml
Labels: area/service-mesh, size/XS, lgtm

#13045 telemetry Operator update parser config handling
  components/telemetry-operator/controllers/logpipeline_controller.go
Labels: size/S, lgtm

#13031 update docu on istio specific conf in kyma
  docs/01-overview/main-areas/service-mesh/smsh-02-default-istio-setup-in-kyma.md
  docs/04-operation-guides/operations/03-change-kyma-config-values.md
Labels: area/documentation, area/service-mesh, size/S, lgtm

#13047 Fix installer version
  installation/resources/installer.yaml
Labels: size/XS, lgtm

#12931 update telemetry operator resource
  resources/telemetry/Chart.yaml
  resources/telemetry/charts/fluent-bit/templates/_pod.tpl
  resources/telemetry/charts/fluent-bit/values.yaml
  resources/telemetry/charts/operator/Chart.yaml
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/templates/leader-election-role.yaml
  resources/telemetry/charts/operator/templates/loggingconfiguration-editor-role.yaml
  resources/telemetry/charts/operator/templates/loggingconfiguration-viewer-role.yaml
  resources/telemetry/charts/operator/templates/logpipeline_editor_role.yaml
  resources/telemetry/charts/operator/templates/logpipeline_viewer_role.yaml
  resources/telemetry/charts/operator/templates/role.yaml
  resources/telemetry/crds/loggingconfiguration.crd.yaml
  resources/telemetry/crds/logpipelines.crd.yaml
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/log-pipeline.yaml
  tests/fast-integration/telemetry-test/logging-config.yaml
  tests/fast-integration/telemetry-test/telemetry-test.js
Labels: size/L, lgtm

#13055 Cleanup unused functions
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
Labels: size/M, lgtm

#13034 Upgrade pushgateway chart
  resources/monitoring/charts/prometheus-pushgateway/Chart.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/deployment.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/ingress.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/networkpolicy.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/pdb.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/service.yaml
  resources/monitoring/charts/prometheus-pushgateway/templates/servicemonitor.yaml
  resources/monitoring/charts/prometheus-pushgateway/values.yaml
  resources/monitoring/values.yaml
Labels: area/monitoring, size/L, lgtm

#13021 Remove global variables from fn ctrl
  components/function-controller/cmd/manager/main.go
  components/function-controller/go.mod
  components/function-controller/go.sum
  components/function-controller/internal/controllers/serverless/automock/git_operator.go
  components/function-controller/internal/controllers/serverless/automock/stats_collector.go
  components/function-controller/internal/controllers/serverless/function_controller.go
  components/function-controller/internal/controllers/serverless/function_metrics.go
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  components/function-controller/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/metrics/function_metrics.go
  components/function-controller/internal/controllers/serverless/metrics/function_metrics_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#13064 Extend svcat migration fast-integration test timeout and improve stability
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
Labels: size/S, lgtm

#12998 Cherry pick from main: Expose istio /healthz/ready endpoint to public (#12754)
  resources/certificates/templates/virtualservice.yaml
Labels: size/S, lgtm

#13069 fix spelling issue
  docs/04-operation-guides/operations/03-change-kyma-config-values.md
  resources/serverless/charts/k3s-tests/values.yaml
  tests/integration/api-gateway/Makefile
Labels: size/S, lgtm

#13061 Fix central-application-connectivity-validator legacy gatewayName in VirtualService
  resources/application-connector/charts/central-application-connectivity-validator/templates/virtual-service.yaml
Labels: area/application-connector, size/XS, lgtm

#13075 Move initial check for SBU before the migration
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
Labels: size/S, lgtm

#13068 Busola logs
  docs/02-get-started/05-observability.md
Labels: size/XS, lgtm

#13004 Event Subscription Get Started update
  docs/02-get-started/04-trigger-workload-with-event.md
Labels: size/S, lgtm

#13080 Fix cluster admin role name typo in busola migrator
  components/busola-migrator/internal/kubernetes/client.go
Labels: size/XS

#13082 Fix cluster admin role name typo in busola migrator
  resources/busola-migrator/values.yaml
Labels: size/XS

#13084 Fix cluster admin role name typo in busola migrator (#13080)
  components/busola-migrator/internal/kubernetes/client.go
Labels: size/XS, lgtm

#13087 Cherry-Pick image bump to fix cluster admin role name typo
  resources/busola-migrator/values.yaml
Labels: size/XS, lgtm

#13088 Update version to 2.0.3
  VERSION
Labels: size/XS, lgtm

#13089 add jellyfish as fast integration test code owner
  CODEOWNERS
Labels: size/XS, lgtm

#13073 enable debug for upgrade-test-cleanup test
  tests/fast-integration/package.json
Labels: size/XS, lgtm

#12997 Retry reconciling subscriptions on NATS disconnect
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/options/options.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/pkg/subscriptionmanager/nats/nats_test.go
  components/eventing-controller/testing/matchers.go
  components/eventing-controller/testing/subscriber.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#13002 fix: broken legacy event cleanup
  components/event-publisher-proxy/pkg/handler/beb/handler.go
  components/event-publisher-proxy/pkg/legacy-events/helpers_test.go
  components/event-publisher-proxy/pkg/legacy-events/legacy.go
  components/event-publisher-proxy/pkg/legacy-events/legacy_test.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#13040 cleanup `iam-kubeconfig`
  CODEOWNERS
  components/iam-kubeconfig-service/.gitignore
  components/iam-kubeconfig-service/Dockerfile
  components/iam-kubeconfig-service/Makefile
  components/iam-kubeconfig-service/OWNERS
  components/iam-kubeconfig-service/README.md
  components/iam-kubeconfig-service/cmd/generator/main.go
  components/iam-kubeconfig-service/cmd/generator/reload/doc.go
  components/iam-kubeconfig-service/cmd/generator/reload/reload.go
  components/iam-kubeconfig-service/cmd/generator/reload/watch.go
  components/iam-kubeconfig-service/cmd/generator/reload/watch_test.go
  components/iam-kubeconfig-service/doc.go
  components/iam-kubeconfig-service/go.mod
  components/iam-kubeconfig-service/go.sum
  components/iam-kubeconfig-service/internal/authn/middleware.go
  components/iam-kubeconfig-service/internal/authn/middleware_test.go
  components/iam-kubeconfig-service/internal/authn/oidc.go
  components/iam-kubeconfig-service/pkg/kube_config/endpoints.go
  components/iam-kubeconfig-service/pkg/kube_config/endpoints_test.go
  components/iam-kubeconfig-service/pkg/kube_config/kube_config.go
Labels: size/XXL, lgtm

#13054 cleanup `dex`
  CODEOWNERS
  components/dex-static-user-configurer/Dockerfile
  components/dex-static-user-configurer/Makefile
  components/dex-static-user-configurer/OWNERS
  components/dex-static-user-configurer/README.md
  components/dex-static-user-configurer/scripts/config_replace.sh
  milv.config.yaml
  resources/ory/values.yaml
  tests/integration/dex/.gitignore
  tests/integration/dex/Dockerfile
  tests/integration/dex/Makefile
  tests/integration/dex/OWNERS
  tests/integration/dex/README.md
  tests/integration/dex/dex/config.go
  tests/integration/dex/dex/dex_test.go
  tests/integration/dex/dex/idtokenprovider.go
  tests/integration/dex/entrypoint.sh
  tests/integration/dex/go.mod
  tests/integration/dex/go.sum
Labels: size/XL, lgtm

#13057 Fix flaky fn ctrl test
  components/function-controller/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/function-controller/internal/controllers/serverless/metrics/function_metrics_test.go
  resources/serverless/values.yaml
Labels: size/S, lgtm

#13090 Busola logs
  docs/02-get-started/05-observability.md
Labels: size/XS, lgtm

#13060 Use the latest Kaniko image
  resources/serverless/values.yaml
Labels: bug, area/serverless, size/XS, lgtm

#13078 Add grego952 to documentation CODEOWNERS in Kyma
  CODEOWNERS
Labels: area/documentation, area/community, size/XS, lgtm

#13096 Adjust auth-proxy memory reservation and limit
  resources/kiali/values.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/tracing/values.yaml
Labels: size/S, lgtm

#13097 Adjust auth-proxy memory reservation and limit
  resources/kiali/values.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/tracing/values.yaml
Labels: size/S, lgtm

#13053 cleanup `xip-patch`
  CODEOWNERS
  components/xip-patch/.dockerignore
  components/xip-patch/Dockerfile
  components/xip-patch/Makefile
  components/xip-patch/OWNERS
  components/xip-patch/README.md
  components/xip-patch/utils.sh
  components/xip-patch/xip-patch.sh
Labels: size/L, lgtm

#13101 fix for ReferenceError: subaccount is not defined in skr-kyma-to-kyma…
  tests/fast-integration/kcp/client.js
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
Labels: size/S, lgtm

#13106 Add additional info about deprovisioning and KEB operation state in fast-integration tests
  tests/fast-integration/kyma-environment-broker/helpers.js
Labels: size/XS, lgtm

#13052 cleanup `apiserver-proxy`
  CODEOWNERS
  components/README.md
  components/apiserver-proxy/.gitignore
  components/apiserver-proxy/Dockerfile
  components/apiserver-proxy/Makefile
  components/apiserver-proxy/OWNERS
  components/apiserver-proxy/README.md
  components/apiserver-proxy/cmd/proxy/main.go
  components/apiserver-proxy/cmd/proxy/main_test.go
  components/apiserver-proxy/cmd/proxy/reload/doc.go
  components/apiserver-proxy/cmd/proxy/reload/reload.go
  components/apiserver-proxy/cmd/proxy/reload/reload_test.go
  components/apiserver-proxy/cmd/proxy/reload/watch.go
  components/apiserver-proxy/cmd/proxy/reload/watch_test.go
  components/apiserver-proxy/go.mod
  components/apiserver-proxy/go.sum
  components/apiserver-proxy/internal/authn/config.go
  components/apiserver-proxy/internal/authn/delegating.go
  components/apiserver-proxy/internal/authn/oidc.go
  components/apiserver-proxy/internal/authz/auth.go
  components/apiserver-proxy/internal/monitoring/monitoring.go
  components/apiserver-proxy/internal/proxy/proxy.go
  components/apiserver-proxy/internal/proxy/proxy_test.go
  components/apiserver-proxy/internal/spdy/spdy.go
  tests/README.md
  tests/integration/apiserver-proxy/.gitignore
  tests/integration/apiserver-proxy/Dockerfile
  tests/integration/apiserver-proxy/Gopkg.lock
  tests/integration/apiserver-proxy/Gopkg.toml
  tests/integration/apiserver-proxy/Makefile
  tests/integration/apiserver-proxy/OWNERS
  tests/integration/apiserver-proxy/README.md
  tests/integration/apiserver-proxy/before-commit.sh
  tests/integration/apiserver-proxy/fetch-token/internal/auth.go
  tests/integration/apiserver-proxy/fetch-token/internal/config.go
  tests/integration/apiserver-proxy/fetch-token/internal/idtokenprovider.go
  tests/integration/apiserver-proxy/fetch-token/main.go
  tests/integration/apiserver-proxy/test.sh
Labels: size/XXL, lgtm

#13094 remove helm commands from telemetry fast integration test
  resources/telemetry/charts/fluent-bit/templates/_pod.tpl
  resources/telemetry/charts/fluent-bit/values.yaml
  tests/fast-integration/telemetry-test/helm.js
  tests/fast-integration/telemetry-test/telemetry-test.js
Labels: size/M, lgtm

#13091 configurable option for fluent-bit tail inotify_watcher setting
  resources/logging/charts/fluent-bit/templates/configmap.yaml
  resources/logging/charts/fluent-bit/values.yaml
Labels: area/logging, size/XS, lgtm

#13109 added config file to keep configs for SKR pre-submit
  tests/fast-integration/eventing-test/prow/config/skr_config.json
Labels: area/eventing, size/XS, lgtm

#13092 updated base images of several components
  resources/kiali/values.yaml
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/telemetry/values.yaml
  resources/tracing/values.yaml
Labels: size/S, lgtm

#13001 Fix endless reconciliation calls - 1.24.8
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/reconciler/subscription-nats/reconciler.go
Labels: bug, area/eventing, size/L, lgtm

#13123 istio-resources component
  CODEOWNERS
  installation/resources/components.yaml
  resources/istio-resources/Chart.yaml
  resources/istio-resources/README.md
  resources/istio-resources/templates/_helpers.tpl
  resources/istio-resources/templates/monitoring/grafana/dashboards/istio-mesh.yaml
  resources/istio-resources/templates/monitoring/grafana/dashboards/istio-performance.yaml
  resources/istio-resources/templates/monitoring/grafana/dashboards/istio-service.yaml
  resources/istio-resources/templates/monitoring/grafana/dashboards/istio-workload.yaml
  resources/istio-resources/templates/monitoring/service-monitor.yaml
  resources/istio-resources/templates/mtls-global-v2.yaml
  resources/istio-resources/values.yaml
Labels: area/service-mesh, area/installation, size/XXL, lgtm

#13131 Bump image eventing-controller to ee0da541
  resources/eventing/charts/controller/values.yaml
Labels: area/eventing, size/XS, lgtm

#13116 Bump service management related images to fix security vulnerabilities
  components/application-broker/cmd/broker/Dockerfile
  components/service-binding-usage-controller/Dockerfile
  resources/cluster-essentials/values.yaml
  resources/helm-broker/values.yaml
  resources/ory/values.yaml
  resources/service-catalog/values.yaml
Labels: size/S, lgtm

#13112 Add hint about event cleanup to Subscription doc
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
  docs/05-technical-reference/evnt-01-event-names.md
Labels: area/documentation, size/S, lgtm

#13074 Bump golang images
  components/busola-migrator/Dockerfile
  components/compass-runtime-agent/Dockerfile
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  resources/busola-migrator/values.yaml
  resources/serverless/values.yaml
  tests/function-controller/Dockerfile
  tests/rafter/Dockerfile
  tests/rafter/go.mod
  tests/rafter/go.sum
Labels: size/M, lgtm

#12966 add doc on functions asynchronous connection
  docs/03-tutorials/00-serverless/svls-02-create-git-function.md
  docs/03-tutorials/00-serverless/svls-03-expose-function.md
  docs/03-tutorials/00-serverless/svls-10-bind-a-serviceinstance-to-a-function.md
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
Labels: size/L, lgtm

#13139 eventing-controller image bump
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#12895 Linting fast-integration
  tests/fast-integration/.eslintrc.json
  tests/fast-integration/Makefile
  tests/fast-integration/audit-log/client.js
  tests/fast-integration/audit-log/helpers.js
  tests/fast-integration/audit-log/index.js
  tests/fast-integration/certificate-test/certificte-test.js
  tests/fast-integration/compass-test/compass-test.js
  tests/fast-integration/compass/client.js
  tests/fast-integration/compass/fixtures.js
  tests/fast-integration/compass/gql.js
  tests/fast-integration/compass/helpers.js
  tests/fast-integration/compass/index.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/metric-test.js
  tests/fast-integration/eventing-test/provision/deprovision-skr.js
  tests/fast-integration/eventing-test/provision/provision-skr.js
  tests/fast-integration/gardener/client.js
  tests/fast-integration/gardener/index.js
  tests/fast-integration/kcp/client.js
  tests/fast-integration/kyma-environment-broker/client.js
  tests/fast-integration/kyma-environment-broker/helpers.js
  tests/fast-integration/kyma-environment-broker/index.js
  tests/fast-integration/lib/oauth.js
  tests/fast-integration/logging/client.js
  tests/fast-integration/logging/helpers.js
  tests/fast-integration/logging/index.js
  tests/fast-integration/monitoring/client.js
  tests/fast-integration/monitoring/grafana.js
  tests/fast-integration/monitoring/prometheus.js
  tests/fast-integration/package-lock.json
  tests/fast-integration/package.json
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
  tests/fast-integration/skr-nightly/provision/provision-skr-nightly.js
  tests/fast-integration/skr-nightly/test/test-nightly.js
  tests/fast-integration/skr-svcat-migration-test/deploy-sample-resources.js
  tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
  tests/fast-integration/skr-test/helpers.js
  tests/fast-integration/skr-test/index.js
  tests/fast-integration/skr-test/skr-test.js
  tests/fast-integration/skr-test/test.js
  tests/fast-integration/telemetry-test/telemetry-test.js
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/test/2-getting-started-guide.js
  tests/fast-integration/test/3-monitoring.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/getting-started-guide/index.js
  tests/fast-integration/test/index.js
  tests/fast-integration/test/test.js
  tests/fast-integration/upgrade-test/fixtures/helm-broker/index.js
  tests/fast-integration/upgrade-test/upgrade-test-cleanup.js
  tests/fast-integration/upgrade-test/upgrade-test-prep.js
  tests/fast-integration/upgrade-test/upgrade-test-tests.js
  tests/fast-integration/utils/index.js
  tests/fast-integration/utils/index.test.js
Labels: area/quality, size/XXL, lgtm

#13134 Bump service management related images to fix security vulnerabilities (release-2.0)
  components/application-broker/cmd/broker/Dockerfile
  components/service-binding-usage-controller/Dockerfile
  resources/cluster-essentials/values.yaml
  resources/helm-broker/values.yaml
  resources/ory/values.yaml
  resources/service-catalog/values.yaml
Labels: size/S, lgtm

#12867 Dockerfile lint 1
  components/application-broker/cmd/broker/Dockerfile
  components/application-connectivity-certs-setup-job/Dockerfile
  components/application-connectivity-validator/Dockerfile
  components/application-gateway/Dockerfile
  components/application-operator/Dockerfile
  components/application-registry/Dockerfile
  tests/application-connector-tests/Dockerfile
  tests/application-gateway-legacy-tests/test/executor/Dockerfile
  tests/application-gateway-legacy-tests/test/helmtest/Dockerfile
  tests/application-gateway-tests/Dockerfile
  tests/application-operator-tests/Dockerfile
  tests/application-registry-tests/Dockerfile
  tests/compass-runtime-agent/Dockerfile
Labels: size/M, lgtm

#13145 Bump API Gateway controller version to include Golang bump
  resources/api-gateway/values.yaml
Labels: area/api-gateway, size/XS, lgtm

#13147 Bump API-Gateway controller version to include Golang bump
  resources/api-gateway/values.yaml
Labels: area/api-gateway, size/XS, lgtm

#13148 Bump application-connector, sbu-controller images
  resources/application-connector/values.yaml
  resources/service-catalog-addons/values.yaml
Labels: size/XS, lgtm

#13149 Bump application-connector, sbu-controller images (release-2.0)
  resources/application-connector/values.yaml
  resources/service-catalog-addons/values.yaml
Labels: size/XS, lgtm

#13100 Document troubleshooting for failng kaniko detection
  docs/04-operation-guides/troubleshooting/svls-04-function-build-failing-on-k3d.md
Labels: size/M, lgtm

#13162 update to grafana 7.5.13
  resources/monitoring/values.yaml
Labels: area/monitoring, size/XS, lgtm

#13160 Bump serverless registry image
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#13165 Bump oauth2 proxy
  resources/kiali/values.yaml
  resources/monitoring/values.yaml
  resources/tracing/values.yaml
Labels: area/monitoring, area/tracing, size/XS, lgtm

#13170 Add a workspace prefix to the AC dockerfiles
  components/application-connectivity-certs-setup-job/Dockerfile
  components/application-connectivity-validator/Dockerfile
  components/application-gateway/Dockerfile
  components/application-operator/Dockerfile
  components/application-operator/charts/application/templates/deployment.yaml
  components/application-operator/charts/gateway/templates/deployment.yaml
  components/application-registry/Dockerfile
  resources/application-connector/charts/application-operator/templates/controller.yaml
  resources/application-connector/charts/application-registry/templates/deployment.yaml
  resources/application-connector/templates/certs-setup-job.yaml
  resources/application-connector/values.yaml
Labels: bug, area/application-connector, size/M, lgtm

#13167 ignore app deletion error
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: size/XS, lgtm

#13156 removed duplicate unregisterKymaFromCompass cleanup step from skr-kyma-to-kyma2-upgrade script
  tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
Labels: size/XS, lgtm

#13172 use local envtest binaries
  components/eventing-controller/Makefile
Labels: area/eventing, size/S, lgtm

#12905 Split up the fast integration tests into pre, tests and cleanup scripts
  tests/fast-integration/Makefile
  tests/fast-integration/eventing-test/README.md
  tests/fast-integration/eventing-test/eventing-test-cleanup.js
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
  tests/fast-integration/package.json
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#13183 Bump version to 2.0.4
  VERSION
Labels: size/XS, lgtm

#13070 Fix endless reconciliation calls
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/pkg/handlers/eventtype/clean.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/values.yaml
Labels: bug, area/eventing, size/L, lgtm

#13185 Bump golang to golang:1.17.6-alpine3.15
  components/busola-migrator/Dockerfile
  components/compass-runtime-agent/Dockerfile
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  tests/function-controller/Dockerfile
  tests/rafter/Dockerfile
  tests/rafter/go.mod
  tests/rafter/go.sum
Labels: size/M, lgtm

#13187 remove dbadura from compass rtm agent
  CODEOWNERS
Labels: size/XS, lgtm

#13065 Fix Helm Broker port names in services to comply with Istio convention
  resources/helm-broker/charts/etcd-stateful/templates/02-service.yaml
  resources/helm-broker/charts/etcd-stateful/templates/04-servicemonitor.yaml
Labels: area/service-catalog, size/S, lgtm

#13186 Bump components images
  resources/busola-migrator/values.yaml
  resources/compass-runtime-agent/values.yaml
  resources/serverless/values.yaml
Labels: size/S, lgtm

#13175 Fix Tracing port names in services to comply with Istio convention
  resources/tracing/templates/kyma-additions/metrics-service.yaml
  resources/tracing/templates/kyma-additions/metrics-servicemonitor.yaml
  resources/tracing/templates/kyma-additions/zipkin-service.yaml
  resources/tracing/templates/service.yaml
Labels: area/tracing, size/S, lgtm

#13062 Fix API Gateway metrics service port name to comply with Istio convention
  resources/api-gateway/templates/monitoring.yaml
Labels: area/api-gateway, size/XS, lgtm

#13124 improve Kiali exposure instructions
  docs/04-operation-guides/security/sec-06-access-expose-kiali-grafana.md
Labels: area/documentation, area/monitoring, size/S, lgtm

#12963 Dockerfile lint 2
  components/application-operator/charts/application/templates/validator.yaml
  components/busola-migrator/Dockerfile
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
  components/compass-runtime-agent/hack/Dockerfile
  components/connection-token-handler/Dockerfile
  components/connector-service/Dockerfile
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/python38/Dockerfile
  components/function-runtimes/python39/Dockerfile
  resources/application-connector/charts/central-application-connectivity-validator/templates/deployment.yaml
  resources/application-connector/charts/central-application-gateway/templates/deployment.yaml
  resources/application-connector/charts/connector-service/templates/deployment.yaml
  resources/application-connector/values.yaml
  resources/busola-migrator/values.yaml
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/values.yaml
  resources/serverless/values.yaml
  tests/connection-token-handler-tests/Dockerfile
  tests/connector-service-tests/Dockerfile
  tests/function-controller/Dockerfile
Labels: size/L, lgtm

#13174 Fix cleanup of BTP resources in fast-integration tests
  tests/fast-integration/skr-svcat-migration-test/deploy-sample-resources.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
  tests/fast-integration/utils/index.js
Labels: size/M, lgtm

#13189 Clean up NATS handler unit tests
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/pkg/handlers/test_helpers.go
  components/eventing-controller/pkg/subscriptionmanager/nats/nats_test.go
  components/eventing-controller/testing/subscriber.go
  resources/eventing/values.yaml
Labels: area/eventing, size/XL, lgtm

#13199 Correct steps for the Bind a Service Instance to a Function page
  docs/03-tutorials/00-serverless/svls-10-bind-a-serviceinstance-to-a-function.md
Labels: size/M, lgtm

#13126 Improve nats reconciler when subscription filters are modified
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#13210 update to fluent-bit 1.8.12
  resources/logging/values.yaml
  resources/telemetry/values.yaml
Labels: area/logging, size/XS, lgtm

#13208 Remove flaky testDispatcherWithMultipleSubscribers
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
Labels: area/eventing, size/L, lgtm

#13180 Deprecate nodejs12
  docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
  docs/03-tutorials/00-serverless/svls-02-create-git-function.md
  docs/03-tutorials/00-serverless/svls-09-log-into-private-packages-registry.md
  docs/04-operation-guides/troubleshooting/svls-02-failing-function-container.md
  docs/04-operation-guides/troubleshooting/svls-03-function-debugger-in-strange-location.md
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  docs/05-technical-reference/svls-01-sample-functions.md
  docs/05-technical-reference/svls-02-function-processing-stages.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
  docs/05-technical-reference/svls-08-function-specification.md
Labels: size/M, lgtm

#13205 Subscriptions reconciliation should be requeued if subscription cannot be marked as ready
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  resources/eventing/values.yaml
Labels: area/eventing, size/S, lgtm

#13192 Bump k8s-tools image on release-2.0 branch
  components/dex-static-user-configurer/Dockerfile
  components/xip-patch/Dockerfile
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/busola-migrator/values.yaml
  resources/cluster-essentials/values.yaml
  resources/ory/values.yaml
  resources/rafter/values.yaml
  resources/serverless/values.yaml
  resources/service-catalog/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/templates/job.yaml
  tests/integration/api-gateway/Dockerfile
  tests/integration/apiserver-proxy/Dockerfile
  tests/integration/dex/Dockerfile
Labels: size/M, lgtm

#13191 Bump k8s-tools image on release-1.24 branch
  components/dex-static-user-configurer/Dockerfile
  components/istio-installer/Dockerfile
  components/istio-installer/README.md
  components/xip-patch/Dockerfile
  docs/kyma/03-03-charts.md
  docs/kyma/08-04-create-volume-snapshots.md
  docs/kyma/10-08-cant-download-img.md
  resources/api-gateway/values.yaml
  resources/apiserver-proxy/templates/job.yaml
  resources/application-connector/charts/application-broker/templates/subscription-migration.yaml
  resources/application-connector/charts/connector-service/values.yaml
  resources/application-connector/values.yaml
  resources/busola-migrator/values.yaml
  resources/certificates/values.yaml
  resources/cluster-essentials/templates/migrate-ac-certs-job.yaml
  resources/cluster-essentials/values.yaml
  resources/cluster-users/values.yaml
  resources/dex/templates/upgrade-job.yaml
  resources/eventing/values.yaml
  resources/helm-broker/templates/clear-cr-job.yaml
  resources/istio/templates/istio-proxy-reset.yaml
  resources/istio/values.yaml
  resources/kiali/values.yaml
  resources/ory/charts/hydra/charts/hydra-maester/values.yaml
  resources/ory/values.yaml
  resources/rafter/charts/upload-service/values.yaml
  resources/rafter/templates/pre-upgrade-delete-vs-job.yaml
  resources/rafter/values.yaml
  resources/serverless/values.yaml
  resources/service-catalog-addons/charts/service-binding-usage-controller/templates/clear-cr-job.yaml
  resources/service-catalog/charts/catalog/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/templates/job.yaml
  tests/integration/api-gateway/Dockerfile
  tests/integration/apiserver-proxy/Dockerfile
  tests/integration/dex/Dockerfile
Labels: size/M, lgtm

#13193 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/busola-migrator/values.yaml
  resources/cluster-essentials/values.yaml
  resources/ory/values.yaml
  resources/rafter/values.yaml
  resources/serverless/values.yaml
  resources/service-catalog/values.yaml
  tests/integration/api-gateway/Dockerfile
Labels: size/S, lgtm

#13221 Prometheus client golang bump to 1.12.1 in connector-service
  components/connector-service/go.mod
  components/connector-service/go.sum
  components/connector-service/internal/monitoring/collector/countercollector_test.go
  components/connector-service/internal/monitoring/collector/summarycollector_test.go
  resources/application-connector/values.yaml
Labels: size/L, lgtm

#13220 Bump k8s-tools dependent images on release-1.24 branch
  resources/api-gateway/values.yaml
  resources/apiserver-proxy/values.yaml
  resources/core/values.yaml
  resources/dex/values.yaml
  resources/istio/values.yaml
  resources/xip-patch/values.yaml
  tests/fast-integration/installer/charts/ingress-dns-cert/values.yaml
Labels: size/S, lgtm

#13188 Bring back missing tracing and monitoring tests
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: area/eventing, size/M, lgtm
