Repository kyma-project/kyma, pull requests merged in 2022-09, with the labels that each got.

#15301 bump k8s api and client go
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/L, lgtm

#15336 [Telemetry Operator] Restructure main function
  components/telemetry-operator/controller/logparser/controller.go
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/suite_test.go
  components/telemetry-operator/controller/metrics/metrics.go
  components/telemetry-operator/main.go
  resources/telemetry/values.yaml
Labels: area/logging, size/L, lgtm

#15305 Keda prometheus scaler tutorial
  docs/03-tutorials/00-serverless/svls-15-use-external-scalers.md
Labels: size/M, lgtm

#15148 changed dockerfile naming convention
  components/function-controller/README.md
  components/function-controller/config/dockerfiles.yaml
  components/function-controller/internal/controllers/serverless/runtime/runtime.go
  components/function-controller/internal/controllers/serverless/runtime/runtime_test.go
  resources/serverless/templates/runtimes.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#15105 Integrate directory size exporter into the telemetry fluent-bit chart
  resources/telemetry/charts/fluent-bit/dashboards/fluent-bit.json
  resources/telemetry/charts/fluent-bit/templates/_pod.tpl
  resources/telemetry/charts/fluent-bit/templates/servicemonitor.yaml
  resources/telemetry/charts/fluent-bit/values.yaml
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15355 Adjust telemetry-operator memory limit
  resources/telemetry/charts/operator/values.yaml
Labels: size/XS, lgtm

#15317 Add Busola extensions for telemetry CRDs
  resources/telemetry/charts/operator/templates/logparser_busola_extension_cm.yaml
  resources/telemetry/charts/operator/templates/logpipeline_busola_extension_cm.yaml
  resources/telemetry/charts/operator/values.yaml
Labels: size/XL, lgtm

#15354 Fix typo in 2.5 to 2.6 migration script
  docs/assets/2.5-2.6-cleanup-logging-fluent-bit.sh
Labels: size/XS, lgtm

#15358 Fix typo in 2.5 to 2.6 migration script (#15354)
  docs/assets/2.5-2.6-cleanup-logging-fluent-bit.sh
Labels: size/XS, lgtm

#15369 Add an external link to be ignored - JWT tutorial
  milv.config.yaml
Labels: size/XS, lgtm

#15366 Remove replicas from autoscaled deployments in Application Connector
  resources/application-connector/charts/central-application-connectivity-validator/templates/deployment.yaml
  resources/application-connector/charts/central-application-gateway/templates/deployment.yaml
Labels: size/XS, lgtm

#15367 Remove replicas from autoscaled deployments in Application Connector
  resources/application-connector/charts/central-application-connectivity-validator/templates/deployment.yaml
  resources/application-connector/charts/central-application-connectivity-validator/values.yaml
  resources/application-connector/charts/central-application-gateway/templates/deployment.yaml
  resources/application-connector/charts/central-application-gateway/values.yaml
Labels: area/application-connector, size/S, lgtm

#15370 bump version to 2.6.2
  VERSION
Labels: size/XS, lgtm

#14912 Components test of central-application-validator component
  tests/components/application-connector/Dockerfile.connectivity-validator
  tests/components/application-connector/Makefile
  tests/components/application-connector/README.md
  tests/components/application-connector/docs/application-connectivity-validator-tests.md
  tests/components/application-connector/docs/application-gateway-tests.md
  tests/components/application-connector/docs/assets/api-auth-methods-mtls.png
  tests/components/application-connector/docs/assets/api-auth-methods.png
  tests/components/application-connector/docs/assets/api-tokens-mtls.png
  tests/components/application-connector/docs/assets/api-tokens.png
  tests/components/application-connector/docs/assets/app-gateway-tests-architecture.svg
  tests/components/application-connector/docs/assets/connectivity-validator-tests-architecture.svg
  tests/components/application-connector/docs/assets/mock-app-mtls-spec.yaml
  tests/components/application-connector/docs/assets/mock-app-spec.yaml
  tests/components/application-connector/internal/testkit/httpd/http.go
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/Chart.yaml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/charts/echoserver/Chart.yaml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/charts/echoserver/templates/echoserver.yml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/charts/test/Chart.yaml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/charts/test/templates/_helpers.tpl
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/charts/test/templates/applications/event-test-compass.yml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/charts/test/templates/applications/event-test-standalone.yml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/charts/test/templates/test.yml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/patches/central-application-connectivity-validator.json
  tests/components/application-connector/test/application-connectivity-validator/suite_test.go
  tests/components/application-connector/test/application-connectivity-validator/tools.go
  tests/components/application-connector/test/application-gateway/complex_test.go
  tests/components/application-connector/test/application-gateway/runner_test.go
  tests/components/application-connector/test/application-gateway/tools.go
Labels: area/documentation, area/application-connector, size/XXL, lgtm, area/tests

#15274 add a system-account user to nats-server
  resources/eventing/charts/nats/templates/configmap.yaml
  resources/eventing/charts/nats/templates/secret.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
Labels: area/eventing, size/M, lgtm

#15359 bump dependency `sigs.k8s.io/controller-runtime` to `v0.13.0`
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/L, lgtm

#15361 bump dependencies in `event-publisher-proxy`
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  resources/eventing/values.yaml
Labels: size/L, lgtm

#15365 Added structure for Compass Runtime Agent test
  tests/components/application-connector/go.mod
  tests/components/application-connector/go.sum
  tests/components/application-connector/test/compass-runtime-agent/suite_test.go
  tests/components/application-connector/test/compass-runtime-agent/synchronisation_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/comparator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/directorclient.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/executor/toolkit.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/executor/toolkit_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/random/randomstring.go
Labels: size/L, lgtm

#15375 [Telemetry operator] Add telemetry_all_logpipelines gauge
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/controller_test.go
  components/telemetry-operator/controller/logpipeline/sync.go
  components/telemetry-operator/controller/logpipeline/sync_test.go
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/values.yaml
Labels: area/logging, size/L, lgtm

#15335 Improve eventing log
  components/event-publisher-proxy/cmd/event-publisher-proxy/beb/beb.go
  components/event-publisher-proxy/cmd/event-publisher-proxy/nats/nats.go
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/event-publisher-proxy/pkg/cloudevents/eventtype/clean.go
  components/event-publisher-proxy/pkg/handler/beb/mock/mock.go
  components/event-publisher-proxy/pkg/legacy-events/error_responses.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/pkg/handlers/jetstream.go
  components/eventing-controller/pkg/handlers/sink/validator.go
  components/eventing-controller/pkg/handlers/sink/validator_test.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go
  components/eventing-controller/testing/matchers.go
Labels: size/L, lgtm

#15387 Disable health-check on fb pod and enable metrics
  resources/telemetry/charts/fluent-bit/values.yaml
Labels: size/XS, lgtm

#15391 Fixed message formatting in crd-serverless
  components/function-controller/config/crd/crd-serverless.yaml
Labels: size/L, lgtm

#15396 [Telemetry Operator] Simplify metric scrape whitelist
  resources/telemetry/charts/operator/values.yaml
Labels: area/logging, size/XS, lgtm

#15383 introduce golangci-lint config and new make target from `https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322`
  components/eventing-controller/.golangci.yaml
  components/eventing-controller/Makefile
Labels: area/eventing, size/L, lgtm

#15398 Change timeout value to15 for all serverless webhooks
  components/function-controller/internal/webhook/resources/webhook_config.go
  resources/serverless/charts/webhook/templates/webhooks.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/S, lgtm

#15379 Compass runtime agent component test
  tests/components/application-connector/go.mod
  tests/components/application-connector/go.sum
  tests/components/application-connector/test/compass-runtime-agent/suite_test.go
  tests/components/application-connector/test/compass-runtime-agent/synchronisation_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/comparator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/comparator_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/mocks/ApplicationGetter.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/mocks/Comparator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/secretcomparator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/secretcomparator_test.go
Labels: size/XL, lgtm

#15382 externalized metric and storage for directory-size-exporter
  components/directory-size-exporter/internal/exporter/exporter.go
  components/directory-size-exporter/internal/exporter/exporter_test.go
  components/directory-size-exporter/main.go
  resources/telemetry/charts/fluent-bit/dashboards/fluent-bit.json
  resources/telemetry/charts/fluent-bit/values.yaml
  resources/telemetry/values.yaml
  tests/fast-integration/monitoring/prometheus.js
Labels: area/logging, size/L, lgtm

#15399 fix timeout for webhooks
  resources/telemetry/charts/operator/templates/validation_webhook.yaml
  resources/telemetry/charts/operator/values.yaml
Labels: size/XS, lgtm

#15400 Fix for cleanup in makefiles for application-connector component tests
  tests/components/application-connector/Makefile.test-application-conn-validator
  tests/components/application-connector/Makefile.test-application-gateway
Labels: size/S, lgtm

#15329 Function Subresources Templating for Serverless v1alpha2
  components/function-controller/design/subresources_templates_proposal.md
Labels: size/M, lgtm

#15405 Cherry-pick the log in EPP which exposes the event to Release 2.6
  components/event-publisher-proxy/pkg/sender/jetstream.go
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#15331 split handlers into their own packages
  components/eventing-controller/Makefile
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/controllers/backend/owner_ref_k8s.go
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/pkg/backend/beb/beb.go
  components/eventing-controller/pkg/backend/beb/beb_test.go
  components/eventing-controller/pkg/backend/eventtype/build.go
  components/eventing-controller/pkg/backend/eventtype/build_test.go
  components/eventing-controller/pkg/backend/eventtype/clean.go
  components/eventing-controller/pkg/backend/eventtype/clean_test.go
  components/eventing-controller/pkg/backend/eventtype/parse.go
  components/eventing-controller/pkg/backend/eventtype/parse_test.go
  components/eventing-controller/pkg/backend/metrics/collector.go
  components/eventing-controller/pkg/backend/mocks/BEBBackend.go
  components/eventing-controller/pkg/backend/mocks/JetStreamBackend.go
  components/eventing-controller/pkg/backend/mocks/NatsBackend.go
  components/eventing-controller/pkg/backend/nats/core/core.go
  components/eventing-controller/pkg/backend/nats/core/core_test.go
  components/eventing-controller/pkg/backend/nats/core/test_helpers.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_util.go
  components/eventing-controller/pkg/backend/nats/jetstream/test_helpers.go
  components/eventing-controller/pkg/backend/nats/nats.go
  components/eventing-controller/pkg/backend/nats/testing/test_helpers.go
  components/eventing-controller/pkg/backend/nats/utils.go
  components/eventing-controller/pkg/backend/sink/validator.go
  components/eventing-controller/pkg/backend/sink/validator_test.go
  components/eventing-controller/pkg/backend/utils/utils.go
  components/eventing-controller/pkg/backend/utils/utils_test.go
  components/eventing-controller/pkg/ems/httpclient/client.go
  components/eventing-controller/pkg/handlers/test_helpers.go
  components/eventing-controller/pkg/object/equality_test.go
  components/eventing-controller/pkg/signals/signals.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb_test.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream_test.go
  components/eventing-controller/pkg/subscriptionmanager/nats/nats.go
  components/eventing-controller/pkg/subscriptionmanager/nats/nats_test.go
  components/eventing-controller/testing/nats/matchers.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/values.yaml
Labels: area/eventing, size/XXL, lgtm

#15417 Increase auth proxy upstream timeout
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/kiali/values.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/values.yaml
Labels: area/monitoring, area/tracing, lgtm

#15406 Clone the fast-integration-tests version which is compatible with the given Kyma version
  tests/fast-integration/image/Dockerfile
  tests/fast-integration/image/clone-and-run-fit.sh
Labels: size/S, lgtm

#15411 [Telemetry Operator] Enable reconciliation error metric
  resources/telemetry/charts/operator/values.yaml
Labels: area/logging, size/XS, lgtm

#15419 Clone the fast-integration-tests version which is compatible with the given Kyma version
  tests/fast-integration/image/Dockerfile
  tests/fast-integration/image/clone-and-run-fit.sh
Labels: size/S, lgtm

#15423 Remove compass from skr-nightly-test
  tests/fast-integration/skr-nightly/provision/provision-skr-nightly.js
Labels: size/XS, lgtm

#15424 add install kyma links
  docs/03-tutorials/00-serverless/svls-04-manage-functions-with-kyma-cli.md
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
  docs/03-tutorials/00-serverless/svls-12-customize-function-traces.md
  docs/03-tutorials/00-serverless/svls-13-override-runtime-image.md
  docs/03-tutorials/00-serverless/svls-14-inject-envs.md
  docs/03-tutorials/00-serverless/svls-15-use-external-scalers.md
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  docs/05-technical-reference/00-custom-resources/svls-02-gitrepository.md
Labels: size/S, lgtm

#15395 Bump to kube-prom-stack 39.11.0 and prometheus to 2.38
  resources/monitoring/templates/grafana/dashboards-1.14/etcd.yaml
  resources/monitoring/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
  resources/monitoring/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
  resources/monitoring/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
  resources/monitoring/templates/prometheus/rules-1.14/node-exporter.yaml
  resources/monitoring/values.yaml
Labels: size/M, lgtm

#15397 Follow godot linter recommendations
  components/eventing-controller/api/v1alpha1/condition.go
  components/eventing-controller/api/v1alpha1/eventingbackend_types.go
  components/eventing-controller/api/v1alpha1/groupversion_info.go
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_eventingbackends.yaml
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/controllers/backend/owner_ref_k8s.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_test.go
  components/eventing-controller/controllers/errors/skip.go
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/testing/test_utils.go
  components/eventing-controller/options/options.go
  components/eventing-controller/pkg/backend/beb/beb.go
  components/eventing-controller/pkg/backend/beb/beb_test.go
  components/eventing-controller/pkg/backend/eventtype/clean.go
  components/eventing-controller/pkg/backend/metrics/collector.go
  components/eventing-controller/pkg/backend/nats/core/core.go
  components/eventing-controller/pkg/backend/nats/core/core_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_test.go
  components/eventing-controller/pkg/backend/sink/validator.go
  components/eventing-controller/pkg/backend/utils/utils.go
  components/eventing-controller/pkg/deployment/publisher_deployment_test.go
  components/eventing-controller/pkg/ems/api/events/client/client.go
  components/eventing-controller/pkg/ems/auth/auth_test.go
  components/eventing-controller/pkg/ems/httpclient/client.go
  components/eventing-controller/pkg/ems/httpclient/error.go
  components/eventing-controller/pkg/informers/sync.go
  components/eventing-controller/pkg/object/apirule.go
  components/eventing-controller/testing/bebmock.go
  components/eventing-controller/testing/nats.go
  components/eventing-controller/testing/test_helpers.go
Labels: size/L, lgtm

#15432 Update image values for application gateway tests to newest versions
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: size/XS, lgtm

#15435 Mention sidecar injection labels in Kyma docs
  docs/04-operation-guides/operations/smsh-01-istio-enable-sidecar-injection.md
Labels: area/documentation, size/XS, lgtm

#15420 Enable monitoring tests for Eventing on skr
  tests/fast-integration/eventing-test/metric-test.js
Labels: size/XS, lgtm

#15438 Enable monitoring tests for Eventing on SKR
  tests/fast-integration/eventing-test/metric-test.js
Labels: size/XS, lgtm

#15308 Rename metrics according to Prometheus guidelines
  components/event-publisher-proxy/pkg/metrics/collector.go
  components/event-publisher-proxy/pkg/metrics/metricstest/metricstest.go
  components/eventing-controller/pkg/backend/metrics/collector.go
  docs/04-operation-guides/operations/evnt-02-eventing-metrics.md
  resources/eventing/charts/dashboards/templates/delivery.yaml
  resources/eventing/charts/dashboards/templates/latency.yaml
  resources/eventing/values.yaml
  tests/fast-integration/eventing-test/metric-test.js
  tests/fast-integration/eventing-test/nats-dashboard-queries.json
Labels: area/eventing, size/L, lgtm

#15415 improved telemetry documentation
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
  installation/resources/crds/telemetry/logpipelines.crd.yaml
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15433 fix stylecheck lint issues
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  components/eventing-controller/pkg/backend/utils/utils_test.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#15454 Bump GOLANG to 1.19 for eventing
  components/event-publisher-proxy/cmd/event-publisher-proxy/Dockerfile
  components/event-publisher-proxy/go.mod
  components/eventing-controller/Dockerfile
  components/eventing-controller/go.mod
  resources/eventing/values.yaml
Labels: size/S, lgtm

#15441 introduce Subscriber interface for nats
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/pkg/backend/nats/core/core.go
  components/eventing-controller/pkg/backend/nats/core/core_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_types.go
  components/eventing-controller/pkg/backend/nats/jetstream/test_helpers.go
  components/eventing-controller/pkg/backend/nats/nats.go
  components/eventing-controller/pkg/backend/nats/utils.go
  components/eventing-controller/pkg/deployment/publisher_deployment.go
  components/eventing-controller/pkg/env/nats_config.go
  components/eventing-controller/testing/nats/matchers.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#15466 Read gardener namespace from ENV in FI tests
  tests/fast-integration/gardener/client.js
Labels: size/XS, lgtm

#15468 Read gardener namespace from ENV in FI tests (release-2.6)
  tests/fast-integration/gardener/client.js
Labels: size/XS, lgtm

#15455 Add anoipm as codeowner
  CODEOWNERS
Labels: size/S, lgtm

#15449 Bump postgres to 1.17-alpine3.16
  resources/ory/values.yaml
Labels: size/XS, lgtm

#15467 Use v1beta1 api version of apigateway for eventing
  components/eventing-controller/config/crd/external/apirules-gateway-kyma-project-io.yaml
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  components/eventing-controller/pkg/backend/beb/beb.go
  components/eventing-controller/pkg/backend/mocks/BEBBackend.go
  components/eventing-controller/pkg/backend/utils/utils.go
  components/eventing-controller/pkg/object/apirule.go
  components/eventing-controller/pkg/object/equality.go
  components/eventing-controller/pkg/object/equality_test.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb.go
  components/eventing-controller/testing/matchers.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#15474 Connectivity Validator - change client_golang to 1.11.1 due to CVE in 1.11.0
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
Labels: area/application-connector, size/XS, lgtm

#15450 Update GO Version in Function Controller
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/go.mod
  components/function-controller/go.sum
  resources/serverless/values.yaml
Labels: area/security, size/M, lgtm

#15389 Refactor function status update logic
  components/function-controller/cmd/manager/main.go
  components/function-controller/go.mod
  components/function-controller/internal/controllers/serverless/configmap.go
  components/function-controller/internal/controllers/serverless/deployment.go
  components/function-controller/internal/controllers/serverless/fsm.go
  components/function-controller/internal/controllers/serverless/fsm_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/job.go
  components/function-controller/internal/controllers/serverless/scaling.go
  components/function-controller/internal/controllers/serverless/service.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#15475 remove defaulting of runtime in v1alpha2
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  resources/serverless/values.yaml
Labels: size/M, lgtm

#15487 Remove compass-system namespace by default in LogPipelines
  components/telemetry-operator/internal/fluentbit/config/builder/config_builder_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/rewritetag_filter.go
  components/telemetry-operator/internal/fluentbit/config/builder/rewritetag_filter_test.go
  components/telemetry-operator/webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#15482 update checking internal subscriptions count
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#15493 Increase Loki resource limits for production profile
  resources/logging/profile-production.yaml
Labels: area/logging, size/XS, lgtm

#15486 refactor of defaulting tests
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#15496 Bump Istio charts to Istio 1.14.4
  resources/istio-resources/files/dashboards/control-plane.json
  resources/istio-resources/files/dashboards/mesh.json
  resources/istio-resources/files/dashboards/performance.json
  resources/istio-resources/files/dashboards/service.json
  resources/istio-resources/files/dashboards/workload.json
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: size/S, lgtm

#15307 Cleanup function_types.go
  components/function-controller/internal/controllers/serverless/build_resources.go
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  components/function-controller/internal/controllers/serverless/fixtures_test.go
  components/function-controller/internal/controllers/serverless/fsm.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  components/function-controller/internal/webhook/defaulting_webhook_test.go
  components/function-controller/internal/webhook/fixtures_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/zz_generated.deepcopy.go
  resources/serverless/values.yaml
Labels: area/serverless, size/L, lgtm, kind/cleanup

#15495 Update CPU requests for Ory Hydra and Oathkeeper in production profile
  resources/ory/profile-production.yaml
Labels: size/XS, lgtm

#15498 fix doc for function presets
  docs/05-technical-reference/svls-09-available-presets.md
Labels: size/XS, lgtm

#15491 add function resource profile to conversion from function v1alpha1 to…
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#15500 consistent naming in epp
  components/event-publisher-proxy/cmd/event-publisher-proxy/beb/beb.go
  components/event-publisher-proxy/cmd/event-publisher-proxy/main.go
  components/event-publisher-proxy/cmd/event-publisher-proxy/nats/nats.go
  components/event-publisher-proxy/pkg/env/beb_config.go
  components/event-publisher-proxy/pkg/env/beb_config_test.go
  components/event-publisher-proxy/pkg/env/nats_config.go
  components/event-publisher-proxy/pkg/handler/beb/handler.go
  components/event-publisher-proxy/pkg/handler/beb/mock/mock.go
  components/event-publisher-proxy/pkg/handler/nats/handler_health_test.go
  components/event-publisher-proxy/pkg/handler/nats/handler_integration_test.go
  components/event-publisher-proxy/pkg/handler/nats/health_test.go
  components/event-publisher-proxy/pkg/handler/nats/mock/mock.go
  components/event-publisher-proxy/pkg/legacy-events/legacy_test.go
  components/event-publisher-proxy/pkg/nats/connect_test.go
  components/event-publisher-proxy/pkg/oauth/client.go
  components/event-publisher-proxy/pkg/oauth/client_test.go
  components/event-publisher-proxy/pkg/oauth/config.go
  components/event-publisher-proxy/pkg/oauth/config_test.go
  components/event-publisher-proxy/pkg/sender/beb.go
  components/event-publisher-proxy/pkg/sender/beb_test.go
  components/event-publisher-proxy/pkg/sender/jetstream.go
  components/event-publisher-proxy/pkg/sender/jetstream_test.go
  components/event-publisher-proxy/pkg/sender/nats.go
  components/event-publisher-proxy/pkg/sender/nats_test.go
  components/event-publisher-proxy/pkg/subscribed/processor.go
  components/event-publisher-proxy/testing/env_config.go
  components/event-publisher-proxy/testing/nats.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#15494 [Telemetry Operator] Add grep filter for namespace filtering in input
  components/telemetry-operator/internal/fluentbit/config/builder/config_builder.go
  components/telemetry-operator/internal/fluentbit/config/builder/config_builder_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/namespace_filter.go
  components/telemetry-operator/internal/fluentbit/config/builder/namespace_filter_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/rewritetag_filter.go
  components/telemetry-operator/internal/fluentbit/config/builder/rewritetag_filter_test.go
  components/telemetry-operator/webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
  resources/telemetry/values.yaml
  tests/fast-integration/logging/client.js
  tests/fast-integration/telemetry-test/resources/deployments/logs-workload.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/loki-exclude-istio-proxy-logpipeline.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/loki-metadata-filter-drop-labels-logpipeline.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/loki-metadata-filter-keep-labels-logpipeline.yaml
  tests/fast-integration/telemetry-test/telemetry-test.js
Labels: size/L, lgtm

#15508 Small notice that downgrades are not supported
  docs/04-operation-guides/operations/05-upgrade-kyma.md
Labels: size/XS, lgtm

#15509 [Telemetry Operator] Set images of operator and exporter to latest
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#15507 Changing images of the components to the commit ones
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/XS, lgtm

#15510 Update Eventing images
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#15515 Move changelog generation to release action step
  .github/workflows/github-release.yaml
Labels: area/ci, size/S, lgtm

#15516 Bump api-gateway to 1.0.0
  resources/api-gateway/values.yaml
Labels: size/XS, lgtm

#15520 Bump serverless images
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15517 Update the Application Connector tests images
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: size/XS, lgtm

#15534 fix Kyma-release pipeline
  .github/workflows/github-release.yaml
Labels: size/S, lgtm

#15513 Fix inttermitent Serverless integration test failiure on update conflicts.
  resources/serverless/values.yaml
  tests/function-controller/Dockerfile
  tests/function-controller/go.mod
  tests/function-controller/go.sum
  tests/function-controller/pkg/resource/resource.go
  tests/function-controller/pkg/retry/retry.go
  tests/function-controller/pkg/subscription/subscription.go
Labels: size/XL, lgtm

#15511 Update CPU requests for Istio pods with HPA
  resources/istio/profile-production.yaml
  resources/istio/values.yaml
  tests/components/istio/features/istio_production.feature
Labels: size/S, lgtm

#15527 Istio reconciliation test - wait for httpbin to become ready
  tests/components/istio/features/istio_reconcilation.feature
Labels: size/XS, lgtm

#15540 Fix loki typo for release 2.7
  resources/logging/profile-production.yaml
Labels: size/XS, lgtm

#15539 fix typo in resources
  resources/logging/profile-production.yaml
Labels: size/XS, lgtm

#15538 Bump Serverless tests image
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15561 Revert: add a system-account user to nats-server
  docs/04-operation-guides/operations/evnt-03-nats-server-system-events.md
  resources/eventing/charts/nats/templates/configmap.yaml
  resources/eventing/charts/nats/templates/secret.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
Labels: size/L, lgtm

#15565 Revert: add a system-account user to nats-server [release-2.7]
  docs/04-operation-guides/operations/evnt-03-nats-server-system-events.md
  resources/eventing/charts/nats/templates/configmap.yaml
  resources/eventing/charts/nats/templates/secret.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
Labels: size/L, lgtm

#15571 Fix the command to add the workloads to Service Mesh
  docs/03-tutorials/00-application-connectivity/ac-03-register-manage-services.md
Labels: kind/bug, area/documentation, area/application-connector, size/XS, lgtm

#15528 Updated jaeger to version 1.37.0
  installation/resources/crds/tracing/jaegers.jaegertracing.crd.yaml
  resources/tracing/Chart.yaml
  resources/tracing/templates/certificate.yaml
  resources/tracing/templates/deployment.yaml
  resources/tracing/templates/kyma-additions/metrics-servicemonitor.yaml
  resources/tracing/templates/mutating-webhook.yaml
  resources/tracing/templates/psp.yaml
  resources/tracing/templates/role.yaml
  resources/tracing/templates/service-account.yaml
  resources/tracing/templates/service.yaml
  resources/tracing/templates/validating-webhook.yaml
  resources/tracing/templates/webhook-secret.yaml
  resources/tracing/values.yaml
Labels: area/tracing, size/XXL, lgtm

#15568 Improve Log Pipeline controller syncer
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/secret_helper.go
  components/telemetry-operator/controller/logpipeline/secret_helper_test.go
  components/telemetry-operator/controller/logpipeline/sync.go
  components/telemetry-operator/controller/logpipeline/sync_test.go
  resources/telemetry/values.yaml
Labels: area/logging, size/XL, lgtm

#15580 make dashboards readonly
  resources/eventing/charts/dashboards/templates/delivery.yaml
  resources/eventing/charts/dashboards/templates/jetstream.yaml
  resources/eventing/charts/dashboards/templates/latency.yaml
  resources/eventing/charts/dashboards/templates/nats.yaml
  resources/eventing/charts/dashboards/templates/pods.yaml
Labels: size/S, lgtm

#15469 Bump NATS image to 2.9.0
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#15564 Set permissive mTLS policy for publisher-proxy metrics port
  resources/eventing/charts/publisher-proxy/templates/peerauthentication.yaml
  resources/eventing/charts/publisher-proxy/templates/servicemonitor.yaml
Labels: size/XS, lgtm

#15119 Cra test gql to compass
  tests/components/application-connector/Makefile.test-compass-runtime-agent
  tests/components/application-connector/go.mod
  tests/components/application-connector/go.sum
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/templates/service-account.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/templates/test.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/test/compass-runtime-agent/config.go
  tests/components/application-connector/test/compass-runtime-agent/suite_test.go
  tests/components/application-connector/test/compass-runtime-agent/synchronisation_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/directorclient.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/directorclient_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/mocks/Client.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/model.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/queryprovider.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/graphql/client.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/graphql/gql_client_testkit.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/graphql/mocks/Client.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/oauth/client.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/oauth/client_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/oauth/mocks/Client.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/oauth/types.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/oauth/types_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/third_party/machinebox/graphql/LICENSE
  tests/components/application-connector/test/compass-runtime-agent/testkit/third_party/machinebox/graphql/README.md
  tests/components/application-connector/test/compass-runtime-agent/testkit/third_party/machinebox/graphql/graphql.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/third_party/machinebox/graphql/graphql_json_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/third_party/machinebox/graphql/graphql_multipart_test.go
Labels: area/application-connector, size/XXL, lgtm, area/tests

#15575 [Telemetry Operator] - Restructure integration tests
  tests/fast-integration/monitoring/client.js
  tests/fast-integration/monitoring/grafana.js
  tests/fast-integration/monitoring/index.js
  tests/fast-integration/package.json
  tests/fast-integration/telemetry-test/helpers.js
  tests/fast-integration/telemetry-test/suite.js
  tests/fast-integration/telemetry-test/telemetry-test.js
  tests/fast-integration/telemetry-test/testdata/logparser-regex.yaml
  tests/fast-integration/telemetry-test/testdata/logpipeline-custom-filter-denied.yaml
  tests/fast-integration/telemetry-test/testdata/logpipeline-custom-filter-unknown.yaml
  tests/fast-integration/telemetry-test/testdata/logpipeline-input-containers-exclude.yaml
  tests/fast-integration/telemetry-test/testdata/logpipeline-input-drop-labels.yaml
  tests/fast-integration/telemetry-test/testdata/logpipeline-input-keep-labels.yaml
  tests/fast-integration/telemetry-test/testdata/logpipeline-output-http.yaml
  tests/fast-integration/telemetry-test/testdata/logs-workload.yaml
  tests/fast-integration/telemetry-test/testdata/mockserver.yaml
  tests/fast-integration/telemetry-test/testdata/regex-filter-deployment.yaml
Labels: size/XL, lgtm

#15582 Moved LoggerWithSubscription method from utils to backendutils
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/pkg/backend/beb/beb.go
  components/eventing-controller/pkg/backend/nats/core/core.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/utils/utils.go
  components/eventing-controller/utils/utils.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#15585 Change VERSION to 2.7.0
  VERSION
Labels: size/XS, lgtm

#15512 add function resource profile to conversion from function v1alpha2 to…
  components/function-controller/cmd/manager/main.go
  components/function-controller/cmd/webhook/main.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/internal/git/errors.go
  components/function-controller/internal/webhook/config.go
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha1/gitrepository_types.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#15591 Fixing APIRule v1alpha1 sub-resources handling
  resources/api-gateway/values.yaml
Labels: area/api-gateway, size/XS, lgtm

#15559 Update of code owners in the Kyma repository
  CODEOWNERS
Labels: size/M, lgtm

#15581 remove kyma 1 traces
  tests/fast-integration/monitoring/.env.template
  tests/fast-integration/monitoring/grafana.js
Labels: size/M, lgtm

#15595 Add a few debug logs to the function-controller
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  resources/serverless/values.yaml
Labels: area/serverless, size/S, lgtm

#15605 Added testing common files for v1alpha2 Subscription CRD
  components/eventing-controller/testing/v2/matchers.go
  components/eventing-controller/testing/v2/test_helpers.go
  resources/eventing/values.yaml
Labels: size/XL, lgtm

#15606 Generic cleaners for backends
  components/eventing-controller/controllers/subscriptionv2/beb/reconciler.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler.go
  components/eventing-controller/pkg/backend/cleaner/eventmesh.go
  components/eventing-controller/pkg/backend/cleaner/jetstream.go
  components/eventing-controller/pkg/backend/cleaner/types.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#15609 Fix the Eventing publisher proxy lint issues
  components/event-publisher-proxy/pkg/handler/beb/handler.go
  components/event-publisher-proxy/pkg/handler/beb/handler_integration_test.go
  components/event-publisher-proxy/pkg/handler/handlertest/handlertest.go
  components/event-publisher-proxy/pkg/handler/nats/handler_integration_test.go
  components/event-publisher-proxy/pkg/metrics/server.go
  components/event-publisher-proxy/pkg/receiver/receiver.go
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#15374 [Telemetry Operator] Set output plugin alias and rewrite tag emitter name
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline_input_includes.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline_loki.yaml
  components/telemetry-operator/controller/logpipeline/controller_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/config_builder_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/output.go
  components/telemetry-operator/internal/fluentbit/config/builder/output_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/rewritetag_filter.go
  components/telemetry-operator/internal/fluentbit/config/builder/rewritetag_filter_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/section_builder.go
  components/telemetry-operator/webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
  resources/telemetry/charts/fluent-bit/values.yaml
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15611 Add api-gateway to areas
  .github/package.json
Labels: size/XS, lgtm

#15612 Fix in the Compass Runtime Test
  tests/components/application-connector/Makefile.test-compass-runtime-agent
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
Labels: size/XS, lgtm

#15562 Add optional `namespace` for `service` in APIRule
  docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
Labels: size/S, lgtm

#15614 Add api/gateway area label
  .github/package.json
Labels: size/XS, lgtm

#15620 updated to fixed image for jaeger-operator
  resources/tracing/values.yaml
Labels: area/tracing, size/XS, lgtm

#15617 update to fluent-bit 1.9.8
  components/telemetry-operator/Dockerfile
  resources/logging/values.yaml
  resources/telemetry/values.yaml
Labels: area/logging, size/XS, lgtm

#15641 change doc after remove replicas preset from function
  docs/05-technical-reference/svls-09-available-presets.md
Labels: size/S, lgtm

#15645 Bump libgit2 for Funtion Controller
  components/function-controller/go.mod
  components/function-controller/go.sum
  resources/serverless/values.yaml
Labels: size/S, lgtm

#15650 Add link to Keda example
  docs/03-tutorials/00-serverless/svls-15-use-external-scalers.md
Labels: size/XS, lgtm

#15613 add build resource profile to conversion between function v1alpha1 an…
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#15652 updated golang version for loki image
  resources/logging/values.yaml
Labels: area/logging, size/XS, lgtm

#15646 [Telemetry Operator] Fix flaky tests
  tests/fast-integration/logging/client.js
  tests/fast-integration/logging/index.js
  tests/fast-integration/logging/loki.js
  tests/fast-integration/monitoring/client.js
  tests/fast-integration/monitoring/grafana.js
  tests/fast-integration/monitoring/index.js
  tests/fast-integration/monitoring/prometheus.js
  tests/fast-integration/telemetry-test/helpers.js
  tests/fast-integration/telemetry-test/suite.js
  tests/fast-integration/telemetry-test/testdata/logs-workload.yaml
Labels: size/L, lgtm

#15560 remove dead code (unused nats core)
  components/event-publisher-proxy/cmd/event-publisher-proxy/main.go
  components/event-publisher-proxy/cmd/event-publisher-proxy/nats/nats.go
  components/event-publisher-proxy/pkg/handler/beb/handler.go
  components/event-publisher-proxy/pkg/handler/beb/handler_integration_test.go
  components/event-publisher-proxy/pkg/handler/handlertest/handlertest.go
  components/event-publisher-proxy/pkg/handler/nats/handler.go
  components/event-publisher-proxy/pkg/handler/nats/handler_health_test.go
  components/event-publisher-proxy/pkg/handler/nats/handler_integration_test.go
  components/event-publisher-proxy/pkg/handler/nats/health.go
  components/event-publisher-proxy/pkg/handler/nats/health_test.go
  components/event-publisher-proxy/pkg/handler/nats/mock/mock.go
  components/event-publisher-proxy/pkg/metrics/server.go
  components/event-publisher-proxy/pkg/nats/connect_test.go
  components/event-publisher-proxy/pkg/receiver/receiver.go
  components/event-publisher-proxy/pkg/sender/jetstream.go
  components/event-publisher-proxy/pkg/sender/jetstream_test.go
  components/event-publisher-proxy/pkg/sender/nats.go
  components/event-publisher-proxy/pkg/sender/nats_test.go
  components/event-publisher-proxy/testing/nats.go
  components/eventing-controller/api/v1alpha1/condition.go
  components/eventing-controller/api/v1alpha1/eventingbackend_types.go
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_eventingbackends.yaml
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/options/options.go
  components/eventing-controller/pkg/backend/nats/core/core.go
  components/eventing-controller/pkg/backend/nats/core/core_test.go
  components/eventing-controller/pkg/backend/nats/core/test_helpers.go
  components/eventing-controller/pkg/deployment/publisher_deployment.go
  components/eventing-controller/pkg/deployment/publisher_deployment_test.go
  components/eventing-controller/pkg/env/nats_config.go
  components/eventing-controller/pkg/env/nats_config_test.go
  components/eventing-controller/pkg/subscriptionmanager/nats/nats.go
  components/eventing-controller/pkg/subscriptionmanager/nats/nats_test.go
  resources/eventing/README.md
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/dashboards/templates/jetstream.yaml
  resources/eventing/charts/dashboards/templates/nats.yaml
  resources/eventing/charts/nats/templates/configmap.yaml
  resources/eventing/charts/nats/templates/serviceMonitor.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
  resources/eventing/values.yaml
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/metric-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: size/XXL, lgtm

#15653 fix broken links kyma repo
  components/eventing-controller/README.md
Labels: size/XS, lgtm

#15428 [Telemetry Operator] Secrets watcher
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/secrets_cache.go
  components/telemetry-operator/controller/logpipeline/secrets_cache_test.go
  components/telemetry-operator/main.go
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/suite.js
  tests/fast-integration/telemetry-test/testdata/http-backend-1-secret.yaml
  tests/fast-integration/telemetry-test/testdata/http-backend-2-secret.yaml
  tests/fast-integration/telemetry-test/testdata/http-backend-namespaces.yaml
  tests/fast-integration/telemetry-test/testdata/http-backend.yaml
  tests/fast-integration/telemetry-test/testdata/logpipeline-output-http.yaml
Labels: size/L, lgtm

#15610 add tests for profile conversion between v1alpha1 and v1alpha2
  components/function-controller/internal/webhook/conversion_webhook_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#15574 Adapt expose tutorial and add multi namespace one
  docs/03-tutorials/00-api-exposure/apix-03-expose-workload-apigateway.md
  docs/03-tutorials/00-api-exposure/apix-09-expose-workloads-multiple-namespaces.md
Labels: size/L, lgtm

#15661 Bump api-gateway to 1.1.0
  resources/api-gateway/Chart.yaml
  resources/api-gateway/values.yaml
Labels: size/XS, lgtm

#15583 Add Subscription conversion logic v1alpha1 to v1alpha2 and backwards
  components/eventing-controller/api/v1alpha1/condition.go
  components/eventing-controller/api/v1alpha1/fixtures_test.go
  components/eventing-controller/api/v1alpha1/subscription_conversion.go
  components/eventing-controller/api/v1alpha1/subscription_conversion_test.go
  components/eventing-controller/api/v1alpha2/constants.go
  components/eventing-controller/api/v1alpha2/spec_types.go
  components/eventing-controller/api/v1alpha2/status_types.go
  components/eventing-controller/api/v1alpha2/subscription_types.go
  components/eventing-controller/api/v1alpha2/zz_generated.deepcopy.go
  components/eventing-controller/pkg/backend/bebv2/beb.go
  components/eventing-controller/testing/v2/subscription.go
  components/eventing-controller/testing/v2/test_helpers.go
  resources/eventing/values.yaml
Labels: size/XXL, lgtm

#15570 Use OPTL trace exporter in Serverless
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/lib/tracer.js
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/package.json
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/lib/tracer.js
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/package.json
  components/function-runtimes/nodejs16/lib/tracer.js
  components/function-runtimes/nodejs16/package.json
  components/function-runtimes/python39/Dockerfile
  components/function-runtimes/python39/kubeless/requirements.txt
  components/function-runtimes/python39/kubeless/tracing.py
Labels: size/M, lgtm

#15670 fix gomod issue with api-gateway
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
Labels: area/eventing, size/XS, lgtm

#15651 Restructure test files ec
  components/eventing-controller/api/v1alpha1/condition_test.go
  components/eventing-controller/api/v1alpha1/condition_unit_test.go
  components/eventing-controller/api/v1alpha1/fixtures_test.go
  components/eventing-controller/api/v1alpha1/subscription_conversion_unit_test.go
  components/eventing-controller/api/v1alpha1/subscription_types_unit_test.go
  components/eventing-controller/api/v1alpha2/condition_test.go
  components/eventing-controller/api/v1alpha2/condition_unit_test.go
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/backend/reconciler_internal_unit_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/XXL, lgtm

#15674 allow OTLP ports for jaeger collector
  resources/tracing/templates/kyma-additions/authorization-policy.yaml
Labels: size/XS, lgtm

#15676 Update secret rotation docs
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: size/S, lgtm

#15678 Allow adding custom service accounts to Jaeger authorizationPolicy
  resources/tracing/templates/kyma-additions/authorization-policy.yaml
  resources/tracing/values.yaml
Labels: size/S, lgtm

#15596 Added EventMesh backend/handler for Subscription v1alpha2
  components/eventing-controller/api/v1alpha2/eventmesh_types.go
  components/eventing-controller/api/v1alpha2/status_types.go
  components/eventing-controller/api/v1alpha2/subscription_types.go
  components/eventing-controller/api/v1alpha2/utils.go
  components/eventing-controller/api/v1alpha2/zz_generated.deepcopy.go
  components/eventing-controller/config/crd/basesv1alpha2/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/beb/reconciler.go
  components/eventing-controller/pkg/backend/beb/beb.go
  components/eventing-controller/pkg/backend/bebv2/beb.go
  components/eventing-controller/pkg/backend/cleaner/eventmesh.go
  components/eventing-controller/pkg/backend/cleaner/eventmesh_test.go
  components/eventing-controller/pkg/backend/eventmesh/eventmesh.go
  components/eventing-controller/pkg/backend/eventmesh/eventmesh_test.go
  components/eventing-controller/pkg/backend/eventmesh/utils.go
  components/eventing-controller/pkg/backend/eventmesh/utils_test.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils_test.go
  components/eventing-controller/pkg/backend/utils/utils.go
  components/eventing-controller/pkg/backend/utils/utils_test.go
  components/eventing-controller/pkg/backend/utils/v2/utils.go
  components/eventing-controller/pkg/ems/api/events/client/mocks/PublisherManager.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb_test.go
  components/eventing-controller/testing/v2/subscription.go
  components/eventing-controller/testing/v2/test_helpers.go
  components/eventing-controller/utils/utils.go
  components/eventing-controller/utils/utils_unit_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/XXL, lgtm

#15683 Update to grafana 7.5.17
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#15686 Backport: Update to grafana 7.5.17
  resources/monitoring/values.yaml
Labels: area/monitoring, area/logging, size/XS, lgtm

#15644 Update istio charts with istio 1.15.0 and cni
  resources/istio-resources/files/dashboards/control-plane.json
  resources/istio-resources/files/dashboards/mesh.json
  resources/istio-resources/files/dashboards/performance.json
  resources/istio-resources/files/dashboards/service.json
  resources/istio-resources/files/dashboards/workload.json
  resources/istio/Chart.yaml
  resources/istio/profile-evaluation.yaml
  resources/istio/profile-production.yaml
  resources/istio/templates/istio-operator.yaml
  resources/istio/values.yaml
  resources/ory/charts/hydra/templates/deployment.yaml
Labels: area/service-mesh, size/M, lgtm

#15689 bump dependencies in `event-publisher-proxy`
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  resources/eventing/values.yaml
Labels: size/L, lgtm

#15693 Add entry for cni in istio docs
  docs/05-technical-reference/00-configuration-parameters/smsh-01-istio-chart.md
Labels: size/XS, lgtm

#15642 added link for fluentbit
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: size/XS, lgtm

#15690 bump the external crd for apirules-gateway
  components/eventing-controller/config/crd/external/apirules-gateway-kyma-project-io.yaml
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  resources/eventing/values.yaml
Labels: size/S, lgtm
