Repository kyma-project/kyma, pull requests merged in 2022-12, with the labels that each got.

#16233 Add maxBytes and discard policy info to documentation
  docs/01-overview/main-areas/eventing/evnt-90-glossary.md
Labels: size/XS, lgtm

#16209 API-gateway custom domain test AWS support
  tests/components/api-gateway/README.md
  tests/components/api-gateway/custom_domain_test.go
  tests/components/api-gateway/pkg/helpers/loadbalancer.go
Labels: size/M, lgtm

#16227 Including OS information to path in Makefile
  components/telemetry-operator/Makefile
Labels: size/XS, lgtm

#16241 Update migration-guide-2.8-2.9.md
  docs/migration-guide-2.8-2.9.md
Labels: size/XS, lgtm

#16240 Bump sqlite-dev to newest edge version
  components/function-runtimes/python39/Dockerfile
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#16243 change loglevel from debug to error for invalid legacyEvent
  components/event-publisher-proxy/pkg/handler/handler.go
Labels: area/eventing, size/XS, lgtm

#16128 Update Serverless & APIRules Kyma Dashboard guides
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/03-tutorials/00-serverless/README.md
  docs/03-tutorials/00-serverless/assets/svls-function-ui.png
  docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
  docs/03-tutorials/00-serverless/svls-02-create-git-function.md
  docs/03-tutorials/00-serverless/svls-03-expose-function.md
Labels: area/busola, area/serverless, area/api-gateway, size/M, lgtm

#16245 bump epp image
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#16183 add explanations to function's api
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#16226 [Telemetry Operator] Harden otel-collector deployment
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/controller_test.go
  components/telemetry-operator/controller/tracepipeline/resources.go
  components/telemetry-operator/controller/tracepipeline/resources_test.go
  components/telemetry-operator/controller/tracepipeline/suite_test.go
  components/telemetry-operator/main.go
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#16250 Update VERSION to 2.9.2
  VERSION
Labels: size/XS, lgtm

#16177 [Telemetry Operator] Unify error handling in controllers
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  components/telemetry-operator/config/rbac/role.yaml
  components/telemetry-operator/controller/common.go
  components/telemetry-operator/controller/logparser/controller.go
  components/telemetry-operator/controller/logparser/setup.go
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/finalizer.go
  components/telemetry-operator/controller/logpipeline/finalizer_test.go
  components/telemetry-operator/controller/logpipeline/setup.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/setup.go
  components/telemetry-operator/internal/setup/predicates.go
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#16176 add component name to nats connection
  components/event-publisher-proxy/pkg/commander/nats/nats.go
  components/event-publisher-proxy/pkg/nats/connect.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#16212 add example with SecretMounts to doc
  docs/03-tutorials/00-serverless/svls-16-use-secret-mounts.md
Labels: size/L, lgtm

#16221 TracePipeline simple status
  components/telemetry-operator/apis/telemetry/v1alpha1/tracepipeline_types.go
  components/telemetry-operator/apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  components/telemetry-operator/config/rbac/role.yaml
  components/telemetry-operator/controller/logparser/finalizer.go
  components/telemetry-operator/controller/logparser/finalizer_test.go
  components/telemetry-operator/controller/logparser/status_test.go
  components/telemetry-operator/controller/logpipeline/finalizer.go
  components/telemetry-operator/controller/logpipeline/finalizer_test.go
  components/telemetry-operator/controller/logpipeline/status_test.go
  components/telemetry-operator/controller/logpipeline/suite_test.go
  components/telemetry-operator/controller/logpipeline/sync.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/mocks/deployment_prober.go
  components/telemetry-operator/controller/tracepipeline/secret_refs.go
  components/telemetry-operator/controller/tracepipeline/status.go
  components/telemetry-operator/controller/tracepipeline/status_test.go
  components/telemetry-operator/controller/tracepipeline/suite_test.go
  components/telemetry-operator/go.mod
  components/telemetry-operator/internal/configchecksum/checksum_test.go
  components/telemetry-operator/internal/kubernetes/daemonset.go
  components/telemetry-operator/internal/kubernetes/daemonset_test.go
  components/telemetry-operator/internal/kubernetes/deployment.go
  components/telemetry-operator/main.go
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/helpers.js
  tests/fast-integration/telemetry-test/suite.js
Labels: size/XL, lgtm

#16253 [Telemetry Operator] Use standard library errors pkg
  components/telemetry-operator/go.mod
  components/telemetry-operator/webhook/logpipeline/validation/filter_validator.go
  components/telemetry-operator/webhook/logpipeline/webhook_test.go
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#16256 Fix issue with internal registry after waking up from hibernation
  resources/serverless/charts/docker-registry/values.yaml
Labels: kind/bug, area/serverless, size/XS, lgtm

#16265 Fix CVE-2022-32149
  components/webhook-cert-init/go.mod
  components/webhook-cert-init/go.sum
Labels: size/S, lgtm

#16259 Fix request body parsers in nodejs runtimes
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/kubeless.js
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/lib/ce.js
  components/function-runtimes/nodejs16/lib/ce.js
  components/function-runtimes/nodejs16/server.js
  resources/serverless/values.yaml
Labels: size/M, lgtm

#16276 Test cleaning 20221202
  resources/serverless/values.yaml
  tests/function-controller/run_integration_tests.sh
  tests/function-controller/testsuite/scenarios/conversion.go
  tests/function-controller/testsuite/scenarios/gitauth.go
  tests/function-controller/testsuite/scenarios/gitops.go
  tests/function-controller/testsuite/scenarios/light_runtimes.go
Labels: size/M, lgtm

#16197 Add eventing FI tests for Subscription v1alpha2 CRD
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#16283 [Telemetry Operator] Deploy internal OpenCensus service
  components/telemetry-operator/controller/tracepipeline/controller.go
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#16260 Add validation webhook integration tests for eventmesh
  components/eventing-controller/api/v1alpha2/subscription_webhook.go
  components/eventing-controller/config/.gitignore
  components/eventing-controller/config/webhook/manifests.yaml
  components/eventing-controller/controllers/subscriptionv2/eventmesh/test/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/test/utils.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#16285 Fix links to monitoring custom metrics folder
  docs/03-tutorials/00-observability/README.md
  docs/03-tutorials/00-observability/obsv-01-observe-application-metrics.md
Labels: size/XS, lgtm

#16278 Change the sequence in the execution of the eventing tests
  tests/fast-integration/upgrade-test/upgrade-test-tests.js
Labels: size/XS, lgtm

#16281 Bump golang.org libraries in kyma/common to latest versions
  CODEOWNERS
  common/go.mod
  common/go.sum
  common/logging/go.mod
  common/logging/go.sum
Labels: size/M, lgtm

#16252 Remove observability tutorial and link to examples
  docs/03-tutorials/00-observability/README.md
  docs/03-tutorials/00-observability/assets/alert-notifications.png
  docs/03-tutorials/00-observability/assets/fired-alert.png
  docs/03-tutorials/00-observability/assets/integration-settings.png
  docs/03-tutorials/00-observability/assets/monitoring-tutorials.svg
  docs/03-tutorials/00-observability/assets/pm-dashboard-1.png
  docs/03-tutorials/00-observability/assets/pm-dashboard-2.png
  docs/03-tutorials/00-observability/assets/rules-dashboard.png
  docs/03-tutorials/00-observability/assets/sample-metrics-2.png
  docs/03-tutorials/00-observability/obsv-01-observe-application-metrics.md
  docs/03-tutorials/00-observability/obsv-02-create-and-configure-grafana-dashboard.md
  docs/03-tutorials/00-observability/obsv-03-define-alerting-rules-monitor.md
  docs/03-tutorials/00-observability/obsv-04-send-notifications.md
  docs/03-tutorials/00-observability/obsv-05-clean-up-configuration.md
  docs/05-technical-reference/00-architecture/obsv-01-architecture-monitoring.md
Labels: size/L, lgtm

#16290 Bump module dependencies of central-application-connectivity-validator
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  resources/application-connector/values.yaml
Labels: size/M, lgtm

#16282 Remove unused code from serverless tests
  resources/serverless/values.yaml
  tests/function-controller/pkg/apirule/apirule.go
  tests/function-controller/pkg/broker/broker.go
  tests/function-controller/pkg/job/job.go
  tests/function-controller/pkg/subscription/subscription.go
  tests/function-controller/testsuite/runtimes/cfg.go
Labels: size/XL, lgtm

#16277 update to latest prometheus images
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#16293 update to latest prometheus images (#16277)
  resources/monitoring/values.yaml
Labels: lgtm

#16292 Updated version of postgres
  resources/ory/values.yaml
Labels: size/XS, lgtm

#16294 Add validation webhook reconciler tests for jetstream
  components/eventing-controller/controllers/subscriptionv2/eventmesh/test/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/test/utils.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/test_utils.go
  components/eventing-controller/controllers/subscriptionv2/reconcilertesting/test_utils.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#16239 CRI delete app test
  tests/components/application-connector/Dockerfile.compass-runtime-agent
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/test/compass-runtime-agent/suite_test.go
  tests/components/application-connector/test/compass-runtime-agent/synchronisation_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/comparator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/comparator_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/mocks/ApplicationGetter.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/mocks/Comparator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/secretcomparator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/secretcomparator_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/mocks/Client.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/graphql/mocks/Client.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/CertificateSecretConfigurator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/CompassConfigurator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/CompassConnectionConfigurator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/ConfigurationSecretConfigurator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/DeploymentConfigurator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/DirectorClient.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/oauth/mocks/Client.go
Labels: size/L, lgtm

#16297 Improve telemetry-operator health checks
  components/telemetry-operator/main.go
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/suite.js
Labels: size/M, lgtm

#16263 [Telemetry Operator] - Operator managed Fluent Bit
  components/telemetry-operator/config/rbac/role.yaml
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/utils.go
  components/telemetry-operator/internal/kubernetes/utils.go
  components/telemetry-operator/internal/resources/logpipeline/resources.go
  components/telemetry-operator/internal/resources/logpipeline/resources_test.go
  components/telemetry-operator/main.go
  components/telemetry-operator/webhook/dryrun/file_writer.go
  resources/telemetry/charts/fluent-bit/templates/configmap-luascripts.yaml
  resources/telemetry/charts/fluent-bit/templates/configmap.yaml
  resources/telemetry/charts/fluent-bit/templates/daemonset.yaml
  resources/telemetry/charts/fluent-bit/templates/service.yaml
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/templates/role.yaml
  resources/telemetry/values.yaml
Labels: size/XL, lgtm

#16328 [release-2.9] Bump Serverless runtimes
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/nodejs16/Dockerfile
  components/function-runtimes/python39/Dockerfile
Labels: size/S, lgtm

#16309 Bump Serverless runtimes
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/nodejs16/Dockerfile
  components/function-runtimes/python39/Dockerfile
  resources/serverless/values.yaml
Labels: area/serverless, area/security, size/S, lgtm

#16308 bump image to golang1.19.4-alpine3.17 in ec and epp
  components/event-publisher-proxy/Dockerfile
  components/eventing-controller/Dockerfile
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#16284 Clean up e2e tests -remove unused fields
  components/function-runtimes/nodejs16/.gitignore
  resources/serverless/values.yaml
  tests/function-controller/Makefile
  tests/function-controller/pkg/configmap/configmap.go
  tests/function-controller/pkg/function/function.go
  tests/function-controller/pkg/function/functiondetails.go
  tests/function-controller/pkg/function/v1alpha1/function.go
  tests/function-controller/pkg/git/git.go
  tests/function-controller/pkg/gitrepository/gitrepository.go
  tests/function-controller/pkg/gitserver/gitserver.go
  tests/function-controller/pkg/namespace/namespace.go
  tests/function-controller/pkg/secret/secret.go
  tests/function-controller/pkg/shared/shared.go
  tests/function-controller/testsuite/scenarios/light_runtimes.go
  tests/function-controller/testsuite/teststep/function.go
Labels: size/L, lgtm

#16335 [relsease-2.9] Serverless go.mod versions bump
  components/function-controller/go.mod
  components/function-controller/go.sum
Labels: area/serverless, area/security, lgtm

#16347 Register keda-module 0.0.1 in alpha channel
  modules/alpha/kustomization.yaml
  modules/alpha/moduletemplate-keda.yaml
Labels: size/M, lgtm

#16304 Trace collector default resource request values update
  components/telemetry-operator/main.go
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#16348 Remove JeremyHarisch from OwnersFile
  CODEOWNERS
Labels: size/XS, lgtm

#16334 Serverless go.mod versions bump
  components/function-controller/go.mod
  components/function-controller/go.sum
  resources/serverless/values.yaml
Labels: area/serverless, area/security, size/M, lgtm

#16275 Adapt subscribed api
  components/event-publisher-proxy/cmd/event-publisher-proxy/main.go
  components/event-publisher-proxy/pkg/commander/beb/beb.go
  components/event-publisher-proxy/pkg/commander/nats/nats.go
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/options/options.go
  components/event-publisher-proxy/pkg/subscribed/helpers.go
  components/event-publisher-proxy/pkg/subscribed/helpers_test.go
  components/event-publisher-proxy/pkg/subscribed/processor.go
  components/eventing-controller/pkg/deployment/publisher_deployment.go
  components/eventing-controller/pkg/env/backend_config.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#16351 Print error when jetstream dispatch fails
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
Labels: area/eventing, size/XS, lgtm

#16295 Remove simple fn cfg from integration tests
  resources/serverless/values.yaml
  tests/function-controller/pkg/function/function.go
  tests/function-controller/testsuite/runtimes/cfg.go
  tests/function-controller/testsuite/scenarios/light_runtimes.go
Labels: area/serverless, size/L, lgtm, kind/cleanup

#16264 Protocol and auth settings for EventMesh in v1alpha2 subscritpion
  components/eventing-controller/api/v1alpha1/fixtures_test.go
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/api/v1alpha2/subscription_types.go
  components/eventing-controller/api/v1alpha2/zz_generated.deepcopy.go
  components/eventing-controller/pkg/backend/eventmesh/eventmesh.go
  components/eventing-controller/pkg/backend/utils/eventmesh_types.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils_test.go
  components/eventing-controller/pkg/env/nats_config.go
  components/eventing-controller/testing/v2/test_helpers.go
  resources/eventing/values.yaml
Labels: size/XL, lgtm

#16343 fix conversion bug for protocol settings
  components/eventing-controller/api/v1alpha1/subscription_conversion.go
  components/eventing-controller/api/v1alpha1/subscription_conversion_unit_test.go
  components/eventing-controller/testing/test_helpers.go
  components/eventing-controller/testing/v2/test_helpers.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#16352 Update cleanup logic for jetstream v1alpha2 to clean slashes
  components/eventing-controller/pkg/backend/cleaner/jetstream.go
  components/eventing-controller/pkg/backend/cleaner/jetstream_unit_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/S, lgtm

#16356 Fix a broken link
  tests/function-controller/README.md
Labels: size/XS, lgtm

#16361 Fix bug
  docs/05-technical-reference/svls-08-function-specification.md
Labels: size/XS, lgtm

#16360 Fix bug
  docs/05-technical-reference/svls-08-function-specification.md
Labels: size/XS, lgtm

#16357 Disable TLS when non https endpoint used
  components/telemetry-operator/controller/tracepipeline/resources.go
  components/telemetry-operator/controller/tracepipeline/resources_test.go
  resources/telemetry/values.yaml
Labels: size/M, lgtm

#16296 Add kubectl proxy support to serverless integration tests
  resources/serverless/values.yaml
  tests/function-controller/Dockerfile
  tests/function-controller/README.md
  tests/function-controller/pkg/function/function.go
  tests/function-controller/pkg/function/v1alpha1/function.go
  tests/function-controller/pkg/gitserver/gitserver.go
  tests/function-controller/pkg/helpers/url.go
  tests/function-controller/pkg/namespace/namespace.go
  tests/function-controller/testsuite/config.go
  tests/function-controller/testsuite/gitops/cfg.go
  tests/function-controller/testsuite/gitops/v1alpha1/cfg.go
  tests/function-controller/testsuite/runtimes/v1alpha1/cfg.go
  tests/function-controller/testsuite/scenarios/conversion.go
  tests/function-controller/testsuite/scenarios/gitauth.go
  tests/function-controller/testsuite/scenarios/gitops.go
  tests/function-controller/testsuite/scenarios/light_runtimes.go
  tests/function-controller/testsuite/teststep/gitserver.go
Labels: size/L, lgtm

#16364 include support for k8sattribute and attribute resource support
  components/telemetry-operator/controller/tracepipeline/resources.go
  resources/telemetry/charts/operator/templates/trace-collector-role.yaml
  resources/telemetry/values.yaml
Labels: size/M, lgtm

#16373 Bump Golang images in Application Connector components
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
Labels: area/security, area/application-connector, size/XS, lgtm

#16371 Update Istio to 1.16.1
  resources/istio-resources/files/dashboards/control-plane.json
  resources/istio-resources/files/dashboards/mesh.json
  resources/istio-resources/files/dashboards/performance.json
  resources/istio-resources/files/dashboards/service.json
  resources/istio-resources/files/dashboards/workload.json
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: area/service-mesh, size/S, lgtm

#16377 Use local kyma directory if defined in Istio component test
  tests/components/istio/Makefile
  tests/components/istio/helpers/command_runner.go
  tests/components/istio/istio_reconcilation_test.go
Labels: size/S, lgtm

#16338 [Telemetry Operator] - Fix managed Fluent Bit
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/internal/kubernetes/utils.go
  components/telemetry-operator/internal/resources/logpipeline/resources.go
  components/telemetry-operator/internal/resources/logpipeline/resources_test.go
  resources/telemetry/values.yaml
Labels: size/M, lgtm

#15901 Java runtime based on JVM as alpha function runtime
  components/function-controller/.gitignore
  components/function-runtimes/java17/.gitignore
  components/function-runtimes/java17/Dockerfile-jvm-function-local
  components/function-runtimes/java17/Dockerfile-jvm-function.tpl
  components/function-runtimes/java17/Dockerfile-jvm-runtime
  components/function-runtimes/java17/Makefile
  components/function-runtimes/java17/examples/hello-world/.Dockerignore
  components/function-runtimes/java17/examples/hello-world/.gitignore
  components/function-runtimes/java17/examples/hello-world/pom.xml
  components/function-runtimes/java17/examples/hello-world/src/main/java/io/project/kyma/serverless/handler/Handler.java
  components/function-runtimes/java17/pom.xml
  components/function-runtimes/java17/resources/.gitignore
  components/function-runtimes/java17/resources/cm.yaml.tpl
  components/function-runtimes/java17/resources/generate-cm.py
  components/function-runtimes/java17/resources/generate-dockerfile.py
  components/function-runtimes/java17/serverless-java-sdk/Makefile
  components/function-runtimes/java17/serverless-java-sdk/pom.xml
  components/function-runtimes/java17/serverless-java-sdk/src/main/java/io/project/kyma/serverless/sdk/CloudEvent.java
  components/function-runtimes/java17/serverless-java-sdk/src/main/java/io/project/kyma/serverless/sdk/Function.java
  components/function-runtimes/java17/serverless-java-sdk/src/main/java/io/project/kyma/serverless/sdk/ResponseCloudEvent.java
  components/function-runtimes/java17/src/main/java/io/project/kyma/serverless/Config.java
  components/function-runtimes/java17/src/main/java/io/project/kyma/serverless/JerseyServer.java
  components/function-runtimes/java17/src/main/java/io/project/kyma/serverless/Main.java
  components/function-runtimes/java17/src/main/java/io/project/kyma/serverless/handler/Handler.java
  components/function-runtimes/java17/src/main/test/io/project/kyma/serverless/MainTest.java
Labels: area/serverless, size/XL, lgtm

#16379 Add nataliasitko to codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#16336 Redesign of telemetry/observability docu
  docs/01-overview/main-areas/assets/kyma-areas.svg
  docs/01-overview/main-areas/observability/README.md
  docs/01-overview/main-areas/observability/assets/distributed-tracing.svg
  docs/01-overview/main-areas/observability/obsv-02-logging-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-03-tracing-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
  docs/01-overview/main-areas/telemetry/README.md
  docs/01-overview/main-areas/telemetry/assets/general-components.drawio.svg
  docs/01-overview/main-areas/telemetry/assets/general-stages.drawio.svg
  docs/01-overview/main-areas/telemetry/assets/logging-arch.drawio.svg
  docs/01-overview/main-areas/telemetry/assets/logging-flow.drawio.svg
  docs/01-overview/main-areas/telemetry/assets/logging-pipelines.drawio.svg
  docs/01-overview/main-areas/telemetry/assets/logging-resources.drawio.svg
  docs/01-overview/main-areas/telemetry/assets/operator-lifecycle.drawio.svg
  docs/01-overview/main-areas/telemetry/assets/tracing-arch.drawio.svg
  docs/01-overview/main-areas/telemetry/assets/tracing-intro.drawio.svg
  docs/01-overview/main-areas/telemetry/assets/tracing-resources.drawio.svg
  docs/01-overview/main-areas/telemetry/metadata.yaml
  docs/01-overview/main-areas/telemetry/telemetry-01-operator.md
  docs/01-overview/main-areas/telemetry/telemetry-02-logs.md
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
  docs/01-overview/main-areas/telemetry/telemetry-04-tutorials.md
  docs/05-technical-reference/00-architecture/assets/obsv-tracing-architecture.svg
  docs/05-technical-reference/00-architecture/obsv-02-architecture-logging.md
  docs/05-technical-reference/00-architecture/obsv-03-architecture-tracing.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/telemetry-01-logpipeline.md
  docs/05-technical-reference/00-custom-resources/telemetry-02-logparser.md
  docs/05-technical-reference/00-custom-resources/telemetry-03-tracepipeline.md
Labels: size/XXL, lgtm

#16382 Bump the golang version in the AC
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/S, lgtm

#16385 bump images
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#16386 [Telemetry Operator] - Fix deployment util merge annotations
  components/telemetry-operator/controller/tracepipeline/resources_test.go
  components/telemetry-operator/internal/kubernetes/utils.go
  components/telemetry-operator/internal/kubernetes/utils_test.go
Labels: size/M, lgtm

#16219 Own Cluster Fast Integration Tests
  tests/fast-integration/Makefile
  tests/fast-integration/gardener/client.js
  tests/fast-integration/kcp/client.js
  tests/fast-integration/package.json
  tests/fast-integration/skr-test/.env.template
  tests/fast-integration/skr-test/helpers.js
  tests/fast-integration/skr-test/test-own-cluster.js
Labels: size/L, lgtm

#16394 adding istio tracing to the tracing documentation
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
Labels: area/tracing, size/L, lgtm

#16402 Update telemetry-03-traces.md
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
Labels: size/XS, lgtm

#16358 Made JetStream tests use unique stream names
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/subscription/testing/test_utils.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/test_utils.go
  components/eventing-controller/controllers/subscriptionv2/reconcilertesting/jetstream_matchers.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/test_helpers.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils_unit_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_integration_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_v1v2_integration_test.go
  components/eventing-controller/pkg/env/nats_config.go
  components/eventing-controller/pkg/env/nats_config_test.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream_test.go
  components/eventing-controller/testing/nats.go
  components/eventing-controller/testing/nats/matchers.go
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/values.yaml
Labels: size/L, lgtm

#16262 Implement Serverless internal registry image garbage collector
  components/function-controller/Makefile
  components/function-controller/cmd/registry-gc/main.go
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/go.mod
  components/function-controller/go.sum
  components/function-controller/internal/registry/images.go
  components/function-controller/internal/registry/images_test.go
  components/function-controller/internal/registry/registry.go
  components/function-controller/internal/registry/registry_test.go
  components/function-controller/internal/registry/repository.go
  components/function-controller/internal/registry/utils.go
  components/function-controller/internal/registry/utils_test.go
  resources/serverless/charts/docker-registry/templates/cronjob.yaml
  resources/serverless/charts/docker-registry/templates/deployment.yaml
  resources/serverless/charts/docker-registry/templates/rbac.yaml
  resources/serverless/charts/docker-registry/values.yaml
  resources/serverless/values.yaml
Labels: kind/feature, area/serverless, size/XL, lgtm

#16398 Use latest patch version for nodejs function runtimes
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/nodejs16/Dockerfile
  resources/serverless/values.yaml
Labels: area/serverless, area/security, size/S, lgtm

#16399 Update istio component test after Istio 1.16
  tests/components/istio/features/istio_reconcilation.feature
  tests/components/istio/istio_reconcilation_test.go
Labels: size/M, lgtm

#16370 Display KEB events in SKR tests
  tests/fast-integration/kcp/client.js
  tests/fast-integration/kyma-environment-broker/helpers.js
  tests/fast-integration/skr-aws-upgrade-integration/upgrade/upgrade-skr.js
  tests/fast-integration/skr-nightly/provision/provision-skr-nightly.js
  tests/fast-integration/skr-test/provision/deprovision-skr.js
  tests/fast-integration/skr-test/provision/provision-skr.js
Labels: size/S, lgtm

#16409 improved telemetry docu page titles
  docs/01-overview/main-areas/telemetry/telemetry-01-operator.md
  docs/01-overview/main-areas/telemetry/telemetry-02-logs.md
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
  docs/01-overview/main-areas/telemetry/telemetry-04-tutorials.md
Labels: size/XS, lgtm

#16410 Cosmetic improvement for fast-integration tests events
  tests/fast-integration/kyma-environment-broker/helpers.js
  tests/fast-integration/skr-aws-upgrade-integration/upgrade/upgrade-skr.js
  tests/fast-integration/skr-nightly/provision/provision-skr-nightly.js
  tests/fast-integration/skr-test/provision/deprovision-skr.js
  tests/fast-integration/skr-test/provision/provision-skr.js
Labels: size/S, lgtm

#16411 Bump qs, body-parser and express in /components/function-runtimes/nod…
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/package-lock.json
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/package.json
Labels: size/XL, lgtm

#16412 Bump express dependency to avoid CVE-2022-24999
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#16407 Update outdated docs
  docs/04-operation-guides/troubleshooting/eventing/evnt-04-free-jetstream-storage.md
Labels: area/documentation, area/eventing, size/S, lgtm

#15910 Enable Java function as alpha
  components/function-controller/cmd/webhook/main.go
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/go.mod
  components/function-controller/go.sum
  components/function-controller/internal/controllers/kubernetes/namespace_controller.go
  components/function-controller/internal/controllers/serverless/deployment_test.go
  components/function-controller/internal/controllers/serverless/runtime/java.go
  components/function-controller/internal/controllers/serverless/runtime/runtime.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/internal/webhook/config.go
  components/function-controller/internal/webhook/fixtures_test.go
  components/function-controller/internal/webhook/validating_webhook.go
  components/function-controller/internal/webhook/validating_webhook_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/runtime_validation.go
  components/function-runtimes/java17/Dockerfile-jvm-function-local
  components/function-runtimes/java17/Dockerfile-jvm-function.tpl
  resources/serverless/charts/webhook/templates/configmap.yaml
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/templates/runtimes.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#16353 Kyma OpenTelemetry Grafana Dashboard
  resources/telemetry/charts/operator/templates/configmap-opentelemetry-dashboard.yaml
Labels: size/XL, lgtm

#16298 improve epp metrics
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/handler/handler_test.go
  components/event-publisher-proxy/pkg/metrics/collector.go
  components/event-publisher-proxy/pkg/metrics/collector_test.go
  components/event-publisher-proxy/pkg/metrics/metricstest/metricstest.go
  resources/eventing/charts/dashboards/templates/delivery.yaml
  resources/eventing/charts/dashboards/templates/latency.yaml
  resources/eventing/values.yaml
  tests/fast-integration/eventing-test/metric-test.js
Labels: area/eventing, size/L, lgtm

#16400 add the doc for nats-server system_account credentials (#15381)
  docs/04-operation-guides/operations/evnt-03-nats-server-system-events.md
Labels: area/documentation, area/eventing, size/S, lgtm

#16396 Add system-account user to nats-server
  components/eventing-controller/api/v1alpha1/condition.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/backend/reconciler_internal_unit_test.go
  resources/eventing/charts/nats/templates/configmap.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#16419 Adjust docs to sidecar injection annotation deprecation
  docs/01-overview/main-areas/telemetry/telemetry-02-logs.md
  docs/04-operation-guides/operations/smsh-01-istio-enable-sidecar-injection.md
  docs/04-operation-guides/troubleshooting/service-mesh/smsh-03-istio-no-sidecar.md
Labels: size/S, lgtm

#16426 Move Java feature flag to deployment
  resources/serverless/charts/webhook/templates/configmap.yaml
  resources/serverless/charts/webhook/templates/deployment.yaml
Labels: size/XS, lgtm

#16143 Script copying secrets used by Application Connector to integration namespace
  docs/assets/2.9-2.10-OS-copy-secrets-to-system-namespace.sh
  docs/assets/2.9-2.10-SKR-copy-secrets-to-system-namespace.sh
  docs/migration-guide-2.9-2.10.md
Labels: area/application-connector, size/S, lgtm

#16428 Update java runtime jetty to newest
  components/function-runtimes/java17/examples/hello-world/pom.xml
  components/function-runtimes/java17/examples/hello-world/src/main/java/io/project/kyma/serverless/handler/Handler.java
  components/function-runtimes/java17/pom.xml
  components/function-runtimes/java17/serverless-java-sdk/pom.xml
  components/function-runtimes/java17/serverless-java-sdk/src/main/java/io/project/kyma/serverless/sdk/CloudEvent.java
  components/function-runtimes/java17/serverless-java-sdk/src/main/java/io/project/kyma/serverless/sdk/Function.java
  components/function-runtimes/java17/serverless-java-sdk/src/main/java/io/project/kyma/serverless/sdk/ResponseCloudEvent.java
  components/function-runtimes/java17/src/main/java/io/project/kyma/serverless/JerseyServer.java
  components/function-runtimes/java17/src/main/java/io/project/kyma/serverless/handler/Handler.java
  resources/serverless/values.yaml
  tests/function-controller/testsuite/runtimes/java.go
Labels: size/M, lgtm

#16427 fix broken epp metrics tests
  resources/eventing/values.yaml
  tests/fast-integration/eventing-test/nats-dashboard-queries.json
Labels: size/XS, lgtm

#16337 Bump prometheus to latest 2.40.7
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#16355 Distribute NATS Pods on Multiple Zones
  resources/eventing/charts/nats/values.yaml
Labels: size/XS, lgtm

#16422 Update eventing metrics docs
  docs/04-operation-guides/operations/evnt-02-eventing-metrics.md
Labels: area/eventing, size/S, lgtm

#16434 fix nats resolv.conf
  components/eventing-controller/controllers/backend/reconciler.go
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#16397 Implement update test
  tests/components/application-connector/Makefile.test-compass-runtime-agent
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/templates/applications/test-create-app.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/test/compass-runtime-agent/synchronisation_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/directorclient.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/queryprovider.go
Labels: size/M, lgtm

#16401 Support publishing cloud-events for Subscritpion v1alpha2 CRD in EPP
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/event-publisher-proxy/pkg/cloudevents/builder/eventmesh.go
  components/event-publisher-proxy/pkg/cloudevents/builder/eventmesh_test.go
  components/event-publisher-proxy/pkg/cloudevents/builder/generic.go
  components/event-publisher-proxy/pkg/cloudevents/builder/generic_test.go
  components/event-publisher-proxy/pkg/cloudevents/builder/types.go
  components/event-publisher-proxy/pkg/cloudevents/builder/utils.go
  components/event-publisher-proxy/pkg/cloudevents/builder/utils_test.go
  components/event-publisher-proxy/pkg/cloudevents/eventtype/parse.go
  components/event-publisher-proxy/pkg/cloudevents/eventtype/parse_test.go
  components/event-publisher-proxy/pkg/commander/beb/beb.go
  components/event-publisher-proxy/pkg/commander/nats/nats.go
  components/event-publisher-proxy/pkg/env/types.go
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/handler/handler_test.go
  components/event-publisher-proxy/pkg/handler/handler_v1alpha2_test.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream_test.go
  resources/eventing/values.yaml
Labels: size/XXL, lgtm

#16439 Update README.md
  resources/serverless/charts/docker-registry/README.md
Labels: size/M, lgtm

#16440 Update README.md
  resources/serverless/charts/k3s-tests/README.md
Labels: size/XS, lgtm

#16414 Change status code for not found in Validators cache
  components/central-application-connectivity-validator/internal/validationproxy/handler.go
  components/central-application-connectivity-validator/internal/validationproxy/handler_test.go
  resources/application-connector/values.yaml
Labels: area/application-connector, size/M, lgtm

#16441 Update README.md
  resources/serverless/charts/webhook/README.md
Labels: size/XS, lgtm

#16436 use github team to configure ownership on eventing components
  CODEOWNERS
Labels: area/eventing, size/S, lgtm

#16446 Change VERSION to 2.9.3
  VERSION
Labels: size/XS, lgtm

#16425 Add registry cache garbage collection for serverless
  components/function-controller/cmd/registry-gc/main.go
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/design/internal_registry_garbage_collection.md
  components/function-controller/go.mod
  components/function-controller/internal/registry/images.go
  components/function-controller/internal/registry/images_test.go
  components/function-controller/internal/registry/nested_set.go
  components/function-controller/internal/registry/nested_set_test.go
  components/function-controller/internal/registry/registry.go
  components/function-controller/internal/registry/registry_test.go
  components/function-controller/internal/registry/repository.go
  resources/serverless/values.yaml
Labels: kind/feature, area/serverless, size/L, lgtm

#16432 Check for b3 headers if the traceparent is not present in headers
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/package.json
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/utils/index.js
Labels: size/M, lgtm

#16024 Change Application Connector secret namespace to kyma-system
  components/central-application-connectivity-validator/README.md
  components/central-application-connectivity-validator/internal/validationproxy/handler_test.go
  components/central-application-gateway/README.md
  components/central-application-gateway/cmd/applicationgateway/options.go
  components/compass-runtime-agent/cmd/options.go
  components/compass-runtime-agent/cmd/options_test.go
  components/compass-runtime-agent/internal/certificates/manager_test.go
  components/compass-runtime-agent/internal/secrets/repository_test.go
  docs/03-tutorials/00-application-connectivity/ac-03-register-manage-services.md
  docs/03-tutorials/00-application-connectivity/ac-04-register-secured-api.md
  installation/resources/components.yaml
  resources/application-connector/charts/central-application-gateway/templates/deployment.yaml
  resources/application-connector/templates/cluster-role-binding.yaml
  resources/application-connector/templates/helm-secret.yaml
  resources/application-connector/templates/limit-range.yaml
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/templates/integration-namespace.yaml
  resources/compass-runtime-agent/templates/resources-role-binding.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/basic-auth-negative.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/basic-auth-positive.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-negative-case.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-negative-expired-client-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-negative-expired-server-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-negative-other-ca.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-oauth-nagative-incorrect-clientid.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-oauth-nagative-other-ca.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-oauth-negative-case.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-oauth-negative-expired-client-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-oauth-negative-expired-server-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-oauth-positive.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/mtls-positive.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/oauth-negative-incorrect-id.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/oauth-negative-invalid-token.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/oauth-positive.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/redirect-basic-auth.yml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/request-parameters-negative.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/request-parameters.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
  tests/components/application-connector/resources/installation-config/mini-kyma-os.yaml
  tests/components/application-connector/resources/installation-config/mini-kyma-skr.yaml
  tests/components/application-connector/test/compass-runtime-agent/config.go
  tests/components/application-connector/test/compass-runtime-agent/suite_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/secretcomparator_test.go
  tests/fast-integration/test/fixtures/commerce-mock/application.yaml
Labels: area/application-connector, size/L, lgtm

#16449 Fixed Eventing FI tests for Subscription v1alpha2 CRD
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
Labels: size/M, lgtm

#16451 Update api-gateway crd in eventing tests
  components/eventing-controller/config/crd/external/apirules-gateway-kyma-project-io.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/S, lgtm

#16413 Ensure single trace pipeline
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/apis/telemetry/v1alpha1/tracepipeline_types.go
  components/telemetry-operator/controller/logparser/status.go
  components/telemetry-operator/controller/logparser/status_test.go
  components/telemetry-operator/controller/logpipeline/status.go
  components/telemetry-operator/controller/logpipeline/status_test.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/status.go
  components/telemetry-operator/controller/tracepipeline/status_test.go
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/helpers.js
  tests/fast-integration/telemetry-test/suite.js
  tests/fast-integration/telemetry-test/testdata/tracepipeline-output-otlp-secret-ref-1.yaml
  tests/fast-integration/telemetry-test/testdata/tracepipeline-output-otlp-secret-ref-2.yaml
Labels: size/L, lgtm

#16456 Update dependencies in eventing 2022 dec 29
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/M, lgtm

#16457 Add generic ArgumentError
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/errors/errors.go
  components/eventing-controller/pkg/errors/errors_internal_unit_test.go
  components/eventing-controller/pkg/errors/errors_unit_test.go
  components/eventing-controller/utils/errors.go
  components/eventing-controller/utils/utils.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#16464 Fix No-Content response from nodejs16 runtime
  components/function-runtimes/nodejs16/lib/helper.js
  components/function-runtimes/nodejs16/server.js
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/XS, lgtm

#16448 Revert java
  components/function-controller/cmd/webhook/main.go
  components/function-controller/go.mod
  components/function-controller/internal/controllers/serverless/runtime/java.go
  components/function-controller/internal/controllers/serverless/runtime/runtime.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/internal/webhook/config.go
  components/function-controller/internal/webhook/validating_webhook.go
  components/function-controller/internal/webhook/validating_webhook_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/runtime_validation.go
  resources/serverless/charts/webhook/templates/deployment.yaml
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/templates/runtimes.yaml
  resources/serverless/values.yaml
  tests/function-controller/go.mod
  tests/function-controller/go.sum
  tests/function-controller/testsuite/runtimes/java.go
  tests/function-controller/testsuite/scenarios/light_runtimes.go
Labels: size/L, lgtm

#16460 Add cloudevent client and factory
  components/eventing-controller/pkg/cloudevent/client.go
  components/eventing-controller/pkg/cloudevent/client_unit_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#16466 rename `beb` to `eventmesh` in epp/pkg/sender
  components/event-publisher-proxy/pkg/commander/beb/beb.go
  components/event-publisher-proxy/pkg/handler/handler_test.go
  components/event-publisher-proxy/pkg/handler/handler_v1alpha2_test.go
  components/event-publisher-proxy/pkg/sender/eventmesh/eventmesh.go
  components/event-publisher-proxy/pkg/sender/eventmesh/eventmesh_test.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#16433 Support publishing legacy-events for Subscritpion v1alpha2 CRD in EPP
  components/event-publisher-proxy/pkg/commander/beb/beb.go
  components/event-publisher-proxy/pkg/commander/nats/nats.go
  components/event-publisher-proxy/pkg/env/types.go
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/handler/handler_test.go
  components/event-publisher-proxy/pkg/handler/handler_v1alpha2_test.go
  components/event-publisher-proxy/pkg/legacy/api/types.go
  components/event-publisher-proxy/pkg/legacy/helpers.go
  components/event-publisher-proxy/pkg/legacy/legacy.go
  components/event-publisher-proxy/pkg/legacy/legacy_test.go
  components/event-publisher-proxy/pkg/legacy/legacytest/test.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream_test.go
  components/event-publisher-proxy/testing/fixtures.go
  resources/eventing/values.yaml
Labels: size/XL, lgtm

#16471 Fix Serverless registry-gc failure on NotFound tags
  components/function-controller/cmd/registry-gc/main.go
  components/function-controller/internal/registry/registry.go
  components/function-controller/internal/registry/registry_test.go
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/L, lgtm

#16461 Fixed Eventing FI tests legacy events in Subscription v1alpha2 CRD
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
Labels: size/M, lgtm

#16459 Add KLogger interface
  components/eventing-controller/logger/logger.go
  components/eventing-controller/logger/logger_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#16472 Change `BEB` to `EventMesh` in `epp/pkg/env`
  components/event-publisher-proxy/pkg/commander/beb/beb.go
  components/event-publisher-proxy/pkg/commander/nats/nats.go
  components/event-publisher-proxy/pkg/env/eventmesh_config.go
  components/event-publisher-proxy/pkg/env/eventmesh_config_test.go
  components/event-publisher-proxy/pkg/env/nats_config.go
  components/event-publisher-proxy/pkg/oauth/client.go
  components/event-publisher-proxy/pkg/oauth/client_test.go
  components/event-publisher-proxy/pkg/oauth/config.go
  components/event-publisher-proxy/pkg/oauth/config_test.go
  components/event-publisher-proxy/pkg/sender/eventmesh/eventmesh_test.go
  components/event-publisher-proxy/testing/env_config.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#16475 Fix Serverless registry-gc race condition
  components/function-controller/cmd/registry-gc/main.go
  components/function-controller/internal/registry/utils.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types_test.go
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/L, lgtm

#16468 Reorganise nats config and nats backend import paths
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/test_utils.go
  components/eventing-controller/controllers/subscriptionv2/reconcilertesting/jetstream_matchers.go
  components/eventing-controller/pkg/backend/jetstreamv2/config.go
  components/eventing-controller/pkg/backend/jetstreamv2/config_internal_unit_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/errors.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/test_helpers.go
  components/eventing-controller/pkg/backend/jetstreamv2/types.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils_unit_test.go
  components/eventing-controller/pkg/backend/nats/config.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_integration_test.go
  components/eventing-controller/pkg/deployment/publisher_deployment.go
  components/eventing-controller/pkg/deployment/publisher_deployment_integration_test.go
  components/eventing-controller/pkg/object/equality_test.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream_test.go
  components/eventing-controller/testing/nats/matchers.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm
