Repository kyma-project/kyma, pull requests merged in 2022-10, with the labels that each got.

#15691 update to node-exporter 1.4.0
  resources/monitoring/charts/prometheus-istio/values.yaml
  resources/monitoring/charts/prometheus-node-exporter/Chart.yaml
  resources/monitoring/values.yaml
Labels: area/monitoring, size/XS, lgtm

#15696 fixed broken rendering of telemetry docs
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: size/XS, lgtm

#15649 Added EventMesh reconciler for Subscription v1alpha2 CRD
  components/eventing-controller/api/v1alpha2/condition.go
  components/eventing-controller/api/v1alpha2/condition_unit_test.go
  components/eventing-controller/config/crd/kustomization.yaml
  components/eventing-controller/config/samples/eventing_v1alpha2_exact_eventmesh.yaml
  components/eventing-controller/config/samples/eventing_v1alpha2_standard.yaml
  components/eventing-controller/controllers/subscriptionv2/beb/reconciler.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/reconciler.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/utils.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/utils_test.go
  components/eventing-controller/pkg/backend/eventmesh/mocks/Backend.go
  components/eventing-controller/pkg/object/apirule.go
  components/eventing-controller/pkg/object/v2/apirule.go
  components/eventing-controller/pkg/object/v2/equality.go
  components/eventing-controller/pkg/object/v2/equality_test.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb_test.go
  components/eventing-controller/testing/v2/matchers.go
  components/eventing-controller/testing/v2/test_helpers.go
  resources/eventing/values.yaml
Labels: area/eventing, size/XXL, lgtm

#15711 Move Dockerfile of `event-publisher-proxy` to base dir
  components/event-publisher-proxy/Dockerfile
  components/event-publisher-proxy/Makefile
  resources/eventing/values.yaml
Labels: size/M, lgtm

#15607 Adding test for secret references
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/suite.js
  tests/fast-integration/telemetry-test/testdata/logpipeline-output-custom.yaml
Labels: size/M, lgtm

#15712 Bump dependencies `eventing-controller`
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/L, lgtm

#15710 Gateway redirects component tests
  tests/components/application-connector/Makefile.test-application-gateway
  tests/components/application-connector/internal/testkit/test-api/apis.go
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/credentials/redirect-basic-auth.yml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/redirect.yml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
  tests/components/application-connector/test/application-gateway/runner_test.go
Labels: size/M, lgtm

#15721 Add huskies team member
  CODEOWNERS
Labels: size/S, lgtm

#15692 update to fluent bit 1.9.9
  components/telemetry-operator/Dockerfile
  resources/logging/values.yaml
  resources/telemetry/values.yaml
Labels: area/logging, size/XS, lgtm

#15726 Add New Code Owner
  CODEOWNERS
Labels: size/S, lgtm

#15673 Propagate maxInFlight config changes to the consumer
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_integration_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#15735 Update expat library to 2.4.9
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/python39/Dockerfile
Labels: size/L, lgtm

#15671 Use OPTL exporters in serverless function runtimes
  components/function-controller/internal/controllers/serverless/config.go
  components/function-controller/internal/controllers/serverless/deployment.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/kubeless.js
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/lib/tracer.js
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/package.json
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/kubeless.js
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/lib/tracer.js
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/package-lock.json
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/package.json
  components/function-runtimes/nodejs16/lib/tracer.js
  components/function-runtimes/nodejs16/package.json
  components/function-runtimes/python39/Dockerfile
  components/function-runtimes/python39/kubeless/kubeless.py
  components/function-runtimes/python39/kubeless/requirements.txt
  components/function-runtimes/python39/kubeless/tracing.py
  docs/05-technical-reference/00-configuration-parameters/svls-02-environment-variables.md
  milv.config.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/values.yaml
Labels: area/serverless, area/tracing, size/XXL, lgtm

#15748 Bump docker registry
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15749 Change templates in validateLabels and change tests to match function
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  resources/serverless/values.yaml
Labels: size/S, lgtm

#15738 Remove sleep as it is not required
  tests/fast-integration/utils/index.js
Labels: area/eventing, size/XS, lgtm

#15750 Add a section on Response rewriting to Application Gateway details
  components/central-application-gateway/README.md
  docs/01-overview/main-areas/application-connectivity/ac-02-application-gateway.md
  docs/05-technical-reference/ac-01-application-gateway-details.md
Labels: area/documentation, area/application-connector, hacktoberfest-accepted, size/S, lgtm

#15757 Bump AC images
  resources/application-connector/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/XS, lgtm

#15759 Bump registry
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15713 bump dependencies in `event-publisher-proxy`
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  resources/eventing/values.yaml
Labels: size/M, lgtm

#15761 Bump dependencies
  components/function-controller/go.mod
  components/function-controller/go.sum
  components/function-runtimes/nodejs14/Dockerfile
  resources/serverless/values.yaml
Labels: size/S, lgtm

#15714 delete minor unreachable code caused by log.Fatal
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
  tests/components/application-connector/tools/external-api-mock-app/server.go
Labels: size/XS, lgtm

#15773 Fix a broken link to documentation on Kubernetes operators
  components/README.md
Labels: kind/bug, area/documentation, size/S, lgtm

#15707 Add Kiali deprecation and link to example
  docs/01-overview/main-areas/assets/kyma-areas.svg
  docs/01-overview/main-areas/observability/README.md
  docs/01-overview/main-areas/observability/obsv-10-useful-links.md
  docs/01-overview/main-areas/service-mesh/smsh-02-default-istio-setup-in-kyma.md
  docs/01-overview/main-areas/service-mesh/smsh-03-istio-sidecars-in-kyma.md
  docs/02-get-started/05-observability.md
  docs/03-tutorials/00-observability/obsv-02-create-and-configure-grafana-dashboard.md
  docs/03-tutorials/00-serverless/svls-12-customize-function-traces.md
  docs/04-operation-guides/operations/evnt-01-eventing-dashboards.md
  docs/04-operation-guides/security/sec-06-access-expose-grafana.md
  docs/04-operation-guides/security/sec-06-access-expose-kiali-grafana.md
  docs/05-technical-reference/00-architecture/obsv-01-architecture-monitoring.md
  docs/05-technical-reference/00-architecture/obsv-02-architecture-logging.md
  docs/05-technical-reference/00-architecture/obsv-03-architecture-tracing.md
  docs/05-technical-reference/00-architecture/obsv-04-architecture-kiali.md
  docs/05-technical-reference/00-configuration-parameters/obsv-01-configpara-observability.md
  resources/kiali/values.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/tracing/values.yaml
Labels: size/L, lgtm

#15717 Align status codes for errors in Application Gateway
  components/central-application-gateway/cmd/applicationgateway/applicationproxy.go
  components/central-application-gateway/internal/metadata/applications/repository.go
  components/central-application-gateway/internal/proxy/factory_test.go
  components/central-application-gateway/internal/proxy/proxy.go
  components/central-application-gateway/internal/proxy/reverseproxy.go
  resources/application-connector/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/missing-resources-error-handling.yml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/path-related-error-handling.yml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/proxy-errors.yml
  tests/components/application-connector/resources/installation-config/mini-kyma-os.yaml
Labels: area/application-connector, hacktoberfest-accepted, size/M, lgtm

#15778 Revert logLevel overrides for profiles files
  resources/serverless/profile-evaluation.yaml
  resources/serverless/profile-production.yaml
Labels: area/serverless, size/XS, lgtm, kind/cleanup

#15576 Fix conflicting Serverless scaling options
  components/function-controller/design/scaling_functions.md
  components/function-controller/internal/controllers/serverless/deployment.go
  components/function-controller/internal/controllers/serverless/deployment_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_asserts_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/scaling.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/internal/webhook/defaulting_webhook.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  resources/serverless/values.yaml
  tests/function-controller/go.mod
  tests/function-controller/go.sum
  tests/function-controller/testsuite/teststep/check.go
Labels: kind/bug, area/serverless, size/L, lgtm

#15694 Multiple path test
  tests/components/api-gateway/features/service_per_path.feature
  tests/components/api-gateway/main_test.go
  tests/components/api-gateway/manifests/two-services-deployment.yaml
  tests/components/api-gateway/manifests/two-services.yaml
  tests/components/api-gateway/pkg/helpers/helpers.go
  tests/components/api-gateway/pkg/jwt/idtokenprovider.go
  tests/components/api-gateway/service_override_test.go
  tests/components/api-gateway/service_per_path_test.go
  tests/components/api-gateway/test_helpers.go
Labels: area/api-gateway, size/L, lgtm, area/tests

#15781 Correcting input param name
  docs/03-tutorials/00-service-management/smgt-01-deploy-service.md
Labels: area/documentation, area/service-management, size/XS, lgtm

#15782 Fix a broken link to the Grafana documentation on gauge
  docs/03-tutorials/00-observability/obsv-02-create-and-configure-grafana-dashboard.md
Labels: kind/bug, area/documentation, size/XS, lgtm

#15784 Add istio/install-cni to values, required for protecode scans
  resources/istio/values.yaml
Labels: size/XS, lgtm

#15780 Application Gateway readme update regarding new error codes
  components/central-application-gateway/README.md
Labels: area/documentation, area/application-connector, hacktoberfest, hacktoberfest-accepted, size/XS, lgtm

#15767 Fix logged stateFn name
  components/function-controller/internal/controllers/serverless/fsm.go
  components/function-controller/internal/controllers/serverless/fsm_test.go
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/S, lgtm, kind/cleanup

#15776 remove merging resource presets and custom settings
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  resources/serverless/values.yaml
  tests/function-controller/go.mod
  tests/function-controller/go.sum
Labels: size/L, lgtm

#15716 Setup mTLS gateway and access exposed workload with certificate tutorials
  docs/03-tutorials/00-api-exposure/apix-10-expose-and-secure-workload-with-certificate.md
  docs/03-tutorials/00-security/metadata.yaml
  docs/03-tutorials/00-security/sec-01-tls-certificates-security.md
  docs/03-tutorials/00-security/sec-02-mtls-selfsign-client-certicate.md
  docs/03-tutorials/00-security/sec-03-setup-mtls-gateway.md
  docs/03-tutorials/00-security/sec-04-set-up-idp.md
  docs/04-operation-guides/security/sec-04-ingress-egress-traffic.md
  docs/04-operation-guides/security/sec-07-useful-links.md
  docs/04-operation-guides/troubleshooting/service-mesh/smsh-01-503-no-access.md
Labels: size/L, lgtm

#15783 add conversion from and to v1alpha2 using Templates..Resources
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#15807 Increase Fluent Bit memory limit
  resources/telemetry/profile-production.yaml
Labels: size/XS, lgtm

#15808 Update application-connector docker images to latest versions built on main for release 2.8
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: size/S, lgtm

#15806 [Telemetry Operator] - Bump k8s client dependencies
  components/telemetry-operator/go.mod
  components/telemetry-operator/go.sum
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15805 Revert api templating
  components/function-controller/adr/2022-10-v1alpha2-templating.txt
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/zz_generated.deepcopy.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/values.yaml
Labels: size/XXL, lgtm

#15811 [Telemetry Operator] - Bump image
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#15812 update kiwigrid sidecar to newer python version
  resources/monitoring/values.yaml
Labels: area/monitoring, size/XS, lgtm

#15792 Bring back jaegerServiceEndpoint ENV for backward compatibility
  components/function-controller/internal/controllers/serverless/config.go
  components/function-controller/internal/controllers/serverless/deployment.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/controllers/serverless/utils.go
  docs/05-technical-reference/00-configuration-parameters/svls-02-environment-variables.md
  milv.config.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, area/tracing, size/S, lgtm

#15821 Fix scale conversion for Serverless v1alpha1
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  resources/serverless/values.yaml
Labels: size/M, lgtm

#15822 Release readiness for serverless image tags
  resources/serverless/values.yaml
Labels: size/S, lgtm

#15733 bump build image in Dockerfile to golang1.19.2-alpine3.16 in eventing-controller
  components/eventing-controller/Dockerfile
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#15734 bump build image in Dockerfile to golang1.19.2-alpine3.16 in event-publisher-proxy
  components/event-publisher-proxy/Dockerfile
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#15727 bump nats server
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#15744 Disable PSP and configure securityContext properly for observability pods
  resources/kiali/templates/deployment.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/kiali/values.yaml
  resources/logging/charts/loki/templates/statefulset.yaml
  resources/logging/charts/loki/values.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/grafana/values.yaml
  resources/monitoring/charts/kube-state-metrics/values.yaml
  resources/monitoring/charts/prometheus-istio/values.yaml
  resources/monitoring/charts/prometheus-node-exporter/values.yaml
  resources/monitoring/charts/prometheus-pushgateway/values.yaml
  resources/monitoring/values.yaml
  resources/telemetry/charts/fluent-bit/values.yaml
  resources/telemetry/charts/operator/values.yaml
  resources/tracing/templates/deployment.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/values.yaml
Labels: size/L, lgtm

#15843 [Telemetry Operator] - CVE-2022-32149 Fix
  components/telemetry-operator/go.mod
  components/telemetry-operator/go.sum
Labels: size/S, lgtm

#15835 Remove logging Fluent Bit
  docs/05-technical-reference/00-configuration-parameters/obsv-01-configpara-observability.md
  resources/logging/Chart.yaml
  resources/logging/charts/fluent-bit/Chart.yaml
  resources/logging/charts/fluent-bit/templates/_helpers.tpl
  resources/logging/charts/fluent-bit/templates/_pod.tpl
  resources/logging/charts/fluent-bit/templates/clusterrole.yaml
  resources/logging/charts/fluent-bit/templates/clusterrolebinding.yaml
  resources/logging/charts/fluent-bit/templates/configmap.yaml
  resources/logging/charts/fluent-bit/templates/daemonset.yaml
  resources/logging/charts/fluent-bit/templates/deployment.yaml
  resources/logging/charts/fluent-bit/templates/kyma-additions/_parsers.tpl
  resources/logging/charts/fluent-bit/templates/kyma-additions/fluent-bit.rules.yaml
  resources/logging/charts/fluent-bit/templates/kyma-additions/grafana-dashboard.yaml
  resources/logging/charts/fluent-bit/templates/kyma-additions/peerauthentication.yaml
  resources/logging/charts/fluent-bit/templates/kyma-additions/secrets.yaml
  resources/logging/charts/fluent-bit/templates/kyma-additions/serviceentry.yaml
  resources/logging/charts/fluent-bit/templates/psp.yaml
  resources/logging/charts/fluent-bit/templates/service.yaml
  resources/logging/charts/fluent-bit/templates/serviceaccount.yaml
  resources/logging/charts/fluent-bit/templates/servicemonitor.yaml
  resources/logging/charts/fluent-bit/values.yaml
  resources/logging/charts/loki/templates/kyma-additions/authorizationpolicy.yaml
  resources/logging/charts/loki/templates/kyma-additions/logpipeline_loki.yaml
  resources/logging/profile-evaluation.yaml
  resources/logging/profile-production.yaml
  resources/logging/values.yaml
  tests/fast-integration/monitoring/prometheus.js
Labels: area/logging, size/XXL, lgtm

#15846 Update nats server (#15727)
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#15844 Update nats server (#15727)
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#15746 Dynamic logging for the serverless webhook
  components/function-controller/cmd/manager/main.go
  components/function-controller/cmd/webhook/main.go
  components/function-controller/internal/logging/dynamic.go
  components/function-controller/internal/logging/registry.go
  components/function-controller/internal/webhook/resources/certificates.go
  components/function-controller/internal/webhook/resources/resources.go
  resources/serverless/charts/webhook/templates/configmap.yaml
  resources/serverless/charts/webhook/templates/deployment.yaml
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/templates/configmap.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/L, lgtm

#15769 add wait for jaeger pods in FIT
  tests/fast-integration/eventing-test/common/common.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/monitoring/grafana.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#15608 Use the configured NATS URL as the destination service value for the Eventing publisher proxy custom metrics
  components/event-publisher-proxy/pkg/env/nats_config.go
  components/event-publisher-proxy/pkg/sender/jetstream.go
  components/eventing-controller/pkg/deployment/publisher_deployment.go
  components/eventing-controller/pkg/deployment/publisher_deployment_integration_test.go
  components/eventing-controller/pkg/env/nats_config.go
  components/eventing-controller/pkg/env/nats_config_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/S, lgtm

#15786 Remove knative leftovers from serverless webhook
  resources/serverless/charts/webhook/templates/deployment.yaml
  resources/serverless/charts/webhook/values.yaml
Labels: size/S, lgtm, kind/cleanup

#15791 Removed @hanngos from Codeowners
  CODEOWNERS
Labels: size/S, lgtm

#15762 Improve consumer logic, add unit tests
  components/eventing-controller/.golangci.yaml
  components/eventing-controller/api/v1alpha2/subscription_types.go
  components/eventing-controller/api/v1alpha2/subscription_types_test.go
  components/eventing-controller/controllers/backend/reconciler_internal_unit_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_test.go
  components/eventing-controller/pkg/backend/beb/mocks/Backend.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_internal_unit_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/mocks/JetStreamBackend.go
  components/eventing-controller/pkg/backend/jetstreamv2/mocks/JetStreamContext.go
  components/eventing-controller/pkg/backend/jetstreamv2/stubs_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/test_helpers.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils_unit_test.go
  components/eventing-controller/pkg/backend/mocks/BEBBackend.go
  components/eventing-controller/pkg/backend/mocks/NatsBackend.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_integration_test.go
  components/eventing-controller/pkg/backend/utils/v2/utils.go
  components/eventing-controller/pkg/env/nats_config.go
  components/eventing-controller/pkg/errors/errors.go
  resources/eventing/values.yaml
Labels: size/XXL, lgtm

#15390 Prepare code initializing Compass Runtime Agent before Compass Runtime Agent runs
  tests/components/application-connector/Makefile.test-compass-runtime-agent
  tests/components/application-connector/go.mod
  tests/components/application-connector/go.sum
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/templates/applications/test-create-app.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/templates/service-account.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/test/compass-runtime-agent/config.go
  tests/components/application-connector/test/compass-runtime-agent/suite_test.go
  tests/components/application-connector/test/compass-runtime-agent/synchronisation_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/comparator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/comparator_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/directorclient.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/directorclient_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/mocks/Client.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/mocks/DirectorClient.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/model.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/queryprovider.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/certificatesecrets_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/certificatessecrets.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/compass.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/compass_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/compassconnection.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/compassconnection_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/configurationsecret.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/configurationsecret_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/deployment.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/init.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/init_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/CertificateSecretConfigurator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/CompassConfigurator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/CompassConnectionConfigurator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/ConfigurationSecretConfigurator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/DeploymentConfigurator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/DirectorClient.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/types.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/random/randomstring.go
Labels: area/application-connector, size/XXL, lgtm, area/tests

#15857 updated observability images to newest golang version
  components/telemetry-operator/Dockerfile
  resources/kiali/values.yaml
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/telemetry/values.yaml
  resources/tracing/values.yaml
Labels: size/S, lgtm

#15841 Refactor error managment in Serverless FSM.
  components/function-controller/internal/controllers/serverless/configmap.go
  components/function-controller/internal/controllers/serverless/deployment.go
  components/function-controller/internal/controllers/serverless/fsm.go
  components/function-controller/internal/controllers/serverless/fsm_test.go
  components/function-controller/internal/controllers/serverless/job.go
  components/function-controller/internal/controllers/serverless/scaling.go
  components/function-controller/internal/controllers/serverless/service.go
  components/function-controller/internal/controllers/serverless/service_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#15860 update golang version for directory-size-exporter
  components/directory-size-exporter/Dockerfile
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#14862 update kyma codeowners
  CODEOWNERS
Labels: size/M, lgtm

#15643 Add exponential buckets for the Event publisher proxy latency histogram
  components/event-publisher-proxy/Makefile
  components/event-publisher-proxy/cmd/event-publisher-proxy/main.go
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/event-publisher-proxy/pkg/handler/beb/mock/mock.go
  components/event-publisher-proxy/pkg/handler/nats/mock/mock.go
  components/event-publisher-proxy/pkg/metrics/collector.go
  components/event-publisher-proxy/pkg/metrics/collector_test.go
  components/event-publisher-proxy/pkg/metrics/histogram/buckets.go
  components/event-publisher-proxy/pkg/metrics/histogram/mocks/BucketsProvider.go
  components/event-publisher-proxy/pkg/metrics/latency/latency.go
  components/event-publisher-proxy/pkg/metrics/latency/latency_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#15866 Bump pod preset to "0c2fc208" (#15855)
  resources/cluster-essentials/values.yaml
Labels: size/XS, lgtm

#15867 Bump pod preset to "0c2fc208" (#15855)
  resources/cluster-essentials/values.yaml
Labels: size/XS, lgtm

#14514 Use nodejs16 in fast-integration tests
  tests/fast-integration/monitoring/prometheus.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
Labels: size/XS, lgtm

#15868 Add one more useful debug log for the `function-controller`
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm, kind/cleanup

#15850 Enhance telemetry component README
  components/telemetry-operator/README.md
Labels: size/M, lgtm

#15885 Restore jetstreamEnabled flag for 2.8.x releases to prevent eventing issues
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#15896 Automate patching subscription CRD when new version is enabled
  components/eventing-controller/Makefile
  components/eventing-controller/config/crd/kustomization.yaml
  components/eventing-controller/config/crd/kustomizeconfig.yaml
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
Labels: area/eventing, size/M, lgtm

#15898 fix broken links
  components/eventing-controller/README.md
  tests/serverless-bench/README.md
Labels: size/M, lgtm

#15895 Removed gomega matchers from eventmesh reconciler internal tests
  components/eventing-controller/controllers/subscriptionv2/eventmesh/reconciler_internal_integration_test.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#15879 Adjusted tutorial based on additional comments in #15716
  docs/03-tutorials/00-api-exposure/apix-02-setup-custom-domain-for-workload.md
  docs/03-tutorials/00-api-exposure/apix-10-expose-and-secure-workload-with-certificate.md
  docs/03-tutorials/00-security/sec-02-mtls-selfsign-client-certicate.md
  docs/04-operation-guides/security/sec-07-useful-links.md
Labels: size/S, lgtm

#15908 Update EPP dependencies.
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#15909 Remove myself from owners
  CODEOWNERS
Labels: size/S, lgtm

#15903 Use golang 1.19.2 in serverless
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  resources/serverless/values.yaml
Labels: size/S, lgtm

#15886 Support basic auth for OTLP output in TracePipeline
  components/telemetry-operator/apis/telemetry/v1alpha1/tracepipeline_types.go
  components/telemetry-operator/apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_tracepipeline_jaeger.yaml
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/controller_test.go
  components/telemetry-operator/controller/tracepipeline/resources.go
  components/telemetry-operator/controller/tracepipeline/resources_test.go
  components/telemetry-operator/controller/tracepipeline/utils.go
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15876 Add missing timeout when notifying health channel
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  components/function-controller/internal/controllers/serverless/function_reconcile_health_test.go
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/M, lgtm

#15902 Add additional columns when listing API Rules on the cluster
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
Labels: size/S, lgtm

#15913 Bump tpi in serverless
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15918 Remove myself from compass agent
  CODEOWNERS
Labels: size/XS, lgtm

#15926 Add note about zero-downtime upgrades
  docs/04-operation-guides/operations/05-upgrade-kyma.md
Labels: area/documentation, size/S, lgtm

#15906 remove v1 to v2 status conversion and pretty print cleaneventtypes
  components/eventing-controller/api/v1alpha1/subscription_conversion.go
  components/eventing-controller/api/v1alpha1/subscription_conversion_unit_test.go
  components/eventing-controller/api/v1alpha2/subscription_types.go
  components/eventing-controller/config/crd/basesv1alpha2/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/config/samples/eventing_v1alpha2_subscription.yaml
  components/eventing-controller/controllers/subscriptionv2/jetstream/errors.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler_internal_unit_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/utils.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/utils_unit_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/testing/test_helpers.go
  components/eventing-controller/testing/v2/test_helpers.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#15929 removed global kyma PSPs
  resources/cluster-essentials/templates/psp-privileged.yaml
  resources/cluster-essentials/templates/psp-unprivileged.yaml
  resources/cluster-essentials/templates/rbac-clusterrole.yaml
  resources/cluster-essentials/templates/rbac-clusterrolebinding.yaml
  resources/cluster-essentials/values.yaml
Labels: size/L, lgtm

#15917 Check for empty segments in event type in EPP
  components/event-publisher-proxy/pkg/cloudevents/eventtype/parse.go
  components/event-publisher-proxy/pkg/cloudevents/eventtype/parse_test.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#15927 Use API GW Cert Handler Image
  components/eventing-controller/config/certmanager/certificate.yaml
  components/eventing-controller/config/certmanager/kustomization.yaml
  components/eventing-controller/config/certmanager/kustomizeconfig.yaml
  components/eventing-controller/config/helm/kustomization.yaml
  resources/eventing/charts/controller/templates/certmanager.yaml
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/templates/webhook-cert-handler.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/values.yaml
Labels: size/L, lgtm

#15935 Add support for secret references to TracePipeline
  components/telemetry-operator/controller/logpipeline/sync.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/controller_test.go
  components/telemetry-operator/controller/tracepipeline/resources.go
  components/telemetry-operator/controller/tracepipeline/resources_test.go
  components/telemetry-operator/controller/tracepipeline/secret_refs.go
  components/telemetry-operator/controller/tracepipeline/secret_refs_test.go
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15947 Serverless picks
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/python39/Dockerfile
  resources/serverless/values.yaml
Labels: size/S, lgtm

#15933 Rebuild python and set specific version
  components/function-runtimes/python39/Dockerfile
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15873 Fixing incorrect tls handshake error logging
  components/telemetry-operator/go.mod
  components/telemetry-operator/internal/logger/logger.go
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#15949 Remove the `nodejs12` component
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs12/docker-entrypoint.sh
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/.gitignore
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/kubeless.js
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/lib/ce.js
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/lib/helper.js
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/lib/tracer.js
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/package-lock.json
  components/function-runtimes/nodejs12/kubeless/kubeless_rt/package.json
Labels: area/serverless, size/XXL, lgtm, kind/cleanup

#15959 Istio 1.15.3
  resources/istio-resources/files/dashboards/control-plane.json
  resources/istio-resources/files/dashboards/mesh.json
  resources/istio-resources/files/dashboards/performance.json
  resources/istio-resources/files/dashboards/service.json
  resources/istio-resources/files/dashboards/workload.json
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: area/service-mesh, size/S, lgtm

#15954 bump build image in Dockerfile to golang1.19.2-alpine3.16
  components/event-publisher-proxy/Dockerfile
  components/eventing-controller/Dockerfile
Labels: size/XS, lgtm

#15953 cherry pick golang bump
  components/event-publisher-proxy/Dockerfile
  components/event-publisher-proxy/Makefile
  components/eventing-controller/Dockerfile
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
Labels: size/M, lgtm

#15962 Bump eventing images
  resources/eventing/values.yaml
Labels: size/XS, lgtm
