Repository kyma-project/kyma, pull requests merged in 2022-08, with the labels that each got.

#14936 Add custom metrics to epp
  components/event-publisher-proxy/pkg/handler/beb/handler.go
  components/event-publisher-proxy/pkg/handler/nats/handler.go
  components/event-publisher-proxy/pkg/metrics/collector.go
  components/event-publisher-proxy/pkg/sender/jetstream.go
  components/event-publisher-proxy/pkg/sender/nats.go
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#14973 Change default URI for Fluent Bit HTTP output
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/fluentbit/config_builder_test.go
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#14927 Lua de-dotting filter
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline_http.yaml
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/fluentbit/config_builder_test.go
  components/telemetry-operator/internal/validation/parser_validator.go
  components/telemetry-operator/internal/validation/plugin_validator.go
  installation/resources/crds/telemetry/logpipelines.crd.yaml
  resources/telemetry/charts/fluent-bit/values.yaml
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#14986 Change VERSION to 2.5.0
  VERSION
Labels: size/XS, lgtm

#14987 Update version of controller-gen in README
  components/function-controller/README.md
Labels: size/XS, lgtm

#14989 add min Docker resources
  docs/02-get-started/README.md
  docs/04-operation-guides/operations/02-install-kyma.md
Labels: area/documentation, size/XS, lgtm

#14966 Fix git ssh validation
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  resources/serverless/values.yaml
Labels: size/M, lgtm

#14981 Fix failing upgrade fast-integration tests
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/index.js
  tests/fast-integration/test/fixtures/getting-started-guide/xf-mocks.yaml
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#14997 fix link to upgrade sidecar proxy troubleshooting
  docs/01-overview/main-areas/service-mesh/smsh-03-istio-sidecars-in-kyma.md
Labels: size/XS, lgtm

#14934 Telemetry input section
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline_input.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline_input_excludes.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline_input_includes.yaml
  components/telemetry-operator/controllers/telemetry/logpipeline_controller.go
  components/telemetry-operator/controllers/telemetry/logpipeline_controller_test.go
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/fluentbit/config_builder_test.go
  components/telemetry-operator/internal/fluentbit/rewrite_tag.go
  components/telemetry-operator/internal/fluentbit/rewrite_tag_test.go
  components/telemetry-operator/internal/fluentbit/utils.go
  components/telemetry-operator/internal/sync/sync.go
  components/telemetry-operator/internal/validation/input_validator.go
  components/telemetry-operator/internal/validation/input_validator_test.go
  components/telemetry-operator/internal/validation/mocks/input_validator.go
  components/telemetry-operator/internal/webhook/logpipeline_webhook.go
  components/telemetry-operator/internal/webhook/logpipeline_webhook_test.go
  components/telemetry-operator/internal/webhook/suite_test.go
  components/telemetry-operator/main.go
  installation/resources/crds/telemetry/logpipelines.crd.yaml
  resources/telemetry/values.yaml
  tests/fast-integration/Makefile
  tests/fast-integration/telemetry-test/telemetry-test.js
Labels: size/XL, lgtm

#14811 Handling insecure calls in Application Gateway based on skipVerify flag
  components/central-application-gateway/internal/csrf/client/csrfclient.go
  components/central-application-gateway/internal/csrf/client/csrfclient_test.go
  components/central-application-gateway/internal/csrf/mocks/Client.go
  components/central-application-gateway/internal/csrf/mocks/TokenStrategy.go
  components/central-application-gateway/internal/csrf/mocks/TokenStrategyFactory.go
  components/central-application-gateway/internal/csrf/strategy/csrf.go
  components/central-application-gateway/internal/csrf/strategy/csrf_test.go
  components/central-application-gateway/internal/csrf/types.go
  components/central-application-gateway/internal/proxy/cache.go
  components/central-application-gateway/internal/proxy/factory_test.go
  components/central-application-gateway/internal/proxy/proxy.go
  components/central-application-gateway/internal/proxy/proxy_test.go
  components/central-application-gateway/internal/proxy/retryableroundtripper.go
  components/central-application-gateway/internal/proxy/retryableroundtripper_test.go
  components/central-application-gateway/internal/proxy/reverseproxy.go
  components/central-application-gateway/pkg/authorization/basicauthstrategy.go
  components/central-application-gateway/pkg/authorization/basicauthstrategy_test.go
  components/central-application-gateway/pkg/authorization/certificategenstrategy.go
  components/central-application-gateway/pkg/authorization/certificategenstrategy_test.go
  components/central-application-gateway/pkg/authorization/externaltokenstrategy.go
  components/central-application-gateway/pkg/authorization/externaltokenstrategy_test.go
  components/central-application-gateway/pkg/authorization/factory.go
  components/central-application-gateway/pkg/authorization/factory_test.go
  components/central-application-gateway/pkg/authorization/mocks/OAuthClient.go
  components/central-application-gateway/pkg/authorization/mocks/Strategy.go
  components/central-application-gateway/pkg/authorization/mocks/StrategyFactory.go
  components/central-application-gateway/pkg/authorization/noauthstrategy.go
  components/central-application-gateway/pkg/authorization/oauth/mocks/Client.go
  components/central-application-gateway/pkg/authorization/oauth/oauthclient.go
  components/central-application-gateway/pkg/authorization/oauth/oauthclient_test.go
  components/central-application-gateway/pkg/authorization/oauthcertstrategy.go
  components/central-application-gateway/pkg/authorization/oauthcertstrategy_test.go
  components/central-application-gateway/pkg/authorization/oauthstrategy.go
  components/central-application-gateway/pkg/authorization/oauthstrategy_test.go
  resources/application-connector/values.yaml
Labels: size/XL, lgtm

#14946 Git operator fix logger
  components/function-controller/cmd/manager/main.go
  components/function-controller/go.mod
  components/function-controller/internal/controllers/serverless/automock/git_client.go
  components/function-controller/internal/controllers/serverless/automock/git_client_factory.go
  components/function-controller/internal/controllers/serverless/automock/git_operator.go
  components/function-controller/internal/controllers/serverless/automock/stats_collector.go
  components/function-controller/internal/controllers/serverless/fsm.go
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  components/function-controller/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/git/go2git.go
  components/function-controller/internal/git/go2git_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#14804 Add testing mTLS for Application Gateway tests
  components/central-application-gateway/pkg/authorization/oauth/oauthclient.go
  resources/application-connector/values.yaml
  tests/components/application-connector/.gitignore
  tests/components/application-connector/Makefile
  tests/components/application-connector/internal/testkit/test-api/apis.go
  tests/components/application-connector/internal/testkit/test-api/basicauth.go
  tests/components/application-connector/internal/testkit/test-api/middleware.go
  tests/components/application-connector/internal/testkit/test-api/oauth.go
  tests/components/application-connector/internal/testkit/test-api/requestparams.go
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/basic-auth-negative.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/basic-auth-positive.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-negative-expired-client-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-negative-expired-server-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-negative-other-ca.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-oauth-nagative-incorrect-clientid.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-oauth-nagative-other-ca.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-oauth-negative-expired-client-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-oauth-negative-expired-server-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-oauth-positive.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-positive.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/oauth-negative-incorrect-id.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/oauth-negative-invalid-token.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/oauth-positive.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/request-parameters-negative.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/request-parameters.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/negative-authorisation.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/positive-authorisation.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/target-api-mock/credentials/expired-mtls-cert-secret.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/target-api-mock/credentials/mtls-cert-secret.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/target-api-mock/mock-app.yml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
  tests/components/application-connector/scripts/generate-self-signed-certs.sh
  tests/components/application-connector/tools/external-api-mock-app/config.go
  tests/components/application-connector/tools/external-api-mock-app/server.go
Labels: size/XL, lgtm

#14993 Validate file name
  components/telemetry-operator/internal/validation/files_validator.go
  components/telemetry-operator/internal/validation/files_validator_test.go
  components/telemetry-operator/internal/validation/mocks/files_validator.go
  components/telemetry-operator/internal/webhook/logpipeline_webhook.go
  components/telemetry-operator/internal/webhook/logpipeline_webhook_test.go
  components/telemetry-operator/internal/webhook/suite_test.go
  components/telemetry-operator/main.go
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15008 Bumped NATS to v2.8.4 [release-2.5]
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#15007 Bumped NATS to v2.8.4
  resources/eventing/values.yaml
Labels: area/eventing, lgtm

#15018 Telemetry: Restructure webhook pkg and refactor dryrun functionality
  components/telemetry-operator/internal/fluentbit/utils.go
  components/telemetry-operator/internal/fs/mocks/wrapper.go
  components/telemetry-operator/internal/utils/fs.go
  components/telemetry-operator/internal/utils/mocks/fs.go
  components/telemetry-operator/internal/validation/mocks/config_validator.go
  components/telemetry-operator/internal/webhook/dryrun/dryrun.go
  components/telemetry-operator/internal/webhook/dryrun/dryrun_test.go
  components/telemetry-operator/internal/webhook/logparser/mocks/dryrun.go
  components/telemetry-operator/internal/webhook/logparser/validation/mocks/parser_validator.go
  components/telemetry-operator/internal/webhook/logparser/validation/parser_validator.go
  components/telemetry-operator/internal/webhook/logparser/validation/parser_validator_test.go
  components/telemetry-operator/internal/webhook/logparser/webhook.go
  components/telemetry-operator/internal/webhook/logpipeline/mocks/dryrun.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/files_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/files_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/input_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/input_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/max_pipelines_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/max_pipelines_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/mocks/files_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/mocks/input_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/mocks/max_pipeliens_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/mocks/output_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/mocks/plugin_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/mocks/variables_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/output_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/output_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/plugin_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/plugin_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/variable_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/variable_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook_suite_test.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook_test.go
  components/telemetry-operator/main.go
  resources/telemetry/values.yaml
Labels: size/XL, lgtm

#15006 test for istio access logs feature
  tests/fast-integration/logging/client.js
  tests/fast-integration/logging/index.js
  tests/fast-integration/logging/istio_access_logs.yaml
  tests/fast-integration/logging/loki.js
Labels: size/M, lgtm

#14907 Update README for Gateway tests
  milv.config.yaml
  tests/components/application-connector/README.md
Labels: size/L, lgtm

#15036 Change Kyma VERSION to 2.5.1
  VERSION
Labels: size/XS, lgtm

#15023 Fix git-auth testsuite
  resources/serverless/values.yaml
  tests/function-controller/testsuite/scenarios/gitauth.go
Labels: size/XS, lgtm

#15040 improve screenshots in serverless
  docs/03-tutorials/00-serverless/assets/svls-add-ssh-key.png
  docs/03-tutorials/00-serverless/assets/svls-create-ssh-key.png
  docs/03-tutorials/00-serverless/assets/svls-function-ui.png
  docs/03-tutorials/00-serverless/assets/svls-kyma-cli-functions.png
  docs/03-tutorials/00-serverless/assets/svls-settings.png
Labels: size/XS, lgtm

#14988 Bump eventing crds
  components/eventing-controller/config/crd/external/apirules-gateway-kyma-project-io.yaml
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/eventing/values.yaml
Labels: size/S, lgtm

#15045 increase istio access logs creation timeout
  tests/fast-integration/logging/index.js
Labels: size/XS, lgtm

#15031 Adjust ory-oathkeeper health probes
  resources/ory/charts/oathkeeper/templates/deployment-sidecar.yaml
  resources/ory/values.yaml
Labels: area/security, size/XS, lgtm, area/charts

#15038 Bump nodejs16 alpine image
  components/function-runtimes/nodejs16/Dockerfile
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15048 Use nodejs v16.16 in serverless runtime
  components/function-runtimes/nodejs16/Dockerfile
Labels: size/XS, lgtm

#14996 Add the rest of the CSRF Application Gateway tests
  tests/components/application-connector/internal/testkit/test-api/apis.go
  tests/components/application-connector/internal/testkit/test-api/csrf.go
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-negative-case.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-oauth-negative-case.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/negative-authorisation.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/positive-authorisation.yml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
  tests/components/application-connector/tools/external-api-mock-app/server.go
Labels: area/application-connector, size/L, lgtm, area/tests

#15050 Use nodejs v16.16 in serverless runtime
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15034 Updated JetStream Dashboard to read from leaders only
  resources/eventing/charts/dashboards/templates/jetstream.yaml
  tests/fast-integration/eventing-test/nats-dashboard-queries.json
Labels: size/M, lgtm

#15051 Updated JetStream Dashboard to read from leaders only (#15034)
  resources/eventing/charts/dashboards/templates/jetstream.yaml
  tests/fast-integration/eventing-test/nats-dashboard-queries.json
Labels: area/eventing, size/M, lgtm

#15053 Change Kyma VERSION to 2.5.2
  VERSION
Labels: size/XS, lgtm

#15030 Include system logs in Loki LogPipeline
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  installation/resources/crds/telemetry/logpipelines.crd.yaml
  resources/logging/charts/loki/templates/kyma-additions/logpipeline_loki.yaml
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/telemetry-test.js
Labels: size/M, lgtm

#15054 make MergeParsersConfig permutation invariant
  components/telemetry-operator/controllers/telemetry/logparser_controller.go
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/parserSync/parser.go
Labels: area/logging, size/S, lgtm

#15062 add logparsers CRs to telemetry fluent bit
  resources/telemetry/charts/fluent-bit/templates/kyma-additions/logparsers.yaml
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15024 Stub compas runetime agent tests
  tests/components/application-connector/Dockerfile.compass-runtime-agent
  tests/components/application-connector/Makefile
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/Chart.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/templates/_helpers.tpl
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/templates/test.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/scripts/check-pod-logs.sh
  tests/components/application-connector/test/compass-runtime-agent/suite_test.go
  tests/components/application-connector/test/compass-runtime-agent/synchronisation_test.go
Labels: size/L, lgtm

#15035 Telemetry Operator: Input documentation
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: size/L, lgtm

#15049 Add v1alpha1 webhooks for serverless
  components/function-controller/cmd/webhook/main.go
  components/function-controller/internal/webhook/config.go
  components/function-controller/internal/webhook/defaulting_webhook.go
  components/function-controller/internal/webhook/defaulting_webhook_test.go
  components/function-controller/internal/webhook/fixtures_test.go
  components/function-controller/internal/webhook/resources/webhook_config.go
  components/function-controller/internal/webhook/resources/webhook_config_test.go
  components/function-controller/internal/webhook/validating_webhook.go
  components/function-controller/internal/webhook/validating_webhook_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/groupversion_info.go
  components/function-controller/pkg/apis/serverless/v1alpha2/groupversion_info.go
  resources/serverless/values.yaml
Labels: size/XL, lgtm

#15072 Add reconciler Gherkin tests
  tests/components/reconciler/cucumber_test.go
  tests/components/reconciler/features/kyma-lifecycle.feature
  tests/components/reconciler/go.mod
  tests/components/reconciler/go.sum
Labels: size/XL, lgtm

#15043 Fix MinReplicas field
  components/function-controller/internal/webhook/conversion_webhook.go
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/XS, lgtm

#15057 Enable telemetry component
  installation/resources/components.yaml
  resources/logging/values.yaml
  tests/fast-integration/logging/loki.js
  tests/fast-integration/telemetry-test/telemetry-test.js
Labels: size/S, lgtm

#15020 Update eventing dashboard queries
  resources/eventing/charts/dashboards/templates/eventTypesSummary.yaml
  tests/fast-integration/eventing-test/nats-dashboard-queries.json
Labels: area/eventing, size/S, lgtm

#15081 Fix allowed parameter values in the App CR doc
  docs/05-technical-reference/00-custom-resources/ac-01-application.md
Labels: kind/bug, area/documentation, size/XS, lgtm

#15080 MinReplicas Converting Webhook2to1
  components/function-controller/internal/webhook/conversion_webhook.go
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15086 improve eventing-controller tests
  components/eventing-controller/controllers/backend/reconciler_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/controllers/subscription/testing/test_utils.go
  components/eventing-controller/pkg/ems/httpclient/client.go
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/pkg/handlers/beb_test.go
  components/eventing-controller/testing/event/cehelper/converter.go
  components/eventing-controller/testing/subscriber.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#15066 rename fluent bit restarts total metric
  components/telemetry-operator/controllers/telemetry/logpipeline_controller_test.go
  components/telemetry-operator/controllers/telemetry/suite_test.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook_suite_test.go
  components/telemetry-operator/main.go
  resources/telemetry/charts/operator/values.yaml
Labels: size/S, lgtm

#15077 Add missing information to README for Application Connector tests
  tests/components/application-connector/README.md
  tests/components/application-connector/assets/api-auth-methods-mtls.png
  tests/components/application-connector/assets/api-auth-methods.png
  tests/components/application-connector/assets/api-tokens-mtls.png
  tests/components/application-connector/assets/api-tokens.png
  tests/components/application-connector/assets/mock-app-mtls-spec.yaml
  tests/components/application-connector/assets/mock-app-spec.yaml
  tests/components/application-connector/internal/testkit/test-api/apis.go
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-negative-expired-client-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/credentials/mtls-negative-expired-server-cert.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/proxy-cases.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/target-api-mock/credentials/expired-mtls-cert-secret.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: size/L, lgtm

#15083 Adjust Serverless bench functions to v1alpha2
  tests/serverless-bench/fixtures/functions/nodejs14-l.yaml
  tests/serverless-bench/fixtures/functions/nodejs14-m.yaml
  tests/serverless-bench/fixtures/functions/nodejs14-s.yaml
  tests/serverless-bench/fixtures/functions/nodejs14-xl.yaml
  tests/serverless-bench/fixtures/functions/nodejs14-xs.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-l.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-m.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-s.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-xl.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-xs.yaml
  tests/serverless-bench/fixtures/functions/python39-l.yaml
  tests/serverless-bench/fixtures/functions/python39-m.yaml
  tests/serverless-bench/fixtures/functions/python39-s.yaml
  tests/serverless-bench/fixtures/functions/python39-xl.yaml
Labels: size/M, lgtm

#15071 Document ENV injection to Functions
  docs/03-tutorials/00-serverless/svls-14-inject-envs.md
Labels: size/L, lgtm

#15091 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
  test_file
Labels: size/XS, lgtm

#15079 Telemetry Operator - Refactor dry-run pkg
  components/telemetry-operator/go.mod
  components/telemetry-operator/go.sum
  components/telemetry-operator/internal/fluentbit/utils.go
  components/telemetry-operator/internal/utils/fs.go
  components/telemetry-operator/internal/utils/mocks/fs.go
  components/telemetry-operator/internal/webhook/dryrun/command_runner.go
  components/telemetry-operator/internal/webhook/dryrun/dryrun.go
  components/telemetry-operator/internal/webhook/dryrun/dryrun_test.go
  components/telemetry-operator/internal/webhook/dryrun/file_writer.go
  components/telemetry-operator/internal/webhook/dryrun/file_writer_test.go
  components/telemetry-operator/internal/webhook/dryrun/mocks/command_runner.go
  components/telemetry-operator/internal/webhook/dryrun/mocks/file_writer.go
  components/telemetry-operator/internal/webhook/dryrun/testdata/.gitignore
  components/telemetry-operator/internal/webhook/dryrun/testdata/expected/parsers/dynamic-parsers/parsers.conf
  components/telemetry-operator/internal/webhook/dryrun/testdata/expected/pipelines/custom_parsers.conf
  components/telemetry-operator/internal/webhook/dryrun/testdata/expected/pipelines/dynamic-parsers/parsers.conf
  components/telemetry-operator/internal/webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
  components/telemetry-operator/internal/webhook/dryrun/testdata/expected/pipelines/files/dummy.txt
  components/telemetry-operator/internal/webhook/dryrun/testdata/expected/pipelines/fluent-bit.conf
  components/telemetry-operator/internal/webhook/dryrun/testdata/given/fluent-bit-configmap.yaml
  components/telemetry-operator/internal/webhook/dryrun/testdata/given/logparser-1.yaml
  components/telemetry-operator/internal/webhook/dryrun/testdata/given/logparser-2.yaml
  components/telemetry-operator/internal/webhook/dryrun/testdata/given/logpipeline-1.yaml
  components/telemetry-operator/internal/webhook/logparser/mocks/dryrun.go
  components/telemetry-operator/internal/webhook/logparser/webhook.go
  components/telemetry-operator/internal/webhook/logpipeline/mocks/dryrun.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook_suite_test.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook_test.go
  components/telemetry-operator/main.go
  resources/telemetry/values.yaml
Labels: size/XXL, lgtm

#15088 Add missing documentation for grafana-loki LogPipeline output
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: size/S, lgtm

#15092 add logging-fluent-bit cleanup script to 2.5-2.6 migration guide
  docs/assets/2.5-2.6-cleanup-logging-fluent-bit.sh
  docs/migration-guide-2.5-2.6.md
Labels: size/S, lgtm

#15055 Update nats charts to version 0.17.3
  resources/eventing/charts/nats/Chart.yaml
  resources/eventing/charts/nats/README.md
  resources/eventing/charts/nats/templates/configmap.yaml
  resources/eventing/charts/nats/templates/service.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
Labels: area/eventing, size/L, lgtm

#15095 Bump lib versions in eventing components
  components/event-publisher-proxy/cmd/event-publisher-proxy/Dockerfile
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/Dockerfile
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/S, lgtm

#15108 updated several alpine base images
  resources/kiali/values.yaml
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/tracing/values.yaml
Labels: size/S, lgtm

#14979 Add Nodejs16 integration test
  resources/serverless/values.yaml
  tests/function-controller/testsuite/runtimes/nodejs.go
  tests/function-controller/testsuite/scenarios/light_runtimes.go
Labels: size/S, lgtm

#14976 Refactor min/maxReplicas
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/crd/crd-serverless.yaml
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  components/function-controller/internal/controllers/serverless/fixtures_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/horizontalpodautoscaler.go
  components/function-controller/internal/controllers/serverless/horizontalpodautoscaler_test.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/defaulting_webhook_test.go
  components/function-controller/internal/webhook/fixtures_test.go
  components/function-controller/internal/webhook/validating_webhook_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/zz_generated.deepcopy.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/values.yaml
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/xf-mocks.yaml
  tests/function-controller/go.mod
  tests/function-controller/go.sum
  tests/function-controller/testsuite/gitops/function.go
  tests/function-controller/testsuite/teststep/check.go
  tests/serverless-bench/fixtures/functions/nodejs14-l.yaml
  tests/serverless-bench/fixtures/functions/nodejs14-m.yaml
  tests/serverless-bench/fixtures/functions/nodejs14-s.yaml
  tests/serverless-bench/fixtures/functions/nodejs14-xl.yaml
  tests/serverless-bench/fixtures/functions/nodejs14-xs.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-l.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-m.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-s.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-xl.yaml
  tests/serverless-bench/fixtures/functions/nodejs16-xs.yaml
  tests/serverless-bench/fixtures/functions/python39-l.yaml
  tests/serverless-bench/fixtures/functions/python39-m.yaml
  tests/serverless-bench/fixtures/functions/python39-s.yaml
  tests/serverless-bench/fixtures/functions/python39-xl.yaml
Labels: size/XL, lgtm

#15076 Added script in skr-test to only provision or deprovision SKR
  tests/fast-integration/Makefile
  tests/fast-integration/image/Dockerfile
  tests/fast-integration/kyma-environment-broker/client.js
  tests/fast-integration/kyma-environment-broker/helpers.js
  tests/fast-integration/package.json
  tests/fast-integration/skr-aws-upgrade-integration/index.js
  tests/fast-integration/skr-nightly/provision/provision-skr-nightly.js
  tests/fast-integration/skr-test/deprovision-skr.js
  tests/fast-integration/skr-test/helpers.js
  tests/fast-integration/skr-test/oidc/index.js
  tests/fast-integration/skr-test/provision-skr.js
  tests/fast-integration/skr-test/provision/provision-skr.js
  tests/fast-integration/skr-test/test.js
Labels: size/L, lgtm

#15124 update goats CODEOWNERS
  CODEOWNERS
Labels: size/S, lgtm

#15109 add better description for the fluent-bit container exclude
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: size/XS, lgtm

#15068 added new directory-size-exporter component to be used in telemetry component
  CODEOWNERS
  components/directory-size-exporter/.dockerignore
  components/directory-size-exporter/.gitignore
  components/directory-size-exporter/Dockerfile
  components/directory-size-exporter/Makefile
  components/directory-size-exporter/README.md
  components/directory-size-exporter/go.mod
  components/directory-size-exporter/go.sum
  components/directory-size-exporter/internal/exporter/exporter.go
  components/directory-size-exporter/internal/exporter/exporter_test.go
  components/directory-size-exporter/main.go
Labels: size/XXL, lgtm

#15112 docs: make collection of k8s annotations and labels optional
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: size/XS, lgtm

#15126 update http output examples
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: size/M, lgtm

#15089 Jetstream Controller-Integration Test improvements
  components/eventing-controller/controllers/subscription/jetstream/reconciler_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/controllers/subscription/testing/test_utils.go
Labels: area/eventing, size/L, lgtm

#15044 API-Rule v1beta1
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/templates/rbac.yaml
  resources/api-gateway/templates/webhook-certificates.yaml
  resources/api-gateway/templates/webhook-service.yaml
  resources/api-gateway/values.yaml
Labels: size/L, lgtm

#15114 Fix git validation
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/pkg/apis/serverless/v1alpha1/gitrepository_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha1/gitrepository_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  resources/serverless/values.yaml
Labels: size/M, lgtm

#15125 Bump Golang in Application Connectivity
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/Dockerfile
  components/central-application-gateway/go.mod
  components/compass-runtime-agent/go.mod
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/security, area/application-connector, size/S, lgtm

#15127 Change base image for FI test docker image
  tests/fast-integration/image/Dockerfile
Labels: size/XS, lgtm

#15144 Fix telemetry operator deployment
  resources/telemetry/charts/operator/templates/deployment.yaml
Labels: area/logging, size/XS, lgtm

#15121 Crd runtime as string 15016
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/crd/crd-serverless.yaml
  components/function-controller/internal/controllers/serverless/fsm.go
  components/function-controller/internal/controllers/serverless/gitops_test.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#15100 [Telemetry Operator] Make collection of k8s annotations and labels optional
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  components/telemetry-operator/controllers/telemetry/logpipeline_controller_test.go
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/fluentbit/config_builder_test.go
  components/telemetry-operator/internal/webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
  installation/resources/crds/telemetry/logpipelines.crd.yaml
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/resources/deployments/regex-filter-deployment.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/http-logpipeline.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/invalid-logpipeline.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/loki-k8s-metadata-filter-drop-labels-logpipeline.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/loki-k8s-metadata-filter-keep-labels-logpipeline.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/regex-logparser.yaml
  tests/fast-integration/telemetry-test/telemetry-test.js
Labels: area/logging, size/L, lgtm

#15138 API rule support multiple services documentation update
  components/eventing-controller/config/crd/external/README.md
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/03-tutorials/00-api-exposure/apix-02-expose-workload-apigateway.md
  docs/03-tutorials/00-api-exposure/apix-03-expose-and-secure-workload-oauth2.md
  docs/03-tutorials/00-api-exposure/apix-05-expose-and-secure-workload-jwt.md
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
  docs/03-tutorials/00-serverless/svls-03-expose-function.md
  docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
Labels: size/M, lgtm

#15149 Update CODEOWNERS
  CODEOWNERS
Labels: area/community, size/XS, lgtm

#15139 Disabling sidecar injection and workload migration
  docs/01-overview/main-areas/service-mesh/smsh-01-details.md
  docs/01-overview/main-areas/service-mesh/smsh-02-default-istio-setup-in-kyma.md
  docs/01-overview/main-areas/service-mesh/smsh-03-istio-sidecars-in-kyma.md
  docs/01-overview/main-areas/service-mesh/smsh-99-useful-links.md
  docs/03-tutorials/00-api-exposure/apix-01-own-domain.md
  docs/03-tutorials/00-api-exposure/apix-02-create-workload.md
  docs/03-tutorials/00-observability/obsv-01-observe-application-metrics.md
  docs/03-tutorials/00-serverless/svls-06-sync-function-with-gitops.md
  docs/03-tutorials/00-service-management/smgt-01-deploy-service.md
  docs/04-operation-guides/operations/smsh-01-istio-disable-sidecar-injection.md
  docs/04-operation-guides/operations/smsh-01-istio-enable-sidecar-injection.md
  docs/04-operation-guides/troubleshooting/service-mesh/smsh-03-istio-no-sidecar.md
  docs/04-operation-guides/troubleshooting/service-mesh/smsh-04-istio-sidecar-version.md
  docs/05-technical-reference/00-architecture/svls-01-architecture.md
  resources/istio/values.yaml
  tests/fast-integration/package-lock.json
  tests/fast-integration/utils/index.js
Labels: area/service-mesh, size/XXL, lgtm

#15153 Bump api-gateway
  resources/api-gateway/values.yaml
Labels: size/XS, lgtm

#15157 bump `prometheus-nats-exporter` and `nats-config-reloader`
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#15159 Updated SKR provision fast-integration step
  tests/fast-integration/skr-test/provision-skr.js
Labels: size/S, lgtm

#15122 Describe how to handle overrides to Fluent Bit in migration guide
  docs/migration-guide-2.5-2.6.md
Labels: size/XS, lgtm

#15160 Bump istio to 1.14.3
  resources/istio-resources/files/dashboards/control-plane.json
  resources/istio-resources/files/dashboards/mesh.json
  resources/istio-resources/files/dashboards/performance.json
  resources/istio-resources/files/dashboards/service.json
  resources/istio-resources/files/dashboards/workload.json
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: size/S, lgtm

#15167 Api gateway Istio client go 1.14.3
  resources/api-gateway/values.yaml
Labels: size/XS, lgtm

#15164 Remove application-connector PR images before release branch cut-off
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: size/S, lgtm

#15170 Remove dependcy to istio in test
  resources/serverless/charts/k3s-tests/templates/k3s-test.yaml
Labels: size/XS, lgtm

#15146 [Telemetry Operator] Adapt input API
  components/telemetry-operator/apis/telemetry/v1alpha1/groupversion_info.go
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline_input.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline_input_excludes.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline_input_includes.yaml
  components/telemetry-operator/controllers/telemetry/logpipeline_controller_test.go
  components/telemetry-operator/internal/fluentbit/rewrite_tag.go
  components/telemetry-operator/internal/fluentbit/rewrite_tag_test.go
  components/telemetry-operator/internal/webhook/logparser/webhook.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/input_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/input_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook_suite_test.go
  installation/resources/crds/telemetry/logpipelines.crd.yaml
  resources/logging/charts/loki/templates/kyma-additions/logpipeline_loki.yaml
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/loki-k8s-metadata-filter-drop-labels-logpipeline.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/loki-k8s-metadata-filter-keep-labels-logpipeline.yaml
Labels: size/L, lgtm

#14704 Implement scale sub-resource
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/crd/crd-serverless.yaml
  components/function-controller/internal/controllers/serverless/fsm.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/scaling.go
  components/function-controller/internal/controllers/serverless/scaling_test.go
  components/function-controller/internal/controllers/serverless/service.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/zz_generated.deepcopy.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/values.yaml
Labels: size/XL, lgtm

#15156 bump dependencies in `event-publisher-proxy`
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  resources/eventing/values.yaml
Labels: size/M, lgtm

#15158 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15154 bump dependencies in `eventing-controller`
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/M, lgtm

#15171 Updating docs with sidecar injection disabled
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/03-tutorials/00-application-connectivity/ac-01-create-application.md
  docs/03-tutorials/00-application-connectivity/ac-03-register-manage-services.md
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
  docs/03-tutorials/00-eventing/evnt-02-subs-with-multiple-filters.md
  docs/03-tutorials/00-eventing/evnt-03-type-cleanup.md
  docs/03-tutorials/00-eventing/evnt-04-change-max-in-flight-in-sub.md
  docs/03-tutorials/00-eventing/evnt-05-send-legacy-events.md
  docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
  docs/03-tutorials/00-serverless/svls-02-create-git-function.md
  docs/03-tutorials/00-serverless/svls-03-expose-function.md
  docs/03-tutorials/00-serverless/svls-04-manage-functions-with-kyma-cli.md
Labels: size/S, lgtm

#15193 update loki plugin of fluent bit to newest golang patch version
  components/telemetry-operator/Dockerfile
  resources/logging/values.yaml
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#15161 Revert "add logparsers CRs to telemetry fluent bit (#15062)"
  resources/telemetry/charts/fluent-bit/templates/kyma-additions/logparsers.yaml
Labels: size/L, lgtm

#15132 [Telemetry Operator] Don't restart Fluent Bit pod when the CR is being updated
  components/telemetry-operator/controllers/telemetry/logparser_controller.go
  components/telemetry-operator/controllers/telemetry/logpipeline_controller.go
  components/telemetry-operator/internal/parserSync/parser.go
  components/telemetry-operator/internal/parserSync/parser_test.go
  components/telemetry-operator/internal/sync/sync.go
  components/telemetry-operator/internal/sync/sync_test.go
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15151 Document metrics emitted by eventing
  docs/01-overview/main-areas/eventing/evnt-99-useful-links.md
  docs/04-operation-guides/operations/evnt-01-eventing-dashboards.md
  docs/04-operation-guides/operations/evnt-02-eventing-metrics.md
Labels: area/documentation, area/eventing, size/M, lgtm

#15197 Minor output update to SKR provision FI script
  tests/fast-integration/skr-test/provision-skr.js
Labels: size/XS, lgtm

#15147 Add a new consolidated eventing dashboard
  components/event-publisher-proxy/pkg/handler/nats/handler.go
  components/event-publisher-proxy/pkg/metrics/collector.go
  resources/eventing/charts/dashboards/templates/delivery.yaml
  resources/eventing/charts/dashboards/templates/deliverypersubscription.yaml
  resources/eventing/charts/dashboards/templates/eventTypesSummary.yaml
  resources/eventing/charts/dashboards/templates/jetstream.yaml
  resources/eventing/values.yaml
  tests/fast-integration/eventing-test/nats-dashboard-queries.json
Labels: area/eventing, size/XXL, lgtm

#15166 Improve serverless CRD deprecation messages
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/crd/bases/serverless.kyma-project.io_gitrepositories.yaml
  components/function-controller/config/crd/crd-serverless.yaml
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha1/gitrepository_types.go
  installation/resources/crds/serverless/crd-serverless.yaml
Labels: size/L, lgtm

#15168 [Telemetry Operator] - Adapt LogPipeline input spec documentation to new API
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: size/M, lgtm

#15212 Add kustomize requirement in readme for serverless
  components/function-controller/README.md
Labels: size/XS, lgtm

#15140 Serverless external scalers tutorial
  docs/03-tutorials/00-serverless/svls-15-use-external-scalers.md
Labels: area/documentation, area/serverless, size/L, lgtm

#15133 update reserved keywords in log payload for telemetry docs
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: size/XS, lgtm

#15103 Reconciler Gherkin tests (II)
  CODEOWNERS
  tests/components/reconciler/Makefile
  tests/components/reconciler/cucumber_test.go
  tests/components/reconciler/e2e_test.go
  tests/components/reconciler/features/incident-recovery.feature
  tests/components/reconciler/features/module-template.feature
  tests/components/reconciler/given.go
  tests/components/reconciler/go.mod
  tests/components/reconciler/go.sum
  tests/components/reconciler/then.go
Labels: size/L, lgtm

#15196 Added description for LogPipeline.unsupportedMode
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: area/logging, size/S, lgtm

#15216 Revert "[Telemetry Operator] Don't restart Fluent Bit pod when the CR is being updated (#15132)
  components/telemetry-operator/controllers/telemetry/logparser_controller.go
  components/telemetry-operator/controllers/telemetry/logpipeline_controller.go
  components/telemetry-operator/internal/parserSync/parser.go
  components/telemetry-operator/internal/parserSync/parser_test.go
  components/telemetry-operator/internal/sync/sync.go
  components/telemetry-operator/internal/sync/sync_test.go
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15217 Add instruction how to keep Fluent Bit from the logging component
  docs/migration-guide-2.5-2.6.md
Labels: size/XS, lgtm

#15218 Remove telemetry-operator PR image
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#15163 Add requirements for ScaleConfig
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/crd/crd-serverless.yaml
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/values.yaml
Labels: size/S, lgtm

#15205 Fixed problem with Istio sidecar injection in Application Gateway Test
  tests/components/application-connector/Makefile
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: size/XS, lgtm

#15224 Bump Application Gateway test image
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: size/XS, lgtm

#15075 Bumped kyma override version in eventing fast-integration tests
  tests/fast-integration/eventing-test/prow/config/skr_config.json
Labels: size/XS, lgtm

#15169 V1alpha2 doc 15155
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  docs/05-technical-reference/00-custom-resources/svls-02-gitrepository.md
Labels: size/L, lgtm

#15178 Otters security fixes 2.6
  components/busola-migrator/Dockerfile
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/nodejs16/Dockerfile
  components/function-runtimes/python39/Dockerfile
  resources/serverless/values.yaml
Labels: size/M, lgtm

#15226 Replace all `PR` tags for the `otter's` components
  resources/busola-migrator/values.yaml
  resources/serverless/values.yaml
Labels: size/S, lgtm

#15229 Upgrade serverless test PR tag
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#15143 [Telemetry Operator] Support duplicate keys custom plugins
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/controllers/telemetry/logpipeline_controller.go
  components/telemetry-operator/controllers/telemetry/logpipeline_controller_test.go
  components/telemetry-operator/controllers/telemetry/suite_test.go
  components/telemetry-operator/go.mod
  components/telemetry-operator/internal/fluentbit/config/builder/config_builder.go
  components/telemetry-operator/internal/fluentbit/config/builder/config_builder_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/custom_filter.go
  components/telemetry-operator/internal/fluentbit/config/builder/custom_filter_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/metadata_filter.go
  components/telemetry-operator/internal/fluentbit/config/builder/metadata_filter_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/output.go
  components/telemetry-operator/internal/fluentbit/config/builder/output_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/rewritetag_filter.go
  components/telemetry-operator/internal/fluentbit/config/builder/rewritetag_filter_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/section_builder.go
  components/telemetry-operator/internal/fluentbit/config/builder/section_builder_test.go
  components/telemetry-operator/internal/fluentbit/config/types.go
  components/telemetry-operator/internal/fluentbit/config/validation.go
  components/telemetry-operator/internal/fluentbit/config/validation_test.go
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/fluentbit/config_builder_test.go
  components/telemetry-operator/internal/fluentbit/rewrite_tag.go
  components/telemetry-operator/internal/fluentbit/sections_test.go
  components/telemetry-operator/internal/parserSync/parser.go
  components/telemetry-operator/internal/secret/secret_helper.go
  components/telemetry-operator/internal/secret/secret_helper_test.go
  components/telemetry-operator/internal/sync/sync.go
  components/telemetry-operator/internal/sync/sync_test.go
  components/telemetry-operator/internal/utils/envvar/format.go
  components/telemetry-operator/internal/utils/envvar/format_test.go
  components/telemetry-operator/internal/webhook/dryrun/dryrun.go
  components/telemetry-operator/internal/webhook/dryrun/file_writer.go
  components/telemetry-operator/internal/webhook/dryrun/file_writer_test.go
  components/telemetry-operator/internal/webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
  components/telemetry-operator/internal/webhook/logparser/validation/parser_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/mocks/plugin_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/output_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/plugin_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/plugin_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook_test.go
  components/telemetry-operator/main.go
  resources/telemetry/values.yaml
Labels: size/XXL, lgtm

#15227 [Telemetry Operator] Fix logparser finalizer handling
  components/telemetry-operator/internal/parserSync/parser.go
  resources/telemetry/values.yaml
Labels: area/logging, size/M, lgtm

#15236 Print SKR kyma version when provisioning SKR
  tests/fast-integration/skr-test/helpers.js
  tests/fast-integration/skr-test/provision-skr.js
  tests/fast-integration/skr-test/provision/provision-skr.js
Labels: size/S, lgtm

#15228 [Telemetry Operator] rename reserverd log attribute __k8s__ to __kyma__
  components/telemetry-operator/controllers/telemetry/logpipeline_controller_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/metadata_filter.go
  components/telemetry-operator/internal/fluentbit/config/builder/metadata_filter_test.go
  components/telemetry-operator/internal/webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
Labels: area/logging, size/M, lgtm

#15243 fix namespace in observability tutorial
  docs/03-tutorials/00-observability/obsv-05-clean-up-configuration.md
Labels: size/XS, lgtm

#15247 [Telemetry Operator] Fix output config builder - duplicate format and port
  components/telemetry-operator/internal/fluentbit/config/builder/output.go
  components/telemetry-operator/internal/fluentbit/config/builder/output_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/section_builder.go
  resources/telemetry/values.yaml
Labels: size/M, lgtm

#15248 Fix content-type header in serverless tutorial
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
Labels: size/XS, lgtm

#15249 Fix content-type header in serverless tutorial (#15248)
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
Labels: size/XS, lgtm

#15250 Remove outdated function controller samples
  components/function-controller/config/samples/serverless_v1alpha1_function-with-dep.yaml
  components/function-controller/config/samples/serverless_v1alpha1_function.yaml
  components/function-controller/config/samples/serverless_v1alpha1_function_full.yaml
  components/function-controller/config/samples/serverless_v1alpha1_function_git.yaml
  components/function-controller/config/samples/serverless_v1alpha1_function_python39.yaml
  components/function-controller/config/samples/serverless_v1alpha1_funtion_python39.yaml
  components/function-controller/config/samples/serverless_v1alpha1_gitrepository-with-auth.yaml
  components/function-controller/config/samples/serverless_v1alpha1_gitrepository.yaml
Labels: size/L, lgtm

#15262 Add fixes to Application Connector tutorials' commands
  docs/03-tutorials/00-application-connectivity/ac-01-create-application.md
  docs/03-tutorials/00-application-connectivity/ac-03-register-manage-services.md
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
  docs/03-tutorials/00-application-connectivity/ac-11-disable-tls-certificate-verification.md
Labels: kind/bug, area/documentation, size/L, lgtm

#15263 Refine the Get Started guides and fix the bug in the event delivery verification command
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/02-get-started/README.md
  docs/03-tutorials/00-eventing/README.md
  docs/03-tutorials/00-eventing/evnt-02-subs-with-multiple-filters.md
  docs/03-tutorials/00-eventing/evnt-03-type-cleanup.md
  docs/03-tutorials/00-eventing/evnt-04-change-max-in-flight-in-sub.md
  docs/03-tutorials/00-eventing/evnt-05-send-legacy-events.md
Labels: kind/bug, area/documentation, size/L, lgtm

#15265 Fix prerequisites for AC tutorials, Get Started guides, and Eventing tutorials, and tidy up the AC and GSG documents
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/02-get-started/README.md
  docs/03-tutorials/00-application-connectivity/ac-01-create-application.md
  docs/03-tutorials/00-application-connectivity/ac-03-register-manage-services.md
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
  docs/03-tutorials/00-application-connectivity/ac-11-disable-tls-certificate-verification.md
  docs/03-tutorials/00-eventing/README.md
  docs/03-tutorials/00-eventing/evnt-02-subs-with-multiple-filters.md
  docs/03-tutorials/00-eventing/evnt-03-type-cleanup.md
  docs/03-tutorials/00-eventing/evnt-04-change-max-in-flight-in-sub.md
  docs/03-tutorials/00-eventing/evnt-05-send-legacy-events.md
Labels: kind/bug, area/documentation, size/L, lgtm

#15271 update directory-size-exporter go version
  components/directory-size-exporter/go.mod
Labels: size/XS, lgtm

#15272 Adjust migration guide
  docs/migration-guide-2.5-2.6.md
Labels: size/S, lgtm

#15273 remove link to obsolete anchor
  docs/01-overview/main-areas/serverless/svls-06-security-considerations.md
Labels: size/S, lgtm

#15277 Cherry-pick migration guide (#15272)
  docs/migration-guide-2.5-2.6.md
Labels: size/S, lgtm

#15276 remove link to obsolete anchor #15273
  docs/01-overview/main-areas/serverless/svls-06-security-considerations.md
Labels: area/documentation, area/serverless, size/S, lgtm

#15278 bump version
  VERSION
Labels: size/XS, lgtm

#15209 Remove log that exposes the event internals
  components/event-publisher-proxy/pkg/sender/jetstream.go
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#15275 Improve the command for getting logs of the event sink in the getting started guides
  docs/02-get-started/04-trigger-workload-with-event.md
Labels: area/serverless, area/eventing, size/XS, lgtm

#15280 fix secret handling typo
  components/telemetry-operator/internal/sync/sync.go
Labels: size/XS, lgtm

#15294 Add the omitted parameter to the command description
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
Labels: kind/bug, area/documentation, size/XS, lgtm

#15297 bump dependencies in `event-publisher-proxy`
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  resources/eventing/values.yaml
Labels: size/M, lgtm

#15296 bump dependencies in `eventing-controller`
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/M, lgtm

#15281 [Telemetry Operator] Bump kubebuilder and controller-runtime dependencies
  components/telemetry-operator/Makefile
  components/telemetry-operator/README.md
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  components/telemetry-operator/config/rbac/role.yaml
  components/telemetry-operator/go.mod
  components/telemetry-operator/go.sum
  installation/resources/crds/telemetry/logparsers.crd.yaml
  installation/resources/crds/telemetry/logpipelines.crd.yaml
  resources/telemetry/charts/operator/templates/role.yaml
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#15234 [Telemetry Operator] Make Loki and HTTP outputs nullable
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types_test.go
  components/telemetry-operator/apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  components/telemetry-operator/internal/fluentbit/config/builder/config_builder.go
  components/telemetry-operator/internal/fluentbit/config/builder/config_builder_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/output.go
  components/telemetry-operator/internal/fluentbit/config/builder/output_test.go
  components/telemetry-operator/internal/secret/secret_helper.go
  components/telemetry-operator/internal/secret/secret_helper_test.go
  components/telemetry-operator/internal/sync/sync.go
  components/telemetry-operator/internal/sync/sync_test.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/filter_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/filter_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/output_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/output_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/plugin_validator.go
  components/telemetry-operator/internal/webhook/logpipeline/validation/plugin_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline/webhook.go
  components/telemetry-operator/main.go
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/kubernetes-custom-filter-logpipeline.yaml
  tests/fast-integration/telemetry-test/resources/telemetry-custom-resources/unknown-plugin-logpipeline.yaml
  tests/fast-integration/telemetry-test/telemetry-test.js
Labels: area/logging, size/XXL, lgtm

#15306 Add myself to /tests/components/istio codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#15310 Fix deployment of apirule crd on 2.6.0
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
Labels: size/XS, lgtm

#15264 Fix github authentication integration tests
  resources/serverless/values.yaml
  tests/function-controller/pkg/secret/secret.go
  tests/function-controller/testsuite/gitops/function.go
  tests/function-controller/testsuite/scenarios/gitauth.go
  tests/function-controller/testsuite/scenarios/gitops.go
Labels: size/M, lgtm

#15230 Test for istio resources
  tests/components/istio/features/istio_evaluation.feature
  tests/components/istio/features/istio_production.feature
  tests/components/istio/go.mod
  tests/components/istio/go.sum
  tests/components/istio/istio_installed_test.go
  tests/components/istio/istio_sidecar_test.go
  tests/components/istio/main_test.go
  tests/components/istio/test_helpers.go
Labels: size/L, lgtm

#15293 Remove JWKS parameter in api-gateway
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/values.yaml
Labels: size/XS, lgtm

#15318 [Telemetry Operator] Make ValueFrom and SecretRef nullable
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  components/telemetry-operator/controller/logpipeline/controller_test.go
  components/telemetry-operator/controller/logpipeline/secret_helper.go
  components/telemetry-operator/controller/logpipeline/secret_helper_test.go
  components/telemetry-operator/controller/logpipeline/sync.go
  components/telemetry-operator/controller/logpipeline/sync_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/output.go
  components/telemetry-operator/internal/fluentbit/config/builder/output_test.go
  components/telemetry-operator/internal/utils/envvar/format_test.go
  components/telemetry-operator/webhook/logpipeline/validation/variable_validator.go
  components/telemetry-operator/webhook/logpipeline/validation/variable_validator_test.go
  resources/telemetry/values.yaml
Labels: area/logging, size/L, lgtm

#15319 add preserve unknown fields = false (#15310)
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
Labels: size/XS, lgtm

#15322 release 2.6.1
  VERSION
Labels: size/XS, lgtm

#15324 Add Enabling Istio Mesh as a prerequisite for serverless tutorial
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
Labels: size/XS, lgtm

#15325 Add istio enable prerequisite
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
Labels: size/XS, lgtm

#15231 Set proper logger in serverless webhook
  components/function-controller/cmd/manager/main.go
  components/function-controller/cmd/webhook/main.go
  components/function-controller/go.mod
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  components/function-controller/internal/webhook/resources/certificates.go
  components/function-controller/internal/webhook/resources/certificates_test.go
  components/function-controller/internal/webhook/resources/resources.go
  components/function-controller/internal/webhook/resources/resources_test.go
  resources/serverless/charts/webhook/templates/deployment.yaml
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm
