Repository kyma-project/kyma, pull requests merged in 2022-07, with the labels that each got.

#14723 [release-2.4] Bump serverless images
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#14727 Bump Kyma version to 2.4.1
  VERSION
Labels: size/XS, lgtm

#14728 Add Kiali cleanup script to 2.3-2.4 migration guide
  docs/migration-guide-2.3-2.4.md
Labels: size/XS, lgtm

#14729 Add Kiali cleanup script to 2.3-2.4 migration guide (#14728)
  docs/migration-guide-2.3-2.4.md
Labels: size/XS, lgtm

#14733 Update VERSION to 2.4.2
  VERSION
Labels: size/XS, lgtm

#14725 Standardize the logs in the eventing controller
  components/event-publisher-proxy/cmd/event-publisher-proxy/main.go
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/pkg/handlers/eventtype/clean.go
  components/eventing-controller/pkg/handlers/jetstream.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/informers/sync.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go
  components/eventing-controller/pkg/subscriptionmanager/nats/nats.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#14732 Istio sidecar disabled test
  tests/components/istio/.gitignore
  tests/components/istio/features/namespace_disabled_sidecar.feature
  tests/components/istio/istio_installed_test.go
  tests/components/istio/istio_sidecar_test.go
  tests/components/istio/kube_system_sidecar_test.go
  tests/components/istio/test_helpers.go
Labels: size/L, lgtm

#14639 update fast integration tests codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#14705 validate and default buffer limits
  components/telemetry-operator/controllers/logpipeline_controller.go
  components/telemetry-operator/controllers/logpipeline_controller_test.go
  components/telemetry-operator/controllers/suite_test.go
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/fluentbit/config_builder_test.go
  components/telemetry-operator/internal/fluentbit/sections.go
  components/telemetry-operator/internal/fluentbit/sections_test.go
  components/telemetry-operator/internal/sync/sync.go
  components/telemetry-operator/internal/sync/sync_test.go
  components/telemetry-operator/internal/validation/mocks/output_validator.go
  components/telemetry-operator/internal/validation/output_validator.go
  components/telemetry-operator/internal/validation/output_validator_test.go
  components/telemetry-operator/internal/webhook/logpipeline_webhook.go
  components/telemetry-operator/internal/webhook/logpipeline_webhook_test.go
  components/telemetry-operator/internal/webhook/suite_test.go
  components/telemetry-operator/main.go
  resources/telemetry/charts/fluent-bit/values.yaml
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/values.yaml
Labels: size/XL, lgtm

#14312 FIT: add grafana exposure on SKR
  tests/fast-integration/skr-test/commerce-mock/index.js
  tests/fast-integration/skr-test/test.js
Labels: size/S, lgtm

#14739 Improved eventing getting-started guide
  docs/02-get-started/04-trigger-workload-with-event.md
Labels: size/XS, lgtm

#14745 revert adding grafana to SKR
  tests/fast-integration/skr-test/commerce-mock/index.js
  tests/fast-integration/skr-test/test.js
Labels: size/S, lgtm

#14752 updated util image for loki and ory to alpine 3.16.0
  resources/logging/values.yaml
  resources/ory/values.yaml
Labels: size/XS, lgtm

#14756 update to fluent-bit 1.9.5
  components/telemetry-operator/Dockerfile
  resources/logging/values.yaml
  resources/telemetry/charts/fluent-bit/Chart.yaml
  resources/telemetry/values.yaml
Labels: area/logging, size/S, lgtm

#14741 Add kyma-system Istio component tests
  tests/components/istio/features/kyma_system_sidecar.feature
  tests/components/istio/istio_installed_test.go
  tests/components/istio/istio_sidecar_test.go
  tests/components/istio/kube_system_sidecar_test.go
  tests/components/istio/kyma_system_sidecar_test.go
  tests/components/istio/test_helpers.go
Labels: area/service-mesh, size/L, lgtm, area/tests

#14761 Add missing command to the tutorial
  docs/03-tutorials/00-service-management/smgt-01-deploy-service.md
Labels: kind/bug, area/documentation, area/service-management, size/XS, lgtm

#14702 Update Eventing Documentation
  docs/05-technical-reference/00-architecture/assets/evnt-architecture.svg
  docs/05-technical-reference/00-architecture/evnt-01-architecture.md
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
  docs/05-technical-reference/00-custom-resources/evnt-02-eventingbackend.md
Labels: area/documentation, size/M, lgtm

#14706 Added eventing tutorials to docs
  docs/01-overview/main-areas/eventing/evnt-02-useful-links.md
  docs/03-tutorials/00-eventing/evnt-01-send-event-outside-cluster.md
  docs/03-tutorials/00-eventing/evnt-02-setup-in-cluster-eventing.md
  docs/03-tutorials/00-eventing/evnt-02-subs-with-multiple-filters.md
  docs/03-tutorials/00-eventing/evnt-03-introduction-to-jetstream.md
  docs/03-tutorials/00-eventing/evnt-03-type-cleanup.md
  docs/03-tutorials/00-eventing/evnt-04-change-max-in-flight-in-sub.md
  docs/03-tutorials/00-eventing/evnt-05-send-legacy-events.md
  docs/05-technical-reference/00-architecture/evnt-01-architecture.md
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
Labels: size/XL, lgtm

#14765 Fix linting errors in telemetry-operator
  components/telemetry-operator/Makefile
  components/telemetry-operator/controllers/logpipeline_controller.go
  components/telemetry-operator/internal/secret/secret_handling.go
  components/telemetry-operator/internal/sync/sync.go
  components/telemetry-operator/internal/validation/plugin_validator.go
  components/telemetry-operator/internal/validation/plugin_validator_test.go
Labels: size/M, lgtm

#14731 Adjust resources for telemetry-operator and fluent-bit
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/profile-production.yaml
Labels: size/S, lgtm

#14764 Make the port usages consistent across the eventing templates
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/templates/service.yaml
  resources/eventing/charts/controller/templates/servicemonitor.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/nats/templates/service.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
  resources/eventing/charts/publisher-proxy/templates/service.yaml
  resources/eventing/charts/publisher-proxy/templates/servicemonitor.yaml
  resources/eventing/charts/publisher-proxy/values.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#14768 Fix the webhooks ClusterRole
  resources/serverless/charts/webhook/templates/cluster-role.yaml
Labels: kind/bug, size/XS, lgtm

#14767 Prohibited matches in filters and outputs in telemetry-operator
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline_loki.yaml
  components/telemetry-operator/controllers/logpipeline_controller_test.go
  components/telemetry-operator/go.mod
  components/telemetry-operator/go.sum
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/validation/plugin_validator.go
  components/telemetry-operator/internal/validation/plugin_validator_test.go
  resources/logging/charts/loki/templates/kyma-additions/logpipeline_loki.yaml
  resources/logging/charts/loki/values.yaml
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/invalid-log-pipeline.yaml
Labels: size/L, lgtm

#14769 Add Istio sidecar enabled tests and refactor code
  tests/components/istio/README.md
  tests/components/istio/features/kube_system_sidecar.feature
  tests/components/istio/features/kyma_system_sidecar.feature
  tests/components/istio/features/namespace_disabled_sidecar.feature
  tests/components/istio/features/sidecar_injection.feature
  tests/components/istio/istio_installed_test.go
  tests/components/istio/istio_sidecar_test.go
  tests/components/istio/kube_system_sidecar_test.go
  tests/components/istio/kyma_system_sidecar_test.go
  tests/components/istio/main_test.go
  tests/components/istio/test_helpers.go
Labels: area/service-mesh, size/XL, lgtm, area/tests

#14298 Refactor skr-aws-upgrade-integration-dev test - part 2
  tests/fast-integration/compass/client.js
  tests/fast-integration/skr-aws-upgrade-integration/index.js
  tests/fast-integration/skr-aws-upgrade-integration/upgrade/upgrade-skr.js
  tests/fast-integration/skr-test/.env.template
  tests/fast-integration/skr-test/README.md
  tests/fast-integration/skr-test/commerce-mock/index.js
  tests/fast-integration/skr-test/commerce-mock/prep.js
  tests/fast-integration/skr-test/helpers.js
  tests/fast-integration/skr-test/index.js
  tests/fast-integration/skr-test/oidc/index.js
  tests/fast-integration/skr-test/provision/deprovision-skr.js
  tests/fast-integration/skr-test/provision/provision-skr.js
  tests/fast-integration/skr-test/test.js
Labels: size/XL, lgtm

#14777 Enhance Application Connectivity documentation following the new flow introduction
  docs/05-technical-reference/00-architecture/ac-03-application-gateway.md
  docs/05-technical-reference/ac-01-application-gateway-details.md
  docs/05-technical-reference/ra-01-configuring-runtime.md
  milv.config.yaml
Labels: area/documentation, area/application-connector, size/M, lgtm

#14775 Fix flaky integration backend reconciler test
  components/eventing-controller/controllers/backend/reconciler_test.go
  resources/eventing/values.yaml
Labels: size/S, lgtm

#14743 Implement minimal Application Connector test
  CODEOWNERS
  tests/components/application-connector/.dockerignore
  tests/components/application-connector/Dockerfile.gateway
  tests/components/application-connector/Dockerfile.mockapp
  tests/components/application-connector/Makefile
  tests/components/application-connector/README.md
  tests/components/application-connector/assets/app-gateway-tests-architecture.svg
  tests/components/application-connector/go.mod
  tests/components/application-connector/go.sum
  tests/components/application-connector/internal/testkit/test-api/apis.go
  tests/components/application-connector/internal/testkit/test-api/handlers.go
  tests/components/application-connector/internal/testkit/test-api/middleware.go
  tests/components/application-connector/resources/charts/gateway-test/Chart.yaml
  tests/components/application-connector/resources/charts/gateway-test/templates/_helpers.tpl
  tests/components/application-connector/resources/charts/gateway-test/templates/basic-cases.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/service-account.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/test-app.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/test.yml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
  tests/components/application-connector/resources/installation-config/mini-kyma-os.yaml
  tests/components/application-connector/resources/installation-config/mini-kyma-skr.yaml
  tests/components/application-connector/scripts/local-build.sh
  tests/components/application-connector/scripts/wait-for-gateway-tests-finish.sh
  tests/components/application-connector/test/application-gateway/simple_test.go
  tests/components/application-connector/test/application-gateway/suite_test.go
  tests/components/application-connector/tools/external-api-mock-app/config.go
  tests/components/application-connector/tools/external-api-mock-app/server.go
Labels: area/application-connector, size/XXL, lgtm, area/tests

#14734 Updated Eventing Operations Guides
  docs/04-operation-guides/operations/evnt-01-eventing-monitoring.md
  docs/04-operation-guides/troubleshooting/evnt-01-eventing-troubleshooting.md
  docs/04-operation-guides/troubleshooting/evnt-02-jetstream-troubleshooting.md
  docs/04-operation-guides/troubleshooting/evnt-03-type-collision.md
  docs/05-technical-reference/evnt-01-event-names.md
Labels: area/eventing, size/L, lgtm

#14779 improve warn msgs
  components/telemetry-operator/internal/validation/output_validator.go
  components/telemetry-operator/internal/validation/variable_validator.go
  components/telemetry-operator/internal/webhook/logpipeline_webhook.go
Labels: size/S, lgtm

#14778 Introduce dummy input for default log pipeline
  resources/telemetry/charts/fluent-bit/values.yaml
Labels: size/XS, lgtm

#14736 test: use `T.Setenv` to set env vars in tests
  components/eventing-controller/pkg/deployment/publisher_deployment_test.go
  components/eventing-controller/pkg/ems/auth/auth_test.go
  components/eventing-controller/pkg/env/backend_config_test.go
  components/eventing-controller/pkg/env/config_test.go
  components/eventing-controller/pkg/env/nats_config_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_validation_test.go
  resources/eventing/values.yaml
  resources/serverless/values.yaml
Labels: area/serverless, area/eventing, size/M, lgtm, ok-to-test

#14800 update documentation to support kubernetes 1.23
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/operations/10-backup-kyma.md
Labels: size/XS, lgtm

#14803 Fix wrong priorityClassName
  resources/ory/charts/hydra/templates/deployment.yaml
Labels: size/XS, lgtm

#14801 Remove migration guide and scripts for 2.4 from `main` post-release
  docs/05-technical-reference/ra-01-configuring-runtime.md
  docs/assets/2.3-2.4-cleanup-kiali-istio-upgrade.sh
  docs/assets/2.3-2.4-cleanup-orphaned-svcat-resources.sh
  docs/migration-guide-2.3-2.4.md
Labels: area/documentation, size/M, lgtm

#14806 Fix a typo in the Application Gateway URL for the Compass scenario in documentation
  docs/05-technical-reference/ac-01-application-gateway-details.md
  milv.config.yaml
Labels: kind/bug, area/documentation, size/XS, lgtm

#14808 Bump api-gateway to the latest version
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
  resources/api-gateway/values.yaml
Labels: area/api-gateway, size/L, lgtm

#14744 Gherkinize API-gateway tests with Godog
  tests/components/api-gateway/.gitignore
  tests/components/api-gateway/Dockerfile
  tests/components/api-gateway/Makefile
  tests/components/api-gateway/features/oauth2_jwt_1path.feature
  tests/components/api-gateway/features/oauth2_jwt_2path.feature
  tests/components/api-gateway/features/oauth2_secured_endpoint.feature
  tests/components/api-gateway/features/secure_to_unsecure.feature
  tests/components/api-gateway/features/unsecure_to_secure_OAuth2.feature
  tests/components/api-gateway/features/unsecure_to_secure_OAuth2_JWT.feature
  tests/components/api-gateway/features/unsecured_endpoint.feature
  tests/components/api-gateway/gateway-tests/go.mod
  tests/components/api-gateway/gateway-tests/go.sum
  tests/components/api-gateway/gateway-tests/main_test.go
  tests/components/api-gateway/gateway-tests/pkg/api/apitest.go
  tests/components/api-gateway/gateway-tests/pkg/api/apitest_test.go
  tests/components/api-gateway/gateway-tests/pkg/client/client.go
  tests/components/api-gateway/go.mod
  tests/components/api-gateway/go.sum
  tests/components/api-gateway/main_test.go
  tests/components/api-gateway/manifests/global-commons.yaml
  tests/components/api-gateway/manifests/hydra-client.yaml
  tests/components/api-gateway/manifests/jwt-oauth-one-path-strategy.yaml
  tests/components/api-gateway/manifests/jwt-oauth-strategy.yaml
  tests/components/api-gateway/manifests/k8s/deployment.yaml
  tests/components/api-gateway/manifests/k8s/service.yaml
  tests/components/api-gateway/manifests/k8s/virtualservice.yaml
  tests/components/api-gateway/manifests/no_access_strategy.yaml
  tests/components/api-gateway/manifests/oauth-strategy.yaml
  tests/components/api-gateway/manifests/testing-app.yaml
  tests/components/api-gateway/oauth2_jwt_one_path_test.go
  tests/components/api-gateway/oauth2_jwt_two_paths_test.go
  tests/components/api-gateway/oauth2_secured_endpoint_test.go
  tests/components/api-gateway/pkg/client/client.go
  tests/components/api-gateway/pkg/helpers/helpers.go
  tests/components/api-gateway/pkg/jwt/auth.go
  tests/components/api-gateway/pkg/jwt/config.go
  tests/components/api-gateway/pkg/jwt/idtokenprovider.go
  tests/components/api-gateway/pkg/manifestprocessor/processor.go
  tests/components/api-gateway/pkg/resource/batch.go
  tests/components/api-gateway/pkg/resource/manager.go
  tests/components/api-gateway/prepare_local.sh
  tests/components/api-gateway/secure_to_unsecure_test.go
  tests/components/api-gateway/test_helpers.go
  tests/components/api-gateway/unsecured_test.go
  tests/components/api-gateway/unsecured_to_secured_OAuth2_JWT_test.go
  tests/components/api-gateway/unsecured_to_secured_OAuth2_test.go
Labels: area/api-gateway, size/XXL, lgtm, area/tests

#14810 Update kyma overrides version
  tests/fast-integration/eventing-test/prow/config/skr_config.json
Labels: size/XS, lgtm

#14812 Increase timeout while waiting for virtualservice on fast integration tests
  tests/fast-integration/utils/index.js
Labels: size/XS, lgtm

#14829 update kube-openapi in eventing-conrolller
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
Labels: size/M, lgtm

#14781 Update BEB subscription Status to show error messages in the conditions
  components/eventing-controller/api/v1alpha1/condition.go
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/pkg/handlers/sink/validator.go
  components/eventing-controller/pkg/handlers/sink/validator_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#14796 Using short name of stateFn in INFO log
  components/function-controller/internal/controllers/serverless/fsm.go
  components/function-controller/internal/controllers/serverless/fsm_test.go
  resources/serverless/values.yaml
Labels: size/M, lgtm

#14799 Add Application Gateway OAuth tests
  tests/components/application-connector/go.mod
  tests/components/application-connector/go.sum
  tests/components/application-connector/internal/testkit/test-api/apis.go
  tests/components/application-connector/internal/testkit/test-api/oauth.go
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/negative-authorisation.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/positive-authorisation.yml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
  tests/components/application-connector/test/application-gateway/runner_test.go
  tests/components/application-connector/tools/external-api-mock-app/config.go
  tests/components/application-connector/tools/external-api-mock-app/server.go
Labels: area/application-connector, size/L, lgtm, area/tests

#14792 Add Basic with CSRF scenario to the App Gateway tests
  tests/components/application-connector/internal/testkit/test-api/apis.go
  tests/components/application-connector/internal/testkit/test-api/csrf.go
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/negative-authorisation.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/positive-authorisation.yml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/L, lgtm, area/tests

#14837 update to fluentbit 1.9.6
  components/telemetry-operator/Dockerfile
  resources/logging/values.yaml
  resources/telemetry/values.yaml
Labels: area/logging, size/XS, lgtm

#14844 Fast-Integrations-Tests: update code owners; refactor skr-test
  CODEOWNERS
Labels: size/S, lgtm

#14805 Reconcile method unit tests for eventing reconcilers
  components/eventing-controller/api/v1alpha1/condition.go
  components/eventing-controller/api/v1alpha1/condition_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_test.go
  components/eventing-controller/pkg/handlers/mocks/BEBBackend.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#14830 Bump eventing images
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#14835 Rework tests nats subscriber
  components/eventing-controller/controllers/backend/reconciler_test.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/handlers/nats_test.go
  components/eventing-controller/testing/event/cehelper/builder.go
  components/eventing-controller/testing/event/cehelper/converter.go
  components/eventing-controller/testing/subscriber.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#14860 Update Application Connector images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/XS, lgtm

#14859 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#14831 Implement proxying test cases
  tests/components/application-connector/internal/testkit/test-api/apis.go
  tests/components/application-connector/internal/testkit/test-api/handlers.go
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/proxy-errors.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/proxying.yml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
  tests/components/application-connector/test/application-gateway/complex_test.go
  tests/components/application-connector/test/application-gateway/request.go
  tests/components/application-connector/test/application-gateway/runner_test.go
Labels: size/L, lgtm

#14476 Remove old comments from profiles
  resources/serverless/profile-evaluation.yaml
  resources/serverless/profile-production.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#14868 Update the versions of the images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/XS, lgtm

#14850 Add Application Gateway with Request Parameters test
  tests/components/application-connector/go.mod
  tests/components/application-connector/go.sum
  tests/components/application-connector/internal/testkit/test-api/apis.go
  tests/components/application-connector/internal/testkit/test-api/middleware.go
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/negative-authorisation.yml
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/positive-authorisation.yml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
  tests/components/application-connector/tools/external-api-mock-app/config.go
  tests/components/application-connector/tools/external-api-mock-app/server.go
Labels: area/application-connector, size/L, lgtm, area/tests

#14871 Migrate stalebot to actions/stale@v5
  .github/stale.yml
  .github/workflows/stale.yaml
Labels: size/M, lgtm

#14874 Replace PR-* tags for `serverless` resources
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#14861 enable self-metrics for kube-state-metrics
  resources/monitoring/values.yaml
Labels: area/monitoring, size/XS, lgtm

#14880 Added cluster identifiers to logs
  components/telemetry-operator/controllers/telemetry/logpipeline_controller_test.go
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/fluentbit/config_builder_test.go
  resources/telemetry/values.yaml
Labels: size/M, lgtm

#14838 Istio component configuration for sidecar migration
  resources/istio/values.yaml
Labels: area/service-mesh, size/XS, lgtm, area/charts

#14863 Add http output to LogPipeline
  components/telemetry-operator/apis/telemetry/v1alpha1/logpipeline_types.go
  components/telemetry-operator/apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  components/telemetry-operator/config/samples/http-mockserver.yaml
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline_http.yaml
  components/telemetry-operator/controllers/telemetry/logpipeline_controller.go
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/fluentbit/config_builder_test.go
  components/telemetry-operator/internal/secret/secret_handling.go
  components/telemetry-operator/internal/secret/secret_helper.go
  components/telemetry-operator/internal/secret/secret_helper_test.go
  components/telemetry-operator/internal/sync/sync.go
  components/telemetry-operator/internal/sync/sync_test.go
  components/telemetry-operator/internal/validation/plugin_validator.go
  components/telemetry-operator/internal/validation/plugin_validator_test.go
  installation/resources/crds/telemetry/logpipelines.crd.yaml
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/resources/deployments/mockserver.yaml
  tests/fast-integration/telemetry-test/resources/pipelines/http-log-pipeline.yaml
  tests/fast-integration/telemetry-test/telemetry-test.js
Labels: size/XXL, lgtm

#14063 Configurable logging docs
  components/telemetry-operator/README.md
  docs/01-overview/main-areas/observability/README.md
  docs/01-overview/main-areas/observability/assets/telemetry-logging-arch.drawio.svg
  docs/01-overview/main-areas/observability/assets/telemetry-logging-flow.drawio.svg
  docs/01-overview/main-areas/observability/assets/telemetry-logging-pipelines.drawio.svg
  docs/01-overview/main-areas/observability/assets/telemetry-operator-resources.drawio.svg
  docs/01-overview/main-areas/observability/obsv-01-monitoring-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-02-logging-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-03-tracing-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-10-useful-links.md
  docs/03-tutorials/00-observability/assets/monitoring-tutorials.svg
  docs/04-operation-guides/operations/obsv-00-enable-telemetry_component.md
  docs/05-technical-reference/00-architecture/assets/obsv-configurable-logging-architecture.drawio.svg
  docs/05-technical-reference/00-architecture/assets/obsv-kiali-architecture.svg
  docs/05-technical-reference/00-architecture/assets/obsv-logging-architecture.drawio.svg
  docs/05-technical-reference/00-architecture/assets/obsv-logging-architecture.svg
  docs/05-technical-reference/00-architecture/assets/obsv-monitoring-architecture.svg
  docs/05-technical-reference/00-architecture/assets/obsv-monitoring-flow.svg
  docs/05-technical-reference/00-architecture/assets/obsv-monitoring-istio.svg
  docs/05-technical-reference/00-architecture/assets/obsv-prometheus-setup.svg
  docs/05-technical-reference/00-architecture/assets/obsv-tracing-architecture.svg
  docs/05-technical-reference/00-architecture/obsv-01-architecture-monitoring.md
  docs/05-technical-reference/00-architecture/obsv-02-architecture-logging.md
Labels: area/documentation, size/XXL, lgtm

#14889 Bump AC tests images
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/XS, lgtm

#14864 adjust docu to list only the one supported k8s version
  docs/04-operation-guides/operations/02-install-kyma.md
Labels: size/XS, lgtm

#14891 Updated eventing monitoring operations guide
  components/telemetry-operator/README.md
  docs/04-operation-guides/operations/evnt-01-eventing-monitoring.md
Labels: size/XS, lgtm

#14840 bump golang version and dependencies in `eventing-publisher-proxy`
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  resources/eventing/values.yaml
Labels: size/XL, lgtm

#14875 fix the validation problem with parsers
  components/telemetry-operator/controllers/telemetry/logparser_controller.go
  components/telemetry-operator/internal/fluentbit/config_builder.go
  components/telemetry-operator/internal/fluentbit/utils.go
  components/telemetry-operator/internal/parserSync/parser.go
  components/telemetry-operator/internal/validation/config_validator.go
  components/telemetry-operator/internal/webhook/logparser_webhook.go
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#14895 Fix typos in the _Register a secured API_ tutorial
  docs/03-tutorials/00-application-connectivity/ac-04-register-secured-api.md
Labels: kind/bug, area/documentation, area/application-connector, size/XS, lgtm

#14897 Update Eventing images
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#14867 Implement verbs tests
  tests/components/application-connector/resources/charts/gateway-test/templates/applications/methods-with-body.yml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
  tests/components/application-connector/scripts/check-pod-logs.sh
  tests/components/application-connector/test/application-gateway/request.go
  tests/components/application-connector/test/application-gateway/runner_test.go
Labels: size/M, lgtm

#14901 Remove PR images for release
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: size/XS, lgtm

#14899 Oathkeeper and Hydra disable condition
  resources/ory/Chart.yaml
  resources/ory/charts/hydra/templates/hydra-virtualservice.yaml
  resources/ory/values.yaml
Labels: size/S, lgtm

#14906 Fix helm
  resources/ory/templates/monitoring-hydra.yaml
  resources/ory/templates/monitoring-oathkeeper.yaml
Labels: size/XS, lgtm

#14902 Upgrade nodejs versions
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
  resources/serverless/values.yaml
Labels: size/S, lgtm

#14910 Upgrade serverless image tags
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#14848 Initial two-way conversion implementation
  components/function-controller/cmd/webhook/main.go
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  components/function-controller/internal/webhook/resources/webhook_config.go
  components/function-controller/internal/webhook/version_converter.go
  installation/resources/crds/serverless/gitrepositories.serverless.crd.yaml
  resources/serverless/charts/webhook/templates/cluster-role.yaml
  resources/serverless/values.yaml
Labels: size/XXL, lgtm

#14914 Reduce istio resource consumption
  resources/istio/profile-evaluation.yaml
  resources/istio/profile-production.yaml
  resources/istio/values.yaml
Labels: size/S, lgtm

#14915 Fix linting errors in telemetry-operator
  components/telemetry-operator/internal/secret/secret_helper.go
  components/telemetry-operator/internal/validation/plugin_validator.go
  components/telemetry-operator/internal/webhook/logparser_webhook.go
  components/telemetry-operator/internal/webhook/logpipeline_webhook.go
Labels: size/M, lgtm

#14916 Reduce istio resource consumption (#14914)
  resources/istio/profile-evaluation.yaml
  resources/istio/profile-production.yaml
  resources/istio/values.yaml
Labels: size/S, lgtm

#14919 Prepare for Kyma release 2.5.0-rc2
  VERSION
Labels: size/XS, lgtm

#14918 added extensionProviders for envoy access logs to have logs in JSON format
  docs/04-operation-guides/operations/obsv-03-enable-istio-access-logs.md
  resources/istio/values.yaml
Labels: size/S, lgtm

#14920 Upgrade nodejs versions
  components/function-runtimes/nodejs12/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
Labels: size/XS, lgtm

#14834 Update Eventing Overview Documentation
  docs/01-overview/main-areas/eventing/README.md
  docs/01-overview/main-areas/eventing/assets/pubsub.svg
  docs/01-overview/main-areas/eventing/evnt-01-overview.md
  docs/01-overview/main-areas/eventing/evnt-90-glossary.md
  docs/01-overview/main-areas/eventing/evnt-99-useful-links.md
Labels: area/documentation, area/eventing, size/M, lgtm

#14922 Upgrade serverless image tags
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#14923 added extensionProviders for envoy access logs to have logs in JSON format
  docs/04-operation-guides/operations/obsv-03-enable-istio-access-logs.md
  resources/istio/values.yaml
Labels: size/S, lgtm

#14881 Remove the omitempty from SubscriptionStatus CleanEventTypes
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/api/v1alpha1/subscription_types_test.go
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/controllers/backend/reconciler_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_test.go
  components/eventing-controller/controllers/subscription/nats/reconciler.go
  components/eventing-controller/controllers/subscription/nats/reconciler_test.go
  components/eventing-controller/controllers/subscription/testing/test_utils.go
  components/eventing-controller/pkg/handlers/beb.go
  components/eventing-controller/pkg/handlers/jetstream_test.go
  components/eventing-controller/pkg/handlers/nats.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb_test.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream_test.go
  components/eventing-controller/pkg/subscriptionmanager/nats/nats_test.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#14913 Add schema validation for jwks_urls and trusted_issuers for jwt handler
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
  resources/api-gateway/values.yaml
Labels: area/api-gateway, size/S, lgtm, area/crds

#14926 added extensionProviders for envoy access logs to have logs in JSON format
  resources/istio/values.yaml
Labels: size/XS, lgtm

#14932 bump golang to 1.18.3
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
Labels: size/XS, lgtm

#14839 bump golang version and dependencies in `eventing-controller`
  components/eventing-controller/config/crd/external/apirules-gateway-kyma-project-io.yaml
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/XL, lgtm

#14935 prepare 2.4 branch for next patch release
  VERSION
Labels: size/XS, lgtm

#14944 Logger dependency bump
  common/go.mod
  common/go.sum
  common/logging/go.mod
  common/logging/go.sum
Labels: size/L, lgtm

#14943 Logger dependency bump
  common/go.mod
  common/go.sum
  common/logging/go.mod
  common/logging/go.sum
Labels: size/L, lgtm

#14951 Add the `npm_config_cache` env for nodejs16 runtimes
  components/function-runtimes/nodejs16/Dockerfile
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#14952 Add the `npm_config_cache` env for nodejs16 runtimes
  components/function-runtimes/nodejs16/Dockerfile
Labels: size/XS, lgtm

#14948 Using lastet common/logger package and latest version of golang.org/x/net
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
Labels: size/M, lgtm

#14954 Add the `npm_config_cache env` for nodejs16 runtimes
  components/function-runtimes/nodejs16/Dockerfile
Labels: size/XS, lgtm

#14945 Using lastet common/logger package and latest version of golang.org/x/net
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  resources/application-connector/values.yaml
Labels: size/M, lgtm

#14955 Bump serverless resources
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#14956 Bump serverless resources
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#14957 Bump image of app connectivity validator to use latest image build for release 2.4
  resources/application-connector/values.yaml
Labels: size/XS, lgtm

#14958 Update dependencies to newer versions for kyma/common module on release-2.5
  common/go.mod
  common/go.sum
  common/logging/go.mod
  common/logging/go.sum
Labels: size/L, lgtm

#14967 revert changes in makefiles
  tests/application-gateway-tests/Makefile
  tests/telemetry-operator-perf-tests/Makefile
Labels: size/XS, lgtm

#14959 Using latest common/logger package and latest version of golang.org/x/net
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
Labels: size/M, lgtm

#14917 Update event Types Summary dashboard and promql queries
  resources/eventing/charts/dashboards/templates/eventTypesSummary.yaml
  tests/fast-integration/eventing-test/nats-dashboard-queries.json
Labels: area/eventing, size/M, lgtm

#14968 Delete space in makefiles
  tests/application-gateway-tests/Makefile
  tests/telemetry-operator-perf-tests/Makefile
Labels: size/XS, lgtm

#14969 Bump image of app connectivity validator to use latest image build for release 2.5
  resources/application-connector/values.yaml
Labels: size/XS, lgtm

#14908 Add troubleshooting guide for how to free JS storage
  components/event-publisher-proxy/pkg/sender/jetstream.go
  docs/04-operation-guides/troubleshooting/eventing/evnt-04-free-jetstream-storage.md
  resources/eventing/values.yaml
Labels: area/documentation, area/eventing, size/M, lgtm

#14970 Fix crd generation
  components/function-controller/Makefile
  components/function-controller/config/crd/crd-serverless.yaml
  components/function-controller/config/crd/kustomization.yaml
  components/function-controller/config/crd/patches/conversion_webhook_function.yaml
  components/function-controller/config/crd/serverless.kyma-project.io_gitrepositories.yaml
  installation/resources/crds/serverless/crd-serverless.yaml
  installation/resources/crds/serverless/gitrepositories.serverless.crd.yaml
Labels: size/XL, lgtm

#14930 Upgrade controller gen to v0.6.2
  components/function-controller/Makefile
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/crd/bases/serverless.kyma-project.io_gitrepositories.yaml
  components/function-controller/config/crd/crd-serverless.yaml
  components/function-controller/config/webhook/manifests.yaml
  components/function-controller/go.sum
  components/function-controller/internal/webhook/remote_registry_cfg_webhook.go
  components/function-controller/pkg/apis/serverless/v1alpha1/gitrepository_types.go
  components/function-controller/pkg/apis/serverless/v1alpha1/zz_generated.deepcopy.go
  components/function-controller/pkg/apis/serverless/v1alpha2/zz_generated.deepcopy.go
  installation/resources/crds/serverless/crd-serverless.yaml
Labels: size/M, lgtm

#14971 Change version to rc3
  VERSION
Labels: size/XS, lgtm

#14942 Add unit test for auth removal
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  resources/serverless/values.yaml
Labels: size/M, lgtm

#14924 Add Git Repository update controller
  components/function-controller/cmd/manager/main.go
  components/function-controller/internal/controllers/serverless/gitrepo/git_repo_controller.go
  components/function-controller/internal/controllers/serverless/gitrepo/git_repo_controller_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#14950 Serverless deprecate v1alpha1
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/crd/bases/serverless.kyma-project.io_gitrepositories.yaml
  components/function-controller/config/crd/crd-serverless.yaml
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha1/gitrepository_types.go
  installation/resources/crds/serverless/crd-serverless.yaml
Labels: size/S, lgtm
