Repository kyma-project/kyma, pull requests merged in 2023-06, with the labels that each got.

#17597 Add namespace to docker-registry sub chart
  resources/serverless/charts/docker-registry/templates/configmap.yaml
  resources/serverless/charts/docker-registry/templates/cronjob.yaml
  resources/serverless/charts/docker-registry/templates/deployment.yaml
  resources/serverless/charts/docker-registry/templates/ingress.yaml
  resources/serverless/charts/docker-registry/templates/poddisruptionbudget.yaml
  resources/serverless/charts/docker-registry/templates/pvc.yaml
  resources/serverless/charts/docker-registry/templates/secret.yaml
  resources/serverless/charts/docker-registry/templates/service.yaml
Labels: size/XS, lgtm

#17599 bump eventing images for `rel2.15`
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#17602 Serverless: merge production and remove profiles
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/profile-evaluation.yaml
  resources/serverless/profile-production.yaml
  resources/serverless/values.yaml
Labels: size/M, lgtm

#17604 Update Oathkeeper & AWS LB on Istio GW connection timeout settings
  resources/istio/templates/istio-operator.yaml
  resources/ory/values.yaml
Labels: size/XS, lgtm

#17260 Refactor registry related envs
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  components/function-controller/internal/controllers/serverless/function_reconcile_asserts_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/suite_test.go
  resources/serverless/charts/docker-registry/templates/deployment.yaml
  resources/serverless/templates/registry-config.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#17605 Fix broken links
  docs/03-tutorials/00-serverless/svls-07-set-external-registry.md
  docs/03-tutorials/00-serverless/svls-08-switch-to-external-registry.md
Labels: size/S, lgtm

#17608 bump images for release 2.15
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17612 fix description for subscription extension
  resources/eventing/charts/controller/templates/busola-extension.yaml
Labels: size/XS, lgtm

#17609 [Telemetry Manager] Only rotate server cert upon expiry
  resources/telemetry/values.yaml
Labels: size/XS, lgtm, area/telemetry

#17563 Increase memory limit for telemetry operator
  resources/telemetry/charts/operator/values.yaml
Labels: size/XS, lgtm, area/telemetry

#17571 Rename beb to eventmesh in ec
  components/eventing-controller/api/v1alpha1/fixtures_test.go
  components/eventing-controller/api/v1alpha1/subscription_conversion.go
  components/eventing-controller/api/v1alpha1/subscription_conversion_unit_test.go
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/api/v1alpha1/subscription_types_unit_test.go
  components/eventing-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/eventing-controller/api/v1alpha2/status_types.go
  components/eventing-controller/api/v1alpha2/subscription_webhook_unit_test.go
  components/eventing-controller/api/v1alpha2/zz_generated.deepcopy.go
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/config/crd/external/apirules-gateway-kyma-project-io.yaml
  components/eventing-controller/config/crd/external/applications-applicationconnector-kyma-project-io.yaml
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/subscription/eventmesh/reconciler.go
  components/eventing-controller/controllers/subscription/eventmesh/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/subscription/eventmesh/test/reconciler_integration_test.go
  components/eventing-controller/controllers/subscription/eventmesh/test/utils.go
  components/eventing-controller/pkg/backend/eventmesh/eventmesh.go
  components/eventing-controller/pkg/backend/eventmesh/eventmesh_integration_test.go
  components/eventing-controller/pkg/backend/eventmesh/utils.go
  components/eventing-controller/pkg/backend/eventmesh/utils_unit_test.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils_test.go
  components/eventing-controller/pkg/deployment/publisher_deployment_integration_test.go
  components/eventing-controller/pkg/subscriptionmanager/eventmesh/eventmesh.go
  components/eventing-controller/pkg/subscriptionmanager/eventmesh/eventmesh_test.go
  components/eventing-controller/testing/eventmesh_unit_test.go
  components/eventing-controller/testing/eventmeshmock.go
  components/eventing-controller/testing/test_helpers.go
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/eventing/values.yaml
Labels: size/XL, lgtm

#17613 fix description for subscription extension
  resources/eventing/charts/controller/templates/busola-extension.yaml
Labels: size/XS, lgtm

#17603 Upgrade eventing-webhook-certificates image
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#17622 Add a warning about the Ory stack deprecation
  docs/01-overview/main-areas/api-exposure/apix-01-api-gateway.md
Labels: size/XS, lgtm

#17600 Fast integration BTP Manager Secret tests
  tests/fast-integration/skr-test/btp-manager-secret/index.js
  tests/fast-integration/skr-test/index.js
  tests/fast-integration/skr-test/test.js
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#17625 Update VERSION to 2.15.0
  VERSION
Labels: size/XS, lgtm

#17598 Add Eventing auth manager feature flag
  components/eventing-controller/Dockerfile
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/backend/reconciler_internal_unit_test.go
  components/eventing-controller/controllers/subscription/eventmesh/test/reconciler_integration_test.go
  components/eventing-controller/controllers/subscription/eventmesh/test/utils.go
  components/eventing-controller/internal/featureflags/featureflags.go
  components/eventing-controller/pkg/backend/eventmesh/eventmesh.go
  components/eventing-controller/pkg/backend/eventmesh/types.go
  components/eventing-controller/pkg/env/backend_config.go
  components/eventing-controller/pkg/env/config.go
  components/eventing-controller/pkg/subscriptionmanager/eventmesh/eventmesh.go
  components/eventing-controller/pkg/subscriptionmanager/manager.go
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/values.yaml
Labels: kind/feature, area/eventing, size/L, lgtm

#17630 remove migration guide 2.14-2.15 from main
  docs/assets/2.14-2.15-cleanup-telemetry.sh
  docs/migration-guide-2.14-2.15.md
Labels: size/S, lgtm

#17631 Make excluded Fluent Bit container more specific
  resources/telemetry/values.yaml
Labels: area/logging, size/XS, lgtm, area/telemetry

#17633 Move loki logpipeline to telemetry module
  resources/logging/charts/loki/templates/kyma-additions/logpipeline_loki.yaml
  resources/telemetry/values.yaml
Labels: area/logging, size/S, lgtm, area/telemetry

#17629 update images with newer golang and alpine version, otel-collector 0.79.0
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/telemetry/values.yaml
Labels: area/monitoring, area/logging, size/S, lgtm, area/telemetry

#17635 Bump btp-manager to 0.4.2
  resources/btp-manager/values.yaml
Labels: size/XS, lgtm

#17593 rename to eventmesh in epp
  components/event-publisher-proxy/cmd/event-publisher-proxy/main.go
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/event-publisher-proxy/pkg/cloudevents/utils_test.go
  components/event-publisher-proxy/pkg/commander/eventmesh/eventmesh.go
  components/event-publisher-proxy/pkg/env/eventmesh_config.go
  components/event-publisher-proxy/pkg/env/nats_config.go
  components/event-publisher-proxy/pkg/eventmesh/types.go
  components/event-publisher-proxy/pkg/legacy/legacy.go
  components/event-publisher-proxy/pkg/legacy/legacy_test.go
  components/event-publisher-proxy/pkg/sender/eventmesh/eventmesh.go
  components/event-publisher-proxy/pkg/subscribed/helpers_test.go
  components/event-publisher-proxy/testing/env_config.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#17634 updates golang-runtime images in application connector components to …
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/S, lgtm

#17638 Bump dependencies
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  resources/eventing/values.yaml
Labels: size/M, lgtm

#17645 update directory-size-exporter to golang 1.20.5
  resources/telemetry/values.yaml
Labels: size/XS, lgtm, area/telemetry

#17621 Remove api-gateway tests
  tests/components/api-gateway/.gitignore
  tests/components/api-gateway/Makefile
  tests/components/api-gateway/README.md
  tests/components/api-gateway/custom_domain_test.go
  tests/components/api-gateway/custom_domain_test_env.sh
  tests/components/api-gateway/features/api-gateway/oauth2_jwt_1path.feature
  tests/components/api-gateway/features/api-gateway/oauth2_jwt_2path.feature
  tests/components/api-gateway/features/api-gateway/oauth2_secured_endpoint.feature
  tests/components/api-gateway/features/api-gateway/secure_to_unsecure.feature
  tests/components/api-gateway/features/api-gateway/service_per_path.feature
  tests/components/api-gateway/features/api-gateway/unsecure_to_secure_OAuth2.feature
  tests/components/api-gateway/features/api-gateway/unsecure_to_secure_OAuth2_JWT.feature
  tests/components/api-gateway/features/api-gateway/unsecured_endpoint.feature
  tests/components/api-gateway/features/e2e/custom_domain.feature
  tests/components/api-gateway/go.mod
  tests/components/api-gateway/go.sum
  tests/components/api-gateway/main_test.go
  tests/components/api-gateway/manifests/custom-domain/resources.yaml
  tests/components/api-gateway/manifests/global-commons.yaml
  tests/components/api-gateway/manifests/hydra-client.yaml
  tests/components/api-gateway/manifests/jwt-oauth-one-path-strategy.yaml
  tests/components/api-gateway/manifests/jwt-oauth-strategy.yaml
  tests/components/api-gateway/manifests/k8s/deployment.yaml
  tests/components/api-gateway/manifests/k8s/service.yaml
  tests/components/api-gateway/manifests/k8s/virtualservice.yaml
  tests/components/api-gateway/manifests/no_access_strategy.yaml
  tests/components/api-gateway/manifests/oauth-strategy.yaml
  tests/components/api-gateway/manifests/oauth2-secured-endpoint.yaml
  tests/components/api-gateway/manifests/testing-app.yaml
  tests/components/api-gateway/manifests/two-services-deployment.yaml
  tests/components/api-gateway/manifests/two-services.yaml
  tests/components/api-gateway/oauth2_jwt_one_path_test.go
  tests/components/api-gateway/oauth2_jwt_two_paths_test.go
  tests/components/api-gateway/oauth2_secured_endpoint_test.go
  tests/components/api-gateway/pkg/client/client.go
  tests/components/api-gateway/pkg/helpers/helpers.go
  tests/components/api-gateway/pkg/helpers/loadbalancer.go
  tests/components/api-gateway/pkg/jwt/auth.go
  tests/components/api-gateway/pkg/jwt/config.go
  tests/components/api-gateway/pkg/jwt/idtokenprovider.go
  tests/components/api-gateway/pkg/manifestprocessor/processor.go
  tests/components/api-gateway/pkg/resource/batch.go
  tests/components/api-gateway/pkg/resource/manager.go
  tests/components/api-gateway/prepare_local.sh
  tests/components/api-gateway/secure_to_unsecure_test.go
  tests/components/api-gateway/service_override_test.go
  tests/components/api-gateway/service_per_path_test.go
  tests/components/api-gateway/test_helpers.go
  tests/components/api-gateway/unsecured_test.go
  tests/components/api-gateway/unsecured_to_secured_OAuth2_JWT_test.go
  tests/components/api-gateway/unsecured_to_secured_OAuth2_test.go
Labels: size/XXL, lgtm

#17658 update fluentbit to 2.1.4
  resources/telemetry/values.yaml
Labels: area/logging, size/XS, lgtm, area/telemetry

#17659 Bump keda manager image in security config
  resources/keda-manager/values.yaml
Labels: size/XS, lgtm

#17660 Bump keda manager image in security config
  resources/keda-manager/values.yaml
Labels: size/XS, lgtm

#17663 Fix broken link
  resources/ory/charts/postgresql/README.md
Labels: size/XS, lgtm

#17668 Omit Dev Dependencies in nodejs runtimes
  resources/serverless/templates/runtimes.yaml
Labels: area/serverless, size/XS, lgtm, kind/cleanup

#17670 Bump Istio to 1.18
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: kind/feature, area/service-mesh, size/S, lgtm

#17681 Use newest golang
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  resources/serverless/values.yaml
Labels: size/M, lgtm

#17683 use newest golang
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
Labels: size/S, lgtm

#17684 App-conn area dependabot images bumps
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/M, lgtm, kind/chore

#17685 Bump images
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17682 Update Eventing deps
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm, area/dependency

#17661 Refine application-connector and compass-runtime-agent charts
  resources/application-connector/charts/central-application-gateway/templates/rbac.yaml
  resources/compass-runtime-agent/templates/resources-role-binding.yaml
  resources/compass-runtime-agent/templates/role-binding.yaml
Labels: area/application-connector, lgtm

#17680 Bump BTP manager to 0.4.3
  resources/btp-manager/values.yaml
Labels: size/XS, lgtm

#17693 2.15 bump alpine
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/nodejs/nodejs16/Dockerfile
  components/function-runtimes/nodejs/nodejs18/Dockerfile
Labels: size/S, lgtm

#17694 use post main images
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17692 Use newest alpine
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/nodejs/nodejs16/Dockerfile
  components/function-runtimes/nodejs/nodejs18/Dockerfile
  resources/serverless/values.yaml
Labels: size/M, lgtm

#17704 bump python
  components/function-runtimes/python39/Dockerfile
Labels: size/XS, lgtm

#17705 Update Keda Version in Keda-Manager resources
  resources/keda-manager/values.yaml
Labels: size/XS, lgtm

#17707 Bump gce-proxy to 1.33.8
  resources/ory/values.yaml
Labels: area/api-gateway, size/XS, lgtm, kind/chore

#17706 bump python image and update nodejs
  components/function-runtimes/nodejs/nodejs16/Dockerfile
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17712 Bump nodejs
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17713 Bump gce-proxy to 1.33.8
  resources/ory/values.yaml
Labels: size/XS, lgtm

#17716 bump
  components/function-runtimes/nodejs/nodejs18/Dockerfile
Labels: size/XS, lgtm

#17717 bump
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17718 Use newest versions of runtime
  components/function-runtimes/nodejs/nodejs16/Dockerfile
  components/function-runtimes/nodejs/nodejs18/Dockerfile
  components/function-runtimes/python39/Dockerfile
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17719 add networkpolicy to rbac role, fix webhook clusterrole
  resources/telemetry/charts/operator/templates/role.yaml
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#17696 update nats-server to 2.9.18
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#17722 Bump api-gateway image to 1.6.1
  resources/api-gateway/values.yaml
Labels: size/XS, lgtm

#17721 Bump api-gateway image to 1.6.1
  resources/api-gateway/values.yaml
Labels: size/XS, lgtm

#17723 update nats-server to 2.9.18
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#17720 Update supported version of Kubernetes to 1.26
  docs/04-operation-guides/operations/02-install-kyma.md
Labels: size/XS, lgtm

#17727 update telemetry manager clusterrole to include replicasets
  resources/telemetry/charts/operator/templates/role.yaml
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#17726 Fix eventing upgrade test flaky
  tests/fast-integration/test/fixtures/jaeger/jaeger.yaml
Labels: size/XS, lgtm

#17703 remove git repository CR description
  docs/01-overview/main-areas/serverless/svls-05-useful-links.md
  docs/05-technical-reference/00-architecture/svls-01-architecture.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  docs/05-technical-reference/00-custom-resources/svls-02-gitrepository.md
  docs/05-technical-reference/svls-03-switching-registries.md
  docs/05-technical-reference/svls-04-git-source-type.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
  docs/05-technical-reference/svls-07-supported-webhooks.md
Labels: area/documentation, size/L, lgtm

#17728 Remove overriding telemetry-trace-collector resources
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/values.yaml
Labels: size/S, lgtm

#17729 Update k8s and kubectl to 1.26 in the documentation
  docs/02-get-started/README.md
  docs/03-tutorials/00-service-management/smgt-01-deploy-service.md
Labels: size/XS, lgtm

#17730 Delete modules folder
  modules/README.md
  modules/alpha/kustomization.yaml
  modules/alpha/moduletemplate-keda.yaml
  modules/fast/kustomization.yaml
  modules/kustomization.yaml
  modules/regular/kustomization.yaml
Labels: size/L, lgtm

#17697 App conn dependabot bumps 20.06.2023
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#17739 Bump k8s-tools image in Kyma 2.15
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17738 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17741 Bump kube-state-metrics to latest golang version
  resources/monitoring/values.yaml
Labels: size/XS, lgtm, area/telemetry

#17714 Update api gateway to 1.7.1
  resources/api-gateway/Chart.yaml
  resources/api-gateway/values.yaml
Labels: kind/feature, area/api-gateway, size/XS, lgtm

#17743 Update TracePipeline limits in docs
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
Labels: size/XS, lgtm

#17745 Change VERSION to 2.15.1
  VERSION
Labels: size/XS, lgtm

#17746 Remove nodejs14 from docs
  docs/01-overview/main-areas/serverless/svls-02-from-code-to-function.md
  docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
  docs/05-technical-reference/svls-04-git-source-type.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
  docs/05-technical-reference/svls-08-function-specification.md
Labels: size/S, lgtm

#17715 Add module installation steps to Quick Install
  docs/02-get-started/01-quick-install.md
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/operations/05-upgrade-kyma.md
  docs/04-operation-guides/operations/07-uninstall-kyma.md
  docs/04-operation-guides/operations/08-install-uninstall-upgrade-kyma-module.md
Labels: area/documentation, size/M, lgtm, docs/modularization

#17750 Pass more info to the Function status when service can't be created
  components/function-controller/internal/controllers/serverless/service.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
Labels: size/S, lgtm

#17744 Remove nodejs14
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/function-controller/internal/controllers/serverless/runtime/runtime.go
  components/function-controller/internal/controllers/serverless/runtime/runtime_test.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/runtime_validation.go
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/nodejs14/docker-entrypoint.sh
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/.gitignore
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/kubeless.js
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/lib/ce.js
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/lib/helper.js
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/lib/tracer.js
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/package-lock.json
  components/function-runtimes/nodejs14/kubeless/kubeless_rt/package.json
  resources/serverless/templates/busola-serverless-extension.yaml
  resources/serverless/templates/runtimes.yaml
  resources/serverless/values.yaml
  tests/function-controller/testsuite/scenarios/gitauth.go
  tests/function-controller/testsuite/scenarios/light_runtimes.go
Labels: size/XXL, lgtm

#17754 Document the ServiceFailed condition
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
Labels: size/XS, lgtm

#17753 Update serverless images
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17756 Update installation links
  docs/02-get-started/01-quick-install.md
Labels: size/XS, lgtm

#17760 Fix link
  docs/04-operation-guides/operations/08-install-uninstall-upgrade-kyma-module.md
Labels: size/XS, lgtm

#17758 Deprecate nodejs16
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/03-tutorials/00-api-exposure/apix-01-create-workload.md
  docs/03-tutorials/00-api-exposure/assets/function.yaml
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
  docs/03-tutorials/00-eventing/evnt-03-type-cleanup.md
  docs/03-tutorials/00-eventing/evnt-04-change-max-in-flight-in-sub.md
  docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
  docs/03-tutorials/00-serverless/svls-02-create-git-function.md
  docs/03-tutorials/00-serverless/svls-09-log-into-private-packages-registry.md
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
  docs/03-tutorials/00-serverless/svls-14-inject-envs.md
  docs/03-tutorials/00-serverless/svls-15-use-external-scalers.md
  docs/04-operation-guides/troubleshooting/serverless/svls-02-failing-function-container.md
  docs/04-operation-guides/troubleshooting/serverless/svls-03-function-debugger-in-strange-location.md
  docs/04-operation-guides/troubleshooting/serverless/svls-04-function-build-failing-on-k3d.md
  docs/05-technical-reference/00-configuration-parameters/svls-02-environment-variables.md
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  docs/05-technical-reference/svls-01-sample-functions.md
  docs/05-technical-reference/svls-02-function-processing-stages.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
  docs/05-technical-reference/svls-07-supported-webhooks.md
  docs/05-technical-reference/svls-08-function-specification.md
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/templates/busola-serverless-extension.yaml
  resources/serverless/templates/crds.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#17761 Change links to module installation
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/operations/05-upgrade-kyma.md
  docs/04-operation-guides/operations/07-uninstall-kyma.md
Labels: size/XS, lgtm

#17759 update to node-exporter 1.6.0
  resources/monitoring/charts/prometheus-istio/values.yaml
  resources/monitoring/charts/prometheus-node-exporter/Chart.yaml
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#17766 Bump k8s-sidecar image to Python 3.11.4
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#17769 Change the table of modules
  docs/README.md
Labels: size/XS, lgtm

#17772 fix eventing upgrade test flaky (#17726)
  tests/fast-integration/test/fixtures/jaeger/jaeger.yaml
Labels: size/XS, lgtm

#17771 Add logg and unify names
  tests/function-controller/cmd/main.go
Labels: size/S, lgtm

#17764 Remove PR images from Application Connector resources
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/S, lgtm

#17767 Remove nodejs14
  components/function-runtimes/Makefile
  tests/fast-integration/monitoring/prometheus.js
  tests/fast-integration/test/fixtures/getting-started-guide/xf-mocks.yaml
  tests/serverless-bench/fixtures/serverless-benchmark-job.yaml
Labels: size/S, lgtm

#17774 Ignore results of tracing tests in Eventing fast-integration tests - Rel-2.15
  tests/fast-integration/eventing-test/eventing-test.js
Labels: size/S, lgtm

#17773 Ignore results of tracing tests in Eventing fast-integration tests
  tests/fast-integration/eventing-test/eventing-test.js
Labels: size/S, lgtm

#17778 Fix the links to Keda and BTP Operator docu
  docs/01-overview/README.md
  docs/README.md
Labels: size/S, lgtm

#17780 update kube-state-metrics to 2.9.2
  resources/monitoring/charts/kube-state-metrics/Chart.yaml
  resources/monitoring/charts/kube-state-metrics/values.yaml
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#17777 Update telemetry-operator to exclude pending pipelines from config
  resources/telemetry/values.yaml
Labels: size/XS, lgtm, area/telemetry

#17785 remove PR images in eventing
  resources/eventing/values.yaml
Labels: size/S, lgtm
