Repository kyma-project/kyma, pull requests merged in 2023-12, with the labels that each got.

#18446 Remove modularized eventing content
  CODEOWNERS
  README.md
  components/eventing-controller/Makefile
  hack/table-gen/Makefile
  installation/resources/components.yaml
  installation/resources/crds/eventing/eventingbackends.eventing.kyma-project.io.crd.yaml
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/eventing/.helmignore
  resources/eventing/Chart.yaml
  resources/eventing/README.md
  resources/eventing/charts/controller/.helmignore
  resources/eventing/charts/controller/Chart.yaml
  resources/eventing/charts/controller/templates/_helpers.tpl
  resources/eventing/charts/controller/templates/busola-extension.yaml
  resources/eventing/charts/controller/templates/clusterrole.yaml
  resources/eventing/charts/controller/templates/clusterrolebinding.yaml
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/templates/eventingbackend.yaml
  resources/eventing/charts/controller/templates/oauth2-client.yaml
  resources/eventing/charts/controller/templates/peerauthentication.yaml
  resources/eventing/charts/controller/templates/service.yaml
  resources/eventing/charts/controller/templates/serviceaccount.yaml
  resources/eventing/charts/controller/templates/webhook-cert-handler.yaml
  resources/eventing/charts/controller/templates/webhook.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/nats/.helmignore
  resources/eventing/charts/nats/Chart.yaml
  resources/eventing/charts/nats/README.md
  resources/eventing/charts/nats/templates/_helpers.tpl
  resources/eventing/charts/nats/templates/configmap.yaml
  resources/eventing/charts/nats/templates/destination-rule.yaml
  resources/eventing/charts/nats/templates/service.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
  resources/eventing/charts/publisher-proxy/.helmignore
  resources/eventing/charts/publisher-proxy/Chart.yaml
  resources/eventing/charts/publisher-proxy/templates/_helpers.tpl
  resources/eventing/charts/publisher-proxy/templates/clusterrole.yaml
  resources/eventing/charts/publisher-proxy/templates/clusterrolebinding.yaml
  resources/eventing/charts/publisher-proxy/templates/peerauthentication.yaml
  resources/eventing/charts/publisher-proxy/templates/service.yaml
  resources/eventing/charts/publisher-proxy/templates/serviceaccount.yaml
  resources/eventing/charts/publisher-proxy/values.yaml
  resources/eventing/profile-evaluation.yaml
  resources/eventing/profile-production.yaml
  resources/eventing/templates/_helpers.tpl
  resources/eventing/templates/configmap.yaml
  resources/eventing/templates/legacy-eventing-secret.yaml
  resources/eventing/templates/priority-class.yaml
  resources/eventing/values.yaml
Labels: size/XXL, lgtm, cla: yes

#18452 Move Istio to the Modules section
  README.md
  docs/01-overview/_sidebar1.md
  docs/01-overview/service-mesh/README.md
  docs/02-get-started/README.md
  docs/04-operation-guides/operations/README.md
  docs/04-operation-guides/operations/_sidebar1.md
  docs/04-operation-guides/security/README.md
  docs/04-operation-guides/security/_sidebar1.md
  docs/04-operation-guides/troubleshooting/README.md
  docs/04-operation-guides/troubleshooting/_sidebar1.md
  docs/05-technical-reference/00-configuration-parameters/_sidebar1.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/_sidebar1.md
  docs/06-modules/README.md
  docs/_sidebar.md
Labels: size/M, lgtm, cla: yes

#18459 Update golang libraries for application-connector to latest versions
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
Labels: size/L, lgtm, cla: yes

#18456 Remove service management docu
  docs/01-overview/README.md
  docs/01-overview/_sidebar1.md
  docs/01-overview/service-management/README.md
  docs/01-overview/service-management/metadata.yaml
  docs/01-overview/service-management/smgt-01-overview.md
  docs/01-overview/service-management/smgt-99-useful-links.md
  docs/03-tutorials/00-service-management/README.md
  docs/03-tutorials/00-service-management/metadata.yaml
  docs/03-tutorials/00-service-management/smgt-01-deploy-service.md
  docs/03-tutorials/_sidebar1.md
  docs/_sidebar.md
Labels: area/documentation, size/L, lgtm, cla: yes

#18461 Remove Luigi mention from the Busola section and AC CR from components
  docs/01-overview/ui/README.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/_sidebar1.md
  docs/05-technical-reference/00-custom-resources/ac-01-application.md
  docs/_sidebar.md
Labels: size/M, lgtm, cla: yes

#18463 Removed the note on unmodularized components
  docs/06-modules/README.md
Labels: area/documentation, size/XS, lgtm, cla: yes

#18453 Remove Istio
  CODEOWNERS
  installation/resources/components.yaml
  installation/resources/crds/istio/istios.operator.crd.yaml
  resources/istio/Chart.yaml
  resources/istio/README.md
  resources/istio/templates/_helpers.tpl
  resources/istio/templates/istio-manager-config.yaml
  resources/istio/values.yaml
Labels: size/L, lgtm, cla: yes

#18465 use correct publisher service in tutorial
  docs/02-get-started/04-trigger-workload-with-event.md
Labels: area/documentation, area/eventing, lgtm, cla: yes

#18471 Fix broken links
  docs/03-tutorials/README.md
  docs/glossary.md
Labels: size/XS, lgtm, cla: yes

#18466 Remove component documents
  docs/01-overview/README.md
  docs/01-overview/_sidebar1.md
  docs/01-overview/api-exposure/README.md
  docs/01-overview/api-exposure/metadata.yaml
  docs/01-overview/metadata.yaml
  docs/01-overview/serverless/README.md
  docs/01-overview/serverless/metadata.yaml
  docs/01-overview/service-mesh/README.md
  docs/01-overview/service-mesh/metadata.yaml
  docs/01-overview/telemetry/README.md
  docs/01-overview/telemetry/metadata.yaml
  docs/02-get-started/01-quick-install.md
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/02-get-started/08-install-uninstall-upgrade-kyma-module.md
  docs/02-get-started/08-uninstall-upgrade-kyma-module.md
  docs/02-get-started/README.md
  docs/02-get-started/_sidebar1.md
  docs/03-tutorials/_sidebar1.md
  docs/04-operation-guides/_sidebar1.md
  docs/04-operation-guides/operations/01-install-kyma-CLI.md
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/operations/03-change-kyma-config-values.md
  docs/04-operation-guides/operations/05-upgrade-kyma.md
  docs/04-operation-guides/operations/07-uninstall-kyma.md
  docs/04-operation-guides/operations/README.md
  docs/04-operation-guides/operations/_sidebar1.md
  docs/04-operation-guides/operations/metadata.yaml
  docs/04-operation-guides/operations/ra-01-enable-kyma-with-runtime-agent.md
  docs/05-technical-reference/00-api-overview/README.md
  docs/05-technical-reference/00-cli-commands/README.md
  docs/05-technical-reference/00-cli-commands/metadata.yaml
  docs/05-technical-reference/apix-01-config-authorizations-apigateway.md
  docs/_redirects
  docs/_sidebar.md
Labels: area/documentation, size/XXL, lgtm, do-not-merge/missing-docs-review, cla: yes

#18472 Add a reference to the uninstall and upgrade doc
  docs/02-get-started/01-quick-install.md
  docs/04-operation-guides/operations/README.md
Labels: size/XS, lgtm, cla: yes

#18473 Fix spelling
  docs/02-get-started/01-quick-install.md
Labels: size/XS, lgtm, cla: yes

#18474 Fix alias for Serverless repo
  docs/index.html
Labels: size/XS, lgtm, cla: yes

#18475 Update _sidebar.md
  docs/_sidebar.md
Labels: size/XS, lgtm, cla: yes

#18476 Fix links and change Busola to Kyma Dashboard
  docs/01-overview/application-connectivity/ra-02-useful-links.md
  docs/01-overview/ui/README.md
  docs/01-overview/ui/ui-01-gui.md
  docs/05-technical-reference/00-configuration-parameters/README.md
  docs/06-modules/README.md
Labels: size/S, lgtm, cla: yes

#18481 Add Istio to Quick Install
  docs/02-get-started/01-quick-install.md
Labels: size/XS, lgtm, cla: yes

#18493 Update compass runtime agent image to version v20231218-ff3777c4
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm, cla: yes

#18494 Document quick install for Eventing
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/subscription/eventmesh/test/utils.go
  components/eventing-controller/controllers/subscription/eventmesh/testwebhookauth/utils.go
  components/eventing-controller/controllers/subscription/eventmesh/testwithory/utils.go
  components/eventing-controller/controllers/subscription/jetstream/test_utils_test.go
  docs/02-get-started/01-quick-install.md
Labels: size/S, lgtm, cla: yes

#18496 docs: Remove Access Application Logs
  docs/04-operation-guides/operations/README.md
  docs/04-operation-guides/operations/obsv-01-access-logs.md
Labels: size/S, lgtm, cla: yes

#18501 Fix a broken link
  docs/03-tutorials/00-observability.md
Labels: size/S, lgtm, cla: yes
