Repository kyma-project/kyma, pull requests merged in 2023-11, with the labels that each got.

#18378 Move the AC module higher in the modules table
  docs/01-overview/README.md
  docs/06-modules/README.md
Labels: size/XS, lgtm

#18367 Rremove all application connector helm charts as they are managed now in the Application Connector module
  CODEOWNERS
  components/central-application-connectivity-validator/Makefile
  components/central-application-gateway/Makefile
  installation/resources/components.yaml
  resources/application-connector/Chart.yaml
  resources/application-connector/README.md
  resources/application-connector/charts/central-application-connectivity-validator/Chart.yaml
  resources/application-connector/charts/central-application-connectivity-validator/templates/_helpers.tpl
  resources/application-connector/charts/central-application-connectivity-validator/templates/autoscaling.yaml
  resources/application-connector/charts/central-application-connectivity-validator/templates/deployment.yaml
  resources/application-connector/charts/central-application-connectivity-validator/templates/priority-class.yaml
  resources/application-connector/charts/central-application-connectivity-validator/templates/rbac.yaml
  resources/application-connector/charts/central-application-connectivity-validator/templates/service-account.yaml
  resources/application-connector/charts/central-application-connectivity-validator/templates/service.yaml
  resources/application-connector/charts/central-application-connectivity-validator/templates/virtual-service.yaml
  resources/application-connector/charts/central-application-connectivity-validator/values.yaml
  resources/application-connector/charts/central-application-gateway/.helmignore
  resources/application-connector/charts/central-application-gateway/Chart.yaml
  resources/application-connector/charts/central-application-gateway/profile-evaluation.yaml
  resources/application-connector/charts/central-application-gateway/profile-production.yaml
  resources/application-connector/charts/central-application-gateway/templates/_helpers.tpl
  resources/application-connector/charts/central-application-gateway/templates/deployment.yaml
  resources/application-connector/charts/central-application-gateway/templates/hpa.yaml
  resources/application-connector/charts/central-application-gateway/templates/priority-class.yaml
  resources/application-connector/charts/central-application-gateway/templates/rbac.yaml
  resources/application-connector/charts/central-application-gateway/templates/service.yaml
  resources/application-connector/charts/central-application-gateway/templates/tests/test-connection.yaml
  resources/application-connector/charts/central-application-gateway/values.yaml
  resources/application-connector/profile-evaluation.yaml
  resources/application-connector/profile-production.yaml
  resources/application-connector/templates/_helpers.tpl
  resources/application-connector/templates/application-connector-gateway.yaml
  resources/application-connector/templates/cluster-role-binding.yaml
  resources/application-connector/values.yaml
Labels: size/XL, lgtm

#18385 Add the AC module installation step
  docs/02-get-started/08-install-uninstall-upgrade-kyma-module.md
Labels: area/documentation, area/application-connector, lgtm

#18386 Fix module name
  docs/02-get-started/08-install-uninstall-upgrade-kyma-module.md
Labels: area/documentation, size/XS, lgtm

#18387 Update VERSION to 2.20.0
  VERSION
Labels: size/XS, lgtm

#18382 Remove ac docs
  components/central-application-gateway/README.md
  docs/01-overview/_sidebar.md
  docs/01-overview/application-connectivity/README.md
  docs/01-overview/application-connectivity/ac-01-application-connector.md
  docs/01-overview/application-connectivity/ac-02-application-gateway.md
  docs/01-overview/application-connectivity/ac-04-security.md
  docs/01-overview/application-connectivity/ac-05-useful-links.md
  docs/03-tutorials/00-application-connectivity/_sidebar.md
  docs/03-tutorials/00-application-connectivity/ac-01-create-application.md
  docs/03-tutorials/00-application-connectivity/ac-03-register-manage-services.md
  docs/03-tutorials/00-application-connectivity/ac-04-register-secured-api.md
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
  docs/03-tutorials/00-application-connectivity/ac-11-disable-tls-certificate-verification.md
  docs/03-tutorials/README.md
  docs/04-operation-guides/operations/README.md
  docs/04-operation-guides/operations/_sidebar.md
  docs/04-operation-guides/operations/ac-01-pass-access-token-in-request-header.md
  docs/05-technical-reference/00-architecture/README.md
  docs/05-technical-reference/00-architecture/_sidebar.md
  docs/05-technical-reference/00-architecture/ac-01-application-connector-components.md
  docs/05-technical-reference/00-architecture/ac-03-application-gateway.md
  docs/05-technical-reference/00-configuration-parameters/_sidebar.md
  docs/05-technical-reference/00-configuration-parameters/ac-01-application-connector-chart.md
  docs/05-technical-reference/00-custom-resources/ac-01-application.md
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
  docs/05-technical-reference/_sidebar.md
  docs/05-technical-reference/ac-01-application-gateway-details.md
  docs/glossary.md
Labels: area/documentation, area/application-connector, size/XXL, lgtm

#18401 improve prometheus cleanup script
  docs/assets/2.19-2.20-cleanup-monitoring.sh
Labels: area/monitoring, size/L, lgtm

#18397 Add the link to the Eventing module documentation
  docs/06-modules/README.md
  docs/_sidebar.md
Labels: area/documentation, lgtm

#18400 Add api gateway module's docs
  docs/_sidebar.md
  docs/index.html
Labels: size/XS, lgtm

#18406 improve prometheus cleanup script (#18401) cherry-picked to 2.20 branch
  docs/assets/2.19-2.20-cleanup-monitoring.sh
Labels: area/monitoring, size/L, lgtm

#18411 Add copy-code and pagination plugins
  docs/index.html
Labels: area/documentation, size/XS, lgtm

#18421 Move the Istio access logs tutorial to the Istio repo
  docs/04-operation-guides/operations/_sidebar.md
  docs/04-operation-guides/operations/obsv-03-enable-istio-access-logs.md
Labels: size/M, lgtm

#18420 Moved out the observability tutorial to the examples
  README.md
  docs/03-tutorials/00-observability.md
  docs/03-tutorials/assets/monitoring-tutorials.svg
  resources/README.md
Labels: size/M, lgtm

#18422 Fix broken links
  docs/01-overview/api-exposure/README.md
  docs/01-overview/api-exposure/apix-02-useful-links.md
  docs/04-operation-guides/operations/README.md
Labels: size/XS, lgtm

#18428 Change tabs in the Eventing tutorials
  docs/03-tutorials/00-eventing/evnt-02-subs-with-multiple-filters.md
  docs/03-tutorials/00-eventing/evnt-03-type-cleanup.md
  docs/03-tutorials/00-eventing/evnt-04-change-max-in-flight-in-sub.md
  docs/03-tutorials/00-eventing/evnt-05-send-legacy-events.md
Labels: area/documentation, size/XL, lgtm

#18429 Change tabs in the remaining kyma docs
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/04-operation-guides/operations/01-install-kyma-CLI.md
  docs/04-operation-guides/operations/10-backup-kyma.md
  docs/04-operation-guides/troubleshooting/security/sec-01-certificates-gardener.md
Labels: area/documentation, size/M, lgtm

#18432 Remove eventing docu from kyma repository
  docs/01-overview/README.md
  docs/01-overview/_sidebar1.md
  docs/01-overview/eventing/README.md
  docs/01-overview/eventing/assets/pubsub.svg
  docs/01-overview/eventing/evnt-90-glossary.md
  docs/01-overview/eventing/evnt-99-useful-links.md
  docs/01-overview/eventing/metadata.yaml
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/03-tutorials/00-eventing/README.md
  docs/03-tutorials/00-eventing/_sidebar1.md
  docs/03-tutorials/00-eventing/evnt-02-subs-with-multiple-filters.md
  docs/03-tutorials/00-eventing/evnt-03-type-cleanup.md
  docs/03-tutorials/00-eventing/evnt-04-change-max-in-flight-in-sub.md
  docs/03-tutorials/00-eventing/evnt-05-send-legacy-events.md
  docs/03-tutorials/00-eventing/metadata.yaml
  docs/03-tutorials/README.md
  docs/03-tutorials/_sidebar1.md
  docs/04-operation-guides/assets/eventing-implementation.svg
  docs/04-operation-guides/operations/README.md
  docs/04-operation-guides/operations/_sidebar1.md
  docs/04-operation-guides/operations/evnt-02-eventing-metrics.md
  docs/04-operation-guides/operations/evnt-03-nats-server-system-events.md
  docs/04-operation-guides/troubleshooting/README.md
  docs/04-operation-guides/troubleshooting/_sidebar1.md
  docs/04-operation-guides/troubleshooting/eventing/README.md
  docs/04-operation-guides/troubleshooting/eventing/_sidebar.md
  docs/04-operation-guides/troubleshooting/eventing/evnt-01-eventing-troubleshooting.md
  docs/04-operation-guides/troubleshooting/eventing/evnt-02-jetstream-troubleshooting.md
  docs/04-operation-guides/troubleshooting/eventing/evnt-03-type-collision.md
  docs/04-operation-guides/troubleshooting/eventing/evnt-04-free-jetstream-storage.md
  docs/04-operation-guides/troubleshooting/eventing/evnt-05-fix-pending-messages.md
  docs/04-operation-guides/troubleshooting/eventing/metadata.yaml
  docs/05-technical-reference/00-architecture/README.md
  docs/05-technical-reference/00-architecture/_sidebar1.md
  docs/05-technical-reference/00-architecture/evnt-01-architecture.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/_sidebar1.md
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
  docs/05-technical-reference/00-custom-resources/evnt-02-eventingbackend.md
  docs/05-technical-reference/_sidebar1.md
  docs/05-technical-reference/evnt-01-event-names.md
  docs/_sidebar.md
Labels: size/XXL, lgtm

#18434 Remove the leftover component docu
  docs/03-tutorials/00-api-exposure/_sidebar1.md
  docs/03-tutorials/00-eventing/_sidebar1.md
  docs/03-tutorials/00-security/_sidebar1.md
Labels: area/documentation, size/S, lgtm

#18435 Update the main navigation file
  docs/_sidebar.md
Labels: area/documentation, size/S, lgtm

#18442 Add module installation doc the navigation
  docs/_sidebar.md
Labels: size/XS, lgtm

#18445 remove fast-integration tests
  CODEOWNERS
  tests/fast-integration/.eslintrc.json
  tests/fast-integration/.gitignore
  tests/fast-integration/Makefile
  tests/fast-integration/README.md
  tests/fast-integration/compass-test/.env.template
  tests/fast-integration/compass-test/compass-test.js
  tests/fast-integration/compass-test/readme.md
  tests/fast-integration/compass/client.js
  tests/fast-integration/compass/fixtures.js
  tests/fast-integration/compass/gql.js
  tests/fast-integration/compass/helpers.js
  tests/fast-integration/compass/index.js
  tests/fast-integration/eventing-test/.env.template
  tests/fast-integration/eventing-test/README.md
  tests/fast-integration/eventing-test/assets/README.md
  tests/fast-integration/eventing-test/assets/eventing-sink.yaml
  tests/fast-integration/eventing-test/assets/eventing-upgrade-sink.yaml
  tests/fast-integration/eventing-test/common/common.js
  tests/fast-integration/eventing-test/eventing-test-cleanup.js
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/kcp/client.js
  tests/fast-integration/eventing-test/kyma-environment-broker/client.js
  tests/fast-integration/eventing-test/kyma-environment-broker/helpers.js
  tests/fast-integration/eventing-test/kyma-environment-broker/index.js
  tests/fast-integration/eventing-test/provision/deprovision-skr.js
  tests/fast-integration/eventing-test/provision/provision-skr.js
  tests/fast-integration/eventing-test/prow/config/skr_config.json
  tests/fast-integration/eventing-test/skr-helpers/helpers.js
  tests/fast-integration/eventing-test/utils.js
  tests/fast-integration/gardener/client.js
  tests/fast-integration/gardener/index.js
  tests/fast-integration/image/Dockerfile
  tests/fast-integration/image/Makefile
  tests/fast-integration/image/clone-and-run-fit.sh
  tests/fast-integration/lib/oauth.js
  tests/fast-integration/mocha-reporter-config.json
  tests/fast-integration/package-lock.json
  tests/fast-integration/package.json
  tests/fast-integration/prow/kyma-upgrade.sh
  tests/fast-integration/test/fixtures/commerce-mock/application.yaml
  tests/fast-integration/test/fixtures/commerce-mock/commerce-mock.yaml
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/upgrade-test/upgrade-test-cleanup.js
  tests/fast-integration/upgrade-test/upgrade-test-prep.js
  tests/fast-integration/upgrade-test/upgrade-test-tests.js
  tests/fast-integration/utils/index.js
  tests/fast-integration/utils/index.test.js
Labels: size/XXL, lgtm, cla: yes

#18448 Add a new guide to Useful Links
  docs/04-operation-guides/operations/README.md
  docs/04-operation-guides/operations/_sidebar1.md
  docs/04-operation-guides/troubleshooting/README.md
Labels: size/S, lgtm, cla: yes
