Repository kyma-project/kyma, pull requests merged in 2023-01, with the labels that each got.

#16423 Change JetStream maxBytes to be 70% of the total file storage
  resources/eventing/profile-evaluation.yaml
  resources/eventing/profile-production.yaml
  resources/eventing/values.yaml
Labels: kind/bug, area/eventing, size/XS, lgtm

#16474 Add NATS ConnectionBuilder
  components/eventing-controller/pkg/backend/jetstreamv2/connection.go
  components/eventing-controller/pkg/backend/jetstreamv2/connection_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/errors.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#16477 Directory size exporter Golang update
  components/directory-size-exporter/Dockerfile
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#16476 Separate between unit and integration tests for jetstreamv2 package
  components/eventing-controller/pkg/backend/jetstreamv2/config_internal_unit_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/connection_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_internal_unit_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils_internal_integration_test.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils_internal_unit_test.go
Labels: area/eventing, size/L, lgtm

#16480 Bump telemetry images
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#16482 Upgrade the NATS-Server image to `v2.9.9-alpine3.17`.
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#16381 New busola UI
  resources/eventing/charts/controller/templates/busola-extension.yaml
Labels: size/L, lgtm

#16484 bump kiwigrid image
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#16486 Image bump
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: size/S, lgtm

#16483 Finalize tracepipeline Api
  components/telemetry-operator/Makefile
  components/telemetry-operator/apis/telemetry/v1alpha1/tracepipeline_types.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  installation/resources/crds/telemetry/tracepipelines.crd.yaml
  resources/telemetry/values.yaml
Labels: size/M, lgtm

#16453 Cover case with API Bundles in the Compass Runtime Agent tests
  tests/components/application-connector/Makefile.test-compass-runtime-agent
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/templates/applications/test-create-app.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/test/compass-runtime-agent/synchronisation_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/applications/comparator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/directorclient.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/queryprovider.go
Labels: size/L, lgtm

#16497 Bump telemetry operator image to non PR image
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#16499 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#16500 Bump k8s-tools image in Kyma 2.9
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#16502 Preset typeMatching standard as a default value in create subscriptions' form
  resources/eventing/charts/controller/templates/busola-extension.yaml
Labels: area/busola, area/eventing, size/XS, lgtm

#16503 Image bumps for Eventing
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#16481 disable registry garbage collector
  components/function-controller/Makefile
  resources/serverless/charts/docker-registry/templates/cronjob.yaml
  resources/serverless/charts/docker-registry/templates/rbac.yaml
  resources/serverless/charts/docker-registry/values.yaml
  resources/serverless/values.yaml
Labels: size/S, lgtm

#16506 Compass Runtime Agent image bump
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
Labels: size/XS, lgtm

#16507 bump images for release 2.10
  resources/serverless/values.yaml
Labels: size/S, lgtm

#16511 bump loki to latest golang version
  resources/logging/values.yaml
Labels: size/XS, lgtm

#16515 Fixed spelling in telemetry docu and removed metrics from the picture for now
  docs/01-overview/main-areas/telemetry/README.md
  docs/01-overview/main-areas/telemetry/assets/general-components.drawio.svg
  docs/01-overview/main-areas/telemetry/assets/tracing-arch.drawio.svg
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
Labels: size/M, lgtm

#16518 Change VERSION to 2.10.0-rc1
  VERSION
Labels: size/XS, lgtm

#16521 fix mg link
  docs/migration-guide-2.9-2.10.md
Labels: size/XS, lgtm

#16526 fix mg link (#16521)
  docs/migration-guide-2.9-2.10.md
Labels: size/XS, lgtm

#16510 improve application name parsing from request path
  components/event-publisher-proxy/pkg/legacy/helpers.go
  components/event-publisher-proxy/pkg/legacy/helpers_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/S, lgtm

#16508 Adding APIRule create troubleshooting guide
  docs/04-operation-guides/troubleshooting/api-exposure/apix-10-api-rule-troubleshooting.md
Labels: size/L, lgtm

#16532 Fix legacy event not clean appName issue
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/legacy/legacy.go
  components/event-publisher-proxy/pkg/legacy/legacy_test.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#16535 Release 2.10
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/legacy/legacy.go
  components/event-publisher-proxy/pkg/legacy/legacy_test.go
Labels: size/M, lgtm

#16517 Fix otel collector restart
  components/telemetry-operator/internal/kubernetes/utils.go
  components/telemetry-operator/internal/kubernetes/utils_test.go
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#16516 Remove Kiali
  CODEOWNERS
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/security/assets/obsv-access-services.svg
  docs/04-operation-guides/security/sec-06-access-expose-grafana.md
  docs/04-operation-guides/security/sec-06-access-expose-kiali-grafana.md
  docs/05-technical-reference/00-architecture/assets/obsv-kiali-architecture.svg
  docs/05-technical-reference/00-architecture/obsv-04-architecture-kiali.md
  docs/05-technical-reference/00-configuration-parameters/obsv-01-configpara-observability.md
  docs/05-technical-reference/assets/architecture.svg
  installation/resources/components.yaml
  milv.config.yaml
  resources/kiali/Chart.yaml
  resources/kiali/README.md
  resources/kiali/profile-evaluation.yaml
  resources/kiali/templates/NOTES.txt
  resources/kiali/templates/_helpers.tpl
  resources/kiali/templates/cabundle.yaml
  resources/kiali/templates/configmap.yaml
  resources/kiali/templates/deployment.yaml
  resources/kiali/templates/hpa.yaml
  resources/kiali/templates/ingress.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-configmap.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-secret.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-service.yaml
  resources/kiali/templates/kyma-additions/auth-proxy-serviceaccount.yaml
  resources/kiali/templates/kyma-additions/authorization-policy.yaml
  resources/kiali/templates/kyma-additions/peerauthentication.yaml
  resources/kiali/templates/kyma-additions/servicemonitor.yaml
  resources/kiali/templates/kyma-additions/virtualservice.yaml
  resources/kiali/templates/oauth.yaml
  resources/kiali/templates/role-controlplane.yaml
  resources/kiali/templates/role-viewer.yaml
  resources/kiali/templates/role.yaml
  resources/kiali/templates/rolebinding-controlplane.yaml
  resources/kiali/templates/rolebinding.yaml
  resources/kiali/templates/route.yaml
  resources/kiali/templates/service.yaml
  resources/kiali/templates/serviceaccount.yaml
  resources/kiali/values.yaml
  resources/tracing/templates/kyma-additions/authorization-policy.yaml
Labels: size/XXL, lgtm

#16534 Adjust Get Started guides
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
Labels: size/XS, lgtm

#16536 Fix otel collector restart
  components/telemetry-operator/internal/kubernetes/utils.go
  components/telemetry-operator/internal/kubernetes/utils_test.go
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#16539 Bump eventing pulbisher proxy hotfix image
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#16542 Compass Runtime Agent, skipVerify to Kyma installation command
  tests/components/application-connector/docs/compass-runtime-agent-tests.md
Labels: area/documentation, size/XS, lgtm

#16538 Reverted NATS version to v2.9.6 - Release-2.10
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#16545 small get started adjustments (#16534)
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
Labels: size/XS, lgtm

#16537 Reverted NATS version to v2.9.6
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#16543 fix broken link in postgresql readmes
  resources/ory/charts/postgresql/README.md
  resources/ory/charts/postgresql/files/conf.d/README.md
  resources/ory/charts/postgresql/files/docker-entrypoint-initdb.d/README.md
Labels: size/S, lgtm

#16496 Cleanup event type from prefixes before forwarding event to the sink
  components/event-publisher-proxy/pkg/cloudevents/builder/eventmesh_test.go
  components/event-publisher-proxy/pkg/cloudevents/builder/generic.go
  components/event-publisher-proxy/pkg/cloudevents/builder/generic_test.go
  components/event-publisher-proxy/pkg/cloudevents/builder/types.go
  components/event-publisher-proxy/pkg/handler/handler.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_internal_unit_test.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#16487 Trace pipelines busola extension
  resources/telemetry/charts/operator/templates/tracepipeline_busola_extension_cm.yaml
Labels: size/L, lgtm

#16540 Add migration guide for Kyma 2.10 to 2.11
  docs/assets/2.10-2.11-cleanup-kiali.sh
  docs/migration-guide-2.10-2.11.md
Labels: size/S, lgtm

#16565 removed unused autoscaling settings for fluentbit
  resources/telemetry/charts/fluent-bit/templates/hpa.yaml
  resources/telemetry/charts/fluent-bit/values.yaml
Labels: area/logging, size/M, lgtm

#16573 Remove Fluent Bit dummy pipeline creation
  components/directory-size-exporter/Dockerfile
  components/telemetry-operator/Dockerfile
  components/telemetry-operator/internal/resources/logpipeline/resources.go
  components/webhook-cert-init/Dockerfile
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#16578 Change VERSION to 2.10.0
  VERSION
Labels: size/XS, lgtm

#16576 Upgrade golang version for all otters components
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/nodejs16/Dockerfile
  components/function-runtimes/python39/Dockerfile
  resources/serverless/values.yaml
Labels: area/serverless, size/M, lgtm

#16580 [Cherry-Pick] Upgrade golang version for all otters components
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/nodejs16/Dockerfile
  components/function-runtimes/python39/Dockerfile
Labels: area/serverless, size/S, lgtm

#16582 Upgrade serverless images
  resources/serverless/values.yaml
Labels: area/serverless, size/S, lgtm

#16583 Upgrade serverless tags
  resources/serverless/values.yaml
Labels: area/serverless, size/S, lgtm

#16574 Add logging exporter to otel collector
  components/telemetry-operator/controller/tracepipeline/resources.go
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#16592 Refactor creating otel collector configuration
  components/telemetry-operator/controller/tracepipeline/config_builder.go
  components/telemetry-operator/controller/tracepipeline/config_builder_test.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/controller_test.go
  components/telemetry-operator/controller/tracepipeline/resources.go
  components/telemetry-operator/controller/tracepipeline/resources_test.go
  components/telemetry-operator/controller/tracepipeline/secret_refs.go
  components/telemetry-operator/controller/tracepipeline/setup.go
  components/telemetry-operator/controller/tracepipeline/setup_test.go
  components/telemetry-operator/controller/tracepipeline/status_test.go
  components/telemetry-operator/main.go
  resources/telemetry/values.yaml
Labels: size/XL, lgtm

#16485 Add pprof profiling to telemetry-operator
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/main.go
  resources/telemetry/charts/operator/templates/networkpolicy.yaml
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/values.yaml
Labels: size/M, lgtm

#16575 Jaeger deprecation
  docs/01-overview/main-areas/assets/kyma-areas.svg
  docs/01-overview/main-areas/observability/README.md
  docs/01-overview/main-areas/observability/obsv-03-tracing-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-10-useful-links.md
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/security/sec-06-access-expose-grafana.md
  docs/04-operation-guides/troubleshooting/observability/obsv-02-troubleshoot-jaeger-shows-few-traces.md
  docs/05-technical-reference/00-architecture/obsv-03-architecture-tracing.md
  docs/05-technical-reference/00-custom-resources/telemetry-03-tracepipeline.md
  docs/05-technical-reference/svls-08-function-specification.md
Labels: size/XL, lgtm

#16547 Add PeerAuthentication to scrape Fluent Bit via plain http
  resources/telemetry/charts/fluent-bit/templates/peerauthentication.yaml
  resources/telemetry/charts/fluent-bit/templates/servicemonitor.yaml
  resources/telemetry/charts/fluent-bit/values.yaml
Labels: size/M, lgtm

#16442 Mitigate OAuth2Client reapply
  resources/eventing/charts/controller/templates/oauth2-client.yaml
Labels: size/XS, lgtm

#16488 Refactor the API Exposure tutorials
  docs/01-overview/main-areas/api-exposure/apix-02-useful-links.md
  docs/01-overview/main-areas/service-mesh/smsh-03-istio-sidecars-in-kyma.md
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
  docs/03-tutorials/00-api-exposure/apix-01-create-workload.md
  docs/03-tutorials/00-api-exposure/apix-02-setup-custom-domain-for-workload.md
  docs/03-tutorials/00-api-exposure/apix-03-expose-workload-apigateway.md
  docs/03-tutorials/00-api-exposure/apix-03-set-up-tls-gateway.md
  docs/03-tutorials/00-api-exposure/apix-04-expose-multiple-workloads.md
  docs/03-tutorials/00-api-exposure/apix-04-expose-workload/apix-04-01-expose-workload-apigateway.md
  docs/03-tutorials/00-api-exposure/apix-04-expose-workload/apix-04-02-expose-multiple-workloads.md
  docs/03-tutorials/00-api-exposure/apix-04-expose-workload/apix-04-03-expose-workloads-multiple-namespaces.md
  docs/03-tutorials/00-api-exposure/apix-04-expose-workload/metadata.yaml
  docs/03-tutorials/00-api-exposure/apix-05-expose-and-secure-a-workload/apix-05-01-expose-and-secure-workload-oauth2.md
  docs/03-tutorials/00-api-exposure/apix-05-expose-and-secure-a-workload/apix-05-02-get-jwt.md
  docs/03-tutorials/00-api-exposure/apix-05-expose-and-secure-a-workload/apix-05-03-expose-and-secure-workload-jwt.md
  docs/03-tutorials/00-api-exposure/apix-05-expose-and-secure-a-workload/apix-05-04-expose-and-secure-workload-istio.md
  docs/03-tutorials/00-api-exposure/apix-05-expose-and-secure-a-workload/apix-05-05-expose-and-secure-workload-with-certificate.md
  docs/03-tutorials/00-api-exposure/apix-05-expose-and-secure-a-workload/metadata.yaml
  docs/03-tutorials/00-api-exposure/apix-09-expose-workloads-multiple-namespaces.md
  docs/03-tutorials/00-security/sec-01-tls-certificates-security.md
  docs/03-tutorials/00-security/sec-02-mtls-selfsign-client-certicate.md
  docs/03-tutorials/00-security/sec-03-set-up-idp.md
  docs/03-tutorials/00-security/sec-03-setup-mtls-gateway.md
  docs/03-tutorials/00-security/sec-04-set-up-idp.md
  docs/03-tutorials/00-serverless/svls-03-expose-function.md
  docs/04-operation-guides/security/sec-07-useful-links.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-01-apigateway-connect-api-rule.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-02-401-unauthorized-403-forbidden.md
Labels: size/XXL, lgtm

#16558 OpenTelemetry filter processor
  components/telemetry-operator/controller/tracepipeline/config_builder.go
  components/telemetry-operator/controller/tracepipeline/config_builder_test.go
  components/telemetry-operator/main.go
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#16598 Fix wrong TLS setting for endpoints defined in a secret
  components/telemetry-operator/controller/tracepipeline/controller.go
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#16601 Set log level in trace collector
  components/telemetry-operator/controller/tracepipeline/config_builder.go
  components/telemetry-operator/controller/tracepipeline/config_builder_test.go
  resources/telemetry/values.yaml
Labels: area/tracing, size/S, lgtm

#16567 Add debug ability to the telemetry operator
  components/telemetry-operator/controller/logparser/controller.go
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/suite_test.go
  components/telemetry-operator/controller/tracepipeline/controller.go
  components/telemetry-operator/controller/tracepipeline/mocks/configmap_prober.go
  components/telemetry-operator/controller/tracepipeline/mocks/deployment_prober.go
  components/telemetry-operator/controller/tracepipeline/setup.go
  components/telemetry-operator/controller/tracepipeline/suite_test.go
  components/telemetry-operator/go.mod
  components/telemetry-operator/go.sum
  components/telemetry-operator/internal/kubernetes/configmap.go
  components/telemetry-operator/internal/kubernetes/configmap_test.go
  components/telemetry-operator/internal/logger/logger.go
  components/telemetry-operator/internal/overrides/overrides.go
  components/telemetry-operator/main.go
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#16622 fix link to telemetry readme (#16595)
  docs/01-overview/main-areas/observability/README.md
  docs/01-overview/main-areas/observability/obsv-02-logging-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-03-tracing-in-kyma.md
Labels: size/S, lgtm

#16627 Update api-gateway CRD
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
Labels: size/S, lgtm

#16630 with k8s 1.25 policy/v1beta1 is not available
  resources/cluster-essentials/charts/pod-preset/templates/webhook/deploy.yaml
Labels: size/XS, lgtm

#16625 create nats secret irrespective of the eventing backend
  components/eventing-controller/api/v1alpha1/condition.go
  components/eventing-controller/controllers/backend/reconciler.go
Labels: size/M, lgtm

#16637 bump eventing images
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#16636 with k8s 1.25 policy/v1beta1 is not available (#16630)
  resources/cluster-essentials/charts/pod-preset/templates/webhook/deploy.yaml
Labels: size/XS, lgtm

#16489 Remove dependencies to kyma-integration Namespace
  components/function-controller/README.md
  components/function-controller/internal/controllers/kubernetes/shared.go
  components/telemetry-operator/config/samples/telemetry_v1alpha1_logpipeline.yaml
  components/telemetry-operator/internal/fluentbit/config/builder/config_builder_test.go
  components/telemetry-operator/internal/fluentbit/config/builder/namespace_filter.go
  components/telemetry-operator/internal/fluentbit/config/builder/namespace_filter_test.go
  components/telemetry-operator/webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
  docs/01-overview/main-areas/service-mesh/smsh-03-istio-sidecars-in-kyma.md
  docs/01-overview/main-areas/telemetry/telemetry-02-logs.md
  resources/serverless/templates/_helper_tests.txt
  resources/serverless/values.yaml
  resources/telemetry/values.yaml
Labels: area/documentation, area/serverless, area/application-connector, area/tracing, size/M, lgtm

#16562 Bump k8s-tools image in Kyma 2.10
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm

#16639 Update VERSION to 2.10.1
  VERSION
Labels: size/XS, lgtm

#16629 Implement tests for pause flag
  components/telemetry-operator/README.md
  components/telemetry-operator/internal/overrides/overrides.go
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/helpers.js
  tests/fast-integration/telemetry-test/suite.js
  tests/fast-integration/telemetry-test/testdata/override-config.yaml
  tests/fast-integration/telemetry-test/testdata/tracepipeline-output-otlp.yaml
Labels: size/L, lgtm

#16561 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm

#16628 Move protocolsettings checks to the validating webhook
  components/eventing-controller/api/v1alpha2/errors.go
  components/eventing-controller/api/v1alpha2/subscription_webhook.go
  components/eventing-controller/api/v1alpha2/subscription_webhook_unit_test.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/test/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler_integration_test.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils_test.go
  components/eventing-controller/pkg/backend/utils/utils.go
  components/eventing-controller/pkg/ems/api/events/types/auth_type.go
  components/eventing-controller/pkg/ems/api/events/types/grant_type.go
  components/eventing-controller/pkg/ems/api/events/types/qos.go
  components/eventing-controller/testing/v2/test_helpers.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#16623 create nats secret irrespective of the backend
  components/eventing-controller/api/v1alpha1/condition.go
  components/eventing-controller/controllers/backend/reconciler.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#16557 Enhance js reconciler
  components/eventing-controller/api/v1alpha2/condition.go
  components/eventing-controller/api/v1alpha2/condition_unit_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/errors.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler_internal_unit_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/utils.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/utils_unit_test.go
  resources/eventing/values.yaml
Labels: size/XL, lgtm

#16621 Fixed EPP to not clean application name twice
  components/event-publisher-proxy/pkg/application/clean.go
  components/event-publisher-proxy/pkg/application/clean_test.go
  components/event-publisher-proxy/pkg/cloudevents/builder/generic.go
  components/event-publisher-proxy/pkg/cloudevents/builder/generic_test.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#16655 fix the configmap name of trace collector
  docs/01-overview/main-areas/telemetry/assets/tracing-resources.drawio.svg
Labels: size/XS, lgtm

#16577 Parametrise gateway URL encoding
  components/application-operator/pkg/apis/applicationconnector/v1alpha1/types.go
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/central-application-gateway/internal/csrf/mocks/Client.go
  components/central-application-gateway/internal/csrf/mocks/TokenStrategy.go
  components/central-application-gateway/internal/csrf/mocks/TokenStrategyFactory.go
  components/central-application-gateway/internal/metadata/applications/mocks/Manager.go
  components/central-application-gateway/internal/metadata/applications/mocks/ServiceRepository.go
  components/central-application-gateway/internal/metadata/applications/repository.go
  components/central-application-gateway/internal/metadata/model/model.go
  components/central-application-gateway/internal/metadata/secrets/mocks/Manager.go
  components/central-application-gateway/internal/metadata/secrets/mocks/Repository.go
  components/central-application-gateway/internal/metadata/serviceapi/serviceapiservice.go
  components/central-application-gateway/internal/proxy/factory.go
  components/central-application-gateway/internal/proxy/factory_test.go
  components/central-application-gateway/internal/proxy/mocks/APIExtractor.go
  components/central-application-gateway/internal/proxy/proxy.go
  components/central-application-gateway/internal/proxy/proxy_test.go
  components/central-application-gateway/internal/proxy/reverseproxy.go
  components/central-application-gateway/pkg/authorization/mocks/OAuthClient.go
  components/central-application-gateway/pkg/authorization/mocks/Strategy.go
  components/central-application-gateway/pkg/authorization/mocks/StrategyFactory.go
  components/central-application-gateway/pkg/authorization/oauth/mocks/Client.go
  components/central-application-gateway/pkg/proxyconfig/mocks/TargetConfigProvider.go
  installation/resources/crds/application-connector/applications.applicationconnector.crd.yaml
  resources/application-connector/values.yaml
  tests/components/application-connector/docs/application-gateway-tests.md
Labels: size/L, lgtm

#16642 Improve webhook logs
  components/function-controller/cmd/webhook/main.go
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/defaulting_webhook.go
  components/function-controller/internal/webhook/defaulting_webhook_test.go
  components/function-controller/internal/webhook/remote_registry_cfg_webhook.go
  components/function-controller/internal/webhook/remote_registry_cfg_webhook_test.go
  components/function-controller/internal/webhook/validating_webhook.go
  components/function-controller/internal/webhook/validating_webhook_test.go
  resources/serverless/values.yaml
Labels: area/serverless, size/M, lgtm, kind/cleanup

#16665 Unreplace app operator dependency
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  resources/application-connector/values.yaml
Labels: size/XS, lgtm

#16667 add encodeUrl to Application parameters table
  docs/05-technical-reference/00-custom-resources/ac-01-application.md
Labels: size/XS, lgtm, 2023-Q1

#16634 Tracing filter processor integration test
  components/telemetry-operator/controller/tracepipeline/config_builder.go
  components/telemetry-operator/controller/tracepipeline/config_builder_test.go
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/helpers.js
  tests/fast-integration/telemetry-test/suite.js
  tests/fast-integration/telemetry-test/testdata/tracepipeline-jaeger.yaml
  tests/fast-integration/telemetry-test/testdata/tracepipeline-test-app.yaml
  tests/fast-integration/telemetry-test/testdata/tracepipeline-test-istio-telemetry-patch.yaml
  tests/fast-integration/tracing/client.js
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#16644 Add hint about pprof to telemetry-operator README
  components/telemetry-operator/README.md
Labels: size/S, lgtm

#16672 Fix keda module name prefix
  modules/alpha/moduletemplate-keda.yaml
Labels: size/XS, lgtm

#16654 Upgrade Fluent Bit to 2.0
  components/telemetry-operator/Dockerfile
  components/telemetry-operator/config/samples/http-mockserver.yaml
  components/telemetry-operator/internal/resources/logpipeline/resources.go
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/testdata/http-backend.yaml
Labels: size/S, lgtm

#16678 bring back mg 2.10-2.11
  docs/migration-guide-2.10-2.11.md
Labels: size/XS, lgtm

#16670 Update info on Kyma Dashboard
  docs/04-operation-guides/operations/02-install-kyma.md
Labels: area/documentation, size/XS, lgtm

#16679 Fix link to the script
  docs/migration-guide-2.10-2.11.md
Labels: size/XS, lgtm

#16661 Bump net
  components/application-operator/go.mod
  components/application-operator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/M, lgtm

#16676 Bump autoscaling in Ory charts
  resources/ory/charts/gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml
  resources/ory/charts/hydra/templates/hpa.yaml
  resources/ory/charts/oathkeeper/templates/hpa.yaml
Labels: size/M, lgtm

#16680 Bump the net library images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/XS, lgtm

#16683 Bump the net library (#16680)
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/XS, lgtm

#16671 validate source for valid URI
  components/event-publisher-proxy/pkg/cloudevents/builder/eventmesh_test.go
  components/event-publisher-proxy/pkg/cloudevents/builder/generic.go
  components/event-publisher-proxy/pkg/cloudevents/builder/generic_test.go
  components/eventing-controller/api/v1alpha2/errors.go
  components/eventing-controller/api/v1alpha2/subscription_webhook.go
  components/eventing-controller/api/v1alpha2/subscription_webhook_unit_test.go
  components/eventing-controller/utils/utils.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#16682 update of alpine and golang version for telemetry/observability images
  components/telemetry-operator/Dockerfile
  components/telemetry-operator/config/samples/http-mockserver.yaml
  components/telemetry-operator/internal/resources/logpipeline/resources.go
  components/telemetry-operator/main.go
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/telemetry/values.yaml
  resources/tracing/values.yaml
  tests/fast-integration/telemetry-test/testdata/http-backend.yaml
Labels: area/monitoring, area/logging, size/S, lgtm

#16666 Fix TracePipeline has wrong status
  components/telemetry-operator/config/rbac/role.yaml
  components/telemetry-operator/internal/kubernetes/deployment.go
  components/telemetry-operator/internal/kubernetes/deployment_test.go
  components/telemetry-operator/main.go
  resources/telemetry/charts/operator/templates/role.yaml
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#16684 Update VERSION to 2.10.2
  VERSION
Labels: size/XS, lgtm

#16646 Cleanup event types in conversion webhook for v1alpha2 Subscription
  components/eventing-controller/api/v1alpha1/subscription_conversion.go
  components/eventing-controller/api/v1alpha1/subscription_conversion_unit_test.go
  components/eventing-controller/pkg/backend/eventtype/simple_clean.go
  components/eventing-controller/pkg/backend/eventtype/simple_clean_internal_unit_test.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#16647 Pod preset cleanup
  CODEOWNERS
  installation/resources/crds/pod-presets/podpresets.settings.svcat.crd.yaml
  resources/cluster-essentials/charts/pod-preset/.helmignore
  resources/cluster-essentials/charts/pod-preset/Chart.yaml
  resources/cluster-essentials/charts/pod-preset/README.md
  resources/cluster-essentials/charts/pod-preset/templates/_helpers.tpl
  resources/cluster-essentials/charts/pod-preset/templates/controller-manager/cluster-role-binding.yaml
  resources/cluster-essentials/charts/pod-preset/templates/controller-manager/cluster-role.yaml
  resources/cluster-essentials/charts/pod-preset/templates/controller-manager/sa.yaml
  resources/cluster-essentials/charts/pod-preset/templates/controller-manager/stateful-set.yaml
  resources/cluster-essentials/charts/pod-preset/templates/webhook/cluster-role-binding.yaml
  resources/cluster-essentials/charts/pod-preset/templates/webhook/cluster-role.yaml
  resources/cluster-essentials/charts/pod-preset/templates/webhook/deploy.yaml
  resources/cluster-essentials/charts/pod-preset/templates/webhook/sa.yaml
  resources/cluster-essentials/charts/pod-preset/templates/webhook/service.yaml
  resources/cluster-essentials/charts/pod-preset/templates/webhook/webhook.yaml
  resources/cluster-essentials/charts/pod-preset/values.yaml
  resources/cluster-essentials/profile-evaluation.yaml
  resources/cluster-essentials/profile-production.yaml
  resources/cluster-essentials/values.yaml
  tests/fast-integration/eventing-test/provision/provision-skr.js
  tests/fast-integration/skr-svcat-migration-test/test-helpers.js
  tests/fast-integration/utils/index.js
Labels: size/XL, lgtm

#16675 Fix empty response case from async nodejs16 runtime
  components/function-runtimes/nodejs16/lib/helper.js
  components/function-runtimes/nodejs16/server.js
  resources/serverless/values.yaml
Labels: size/M, lgtm

#16695 Upgrade serverless images
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm, kind/cleanup

#16677 Migrate Compass Runtime Agent after Application Operator removal
  components/compass-runtime-agent/cmd/init.go
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  components/compass-runtime-agent/internal/compassconnection/controller.go
  components/compass-runtime-agent/internal/kyma/applications/converter.go
  components/compass-runtime-agent/internal/kyma/applications/converter_test.go
  components/compass-runtime-agent/internal/kyma/applications/mocks/Converter.go
  components/compass-runtime-agent/internal/kyma/applications/mocks/Repository.go
  components/compass-runtime-agent/internal/kyma/applications/repository.go
  components/compass-runtime-agent/internal/kyma/service.go
  components/compass-runtime-agent/internal/kyma/service_test.go
  components/compass-runtime-agent/internal/kyma/util.go
  resources/compass-runtime-agent/values.yaml
Labels: size/XL, lgtm

#16690 Bump NATS image to 2.9.11
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#16689 Telemetry integration test retry operations
  tests/fast-integration/telemetry-test/suite.js
Labels: size/M, lgtm
