Repository kyma-project/kyma, pull requests merged in 2023-04, with the labels that each got.

#17226 change main to release branch for Kiali
  docs/migration-guide-2.10-2.11.md
Labels: size/XS, lgtm

#17224 Update Alpine based images to 3.17.3
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/ory/values.yaml
  resources/tracing/values.yaml
Labels: size/S, lgtm

#17137 reduce rbac permissions for eventing component
  resources/eventing/charts/controller/templates/clusterrole.yaml
Labels: size/XS, lgtm

#17236 Cherry-pick "Change v1alpha1 to v1alpha2 serverless fast integration" to release-2.12
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/getting-started-guide/index.js
  tests/fast-integration/utils/index.js
Labels: area/serverless, size/XS, lgtm

#17237 Security Team Otters
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17218 Api-gateway 1.5.0
  resources/api-gateway/Chart.yaml
  resources/api-gateway/templates/rbac.yaml
  resources/api-gateway/values.yaml
Labels: area/api-gateway, size/XS, lgtm

#17240 Security Team Otters - Bump Values
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17235 Added retries on Eventing FI tests
  tests/fast-integration/eventing-test/utils.js
Labels: size/S, lgtm

#17241 Cherry-picked "Added retries on Eventing FI tests" to Release-2.12
  tests/fast-integration/eventing-test/utils.js
Labels: size/S, lgtm

#17242 More Logging Messages
  tests/fast-integration/utils/index.js
Labels: size/XS, lgtm

#17248 Logging Messages
  tests/fast-integration/skr-aws-upgrade-integration/index.js
  tests/fast-integration/skr-test/provision/provision-skr.js
  tests/fast-integration/utils/index.js
Labels: size/XS, lgtm

#17249 Add documentation regarding limatations on Istio, Ory and API Gateway
  docs/01-overview/main-areas/api-exposure/apix-03-api-gateway-limitations.md
  docs/01-overview/main-areas/service-mesh/smsh-04-istio-limitations.md
  docs/05-technical-reference/00-configuration-parameters/apix-01-ory-limitations.md
  docs/05-technical-reference/00-configuration-parameters/smsh-01-istio-chart.md
Labels: area/documentation, area/service-mesh, area/api-gateway, size/L, lgtm

#17251 [Telemetry] Bump image for hardened metric config
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#17254 Update telemetry images
  resources/monitoring/values.yaml
  resources/telemetry/values.yaml
Labels: area/monitoring, size/XS, lgtm, area/telemetry

#17207 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17261 Eventing image bumps for rel-2.13
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#17256 bumps golang runtime in central-application-connectivity-validator due to CVE-2023-24532
  components/central-application-connectivity-validator/Dockerfile
  resources/application-connector/values.yaml
Labels: size/XS, lgtm

#17262 bumps images in application-connector and compass-runtime-agent components
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
Labels: size/XS, lgtm

#17247 improve Kyma overview and contributing
  CONTRIBUTING.md
  README.md
Labels: size/M, lgtm

#17259 remove unused functions for labels
  components/function-controller/internal/controllers/serverless/build_resources.go
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#17266 add links for Eventing and Service Mesh
  README.md
Labels: size/XS, lgtm

#17263 Replace serverless PR tags
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17278 Delete 2.10-2.11-cleanup-kiali.sh
  docs/assets/2.10-2.11-cleanup-kiali.sh
Labels: size/S, lgtm

#17280 Change VERSION to 2.13.0-rc1
  VERSION
Labels: size/XS, lgtm

#17252 Improve log msg
  components/function-controller/internal/controllers/serverless/function_reconcile.go
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17283 adjusted namespace in migration script
  docs/assets/2.11-2.12-cleanup-servicemonitors.sh
Labels: kind/bug, area/monitoring, size/XS, lgtm

#17282 Adapt api-gateway registry
  resources/api-gateway/values.yaml
Labels: size/XS, lgtm

#17288 bumps application-connectivity components to 1.20.3-alpine3.17
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/S, lgtm

#17264 removes application-gateway-legacy-tests
  CODEOWNERS
  resources/application-connector/values.yaml
  tests/application-gateway-legacy-tests/.gitignore
  tests/application-gateway-legacy-tests/Makefile
  tests/application-gateway-legacy-tests/README.md
  tests/application-gateway-legacy-tests/go.mod
  tests/application-gateway-legacy-tests/go.sum
  tests/application-gateway-legacy-tests/scripts/executor-entrypoint.sh
  tests/application-gateway-legacy-tests/scripts/helm-test-entrypoint.sh
  tests/application-gateway-legacy-tests/spec.json
  tests/application-gateway-legacy-tests/test/executor/Dockerfile
  tests/application-gateway-legacy-tests/test/executor/config.go
  tests/application-gateway-legacy-tests/test/executor/proxy/mock/applicationserver.go
  tests/application-gateway-legacy-tests/test/executor/proxy/mock/basicauthhandler.go
  tests/application-gateway-legacy-tests/test/executor/proxy/mock/csrfhandler.go
  tests/application-gateway-legacy-tests/test/executor/proxy/mock/errorhandler.go
  tests/application-gateway-legacy-tests/test/executor/proxy/mock/headershandler.go
  tests/application-gateway-legacy-tests/test/executor/proxy/mock/oauthhandler.go
  tests/application-gateway-legacy-tests/test/executor/proxy/mock/queryparamshandler.go
  tests/application-gateway-legacy-tests/test/executor/proxy/suite.go
  tests/application-gateway-legacy-tests/test/executor/proxy/tests/proxy_test.go
  tests/application-gateway-legacy-tests/test/executor/testkit/registry/client.go
  tests/application-gateway-legacy-tests/test/executor/testkit/registry/model.go
  tests/application-gateway-legacy-tests/test/executor/testkit/util/util.go
  tests/application-gateway-legacy-tests/test/gateway/spec.json
  tests/application-gateway-legacy-tests/test/helmtest/Dockerfile
  tests/application-gateway-legacy-tests/test/helmtest/config.go
  tests/application-gateway-legacy-tests/test/helmtest/proxy/suite.go
  tests/application-gateway-legacy-tests/test/helmtest/proxy/tests/proxy_test.go
  tests/application-gateway-legacy-tests/test/tools/wait.go
Labels: size/XXL, lgtm

#17289 Bumped api-gateway-webhook-certificates image in Eventing to 1.5.0
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#17279 Added check for length of clean event types
  components/eventing-controller/api/v1alpha2/condition.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils_internal_unit_test.go
  resources/eventing/values.yaml
Labels: size/M, lgtm

#17215 minor fixes to eventing fi tests
  tests/fast-integration/eventing-test/README.md
  tests/fast-integration/eventing-test/assets/eventing-sink.yaml
  tests/fast-integration/eventing-test/assets/eventing-upgrade-sink.yaml
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/prow/config/skr_config.json
  tests/fast-integration/eventing-test/utils.js
Labels: size/L, lgtm

#17305 consolidate access logging in istio profiles
  resources/istio/profile-evaluation.yaml
  resources/istio/profile-production.yaml
  resources/istio/values.yaml
Labels: area/logging, area/api-gateway, size/S, lgtm

#17304 added traceparent attribute to default access log format
  docs/01-overview/main-areas/api-exposure/apix-02-useful-links.md
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
  docs/04-operation-guides/operations/obsv-03-enable-istio-access-logs.md
  resources/istio/values.yaml
Labels: area/documentation, area/tracing, area/logging, area/api-gateway, size/M, lgtm

#17309 Update VERSION to 2.13.0
  VERSION
Labels: size/XS, lgtm

#17303 remove event-subscriber-tools
  CODEOWNERS
  tools/event-subscriber/Dockerfile
  tools/event-subscriber/Makefile
  tools/event-subscriber/README.md
  tools/event-subscriber/cmd/subscriber.go
  tools/event-subscriber/cmd/subscriber_test.go
  tools/event-subscriber/go.mod
  tools/event-subscriber/go.sum
Labels: size/XL, lgtm

#17258 Function labels
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  components/function-controller/internal/controllers/serverless/fixtures_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/controllers/serverless/system_state_test.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/zz_generated.deepcopy.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/templates/crds.yaml
  resources/serverless/values.yaml
Labels: size/XL, lgtm

#17311 add telemetry area to changelog generation
  .github/package.json
Labels: size/XS, lgtm

#17310 update to fluentbit 2.0.11
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/testdata/http-backend.yaml
Labels: area/logging, size/XS, lgtm, area/telemetry

#17317 Fix the link to a troubleshooting tutorial
  docs/01-overview/main-areas/service-mesh/smsh-03-istio-sidecars-in-kyma.md
Labels: area/documentation, size/XS, lgtm

#17312 Enabled Stream/Consumer not recreated test in Eventing FI tests
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: area/eventing, size/L, lgtm

#17316 bumps client-go and apimachinery in application-connectivity area
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/L, lgtm

#17308 istio access log test is flaky
  tests/fast-integration/logging/index.js
  tests/fast-integration/logging/loki.js
  tests/fast-integration/utils/index.js
Labels: size/M, lgtm

#17102 NakWithDelay Message Delivery in JetStream
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  resources/eventing/values.yaml
Labels: size/S, lgtm

#17331 Cherry-picked changes for length check and metrics - Rel: 2.12
  components/eventing-controller/api/v1alpha2/condition.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils_internal_unit_test.go
Labels: area/eventing, size/M, lgtm

#17332 Cherry-picked changes for length check and metrics - Rel: 2.13
  components/eventing-controller/api/v1alpha2/condition.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils.go
  components/eventing-controller/pkg/backend/jetstreamv2/utils_internal_unit_test.go
Labels: area/eventing, size/M, lgtm

#17333 fixed links to access logs page
  docs/01-overview/main-areas/api-exposure/apix-02-useful-links.md
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
Labels: kind/bug, area/documentation, size/XS, lgtm

#17335 Image bump for Eventing Controller - Rel 2.12
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#17336 Image bump for Eventing Controller - Rel 2.13
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#17313 switch image registry for telemetry/observability components
  resources/logging/values.yaml
  resources/monitoring/charts/grafana/templates/_pod.tpl
  resources/monitoring/charts/grafana/values.yaml
  resources/monitoring/values.yaml
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/testdata/http-backend.yaml
Labels: size/M, lgtm, area/telemetry

#17328 Enhance the Eventing troubleshooting guide
  docs/04-operation-guides/troubleshooting/eventing/evnt-05-fix-pending-messages.md
Labels: area/documentation, area/eventing, size/S, lgtm

#17346 bumps golang to 1.20.3 in application-connectivity modules for release 2.12
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
Labels: size/XS, lgtm

#17345 bumps golang to 1.20.3 in application-connectivity modules for release-2.13
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
Labels: size/XS, lgtm

#17355 images bump - 2.12 - app-con security
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#17356 images bump - 2.13 - app-con security
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#17290 Execa Logs Streaming
  tests/fast-integration/kcp/client.js
  tests/fast-integration/skr-aws-upgrade-integration/index.js
Labels: size/S, lgtm

#17349 restructure eventing troubleshooting guide
  docs/04-operation-guides/troubleshooting/eventing/evnt-05-fix-pending-messages.md
Labels: area/documentation, area/eventing, size/L, lgtm

#17359 fix typo in eventing troubleshooting
  docs/04-operation-guides/troubleshooting/eventing/evnt-05-fix-pending-messages.md
Labels: size/XS, lgtm

#17361 Update Golang builder to 1.20.3
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17350 Adapt Application Connector image registry
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/S, lgtm

#17362 Update images in severless Values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17330 Correct the 'Set up a custom domain for a workload' tutorial
  docs/03-tutorials/00-api-exposure/apix-02-setup-custom-domain-for-workload.md
Labels: size/M, lgtm

#17365 update to golang 1.20.3 for observability images
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/telemetry/values.yaml
Labels: area/monitoring, area/tracing, area/logging, size/S, lgtm, area/telemetry

#17364 bumps golang.org/x/net to 0.7 in application-connectivity in 2.12
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
Labels: size/M, lgtm

#17372 Bump images for golang.org/x/net to 0.7 in application-connectivity in 2.12
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#17376 Update custom resources list and fix typo
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
Labels: size/XS, lgtm

#17255 Add to the function status the base image from the config
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/internal/controllers/serverless/deployment_test.go
  components/function-controller/internal/controllers/serverless/fsm.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/job.go
  components/function-controller/internal/controllers/serverless/suite_test.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/templates/crds.yaml
  resources/serverless/values.yaml
Labels: size/M, lgtm

#17357 add runtime labels and annotations of serverless functions to busola …
  resources/serverless/templates/busola-serverless-extension.yaml
Labels: size/S, lgtm

#17369 Bump pkgs in EC and EPP as per dependerbot
  components/event-publisher-proxy/Dockerfile
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/Dockerfile
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/L, lgtm

#17358 Add Keda to security scans
  CODEOWNERS
  resources/keda-manager/values.yaml
Labels: size/S, lgtm

#17381 Add BTP manager to security scans
  CODEOWNERS
  resources/btp-manager/values.yaml
Labels: size/XS, lgtm

#17386 Use latest golang in keda-manager builder image
  resources/keda-manager/values.yaml
Labels: size/XS, lgtm

#17384 Bump k8s-tools
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17387 Telemetry manager image bump
  resources/telemetry/values.yaml
Labels: kind/bug, size/XS, lgtm, area/telemetry

#17388 Bump k8s-tools in Kyma 2.13
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17392 update nats-server to 2.9.16
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#17353 Remove jaeger and fix tests
  CODEOWNERS
  installation/resources/components.yaml
  installation/resources/crds/tracing/jaegers.jaegertracing.crd.yaml
  resources/logging/charts/loki/templates/kyma-additions/grafana-datasource.yaml
  resources/logging/charts/loki/values.yaml
  resources/tracing/Chart.yaml
  resources/tracing/README.md
  resources/tracing/profile-evaluation.yaml
  resources/tracing/templates/_helpers.tpl
  resources/tracing/templates/certificate.yaml
  resources/tracing/templates/deployment.yaml
  resources/tracing/templates/jaeger.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-configmap.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-secret.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-service.yaml
  resources/tracing/templates/kyma-additions/auth-proxy-serviceaccount.yaml
  resources/tracing/templates/kyma-additions/authorization-policy.yaml
  resources/tracing/templates/kyma-additions/grafana-dashboard.yaml
  resources/tracing/templates/kyma-additions/grafana-datasource.yaml
  resources/tracing/templates/kyma-additions/istio-telemetry.yaml
  resources/tracing/templates/kyma-additions/metrics-service.yaml
  resources/tracing/templates/kyma-additions/peerauthentication.yaml
  resources/tracing/templates/kyma-additions/pvc.yaml
  resources/tracing/templates/kyma-additions/tracepipeline.yaml
  resources/tracing/templates/kyma-additions/virtualservice.yaml
  resources/tracing/templates/kyma-additions/zipkin-service.yaml
  resources/tracing/templates/mutating-webhook.yaml
  resources/tracing/templates/psp.yaml
  resources/tracing/templates/role-binding.yaml
  resources/tracing/templates/role.yaml
  resources/tracing/templates/service-account.yaml
  resources/tracing/templates/service.yaml
  resources/tracing/templates/validating-webhook.yaml
  resources/tracing/templates/webhook-secret.yaml
  resources/tracing/values.yaml
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/logging/client.js
  tests/fast-integration/logging/index.js
  tests/fast-integration/logging/loki.js
  tests/fast-integration/monitoring/grafana.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/jaeger/jaeger.yaml
  tests/fast-integration/test/test.js
  tests/fast-integration/utils/index.js
Labels: size/XXL, lgtm

#17389 Cleanup script for jaeger removal
  docs/assets/2.13.-2.14-cleanup-jaeger.sh
Labels: area/tracing, size/S, lgtm

#17360 Make sure to delete custom domain DNS secret after running tests
  tests/components/api-gateway/Makefile
  tests/components/api-gateway/README.md
  tests/components/api-gateway/custom_domain_test_env.sh
  tests/components/api-gateway/go.mod
  tests/components/api-gateway/go.sum
  tests/components/api-gateway/manifests/custom-domain/resources.yaml
  tests/components/api-gateway/pkg/jwt/auth.go
  tests/components/api-gateway/test_helpers.go
Labels: size/L, lgtm

#17401 Update serverless docker images
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/python39/Dockerfile
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17391 bumps images for the fix of golang.org/x/net-v0.5.0:CVE-2022-41723 in 2.13
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#17396 Cherry pick nats-server upgrade
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/values.yaml
Labels: size/S, lgtm

#17403 Bump gce-proxy image version to 1.33.6
  resources/ory/values.yaml
Labels: size/XS, lgtm

#17404 Bump gce-proxy to 1.33.6
  resources/ory/values.yaml
Labels: size/XS, lgtm

#17407 remove link to tracing values YAML
  docs/05-technical-reference/00-configuration-parameters/obsv-01-configpara-observability.md
Labels: area/tracing, size/XS, lgtm

#17406 Bump api-gateway to 1.5.1
  resources/api-gateway/values.yaml
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#17410 Change VERSION to 2.13.1
  VERSION
Labels: size/XS, lgtm

#17411 Upgrade the kaniko and the registry images
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17415 Bump Istio images to 1.17.2
  resources/istio/values.yaml
Labels: size/S, lgtm

#17390 Bump Istio version to 1.17.2
  resources/istio/values.yaml
Labels: size/S, lgtm

#17417 Switch to the new container registry
  resources/ory/values.yaml
Labels: size/XS, lgtm

#17412 Use artefact registry as serverless images pull url
  components/function-controller/README.md
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-controller/internal/controllers/serverless/config.go
  resources/keda-manager/values.yaml
  resources/serverless/values.yaml
Labels: size/M, lgtm

#17419 Change eu.gcr.io/ to europe-docker.pkg.dev/ for ory and istio images
  docs/04-operation-guides/operations/03-change-kyma-config-values.md
  docs/04-operation-guides/troubleshooting/service-mesh/smsh-04-istio-sidecar-version.md
  resources/istio/templates/istio-operator.yaml
  resources/istio/values.yaml
  resources/ory/charts/postgresql/values.yaml
  resources/ory/values.yaml
  tests/perf/prerequisites/istio/app.yaml
  tests/perf/prerequisites/ory/deployment.yaml
Labels: area/service-mesh, area/api-gateway, size/M, lgtm, kind/deprecation

#17429 Bump postgres exporter image
  resources/ory/values.yaml
Labels: size/XS, lgtm

#17427 Bump postgres exporter image
  resources/ory/values.yaml
Labels: size/XS, lgtm

#17423 Bump telemetry image to remove referecnces to jaeger
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/suite.js
  tests/fast-integration/upgrade-test/upgrade-test-tests.js
Labels: size/S, lgtm, area/telemetry

#17307 Rebuild the function when the base image is changed
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/job.go
  components/function-controller/internal/controllers/serverless/suite_test.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/templates/crds.yaml
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/L, lgtm
