Repository kyma-project/kyma, pull requests merged in 2023-08, with the labels that each got.

#17894 Contract test between api-gateway and serverless
  tests/function-controller/cmd/main.go
  tests/function-controller/testsuite/scenarios/api_gateway.go
  tests/function-controller/testsuite/teststep/check.go
Labels: area/serverless, size/L, lgtm, area/tests

#17912 Enable docsify
  docs/.nojekyll
  docs/03-tutorials/00-api-exposure/_sidebar.md
  docs/README.md
  docs/_sidebar.md
  docs/assets/apple-touch-icon.png
  docs/assets/favicon-16x16.png
  docs/assets/favicon-32x32.png
  docs/assets/favicon.ico
  docs/assets/safari-pinned-tab.svg
  docs/assets/theme-custom.css
  docs/index.html
Labels: size/L, lgtm

#17919 Docsify tab support
  docs/03-tutorials/00-api-exposure/apix-01-create-workload.md
  docs/03-tutorials/00-api-exposure/apix-04-expose-workload/apix-04-01-expose-workload-apigateway.md
  docs/03-tutorials/00-api-exposure/apix-04-expose-workload/apix-04-03-expose-workloads-multiple-namespaces.md
  docs/03-tutorials/00-api-exposure/apix-05-expose-and-secure-a-workload/apix-05-05-expose-and-secure-workload-with-certificate.md
  docs/index.html
Labels: size/L, lgtm

#17913 Add serverless-contract-tests scenario
  tests/function-controller/Makefile
  tests/function-controller/cmd/main.go
  tests/function-controller/testsuite/scenarios/api_gateway.go
Labels: kind/feature, area/serverless, size/S, lgtm

#17920 Fix a broken link
  docs/05-technical-reference/svls-01-sample-functions.md
Labels: size/XS, lgtm

#17922 Get Started docs fix
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/04-trigger-workload-with-event.md
Labels: size/S, lgtm

#17923 Small docsify improvements
  docs/assets/theme-custom.css
  docs/index.html
Labels: size/S, lgtm

#17915 Update RBAC for api-exposure
  resources/api-gateway/templates/rbac.yaml
  resources/ory/charts/hydra/charts/hydra-maester/templates/rbac.yaml
Labels: area/api-gateway, size/M, lgtm, kind/chore

#17918 Update docs structure for Docsify
  docs/01-overview/_sidebar.md
  docs/01-overview/api-exposure/README.md
  docs/01-overview/application-connectivity/README.md
  docs/01-overview/application-connectivity/ra-01-runtime-agent-overview.md
  docs/01-overview/eventing/README.md
  docs/01-overview/observability/README.md
  docs/01-overview/serverless/README.md
  docs/01-overview/service-management/README.md
  docs/01-overview/service-mesh/README.md
  docs/01-overview/telemetry/README.md
  docs/01-overview/ui/README.md
  docs/02-get-started/_sidebar.md
  docs/03-tutorials/00-api-exposure/_sidebar.md
  docs/03-tutorials/README.md
  docs/04-operation-guides/_sidebar.md
  docs/04-operation-guides/operations/README.md
  docs/04-operation-guides/operations/_sidebar.md
  docs/04-operation-guides/security/README.md
  docs/04-operation-guides/security/_sidebar.md
  docs/04-operation-guides/troubleshooting/README.md
  docs/05-technical-reference/00-architecture/README.md
  docs/05-technical-reference/00-architecture/_sidebar.md
  docs/05-technical-reference/00-architecture/obsv-01-architecture-monitoring.md
  docs/05-technical-reference/00-architecture/ra-01-runtime-agent-workflow.md
  docs/05-technical-reference/00-configuration-parameters/README.md
  docs/05-technical-reference/00-configuration-parameters/_sidebar.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/_sidebar.md
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
  docs/05-technical-reference/00-custom-resources/oper-01-istio.md
  docs/05-technical-reference/README.md
  docs/05-technical-reference/_sidebar.md
  docs/_sidebar.md
  docs/migration-guide-2.16-2.17.md
Labels: size/XXL, lgtm

#17933 Skip failing tests for EventMesh
  tests/fast-integration/eventing-test/eventing-test.js
Labels: area/eventing, kind/failing-test, size/S, lgtm

#17888 Fix bug dispatching messages to old sink
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_integration_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_unit_test.go
  components/eventing-controller/pkg/backend/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/jetstream/mocks/Backend.go
  components/eventing-controller/pkg/backend/jetstream/types.go
  resources/eventing/values.yaml
Labels: kind/bug, area/eventing, size/L, lgtm

#17569 Add retry for failing commerce mock test on gardener azure job
  tests/fast-integration/api-exposure/fixtures/index.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/test.js
Labels: size/M, lgtm, area/tests

#17934 Update VERSION to 2.17.0
  VERSION
Labels: size/XS, lgtm

#17935 Fix broken links
  docs/03-tutorials/README.md
Labels: size/XS, lgtm

#17914 bump kyma-project/prod/external/golang from 1.20.5-alpine3.18 to 1.20.6-alpine3.18 in application connector components
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/Dockerfile.compass-runtime-agent
  tests/components/application-connector/Dockerfile.connectivity-validator
  tests/components/application-connector/Dockerfile.gateway
  tests/components/application-connector/Dockerfile.mockapp
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/M, lgtm, kind/chore

#17938 Fix logging in test
  tests/function-controller/testsuite/scenarios/api_gateway.go
  tests/function-controller/testsuite/scenarios/light_runtimes.go
  tests/function-controller/testsuite/scenarios/tracing.go
  tests/function-controller/testsuite/teststep/check.go
Labels: size/S, lgtm

#17928 API Gateway 1.8.0
  docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
  resources/api-gateway/Chart.yaml
  resources/api-gateway/values.yaml
Labels: kind/feature, area/api-gateway, size/L, lgtm

#17937 Improve Docsify navigation
  docs/02-get-started/_sidebar.md
  docs/03-tutorials/00-api-exposure/_sidebar.md
  docs/03-tutorials/00-application-connectivity/README.md
  docs/03-tutorials/00-application-connectivity/_sidebar.md
  docs/03-tutorials/00-eventing/README.md
  docs/03-tutorials/00-eventing/_sidebar.md
  docs/03-tutorials/00-security/README.md
  docs/03-tutorials/00-security/_sidebar.md
  docs/03-tutorials/00-serverless/README.md
  docs/03-tutorials/00-serverless/_sidebar.md
  docs/03-tutorials/README.md
  docs/03-tutorials/_sidebar.md
  docs/04-operation-guides/_sidebar.md
  docs/04-operation-guides/operations/_sidebar.md
  docs/04-operation-guides/security/_sidebar.md
  docs/04-operation-guides/troubleshooting/README.md
  docs/04-operation-guides/troubleshooting/_sidebar.md
  docs/04-operation-guides/troubleshooting/api-exposure/_sidebar.md
  docs/04-operation-guides/troubleshooting/eventing/_sidebar.md
  docs/04-operation-guides/troubleshooting/observability/_sidebar.md
  docs/04-operation-guides/troubleshooting/security/_sidebar.md
  docs/04-operation-guides/troubleshooting/serverless/_sidebar.md
  docs/04-operation-guides/troubleshooting/service-mesh/_sidebar.md
  docs/05-technical-reference/00-architecture/README.md
  docs/05-technical-reference/00-architecture/_sidebar.md
  docs/05-technical-reference/00-configuration-parameters/README.md
  docs/05-technical-reference/00-configuration-parameters/_sidebar.md
  docs/05-technical-reference/00-custom-resources/_sidebar.md
  docs/05-technical-reference/README.md
  docs/05-technical-reference/_sidebar.md
Labels: size/L, lgtm

#17932 Fix the APIRule OwnerReferences equality check
  components/eventing-controller/pkg/object/equality.go
  components/eventing-controller/pkg/object/equality_test.go
  resources/eventing/values.yaml
Labels: kind/bug, area/eventing, size/L, lgtm

#17843 introduce subscription status as a metric
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_internal_unit_test.go
  components/eventing-controller/controllers/subscription/eventmesh/reconciler.go
  components/eventing-controller/controllers/subscription/eventmesh/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/subscription/eventmesh/test/utils.go
  components/eventing-controller/controllers/subscription/eventmesh/testwebhookauth/utils.go
  components/eventing-controller/controllers/subscription/eventmesh/testwithory/utils.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_unit_test.go
  components/eventing-controller/controllers/subscription/jetstream/test_utils_test.go
  components/eventing-controller/pkg/backend/jetstream/mocks/Backend.go
  components/eventing-controller/pkg/backend/jetstream/mocks/JetStreamContext.go
  components/eventing-controller/pkg/backend/jetstream/types.go
  components/eventing-controller/pkg/backend/metrics/collector.go
  components/eventing-controller/pkg/ems/api/events/client/mocks/PublisherManager.go
  components/eventing-controller/pkg/subscriptionmanager/eventmesh/eventmesh.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go
  docs/04-operation-guides/operations/evnt-02-eventing-metrics.md
  resources/eventing/values.yaml
Labels: area/eventing, size/XL, lgtm

#17949 Add the link to the BTP Operator module
  docs/index.html
Labels: area/documentation, size/XS, lgtm

#17942 Remove deprecated JaegerServiceEndpoint
  components/function-controller/internal/controllers/serverless/config.go
  components/function-controller/internal/controllers/serverless/deployment.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/controllers/serverless/utils.go
  resources/serverless/templates/deployment.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/S, lgtm, kind/cleanup

#17897 Update function documentation in quick start
  docs/02-get-started/02-deploy-expose-function.md
Labels: size/XS, lgtm

#17952 Unify sample function in docs
  docs/02-get-started/02-deploy-expose-function.md
Labels: area/documentation, area/serverless, size/S, lgtm

#17956 Remove an outdated tutorial
  docs/04-operation-guides/security/sec-07-useful-links.md
  docs/04-operation-guides/troubleshooting/README.md
  docs/04-operation-guides/troubleshooting/security/_sidebar.md
  docs/04-operation-guides/troubleshooting/security/sec-02-oauth2-protected-apirules.md
Labels: size/S, lgtm

#17958 Fix the link to the BTP Operator documentation in the _sidebar.md file
  docs/_sidebar.md
Labels: area/documentation, lgtm

#17955 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm, kind/chore

#17963 Configuration for installation of Istio operator
  resources/istio/templates/istio-manager-config.yaml
  resources/istio/values.yaml
Labels: kind/feature, area/service-mesh, size/XS, lgtm

#17959 Preserve EventMesh precomputed hashes
  components/eventing-controller/api/v1alpha2/status_types.go
  components/eventing-controller/api/v1alpha2/status_types_test.go
  components/eventing-controller/controllers/subscription/eventmesh/reconciler.go
  components/eventing-controller/controllers/subscription/eventmesh/reconciler_internal_integration_test.go
  components/eventing-controller/pkg/ems/api/events/client/client_test.go
  components/eventing-controller/pkg/ems/api/events/types/types.go
  components/eventing-controller/pkg/subscriptionmanager/eventmesh/eventmesh.go
  components/eventing-controller/pkg/subscriptionmanager/eventmesh/eventmesh_test.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/values.yaml
Labels: kind/bug, area/eventing, size/L, lgtm

#17964 Configuration for installation of Istio operator
  resources/istio/templates/istio-manager-config.yaml
  resources/istio/values.yaml
Labels: size/XS, lgtm

#17988 update link to Telemetry docs
  docs/index.html
Labels: area/documentation, size/XS, lgtm, docs/modularization

#17990 Improve test run
  tests/function-controller/README.md
  tests/function-controller/cmd/main.go
  tests/function-controller/testsuite/tests/api_gateway.go
  tests/function-controller/testsuite/tests/gitauth.go
  tests/function-controller/testsuite/tests/gitops.go
  tests/function-controller/testsuite/tests/light_runtimes.go
  tests/function-controller/testsuite/tests/tracing.go
Labels: size/L, lgtm

#17997 Bump ory postgres
  resources/ory/values.yaml
Labels: size/XS, lgtm

#17965 Update links for the domain change
  .kyma-project-io/build-preview.sh
  CONTRIBUTING.md
  README.md
  components/central-application-gateway/README.md
  components/function-controller/cmd/jobinit/README.md
  docs/01-overview/service-mesh/README.md
  docs/01-overview/service-mesh/smsh-03-istio-sidecars-in-kyma.md
  docs/03-tutorials/00-api-exposure/apix-04-expose-workload/apix-04-03-expose-workloads-multiple-namespaces.md
  docs/03-tutorials/00-service-management/smgt-01-deploy-service.md
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-06-api-rule-troubleshooting.md
  docs/04-operation-guides/troubleshooting/observability/obsv-02-troubleshoot-trace-backend-shows-few-traces.md
  docs/05-technical-reference/00-custom-resources/telemetry-01-logpipeline.md
  docs/05-technical-reference/svls-07-function-specification.md
  installation/README.md
  installation/resources/crds/telemetry/logpipelines.crd.yaml
  resources/README.md
  resources/serverless/README.md
  tests/components/application-connector/docs/application-connectivity-validator-tests.md
  tests/components/application-connector/docs/application-gateway-tests.md
  tests/components/application-connector/docs/compass-runtime-agent-tests.md
  tests/function-controller/README.md
  tests/serverless-bench/README.md
Labels: size/M, lgtm

#17996 updated monitoring images to alpine 1.18.3 and golang 1.20.7
  resources/monitoring/values.yaml
Labels: area/monitoring, size/S, lgtm

#17957 fix application-connector-validator caching
  components/central-application-connectivity-validator/.gitignore
  components/central-application-connectivity-validator/Makefile
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/centralapplicationconnectivityvalidator.go
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/options.go
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/options_test.go
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-connectivity-validator/hack/applications.applicationconnector.crd.yaml
  components/central-application-connectivity-validator/internal/controller/cache_sync_controller_test.go
  components/central-application-connectivity-validator/internal/controller/cachesync.go
  components/central-application-connectivity-validator/internal/controller/cachesynccontroller.go
  components/central-application-connectivity-validator/internal/controller/controller_suite_test.go
  components/central-application-connectivity-validator/internal/controller/suite_test.go
  components/central-application-connectivity-validator/internal/validationproxy/handler.go
  resources/application-connector/charts/central-application-connectivity-validator/templates/deployment.yaml
  resources/application-connector/charts/central-application-connectivity-validator/values.yaml
  resources/application-connector/values.yaml
  tests/components/application-connector/resources/patches/central-application-connectivity-validator.json
Labels: kind/bug, area/application-connector, size/XL, lgtm

#17999 Bump telemetry manager to fix metric exposure which is not following prometheus specification
  resources/telemetry/values.yaml
Labels: kind/bug, area/logging, size/XS, lgtm

#18001 Fix for caching in the Application Connectivity Validator
  components/central-application-connectivity-validator/.gitignore
  components/central-application-connectivity-validator/Makefile
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/centralapplicationconnectivityvalidator.go
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/options.go
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/options_test.go
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-connectivity-validator/hack/applications.applicationconnector.crd.yaml
  components/central-application-connectivity-validator/internal/controller/cache_sync_controller_test.go
  components/central-application-connectivity-validator/internal/controller/cachesync.go
  components/central-application-connectivity-validator/internal/controller/cachesynccontroller.go
  components/central-application-connectivity-validator/internal/controller/controller_suite_test.go
  components/central-application-connectivity-validator/internal/controller/suite_test.go
  components/central-application-connectivity-validator/internal/validationproxy/handler.go
  resources/application-connector/charts/central-application-connectivity-validator/templates/deployment.yaml
  resources/application-connector/charts/central-application-connectivity-validator/values.yaml
  resources/application-connector/values.yaml
  tests/components/application-connector/resources/patches/central-application-connectivity-validator.json
Labels: size/XL, lgtm

#18004 Bump telemetry manager to fix metric exposure which is not following prometheus specification (fix rel-2.17)
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#18017 Fix formatting
  README.md
Labels: size/XS, lgtm

#18018 Create _redirects
  docs/_redirects
Labels: size/M, lgtm

#18020 Change VERSION to 2.17.1
  VERSION
Labels: size/XS, lgtm

#18019 fix formatting for Grafana tip
  docs/04-operation-guides/security/sec-06-access-expose-grafana.md
Labels: size/XS, lgtm

#18008 Add cloud event test for python and fix python
  components/function-runtimes/python39/kubeless/ce.py
  components/function-runtimes/python39/kubeless/kubeless.py
  components/function-runtimes/python39/kubeless/requirements.txt
  resources/serverless/values.yaml
  tests/function-controller/internal/resources/runtimes/python.go
  tests/function-controller/internal/testsuite/cloud_events.go
Labels: size/L, lgtm

#18021 update to otel-collector 0.83.0 and fluent-bit 2.1.8
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/testdata/http-backend.yaml
Labels: size/S, lgtm, area/telemetry

#18011 Unify gitauth
  tests/function-controller/internal/testsuite/gitauth.go
Labels: size/M, lgtm

#18024 add dedicated eventing-priority-class
  resources/eventing/templates/priority-class.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#18032 Adjust Serverless controller resource limits
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm

#18030 bumps application connector images before 2.18 release
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, lgtm

#18035 Update telemetry-manager to enable mTLS for traces
  resources/telemetry/values.yaml
Labels: area/tracing, size/XS, lgtm

#18036 Fix Eventing tests
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: area/eventing, size/S, lgtm

#18039 Serverless Release bumps
  resources/serverless/values.yaml
Labels: size/S, lgtm

#18040 bump prometheus nats exporter and nats config reloader
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#18026 no usage of kymas global priorityclass in telemetry and monitoring component
  resources/monitoring/charts/grafana/templates/_pod.tpl
  resources/monitoring/charts/grafana/templates/image-renderer-deployment.yaml
  resources/monitoring/charts/grafana/templates/kyma-additions/auth-proxy-deployment.yaml
  resources/monitoring/charts/prometheus-istio/templates/deploy.yaml
  resources/monitoring/charts/prometheus-istio/templates/sts.yaml
  resources/monitoring/charts/prometheus-node-exporter/templates/daemonset.yaml
  resources/monitoring/templates/kyma-additions/priority-class-high.yaml
  resources/monitoring/templates/kyma-additions/priority-class.yaml
  resources/monitoring/templates/prometheus-operator/deployment.yaml
  resources/monitoring/templates/prometheus/prometheus.yaml
  resources/monitoring/values.yaml
  resources/telemetry/charts/operator/templates/deployment.yaml
Labels: area/monitoring, size/M, lgtm, kind/chore

#18028 Switch flag
  resources/eventing/charts/controller/values.yaml
Labels: size/XS, lgtm

#18043 Update telemetry-operator to make insecure flag optional
  docs/05-technical-reference/00-custom-resources/telemetry-03-tracepipeline.md
  installation/resources/crds/telemetry/tracepipelines.crd.yaml
  resources/telemetry/values.yaml
Labels: lgtm, area/telemetry

#18048 Fix response handling for non string, non object response payloads
  components/function-runtimes/nodejs/server.js
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/S, lgtm

#18052 Bump serverless runtime images before 2.18
  resources/serverless/values.yaml
Labels: area/serverless, size/S, lgtm, kind/chore

#18045 Update Telemetry images to use Golang 1.21.0
  resources/telemetry/values.yaml
Labels: size/XS, lgtm, area/telemetry

#18063 Bump serverless nodejs runtime images before 2.18
  resources/serverless/values.yaml
Labels: size/XS, lgtm, kind/chore

#18064 Remove pr images in eventing for release 2.18
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#18065 bumps images for application-connector components tests
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/S, lgtm, kind/chore

#18041 Added feature flag to disable provisioning of NATS as part of eventing
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/internal/featureflags/featureflags.go
  components/eventing-controller/pkg/env/config.go
  components/eventing-controller/pkg/env/config_test.go
  components/eventing-controller/testing/eventmeshmock.go
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/nats/templates/configmap.yaml
  resources/eventing/charts/nats/templates/destination-rule.yaml
  resources/eventing/charts/nats/templates/service.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/values.yaml
Labels: size/M, lgtm

#18072 fix the code block in the deploy expose function (#18071)
  docs/02-get-started/02-deploy-expose-function.md
Labels: size/XS, lgtm

#18075 Added feature flag to disable provisioning of NATS as part of eventing
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/internal/featureflags/featureflags.go
  components/eventing-controller/pkg/env/config.go
  components/eventing-controller/pkg/env/config_test.go
  components/eventing-controller/testing/eventmeshmock.go
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/nats/templates/configmap.yaml
  resources/eventing/charts/nats/templates/destination-rule.yaml
  resources/eventing/charts/nats/templates/service.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#18077 Change VERSION to 2.18.0-rc2
  VERSION
Labels: size/XS, lgtm

#18076 Image bump for eventing
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#18079 Change VERSION to 2.18.0-rc3
  VERSION
Labels: size/XS, lgtm

#18080 Configuration file for btp-manager removed
  resources/btp-manager/values.yaml
Labels: size/XS, lgtm

#18084 Fix for issue 18082
  docs/02-get-started/README.md
  docs/index.html
Labels: size/XS, lgtm

#18081 Move enable module doc to Get started
  docs/01-overview/README.md
  docs/02-get-started/01-quick-install.md
  docs/02-get-started/08-install-uninstall-upgrade-kyma-module.md
  docs/02-get-started/README.md
  docs/02-get-started/_sidebar.md
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/operations/05-upgrade-kyma.md
  docs/04-operation-guides/operations/07-uninstall-kyma.md
  docs/04-operation-guides/operations/08-enable-disable-upgrade-kyma-module.md
  docs/04-operation-guides/operations/README.md
  docs/04-operation-guides/operations/_sidebar.md
  docs/README.md
Labels: size/L, lgtm

#18093 Fix serverless leftovers
  README.md
  components/function-runtimes/README.md
  docs/03-tutorials/_sidebar.md
  docs/04-operation-guides/troubleshooting/_sidebar.md
  docs/glossary.md
Labels: size/XS, lgtm

#18094 Change VERSION to 2.18.0
  VERSION
Labels: size/XS, lgtm

#18069 docs: Fix links after Telemetry removal
  docs/01-overview/observability/README.md
  docs/01-overview/observability/obsv-10-useful-links.md
  docs/01-overview/service-mesh/README.md
  docs/01-overview/service-mesh/smsh-03-istio-sidecars-in-kyma.md
  docs/04-operation-guides/operations/obsv-03-enable-istio-access-logs.md
  docs/04-operation-guides/troubleshooting/observability/obsv-02-troubleshoot-trace-backend-shows-few-traces.md
  resources/telemetry/charts/operator/templates/logparser_busola_extension_cm.yaml
  resources/telemetry/charts/operator/templates/logpipeline_busola_extension_cm.yaml
  resources/telemetry/charts/operator/templates/tracepipeline_busola_extension_cm.yaml
Labels: area/documentation, size/S, lgtm, area/telemetry
