Repository kyma-project/kyma, pull requests merged in 2023-07, with the labels that each got.

#17783 Update telemetry-operator to limit Fluent Bit retries
  docs/01-overview/telemetry/telemetry-02-logs.md
  resources/telemetry/values.yaml
Labels: area/logging, size/S, lgtm

#17779 Use newest requests
  components/function-runtimes/python39/Dockerfile
  components/function-runtimes/python39/kubeless/requirements.txt
  resources/serverless/values.yaml
Labels: size/L, lgtm

#17770 Remove relative link from CRD description
  docs/05-technical-reference/00-custom-resources/telemetry-01-logpipeline.md
  hack/table-gen/Makefile
  installation/resources/crds/telemetry/logpipelines.crd.yaml
Labels: size/S, lgtm

#17782 Emphasize the freedom to choose modules
  docs/01-overview/README.md
  docs/README.md
Labels: size/XS, lgtm, docs/modularization

#17787 Change install/uninstall to enable/disable
  docs/02-get-started/01-quick-install.md
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/operations/05-upgrade-kyma.md
  docs/04-operation-guides/operations/07-uninstall-kyma.md
  docs/04-operation-guides/operations/08-enable-disable-upgrade-kyma-module.md
Labels: size/S, lgtm

#17788 Update link in the Overview
  docs/01-overview/README.md
  docs/README.md
Labels: size/XS, lgtm

#17789 Deploy loki resource
  tests/fast-integration/upgrade-test/upgrade-test-tests.js
Labels: size/S, lgtm

#17790 Revert "Deploy loki resource (#17789)"
  tests/fast-integration/upgrade-test/upgrade-test-tests.js
Labels: size/S, lgtm

#17793 Updated OAuth2 init check and added unit test
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_internal_unit_test.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#17740 Create override mechanizm for controllerSyncPeriod time in Compass Runtime Agent tests
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/deployment.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/init.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/init_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/mocks/DeploymentConfigurator.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/types/types.go
Labels: area/application-connector, size/M, lgtm

#17751 Remove Loki
  docs/01-overview/observability/README.md
  docs/01-overview/observability/obsv-02-logging-in-kyma.md
  docs/01-overview/observability/obsv-10-useful-links.md
  docs/01-overview/telemetry/assets/general-components.drawio.svg
  docs/01-overview/telemetry/assets/logging-arch.drawio.svg
  docs/01-overview/telemetry/assets/logging-pipelines.drawio.svg
  docs/01-overview/telemetry/telemetry-02-logs.md
  docs/01-overview/telemetry/telemetry-03-traces.md
  docs/02-get-started/05-observability.md
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/operations/obsv-01-access-logs.md
  docs/04-operation-guides/operations/obsv-02-adjust-loki.md
  docs/04-operation-guides/troubleshooting/observability/obsv-03-troubleshoot-loki-logging.md
  docs/05-technical-reference/00-architecture/assets/obsv-configurable-logging-architecture.drawio.svg
  docs/05-technical-reference/00-architecture/obsv-02-architecture-logging.md
  docs/05-technical-reference/00-configuration-parameters/obsv-01-configpara-observability.md
  docs/05-technical-reference/assets/obsv-logging-arch-test.svg
  docs/assets/2.16-2.17-cleanup-loki.sh
  docs/migration-guide-2.16-2.17.md
  installation/resources/components.yaml
  resources/logging/.helmignore
  resources/logging/Chart.yaml
  resources/logging/README.md
  resources/logging/charts/loki/Chart.yaml
  resources/logging/charts/loki/files/chunkCleaner.sh
  resources/logging/charts/loki/templates/_helpers.tpl
  resources/logging/charts/loki/templates/configmap-alert.yaml
  resources/logging/charts/loki/templates/ingress.yaml
  resources/logging/charts/loki/templates/kyma-additions/authorizationpolicy.yaml
  resources/logging/charts/loki/templates/kyma-additions/grafana-dashboard.yaml
  resources/logging/charts/loki/templates/kyma-additions/grafana-datasource.yaml
  resources/logging/charts/loki/templates/kyma-additions/peerauthentication.yaml
  resources/logging/charts/loki/templates/networkpolicy.yaml
  resources/logging/charts/loki/templates/pdb.yaml
  resources/logging/charts/loki/templates/podsecuritypolicy.yaml
  resources/logging/charts/loki/templates/role.yaml
  resources/logging/charts/loki/templates/rolebinding.yaml
  resources/logging/charts/loki/templates/secret.yaml
  resources/logging/charts/loki/templates/service-headless.yaml
  resources/logging/charts/loki/templates/service.yaml
  resources/logging/charts/loki/templates/serviceaccount.yaml
  resources/logging/charts/loki/templates/statefulset.yaml
  resources/logging/charts/loki/values.yaml
  resources/logging/profile-evaluation.yaml
  resources/logging/profile-production.yaml
  resources/logging/templates/_helpers.tpl
  resources/logging/values.yaml
  resources/monitoring/templates/grafana/kyma-dashboards/kyma-controllers.yaml
Labels: area/logging, size/XXL, lgtm, kind/cleanup

#17792 [WiP] adds a comment to trigger k3d-runtime-agent pipeline
  tests/components/application-connector/test/compass-runtime-agent/synchronisation_test.go
Labels: size/XS, lgtm

#17748 Renaming proposal
  components/function-controller/design/assets/kubebuilder-architecture.png
  components/function-controller/design/glossary_proposal.md
Labels: size/L, lgtm

#17796 Add unit-tests for WebhookAuth config change
  components/eventing-controller/pkg/backend/eventmesh/eventmesh_integration_test.go
  components/eventing-controller/testing/eventmeshmock.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#17650 runtime overrides-1
  resources/application-connector/profile-production.yaml
  resources/cluster-essentials/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/S, lgtm

#17800 Bump python
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17801 bump (#17800)
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17799 Change VERSION to 2.16.0
  VERSION
Labels: size/XS, lgtm

#17794 Dependencies bump for Eventing
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/L, lgtm

#17809 Adjust Logpipeline name in fast-integration test
  tests/fast-integration/telemetry-test/suite.js
Labels: area/logging, kind/failing-test, size/XS, lgtm

#17807 Update OpenTelemetry Collector to 0.81.0
  resources/telemetry/values.yaml
Labels: size/XS, lgtm, area/telemetry

#17813 Update values.yaml with btp manager security image bump to 0.4.5
  resources/btp-manager/values.yaml
Labels: size/XS, lgtm

#17808 fix broken links
  README.md
  components/central-application-gateway/README.md
  docs/04-operation-guides/troubleshooting/observability/obsv-02-troubleshoot-trace-backend-shows-few-traces.md
  resources/serverless/README.md
  resources/telemetry/charts/operator/templates/logpipeline_busola_extension_cm.yaml
Labels: size/S, lgtm

#17802 record backend-errors with latency in epp
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/handler/handler_test.go
  components/event-publisher-proxy/pkg/handler/handler_v1alpha1_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#17819 [Cherry-Pick] Retrigger runtimes build
  components/function-runtimes/nodejs/nodejs16/Dockerfile
  components/function-runtimes/nodejs/nodejs18/Dockerfile
  components/function-runtimes/python39/Dockerfile
Labels: size/XS, lgtm

#17818 Retrigger runtimes build
  components/function-runtimes/nodejs/nodejs16/Dockerfile
  components/function-runtimes/nodejs/nodejs18/Dockerfile
  components/function-runtimes/python39/Dockerfile
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17820 Don't use global.priorityClassName
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/templates/priority-class.yaml
  resources/api-gateway/values.yaml
  resources/ory/charts/gcloud-sqlproxy/templates/deployment.yaml
  resources/ory/charts/hydra/charts/hydra-maester/templates/deployment.yaml
  resources/ory/charts/hydra/templates/deployment.yaml
  resources/ory/charts/oathkeeper/charts/oathkeeper-maester/templates/deployment.yaml
  resources/ory/charts/oathkeeper/templates/deployment-controller.yaml
  resources/ory/charts/oathkeeper/templates/deployment-sidecar.yaml
  resources/ory/charts/postgresql/templates/statefulset-slaves.yaml
  resources/ory/charts/postgresql/templates/statefulset.yaml
  resources/ory/templates/priority-class.yaml
  resources/ory/values.yaml
Labels: size/M, lgtm

#17821 Change the port for the node exporter sevice
  resources/monitoring/charts/prometheus-node-exporter/values.yaml
Labels: area/monitoring, size/XS, lgtm

#17795 Application connectivity validator performance improvements
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/centralapplicationconnectivityvalidator.go
  components/central-application-connectivity-validator/internal/controller/cachesync.go
  components/central-application-connectivity-validator/internal/controller/cachesync_test.go
  components/central-application-connectivity-validator/internal/controller/cachesynccontroller.go
  components/central-application-connectivity-validator/internal/validationproxy/handler.go
  components/central-application-connectivity-validator/internal/validationproxy/handler_test.go
  resources/application-connector/values.yaml
Labels: size/L, lgtm

#17798 revert compass-runtime-agent pipeline trigger
  tests/components/application-connector/test/compass-runtime-agent/synchronisation_test.go
Labels: size/XS, lgtm

#17652 Update production profile for monitoring component
  resources/monitoring/profile-evaluation.yaml
  resources/monitoring/profile-production.yaml
Labels: area/monitoring, size/S, lgtm

#17834 Revert "Change the port for the node exporter sevice (#17821)"
  resources/monitoring/charts/prometheus-node-exporter/values.yaml
Labels: area/monitoring, size/XS, lgtm

#17812 Bump kiwigrid k8s-sidecar to 1.24.6 version
  resources/monitoring/charts/grafana/templates/_pod.tpl
  resources/monitoring/values.yaml
Labels: area/monitoring, size/XS, lgtm

#17829 Update module documentation domain
  docs/01-overview/README.md
  docs/README.md
Labels: size/XS, lgtm

#17822 simplify sender interface
  components/event-publisher-proxy/pkg/commander/eventmesh/eventmesh.go
  components/event-publisher-proxy/pkg/commander/nats/nats.go
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/handler/handler_test.go
  components/event-publisher-proxy/pkg/handler/handler_v1alpha1_test.go
  components/event-publisher-proxy/pkg/metrics/collector.go
  components/event-publisher-proxy/pkg/metrics/collector_test.go
  components/event-publisher-proxy/pkg/metrics/metricstest/metricstest.go
  components/event-publisher-proxy/pkg/sender/common/backendpublisherror.go
  components/event-publisher-proxy/pkg/sender/eventmesh/eventmesh.go
  components/event-publisher-proxy/pkg/sender/eventmesh/eventmesh_test.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream_test.go
  components/event-publisher-proxy/pkg/sender/sender.go
  docs/04-operation-guides/operations/evnt-02-eventing-metrics.md
  resources/eventing/values.yaml
Labels: area/eventing, size/XXL, lgtm

#17835 Bump DependaBot PRs
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/S, lgtm

#17840 Update Istio version to 1.18.1
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: area/service-mesh, size/S, lgtm, kind/chore

#17811 Deconfigure istio proxy tracer explicit to avoid DNS lookups
  resources/istio/values.yaml
Labels: kind/bug, area/service-mesh, area/tracing, size/XS, lgtm, area/telemetry

#17844 Bump telemetry manager image version
  resources/telemetry/values.yaml
Labels: size/XS, lgtm, area/telemetry

#17845 Add mock target for simple tracing
  tests/function-controller/Makefile
Labels: size/S, lgtm

#17848 fix upgrade job
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
Labels: size/M, lgtm

#17823 Deploy Loki resource during upgrade process (#17791)
  tests/fast-integration/upgrade-test/upgrade-test-tests.js
Labels: lgtm, area/tests

#17842 Release 2.16.1 app con val performance
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/centralapplicationconnectivityvalidator.go
  components/central-application-connectivity-validator/internal/controller/cachesync.go
  components/central-application-connectivity-validator/internal/controller/cachesync_test.go
  components/central-application-connectivity-validator/internal/controller/cachesynccontroller.go
  components/central-application-connectivity-validator/internal/validationproxy/handler.go
  components/central-application-connectivity-validator/internal/validationproxy/handler_test.go
Labels: kind/bug, area/application-connector, size/L, lgtm

#17825 Add script for Jellyfish prow job
  CODEOWNERS
  tests/fast-integration/prow/kyma-upgrade.sh
Labels: size/S, lgtm

#17852 Adapt EC for eventing manager
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  components/eventing-controller/pkg/backend/jetstream/utils.go
  components/eventing-controller/pkg/env/nats_config.go
Labels: size/M, lgtm

#17846 Add instructions for nodejs debugging locally
  components/function-runtimes/nodejs/.gitignore
  components/function-runtimes/nodejs/README.md
Labels: size/S, lgtm

#17824 Contract test for tracing propagation in serverless
  components/function-runtimes/nodejs/lib/helper.js
  resources/serverless/values.yaml
  tests/function-controller/Makefile
  tests/function-controller/cmd/main.go
  tests/function-controller/run-local.sh
  tests/function-controller/testsuite/runtimes/nodejs.go
  tests/function-controller/testsuite/scenarios/tracing.go
  tests/function-controller/testsuite/teststep/check.go
Labels: area/serverless, size/L, lgtm, area/tests

#17858 Bump telemetry manager to enable custom metric scraping
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#17831 Move SKR tests to KEB repository
  tests/fast-integration/Makefile
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/kcp/client.js
  tests/fast-integration/eventing-test/kyma-environment-broker/client.js
  tests/fast-integration/eventing-test/kyma-environment-broker/helpers.js
  tests/fast-integration/eventing-test/kyma-environment-broker/index.js
  tests/fast-integration/eventing-test/provision/deprovision-skr.js
  tests/fast-integration/eventing-test/provision/provision-skr.js
  tests/fast-integration/eventing-test/skr-helpers/helpers.js
  tests/fast-integration/keb-endpoints-test/index.js
  tests/fast-integration/package.json
  tests/fast-integration/skr-aws-upgrade-integration/.env.template
  tests/fast-integration/skr-aws-upgrade-integration/index.js
  tests/fast-integration/skr-aws-upgrade-integration/readme.md
  tests/fast-integration/skr-aws-upgrade-integration/upgrade/upgrade-skr.js
  tests/fast-integration/skr-nightly/.env.template
  tests/fast-integration/skr-nightly/provision/provision-skr-nightly.js
  tests/fast-integration/skr-nightly/readme.md
  tests/fast-integration/skr-test/.env.template
  tests/fast-integration/skr-test/README.md
  tests/fast-integration/skr-test/btp-manager-secret/index.js
  tests/fast-integration/skr-test/deprovision-skr.js
  tests/fast-integration/skr-test/index.js
  tests/fast-integration/skr-test/machine-type/index.js
  tests/fast-integration/skr-test/oidc/index.js
  tests/fast-integration/skr-test/provision-skr.js
  tests/fast-integration/skr-test/provision/deprovision-skr.js
  tests/fast-integration/skr-test/provision/provision-skr.js
  tests/fast-integration/skr-test/test-own-cluster.js
  tests/fast-integration/skr-test/test.js
  tests/fast-integration/smctl/helpers.js
Labels: size/XXL, lgtm

#17860 Fix typo in the Eventing controller logs
  components/eventing-controller/pkg/backend/eventmesh/eventmesh.go
  resources/eventing/values.yaml
Labels: area/eventing, size/S, lgtm

#17862 bumps release-2.16 branch with #17842 cherry-pick
  resources/application-connector/values.yaml
Labels: kind/bug, area/application-connector, size/XS, lgtm

#17851 Enable envoy dynamic bootstrap
  resources/istio/values.yaml
Labels: kind/bug, area/service-mesh, size/XS, lgtm

#17863 Bump telemetry manager
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#17856 Tracing test python
  components/function-runtimes/python39/Dockerfile
  components/function-runtimes/python39/kubeless/requirements.txt
  components/function-runtimes/python39/kubeless/tracing.py
  resources/serverless/values.yaml
  tests/function-controller/pkg/gitserver/gitserver.go
  tests/function-controller/pkg/k8s/deployment.go
  tests/function-controller/pkg/k8s/service.go
  tests/function-controller/testsuite/gitops/cfg.go
  tests/function-controller/testsuite/runtimes/nodejs.go
  tests/function-controller/testsuite/runtimes/python.go
  tests/function-controller/testsuite/scenarios/tracing.go
  tests/function-controller/testsuite/teststep/app.go
  tests/function-controller/testsuite/teststep/check.go
Labels: size/XL, lgtm

#17866 Add instructions to run python locally
  components/function-runtimes/nodejs/README.md
  components/function-runtimes/python39/kubeless/.gitignore
  components/function-runtimes/python39/kubeless/README.md
  components/function-runtimes/python39/kubeless/kubeless.py
  resources/serverless/values.yaml
Labels: size/M, lgtm

#17839 expose health status as metric
  components/event-publisher-proxy/cmd/event-publisher-proxy/main.go
  components/event-publisher-proxy/pkg/metrics/collector.go
  components/eventing-controller/Makefile
  docs/04-operation-guides/operations/evnt-02-eventing-metrics.md
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#17875 Bump telemetry manager
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#17878 Update telemetry-operator to include Fluent Bit 2.1.7
  resources/telemetry/values.yaml
Labels: size/XS, lgtm, area/telemetry

#17884 Change VERSION to 2.16.1
  VERSION
Labels: size/XS, lgtm

#17836 change the namespace for jaeger
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/test/fixtures/jaeger/jaeger.yaml
  tests/fast-integration/utils/index.js
Labels: kind/bug, area/tracing, kind/failing-test, size/S, lgtm

#17850 Makefile targets for Application Connector k3d tests
  components/central-application-gateway/cmd/applicationgateway/applicationproxy.go
  tests/components/application-connector/hack/ci/Makefile
Labels: area/application-connector, size/M, lgtm

#17891 Update Istio to version 1.18.2
  resources/istio/values.yaml
Labels: area/service-mesh, size/XS, lgtm, kind/chore

#17892 Change image in the github release action
  .github/workflows/github-release.yaml
Labels: size/XS, lgtm

#17893 Remove Application connector PR images for kyma 2 17 Release
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
Labels: size/S, lgtm

#17895 Docs fixes
  docs/01-overview/api-exposure/apix-03-api-gateway-limitations.md
  docs/03-tutorials/00-api-exposure/apix-04-expose-workload/apix-04-02-expose-multiple-workloads.md
  docs/04-operation-guides/troubleshooting/security/sec-02-oauth2-protected-apirules.md
  docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
  docs/05-technical-reference/svls-07-function-specification.md
Labels: size/L, lgtm

#17889 Change istio disable injection annotation to label in API Gateway
  resources/api-gateway/templates/_helpers.tpl
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/templates/webhook-certificates.yaml
  resources/api-gateway/values.yaml
Labels: area/service-mesh, size/S, lgtm, kind/chore

#17896 bump BTP manager to 0.4.7
  resources/btp-manager/values.yaml
Labels: size/XS, lgtm

#17899 Use latest main images for EPP and EC
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#17901 Bump serverless runtime images
  resources/serverless/values.yaml
Labels: area/serverless, size/S, lgtm, kind/chore

#17898 Do not add pipleine to fluent bit configmap if secret ref is missing
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/testdata/tracepipeline-jaeger.yaml
  tests/fast-integration/telemetry-test/testdata/tracepipeline-test-app.yaml
Labels: kind/bug, area/logging, size/XS, lgtm, area/telemetry

#17902 Fix broken links
  docs/01-overview/serverless/svls-05-useful-links.md
  docs/01-overview/serverless/svls-07-limitations.md
  docs/03-tutorials/00-eventing/evnt-05-send-legacy-events.md
  docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
  docs/03-tutorials/00-serverless/svls-03-expose-function.md
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
  docs/03-tutorials/00-serverless/svls-12-customize-function-traces.md
Labels: size/S, lgtm

#17909 Fix release GH Action
  .github/workflows/github-release.yaml
Labels: size/XS, lgtm

#17910 Fix release GH Action
  .github/workflows/github-release.yaml
Labels: size/XS, lgtm
