Repository kyma-project/kyma, pull requests merged in 2023-03, with the labels that each got.

#16954 Set Istio cni namespace
  resources/istio/templates/istio-operator.yaml
Labels: size/XS, lgtm

#16955 Set Istio cni namespace
  resources/istio/templates/istio-operator.yaml
Labels: size/XS, lgtm

#16965 Deprecate nodejs14 runtime - remove from docs
  components/function-controller/README.md
  docs/03-tutorials/00-api-exposure/apix-01-create-workload.md
  docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
  docs/03-tutorials/00-serverless/svls-02-create-git-function.md
  docs/03-tutorials/00-serverless/svls-09-log-into-private-packages-registry.md
  docs/03-tutorials/00-serverless/svls-14-inject-envs.md
  docs/03-tutorials/00-serverless/svls-15-use-external-scalers.md
  docs/04-operation-guides/troubleshooting/serverless/svls-02-failing-function-container.md
  docs/04-operation-guides/troubleshooting/serverless/svls-03-function-debugger-in-strange-location.md
  docs/04-operation-guides/troubleshooting/serverless/svls-04-function-build-failing-on-k3d.md
  docs/05-technical-reference/00-configuration-parameters/svls-02-environment-variables.md
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  docs/05-technical-reference/svls-01-sample-functions.md
  docs/05-technical-reference/svls-02-function-processing-stages.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
  docs/05-technical-reference/svls-07-supported-webhooks.md
  docs/05-technical-reference/svls-08-function-specification.md
Labels: area/documentation, area/serverless, size/M, lgtm

#16946 Added doc for eventing-sink test function
  tests/fast-integration/eventing-test/assets/README.md
Labels: size/M, lgtm

#16918 Add nodejs18 in function controller
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/design/extend_function_spec_proposal.md
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  components/function-controller/internal/controllers/serverless/fixtures_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_gitops_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/gitops_test.go
  components/function-controller/internal/controllers/serverless/gitrepo/git_repo_controller_test.go
  components/function-controller/internal/controllers/serverless/runtime/nodejs_test.go
  components/function-controller/internal/controllers/serverless/runtime/runtime.go
  components/function-controller/internal/controllers/serverless/runtime/runtime_test.go
  components/function-controller/internal/controllers/serverless/utils.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/runtime_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/runtime_validation.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/templates/runtimes.yaml
  resources/serverless/values.yaml
  tests/fast-integration/eventing-test/assets/eventing-function.yaml
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
Labels: area/serverless, size/XL, lgtm

#16903 nats-server-config-reloader v0.10.1.
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#16967 Bump postgres image to 11.19-alpine3.17
  resources/ory/values.yaml
Labels: size/XS, lgtm

#16942 Refactor stream and consumer not created checks in Eventing FI tests
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: size/L, lgtm

#16953 Remove the tests as this test code is not needed any more
  tests/telemetry-operator-perf-tests/Makefile
  tests/telemetry-operator-perf-tests/README.md
  tests/telemetry-operator-perf-tests/deploy/http.yml
  tests/telemetry-operator-perf-tests/deploy/logspammer.yaml
  tests/telemetry-operator-perf-tests/deploy/loki.yml
  tests/telemetry-operator-perf-tests/deploy/mockserver-vs.yaml
  tests/telemetry-operator-perf-tests/deploy/mockserver.yaml
  tests/telemetry-operator-perf-tests/deploy/telemetry-config.yaml
  tests/telemetry-operator-perf-tests/go.mod
  tests/telemetry-operator-perf-tests/go.sum
  tests/telemetry-operator-perf-tests/main.go
  tests/telemetry-operator-perf-tests/prometheus.go
  tests/telemetry-operator-perf-tests/results/assets/cpu-cores.jpg
  tests/telemetry-operator-perf-tests/results/assets/input-throughput-100-good.jpg
  tests/telemetry-operator-perf-tests/results/assets/input-throughput-50-bad.jpg
  tests/telemetry-operator-perf-tests/results/assets/memory.jpg
  tests/telemetry-operator-perf-tests/results/assets/output-throughput-100-good.jpg
  tests/telemetry-operator-perf-tests/results/assets/output-throughput-50-bad.jpg
  tests/telemetry-operator-perf-tests/results/assets/setup-3c.drawio.svg
  tests/telemetry-operator-perf-tests/results/assets/setup.drawio.svg
  tests/telemetry-operator-perf-tests/results/test-1.md
  tests/telemetry-operator-perf-tests/unstructured.go
Labels: size/XXL, lgtm

#16979 update node14 to version: 14.21.3 (#16914)
  components/function-runtimes/nodejs/nodejs18/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
  resources/serverless/values.yaml
Labels: size/S, lgtm

#16964 fixed link in migration guide
  docs/migration-guide-2.11-2.12.md
Labels: area/documentation, size/XS, lgtm, area/telemetry

#16980 bump serverless images
  resources/serverless/values.yaml
Labels: size/S, lgtm

#16876 Change the migration script name
  docs/assets/2.11-2.12-delete-compass-system-namespace.sh
Labels: area/documentation, size/XS, lgtm

#16985 Change link in 2.12 Migration Guide
  docs/migration-guide-2.11-2.12.md
Labels: area/documentation, size/XS, lgtm

#16988 Changed the k8s version number in the line 13.
  docs/04-operation-guides/operations/02-install-kyma.md
Labels: size/XS, lgtm

#16992 upgrade golang.org/x/net to v0.7.0
  components/function-controller/go.mod
  components/function-controller/go.sum
Labels: size/S, lgtm

#16986 change alpha1 to alpha2 in Trigger a workload with an event
  docs/02-get-started/04-trigger-workload-with-event.md
Labels: area/documentation, area/serverless, lgtm

#17005 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17006 Bump k8s-tools image in Kyma 2.11
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17007 Clean up the comments in Subscription v1alpha2.
  components/eventing-controller/api/v1alpha2/condition.go
  components/eventing-controller/api/v1alpha2/groupversion_info.go
  components/eventing-controller/api/v1alpha2/status_types.go
  components/eventing-controller/api/v1alpha2/subscription_types.go
  components/eventing-controller/api/v1alpha2/subscription_webhook.go
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/config/crd/basesv1alpha2/eventing.kyma-project.io_subscriptions.yaml
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#16978 Remove PR images from application-connector code before release 2.12
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/S, lgtm

#17014 Update Eventing images
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#17017 Remove a broken link
  README.md
Labels: size/XS, lgtm

#16989 change alpha1 to alpha2 in AC and Eventing tutorials
  docs/03-tutorials/00-application-connectivity/ac-01-create-application.md
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
  docs/03-tutorials/00-eventing/evnt-03-type-cleanup.md
  docs/03-tutorials/00-eventing/evnt-04-change-max-in-flight-in-sub.md
Labels: area/documentation, area/serverless, size/L, lgtm

#16990 Exclude default `request` auto-instrumentation in python functions
  components/function-runtimes/python39/Dockerfile
  components/function-runtimes/python39/kubeless/kubeless.py
  components/function-runtimes/python39/kubeless/requirements.txt
  components/function-runtimes/python39/kubeless/tracing.py
  resources/serverless/values.yaml
Labels: area/serverless, size/M, lgtm, area/telemetry

#17020 Replace python runtime image tag
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17019 refactor Function alpha2 code
  docs/02-get-started/04-trigger-workload-with-event.md
Labels: area/documentation, area/serverless, size/S, lgtm

#16931 Documentation for adding schema versioning for v1alpha1 and v1alpha2
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
Labels: area/documentation, area/serverless, size/L, lgtm

#17009 Add target to run tests as binary
  resources/serverless/charts/k3s-tests/templates/k3s-test.yaml
  resources/serverless/values.yaml
  tests/function-controller/Makefile
  tests/function-controller/go.mod
  tests/function-controller/go.sum
  tests/function-controller/pkg/function/v1alpha1/function.go
  tests/function-controller/run-local.sh
  tests/function-controller/testsuite/config.go
  tests/function-controller/testsuite/scenarios/gitauth.go
Labels: size/XXL, lgtm

#16919 SKR machineType update e2e test
  tests/fast-integration/gardener/client.js
  tests/fast-integration/kyma-environment-broker/client.js
  tests/fast-integration/kyma-environment-broker/helpers.js
  tests/fast-integration/package.json
  tests/fast-integration/skr-test/index.js
  tests/fast-integration/skr-test/machine-type/index.js
  tests/fast-integration/skr-test/test.js
Labels: size/L, lgtm

#17028 Adapt Istio default values for HPA autoscaling/v2
  resources/istio/values.yaml
  resources/monitoring/charts/grafana/values.yaml
Labels: size/S, lgtm

#17032 Fix typo in the documentation
  docs/03-tutorials/00-application-connectivity/ac-04-register-secured-api.md
Labels: area/documentation, size/XS, lgtm

#17025 Document example with Python OTEL skd
  docs/03-tutorials/00-serverless/svls-12-customize-function-traces.md
Labels: area/documentation, area/serverless, area/tracing, size/M, lgtm, area/telemetry

#17033 Document example with Python OTEL skd (#17025)
  docs/03-tutorials/00-serverless/svls-12-customize-function-traces.md
Labels: area/documentation, area/serverless, lgtm

#17034 Documentation for adding schema versioning for v1alpha1 and v1alpha2
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
Labels: size/L, lgtm

#17031 Fix missing field check for machineType update test
  tests/fast-integration/skr-test/machine-type/index.js
Labels: size/XS, lgtm

#17035 change mg links from main to release branch
  docs/migration-guide-2.11-2.12.md
Labels: size/XS, lgtm

#17036 Increase test functions' resources
  resources/serverless/values.yaml
  tests/function-controller/pkg/function/v1alpha1/function.go
  tests/function-controller/testsuite/gitops/function.go
  tests/function-controller/testsuite/runtimes/nodejs.go
  tests/function-controller/testsuite/runtimes/python.go
Labels: area/serverless, size/S, lgtm, kind/cleanup

#17041 Allow input of event types in busolas subscription form in the simple view.
  resources/eventing/charts/controller/templates/busola-extension.yaml
Labels: size/XS, lgtm

#17040 Fix priority class name for serverless controller
  resources/serverless/templates/deployment.yaml
Labels: kind/bug, area/serverless, size/XS, lgtm

#17027 Remove pbochynski from fast-integration codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#17015 change alpha1 in the Serverless tutorials
  docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
  docs/03-tutorials/00-serverless/svls-02-create-git-function.md
  docs/03-tutorials/00-serverless/svls-13-override-runtime-image.md
  docs/03-tutorials/00-serverless/svls-14-inject-envs.md
Labels: area/documentation, area/serverless, size/L, lgtm

#17029 Change v1alpha1 to v1alpha2 in the Technical reference section
  docs/05-technical-reference/00-configuration-parameters/svls-02-environment-variables.md
  docs/05-technical-reference/svls-01-sample-functions.md
Labels: area/documentation, area/serverless, size/L, lgtm

#17044 rename reserved env USERNAME
  docs/03-tutorials/00-serverless/svls-07-set-external-registry.md
Labels: size/XS, lgtm

#17047 Allow input of event types in busolas subscription form in the simple - Rel 2.12
  resources/eventing/charts/controller/templates/busola-extension.yaml
Labels: area/eventing, size/XS, lgtm

#16975 Trim down cli flags for telemetry manager
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#17046 Bumped api-gateway-webhook-certificates image in Eventing - Rel-2.12
  resources/eventing/charts/controller/templates/webhook-cert-handler.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/S, lgtm

#17045 Bumped api-gateway-webhook-certificates image in Eventing
  resources/eventing/charts/controller/templates/webhook-cert-handler.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/values.yaml
Labels: size/S, lgtm

#17055 Alpha docs
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
  docs/03-tutorials/00-serverless/svls-02-create-git-function.md
  docs/03-tutorials/00-serverless/svls-13-override-runtime-image.md
  docs/03-tutorials/00-serverless/svls-14-inject-envs.md
  docs/05-technical-reference/00-configuration-parameters/svls-02-environment-variables.md
  docs/05-technical-reference/svls-01-sample-functions.md
Labels: area/documentation, area/serverless, size/L, lgtm

#17043 Improvements for serverless integration
  resources/serverless/values.yaml
  tests/function-controller/pkg/step/cli.go
  tests/function-controller/testsuite/teststep/secret.go
Labels: size/S, lgtm

#17062 Adapt HPA spec values for autoscaling/v2 (#17028)
  resources/istio/values.yaml
  resources/monitoring/charts/grafana/values.yaml
Labels: size/S, lgtm

#17058 update images for telemetry/observabaility
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/telemetry/values.yaml
  resources/tracing/values.yaml
Labels: area/monitoring, area/logging, size/S, lgtm, area/telemetry

#17065 Fix Dependabot rules for Dockerfile in Event-Publisher-Proxy.
  .github/dependabot.yml
Labels: size/XS, lgtm

#17070 Add info on ports in the Kyma Dashboard Get Started guides
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
Labels: size/S, lgtm

#17071 Fix git-auth test config
  resources/serverless/charts/k3s-tests/templates/k3s-test.yaml
  resources/serverless/values.yaml
  tests/function-controller/testsuite/scenarios/gitauth.go
Labels: size/S, lgtm

#17073 Update NATS 2.9.15
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#17072 Fix prometheus upgrade test failed
  tests/fast-integration/monitoring/prometheus.js
Labels: size/S, lgtm

#17084 Add info on ports in the Kyma Dashboard Get Started guides (#17070)
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/03-deploy-expose-microservice.md
Labels: size/S, lgtm

#17085 remove migration guides leftovers
  docs/assets/2.11-2.12-cleanup-init-container.sh
  docs/assets/2.11-2.12-cleanup-servicemonitors.sh
  docs/assets/2.11-2.12-delete-compass-system-namespace.sh
  docs/assets/2.9-2.10-OS-copy-secrets-to-system-namespace.sh
  docs/migration-guide-2.11-2.12.md
Labels: size/M, lgtm

#17074 Update Istio to 1.17.1
  resources/istio-resources/files/dashboards/control-plane.json
  resources/istio-resources/files/dashboards/mesh.json
  resources/istio-resources/files/dashboards/performance.json
  resources/istio-resources/files/dashboards/service.json
  resources/istio-resources/files/dashboards/workload.json
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: area/service-mesh, size/S, lgtm

#17068 disable grafana external snapshot publish endpoint
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring, size/S, lgtm

#17088 Fix a broken link in apix troubleshooting guide
  docs/01-overview/main-areas/service-mesh/smsh-03-istio-sidecars-in-kyma.md
Labels: size/XS, lgtm

#16991 add test atleast once delivery for jetstream during upgrade
  tests/fast-integration/eventing-test/assets/eventing-sink.yaml
  tests/fast-integration/eventing-test/assets/eventing-upgrade-sink.yaml
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: area/eventing, size/L, lgtm

#17093 Fix prometheus upgrade test failed (#17072)
  tests/fast-integration/monitoring/prometheus.js
Labels: size/S, lgtm

#17100 Release 2.12.1
  VERSION
Labels: size/XS, lgtm

#17096 Document serverless limitations
  docs/01-overview/main-areas/serverless/svls-07-limitations.md
Labels: area/documentation, area/serverless, area/performance, size/L, lgtm

#17052 Cleaned Up Eventing Fast-integration tests from last-order function
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/metric-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: size/XL, lgtm

#17042 Add telemetry manager module parameter
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#17104 Remove Telemetry production profile
  docs/01-overview/main-areas/telemetry/telemetry-02-logs.md
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/profile-production.yaml
Labels: size/S, lgtm, area/telemetry

#17089 Remove conversion tests for v1alpha1
  tests/function-controller/Makefile
  tests/function-controller/cmd/main.go
  tests/function-controller/pkg/function/v1alpha1/function.go
  tests/function-controller/pkg/gitrepository/gitrepository.go
  tests/function-controller/testsuite/gitops/v1alpha1/cfg.go
  tests/function-controller/testsuite/gitops/v1alpha1/function.go
  tests/function-controller/testsuite/gitops/v1alpha1/gitrepository.go
  tests/function-controller/testsuite/runtimes/v1alpha1/python.go
  tests/function-controller/testsuite/scenarios/conversion.go
  tests/function-controller/testsuite/teststep/function.go
  tests/function-controller/testsuite/teststep/gitrepository.go
  tests/function-controller/testsuite/teststep/gitserver.go
Labels: size/XL, lgtm

#17105 Cherry-pick the changes to Eventing fast-integration tests
  tests/fast-integration/eventing-test/assets/eventing-sink.yaml
  tests/fast-integration/eventing-test/assets/eventing-upgrade-sink.yaml
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/metric-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: size/XL, lgtm

#17099 Update NATS 2.9.15 - `release-2.12`
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#17109 update to fluentbit 2.0.10
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/testdata/http-backend.yaml
Labels: area/logging, size/XS, lgtm, area/telemetry

#17038 Automatic table from CRD generation
  docs/05-technical-reference/00-custom-resources/telemetry-01-logpipeline.md
  docs/05-technical-reference/00-custom-resources/telemetry-02-logparser.md
  docs/05-technical-reference/00-custom-resources/telemetry-03-tracepipeline.md
  hack/table-gen/Makefile
  hack/table-gen/README.md
  hack/table-gen/go.mod
  hack/table-gen/go.sum
  hack/table-gen/table-gen.go
  hack/verify-md.sh
Labels: size/XL, lgtm, area/telemetry

#17094 Bump image for refactoring of logpipleine and logparser validations
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#17125 Serialise in json non primitive types as string
  components/function-runtimes/python39/kubeless/ce.py
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17126 Update tutorial's title
  docs/04-operation-guides/security/sec-04-ingress-egress-traffic.md
Labels: size/XS, lgtm

#17090 Remove v1alpha1 conversion webhook
  components/function-controller/cmd/webhook/main.go
  components/function-controller/config/crd/kustomization.yaml
  components/function-controller/config/crd/patches/conversion_webhook_function.yaml
  components/function-controller/internal/webhook/conversion_webhook.go
  components/function-controller/internal/webhook/conversion_webhook_test.go
  components/function-controller/internal/webhook/resources/certificates.go
  components/function-controller/internal/webhook/resources/certificates_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/conversions.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/values.yaml
Labels: size/XXL, lgtm

#17129 update prometheus config reloader image to version 0.8.0
  resources/monitoring/values.yaml
Labels: area/monitoring, size/XS, lgtm

#17091 Remove v1alpha1 - webhook's cleanup
  components/function-controller/cmd/webhook/main.go
  components/function-controller/internal/webhook/config.go
  components/function-controller/internal/webhook/defaulting_webhook.go
  components/function-controller/internal/webhook/defaulting_webhook_test.go
  components/function-controller/internal/webhook/fixtures_test.go
  components/function-controller/internal/webhook/resources/webhook_config.go
  components/function-controller/internal/webhook/resources/webhook_config_test.go
  components/function-controller/internal/webhook/validating_webhook.go
  components/function-controller/internal/webhook/validating_webhook_test.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#16968 Remove unused nodejs16 folder
  components/function-runtimes/nodejs16/.gitignore
  components/function-runtimes/nodejs16/Dockerfile
  components/function-runtimes/nodejs16/lib/ce.js
  components/function-runtimes/nodejs16/lib/helper.js
  components/function-runtimes/nodejs16/lib/tracer.js
  components/function-runtimes/nodejs16/package.json
  components/function-runtimes/nodejs16/server.js
Labels: size/XL, lgtm, kind/cleanup

#17124 Clean the replaces in eventing.
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/M, lgtm

#17134 Serverless module defines its CRDs
  resources/serverless/templates/crds.yaml
Labels: size/XL, lgtm

#17153 Bump postgres image to 11.19-alpine3.17
  resources/ory/values.yaml
Labels: size/XS, lgtm

#17138 Restrict localhost `trust` auth in favour of `md5`
  resources/ory/charts/postgresql/files/pg_hba.conf
  resources/ory/charts/postgresql/templates/statefulset-slaves.yaml
  resources/ory/charts/postgresql/templates/statefulset.yaml
  resources/ory/charts/postgresql/values.yaml
Labels: area/api-gateway, size/S, lgtm

#17156 Security fix 2.12
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-controller/go.mod
  components/function-controller/go.sum
  resources/serverless/values.yaml
Labels: size/M, lgtm

#17165 Bump Registry (Security)
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17170 Bump Registry Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
Labels: size/XS, lgtm

#17141 Upgrade Istio to 1.16.3
  resources/istio-resources/files/dashboards/control-plane.json
  resources/istio-resources/files/dashboards/mesh.json
  resources/istio-resources/files/dashboards/performance.json
  resources/istio-resources/files/dashboards/service.json
  resources/istio-resources/files/dashboards/workload.json
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: area/service-mesh, size/S, lgtm

#17172 [Telemetry] Increase Fluent Bit retry limit
  resources/telemetry/values.yaml
Labels: area/logging, size/XS, lgtm

#17174 Bump remaining components
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17169 bump application-connector images
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
Labels: size/XS, lgtm

#17177 Bump serverless (Security)
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17178 update application-connector image values
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#17175 use teams instead of individuals in codeowners file
  CODEOWNERS
Labels: size/M, lgtm

#17179 fix CVE-2022-41723 for application-connector
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
Labels: size/M, lgtm

#17181 update application-connector image values
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/XS, lgtm

#17182 Allow serverless installation in arbitraty namespace
  resources/serverless/charts/webhook/templates/configmap.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/values.yaml
Labels: area/serverless, lgtm, kind/cleanup

#17180 Change v1alpha1 to v1alpha2 serverless fast integration
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/getting-started-guide/index.js
  tests/fast-integration/utils/index.js
Labels: size/XS, lgtm

#17095 Remove old helm tests
  resources/serverless/charts/k3s-tests/Chart.yaml
  resources/serverless/charts/k3s-tests/README.md
  resources/serverless/charts/k3s-tests/templates/_helpers.tpl
  resources/serverless/charts/k3s-tests/templates/k3s-test.yaml
  resources/serverless/charts/k3s-tests/values.yaml
  resources/serverless/values.yaml
  tests/function-controller/Dockerfile
  tests/function-controller/run_integration_tests.sh
  tests/function-controller/testsuite/config.go
Labels: size/L, lgtm

#17092 Remove v1alpha1 crd
  components/function-controller/Makefile
  components/function-controller/cmd/manager/main.go
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/config/crd/bases/serverless.kyma-project.io_gitrepositories.yaml
  components/function-controller/config/crd/kustomization.yaml
  components/function-controller/config/crd/patches/webhook_in_gitrepositories.yaml
  components/function-controller/internal/controllers/serverless/gitrepo/git_repo_controller.go
  components/function-controller/internal/controllers/serverless/gitrepo/git_repo_controller_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/doc.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_defaults_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha1/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/gitrepository_types.go
  components/function-controller/pkg/apis/serverless/v1alpha1/gitrepository_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha1/gitrepository_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha1/groupversion_info.go
  components/function-controller/pkg/apis/serverless/v1alpha1/runtime_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha1/validation_helpers.go
  components/function-controller/pkg/apis/serverless/v1alpha1/zz_generated.deepcopy.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/charts/webhook/templates/cluster-role.yaml
  resources/serverless/templates/cluster-role.yaml
  resources/serverless/values.yaml
Labels: size/XXL, lgtm

#17130 [Telemetry] Update telemetry-operator image
  resources/telemetry/values.yaml
Labels: area/logging, size/XS, lgtm

#17185 Remove k3s-tests from srvls chart definition
  resources/serverless/Chart.yaml
Labels: size/XS, lgtm, kind/cleanup

#17190 add info on Kyma import certs
  docs/02-get-started/02-deploy-expose-function.md
Labels: area/documentation, size/XS, lgtm

#17197 adjust eval and prod resource setting for istio
  resources/istio/profile-evaluation.yaml
  resources/istio/profile-production.yaml
  tests/components/istio/features/istio_evaluation.feature
  tests/components/istio/features/istio_production.feature
Labels: size/S, lgtm

#17209 Script preparation for prow job
  hack/verify-md.sh
Labels: size/XS, lgtm

#17187 Fullfill stub for webhooks
  components/function-controller/hack/config.yaml
  components/function-controller/internal/webhook/resources/resources.go
  components/function-controller/internal/webhook/resources/resources_test.go
  components/function-controller/internal/webhook/resources/webhook_config.go
  components/function-controller/internal/webhook/resources/webhook_config_test.go
  resources/serverless/charts/webhook/templates/webhooks.yaml
  resources/serverless/values.yaml
Labels: size/XL, lgtm
