Repository kyma-project/kyma, pull requests merged in 2023-02, with the labels that each got.

#16693 Migrate connectivity validator after operator removal
  components/central-application-connectivity-validator/cmd/centralapplicationconnectivityvalidator/centralapplicationconnectivityvalidator.go
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-connectivity-validator/internal/controller/cachesync.go
  components/central-application-connectivity-validator/internal/controller/cachesync_test.go
  components/central-application-connectivity-validator/internal/controller/cachesynccontroller.go
  components/central-application-connectivity-validator/internal/validationproxy/handler_test.go
  resources/application-connector/values.yaml
Labels: size/L, lgtm

#16681 Configure PSA for Eventing components
  components/eventing-controller/pkg/deployment/publisher_deployment.go
  components/eventing-controller/pkg/deployment/publisher_deployment_integration_test.go
  components/eventing-controller/utils/utils.go
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#16704 switch owners of observability components to github team approach
  CODEOWNERS
Labels: size/M, lgtm

#16706 Fix content-type header check in python runtime
  components/function-runtimes/python39/kubeless/kubeless.py
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#16668 Enable managed fluent-bit
  components/telemetry-operator/config/rbac/role.yaml
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/controller_test.go
  components/telemetry-operator/controller/logpipeline/suite_test.go
  components/telemetry-operator/internal/kubernetes/daemonset.go
  components/telemetry-operator/internal/kubernetes/utils.go
  components/telemetry-operator/internal/resources/logpipeline/resources.go
  components/telemetry-operator/internal/resources/logpipeline/resources_test.go
  components/telemetry-operator/main.go
  resources/telemetry/charts/fluent-bit/.helmignore
  resources/telemetry/charts/fluent-bit/Chart.yaml
  resources/telemetry/charts/fluent-bit/templates/NOTES.txt
  resources/telemetry/charts/fluent-bit/templates/_helpers.tpl
  resources/telemetry/charts/fluent-bit/templates/_pod.tpl
  resources/telemetry/charts/fluent-bit/templates/clusterrole.yaml
  resources/telemetry/charts/fluent-bit/templates/clusterrolebinding.yaml
  resources/telemetry/charts/fluent-bit/templates/configmap-luascripts.yaml
  resources/telemetry/charts/fluent-bit/templates/configmap.yaml
  resources/telemetry/charts/fluent-bit/templates/daemonset.yaml
  resources/telemetry/charts/fluent-bit/templates/deployment.yaml
  resources/telemetry/charts/fluent-bit/templates/ingress.yaml
  resources/telemetry/charts/fluent-bit/templates/pdb.yaml
  resources/telemetry/charts/fluent-bit/templates/prometheusrule.yaml
  resources/telemetry/charts/fluent-bit/templates/psp.yaml
  resources/telemetry/charts/fluent-bit/templates/scc.yaml
  resources/telemetry/charts/fluent-bit/templates/service.yaml
  resources/telemetry/charts/fluent-bit/templates/serviceaccount.yaml
  resources/telemetry/charts/fluent-bit/templates/tests/test-connection.yaml
  resources/telemetry/charts/fluent-bit/values.yaml
  resources/telemetry/charts/operator/dashboards/fluent-bit.json
  resources/telemetry/charts/operator/templates/_helpers.tpl
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/templates/fluent-bit/configmap-dashboards.yaml
  resources/telemetry/charts/operator/templates/fluent-bit/networkpolicy.yaml
  resources/telemetry/charts/operator/templates/fluent-bit/peerauthentication.yaml
  resources/telemetry/charts/operator/templates/fluent-bit/service-monitor.yaml
  resources/telemetry/charts/operator/templates/role-binding.yaml
  resources/telemetry/charts/operator/templates/role.yaml
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/values.yaml
Labels: size/XXL, lgtm

#16713 Upgrade runtimes bases
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/nodejs16/Dockerfile
  components/function-runtimes/python39/Dockerfile
Labels: area/serverless, size/XS, lgtm

#16714 Upgrade runtimes bases
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/nodejs16/Dockerfile
  components/function-runtimes/python39/Dockerfile
  resources/serverless/values.yaml
Labels: area/serverless, size/S, lgtm

#16662 Read from tail flag inclusion
  components/telemetry-operator/internal/resources/logpipeline/resources.go
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#16715 Replace serverless PR tags
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm

#16701 Add custom header support for TracePipeline output
  components/telemetry-operator/apis/telemetry/v1alpha1/tracepipeline_types.go
  components/telemetry-operator/apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  components/telemetry-operator/config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  components/telemetry-operator/controller/tracepipeline/config_builder.go
  components/telemetry-operator/controller/tracepipeline/config_builder_test.go
  components/telemetry-operator/controller/tracepipeline/secret_refs.go
  components/telemetry-operator/controller/tracepipeline/secret_refs_test.go
  components/telemetry-operator/internal/utils/envvar/format.go
  installation/resources/crds/telemetry/tracepipelines.crd.yaml
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#16709 Conform serverless webhooks with gardener hibernation constaints
  components/function-controller/internal/webhook/resources/webhook_config.go
  resources/serverless/charts/webhook/templates/webhooks.yaml
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/M, lgtm

#16712 Clean up go mod `replace`
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
Labels: size/XS, lgtm

#16723 Use standardised tag for function webhook image
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm

#16719 Add documentation for custom header usage in TracePipelines
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
  docs/05-technical-reference/00-custom-resources/telemetry-03-tracepipeline.md
Labels: size/M, lgtm

#16721 Eventing image bumps
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#16707 Bump API-Gateway image to release 1.3.0
  resources/api-gateway/Chart.yaml
  resources/api-gateway/values.yaml
Labels: area/api-gateway, size/XS, lgtm

#16725 Bump AC images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/XS, lgtm

#16724 Fix for failing integration tests
  tests/fast-integration/telemetry-test/suite.js
Labels: size/XS, lgtm

#16726 add tests for managed fluent-bit
  components/telemetry-operator/controller/logpipeline/controller_test.go
Labels: size/L, lgtm

#16705 Update istio to 1.16.2
  resources/istio-resources/files/dashboards/control-plane.json
  resources/istio-resources/files/dashboards/mesh.json
  resources/istio-resources/files/dashboards/performance.json
  resources/istio-resources/files/dashboards/service.json
  resources/istio-resources/files/dashboards/workload.json
  resources/istio/Chart.yaml
  resources/istio/values.yaml
Labels: area/service-mesh, size/S, lgtm

#16727 Ory Postgress configuration changes for monitoring
  resources/ory/charts/postgresql/values.yaml
Labels: size/XS, lgtm

#16728 Disabled NATS security context
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/values.yaml
Labels: area/eventing, lgtm

#16735 Remove gherkin reference implementation
  tests/components/reconciler/Makefile
  tests/components/reconciler/e2e_test.go
  tests/components/reconciler/features/incident-recovery.feature
  tests/components/reconciler/features/kyma-lifecycle.feature
  tests/components/reconciler/features/module-template.feature
  tests/components/reconciler/given.go
  tests/components/reconciler/go.mod
  tests/components/reconciler/go.sum
  tests/components/reconciler/then.go
Labels: size/XL, lgtm, area/tests

#16734 Fix left over issues with managed fluentbit
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/suite_test.go
  components/telemetry-operator/internal/resources/logpipeline/resources.go
  components/telemetry-operator/internal/resources/logpipeline/resources_test.go
  components/telemetry-operator/main.go
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/profile-production.yaml
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#16729 bump to non pr image
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#16737 bump all telemetry images to release images
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#16530 [Do-Not-Merge] Update Function Docs for Eventing New CRD
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
Labels: size/M, lgtm

#16741 Revert function docs changes
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
Labels: size/M, lgtm

#16688 Add retries in eventing fast integration
  tests/fast-integration/eventing-test/eventing-test.js
Labels: size/XS, lgtm

#16759 Fix compare stream config - Release 2.11
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_internal_unit_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_unit_test.go
Labels: area/eventing, size/L, lgtm

#16762 Image bumps for Eventing - rel 2.11
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#16756 Fixed NATS config comparison
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream_internal_unit_test.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream_unit_test.go
  resources/eventing/values.yaml
Labels: area/eventing, size/L, lgtm

#16760 Adding headers to busola tracepipeline extensions
  resources/telemetry/charts/operator/templates/tracepipeline_busola_extension_cm.yaml
Labels: size/M, lgtm

#16720 Fix Eventing Metrics for new CRD
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/handler/handler_test.go
  components/event-publisher-proxy/pkg/handler/handler_v1alpha2_test.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#16766 Temporarily re-add FluentBit ServiceMonitor
  resources/telemetry/charts/operator/templates/fluent-bit/service-monitor.yaml
  resources/telemetry/charts/operator/values.yaml
Labels: area/monitoring, size/M, lgtm

#16767 Always have dynamic-parsers config file
  components/telemetry-operator/controller/logparser/sync.go
  components/telemetry-operator/controller/logpipeline/controller.go
  components/telemetry-operator/controller/logpipeline/controller_test.go
  components/telemetry-operator/internal/kubernetes/utils.go
  components/telemetry-operator/internal/resources/logpipeline/resources.go
  resources/telemetry/values.yaml
Labels: size/M, lgtm

#16781 remove init container from fluentbit
  components/telemetry-operator/internal/resources/logpipeline/resources.go
  components/telemetry-operator/internal/resources/logpipeline/resources_test.go
  components/telemetry-operator/main.go
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/values.yaml
Labels: size/M, lgtm

#16789 adjust busola get started to recent changes
  docs/02-get-started/02-deploy-expose-function.md
  docs/02-get-started/04-trigger-workload-with-event.md
Labels: size/S, lgtm

#16797 Rename 2.12-cleanup-servicemonitors.sh to 2.11-2.12-cleanup-servicemo…
  docs/assets/2.11-2.12-cleanup-servicemonitors.sh
Labels: size/XS, lgtm

#16796 fix naming and link in mg211-212
  docs/migration-guide-2.11-2.12.md
  docs/migration-guide-2.12.md
Labels: size/XS, lgtm

#16752 Add Debug log for Deleting Dangling Consumer
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#16764 update fluentbit to 2.0.9
  components/telemetry-operator/Dockerfile
  components/telemetry-operator/config/samples/http-mockserver.yaml
  components/telemetry-operator/main.go
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/testdata/http-backend.yaml
Labels: area/logging, size/S, lgtm

#16800 Add tests to logparser controller
  components/telemetry-operator/controller/logparser/controller_test.go
  components/telemetry-operator/controller/logparser/suite_test.go
  components/telemetry-operator/controller/logpipeline/controller_test.go
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#16553 change epp linter config
  components/event-publisher-proxy/.golangci.yaml
  components/event-publisher-proxy/pkg/application/clean_test.go
  components/event-publisher-proxy/pkg/application/lister.go
  components/event-publisher-proxy/pkg/cloudevents/builder/eventmesh.go
  components/event-publisher-proxy/pkg/cloudevents/builder/generic.go
  components/event-publisher-proxy/pkg/cloudevents/eventtype/clean.go
  components/event-publisher-proxy/pkg/cloudevents/eventtype/clean_test.go
  components/event-publisher-proxy/pkg/cloudevents/utils.go
  components/event-publisher-proxy/pkg/commander/beb/beb.go
  components/event-publisher-proxy/pkg/commander/commander.go
  components/event-publisher-proxy/pkg/env/eventmesh_config.go
  components/event-publisher-proxy/pkg/env/eventmesh_config_test.go
  components/event-publisher-proxy/pkg/env/nats_config.go
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/handler/handler_test.go
  components/event-publisher-proxy/pkg/handler/handler_v1alpha2_test.go
  components/event-publisher-proxy/pkg/handler/health/health_test.go
  components/event-publisher-proxy/pkg/informers/sync.go
  components/event-publisher-proxy/pkg/legacy/constants.go
  components/event-publisher-proxy/pkg/legacy/error_responses.go
  components/event-publisher-proxy/pkg/legacy/helpers.go
  components/event-publisher-proxy/pkg/legacy/helpers_test.go
  components/event-publisher-proxy/pkg/legacy/legacy.go
  components/event-publisher-proxy/pkg/legacy/legacy_test.go
  components/event-publisher-proxy/pkg/legacy/legacytest/test.go
  components/event-publisher-proxy/pkg/metrics/collector.go
  components/event-publisher-proxy/pkg/metrics/metricstest/metricstest.go
  components/event-publisher-proxy/pkg/oauth/client.go
  components/event-publisher-proxy/pkg/oauth/client_test.go
  components/event-publisher-proxy/pkg/options/options.go
  components/event-publisher-proxy/pkg/receiver/receiver_test.go
  components/event-publisher-proxy/pkg/sender/eventmesh/eventmesh_test.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream.go
  components/event-publisher-proxy/pkg/signals/signals.go
  components/event-publisher-proxy/pkg/subscribed/helpers.go
  components/event-publisher-proxy/pkg/subscribed/helpers_test.go
  components/event-publisher-proxy/pkg/subscribed/response.go
  components/event-publisher-proxy/pkg/tracing/helpers_test.go
  components/event-publisher-proxy/testing/env_config.go
  components/event-publisher-proxy/testing/mock_server.go
  components/event-publisher-proxy/testing/nats.go
  components/event-publisher-proxy/testing/utils.go
  resources/eventing/values.yaml
Labels: area/eventing, size/XL, lgtm

#16769 Add deprecation notes for monitoring component
  docs/01-overview/main-areas/assets/kyma-areas.svg
  docs/01-overview/main-areas/observability/README.md
  docs/01-overview/main-areas/observability/obsv-01-monitoring-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-03-tracing-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-10-useful-links.md
  docs/01-overview/main-areas/telemetry/telemetry-02-logs.md
  docs/02-get-started/05-observability.md
  docs/03-tutorials/00-observability.md
  docs/04-operation-guides/operations/evnt-01-eventing-dashboards.md
  docs/04-operation-guides/operations/evnt-02-eventing-metrics.md
  docs/04-operation-guides/operations/obsv-01-access-logs.md
  docs/04-operation-guides/operations/obsv-02-adjust-loki.md
  docs/04-operation-guides/operations/obsv-03-enable-grafana-for-istio.md
  docs/04-operation-guides/operations/obsv-04-enable-mtls-for-custom-metrics.md
  docs/04-operation-guides/security/sec-06-access-expose-grafana.md
  docs/04-operation-guides/troubleshooting/observability/obsv-01-troubleshoot-prometheus-istio-server-crash-oom.md
  docs/04-operation-guides/troubleshooting/observability/obsv-02-troubleshoot-jaeger-shows-few-traces.md
  docs/04-operation-guides/troubleshooting/observability/obsv-03-troubleshoot-loki-logging.md
  docs/05-technical-reference/00-architecture/obsv-01-architecture-monitoring.md
  docs/05-technical-reference/00-architecture/obsv-02-architecture-logging.md
  docs/05-technical-reference/00-architecture/obsv-03-architecture-tracing.md
  docs/05-technical-reference/00-configuration-parameters/obsv-01-configpara-observability.md
  docs/05-technical-reference/00-custom-resources/telemetry-01-logpipeline.md
  docs/05-technical-reference/svls-08-function-specification.md
Labels: area/monitoring, size/XL, lgtm

#16761 Convert eventing to annotation-based Prometheus scraping
  docs/assets/2.11-2.12-cleanup-servicemonitors.sh
  resources/eventing/charts/controller/templates/service.yaml
  resources/eventing/charts/controller/templates/servicemonitor.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/charts/dashboards/templates/delivery.yaml
  resources/eventing/charts/nats/templates/serviceMonitor.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
  resources/eventing/charts/publisher-proxy/templates/_helpers.tpl
  resources/eventing/charts/publisher-proxy/templates/service.yaml
  resources/eventing/charts/publisher-proxy/templates/servicemonitor.yaml
  tests/fast-integration/eventing-test/nats-dashboard-queries.json
Labels: area/monitoring, size/L, lgtm

#16569 Updated health probes for NATS JetStream
  resources/eventing/charts/nats/templates/service.yaml
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
  resources/eventing/values.yaml
Labels: size/M, lgtm

#16805 Convert api gateway, istio, ory to annotation-based Prometheus scraping
  docs/assets/2.11-2.12-cleanup-servicemonitors.sh
  resources/api-gateway/templates/monitoring.yaml
  resources/istio-resources/README.md
  resources/istio-resources/templates/service-monitor.yaml
  resources/istio-resources/values.yaml
  resources/istio/profile-evaluation.yaml
  resources/istio/templates/istio-operator.yaml
  resources/istio/values.yaml
  resources/ory/charts/hydra/charts/hydra-maester/templates/service-metrics.yaml
  resources/ory/charts/oathkeeper/templates/service-metrics.yaml
  resources/ory/templates/monitoring-hydra.yaml
  resources/ory/templates/monitoring-oathkeeper.yaml
Labels: size/L, lgtm

#16801 add note about the renewal of a certificate
  docs/03-tutorials/00-api-exposure/apix-02-setup-custom-domain-for-workload.md
Labels: size/XS, lgtm

#16808 Revert function docs changes
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
  docs/05-technical-reference/svls-06-function-configuration-file.md
Labels: size/M, lgtm

#16810 Convert serverless to annotation-based Prometheus scraping
  docs/assets/2.11-2.12-cleanup-servicemonitors.sh
  resources/serverless/templates/service-monitor.yaml
  resources/serverless/values.yaml
Labels: size/M, lgtm

#16771 Change loglevel for unneccessary info messages to debug
  components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#16804 Troubleshooting guide explaining possible reasons why exposed service cannot be reached (5xx)
  docs/04-operation-guides/troubleshooting/api-exposure/apix-01-apigateway-connect-api-rule.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-11-500-server-error.md
Labels: size/L, lgtm

#16772 Update security context for the Eventing components
  components/eventing-controller/pkg/deployment/publisher_deployment.go
  resources/eventing/charts/nats/templates/statefulset.yaml
  resources/eventing/charts/nats/values.yaml
  resources/eventing/values.yaml
Labels: area/eventing, size/M, lgtm

#16813 Convert logging, tracing to annotation-based Prometheus scraping
  docs/assets/2.11-2.12-cleanup-servicemonitors.sh
  resources/logging/charts/loki/templates/kyma-additions/loki.rules.yaml
  resources/logging/charts/loki/templates/servicemonitor.yaml
  resources/logging/charts/loki/values.yaml
  resources/tracing/templates/kyma-additions/metrics-service.yaml
  resources/tracing/templates/kyma-additions/metrics-servicemonitor.yaml
  resources/tracing/values.yaml
Labels: area/monitoring, size/L, lgtm

#16815 change the link in the Tip section about Docker and k8s
  README.md
Labels: size/XS, lgtm

#16814 Revert "Temporarily re-add FluentBit ServiceMonitor"
  resources/telemetry/charts/operator/templates/fluent-bit/service-monitor.yaml
  resources/telemetry/charts/operator/values.yaml
Labels: size/M, lgtm

#16816 Fix Kyma 2.12.0 cleanup script
  docs/assets/2.11-2.12-cleanup-servicemonitors.sh
Labels: area/monitoring, size/XS, lgtm

#16817 remove mg from main
  docs/assets/2.10-2.11-cleanup-kiali.sh
  docs/assets/2.9-2.10-OS-copy-secrets-to-system-namespace.sh
  docs/assets/2.9-2.10-SKR-copy-secrets-to-system-namespace.sh
  docs/migration-guide-2.10-2.11.md
Labels: size/M, lgtm

#16819 bring back assets
  docs/assets/2.10-2.11-cleanup-kiali.sh
  docs/assets/2.9-2.10-OS-copy-secrets-to-system-namespace.sh
Labels: size/S, lgtm

#16522 add metric for dispatch duration in nats dispatcher
  components/eventing-controller/Makefile
  components/eventing-controller/hack/metrics.doc.tpl
  components/eventing-controller/pkg/backend/metrics/collector.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  docs/04-operation-guides/operations/evnt-02-eventing-metrics.md
  resources/eventing/charts/dashboards/templates/delivery.yaml
  resources/eventing/values.yaml
  tests/fast-integration/eventing-test/metric-test.js
  tests/fast-integration/eventing-test/nats-dashboard-queries.json
Labels: area/eventing, size/L, lgtm

#16590 Improve jetStream v2 reconciler integration tests
  components/eventing-controller/.golangci.yaml
  components/eventing-controller/api/v1alpha1/condition.go
  components/eventing-controller/api/v1alpha1/subscription_conversion.go
  components/eventing-controller/api/v1alpha1/subscription_conversion_unit_test.go
  components/eventing-controller/api/v1alpha2/condition.go
  components/eventing-controller/api/v1alpha2/constants.go
  components/eventing-controller/api/v1alpha2/groupversion_info.go
  components/eventing-controller/api/v1alpha2/status_types.go
  components/eventing-controller/api/v1alpha2/subscription_types.go
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/backend/reconciler_internal_unit_test.go
  components/eventing-controller/controllers/subscription/beb/reconciler.go
  components/eventing-controller/controllers/subscription/beb/reconciler_integration_test.go
  components/eventing-controller/controllers/subscription/testing/test_utils.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/reconciler.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/test/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/eventmesh/test/utils.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/matchers_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/reconciler_integration_test.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/test_utils.go
  components/eventing-controller/controllers/subscriptionv2/jetstream/test_utils_test.go
  components/eventing-controller/controllers/subscriptionv2/reconcilertesting/test_utils.go
  components/eventing-controller/pkg/backend/cleaner/eventmesh.go
  components/eventing-controller/pkg/backend/eventmesh/eventmesh.go
  components/eventing-controller/pkg/backend/eventmesh/eventmesh_integration_test.go
  components/eventing-controller/pkg/backend/eventmesh/utils_unit_test.go
  components/eventing-controller/pkg/backend/metrics/collector.go
  components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go
  components/eventing-controller/pkg/backend/nats/testing/test_helpers.go
  components/eventing-controller/pkg/backend/nats/utils.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils_test.go
  components/eventing-controller/pkg/backend/utils/utils.go
  components/eventing-controller/pkg/backend/utils/utils_test.go
  components/eventing-controller/pkg/backend/utils/v2/utils.go
  components/eventing-controller/pkg/object/apirule.go
  components/eventing-controller/pkg/object/equality_test.go
  components/eventing-controller/pkg/object/v2/equality_test.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb.go
  components/eventing-controller/pkg/subscriptionmanager/beb/beb_test.go
  components/eventing-controller/testing/bebmock.go
  components/eventing-controller/testing/matchers.go
  components/eventing-controller/testing/v2/matchers.go
  components/eventing-controller/testing/v2/test_helpers.go
  resources/eventing/values.yaml
Labels: size/XXL, lgtm

#16763 Missing Deprovisioning
  tests/fast-integration/skr-test/test-own-cluster.js
Labels: size/XS, lgtm

#16823 Reorder ory troubleshooting guide
  docs/01-overview/main-areas/api-exposure/apix-02-useful-links.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-01-apigateway-connect-api-rule.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-04-500-server-error.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-05-dns-mgt-connection-refused.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-06-dns-mgt-could-not-resolve-host.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-07-dns-mgt-resource-ignored.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-08-cert-mgt-issuer-not-created.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-09-gateway-not-reachable.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-10-upgrade-sidecar-proxy.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-11-api-rule-troubleshooting.md
Labels: size/S, lgtm

#16821 Update Telemetry Manager image
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#16838 Correct `make` calls in conn validator tests README
  tests/components/application-connector/docs/application-connectivity-validator-tests.md
Labels: size/XS, lgtm

#16846 Use gopher group in CODEOWNERS instead of enumerating its members
  CODEOWNERS
Labels: size/S, lgtm

#16854 cleanup codeowners
  CODEOWNERS
Labels: size/S, lgtm

#16851 Remove unused network policy
  resources/telemetry/charts/operator/templates/fluent-bit/networkpolicy.yaml
  resources/telemetry/charts/operator/values.yaml
Labels: size/S, lgtm

#16806 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#16548 bump CPU limit to 1k to support same load as epp
  resources/eventing/profile-production.yaml
Labels: area/eventing, size/XS, lgtm

#16857 Fix broken links in Telemetry docs
  docs/05-technical-reference/00-custom-resources/telemetry-01-logpipeline.md
  docs/05-technical-reference/00-custom-resources/telemetry-02-logparser.md
  docs/05-technical-reference/00-custom-resources/telemetry-03-tracepipeline.md
Labels: area/documentation, size/S, lgtm

#16858 update to alpine 1.17.2 for third-party-images
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/tracing/values.yaml
Labels: area/monitoring, area/logging, size/S, lgtm

#16856 Replace usernames with a team name in CODEOWNERS
  CODEOWNERS
Labels: size/S, lgtm

#16859 updated manager base image and otel-collector version
  resources/telemetry/values.yaml
Labels: area/tracing, area/logging, size/XS, lgtm

#16832 Refactor Eventing FI tests for event delivery and tracing check
  tests/fast-integration/eventing-test/assets/eventing-function.yaml
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: size/XL, lgtm

#16525 Change Compass Runtime Agent namespace to kyma-system
  components/compass-runtime-agent/cmd/main.go
  components/compass-runtime-agent/cmd/options.go
  components/compass-runtime-agent/cmd/options_test.go
  components/compass-runtime-agent/internal/certificates/migrator_test.go
  components/compass-runtime-agent/internal/config/provider_test.go
  components/compass-runtime-agent/scripts/patch-local-changes.sh
  docs/03-tutorials/00-application-connectivity/ra-04-configure-runtime-agent-with-compass.md
  docs/04-operation-guides/operations/ra-01-enable-kyma-with-runtime-agent.md
  docs/assets/2.11-2.12-SKR-delete-compass-system-namespace.sh
  resources/compass-runtime-agent/templates/cluster-role-binding.yaml
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/templates/role-binding.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/docs/assets/compass-runtime-agent-tests-architecture.svg
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/installation-config/mini-kyma-skr.yaml
  tests/components/application-connector/test/compass-runtime-agent/config.go
  tests/components/application-connector/test/compass-runtime-agent/suite_test.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/deployment.go
  tests/components/application-connector/test/compass-runtime-agent/testkit/init/init.go
  tests/fast-integration/compass/fixtures.js
Labels: area/application-connector, size/L, lgtm

#16867 Pod preset cleanup guide
  docs/assets/2.11-2.12-cleanup-podpreset.bash
  docs/migration-guide-2.11-2.12.md
Labels: size/S, lgtm

#16869 Fix regression in response formatting in nodejs16 runtime
  components/function-runtimes/nodejs16/server.js
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, lgtm

#16874 add AC migration guide
  docs/migration-guide-2.11-2.12.md
Labels: size/S, lgtm

#16870 Fix regression in response formatting in nodejs16 runtime
  components/function-runtimes/nodejs16/server.js
Labels: size/S, lgtm

#16873 updated alpine to 1.17.2
  resources/logging/values.yaml
  resources/monitoring/values.yaml
  resources/ory/values.yaml
  tests/fast-integration/telemetry-test/testdata/regex-filter-deployment.yaml
Labels: area/monitoring, size/XS, lgtm

#16849 Enable subscription v1alpha2
  components/event-publisher-proxy/pkg/options/options.go
  components/eventing-controller/Makefile
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/config/crd/basesv1alpha1/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/config/crd/basesv1alpha2/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/controllers/subscription/beb/reconciler_integration_test.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_integration_test.go
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/values.yaml
  tests/fast-integration/eventing-test/utils.js
Labels: size/XL, lgtm

#16883 Rebuild nodejs16
  components/function-runtimes/nodejs16/server.js
Labels: size/XS, lgtm

#16848 Update Istio HPA to autoscaling/v2
  resources/istio/profile-production.yaml
Labels: size/S, lgtm

#16886 Rebuild nodejs16 - 2.11
  components/function-runtimes/nodejs16/server.js
Labels: size/XS, lgtm

#16340 Update documentation for Subscription v1alpha2 CRD
  docs/01-overview/main-areas/eventing/evnt-99-useful-links.md
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/03-tutorials/00-eventing/evnt-02-subs-with-multiple-filters.md
  docs/03-tutorials/00-eventing/evnt-03-type-cleanup.md
  docs/03-tutorials/00-eventing/evnt-04-change-max-in-flight-in-sub.md
  docs/03-tutorials/00-eventing/evnt-05-send-legacy-events.md
  docs/04-operation-guides/troubleshooting/eventing/evnt-01-eventing-troubleshooting.md
  docs/04-operation-guides/troubleshooting/eventing/evnt-03-type-collision.md
  docs/04-operation-guides/troubleshooting/eventing/evnt-05-fix-pending-messages.md
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
  docs/05-technical-reference/evnt-01-event-names.md
Labels: size/L, lgtm

#16882 Revert pod preset cleanup guide (#16867)
  docs/assets/2.11-2.12-cleanup-podpreset.bash
  docs/migration-guide-2.11-2.12.md
Labels: size/S, lgtm

#16890 Fix nodejs16 returned value formatting regression
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/XS, lgtm

#16885 Pod preset cleanup guide for release-2.11
  docs/assets/2.10-2.11-cleanup-podpreset.bash
  docs/migration-guide-2.10-2.11.md
Labels: size/S, lgtm

#16785 Write Tests for Missing Important Eventing Cases
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/utils/index.js
Labels: size/L, lgtm

#16894 update serverless docker images
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-runtimes/nodejs14/Dockerfile
  components/function-runtimes/nodejs16/Dockerfile
  components/function-runtimes/python39/Dockerfile
  resources/serverless/values.yaml
Labels: size/M, lgtm

#16861 Refactored Eventing monitoring tests to use eventing-sink function
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/metric-test.js
Labels: size/L, lgtm

#16891 Bump k8s-tools image in Kyma 2.11
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#16896 Removed JetStream atLeastOnceCheck test in Eventing FI tests
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: area/eventing, size/L, lgtm

#16879 Remove init container and webhook from telemetry chart
  docs/assets/2.11-2.12-cleanup-init-container.sh
  docs/migration-guide-2.11-2.12.md
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/templates/role.yaml
  resources/telemetry/charts/operator/templates/validation_webhook.yaml
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/values.yaml
Labels: size/L, lgtm

#16902 bump serverless images in release 2.11
  resources/serverless/values.yaml
Labels: size/S, lgtm

#16905 Globalized subscription names in Eventing FI tests
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/metric-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: area/eventing, size/M, lgtm

#16906 Fix the link to the cleanup script
  docs/migration-guide-2.10-2.11.md
Labels: size/XS, lgtm

#16904 Remove webhook-cert-init component
  CODEOWNERS
  components/webhook-cert-init/.dockerignore
  components/webhook-cert-init/.gitignore
  components/webhook-cert-init/Dockerfile
  components/webhook-cert-init/Makefile
  components/webhook-cert-init/README.md
  components/webhook-cert-init/go.mod
  components/webhook-cert-init/go.sum
  components/webhook-cert-init/main.go
Labels: size/XL, lgtm, area/telemetry

#16892 Remove dependencies to compass-system Namespace
  components/function-controller/README.md
  components/function-controller/internal/controllers/kubernetes/shared.go
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm

#16901 Bumped NATS version to 2.9.14 - release-2.11
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#16900 Bumped NATS version to 2.9.14
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#16910 Move Otel collector RBAC creation to telemetry-operator
  resources/telemetry/charts/operator/templates/trace-collector-role.yaml
  resources/telemetry/values.yaml
Labels: size/S, lgtm

#16914 update node14 version
  components/function-runtimes/nodejs14/Dockerfile
Labels: size/XS, lgtm

#16915 bump node14 image
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#16916 Fix time comparisons for NATS in Eventing FI tests
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: area/eventing, size/S, lgtm

#16925 Move function profile overrides from the test-infra scripts
  resources/serverless/values.yaml
  tests/function-controller/testsuite/gitops/function.go
  tests/function-controller/testsuite/runtimes/nodejs.go
  tests/function-controller/testsuite/runtimes/python.go
Labels: area/serverless, size/M, lgtm

#16921 Added tests for exact type matching in Eventing FI tests
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: area/eventing, size/M, lgtm

#16933 Add a disclaimer to the istio telemetry API usage
  docs/01-overview/main-areas/telemetry/telemetry-03-traces.md
  docs/04-operation-guides/operations/obsv-03-enable-istio-access-logs.md
Labels: lgtm, area/telemetry

#16945 Fix Eventing tutorial
  docs/03-tutorials/00-eventing/evnt-02-subs-with-multiple-filters.md
Labels: area/documentation, area/eventing, size/XS, lgtm

#16930 Cherry-pick Eventing FI tests refactoring to release-2.11 branch
  tests/fast-integration/eventing-test/assets/eventing-function.yaml
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/metric-test.js
  tests/fast-integration/eventing-test/utils.js
  tests/fast-integration/test/fixtures/commerce-mock/index.js
Labels: size/XXL, lgtm

#16917 add note on Istio sidecar injection
  docs/01-overview/main-areas/application-connectivity/ac-01-application-connector.md
Labels: area/documentation, area/application-connector, size/XS, lgtm

#16944 Fix Eventing controller makefile recipe indentation
  components/eventing-controller/Makefile
Labels: area/eventing, size/S, lgtm

#16947 Updated Subscription CR doc to mention about deprecation of exact with JetStream
  docs/05-technical-reference/00-custom-resources/evnt-01-subscription.md
Labels: size/XS, lgtm

#16911 Restore validatingwebhook creation in telemetry chart
  resources/telemetry/charts/operator/templates/validation_webhook.yaml
  resources/telemetry/charts/operator/values.yaml
Labels: size/M, lgtm

#16943 update otel-collector to 0.72.0
  resources/telemetry/values.yaml
Labels: size/XS, lgtm, area/telemetry

#16865 Remove component directory-size-exporter
  CODEOWNERS
  components/directory-size-exporter/.dockerignore
  components/directory-size-exporter/.gitignore
  components/directory-size-exporter/Dockerfile
  components/directory-size-exporter/Makefile
  components/directory-size-exporter/README.md
  components/directory-size-exporter/go.mod
  components/directory-size-exporter/go.sum
  components/directory-size-exporter/internal/exporter/exporter.go
  components/directory-size-exporter/internal/exporter/exporter_test.go
  components/directory-size-exporter/main.go
Labels: size/XXL, lgtm

#16768 Add nodejs 18 runtime code
  components/function-runtimes/nodejs/lib/ce.js
  components/function-runtimes/nodejs/lib/helper.js
  components/function-runtimes/nodejs/lib/tracer.js
  components/function-runtimes/nodejs/nodejs16/Dockerfile
  components/function-runtimes/nodejs/nodejs16/package.json
  components/function-runtimes/nodejs/nodejs18/Dockerfile
  components/function-runtimes/nodejs/nodejs18/package.json
  components/function-runtimes/nodejs/server.js
Labels: size/XL, lgtm

#16951 Update image version for adding pod ip usage for trace collector
  resources/telemetry/values.yaml
Labels: size/XS, lgtm
