Repository kyma-project/kyma, pull requests merged in 2023-10, with the labels that each got.

#18253 Update VERSION to 2.19.0
  VERSION
Labels: size/XS, lgtm

#18217 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm, area/tests, kind/chore

#18264 Remove gophers from CODEOWNERS
  .github/workflows/post-master-binding-k3s.yml
  .github/workflows/pre-master-binding-k3s.yml
  CODEOWNERS
Labels: size/L, lgtm

#18257 Remove unnecesary FIT scenarios
  CODEOWNERS
  tests/fast-integration/test/1-commerce-mock.js
  tests/fast-integration/test/2-getting-started-guide.js
  tests/fast-integration/test/fixtures/getting-started-guide/index.js
  tests/fast-integration/test/fixtures/getting-started-guide/microservice.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/ns.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/redis-addon-sb-si.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/redis-sbu.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/xf-mocks.yaml
  tests/fast-integration/test/index.js
  tests/fast-integration/test/test.js
Labels: size/XL, lgtm

#18259 Added ENV flag to disable Application CR lister
  components/event-publisher-proxy/pkg/cloudevents/builder/generic.go
  components/event-publisher-proxy/pkg/cloudevents/builder/generic_test.go
  components/event-publisher-proxy/pkg/cloudevents/builder/types.go
  components/event-publisher-proxy/pkg/cloudevents/eventtype/clean.go
  components/event-publisher-proxy/pkg/cloudevents/eventtype/clean_test.go
  components/event-publisher-proxy/pkg/commander/eventmesh/eventmesh.go
  components/event-publisher-proxy/pkg/commander/nats/nats.go
  components/event-publisher-proxy/pkg/env/eventmesh_config.go
  components/event-publisher-proxy/pkg/env/nats_config.go
  components/event-publisher-proxy/pkg/legacy/legacy.go
  components/event-publisher-proxy/pkg/legacy/legacy_test.go
  resources/eventing/values.yaml
Labels: size/XL, lgtm

#18266 fix docsify-tabs regex
  docs/index.html
Labels: size/S, lgtm

#18261 Components clean up
  CODEOWNERS
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/05-technical-reference/00-configuration-parameters/smsh-02-istio-resources-chart.md
  resources/cluster-essentials/.helmignore
  resources/cluster-essentials/Chart.yaml
  resources/cluster-essentials/templates/_helpers.tpl
  resources/cluster-essentials/templates/ingress-tls-cert.yaml
  resources/cluster-essentials/templates/limit-range.yaml
  resources/cluster-essentials/templates/migrate-ac-certs-job.yaml
  resources/cluster-essentials/templates/priorityclass-high.yaml
  resources/cluster-essentials/templates/priorityclass.yaml
  resources/cluster-essentials/values.yaml
  resources/cluster-users/Chart.yaml
  resources/cluster-users/templates/_helpers.tpl
  resources/cluster-users/templates/clusterroles-addons.yaml
  resources/cluster-users/templates/clusterroles-coreos-com.yaml
  resources/cluster-users/templates/clusterroles-gardener.yaml
  resources/cluster-users/templates/clusterroles-istio-io.yaml
  resources/cluster-users/templates/clusterroles-k8s-io.yaml
  resources/cluster-users/templates/clusterroles-kyma-project-io.yaml
  resources/cluster-users/templates/clusterroles-ory-sh.yaml
  resources/cluster-users/templates/clusterroles-svcat.yaml
  resources/cluster-users/templates/rbac-roles.yaml
  resources/cluster-users/values.yaml
  resources/istio-resources/Chart.yaml
  resources/istio-resources/files/dashboards/README.md
  resources/istio-resources/files/dashboards/control-plane.json
  resources/istio-resources/files/dashboards/mesh.json
  resources/istio-resources/files/dashboards/performance.json
  resources/istio-resources/files/dashboards/service.json
  resources/istio-resources/files/dashboards/workload.json
  resources/istio-resources/templates/_helpers.tpl
  resources/istio-resources/templates/dashboards/istio-control-plane.yaml
  resources/istio-resources/templates/dashboards/istio-mesh.yaml
  resources/istio-resources/templates/dashboards/istio-performance.yaml
  resources/istio-resources/templates/dashboards/istio-service.yaml
  resources/istio-resources/templates/dashboards/istio-workload.yaml
  resources/istio-resources/templates/gateway.yaml
  resources/istio-resources/templates/mtls-global-v2.yaml
  resources/istio-resources/templates/virtualservice.yaml
  resources/istio-resources/values.yaml
  tests/components/application-connector/resources/installation-config/mini-kyma-os.yaml
  tests/components/application-connector/resources/installation-config/mini-kyma-skr.yaml
Labels: area/service-mesh, size/XXL, lgtm, area/charts

#18268 Remove milv config file
  milv.config.yaml
Labels: size/M, lgtm

#18271 Remove serverless from components list
  installation/resources/components.yaml
  installation/resources/crds/serverless/crd-serverless.yaml
Labels: area/serverless, lgtm, kind/cleanup

#18272 Remove Otters from codeowners from serverless components
  CODEOWNERS
Labels: area/serverless, size/S, lgtm, kind/cleanup

#18281 Remove the application lister and cleaner from the eventing-controller
  components/eventing-controller/Makefile
  components/eventing-controller/config/crd/external/apirules-gateway-kyma-project-io.yaml
  components/eventing-controller/config/crd/external/applications-applicationconnector-kyma-project-io.yaml
  components/eventing-controller/config/crd/kustomization.yaml
  components/eventing-controller/config/rbac/role.yaml
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/subscription/eventmesh/reconciler.go
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  components/eventing-controller/pkg/application/applicationtest/applicationtest.go
  components/eventing-controller/pkg/application/clean.go
  components/eventing-controller/pkg/application/clean_unit_test.go
  components/eventing-controller/pkg/application/fake/lister.go
  components/eventing-controller/pkg/application/lister.go
  components/eventing-controller/pkg/backend/eventtype/clean.go
  components/eventing-controller/pkg/backend/eventtype/clean_internal_unit_test.go
  components/eventing-controller/pkg/backend/eventtype/simple_clean.go
  resources/eventing/values.yaml
Labels: area/eventing, size/XL, lgtm

#18239 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
Labels: area/serverless, size/XS, lgtm, kind/chore

#18283 add the Serverless module prerequisite to the Get Started section
  docs/02-get-started/README.md
Labels: area/documentation, area/serverless, size/XS, lgtm

#18267 docs: Refer to new NATS module docs
  docs/README.md
  docs/_sidebar.md
  docs/index.html
Labels: size/XS, lgtm

#18284 Fix rendering of a Twitter link
  README.md
Labels: size/XS, lgtm

#18287 Mitigate dependency to non-existing serverless component in upgraed tests
  tests/fast-integration/Makefile
Labels: size/XS, lgtm

#18297 Wait for serverless installed condition before serverless dependant FIT test
  CODEOWNERS
  tests/fast-integration/Makefile
Labels: size/XS, lgtm

#18299 Remove serverless leftovers
  .github/package.json
  hack/table-gen/Makefile
  tests/fast-integration/.gitignore
Labels: area/serverless, size/XS, lgtm, kind/cleanup

#18291 Bump Go in app connectivity
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/Dockerfile
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/Dockerfile
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/M, lgtm

#18307 simplify readiness check for event-publisher-proxy
  components/event-publisher-proxy/pkg/sender/jetstream/health.go
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#18310 Update the blog redirect
  docs/_redirects
Labels: area/documentation, size/XS, lgtm

#18301 rename metric to eventing_epp_requests_duration_seconds and adjust buckets
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/metrics/collector.go
  components/event-publisher-proxy/pkg/metrics/collector_test.go
  docs/04-operation-guides/operations/evnt-02-eventing-metrics.md
  resources/eventing/values.yaml
Labels: size/L, lgtm

#18225 Fix app-con test timeout
  tests/components/application-connector/scripts/check-pod-logs.sh
Labels: size/S, lgtm

#18313 eventing cherry-pick for 2.19.1
  .github/workflows/lint-markdown-links-pr.yml
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/metrics/collector.go
  components/event-publisher-proxy/pkg/metrics/collector_test.go
  components/event-publisher-proxy/pkg/sender/jetstream/health.go
  docs/04-operation-guides/operations/evnt-02-eventing-metrics.md
  resources/eventing/values.yaml
Labels: size/L, lgtm

#18319 Moved module description to Kyma modules
  docs/02-get-started/08-install-uninstall-upgrade-kyma-module.md
  docs/02-get-started/_sidebar.md
  docs/06-modules/README.md
  docs/README.md
  docs/_sidebar.md
Labels: area/documentation, size/M, lgtm

#18320 bump the event-publisher-proxy image
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#18336 Footer update
  docs/_footer.md
Labels: area/documentation, size/XS, lgtm

#18322 get `branch-to-merge-against` and use it as `base-branch`
  .github/workflows/lint-markdown-links-pr.yml
Labels: size/XS, lgtm

#18337 Bump dependencies
  components/eventing-controller/Dockerfile
  components/eventing-controller/cmd/eventing-controller/main.go
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/backend/reconciler_internal_unit_test.go
  components/eventing-controller/controllers/subscription/eventmesh/reconciler.go
  components/eventing-controller/controllers/subscription/eventmesh/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/subscription/eventmesh/test/assertions.go
  components/eventing-controller/controllers/subscription/eventmesh/test/reconciler_integration_test.go
  components/eventing-controller/controllers/subscription/eventmesh/test/utils.go
  components/eventing-controller/controllers/subscription/eventmesh/testwebhookauth/assertions.go
  components/eventing-controller/controllers/subscription/eventmesh/testwebhookauth/reconciler_integration_test.go
  components/eventing-controller/controllers/subscription/eventmesh/testwebhookauth/utils.go
  components/eventing-controller/controllers/subscription/eventmesh/testwithory/assertions.go
  components/eventing-controller/controllers/subscription/eventmesh/testwithory/reconciler_integration_test.go
  components/eventing-controller/controllers/subscription/eventmesh/testwithory/utils.go
  components/eventing-controller/controllers/subscription/eventmesh/utils.go
  components/eventing-controller/controllers/subscription/eventmesh/utils_test.go
  components/eventing-controller/controllers/subscription/jetstream/test_utils_test.go
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  components/eventing-controller/pkg/backend/eventmesh/eventmesh.go
  components/eventing-controller/pkg/backend/eventmesh/mocks/Backend.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils.go
  components/eventing-controller/pkg/backend/utils/eventmesh_utils_test.go
  components/eventing-controller/pkg/backend/utils/utils.go
  components/eventing-controller/pkg/object/apirule.go
  components/eventing-controller/pkg/object/equality.go
  components/eventing-controller/pkg/object/equality_test.go
  components/eventing-controller/pkg/subscriptionmanager/eventmesh/eventmesh.go
  components/eventing-controller/testing/matchers.go
  components/eventing-controller/testing/test_helpers.go
  resources/eventing/values.yaml
Labels: size/L, lgtm

#18338 Add AC module to the website
  docs/_sidebar.md
  docs/index.html
Labels: size/XS, lgtm

#18343 Remove the SKR abbreviation from the README file
  docs/README.md
Labels: area/documentation, size/XS, lgtm

#18346 Fix enable Keda kubectl command
  docs/02-get-started/08-install-uninstall-upgrade-kyma-module.md
Labels: size/XS, lgtm

#18345 removed api-gateway component from components list
  installation/resources/components.yaml
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
  installation/resources/crds/ory/rules.crd.yaml
Labels: area/api-gateway, size/L, lgtm, kind/cleanup

#18349 Update istio operator to version 1.1.1
  resources/istio/Chart.yaml
  resources/istio/templates/istio-manager-config.yaml
  resources/istio/values.yaml
Labels: area/service-mesh, size/S, lgtm

#18350 Update istio operator version to 1.1.1
  resources/istio/Chart.yaml
  resources/istio/templates/istio-manager-config.yaml
  resources/istio/values.yaml
Labels: area/service-mesh, size/S, lgtm

#18344 Dependency bump epp
  components/event-publisher-proxy/Dockerfile
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/event-publisher-proxy/pkg/commander/eventmesh/eventmesh.go
  components/event-publisher-proxy/pkg/commander/nats/nats.go
  components/event-publisher-proxy/pkg/handler/handler_v1alpha1_test.go
  components/event-publisher-proxy/pkg/legacy/api/types.go
  components/event-publisher-proxy/pkg/legacy/error_responses.go
  components/event-publisher-proxy/pkg/signals/signals.go
  components/event-publisher-proxy/pkg/tracing/helpers_test.go
Labels: size/XL, lgtm

#18351 fixes CVE-2023-39325 in application-connector components
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/M, lgtm

#18355 Resolve vulnerability CVE-2023-39325 in Application Connector
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/Dockerfile
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/Dockerfile
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
Labels: area/application-connector, size/L, lgtm

#18356 Bump AppConn images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/XS, lgtm

#18357 bump-dependencies-ec-20231025
  components/eventing-controller/Dockerfile
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
Labels: size/S, lgtm

#18364 Update VERSION to 2.19.2
  VERSION
Labels: size/XS, lgtm

#18365 Revert "removed api-gateway component from components list (#18345)"
  installation/resources/components.yaml
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
  installation/resources/crds/ory/rules.crd.yaml
Labels: size/L, lgtm

#18361 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
Labels: area/security, size/XS, lgtm, kind/chore

#18358 Fix broken link.
  components/eventing-controller/config/crd/external/README.md
Labels: size/XS, lgtm

#18366 Change Application Connector images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/S, lgtm

#18371 Bump gomega and logr dependencies
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
Labels: size/S, lgtm

#18363 Remove pr images for eventing
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#18373 Move application CRD from application-connector to compass-runtime-agent
  installation/resources/crds/compass-runtime-agent/applications.applicationconnector.crd.yaml
Labels: area/application-connector, size/XS, lgtm, area/crds

#18374 Update VERSION to 2.19.3
  VERSION
Labels: size/XS, lgtm

#18375 update index.html
  docs/index.html
Labels: size/XS, lgtm
