Repository kyma-project/kyma, pull requests merged in 2023-05, with the labels that each got.

#17434 bump application connector and CRA images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/S, lgtm

#17414 Adjust documentation after removing jaeger
  docs/01-overview/main-areas/observability/README.md
  docs/01-overview/main-areas/observability/obsv-03-tracing-in-kyma.md
  docs/01-overview/main-areas/observability/obsv-10-useful-links.md
  docs/01-overview/main-areas/service-mesh/smsh-02-default-istio-setup-in-kyma.md
  docs/01-overview/main-areas/service-mesh/smsh-03-istio-sidecars-in-kyma.md
  docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md
  docs/03-tutorials/00-serverless/svls-12-customize-function-traces.md
  docs/04-operation-guides/operations/02-install-kyma.md
  docs/04-operation-guides/security/sec-06-access-expose-grafana.md
  docs/04-operation-guides/security/sec-06-access-expose-kiali-grafana.md
  docs/04-operation-guides/troubleshooting/observability/obsv-02-troubleshoot-jaeger-shows-few-traces.md
  docs/04-operation-guides/troubleshooting/observability/obsv-02-troubleshoot-trace-backend-shows-few-traces.md
  docs/05-technical-reference/00-architecture/obsv-03-architecture-tracing.md
  docs/05-technical-reference/00-configuration-parameters/svls-02-environment-variables.md
  docs/05-technical-reference/svls-08-function-specification.md
Labels: area/documentation, size/L, lgtm, area/telemetry

#17395 Cleanup v1alpha1 Subscription codebase in EPP
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/event-publisher-proxy/pkg/commander/beb/beb.go
  components/event-publisher-proxy/pkg/commander/nats/nats.go
  components/event-publisher-proxy/pkg/handler/handler.go
  components/event-publisher-proxy/pkg/handler/handler_test.go
  components/event-publisher-proxy/pkg/handler/handler_v1alpha1_test.go
  components/event-publisher-proxy/pkg/handler/handler_v1alpha2_test.go
  components/event-publisher-proxy/pkg/options/options.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream.go
  components/event-publisher-proxy/pkg/sender/jetstream/jetstream_test.go
  components/event-publisher-proxy/pkg/subscribed/helpers.go
  components/event-publisher-proxy/pkg/subscribed/processor.go
  components/eventing-controller/pkg/deployment/publisher_deployment.go
  resources/eventing/charts/controller/templates/busola-extension.yaml
  resources/eventing/charts/controller/templates/deployment.yaml
  resources/eventing/charts/controller/templates/service.yaml
  resources/eventing/charts/controller/templates/webhook-cert-handler.yaml
  resources/eventing/charts/controller/templates/webhook.yaml
  resources/eventing/charts/controller/values.yaml
  resources/eventing/values.yaml
Labels: size/XXL, lgtm

#17425 Use forked webhook certificates image for eventing
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#17439 Update Prometheus operator to v0.64.1 and prometheus to v2.43.0 + monitoring crds
  installation/resources/crds/monitoring/alertmanagerconfigs.monitoring.coreos.crd.yaml
  installation/resources/crds/monitoring/alertmanagers.monitoring.coreos.crd.yaml
  installation/resources/crds/monitoring/podmonitors.monitoring.coreos.crd.yaml
  installation/resources/crds/monitoring/probes.monitoring.coreos.crd.yaml
  installation/resources/crds/monitoring/prometheuses.monitoring.crd.yaml
  installation/resources/crds/monitoring/prometheusrules.monitoring.crd.yaml
  installation/resources/crds/monitoring/servicemonitors.monitoring.coreos.crd.yaml
  installation/resources/crds/monitoring/thanosrulers.monitoring.coreos.crd.yaml
  resources/monitoring/values.yaml
Labels: area/monitoring, size/XXL, lgtm

#17441 remove duplicate info on tracing architecture
  docs/01-overview/main-areas/observability/obsv-10-useful-links.md
  docs/01-overview/main-areas/service-mesh/smsh-03-istio-sidecars-in-kyma.md
  docs/05-technical-reference/00-architecture/assets/obsv-tracing-architecture.svg
  docs/05-technical-reference/00-architecture/obsv-03-architecture-tracing.md
Labels: size/L, lgtm

#17436 Removed Kubeconfig Assertion Logging
  tests/fast-integration/kyma-environment-broker/helpers.js
Labels: size/XS, lgtm

#17445 Fixed make copy-crds target in eventing-controller
  components/eventing-controller/Makefile
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
Labels: area/eventing, size/XS, lgtm

#17440 Bump directory-size-exporter
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#17447 Add services get/list/watch to api-gateway RBAC
  resources/api-gateway/templates/rbac.yaml
Labels: area/api-gateway, size/XS, lgtm

#17446 Implement git2go ssh cert validation callback
  components/function-controller/internal/git/auth.go
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17449 Use serverless image version from prod dir
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17448 fix fast integration test env var check
  tests/fast-integration/eventing-test/eventing-test-prep.js
  tests/fast-integration/eventing-test/eventing-test.js
  tests/fast-integration/eventing-test/utils.js
Labels: area/eventing, size/XS, lgtm

#17438 Update monitoring images
  resources/monitoring/values.yaml
Labels: area/monitoring, size/S, lgtm

#17451 bump prometheus to v2.43.1
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#17452 Upgrade api-gateway to 1.6.0
  resources/api-gateway/values.yaml
Labels: area/api-gateway, size/XS, lgtm

#17428 Add descriptions to CRA's CRD's fields
  docs/05-technical-reference/00-custom-resources/ra-01-compassconnection.md
  hack/table-gen/Makefile
  installation/resources/crds/compass-runtime-agent/compass-connection.crd.yaml
Labels: size/M, lgtm

#17456 Bump logging and monitoring images
  resources/logging/values.yaml
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#17453 Image bumps for Eventing - rel 2.14
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#17455 Set external svc urls as optional
  components/function-controller/Makefile
  components/function-controller/internal/controllers/serverless/config.go
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17460 Add api-gateway integration test
  tests/components/api-gateway/features/api-gateway/oauth2_secured_endpoint.feature
  tests/components/api-gateway/manifests/oauth2-secured-endpoint.yaml
  tests/components/api-gateway/oauth2_secured_endpoint_test.go
  tests/components/api-gateway/prepare_local.sh
  tests/components/api-gateway/test_helpers.go
Labels: area/api-gateway, size/L, lgtm

#17462 use post main images
  resources/serverless/values.yaml
Labels: size/S, lgtm

#17421 CRD documentation list all versions
  docs/05-technical-reference/00-custom-resources/ra-01-compassconnection.md
  docs/05-technical-reference/00-custom-resources/telemetry-01-logpipeline.md
  docs/05-technical-reference/00-custom-resources/telemetry-02-logparser.md
  docs/05-technical-reference/00-custom-resources/telemetry-03-tracepipeline.md
  hack/table-gen/README.md
  hack/table-gen/table-gen.go
  hack/table-gen/table-gen_test.go
Labels: size/XL, lgtm

#17393 Improve deployment code
  components/function-controller/internal/controllers/serverless/deployment.go
  components/function-controller/internal/controllers/serverless/deployment_test.go
  components/function-controller/internal/controllers/serverless/system_state.go
  resources/serverless/values.yaml
Labels: size/M, lgtm

#17466 Bump btp-manager version
  resources/btp-manager/values.yaml
Labels: size/XS, lgtm

#17400 Bump telemetry-operator image to support multiple pipelines
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/values.yaml
  tests/fast-integration/telemetry-test/suite.js
Labels: size/S, lgtm, area/telemetry

#17472 Add alertmanagers/status for prometheus-operator clusterrole
  resources/monitoring/templates/prometheus-operator/clusterrole.yaml
Labels: kind/bug, area/monitoring, size/XS, lgtm

#17475 Cherry-pick the fix for adding alertmanagers/status to prometheus-operator clusterrole
  resources/monitoring/templates/prometheus-operator/clusterrole.yaml
Labels: kind/bug, area/monitoring, size/XS, lgtm

#17469 update to otel-collector 0.77.0
  resources/telemetry/values.yaml
Labels: area/tracing, size/XS, lgtm, area/telemetry

#17467 CRD table generation newline for longer parameter name
  docs/05-technical-reference/00-custom-resources/ra-01-compassconnection.md
  docs/05-technical-reference/00-custom-resources/telemetry-01-logpipeline.md
  docs/05-technical-reference/00-custom-resources/telemetry-02-logparser.md
  docs/05-technical-reference/00-custom-resources/telemetry-03-tracepipeline.md
  hack/table-gen/table-gen.go
Labels: size/L, lgtm

#17473 add deprecation warning to generated documentation
  hack/table-gen/Makefile
  hack/table-gen/go.mod
  hack/table-gen/main.go
  hack/table-gen/table-gen_test.go
Labels: area/documentation, size/S, lgtm

#17471 add deprecation warning to subscription crd
  components/eventing-controller/Makefile
  components/eventing-controller/api/v1alpha1/subscription_types.go
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_eventingbackends.yaml
  components/eventing-controller/config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  components/eventing-controller/config/rbac/role.yaml
  components/eventing-controller/config/webhook/manifests.yaml
  installation/resources/crds/eventing/eventingbackends.eventing.kyma-project.io.crd.yaml
  installation/resources/crds/eventing/subscriptions.eventing.kyma-project.io.crd.yaml
Labels: area/eventing, lgtm

#17476 Update the CRD descriptions of the CompassConnection
  docs/05-technical-reference/00-custom-resources/ra-01-compassconnection.md
  installation/resources/crds/compass-runtime-agent/compass-connection.crd.yaml
Labels: size/M, lgtm

#17482 Bump Kyma 2.14.0
  VERSION
Labels: area/ci, size/XS, lgtm, kind/chore

#17485 update to fluent-bit 2.1.2
  resources/telemetry/values.yaml
Labels: area/logging, size/XS, lgtm, area/telemetry

#17484 Use kill instead of pkill
  tests/function-controller/run-local.sh
Labels: size/XS, lgtm

#17486 Add Telemetry Helm Chart migration guide
  docs/assets/2.14-2.15-cleanup-telemetry.sh
  docs/migration-guide-2.14-2.15.md
Labels: area/documentation, size/S, lgtm, area/telemetry

#17493 add sleep to help istio propagate some changes to the proxies in fastintegration-test
  tests/fast-integration/utils/index.js
Labels: size/XS, lgtm

#17494 increased cpu limit for grafana sidecars
  resources/monitoring/charts/grafana/values.yaml
Labels: area/monitoring, size/XS, lgtm, area/telemetry

#17495 increase fast-integration test timeouts
  tests/fast-integration/utils/index.js
Labels: size/XS, lgtm

#17497 remove Spec/Status sections from documentation if empty
  hack/table-gen/main.go
Labels: size/XS, lgtm

#17502 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm, kind/chore

#17504 Fix ssh cert callback
  components/function-controller/internal/git/auth.go
  resources/serverless/values.yaml
Labels: kind/bug, area/serverless, size/XS, lgtm

#17508 Fix ssh cert callback
  components/function-controller/internal/git/auth.go
Labels: size/XS, lgtm

#17510 Fix ssh cert callback - 2.14 image bump
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#17514 Bump Kyma to 2.14.1
  VERSION
Labels: size/XS, lgtm

#17487 Update Telemetry-related Busola extensions
  resources/telemetry/charts/operator/templates/logparser_busola_extension_cm.yaml
  resources/telemetry/charts/operator/templates/logpipeline_busola_extension_cm.yaml
  resources/telemetry/charts/operator/templates/tracepipeline_busola_extension_cm.yaml
Labels: kind/feature, size/S, lgtm, area/telemetry

#17528 bump application connector dependencies
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/M, lgtm

#17512 Scan keda images from external dir
  resources/keda-manager/values.yaml
Labels: area/serverless, lgtm, kind/chore

#17483 Auto-generate APIRule and Istio CRD docs
  docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
  docs/05-technical-reference/00-custom-resources/oper-01-istio.md
  hack/table-gen/Makefile
  hack/table-gen/README.md
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
  installation/resources/crds/istio/istios.operator.crd.yaml
Labels: size/L, lgtm

#17530 Fix failing telemetry debugability tests
  tests/fast-integration/telemetry-test/suite.js
Labels: kind/failing-test, size/XS, lgtm, area/tests

#17531 Fix path for the synced keda images
  resources/keda-manager/values.yaml
Labels: kind/bug, area/serverless, lgtm

#17529 fix: Logparser and log pipeline extension
  resources/telemetry/charts/operator/templates/logparser_busola_extension_cm.yaml
  resources/telemetry/charts/operator/templates/logpipeline_busola_extension_cm.yaml
  resources/telemetry/charts/operator/templates/tracepipeline_busola_extension_cm.yaml
Labels: size/XXL, lgtm

#17479 add checking changes of runtime annotations
  components/function-controller/internal/controllers/serverless/deployment_test.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/controllers/serverless/utils.go
  resources/serverless/values.yaml
Labels: size/M, lgtm

#17550 Remove logpipeline-editor-role and logpipeline-viewer-role
  docs/assets/2.14-2.15-cleanup-telemetry.sh
  resources/telemetry/charts/operator/templates/logpipeline_editor_role.yaml
  resources/telemetry/charts/operator/templates/logpipeline_viewer_role.yaml
Labels: size/M, lgtm, kind/cleanup, area/telemetry

#17470 Serverless internal docker registry node port - docs
  docs/05-technical-reference/00-architecture/assets/svls-internal-registry.svg
  docs/05-technical-reference/00-architecture/svls-02-internal-registry.md
Labels: size/S, lgtm

#17554 Backport endless loop fix
  components/function-controller/internal/controllers/serverless/configmap.go
  components/function-controller/internal/controllers/serverless/deployment.go
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/controllers/serverless/job.go
  components/function-controller/internal/controllers/serverless/scaling.go
  components/function-controller/internal/controllers/serverless/service.go
  components/function-controller/internal/controllers/serverless/system_state.go
Labels: size/M, lgtm

#17557 Bump Kyma to 2.14.2
  VERSION
Labels: area/ci, size/XS, lgtm, kind/chore

#17545 Adjust API Exposure tutorials to the removal of serverless functions in version v1alpha1
  docs/03-tutorials/00-api-exposure/apix-04-expose-workload/apix-04-03-expose-workloads-multiple-namespaces.md
  docs/03-tutorials/00-api-exposure/assets/function.yaml
Labels: size/M, lgtm

#17544 Bumps dependencies in application-connector components
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/M, lgtm

#17515 Bump k8s-tools image in Kyma 2.14
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm, kind/chore

#17566 Function UI should list subscriptions via new apiversion
  resources/serverless/templates/busola-serverless-extension.yaml
Labels: kind/bug, area/busola, area/serverless, lgtm

#17570 Remove unnecessary function.yaml file and correct the link
  docs/03-tutorials/00-api-exposure/apix-01-create-workload.md
  docs/03-tutorials/assets/function.yaml
Labels: size/S, lgtm

#17546 use new telemetry priority class for fluent-bit
  resources/telemetry/charts/operator/templates/deployment.yaml
  resources/telemetry/charts/operator/templates/priority-class-high.yaml
  resources/telemetry/charts/operator/templates/priority-class.yaml
  resources/telemetry/charts/operator/values.yaml
  resources/telemetry/values.yaml
Labels: size/S, lgtm, area/telemetry

#17565 Exit on certificate secret update
  components/function-controller/cmd/webhook/main.go
  components/function-controller/internal/webhook/resources/certificates.go
  components/function-controller/internal/webhook/resources/certificates_test.go
  components/function-controller/internal/webhook/resources/resources.go
  resources/serverless/values.yaml
Labels: size/L, lgtm

#17575 Remove Fluentbit peerAuthentication
  resources/telemetry/charts/operator/templates/fluent-bit/peerauthentication.yaml
  resources/telemetry/values.yaml
Labels: size/S, lgtm, kind/cleanup, area/telemetry

#17551 Fix loki chunk cleaner cause high CPU usage
  resources/logging/charts/loki/values.yaml
Labels: area/logging, size/XS, lgtm

#17576 Update telemetry-operator to introduce re-usable webhook CA bundle
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#17578 bump postgres image
  resources/ory/values.yaml
Labels: area/api-gateway, size/XS, lgtm

#17574 Update telemetry-operator to cleanup Fluent Bit volume mounts
  resources/telemetry/values.yaml
Labels: size/XS, lgtm

#17582 Release 2.14 - bumps golang from 1.20.3 to 1.20.4 in application connectivity components
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
Labels: area/application-connector, size/XS, lgtm, kind/chore

#17583 Restart serverless webhook upon cert rotation
  components/function-controller/cmd/webhook/main.go
  components/function-controller/internal/webhook/resources/certificates.go
  components/function-controller/internal/webhook/resources/certificates_test.go
  components/function-controller/internal/webhook/resources/resources.go
Labels: kind/bug, area/serverless, size/L, lgtm

#17586 Istio gateway resource modification
  resources/istio-resources/templates/gateway.yaml
  resources/istio-resources/values.yaml
Labels: size/S, lgtm

#17585 bumps application connector images for 2.14
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/XS, lgtm, kind/chore

#17587 Update Alertmanager image to add missing CA bundles
  resources/monitoring/values.yaml
Labels: size/XS, lgtm

#17588 Fix code block formatting
  docs/03-tutorials/00-api-exposure/apix-03-set-up-tls-gateway.md
Labels: size/L, lgtm

#17594 remove mg leftovers
  docs/assets/2.13-2.14-cleanup-jaeger.sh
  docs/migration-guide-2.13-2.14.md
Labels: size/M, lgtm

#17511 Update serverless docs
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  docs/05-technical-reference/00-custom-resources/svls-01-function.md
  hack/table-gen/Makefile
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/templates/crds.yaml
Labels: size/XL, lgtm

#17488 Remove annotation from webhook
  resources/serverless/charts/webhook/values.yaml
Labels: area/serverless, size/XS, lgtm

#17595 Increase loki chunk cleaner target size percentage
  resources/logging/charts/loki/values.yaml
Labels: area/logging, size/XS, lgtm
