Repository kyma-project/kyma, pull requests merged in 2023-09, with the labels that each got.

#18085 Remove deprecated cipher suites from Kyma gateway
  resources/istio-resources/templates/gateway.yaml
  resources/istio-resources/values.yaml
  tests/components/istio/.gitignore
  tests/components/istio/Makefile
  tests/components/istio/README.md
  tests/components/istio/features/istio_evaluation.feature
  tests/components/istio/features/istio_production.feature
  tests/components/istio/features/istio_reconcilation.feature
  tests/components/istio/features/sidecar_injection.feature
  tests/components/istio/go.mod
  tests/components/istio/go.sum
  tests/components/istio/helpers/command_runner.go
  tests/components/istio/istio_installed_test.go
  tests/components/istio/istio_reconcilation_test.go
  tests/components/istio/istio_sidecar_test.go
  tests/components/istio/main_test.go
  tests/components/istio/suites.go
  tests/components/istio/test/httpbin.yaml
  tests/components/istio/test_helpers.go
Labels: area/service-mesh, size/XXL, lgtm, kind/chore

#18070 Webhook config as file
  components/function-controller/cmd/manager/main.go
  components/function-controller/cmd/webhook/main.go
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  components/function-controller/hack/webhook_config.yaml
  components/function-controller/internal/config/file.go
  components/function-controller/internal/config/log.go
  components/function-controller/internal/controllers/serverless/service_test.go
  components/function-controller/internal/resource/automock/client.go
  components/function-controller/internal/resource/automock/k8s_client.go
  components/function-controller/internal/resource/resource.go
  components/function-controller/internal/webhook/config.go
  components/function-controller/internal/webhook/validating_webhook_test.go
  components/function-controller/internal/webhook/webhook_config.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  resources/serverless/charts/webhook/templates/configmap.yaml
  resources/serverless/charts/webhook/templates/deployment.yaml
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/templates/configmap.yaml
  resources/serverless/values.yaml
Labels: size/XL, lgtm

#18068 Update kyma Istio Operator docs
  README.md
  docs/01-overview/_sidebar.md
  docs/01-overview/application-connectivity/README.md
  docs/01-overview/application-connectivity/ac-01-application-connector.md
  docs/01-overview/service-mesh/README.md
  docs/01-overview/service-mesh/metadata.yaml
  docs/01-overview/service-mesh/smsh-01-details.md
  docs/01-overview/service-mesh/smsh-02-default-istio-setup-in-kyma.md
  docs/01-overview/service-mesh/smsh-03-istio-sidecars-in-kyma.md
  docs/01-overview/service-mesh/smsh-04-istio-limitations.md
  docs/01-overview/service-mesh/smsh-99-useful-links.md
  docs/02-get-started/README.md
  docs/03-tutorials/00-api-exposure/apix-04-expose-workload/apix-04-03-expose-workloads-multiple-namespaces.md
  docs/03-tutorials/00-application-connectivity/ac-01-create-application.md
  docs/03-tutorials/00-application-connectivity/ac-03-register-manage-services.md
  docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
  docs/03-tutorials/00-eventing/evnt-02-subs-with-multiple-filters.md
  docs/03-tutorials/00-eventing/evnt-03-type-cleanup.md
  docs/03-tutorials/00-eventing/evnt-04-change-max-in-flight-in-sub.md
  docs/03-tutorials/00-eventing/evnt-05-send-legacy-events.md
  docs/04-operation-guides/operations/README.md
  docs/04-operation-guides/operations/_sidebar.md
  docs/04-operation-guides/operations/smsh-01-istio-enable-sidecar-injection.md
  docs/04-operation-guides/security/_sidebar.md
  docs/04-operation-guides/security/sec-01-authentication-in-kyma.md
  docs/04-operation-guides/security/sec-04-ingress-egress-traffic.md
  docs/04-operation-guides/troubleshooting/README.md
  docs/04-operation-guides/troubleshooting/_sidebar.md
  docs/04-operation-guides/troubleshooting/service-mesh/README.md
  docs/04-operation-guides/troubleshooting/service-mesh/_sidebar.md
  docs/04-operation-guides/troubleshooting/service-mesh/metadata.yaml
  docs/04-operation-guides/troubleshooting/service-mesh/smsh-01-503-no-access.md
  docs/04-operation-guides/troubleshooting/service-mesh/smsh-02-connection-refused.md
  docs/04-operation-guides/troubleshooting/service-mesh/smsh-03-istio-no-sidecar.md
  docs/04-operation-guides/troubleshooting/service-mesh/smsh-04-istio-sidecar-version.md
  docs/05-technical-reference/00-architecture/obsv-01-architecture-monitoring.md
  docs/05-technical-reference/00-configuration-parameters/_sidebar.md
  docs/05-technical-reference/00-configuration-parameters/smsh-01-istio-chart.md
  docs/05-technical-reference/00-custom-resources/_sidebar.md
  docs/05-technical-reference/00-custom-resources/oper-01-istio.md
  docs/index.html
  hack/table-gen/Makefile
Labels: size/XL, lgtm

#18099 Create redirects for Telemetry and Serverless
  docs/05-technical-reference/00-custom-resources/README.md
  docs/_redirects
Labels: area/documentation, size/M, lgtm

#18107 Improve namespace api
  tests/function-controller/internal/resources/namespace/namespace.go
  tests/function-controller/internal/resources/namespace/step.go
  tests/function-controller/internal/testsuite/api_gateway.go
  tests/function-controller/internal/testsuite/cloud_events.go
  tests/function-controller/internal/testsuite/gitauth.go
  tests/function-controller/internal/testsuite/gitops.go
  tests/function-controller/internal/testsuite/light_runtimes.go
  tests/function-controller/internal/testsuite/tracing.go
Labels: size/M, lgtm

#18111 fix broken links
  docs/01-overview/observability/README.md
  docs/01-overview/observability/obsv-04-telemetry-in-kyma.md
  docs/04-operation-guides/security/README.md
  docs/05-technical-reference/00-custom-resources/README.md
Labels: size/XS, lgtm

#18115 Use different path for configuration files
  components/function-controller/cmd/manager/main.go
  components/function-controller/internal/webhook/config.go
  resources/serverless/values.yaml
Labels: size/S, lgtm

#18116 Update links to module documentation
  docs/README.md
Labels: area/documentation, size/XS, lgtm

#18117 Add redirects for Istio module docu
  docs/_redirects
Labels: area/documentation, area/quality, size/XS, lgtm

#18122 remove migration guide
  docs/assets/2.16-2.17-cleanup-loki.sh
  docs/migration-guide-2.16-2.17.md
Labels: size/S, lgtm

#18125 remove migration guide from sidebar
  docs/_sidebar.md
Labels: size/XS, lgtm

#18016 Improve logging
  components/central-application-gateway/README.md
  components/central-application-gateway/cmd/applicationgateway/applicationproxy.go
  components/central-application-gateway/cmd/applicationgateway/options.go
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/central-application-gateway/internal/csrf/client/csrfclient.go
  components/central-application-gateway/internal/csrf/strategy/csrf.go
  components/central-application-gateway/internal/externalapi/externalapi.go
  components/central-application-gateway/internal/metadata/applications/repository.go
  components/central-application-gateway/internal/metadata/applications/repository_test.go
  components/central-application-gateway/internal/metadata/secrets/repository.go
  components/central-application-gateway/internal/metadata/servicedefservice.go
  components/central-application-gateway/internal/metadata/servicedefservice_test.go
  components/central-application-gateway/internal/proxy/reverseproxy.go
  components/central-application-gateway/pkg/authorization/factory_test.go
  components/central-application-gateway/pkg/authorization/oauth/oauthclient_test.go
  components/central-application-gateway/pkg/authorization/oauthcertstrategy.go
  components/central-application-gateway/pkg/authorization/oauthcertstrategy_test.go
  components/central-application-gateway/pkg/authorization/oauthstrategy.go
  components/central-application-gateway/pkg/httptools/headers.go
  components/central-application-gateway/pkg/httptools/logging.go
  resources/application-connector/charts/central-application-gateway/templates/deployment.yaml
  resources/application-connector/charts/central-application-gateway/values.yaml
  resources/application-connector/values.yaml
  tests/components/application-connector/Makefile.test-application-gateway
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/code-rewriting.yaml
  tests/components/application-connector/resources/charts/gateway-test/charts/test/templates/applications/proxy-errors.yml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
  tests/components/application-connector/test/application-gateway/runner_test.go
Labels: size/L, lgtm

#18126 Add nodejs scanarios for sending cloud event and fix python ce handling
  components/function-runtimes/python39/kubeless/ce.py
  resources/serverless/values.yaml
  tests/function-controller/internal/assertion/cloud_events.go
  tests/function-controller/internal/resources/runtimes/nodejs.go
  tests/function-controller/internal/resources/runtimes/python.go
  tests/function-controller/internal/testsuite/cloud_events.go
Labels: size/M, lgtm

#18128 Update main picture
  docs/01-overview/assets/modular-kyma.png
  docs/assets/modular-kyma.png
Labels: size/XS, lgtm

#18104 Add markdown link check configs
  .github/workflows/daily-markdown-link-check.yaml
  .github/workflows/pr-markdown-link-check.yaml
  .mlc.config.json
Labels: area/documentation, area/quality, size/M, lgtm

#18103 Remove global.priorityClass from Application Connector charts
  resources/application-connector/charts/central-application-connectivity-validator/templates/deployment.yaml
  resources/application-connector/charts/central-application-connectivity-validator/templates/priority-class.yaml
  resources/application-connector/charts/central-application-connectivity-validator/values.yaml
  resources/application-connector/charts/central-application-gateway/templates/deployment.yaml
  resources/application-connector/charts/central-application-gateway/templates/priority-class.yaml
  resources/application-connector/charts/central-application-gateway/values.yaml
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/templates/priority-class.yaml
  resources/compass-runtime-agent/values.yaml
Labels: area/application-connector, size/M, lgtm

#18138 Disable Markdown Link Check for certain links
  README.md
  components/function-controller/README.md
  docs/01-overview/_sidebar.md
  docs/01-overview/observability/README.md
  docs/01-overview/observability/obsv-01-monitoring-in-kyma.md
  docs/02-get-started/01-quick-install.md
  docs/02-get-started/05-observability.md
  docs/03-tutorials/00-api-exposure/_sidebar.md
  docs/03-tutorials/_sidebar.md
  docs/04-operation-guides/operations/_sidebar.md
  docs/04-operation-guides/operations/evnt-01-eventing-dashboards.md
  docs/04-operation-guides/security/_sidebar.md
  docs/04-operation-guides/troubleshooting/_sidebar.md
  docs/04-operation-guides/troubleshooting/api-exposure/_sidebar.md
  docs/05-technical-reference/00-architecture/_sidebar.md
  docs/05-technical-reference/00-configuration-parameters/_sidebar.md
  docs/05-technical-reference/00-custom-resources/_sidebar.md
  docs/05-technical-reference/_sidebar.md
  docs/05-technical-reference/apix-01-config-authorizations-apigateway.md
  docs/_sidebar.md
  tests/components/application-connector/test/compass-runtime-agent/testkit/third_party/machinebox/graphql/README.md
  tests/perf/README.md
Labels: area/documentation, area/quality, size/M, lgtm

#18137 Add more logging output
  tests/function-controller/internal/assertion/cloud_events.go
Labels: size/XS, lgtm

#18136 Bump python image to use prod tag
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#18139 Change mlc schedule
  .github/workflows/daily-markdown-link-check.yaml
Labels: area/documentation, area/quality, size/XS, lgtm

#18142 Fix rendering on the website
  docs/04-operation-guides/operations/_sidebar.md
  docs/04-operation-guides/security/_sidebar.md
  docs/04-operation-guides/troubleshooting/_sidebar.md
  docs/05-technical-reference/00-custom-resources/_sidebar.md
Labels: size/S, lgtm

#18123 Clean up fast-integration api-exposure tests
  tests/fast-integration/api-exposure/fixtures/apirule-allow.yaml
  tests/fast-integration/api-exposure/fixtures/apirule-oauth.yaml
  tests/fast-integration/api-exposure/fixtures/httpbin.yaml
  tests/fast-integration/api-exposure/fixtures/index.js
  tests/fast-integration/api-exposure/fixtures/ns.yaml
  tests/fast-integration/api-exposure/index.js
  tests/fast-integration/certificate-test/certificte-test.js
  tests/fast-integration/certificate-test/readme.md
  tests/fast-integration/package.json
  tests/fast-integration/test/test.js
Labels: size/L, lgtm

#18100 Bump dependabot prs
  components/event-publisher-proxy/go.mod
  components/event-publisher-proxy/go.sum
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
  resources/eventing/values.yaml
Labels: size/M, lgtm

#18132 Remove not needed function from helm chart
  resources/serverless/templates/configmap.yaml
  resources/serverless/templates/deployment.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#18144 Fix a broken link
  docs/04-operation-guides/troubleshooting/api-exposure/_sidebar.md
Labels: size/XS, lgtm

#18146 Bump k8s-tools image in Kyma 2.18
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#18145 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: size/XS, lgtm

#18148 update modules table
  docs/README.md
Labels: size/XS, lgtm

#18150 Remove the guide "Pods stuck in `Pending/Failed/Unknown` state after an upgrade"
  docs/01-overview/api-exposure/README.md
  docs/01-overview/api-exposure/apix-02-useful-links.md
  docs/04-operation-guides/operations/README.md
  docs/04-operation-guides/operations/_sidebar.md
  docs/04-operation-guides/troubleshooting/README.md
  docs/04-operation-guides/troubleshooting/api-exposure/_sidebar.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-05-upgrade-sidecar-proxy.md
Labels: size/S, lgtm

#18151 Update quick installation for Telemetry module
  docs/02-get-started/08-install-uninstall-upgrade-kyma-module.md
Labels: size/XS, lgtm, docs/modularization, area/telemetry

#18156 Update Istio operator to 1.1.0
  resources/istio/Chart.yaml
  resources/istio/profile-evaluation.yaml
  resources/istio/profile-production.yaml
  resources/istio/templates/istio-manager-config.yaml
  resources/istio/templates/istio-operator.yaml
  resources/istio/values.yaml
Labels: size/L, lgtm

#18114 Remove profiles from webhook
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/hack/webhook_config.yaml
  components/function-controller/internal/controllers/serverless/function_reconcile_test.go
  components/function-controller/internal/webhook/defaulting_webhook_test.go
  components/function-controller/internal/webhook/webhook_config.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/zz_generated.deepcopy.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/templates/crds.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/L, lgtm

#18163 Remove replicas validation
  components/function-controller/cmd/webhook/main.go
  components/function-controller/config/crd/bases/serverless.kyma-project.io_functions.yaml
  components/function-controller/hack/webhook_config.yaml
  components/function-controller/internal/webhook/validating_webhook_test.go
  components/function-controller/internal/webhook/webhook_config.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_validation_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/zz_generated.deepcopy.go
  installation/resources/crds/serverless/crd-serverless.yaml
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/templates/crds.yaml
  resources/serverless/values.yaml
Labels: size/L, lgtm

#18153 Remove deprecated components
  docs/03-tutorials/00-security/sec-03-set-up-idp.md
  installation/resources/components.yaml
Labels: size/M, lgtm

#18158 Remove istio-resources from components list
  installation/resources/components.yaml
Labels: size/XS, lgtm

#18175 Make eventing-controller to not crash when nats is not present
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_unit_test.go
  components/eventing-controller/pkg/backend/jetstream/jetstream.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go
  resources/eventing/values.yaml
Labels: size/S, lgtm

#18180 Make eventing-controller to not crash when nats is not present
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_unit_test.go
  components/eventing-controller/pkg/backend/jetstream/jetstream.go
  components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go
Labels: area/eventing, size/S, lgtm

#18181 Image bump for make eventing-controller
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#18155 Change mTLS mode to `PERMISSIVE`
  resources/eventing/charts/controller/templates/peerauthentication.yaml
  resources/eventing/charts/controller/templates/service.yaml
Labels: size/XS, lgtm

#18184 Change BTP Operator's name to SAP BTP Operator
  docs/README.md
  docs/_sidebar.md
Labels: size/XS, lgtm

#18183 Trigger reconciliation every 30 seconds if failed to start NATS
  components/eventing-controller/controllers/backend/reconciler.go
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#18185 Cherry pick eventing for mTLS mode change and 30s reconciliation triggering
  components/eventing-controller/controllers/backend/reconciler.go
  resources/eventing/charts/controller/templates/peerauthentication.yaml
  resources/eventing/charts/controller/templates/service.yaml
Labels: size/XS, lgtm

#18186 Image bump for mTLS mode change and 30s reconciliation trigger
  resources/eventing/values.yaml
Labels: size/XS, lgtm

#18187 Update VERSION to 2.18.1
  VERSION
Labels: size/XS, lgtm

#18192 Exlclude Keda from legacy kyma component scanning mechanis
  CODEOWNERS
  resources/keda-manager/values.yaml
Labels: size/S, lgtm, kind/cleanup

#18162 Resolve resources in controller
  components/function-controller/README.md
  components/function-controller/cmd/manager/main.go
  components/function-controller/hack/controller.env
  components/function-controller/internal/controllers/serverless/build_resources_test.go
  components/function-controller/internal/controllers/serverless/config.go
  components/function-controller/internal/controllers/serverless/deployment.go
  components/function-controller/internal/controllers/serverless/fixtures_test.go
  components/function-controller/internal/controllers/serverless/system_state.go
  components/function-controller/internal/webhook/defaulting_webhook_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_types.go
  resources/serverless/templates/deployment.yaml
  resources/serverless/values.yaml
  tests/function-controller/internal/assertion/check.go
  tests/function-controller/internal/testsuite/api_gateway.go
  tests/function-controller/internal/testsuite/cloud_events.go
  tests/function-controller/internal/testsuite/gitauth.go
  tests/function-controller/internal/testsuite/gitops.go
  tests/function-controller/internal/testsuite/light_runtimes.go
  tests/function-controller/internal/testsuite/tracing.go
Labels: size/XL, lgtm

#18202 bump golang runtime
  components/function-controller/deploy/jobinit/Dockerfile
  components/function-controller/deploy/manager/Dockerfile
  components/function-controller/deploy/registry-gc/Dockerfile
  components/function-controller/deploy/webhook/Dockerfile
  resources/serverless/values.yaml
Labels: area/serverless, size/S, lgtm

#18200 Enable Webhook Auth by default
  components/eventing-controller/controllers/backend/reconciler_internal_integration_test.go
  components/eventing-controller/internal/featureflags/featureflags.go
  components/eventing-controller/pkg/backend/eventmesh/eventmesh_integration_test.go
Labels: size/XS, lgtm

#18164 Clean up defaulting webhook code
  components/function-controller/cmd/webhook/main.go
  components/function-controller/internal/webhook/defaulting_webhook.go
  components/function-controller/internal/webhook/defaulting_webhook_test.go
  components/function-controller/internal/webhook/webhook_config.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_defaults_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/function_resources_test.go
  components/function-controller/pkg/apis/serverless/v1alpha2/zz_generated.deepcopy.go
  resources/serverless/charts/webhook/values.yaml
  resources/serverless/values.yaml
Labels: size/XXL, lgtm

#18207 change Url to URL
  resources/serverless/templates/busola-serverless-extension.yaml
Labels: size/XS, lgtm

#18205 Remove PR images for release 2.19 in eventing
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#18152 APIRule v1alpha1 removal
  installation/resources/crds/api-gateway/apirules.gateway.crd.yaml
  resources/api-gateway/Chart.yaml
  resources/api-gateway/files/api-gateway-tests.sh
  resources/api-gateway/templates/deployment.yaml
  resources/api-gateway/templates/rbac.yaml
  resources/api-gateway/templates/webhook-certificates.yaml
  resources/api-gateway/templates/webhook-service.yaml
  resources/api-gateway/values.yaml
  tests/fast-integration/test/fixtures/commerce-mock/commerce-mock.yaml
  tests/fast-integration/test/fixtures/commerce-mock/index.js
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/index.js
  tests/fast-integration/test/fixtures/getting-started-guide/microservice.yaml
  tests/fast-integration/test/fixtures/getting-started-guide/xf-mocks.yaml
  tests/fast-integration/utils/index.js
  tests/perf/prerequisites/istio/apirule.yaml
  tests/perf/prerequisites/ory/apirules.yaml
Labels: area/api-gateway, size/L, lgtm

#18196 Add docs to 5xx
  components/central-application-gateway/README.md
  docs/05-technical-reference/ac-01-application-gateway-details.md
Labels: size/S, lgtm

#18211 Adjust docu to Kyma 2.19 release
  docs/01-overview/api-exposure/README.md
  docs/01-overview/api-exposure/apix-01-api-gateway.md
  docs/01-overview/api-exposure/apix-02-useful-links.md
  docs/03-tutorials/00-api-exposure/apix-03-set-up-tls-gateway.md
  docs/04-operation-guides/operations/03-change-kyma-config-values.md
  docs/04-operation-guides/security/README.md
  docs/04-operation-guides/security/_sidebar.md
  docs/04-operation-guides/security/assets/security-overview.svg
  docs/04-operation-guides/security/sec-01-authentication-in-kyma.md
  docs/04-operation-guides/security/sec-02-authorization-in-kyma.md
  docs/04-operation-guides/security/sec-05-customization-operation.md
  docs/04-operation-guides/security/sec-07-useful-links.md
  docs/04-operation-guides/troubleshooting/README.md
  docs/04-operation-guides/troubleshooting/api-exposure/_sidebar.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-01-cannot-connect-to-service/apix-01-01-apigateway-connect-api-rule.md
  docs/04-operation-guides/troubleshooting/api-exposure/apix-01-cannot-connect-to-service/apix-01-02-401-unauthorized-403-forbidden.md
  docs/05-technical-reference/00-architecture/README.md
  docs/05-technical-reference/00-architecture/_sidebar.md
  docs/05-technical-reference/00-architecture/apix-01-architecture-apigateway.md
  docs/05-technical-reference/00-configuration-parameters/_sidebar.md
  docs/05-technical-reference/00-configuration-parameters/apix-01-ory-limitations.md
  docs/05-technical-reference/00-configuration-parameters/apix-02-ory-chart.md
  docs/05-technical-reference/00-configuration-parameters/sec-01-cluster-users.md
  resources/cluster-essentials/README.md
  resources/cluster-users/README.md
  resources/istio-resources/README.md
Labels: size/L, lgtm

#18215 Fix CVE-2023-29409 in Application Connetor
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
  tests/components/application-connector/Dockerfile.compass-runtime-agent
  tests/components/application-connector/Dockerfile.connectivity-validator
  tests/components/application-connector/Dockerfile.gateway
  tests/components/application-connector/Dockerfile.mockapp
Labels: area/application-connector, size/S, lgtm

#18214 Fix CVE-2023-29409 in App Connector
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/Dockerfile.compass-runtime-agent
  tests/components/application-connector/Dockerfile.connectivity-validator
  tests/components/application-connector/Dockerfile.gateway
  tests/components/application-connector/Dockerfile.mockapp
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/M, lgtm

#18218 Bumps application-connector images
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/S, lgtm, kind/chore

#18219 Bumps images for 2.18 app conn security
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/S, lgtm, kind/chore

#18220 omit creating oauth2client when eventing-webhook-auth is enabled
  resources/eventing/charts/controller/templates/oauth2-client.yaml
Labels: area/eventing, size/XS, lgtm

#18223 Adjust documentation to APIRule `v1alpha1` removal
  docs/05-technical-reference/00-custom-resources/apix-01-apirule.md
Labels: size/M, lgtm

#18206 Bump k8s-tools image
  docs/04-operation-guides/operations/10-backup-kyma.md
  resources/ory/values.yaml
  resources/serverless/values.yaml
Labels: area/serverless, size/XS, lgtm, kind/chore

#18222 Update oauth2-proxy to 7.5.1
  resources/monitoring/values.yaml
Labels: area/monitoring, lgtm

#18209 Configure ORY Oathkeeper oauth2 default endpoints
  installation/resources/crds/ory/oauth2clients.crd.yaml
  resources/ory/values.yaml
  tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml
Labels: area/api-gateway, size/L, lgtm, kind/cleanup

#18221 updates app-connector components golang version to 1.21.1
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/Dockerfile.compass-runtime-agent
  tests/components/application-connector/Dockerfile.connectivity-validator
  tests/components/application-connector/Dockerfile.gateway
  tests/components/application-connector/Dockerfile.mockapp
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/M, lgtm, kind/chore

#18227 bumps the app-con images with 1.21.1 golang bump
  resources/application-connector/values.yaml
  resources/compass-runtime-agent/values.yaml
  tests/components/application-connector/resources/charts/application-connectivity-validator-test/values.yaml
  tests/components/application-connector/resources/charts/compass-runtime-agent-test/values.yaml
  tests/components/application-connector/resources/charts/gateway-test/values.yaml
Labels: area/application-connector, size/S, lgtm, kind/chore

#18229 bump serverless images before v2.19
  resources/serverless/values.yaml
Labels: area/serverless, size/S, lgtm, kind/chore

#18234 Remove PR image for release 2.19 in publisher-proxy.
  resources/eventing/values.yaml
Labels: area/eventing, size/XS, lgtm

#18228 Remove istio components from compass runtime agent charts
  resources/compass-runtime-agent/templates/service.yaml
  resources/compass-runtime-agent/templates/virtualservice.yaml
Labels: size/M, lgtm

#18238 Move note about modules
  docs/04-operation-guides/operations/02-install-kyma.md
Labels: area/documentation, size/XS, lgtm

#18240 Setup envtests in CRA
  components/compass-runtime-agent/Makefile
Labels: size/S, lgtm

#18199 Remove obsolete director proxy from compass runtime agent
  components/compass-runtime-agent/README.md
  components/compass-runtime-agent/cmd/main.go
  components/compass-runtime-agent/cmd/options.go
  components/compass-runtime-agent/internal/compass/director/mocks/ProxyConfigurator.go
  components/compass-runtime-agent/internal/compass/director/proxy.go
  components/compass-runtime-agent/internal/compass/director/proxy_test.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  docs/05-technical-reference/assets/api-credentials-flow.svg
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/templates/director-proxy-service.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/L, lgtm

#18247 small fixes in docs
  docs/02-get-started/04-trigger-workload-with-event.md
  docs/02-get-started/_sidebar.md
Labels: size/XS, lgtm

#18251 Change serverless component to module
  docs/README.md
Labels: size/XS, lgtm

#18250 Upgrade controller-runtime to 0.15.2
  components/eventing-controller/api/v1alpha2/subscription_webhook.go
  components/eventing-controller/api/v1alpha2/subscription_webhook_unit_test.go
  components/eventing-controller/controllers/backend/reconciler.go
  components/eventing-controller/controllers/subscription/eventmesh/reconciler.go
  components/eventing-controller/controllers/subscription/eventmesh/reconciler_internal_integration_test.go
  components/eventing-controller/controllers/subscription/eventmesh/testwithory/utils.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler.go
  components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_unit_test.go
  components/eventing-controller/go.mod
  components/eventing-controller/go.sum
Labels: size/XL, lgtm
