Repository kyma-project/kyma, pull requests merged in 2024-06, with the labels that each got.

#18705 Fix edit on GitHub for release branches
  docs/index.html
Labels: size/XS, lgtm, cla: yes

#18706 docs: Update Quick Install
  docs/02-get-started/01-quick-install.md
Labels: size/XS, lgtm, cla: yes

#18722 Delete .github/workflows/github-release.yaml
  .github/workflows/github-release.yaml
Labels: size/M, lgtm, cla: yes

#18721 Remove app con lint
  .github/workflows/lint-central-application-gateway.yml
Labels: size/S, lgtm, cla: yes
