Repository kyma-project/kyma, pull requests merged in 2024-10, with the labels that each got.

#18756 Fix broken link
  common/makefiles/docs/generic-make-go.md
Labels: size/XS, lgtm, cla: yes

#18749 Update Quick Install guide
  docs/02-get-started/01-quick-install.md
Labels: size/S, lgtm, cla: yes

#18757 Update modules' order in sidebar
  docs/_sidebar.md
Labels: area/documentation, size/S, lgtm, cla: yes

#18758 Changed modules' order in README.md
  docs/06-modules/README.md
Labels: size/S, lgtm, cla: yes

#18759 Fix link in Quick Install
  docs/02-get-started/01-quick-install.md
Labels: size/XS, lgtm, cla: yes
