Repository kyma-project/kyma, pull requests merged in 2024-09, with the labels that each got.

#18742 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, lgtm, cla: yes

#18745 Add missing mandatory section to README
  README.md
Labels: area/documentation, size/XS, lgtm, cla: yes

#18748 Update a link
  docs/02-get-started/01-quick-install.md
Labels: area/documentation, size/XS, lgtm, kind/chore, cla: yes

#18750 Add Docker Registry to the website
  docs/06-modules/README.md
  docs/_sidebar.md
  docs/index.html
Labels: size/XS, lgtm, cla: yes

#18754 Disable link checker for Docker Registry
  docs/06-modules/README.md
Labels: size/XS, lgtm, cla: yes

#18755 Search with indexing nested sidebars
  docs/index.html
  docs/search/component.js
  docs/search/index.js
  docs/search/search.js
Labels: size/XL, lgtm, cla: yes
