Repository kyma-project/kyma, pull requests merged in 2024-03, with the labels that each got.

#18595 Fix the link to Kyma Slack channels
  README.md
  docs/04-operation-guides/troubleshooting/README.md
  docs/04-operation-guides/troubleshooting/security/README.md
  docs/support-contribution.md
Labels: area/documentation, size/XS, lgtm, kind/chore, cla: yes

#18596 Add missing artifacts for reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, lgtm, cla: yes

#18597 Removed empty tools folder
  README.md
  tools/README.md
Labels: size/S, lgtm, cla: yes

#18603 Support other version semantic in Compass Runtime Agnet tests
  tests/components/application-connector/go.mod
  tests/components/application-connector/go.sum
  tests/components/application-connector/test/compass-runtime-agent/testkit/director/queryprovider.go
Labels: area/application-connector, size/L, lgtm, cla: yes

#18622 Switch to md-check-link
  .github/workflows/lint-markdown-links-daily.yml
  .github/workflows/lint-markdown-links-pr.yml
  .github/workflows/pr-docu-checks.yml
Labels: area/documentation, size/M, lgtm, cla: yes

#18625 Favicon icon config update
  docs/index.html
Labels: size/XS, lgtm, cla: yes

#18621 Apply markdowlint rules in the kyma repository
  .markdownlint.yaml
  .markdownlintignore
  CODEOWNERS
  docs/01-overview/application-connectivity/README.md
  docs/01-overview/application-connectivity/ra-01-runtime-agent-overview.md
  docs/01-overview/application-connectivity/ra-02-useful-links.md
  docs/01-overview/ui/README.md
  docs/02-get-started/01-quick-install.md
  docs/02-get-started/08-uninstall-upgrade-kyma-module.md
  docs/03-tutorials/00-application-connectivity/ra-01-establish-secure-connection-with-compass.md
  docs/03-tutorials/00-application-connectivity/ra-02-maintain-secure-connection-with-compass.md
  docs/03-tutorials/00-application-connectivity/ra-03-revoke-client-certificate.md
  docs/03-tutorials/00-application-connectivity/ra-04-configure-runtime-agent-with-compass.md
  docs/03-tutorials/00-observability.md
  docs/03-tutorials/README.md
  docs/04-operation-guides/security/README.md
  docs/04-operation-guides/security/sec-01-authentication-in-kyma.md
  docs/04-operation-guides/security/sec-02-authorization-in-kyma.md
  docs/04-operation-guides/security/sec-03-access-kyma.md
  docs/04-operation-guides/troubleshooting/01-component-installation-fails.md
  docs/04-operation-guides/troubleshooting/01-deplyoment-fails-pending-pods.md
  docs/04-operation-guides/troubleshooting/01-k3d-fails-on-linux.md
  docs/04-operation-guides/troubleshooting/01-kyma-domain-unresolvable.md
  docs/05-technical-reference/00-api-overview/README.md
  docs/05-technical-reference/00-architecture/README.md
  docs/05-technical-reference/00-architecture/ra-01-runtime-agent-workflow.md
  docs/05-technical-reference/00-configuration-parameters/ra-01-connection-with-compass.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/ra-01-compassconnection.md
  docs/05-technical-reference/ra-01-configuring-runtime.md
  docs/README.md
  docs/glossary.md
  docs/migration-guide-2.19-2.20.md
  docs/release-notes.md
  docs/support-contribution.md
  markdown_heading_capitalization.js
Labels: size/L, lgtm, cla: yes

#18580 Update codeowners to align with responsibility changes.
  CODEOWNERS
Labels: size/XS, lgtm, cla: yes

#18624 Remove Runtime Agent docs
  docs/01-overview/application-connectivity/README.md
  docs/01-overview/application-connectivity/metadata.yaml
  docs/01-overview/application-connectivity/ra-01-runtime-agent-overview.md
  docs/01-overview/application-connectivity/ra-02-useful-links.md
  docs/03-tutorials/00-application-connectivity/README.md
  docs/03-tutorials/00-application-connectivity/metadata.yaml
  docs/03-tutorials/00-application-connectivity/ra-01-establish-secure-connection-with-compass.md
  docs/03-tutorials/00-application-connectivity/ra-02-maintain-secure-connection-with-compass.md
  docs/03-tutorials/00-application-connectivity/ra-03-revoke-client-certificate.md
  docs/03-tutorials/00-application-connectivity/ra-04-configure-runtime-agent-with-compass.md
  docs/03-tutorials/00-application-connectivity/ra-05-reconnect-runtime-agent-with-compass.md
  docs/03-tutorials/README.md
  docs/05-technical-reference/00-architecture/README.md
  docs/05-technical-reference/00-architecture/ra-01-runtime-agent-workflow.md
  docs/05-technical-reference/00-configuration-parameters/ra-01-connection-with-compass.md
  docs/05-technical-reference/00-custom-resources/README.md
  docs/05-technical-reference/00-custom-resources/ra-01-compassconnection.md
  docs/05-technical-reference/ra-01-configuring-runtime.md
  docs/_sidebar.md
Labels: size/XL, lgtm, cla: yes

#18627 fix: Remove new lines from generated CRD description
  hack/table-gen/main.go
Labels: size/XS, lgtm, cla: yes

#18629 Fix link in the application gateway readme
  .github/workflows/lint-central-application-gateway.yml
  components/central-application-gateway/README.md
Labels: size/XS, lgtm, cla: yes

#18606 Remove compass-runtime-agent from kyma resources
  docs/05-technical-reference/00-custom-resources/README.md
  installation/resources/crds/compass-runtime-agent/applications.applicationconnector.crd.yaml
  installation/resources/crds/compass-runtime-agent/compass-connection.crd.yaml
  resources/compass-runtime-agent/.helmignore
  resources/compass-runtime-agent/Chart.yaml
  resources/compass-runtime-agent/templates/_helpers.tpl
  resources/compass-runtime-agent/templates/cluster-role-binding.yaml
  resources/compass-runtime-agent/templates/deployment.yaml
  resources/compass-runtime-agent/templates/priority-class.yaml
  resources/compass-runtime-agent/templates/resources-role-binding.yaml
  resources/compass-runtime-agent/templates/role-binding.yaml
  resources/compass-runtime-agent/templates/service-account.yaml
  resources/compass-runtime-agent/templates/service.yaml
  resources/compass-runtime-agent/templates/skr-configmap.yaml
  resources/compass-runtime-agent/values.yaml
Labels: size/XL, lgtm, cla: yes

#18630 Docs clean-up after Runtime Agent's docs removal
  .mlc.config.json
  docs/03-tutorials/00-observability.md
  docs/03-tutorials/README.md
  docs/04-operation-guides/security/README.md
  docs/04-operation-guides/security/_sidebar1.md
  docs/04-operation-guides/security/metadata.yaml
  docs/04-operation-guides/troubleshooting/metadata.yaml
  docs/04-operation-guides/troubleshooting/security/_sidebar.md
  docs/04-operation-guides/troubleshooting/security/metadata.yaml
  docs/05-technical-reference/00-architecture/metadata.yaml
  docs/05-technical-reference/00-configuration-parameters/metadata.yaml
  docs/05-technical-reference/00-custom-resources/metadata.yaml
  docs/05-technical-reference/metadata.yaml
  docs/_sidebar.md
  docs/glossary.md
Labels: area/documentation, size/M, lgtm, docs/modularization, cla: yes
