Repository kyma-project/kyma, pull requests merged in 2024-02, with the labels that each got.

#18559 Update website style sheet
  docs/assets/theme-custom.css
  docs/index.html
Labels: size/M, lgtm, cla: yes

#18566 Fix vulnerability in runc
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
Labels: size/M, lgtm, cla: yes

#18582 docs: It's IN a cluster not ON a cluster
  docs/04-operation-guides/operations/10-backup-kyma.md
  docs/04-operation-guides/troubleshooting/security/sec-01-certificates-gardener.md
  docs/glossary.md
  tests/components/application-connector/docs/application-connectivity-validator-tests.md
  tests/components/application-connector/docs/application-gateway-tests.md
  tests/components/application-connector/docs/compass-runtime-agent-tests.md
Labels: size/S, lgtm, cla: yes

#18579 Fix linter issues in CRA
  components/compass-runtime-agent/internal/certificates/migrator_test.go
  components/compass-runtime-agent/internal/compass/director/client_test.go
  components/compass-runtime-agent/internal/compass/director/converter.go
  components/compass-runtime-agent/internal/compass/director/query.go
  components/compass-runtime-agent/internal/compassconnection/controller.go
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/compassconnection/supervisor.go
  components/compass-runtime-agent/internal/metrics/logger.go
  components/compass-runtime-agent/internal/secrets/repository.go
  components/compass-runtime-agent/internal/testutil/testutil.go
Labels: size/M, lgtm, cla: yes

#18584 Disable link checker for the Stack Overflow page
  docs/support-contribution.md
Labels: size/XS, lgtm, cla: yes

#18589 Update icon link
  docs/index.html
Labels: size/XS, lgtm, cla: yes

#18590 Favicon icon update
  docs/index.html
Labels: size/XS, lgtm, cla: yes
