Repository kyma-project/kyma, pull requests merged in 2025-02, with the labels that each got.

#18778 Remove prow team from CODEOWNERS
  .github/dependabot.yml
  .github/package.json
  CODEOWNERS
  VERSION
Labels: size/L, lgtm, cla: yes

#18779 Change caution to warning
  docs/02-get-started/01-quick-install.md
  docs/06-modules/README.md
  docs/README.md
Labels: size/XS, lgtm, cla: yes

#18781 Update the list of release pages
  docs/release-notes.md
Labels: area/documentation, size/XS, lgtm, cla: yes

#18782 Add Kyma CLI to website
  docs/01-overview/ui/README.md
  docs/_sidebar.md
  docs/index.html
Labels: size/M, lgtm, cla: yes
